### ISSUE TITLE
gb2015正文中引用文献的括号应为中文的，目前均为英文括号

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#1]
使用这个版本时发现的:
china-national-standard-gb-t-7714-2015-author-date-aulower-bilan.csl china-national-standard-gb-t-7714-2015-author-date的修改版，网友牛耕田分享，Raymond修改，作者为首字母大写，支持中文作者超过3个为“等”，英文为“et al”。

可以仔细对比gb2015的参考原文，另外上述文件会自动输出dol，中文文献主流还是不带doi,另出一个新版更好

**Comment by redleafnew** [comment]
你的要求是：1.正文中括号为中文括号2. 不带DOI和URL，是这样吗？如果是我按这个要求再修改一下。

**Comment by fredericky123** [comment]
作者是第一个字母大写，其余小写

**Comment by fredericky123** [comment]
非常感谢及时回复！

**Comment by fredericky123** [comment]
补充：作者是姓的首字母大写，姓的其余字母小写；名均用缩写，大写的形式

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/gb-t-7714-2015-author-date-aulower-bilan-nodoi.csl 麻烦你测试一下，另外再看一下文献的题目，现在设置的是每个单词首字母大写，但我的显示是第一个单词和最后一个单词大写，不知道是我Word的问题还是怎么回事。

**Comment by fredericky123** [comment]
我的显示正常，但是悬挂缩进应该是两个汉字字符或四个字符，我这悬挂缩进了3个汉字字符

**Comment by fredericky123** [comment]
参考文献表用五号字，汉字用宋体，英文用 Times New Roman 体，行距采 用固定值 16 磅，段前 3 磅，段后 0 磅。采用悬挂格式，悬挂缩进 2 个汉字符或 4 个字符。

麻烦问一下，这里的需求能设置好吗？

**Comment by redleafnew** [comment]
更新了另一个悬挂的选项，你再试试。
字体这些设置只能Word中设置。我的Readme中有个帖子https://zhuanlan.zhihu.com/p/58969571。

**Comment by fredericky123** [comment]
直接报错唉

**Comment by fredericky123** [comment]
上述帖子404le

**Comment by redleafnew** [comment]
[https://zhuanlan.zhihu.com/p/58969571](https://zhuanlan.zhihu.com/p/58969571)。链接自动多了个句号。

**Comment by fredericky123** [comment]
大赞！感谢，就差悬挂缩进的问题了。

**Comment by redleafnew** [comment]
悬挂也只能通过word设置了，csl中的选项好像不行发自我的华为手机-------- 原始邮件 --------发件人： fredericky123 <notifications@github.com>日期： 2021年1月3日周日 12:07收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl <Chinese-STD-GB-T-7714-related-csl@noreply.github.com>抄送： redleafnew <redleafnew@163.com>, Comment <comment@noreply.github.com>主    题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)

大赞！感谢，就差悬挂缩进的问题了。

**Comment by fredericky123** [comment]
好的，目前只能这样了，不过word通过书目设置悬挂缩进2字符并不起作用，只能单独通过段落设置，而一刷新又回去了
要不要去官方论坛询问询问
感觉6字符改为4字符，可能在某个地方的设置

**Comment by redleafnew** [comment]
好的，知道了就可以修改csl了。辛苦处理发个帖子去吧。

**Comment by fredericky123** [comment]
"csl设置的是Title格式，但在我的Word中显示只是第一个单词和最后一个单词首字母大写"
我才发现和你的一样
能修改为和title字段一样的显示吗
这样就可以自己在title字段修改了

**Comment by redleafnew** [comment]
修改为用zotero中的大小写了

**Comment by fredericky123** [comment]
论坛里说改不了，只能通过修改word里的Bibliography修改

**Comment by redleafnew** [comment]
那没有办法了，在Word中修改吧。

**Comment by fredericky123** [comment]
为什么我在word里在“书目”的基础上新建一个样式，一刷新，样式又变为Bibliography了

**Comment by redleafnew** [comment]
在那个知乎帖子上讨论吧。

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/103494756-1eceb180-4e73-11eb-8051-4443bca578c9.png)
为什么有的文献在正文中插入的时候，会是作者姓加名字缩写的形式，而有些是正常的，仅有姓
该如何解决哈

示例文献：Social Capital at the Top: Effects of Social Similarity and Status on CEO Compensation

**Comment by redleafnew** [comment]
加名字的应该是分不清的文献，例如张大，2019和张二，2019如果缩写都是张，2019，分不清了，所以添加了名，这是csl文件规定的。当然也可以用添加a，b的方式。
https://docs.citationstyles.org/en/stable/specification.html#disambiguation这上有详细说明。



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 09:58
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)

为什么有的文献在正文中插入的时候，会是作者姓加名字缩写的形式，而有些是正常的，仅有姓
该如何解决哈
示例文献：Social Capital at the Top: Effects of Social Similarity and Status on CEO Compensation

**Comment by fredericky123** [comment]
在我的文献库里，关于（Belliveau M A et al., 1996)的文献有且只有一个，所以还是很奇怪

**Comment by fredericky123** [comment]
也就是不存在作者姓缩写和年份导致不能精准定位的问题

**Comment by redleafnew** [comment]
完整的题录或下载地址给我一下



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 10:13
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)
也就是不存在作者姓缩写和年份导致不能精准定位的问题

**Comment by fredericky123** [comment]
https://pubsonline.informs.org/doi/abs/10.1287/orsc.2019.1322
https://journals.aom.org/doi/abs/10.5465/257069
这两篇文章都遇到相同的问题

**Comment by redleafnew** [comment]
你新建一个word只放这一个文献看看正常吗？
我这试着是正常的。



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 10:26
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)
https://pubsonline.informs.org/doi/abs/10.1287/orsc.2019.1322
https://journals.aom.org/doi/abs/10.5465/257069
这两篇文章都遇到相同的问题

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/103497812-9c97ba80-4e7d-11eb-8b6f-6ff84c67f65d.png)
我新建一个word也是这样的

**Comment by fredericky123** [comment]
换成apa6就是正常的，就是在这个styles下显示的不对

**Comment by redleafnew** [comment]
https://editor.citationstyles.org/visualEditor/你将style上传到这上试试



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 11:12
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)

我新建一个word也是这样的

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/103498506-05803200-4e80-11eb-9ecc-675177e766f7.png)
这里好像也会出现名的缩写

**Comment by fredericky123** [comment]
china-national-standard-gb-t-7714-2015-author-date-chinese-aulower-bilan-nodoi.csl

**Comment by redleafnew** [comment]
修改文献语言了吗？



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 11:29
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)

这里好像也会出现名的缩写

**Comment by fredericky123** [comment]
语言是默认的英文，还用改吗？
那个网址的示例文献里复现了那个问题，需要改他的语言吗

**Comment by redleafnew** [comment]
修改为en试试



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 11:42
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)
语言是默认的英文，还用改吗？
那个网址的示例文献里复现了那个问题，需要改他的语言吗

**Comment by fredericky123** [comment]
修改为en只是把和变成了&
![image](https://user-images.githubusercontent.com/13982749/103499719-0dda6c00-4e84-11eb-825b-4a1cece516b4.png)

**Comment by redleafnew** [comment]
下午QQ远程看一下。1361942015发自我的华为手机-------- 原始邮件 --------发件人： fredericky123 <notifications@github.com>日期： 2021年1月4日周一 11:57收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl <Chinese-STD-GB-T-7714-related-csl@noreply.github.com>抄送： redleafnew <redleafnew@163.com>, State change <state_change@noreply.github.com>主    题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)

修改为en只是把和变成了&

**Comment by fredericky123** [comment]
你把https://raw.githubusercontent.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/main/gb-t-7714-2015-author-date-aulower-bilan-nodoi.csl
上传到visual editor不能复现吗？只有我在本地有问题么，我看上传上去也能复现

**Comment by redleafnew** [comment]
线上也是正常的。用附件的格式试试。上传到线上，或导入到z中



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-01-04 12:11
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; State change
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] gb2015正文中引用文献的括号应为中文的，目前均为英文括号 (#1)
你把https://raw.githubusercontent.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/main/gb-t-7714-2015-author-date-aulower-bilan-nodoi.csl
上传到visual editor不能复现吗？只有我在本地有问题么，我看上传上去也能复现

**Comment by fredericky123** [comment]
这也太神奇了吧 
线上都不一样，系统原因么
