### ISSUE TITLE
china-national-standard-gb-t-7714-2015-author-date-aulower-bilan.csl 去掉和前面的， 

### ISSUE THREAD

**Issue by Sunny-27** [redleafnew/Chinese-STD-GB-T-7714-related-csl#10]
适应我校毕业论文文献要求格式，我根据china-national-standard-gb-t-7714-2015-author-date-aulower-bilan.c修改了一版csl，但在可视化csl修改网站上已经去掉了两名中文作者之间的逗号和空格，但是下载到zotero，还是无法去掉和前面的逗号和空格，另外能否将&替换成et？不能的话也没有关系，最后可以使用word批量替换。
[gb-t-7714-2015-author-date-aulower-bilan-ynu-date-symbol (1).zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7317575/gb-t-7714-2015-author-date-aulower-bilan-ynu-date-symbol.1.zip)
[文献示例.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7317579/default.zip)

**Comment by Sunny-27** [comment]
> ＆是指文末参考文献列表中的吗？

指文中引用两个英文作者出现的（A&B，1990）

**Comment by redleafnew** [comment]
https://docs.citationstyles.org/en/stable/specification.html没提，我在论坛上问一下。

**Comment by Sunny-27** [comment]
> 哪个学校的style要求，有网页要求吗
[文献格式.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7319135/default.docx)

有倒是有，但是并没有明确写明作者编年制的文中引用格式，我们学科常用的文中引用格式为：
（李星学等, 1962; 斯行健和李星学, 1963; Poliansky et al., 1975; Barnard et Miller, 1976; Иминов, 1976; 李佩娟等, 1976）
两个中文作者中间只有和字，两个英文作者中间用et

**Comment by redleafnew** [comment]
“和”前面的逗号修改了一下，你更新试试。

**Comment by Sunny-27** [comment]
> “和”前面的逗号修改了一下，你更新试试。

去哪里更新？

**Comment by Sunny-27** [comment]
> > > “和”前面的逗号修改了一下，你更新试试。
> > 
> > 
> > 去哪里更新？
> 
> 找到了，感谢！

新的这版引用的括号为英文的(),我在网站上改为中文的（）显示错误
![image](https://user-images.githubusercontent.com/69256654/136731065-4f51ce9f-a0a1-46f3-af0c-e7a2002a64cb.png)
我从你的新版基础上还改了，一些东西，能从我这版上改括号为中文括号么？
[china-national-standard-gb-t-7714-2015-author-date-chinese-ynu (1).zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7319445/china-national-standard-gb-t-7714-2015-author-date-chinese-ynu.1.zip)

**Comment by redleafnew** [comment]
> > “和”前面的逗号修改了一下，你更新试试。
> 
> 新的这版引用的括号为英文的(),我在网站上改为中文的（）显示错误 我从你的新版基础上还改了，一些东西，能从我这版上改括号为中文括号么？ [china-national-standard-gb-t-7714-2015-author-date-chinese-ynu (1).zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7319445/china-national-standard-gb-t-7714-2015-author-date-chinese-ynu.1.zip) ![image](https://user-images.githubusercontent.com/69256654/136731065-4f51ce9f-a0a1-46f3-af0c-e7a2002a64cb.png)

文内引用的前后括号吗？

**Comment by redleafnew** [comment]
> > [china-national-standard-gb-t-7714-2015-author-date-chinese-ynu (1).zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/7321618/china-national-standard-gb-t-7714-2015-author-date-chinese-ynu.1.zip) 试一下呢
> 
> 显示出错不能加载

将原来csl的删除

**Comment by redleafnew** [comment]
试一下https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/13gb-t-7714-2015-author-date-ynu.csl，如果没有问题了，我就关闭这个issue了。

**Comment by Sunny-27** [comment]
> 欢迎推荐软件

> 欢迎推荐软件，推荐这个地址，欢迎加星。

好的！
