### ISSUE TITLE
引用多个参考文献时，标号顺序没有按照从小到大排列

### ISSUE THREAD

**Issue by havanoname** [redleafnew/Chinese-STD-GB-T-7714-related-csl#100]
**引用多个参考文献时，标号顺序没有按照从小到大排列**

我不确定这是个bug还是我选的样式不对，但是很早之前我下载的样式：

China National Standard GB/T 7714-2015-numeric-AuLower-BiLan-noDOI

是不存在这个问题的。

尝试了一些样式都有这个问题
CSL 样式：

000gb-t-7714-2015-numeric-bilingual.csl

002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl

添加多个参考文献时，标号的顺序是按照个人添加的顺序排列，而不是按标号从小到大排列

**屏幕截图**

000gb-t-7714-2015-numeric-bilingual.csl

在该样式下，引用多篇参考文献时，标号是按照自己添加的顺序插入的，并不会按从小到大排列

![image](https://user-images.githubusercontent.com/42195455/204780162-31a04301-5f50-45ad-bcb4-ffa17bb6566b.png)

![image](https://user-images.githubusercontent.com/42195455/204773489-289943f9-fb1d-4c10-ba09-9101aac2886a.png)
---

对比：以前的china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-noDOI

在该样式下，多了一个“保持原分类”选项，勾选这个就会自动按照从小到大的顺序排列

![image](https://user-images.githubusercontent.com/42195455/204780652-aa6205d8-2d29-4554-a3f8-777d6ff6fc9f.png)

![image](https://user-images.githubusercontent.com/42195455/204773333-374840ac-3be3-4b95-b658-18d2197496a5.png)

**其他相关信息**

进一步尝试了一下，似乎带有*BiLan*关键词的样式才有“保持原分类”这个功能：

013gb-t-7714-2015-numeric-aulower-bilan-ce.csl

014gb-t-7714-2015-numeric-auup-bilan-ce.csl

但是主页中似乎没有提及这一点，建议添加一个说明，如果能给其他样式也加上这个功能就更好了

**Comment by zepinglee** [comment]
<img width="697" alt="Screen Shot 2022-11-30 at 19 16 53" src="https://user-images.githubusercontent.com/12290822/204782987-880fe88d-6366-4e84-b9bb-76a54e84c532.png">

国标的这个示例中，同一个 citation 内部的序号不一定要按升序，所以我在重制 000～011 这些样式时没有在 citation 内进行排序。这也是为了方便需要手动指定文献顺序的情况（比如按照重要性或者时间顺序）。

> 对比：以前的china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-noDOI
在该样式下，多了一个“保持原分类”选项，勾选这个就会自动按照从小到大的顺序排列

这里“保持原分类”的翻译有误，英文界面是“Keep Sources Sorted”，可以翻译为“保持文献排序”。

我第一次注意到这个选项。既然关掉排序比启用排序对于普通用户更简单，我觉得可以将这个排序的功能加回来。@redleafnew 意见怎样？

相关代码：
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/fbf4182a6d06dfb88940434adfbc4c7be48cc11d/013gb-t-7714-2015-numeric-aulower-bilan-ce.csl#L237-L239

**Comment by redleafnew** [comment]
我觉得可以加回来，大部分人还是按升序来排列的。

**Comment by zepinglee** [comment]
另外著者-出版年制的引注有必要排序吗？

**Comment by redleafnew** [comment]
国标如果没有要求，我觉得可以按APA规则。

**Comment by zepinglee** [comment]
国标没有规定“著者-出版年制”的同一处引用多篇文献的情况，甚至连示例也没有。

APA 是按照著者、出版年排序的：<https://github.com/citation-style-language/styles/blob/bef74edfec3b468e939d5b5e5eb15c888678c759/apa.csl#L1865-L1870>
```xml
    <sort>
      <key macro="author-bib" names-min="3" names-use-first="1"/>
      <key macro="date-sort-group"/>
      <key macro="date-sort-date" sort="ascending"/>
      <key variable="status"/>
    </sort>
```

不过我感觉 author-year 式的用户更倾向于自己控制顺序，Zotero 的论坛也有很多问 APA 的顺序。

**Comment by zepinglee** [comment]
在 a2c4d2b 中只对 numeric 样式添加了引注中序号的排序，顺便修正了几处 `citation-format`（ 1f4cbfc ）。

**Comment by redleafnew** [comment]
我修改了，谢谢。

**Comment by redleafnew** [comment]
> 将更新时间统一修改为上次的提交时间
>  [main](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl)

@zepinglee 这个是通过什么程序修改的。

**Comment by zepinglee** [comment]
> > 将更新时间统一修改为上次的提交时间
> > [main](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl)
> 
> @zepinglee 这个是通过什么程序修改的。

我写了一个 Python 脚本。

```python
import datetime
import glob
import os
import re


for file in sorted(glob.glob('*.csl')):
    last_diff = os.popen(f'git log -1 -p "{file}"').read()
    if re.search(r'-\s+<updated>', last_diff):
        # 上次 commit 修改了时间
        # print(last_diff)
        continue

    commit_date = os.popen(f'git log -1 --pretty="format:%cI" "{file}"').read()
    commit_date = datetime.datetime.fromisoformat(commit_date)
    # print(commit_date)

    with open(file) as f:
        csl_content = f.read()
    update_date = re.search(r'<updated>(.*?)</updated>', csl_content)
    if not update_date:
        raise ValueError
    update_date = update_date.group(1)
    update_date = datetime.datetime.fromisoformat(update_date)

    delta = commit_date - update_date

    if delta > datetime.timedelta(days=1):
        print(file)
        print(update_date.isoformat())
        print(commit_date.isoformat())
        new_content = re.sub(r'<updated>(.*?)</updated>', '<updated>' + commit_date.isoformat() + '</updated>' , csl_content)
        with open(file, 'w') as f:
            f.write(new_content)
```

**Comment by havanoname** [comment]
谢谢两位大佬！

**Comment by redleafnew** [comment]
太厉害了，学过一段时间py，后来还是没有用下去。
