### ISSUE TITLE
403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序

### ISSUE THREAD

**Issue by ssieub** [redleafnew/Chinese-STD-GB-T-7714-related-csl#101]
**描述错误**

CSL 样式：xxx-xxx-xxx.csl

清晰简洁地描述错误是什么，预期的结果是什么。
语言已经修改但排序错误

**屏幕截图**
![图片](https://user-images.githubusercontent.com/107407348/205087221-ae606c10-9d2e-4976-bb76-a352d0809388.png)
![图片](https://user-images.githubusercontent.com/107407348/205087263-c7dc95a0-0a63-4c71-92f3-c669e0b2f2eb.png)
![图片](https://user-images.githubusercontent.com/107407348/205087360-c30145a9-3792-45e2-a002-7c8af931987a.png)

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by redleafnew** [comment]
1. 就是希望中文排在前面，英文排在后面是吧。
2. 给的条目信息太少，建议把6和23导出来，贴在这。

**Comment by ssieub** [comment]
![图片](https://user-images.githubusercontent.com/107407348/205196255-9ba2df29-8a8e-4679-a6b6-5e03e1fdeaec.png)
![图片](https://user-images.githubusercontent.com/107407348/205196284-dfa5c131-904c-42fe-a0b8-bf9b157d2a48.png)
![图片](https://user-images.githubusercontent.com/107407348/205196322-7ca7c4b0-a47e-4a36-a2bf-e8437dd3602e.png)
简单说就是华中我使用的时候没有按照上面说明说的  中文在前英文在后 按作者首字母排序

**Comment by redleafnew** [comment]
给出23、34这两个条目我才可以测试啊。

**Comment by ssieub** [comment]
[陈 et al_2019_外源油菜素内酯缓解水稻穗分化期高温伤害的机理研究.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10137504/et.al_2019_.pdf)

**Comment by redleafnew** [comment]
从你的Zotero中导出来，我可以导入的格式，如json，ris。我不要原文。

**Comment by ssieub** [comment]
稍等

**Comment by ssieub** [comment]
scihub 我不知道怎么上传这个文件 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 上午10:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序 (Issue #101)





 
从你的Zotero中导出来，我可以导入的格式，如json，ris。我不要原文。

**Comment by redleafnew** [comment]
中文、英文各2个吧，方便看各自的排序。
上传附件就可以

**Comment by ssieub** [comment]
[安 et al_2022_OsPM1基因在水稻苗期受非生物胁迫响应时的作用及应用.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10137539/et.al_2022_OsPM1.pdf)
[Bandara 等 - 2022 - Rice and Arabidopsis BBX proteins toward genetic .pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10137541/Bandara.-.2022.-.Rice.and.Arabidopsis.BBX.proteins.toward.genetic.pdf)
[丁 et al_OsWRKY67负向调控水稻耐旱性的功能分析.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10137546/et.al_OsWRKY67.pdf)
[Nadarajah et al_2021_SA-Mediated Regulation and Control of Abiotic Stress Tolerance in Rice.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10137548/Nadarajah.et.al_2021_SA-Mediated.Regulation.and.Control.of.Abiotic.Stress.Tolerance.in.Rice.pdf)

**Comment by ssieub** [comment]
可以不

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/205198532-df646d17-b00e-4894-9f65-83f7c96278b0.png)
这样导出，不要原文。

**Comment by ssieub** [comment]
🆗

**Comment by ssieub** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 上午10:08
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序 (Issue #101)





 

 这样导出，不要原文。

**Comment by ssieub** [comment]
收到了么

**Comment by redleafnew** [comment]
发到哪了？
贴到就可以。

**Comment by ssieub** [comment]
邮件没收到？   scihub 不让贴ris文件 说不支持

**Comment by ssieub** [comment]
[Uploading json.json…]()

**Comment by redleafnew** [comment]
没有收到。可以导出为json格式。

**Comment by ssieub** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 上午10:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序 (Issue #101)





 
没有收到。可以导出为json格式。

**Comment by ssieub** [comment]
josn 邮件发你了 大佬

**Comment by ssieub** [comment]
![图片](https://user-images.githubusercontent.com/107407348/205202320-471a3707-4a7c-4446-85e2-8242d210389d.png)

**Comment by ssieub** [comment]
发到163了 大佬看下

**Comment by redleafnew** [comment]
> （王雷等 2021, 杨诗勤等 [日期不详], 周棋等 2021, Ahmad 2022, Bailey-Serres et al 2019, Dong et al 2022）
> 
> 1. 王雷, 郭岩, 杨淑华. 非生物胁迫与环境适应性育种的现状及对策. 中国科学:生命科学. 2021, 51(10): 1424–1434	
> 2. 杨诗勤, 敖雁, 张晔, 冒小妹, 彭运鹏, 张婷婷, 任胜杰. 水稻干旱响应基因OsSPL3的克隆及功能初步分析. 分子植物育种. [日期不详]: 1–10	
> 3. 周棋, 胡琴, 杜雪竹, 巫燕飞, 盛锋. 水稻CNGCs家族的鉴定及非生物胁迫诱导表达模式分析. 分子植物育种. 2021: 1–16	
> 4. Ahmad M. Genomics and transcriptomics to protect rice (Oryza sativa. L.) from abiotic stressors: -pathways to achieving zero hunger. Front. Plant Sci.. 2022, 13: 1002596	
> 5. Bailey-Serres J, Parker JE, Ainsworth EA, Oldroyd GED, Schroeder JI. Genetic strategies for improving crop yields. Nature. 2019, 575(7781): 109–118	
> 6. Dong Q, Wallrad L, Almutairi BO, Kudla J. Ca2+ signaling in plant responses to abiotic stresses. Journal of Integrative Plant Biology. 2022, 64(2): 287–300.

**Comment by redleafnew** [comment]
最终这样可以吗？

**Comment by ssieub** [comment]
对对对 谢大佬

**Comment by redleafnew** [comment]
更新了。

**Comment by redleafnew** [comment]
Ca<sup>2+</sup>  `Ca<sup>2+</sup> `

**Comment by ssieub** [comment]
这是啥意思啊 需要把代码加到那 大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 中午11:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序 (Issue #101)





 
Ca2+  Ca<sup&gt;2+</sup&gt;

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/205208286-1ec77f45-828c-4fe6-ba2d-1d944b15633c.png)

**Comment by redleafnew** [comment]
https://zhuanlan.zhihu.com/p/57638901

**Comment by ssieub** [comment]
好的好的 大佬&nbsp; 还有 沈阳农大的论文格式能套用华中的 就不用单独改了 麻烦大佬了 
还有个问题 我想学下csl以后有小问题可以自己修改 大佬有推荐教程么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月2日(星期五) 中午11:28
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 403华中农大csl  排序出错 英文在前 中文在后且未未按字母排序 (Issue #101)

**Comment by redleafnew** [comment]
https://docs.citationstyles.org/en/stable/specification.html
