### ISSUE TITLE
沈阳农业大学毕业论文格式

### ISSUE THREAD

**Issue by ssieub** [redleafnew/Chinese-STD-GB-T-7714-related-csl#102]
**样式信息**

- 期刊/学校：沈阳农业大学研究生毕业论文

- 英文名称：SYAU

- 相关领域：biology

- 期刊/学校官网链接：https://www.syau.edu.cn/

- ISSN 号：

- 参考文献格式要求的链接：
![图片](https://user-images.githubusercontent.com/107407348/205088182-4e7c1d3c-7518-4198-b464-c1f5ecabd463.png)

**测试条目**

加入 Zotero 群组[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development，提供Zotero ID，赋予编辑权限后，将**期刊/学校官网的示例文献**条目录入 Zotero 并拖动到群组中，方便测试。

Zotero ID:yuanbo97

**其他样式信息**

**Comment by redleafnew** [comment]
1. 已经调整权限，请将条目上传到群组以方便测试。尽量上传格式要求上的参考文献。
2. 格式要求与现在仓库中哪个类似，我在上面基础上修改。

**Comment by ssieub** [comment]
与华中农大相似 403

**Comment by redleafnew** [comment]
1. 请详细列出区别，从什么改成什么（现在显示效果→希望得到的结果）
2. 将用于显示测试的条目上传到群组的沈阳农大文件夹。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/101#issuecomment-1334718549

**Comment by redleafnew** [comment]
b591082950ed21ed58a7203959376ae45bbdeecc
