### ISSUE TITLE
305 格式没有脚注选项，与标注不符

### ISSUE THREAD

**Issue by babuf** [redleafnew/Chinese-STD-GB-T-7714-related-csl#108]
**描述错误**

该样式应该有「脚注」选项，但实际并没有，而且导入名称上也没有显示有「脚注」二字（见截图）

CSL 样式：305gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

![QO@Y183)QY2%(O}EPW1Q$ A](https://user-images.githubusercontent.com/40053702/207612625-5b3f34bd-f1a1-4431-bfe5-a921c5bd7761.jpg)

**Comment by redleafnew** [comment]
都有啊，你是不是选得不对。
![image](https://user-images.githubusercontent.com/22135631/207616147-e19d51e0-d17a-48ce-9038-0e345d11e8ba.png)

![image](https://user-images.githubusercontent.com/22135631/207616028-52e06ac3-b482-4000-a690-d466749c6a4f.png)

**Comment by zepinglee** [comment]
305 的名称：

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/02d75feed260c55f31833b0f6748ca5de6417daf/305gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi.csl#L4

**Comment by redleafnew** [comment]
如无问题，则关闭了。
