### ISSUE TITLE
能否编写一个csl,针对使用zotero写英文文章时，需引用中文文献的情况

### ISSUE THREAD

**Issue by Williamswz** [redleafnew/Chinese-STD-GB-T-7714-related-csl#109]
类似于：Cai, Zhao. (2021). Research on Temporal and Spatial Evolution Pattern and Influencing Factors of China's Energy Poverty. Soft Science, 35(04), 28-42. https://doi.org/10.13956/j.ss.1001-8409.2021.04.05 (in Chinese)

在APA 7th edition 的基础上更改

**Comment by redleafnew** [comment]
参考这个：https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#112scientia-agricultura-sinicacsl
建立一个条目。
把这篇文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by Williamswz** [comment]
> 参考这个：https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#112scientia-agricultura-sinicacsl
> 
> > 中文文献需要将作者姓名、标题、期刊、出版地、出版社的英文翻译分别填写在 extra 中的 original-author, original-title, original-container-title, original-publisher-place, original-publisher 字段，比如
> > original-author: Ye || Gong Yin
> > original-author: Hu || Cui
> > original-author: Shu || Qing Yao
> > original-title: The development of transgenic rice resistant to insect pests and its wise and sustainable use
> > original-container-title: Agricultural Development and Research in the 21st Century
> > original-publisher-place: Beijing
> > original-publisher: China Environmental Science Press
> 
> 建立一个条目。 把这篇文献导出 CSL-JSON 格式贴过来，不然没法复现。 或 加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

见谅啊 是个新手 刚注册GitHUb 我导出了这篇文献的CSL-json格式，需要上传哪个地方？

**Comment by zepinglee** [comment]
> 类似于：Cai, Zhao. (2021). Research on Temporal and Spatial Evolution Pattern and Influencing Factors of China's Energy Poverty. Soft Science, 35(04), 28-42. https://doi.org/10.13956/j.ss.1001-8409.2021.04.05 (in Chinese)
> 
> 在APA 7th edition 的基础上更改

具体哪个期刊的格式要求？

**Comment by zepinglee** [comment]
> 见谅啊 是个新手 刚注册GitHUb 我导出了这篇文献的CSL-json格式，需要上传哪个地方？

用记事本打开，贴到这里，比如
```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**Comment by Williamswz** [comment]
> > 类似于：Cai, Zhao. (2021). Research on Temporal and Spatial Evolution Pattern and Influencing Factors of China's Energy Poverty. Soft Science, 35(04), 28-42. https://doi.org/10.13956/j.ss.1001-8409.2021.04.05 (in Chinese)
> > 在APA 7th edition 的基础上更改
> 
> 具体哪个期刊的格式要求？

我在看英文期刊时，如Renewable and Sustainable Energy Reviews，看到有中国学者引用中文文献，他们使用的是上面这种格式。

**Comment by Williamswz** [comment]
> 参考这个：https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#112scientia-agricultura-sinicacsl
> 
> > 中文文献需要将作者姓名、标题、期刊、出版地、出版社的英文翻译分别填写在 extra 中的 original-author, original-title, original-container-title, original-publisher-place, original-publisher 字段，比如
> > original-author: Ye || Gong Yin
> > original-author: Hu || Cui
> > original-author: Shu || Qing Yao
> > original-title: The development of transgenic rice resistant to insect pests and its wise and sustainable use
> > original-container-title: Agricultural Development and Research in the 21st Century
> > original-publisher-place: Beijing
> > original-publisher: China Environmental Science Press
> 
> 建立一个条目。 把这篇文献导出 CSL-JSON 格式贴过来，不然没法复现。 或 加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

{
    "items": [
        {
            "id": "8003742/DP565HFX",
            "type": "article-journal",
            "title": "中国区域能源贫困综合评价",
            "container-title": "北京理工大学学报(社会科学版)",
            "page": "1-12",
            "volume": "16",
            "issue": "02",
            "abstract": "中国居民部门存在的能源贫困现象可能会成为改善民生的阻碍,对能源贫困的综合测度及评估分析是认清中国当前能源贫困现状的重要环节,也是国家制定缓解能源贫困政策的前提。在理清中国能源贫困概念和国际能源贫困评估方法基础上,构建了四维度中国区域能源贫困评估指标体系,用以评估中国区域能源贫困现状及变化趋势。研究认为:随着中国经济社会发展,2000—2011年间中国整体能源贫困状况呈自然减缓趋势,但能源贫困问题未来持续大幅减缓还需要依赖政府的重视和专项应对政策的出台和实施;中国区域间能源贫困状态及其减缓速度很不一致,在制定全国能源贫困减缓政策时应充分考虑区域差异,抓住导致不同地区能源贫困的主要矛盾;能源贫困在中国的区域分布情况与中国经济发展水平的区域分布情况并不一致,减缓能源贫困政策实施对象选择和区域投入比例的确定,应区别于其他促进经济社会发展、提升基础建设、改善民生的相关政策。",
            "call-number": "11-4083/C",
            "note": "年鉴",
            "language": "zh-CN",
            "author": [
                {
                    "family": "李慷",
                    "given": ""
                },
                {
                    "family": "王科",
                    "given": ""
                },
                {
                    "family": "王亚璇",
                    "given": ""
                }
            ],
            "editor": [
                {
                    "family": "李慷",
                    "given": ""
                },
                {
                    "family": "王科",
                    "given": ""
                },
                {
                    "family": "王亚璇",
                    "given": ""
                }
            ],
            "issued": {
                "date-parts": [
                    [
                        2014
                    ]
                ]
            }
        }
    ]
}

**Comment by Williamswz** [comment]
> > 见谅啊 是个新手 刚注册GitHUb 我导出了这篇文献的CSL-json格式，需要上传哪个地方？
> 
> 用记事本打开，贴到这里，比如
> 
> ```json
> [
> 	{
> 		"id": "doe1984his",
> 		"type": "book",
> 		"title": "His anonymous life",
> 		"author": [
> 			{
> 				"family": "Doe",
> 				"given": "John"
> 			}
> 		],
> 		"issued": {
> 			"date-parts": [
> 				[
> 					"1984"
> 				]
> 			]
> 		}
> 	}
> ]
> ```

谢谢

**Comment by Williamswz** [comment]
我又添加了一个，供您们参考，非常感谢。


{
    "items": [
        {
            "id": "8003742/7RK7BV6A",
            "type": "article-journal",
            "title": "技术进步、能源贫困与我国包容性绿色发展",
            "container-title": "大连理工大学学报(社会科学版)",
            "page": "1-12",
            "abstract": "经济的快速增长带动了我国社会各方面的发展,但同时也引发了许多社会矛盾与资源环境问题,包容性绿色发展是破解公平与资源环境难题,实现可持续发展的客观要求和必然选择。基于中国30个省份(限于数据所得,不包括西藏自治区和港澳台地区)2004～2017年间的面板数据,实证检验了技术进步和能源贫困对我国包容性绿色发展的影响。研究发现:技术进步是促进我国包容性绿色发展的重要因素,而能源贫困对我国包容性绿色发展具有显著的抑制作用。此外,能源贫困对我国包容性绿色发展的作用受地理区域以及经济发展水平高低的影响较小,但是技术进步在经济欠发达地区的作用效果要优于发达地区。同时,能源贫困对我国包容性绿色发展的影响存在门槛效应,不同技术水平下能源贫困对我国包容性绿色发展的影响存在差异。",
            "call-number": "21-1383/C",
            "author": [
                {
                    "family": "徐盈之",
                    "given": ""
                },
                {
                    "family": "徐菱",
                    "given": ""
                }
            ],
            "editor": [
                {
                    "family": "徐盈之",
                    "given": ""
                },
                {
                    "family": "徐菱",
                    "given": ""
                }
            ],
            "issued": {
                "date-parts": [
                    [
                        2020
                    ]
                ]
            }
        }
    ]
}

**Comment by zepinglee** [comment]
> 类似于：Cai, Zhao. (2021). Research on Temporal and Spatial Evolution Pattern and Influencing Factors of China's Energy Poverty. Soft Science, 35(04), 28-42. https://doi.org/10.13956/j.ss.1001-8409.2021.04.05 (in Chinese)
> 
> 在APA 7th edition 的基础上更改

CSL 没有自动翻译的功能，所以最简单的办法是将中文文献的英文翻译录为另一篇文献，跟英文文献一样引用。

**Comment by Williamswz** [comment]
> > 类似于：Cai, Zhao. (2021). Research on Temporal and Spatial Evolution Pattern and Influencing Factors of China's Energy Poverty. Soft Science, 35(04), 28-42. https://doi.org/10.13956/j.ss.1001-8409.2021.04.05 (in Chinese)
> 
> > 
> 
> > 在APA 7th edition 的基础上更改
> 
> 
> 
> CSL 没有自动翻译的功能，所以最简单的办法是将中文文献的英文翻译录为另一篇文献，跟英文文献一样引用。

我今天就是这样做的，把题目，作者等信息手动改成英文格式，这是一个笨办法，我就想请教您们有没有更好的办法，因为我看到有人推出了双语参考文献。还有个问题是我翻译后，（in Chinese）这个后缀不知道怎么加上去，谢谢🙏

**Comment by zepinglee** [comment]
> 我今天就是这样做的，把题目，作者等信息手动改成英文格式，这是一个笨办法，我就想请教您们有没有更好的办法，因为我看到有人推出了双语参考文献。

我觉得上述应该就是最简单的方法了。

> 还有个问题是我翻译后，（in Chinese）这个后缀不知道怎么加上去，谢谢🙏

对于 APA 而言可以在“extra”字段（“其他”）中填写 `References: in Chinese`。
<img width="730" alt="Screen Shot 2022-12-15 at 12 27 21" src="https://user-images.githubusercontent.com/12290822/207772492-161a0722-9380-4475-a160-160fead027d5.png">

**Comment by Williamswz** [comment]
> > 我今天就是这样做的，把题目，作者等信息手动改成英文格式，这是一个笨办法，我就想请教您们有没有更好的办法，因为我看到有人推出了双语参考文献。
> 
> 
> 
> 我觉得上述应该就是最简单的方法了。
> 
> 
> 
> > 还有个问题是我翻译后，（in Chinese）这个后缀不知道怎么加上去，谢谢🙏
> 
> 
> 
> 对于 APA 而言可以在“extra”字段（“其他”）中填写 `References: in Chinese`。
> 
> <img width="730" alt="Screen Shot 2022-12-15 at 12 27 21" src="https://user-images.githubusercontent.com/12290822/207772492-161a0722-9380-4475-a160-160fead027d5.png">
> 
> 

好的，谢谢，我去试试。🤝🤝

**Comment by redleafnew** [comment]
> > 我今天就是这样做的，把题目，作者等信息手动改成英文格式，这是一个笨办法，我就想请教您们有没有更好的办法，因为我看到有人推出了双语参考文献。
> 
> 我觉得上述应该就是最简单的方法了。
> 
> > 还有个问题是我翻译后，（in Chinese）这个后缀不知道怎么加上去，谢谢🙏
> 
> 对于 APA 而言可以在“extra”字段（“其他”）中填写 `References: in Chinese`。 <img alt="Screen Shot 2022-12-15 at 12 27 21" width="730" src="https://user-images.githubusercontent.com/12290822/207772492-161a0722-9380-4475-a160-160fead027d5.png">

@zepinglee 还有这功能啊，其它csl可以这样搞吗？

**Comment by zepinglee** [comment]
> @zepinglee 还有这功能啊，其它csl可以这样搞吗？

`references` 只是一个普通的变量。我看了一下 APA 的代码，感觉这样最方便。

https://github.com/citation-style-language/styles/blob/f6c778e75b389808de8bd324f3b241bb7b3f226b/apa.csl#L1588-L1620

```xml
  <!-- After 'source', APA also prints publication history (original publication, reprint info, retraction info) -->
  <macro name="publication-history">
    <choose>
      <if type="patent" match="none">
        <group prefix="(" suffix=")">
          <choose>
            <if variable="references">
              <!-- This provides the option for more elaborate description
                   of publication history, such as full "reprinted" references
                   (examples 11, 43, 44) or retracted references -->
              <text variable="references"/>
            </if>
            <else>
              <group delimiter=" ">
                <text value="Original work published"/>
                <choose>
                  <if is-uncertain-date="original-date">
                    <text term="circa" form="short"/>
                  </if>
                </choose>
                <date variable="original-date">
                  <date-part name="year"/>
                </date>
              </group>
            </else>
          </choose>
        </group>
      </if>
      <else>
        <text variable="references" prefix="(" suffix=")"/>
      </else>
    </choose>
  </macro>
```

其他 csl 就不确定了。

**Comment by redleafnew** [comment]
我看是加了一个  `<text variable="references" prefix="(" suffix=")"/>`  在 `<macro name="publication-history">`中。其它csl估计没有写这个。

**Comment by redleafnew** [comment]
@Williamswz 还需要搞翻译用的csl吗？要把翻译的字段放入Extra中，搞的话就是后期如果再转投中文期刊或写毕业论文是可以直接用同一个条目。
如果不需要了就关闭吧。

**Comment by Williamswz** [comment]
> @Williamswz 还需要搞翻译用的csl吗？要把翻译的字段放入Extra中，搞的话就是后期如果再转投中文期刊或写毕业论文是可以直接用同一个条目。如果用中文是两个条目，也不太麻烦。 如果不需要了就关闭吧。

您这边方便修改csl吗？如果能搞一个那就太好了，如果不方便也没事，谢谢。

**Comment by redleafnew** [comment]
那等需要的时候再说吧。
