### ISSUE TITLE
解决两个合并过的中文姓名产生的多余逗号

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#110]
README 中有多处备注“如果中文两个作者的和前面有逗号(, )，如显示为（金红兰, 和金龙勋, 2021），请确认条目的作者是是否经过合并操作，如果合并过请拆分”。

事实上，这是 citeproc-js 的一个 [bug](https://github.com/Juris-M/citeproc-js/issues/218)，会导致用户很不方便。不过，这一 bug 可以通过简单地修改 csl 的逻辑有效地避免，见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/63#issuecomment-1214134614> 和 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/ae6f440cf53259eff923f40ce0072127df106299>。由于 #106 中新增的样式都是在原来的代码基础上写的，所以有必要彻底解决这个问题，防止进一步蔓延。

**Comment by redleafnew** [comment]
就是英文的作者的 `delimiter-precedes-last="always"`中文的作者`delimiter-precedes-et-al="never"`来吗？
忘记了。

**Comment by zepinglee** [comment]
英文的 `delimiter-precedes-last="always"` 会导致“J. Doe, and T. Williams”和“J. Doe, S. Smith, and T. Williams”的结果，但前者并不太常见。https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/ae6f440cf53259eff923f40ce0072127df106299 中修改的 [203economic-research-journal.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/203economic-research-journal.csl) 是个例外。

中文的使用习惯是：“张三和李四”、“张三、李四和王五”，确实最符合 `delimiter-precedes-et-al="never"`。不过在 `et-al-min="3" et-al-use-first="1"` 且没有 `disambiguate-add-names` 的情况下，可以不考虑三个姓名的情况，默认的 "contextual" 也能达到相同效果。

**Comment by redleafnew** [comment]
搞新的时候再说，不过最好还是不合并。

**Comment by zepinglee** [comment]
> 搞新的时候再说，不过最好还是不合并。

像标准、报告这类文献经常以单位名称为作者，本身就不能拆分。

**Comment by zepinglee** [comment]
修改后，用户的作者姓名选择拆分或合并都可以。
