### ISSUE TITLE
申请添加readme内容

### ISSUE THREAD

**Issue by Eunsolfs** [redleafnew/Chinese-STD-GB-T-7714-related-csl#111]
不乏很多用户遇到文献的language不是zh_CN，en_US的，这里有一个zotero插件可以自动做到修改language为zh_CN，en_US

[https://github.com/redleafnew/delitemwithatt](https://github.com/redleafnew/delitemwithatt)

同时它还可以管理附件（无论是实体附件，还是软连接的附件）

还请添加相关内容到本仓库的readme部分，便利更多的用户

**Comment by Eunsolfs** [comment]
我前几天用茉莉花插件，企图修改language为zh_CN，en_US，然而并不生效，还全部给我改成了 en  / ch ，联系茉莉花的开发也得不到具体的解决办法；天无绝人之路，今天在zotero交流群，管理发了一个消息——利用合适的CSL，结合设置条目语言解决et al和等混排问题  [https://gitee.com/zotero-chinese/zotero-chinese/issues/I4YKIN](https://gitee.com/zotero-chinese/zotero-chinese/issues/I4YKIN)，在文中我找到了这个插件。

**Comment by Eunsolfs** [comment]
笑死，这不就是大佬您自己的另一个插件项目吗？哈哈哈哈，关注了

**Comment by redleafnew** [comment]
哈哈，readme也有写用这个插件

> 批量修改语言：可以使用 delitemwithatt 插件，到 https://github.com/redleafnew/delitemwithatt 下载插件并安装, 选择需要修改的条目后，右击，选择“将语言字段设为 en”即可。其他方法参见 https://zhuanlan.zhihu.com/p/341989158。

**Comment by Eunsolfs** [comment]
谢谢老师提点
我还是认认真真多看几遍readme吧, 闹了个大乌龙(捂脸.jpg)



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月15日 20:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请添加readme内容 (Issue #111) |

哈哈，readme也有写用这个插件

批量修改语言：可以使用 delitemwithatt 插件，到 https://github.com/redleafnew/delitemwithatt 下载插件并安装, 选择需要修改的条目后，右击，选择“将语言字段设为 en”即可。其他方法参见 https://zhuanlan.zhihu.com/p/341989158。

**Comment by zepinglee** [comment]
另外应该是 `en-US`、`zh-CN`，不是 `en_US`、`zh_CN`。

**Comment by Eunsolfs** [comment]
哈哈, 打_习惯了, 别介意



---- 回复的原邮件 ----
| 发件人 | Zeping ***@***.***> |
| 日期 | 2022年12月15日 21:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请添加readme内容 (Issue #111) |

另外应该是 en-US、zh-CN，不是 en_US、zh_CN。
