### ISSUE TITLE
管理世界文献综述里面同作者同年份没有abc

### ISSUE THREAD

**Issue by xidadan** [redleafnew/Chinese-STD-GB-T-7714-related-csl#112]
**描述错误**
CSL 样式：202journal-of-management-world.csl

您好，管理世界英文文献综述里面同作者同年份的文献没有abc，截图贴在下边了

**屏幕截图**
年份无abc样式
![image](https://user-images.githubusercontent.com/32384884/208345120-b306ba1e-7728-49ad-ae5d-c96c7db5b6d0.png)
年份有abc样式（这个是之前的版本，格式不太对）
<img width="576" alt="image" src="https://user-images.githubusercontent.com/32384884/208345158-a74896f4-09e2-48d1-9d71-d82de4951e71.png">

**Comment by redleafnew** [comment]
把这几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by xidadan** [comment]
[
 {
  "id": "http://zotero.org/users/8429396/items/2DFM55MW",
  "type": "book",
  "call-number": "338.19",
  "event-place": "Rome",
  "language": "en",
  "publisher": "Food and Agriculture Organization of the United Nations",
  "publisher-place": "Rome",
  "source": "BnF ISBN",
  "title": "The state of food insecurity in the world 2013: the multiple dimensions of food security",
  "title-short": "🔤2013 年世界粮食不安全状况：粮食安全的多个方面",
  "author": [
   {
    "family": "FAO",
    "given": ""
   }
  ],
  "issued": {
   "date-parts": [
    [
     "2013"
    ]
   ]
  }
 },
 {
  "id": "http://zotero.org/users/8429396/items/DGL3ITC9",
  "type": "book",
  "call-number": "HD9000.5 .F5997 2014",
  "event-place": "Rome",
  "language": "en",
  "note": "OCLC: ocn894540796",
  "publisher": "Food and Agriculture Organization of the United Nations",
  "publisher-place": "Rome",
  "source": "Library of Congress ISBN",
  "title": "Food wastage footprint full-cost accounting: final report",
  "title-short": "🔤食物浪费足迹全成本核算：最终报告",
  "author": [
   {
    "family": "FAO",
    "given": ""
   }
  ],
  "issued": {
   "date-parts": [
    [
     "2014"
    ]
   ]
  }
 },
 {
  "id": "http://zotero.org/users/8429396/items/K97MXIVH",
  "type": "book",
  "call-number": "HD9000.5 .T636 2013",
  "event-place": "Rome",
  "language": "en",
  "note": "OCLC: ocn858897077",
  "publisher": "Food and Agriculture Organization of the United Nations",
  "publisher-place": "Rome",
  "source": "Library of Congress ISBN",
  "title": "Toolkit: reducing the food wastage footprint",
  "title-short": "🔤工具包：减少食物浪费足迹",
  "author": [
   {
    "family": "FAO",
    "given": ""
   }
  ],
  "issued": {
   "date-parts": [
    [
     "2013"
    ]
   ]
  }
 },
 {
  "id": "http://zotero.org/users/8429396/items/IEC8FNGL",
  "type": "book",
  "call-number": "HD9000.4 .F67 2013",
  "event-place": "Rome",
  "language": "en",
  "note": "OCLC: ocn858897065",
  "publisher": "Food and Agriculture Organization of the United Nations",
  "publisher-place": "Rome",
  "source": "Library of Congress ISBN",
  "title": "Food wastage footprint: impacts on natural resources: summary report",
  "title-short": "Food wastage footprint",
  "author": [
   {
    "literal": "FAO"
   }
  ],
  "issued": {
   "date-parts": [
    [
     "2013"
    ]
   ]
  }
 },
 {
  "id": "http://zotero.org/users/8429396/items/ETZPEPLB",
  "type": "book",
  "collection-number": "2012",
  "collection-title": "The state of food and agriculture",
  "event-place": "Rome",
  "ISBN": "978-92-5-107317-9",
  "language": "en",
  "number-of-pages": "165",
  "publisher": "Food and Agriculture Organization of the United Nations",
  "publisher-place": "Rome",
  "source": "K10plus ISBN",
  "title": "Investing in agriculture for a better future",
  "title-short": "🔤投资农业创造更美好的未来",
  "editor": [
   {
    "literal": "FAO"
   }
  ],
  "issued": {
   "date-parts": [
    [
     "2012"
    ]
   ]
  }
 }
]

**Comment by redleafnew** [comment]
规则上确实需要相同年代，相同作者加字母吗？

**Comment by zepinglee** [comment]
<img width="630" alt="Screen Shot 2022-12-19 at 20 39 52" src="https://user-images.githubusercontent.com/12290822/208429754-e99a3e7e-5f9f-44d4-a750-2813d9c38b02.png">

应该是要有 `disambiguate-add-year-suffix="true"` 的，我稍后改一下。

好像是我在 5678e26 中重构时不小心删掉了

**Comment by redleafnew** [comment]
我已经修改了，我来上传吧，只是确认一下。

**Comment by redleafnew** [comment]
@zepinglee 还是你上传吧，我重装电脑后又不能push了。

**Comment by redleafnew** [comment]
已经上传了，
@xidadan 测试一下吧。

**Comment by zepinglee** [comment]
我在同为 author-date 样式的 [205business-management-journal.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/205business-management-journal.csl) 和 [207chinas-industrial-economics.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/207chinas-industrial-economics.csl) 中也增加了 `disambiguate-add-givenname="true"` 和 `disambiguate-add-year-suffix="true"`，见 006da51 。

**Comment by redleafnew** [comment]
如无进一步反馈，即将关闭。
