### ISSUE TITLE
武汉大学学位论文

### ISSUE THREAD

**Issue by lixiaoshuang1-ola** [redleafnew/Chinese-STD-GB-T-7714-related-csl#113]
**样式信息**

- 期刊/学校：武汉大学学位论文

- 英文名称：Wuhan University

- 相关领域：

- 期刊/学校官网链接：https://www.whu.edu.cn/

- ISSN 号：

- 参考文献格式要求的链接：https://wwpg.lanzoue.com/iI3oz0j1afcd     密码:3yxy

**测试条目**

加入 Zotero 群组[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供Zotero ID，赋予编辑权限后，将**期刊/学校官网的示例文献**条目录入 Zotero 并拖动到群组中，方便测试。

Zotero ID:AShuang

**其他样式信息**

**Comment by zepinglee** [comment]
参考文献格式要求有没有学校官方的链接（一般是研究生院的）？

我在 group members 中没搜到“AShuang”这个 id 呀，已经加入群组了吗？

**Comment by lixiaoshuang1-ola** [comment]
找到链接啦：http://210.42.121.231/bysj/ShowNews.aspx?newsno=PM3MJm/hS+nVAddilKbNyg

刚加入群组，辛苦大佬~

**Comment by zepinglee** [comment]
已经设为 admin，可以添加文献了。

<img width="908" alt="Screen Shot 2022-12-19 at 23 53 08" src="https://user-images.githubusercontent.com/12290822/208466278-87af45a5-9e05-46c8-9aa9-c5154ef7cfbb.png">

需要将这几篇文献录入“武汉大学-本科生”的collection，方便我们进行测试。

<img width="679" alt="Screen Shot 2022-12-19 at 23 55 18" src="https://user-images.githubusercontent.com/12290822/208466879-694d8414-199d-432f-b091-b3c9ade1890d.png">

<img width="233" alt="Screen Shot 2022-12-19 at 23 57 02" src="https://user-images.githubusercontent.com/12290822/208467134-ebfe257d-3b7b-43c2-96a9-d16214be1816.png">

**Comment by zepinglee** [comment]
> 找到链接啦：https://civ.whu.edu.cn/__local/7/65/BE/EBE513F22AD878EAE587C0D0081_14AFF292_28400.doc?e=..doc

有没有网页的链接？

**Comment by lixiaoshuang1-ola** [comment]
> > 找到链接啦：https://civ.whu.edu.cn/__local/7/65/BE/EBE513F22AD878EAE587C0D0081_14AFF292_28400.doc?e=..doc
> 
> 有没有网页的链接？

没有找到网页的链接诶

**Comment by zepinglee** [comment]
我在 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 的基础上修改的，已经完成了大半，晚上继续搞。

**Comment by zepinglee** [comment]
@lixiaoshuang1-ola [12a9da2](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/12a9da214e6cbe7771f4f9d6a365c83704517efa) 中添加了对应的样式，可以试一下效果。

**Comment by lixiaoshuang1-ola** [comment]
在word里面引用有问题，引用后没有内容

**Comment by zepinglee** [comment]
> 在word里面引用有问题

引用有什么问题？

> 引用后没有内容

点了“Add bibliography”没？

**Comment by lixiaoshuang1-ola** [comment]
懂了！辛苦各位大佬！没啥问题了

**Comment by redleafnew** [comment]
如无进一步反馈，即将关闭。
