### ISSUE TITLE
统一 author-date 样式的消歧义方式

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#114]
目前仓库的 author-date 样式处理消歧义的方式比较混乱，建议统一整理一下。

由于国标没有进行详细规定，只能参考国际常见的样式的设置方式。Zotero 自带的 16 个样式中有 6 个 是 author-date 的，统计如下。

样式名称 | `disambiguate-add-givenname` | `givenname-disambiguation-rule` | `disambiguate-add-names` | `disambiguate-add-year-suffix`
--- | --- | --- | --- | ---
american-political-science-association.csl | true | primary-name | true | true
apa.csl | true | primary-name-with-initials | true | true
american-sociological-association.csl | true | by-cite | true | true
chicago-author-date.csl | true | primary-name | true | true
harvard-cite-them-right.csl | true | by-cite | true | true
elsevier-harvard.csl | true | by-cite | false | true

我提议统一设置为 `disambiguate-add-givenname="true" disambiguate-add-names="true" disambiguate-add-year-suffix="true"`。`givenname-disambiguation-rule` 可以选择 `primary-name` 或者默认的 `by-cite`。或者按照领域设置，比如心理学沿用 APA 的 `givenname-disambiguation-rule="primary-name-with-initials"`，经济学的期刊另找一个该领域的国际期刊。

@redleafnew 你有印象哪个样式详细规定了消歧义的方式吗？

**Comment by redleafnew** [comment]
没有印象了，但感觉我们的习惯还是年代后面加字母这种样式。

**Comment by zepinglee** [comment]
> 没有印象了，但感觉我们的习惯还是年代后面加字母这种样式。

嗯，对应的 `disambiguate-add-year-suffix="true"` 确实是必要的。

另外我又看了一下国标的要求，其中有一条：
<img width="705" alt="Screen Shot 2022-12-20 at 18 51 15" src="https://user-images.githubusercontent.com/12290822/208649835-7b1aae1b-0cbb-4661-8b2c-f26a7e5561b0.png">

比如“Doe, John”和“Doe, Jane”姓相同时，需要额外添加名，也就是 `disambiguate-add-givenname="true"`。

`disambiguate-add-names` 和 `givenname-disambiguation-rule` 还值得再讨论一下。

**Comment by redleafnew** [comment]
那还是根据具体期刊要求来吧。

**Comment by zepinglee** [comment]
> 那还是根据具体期刊要求来吧。

我印象中没有期刊提到 `disambiguate-add-givenname="true"` 以外的消歧义方式。

我提议将全部 author-date 样式统一改为 `disambiguate-add-givenname="true" disambiguate-add-year-suffix="true"`，`disambiguate-add-names` 和 `givenname-disambiguation-rule` 分别保持默认的 `false` 和 `by-cite`。但如果期刊领域内有权威样式作了详细规定的（比如心理学的 APA），按照该格式执行。

**Comment by redleafnew** [comment]
好的，遇到有人提出问题再说。

**Comment by zepinglee** [comment]
在 [2f57d65](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/2f57d65fc523d217cc720122a5bbfc13253ecd27) 中完成。
