### ISSUE TITLE
 南京中医药大学

### ISSUE THREAD

**Issue by sleepyheadforu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#115]
跪求 感谢感谢

**Comment by redleafnew** [comment]
看看与仓库中哪个最接近，在上面修改更方便快捷。
提供学校要求网址，并将例子文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
按照 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/new?assignees=&labels=&template=feature_request.md&title=> 填写。

**Comment by redleafnew** [comment]
@sleepyheadforu 没有进一步反馈将关闭。需要配合测试、提供条目的。
