### ISSUE TITLE
重庆大学研究生学位论文

### ISSUE THREAD

**Issue by ChongqingGuy** [redleafnew/Chinese-STD-GB-T-7714-related-csl#116]
**样式信息**

- 期刊/学校：重庆大学研究生学位论文

- 英文名称：Chongqing University 

- 相关领域：engineering

- 期刊/学校官网链接：http://graduate.cqu.edu.cn/

- ISSN 号：//无
//无

- 参考文献格式要求的链接：https://docs.qq.com/pdf/DU0tHenBLcXdJdkhv
- //因为学校官网发的在压缩包内，我提取后直接发腾讯云文档了

**测试条目**

加入 Zotero 群组[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供Zotero ID，赋予编辑权限后，将**期刊/学校官网的示例文献**条目录入 Zotero 并拖动到群组中，方便测试。

Zotero ID:iskandar520

**其他样式信息**
感觉和扬州大学的很像

**Comment by zepinglee** [comment]
按要求填写内容，参考 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/113>。

**Comment by redleafnew** [comment]
@ChongqingGuy 有加入到群组吗？没有搜索到iskandar520这个ID，或是将这篇文档上的例子JSON格式粘贴过来方便测试。

**Comment by redleafnew** [comment]
@ChongqingGuy 这个看起来也是数字格式的，主要看一下与https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/000gb-t-7714-2015-numeric-bilingual.csl的区别。请详细列出来，现在显示是什么，想改成什么，我们再针对修改

**Comment by zepinglee** [comment]
> 参考文献格式要求的链接：https://docs.qq.com/pdf/DU0tHenBLcXdJdkhv
> 因为学校官网发的在压缩包内，我提取后直接发腾讯云文档了

@ChongqingGuy 有没有官网的链接？如果后续有版本更新方便确认。

另外请将全部示例文献录入 Zotero 群组，方便我们测试。

**Comment by zepinglee** [comment]
> @ChongqingGuy 这个看起来也是数字格式的，主要看一下与使用https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/000gb-t-7714-2015-numeric-bilingual.csl的区别。请详细列出来，现在显示是什么，想改成什么，我们再针对修改

其实与 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 最接近。专利、标准、报纸、电子文献的格式略有不同。

感觉这个问题对于他们不太熟悉参考文献格式的有些太难了，我还是从 issue template 中删掉吧。

**Comment by redleafnew** [comment]
好的，关键是要配合提供资料及测试才好，自己学校的自己需求的格式自己最清楚。

**Comment by ChongqingGuy** [comment]
其实没有找到官网的链接，甚至我是查了才知道原来二级单位（也就是学院）中外国语学院发了

**Comment by redleafnew** [comment]
那先用 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 试试，详细列出什么地方需要修改，并提供测试的条目。

**Comment by zepinglee** [comment]
> 其实没有找到官网的链接，甚至我是查了才知道原来二级单位（也就是学院）中外国语学院发了 http://www.cfl.cqu.edu.cn/info/1367/8626.htm

嗯，这个也可以，总之有官方链接作参考就行。

**Comment by ChongqingGuy** [comment]
> 那先用 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 试试，详细列出什么地方需要修改，并提供测试的条目。

好的，谢谢大佬们！这几天我先忙一下考试，可能得过几天才能试试条目，抱歉Orz

**Comment by zepinglee** [comment]
没关系，不急。

**Comment by redleafnew** [comment]
@ChongqingGuy 还搞吗？

**Comment by redleafnew** [comment]
？？
