### ISSUE TITLE
请求在CSL中 文内引用使用中文的标点符号（无论中英文），参考文献中英文中文分别所属的标点符号状态

### ISSUE THREAD

**Issue by yw124** [redleafnew/Chinese-STD-GB-T-7714-related-csl#117]
能否基于[415zhejiang-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/415zhejiang-university.csl) 进行修改
1.文内引用（无论中英文文献）的标点符号全部使用中文状态
2. 参考文献中文文献的标点符号全部使用中文状态，英文保持默认的英文状态
非常感谢！

**Comment by redleafnew** [comment]
把几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
`suffix="."`这些前后辍之后的也改为`。`？

**Comment by redleafnew** [comment]
中文页码之间的间隔`-`是不是需要修改？
@yw124

**Comment by zepinglee** [comment]
@yw124 这个样式是用于哪个具体的期刊/学校？

**Comment by redleafnew** [comment]
如无其他需求，即将关闭。
