### ISSUE TITLE
北航cls简介错误

### ISSUE THREAD

**Issue by RogerPanBUAA** [redleafnew/Chinese-STD-GB-T-7714-related-csl#121]
**描述错误**

CSL 样式：420-beihang-university.csl

介绍写错了 北航写成了北师大的

**屏幕截图**
![image](https://user-images.githubusercontent.com/21955583/215336082-9feaf03a-13e3-4a9f-a7b8-2594d6d1aaf3.png)

**Comment by redleafnew** [comment]
已修改，谢谢。
