### ISSUE TITLE
请求增加《世界经济》期刊样式

### ISSUE THREAD

**Issue by artemith** [redleafnew/Chinese-STD-GB-T-7714-related-csl#122]
**样式信息**

- 期刊/学校名称：《世界经济》

- 英文名称：The Journal of World Economy

- 参考文献格式要求的**官网**链接
  - [世界经济|下载中心](https://manu30.magtech.com.cn/sjjj/CN/column/column10.shtml)
  - [稿件体例调整规范](https://manu30.magtech.com.cn/sjjj/attached/file/20200810/20200810171351_281.doc)

- （期刊的）ISSN 号：1002-9621

- （期刊的）相关领域：social_science

- 较为接近的已有csl格式
  - [202journal-of-management-world.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/202journal-of-management-world.csl)

- 期刊中的文献
  -  [韩珣 等。 - 2022 - 政策不连续性、非金融企业影子银行化与企业创新.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10553097/-.2022.-.pdf)

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: hy_0943（已加入群组）

**其他样式信息**

**Comment by redleafnew** [comment]
hy_0943 已经给予权限，请上传测试条目。

**Comment by redleafnew** [comment]
另外，请详细列出与202的区别，原来是什么→改为什么。

**Comment by artemith** [comment]
> hy_0943 已经给予权限，请上传测试条目。

已上传

> 另外，请详细列出与202的区别，原来是什么→改为什么。

- **文中引用**

<html>
<body>
<!DOCTYPE html>

  | 中文 | 英文
-- | -- | --
一个作者 |   |  
两个作者 | （刘煜辉、沈可挺，2011）→（刘煜辉和沈可挺，2011） |  
三个作者 |   | （Hsu et al., 2014）→ （Hsu *et al*., 2014）


</body>
</html>


- **文末参考文献**
  - （1）... -> ...
  > 去掉序号
  - 邵新建、王兴春、贾中正、廖静池：《投资银行—机构投资者关系、“捧场”与IPO中的利益问题》，《金融研究》，2019年第11期。→ 邵新建、王兴春、贾中正、廖静池（2019）：《投资银行—机构投资者关系、“捧场”与IPO中的利益问题》，《金融研究》第11期。
  > 年份变化
  - （40）Ball, R. and Brown, P., 1968, “An Empirical Evaluation of Accounting Income Numbers”, *Journal of Accounting Research*, 6(2), pp.159~178. → Ball, R. and Brown, P. “An Empirical Evaluation of Accounting Income Numbers.” *Journal of Accounting Research*, 1968, 6(2), pp.159-178.
  > 年份位置调整
  > 作者名与文章名之间之后只有" "
  > 文章名的引号内最后有一个"."
  > 文章名与期刊名之间以" "相连
  > 页码的波浪线变为直线
  > 页码的"pp."与数字之间有一个空格

  - Barth, M. E., Clinch, G. and Israeli, D., 2016, “What Do Accruals Tell Us About Future Cash Flows?”, *Review of Accounting Studies*, 21(3), pp.768~807.→ Barth, M. E.; Clinch, G. and Israeli, D. “What Do Accruals Tell Us About Future Cash Flows?” *Review of Accounting Studies*, 2016, 21(3), pp. 768-807. 
  > 第一个作者名与第二个作者名之间间隔的","变为";"

**Comment by redleafnew** [comment]
制作中...

**Comment by redleafnew** [comment]
> 文章名的引号内最后有一个"."
把<text variable="title" text-case="title" quotes="true"/>改为 `<text variable="title" text-case="title" prefix="&quot;" suffix=".&quot;"/>`实现的，否则这个`.`一直不能在引号内。
但我在在线编辑器试APA的，`title` `quotes="true"` 的`.`可以在引号内，不知道怎么回事。
@zepinglee

**Comment by redleafnew** [comment]
@artemith 现在是这个效果了，还需要改什么？
（Bartov _et al_.，2002）
（陆铭和冯皓，2014）
（Alesina _et al._，2004）
（Ball and Brown，1968）
（Baron，1982）
（吕怀立等，2021）
（刘煜辉和沈可挺，2011）
（宋顺林，2022）

Unique citation
（Bartov _et al._，2002；陆铭和冯皓，2014；Alesina _et al._，2004；Ball and Brown，1968；Baron，1982；吕怀立等，2021；刘煜辉和沈可挺，2011；宋顺林，2022）

Bibliography
刘煜辉、沈可挺（2011）：《是一级市场抑价,还是二级市场溢价——关于我国新股高抑价的一种检验和一个解释》，《金融研究》第11期。
陆铭、冯皓（2014）：《集聚与减排:城市规模差距影响工业污染强度的经验研究》，《世界经济》第7期。
吕怀立、贾琬娇、李婉丽（2021）：《核准制保荐经历与科创板IPO定价——来自保荐代表人的经验证据》，《会计研究》第5期。
宋顺林（2022）：《中国式IPO定价：一个文献综述》，《中央财经大学学报》第1期。
Alesina, A., Di Tella, R. and MacCulloch, R. "Inequality and Happiness: Are Europeans and Americans Different?" Journal of Public Economics, 2004, 88(9) pp. 2009-2042.
Ball, R. and Brown, P. "An Empirical Evaluation of Accounting Income Numbers." Journal of Accounting Research, 1968, 6(2) pp. 159-178.
Baron, D. P. "A Model of the Demand for Investment Banking Advising and Distribution Services for New Issues." The Journal of Finance, 1982, 37(4) pp. 955-976.
Bartov, E., Mohanram, P. and Seethamraju, C. "Valuation of Internet Stocks—An IPO Perspective." Journal of Accounting Research, 2002, 40(2) pp. 321-346.

**Comment by artemith** [comment]
>（Bartov et al.，2002；陆铭和冯皓，2014；Alesina et al.，2004；Ball and Brown，1968；Baron，1982；吕怀立等，2021；刘煜辉和沈可挺，2011；宋顺林，2022）
- 这里多个文献的顺序官网没有明说，但是参考我提供的期刊论文，规则应该是“先英文后中文，其次是年份，最后作者姓氏首字母”的顺序排列。附上论文中的截图
![image](https://user-images.githubusercontent.com/14881525/215981398-eb88f79d-128c-4da0-abe6-14aa9e89388f.png)
![image](https://user-images.githubusercontent.com/14881525/215981471-73c7707a-a5e6-490d-aa93-fcf72dd95921.png)

> Bibliography 刘煜辉、沈可挺（2011）：《是一级市场抑价,还是二级市场溢价——关于我国新股高抑价的一种检验和一个解释》，《金融研究》第11期。 陆铭、冯皓（2014）：《集聚与减排:城市规模差距影响工业污染强度的经验研究》，《世界经济》第7期。 吕怀立、贾琬娇、李婉丽（2021）：《核准制保荐经历与科创板IPO定价——来自保荐代表人的经验证据》，《会计研究》第5期。 宋顺林（2022）：《中国式IPO定价：一个文献综述》，《中央财经大学学报》第1期。 Alesina, A., Di Tella, R. and MacCulloch, R. "Inequality and Happiness: Are Europeans and Americans Different?" Journal of Public Economics, 2004, 88(9) pp. 2009-2042. Ball, R. and Brown, P. "An Empirical Evaluation of Accounting Income Numbers." Journal of Accounting Research, 1968, 6(2) pp. 159-178. Baron, D. P. "A Model of the Demand for Investment Banking Advising and Distribution Services for New Issues." The Journal of Finance, 1982, 37(4) pp. 955-976. Bartov, E., Mohanram, P. and Seethamraju, C. "Valuation of Internet Stocks—An IPO Perspective." Journal of Accounting Research, 2002, 40(2) pp. 321-346.
- 这里英文期刊名应该是斜体（或许是您复试的时候格式消失了）。

**Comment by redleafnew** [comment]
> 正文中排名修改：

（Alesina _et al._，2004；Ball and Brown，1968；Baron，1982；Bartov _et al._，2002；刘煜辉和沈可挺，2011；陆铭和冯皓，2014；吕怀立等，2021；宋顺林，2022）

> 这里英文期刊名应该是斜体
复制时消失了。

**Comment by artemith** [comment]
> > （Bartov et al.，2002；陆铭和冯皓，2014；Alesina et al.，2004；Ball and Brown，1968；Baron，1982；吕怀立等，2021；刘煜辉和沈可挺，2011；宋顺林，2022）
> 
> * 这里多个文献的顺序官网没有明说，但是参考我提供的期刊论文，规则应该是“先年份，后作者姓氏首字母”的顺序排列。附上论文中的截图
>   ![image](https://user-images.githubusercontent.com/14881525/215981398-eb88f79d-128c-4da0-abe6-14aa9e89388f.png)
>   ![image](https://user-images.githubusercontent.com/14881525/215981471-73c7707a-a5e6-490d-aa93-fcf72dd95921.png)
>   ![image](https://user-images.githubusercontent.com/14881525/215983652-c8bf7d0e-3736-47a3-a560-e8b250bcdca2.png)

前面这里顺序搞错了，又找了一篇期刊，更新了一下规则

**Comment by redleafnew** [comment]
（Ball and Brown，1968；Baron，1982；Bartov et al.，2002；Alesina et al.，2004；刘煜辉和沈可挺，2011；陆铭和冯皓，2014；吕怀立等，2021；宋顺林，2022）

没有你的例子条目。

**Comment by redleafnew** [comment]
另外，集聚与减排:城市规模差距影响工业污染强度的经验研究 条目的作者录入有问题，在群组中改成正确的了。

**Comment by artemith** [comment]
> （Ball and Brown，1968；Baron，1982；Bartov et al.，2002；Alesina et al.，2004；刘煜辉和沈可挺，2011；陆铭和冯皓，2014；吕怀立等，2021；宋顺林，2022）
> 
> 没有你的例子条目。

![image](https://user-images.githubusercontent.com/14881525/215992992-e72dde89-4f46-4ad8-a9d6-da694770a422.png)
刚才将这个截图中的条目导入了群组

**Comment by redleafnew** [comment]
里面的et al都是斜体。

（刘生龙和胡鞍钢，2011）
（丁从明等，2018）
（Herrmann-Pillath et al.，2014）
（范欣等，2017）

Unique citation
（刘生龙和胡鞍钢，2011；Herrmann-Pillath et al.，2014；范欣等，2017；丁从明等，2018）

Bibliography
丁从明、吉振霖、雷雨、梁甄桥（2018）：《方言多样性与市场一体化:基于城市圈的视角》，《经济研究》第11期。
范欣、宋冬林、赵新宇（2017）：《基础设施建设打破了国内市场分割吗?》，《经济研究》第02期。
刘生龙、胡鞍钢（2011）：《交通基础设施与中国区域经济一体化》，《经济研究》第03期。
Herrmann-Pillath, C., Libman, A. and Yu, X. "Economic Integration in China: Politics and Culture." Journal of Comparative Economics, 2014, 42(2) pp. 470-492.

**Comment by artemith** [comment]
> Herrmann-Pillath, C., Libman, A. and Yu, X. "Economic Integration in China: Politics and Culture." Journal of Comparative Economics, 2014, 42(2) pp. 470-492.
我看还有两个问题：
- 三个作者时，第一个作者和第二个作者之间用";"来间隔
- 期刊号与页码之间有","

修正后的格式应该为
Herrmann-Pillath, C.; Libman, A. and Yu, X. "Economic Integration in China: Politics and Culture." *Journal of Comparative Economics*, 2014, 42(2), pp. 470-492.

**Comment by redleafnew** [comment]
Herrmann-Pillath, C.; Libman, A. and Yu, X. "Economic Integration in China: Politics and Culture." _Journal of Comparative Economics_, 2014, 42(2) , pp. 470-492.

**Comment by artemith** [comment]
> Herrmann-Pillath, C.; Libman, A. and Yu, X. "Economic Integration in China: Politics and Culture." Journal of Comparative Economics, 2014, 42(2) , pp. 470-492.

感谢您的耐心修改，我发现最后有两点不同：

- pp前的","前仿佛多了一个空格？
- 英文bibliography里文章的引号应该是中文的引号

附上官网里的示例和期刊文献里的截图
- 官网示例
第一作者Family name, First name; 第二作者Family name, First name and 第三作者Family name, First name. “The Title of the Article.” The Name of the Journal or Newspaper, the time, pp. XX-XX.
- 期刊文献截图
![image](https://user-images.githubusercontent.com/14881525/216003461-b56c45de-4d84-4336-918c-a52200fed573.png)

**Comment by redleafnew** [comment]
Herrmann-Pillath, C.; Libman, A. and Yu, X. “Economic Integration in China: Politics and Culture.” Journal of Comparative Economics, 2014, 42(2), pp. 470-492.

引号好像需要在Word中将字体修改为宋体才可以。

**Comment by artemith** [comment]
现在我看没什么问题了，就关闭了

**Comment by artemith** [comment]
> Herrmann-Pillath, C.; Libman, A. and Yu, X. “Economic Integration in China: Politics and Culture.” Journal of Comparative Economics, 2014, 42(2), pp. 470-492.
> 
> 引号好像需要在Word中将字体修改为宋体才可以。

最后再次感谢您！

**Comment by redleafnew** [comment]
已上传为216
