### ISSUE TITLE
学位论文缩进问题

### ISSUE THREAD

**Issue by TangHUST** [redleafnew/Chinese-STD-GB-T-7714-related-csl#123]
**描述错误**

CSL 样式：418huazhong-university-of-science-and-technology.csl

参考文献在个位数时，缩进格式正确，但参考文献达到两位甚至三位数时缩进显示错误。

**屏幕截图**

![6T~{3F2A0MGTNU7U435(YGK](https://user-images.githubusercontent.com/79521568/217239152-02c856b4-00a3-46e6-befa-bdacb51f60e0.png)
可能是由于序号增加了一位，导致序号后的空格位置减少

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by TangHUST** [comment]
模板里似乎是显示首行缩进2.36字符

**Comment by zepinglee** [comment]
缩进是在 word 中设置的，CSL 无法控制。序号后的符号不是空格而是制表符，你需要同时修改“悬挂缩进”和“制表符宽度”两个参数（比如设成稍微宽一点的 3.5字宽）才能完美对齐。

**Comment by TangHUST** [comment]
谢谢解答，我研究一下------------------------------------------------------------------
发件人：Zeping ***@***.***>
日　期：2023年02月07日 20:17:58
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 学位论文缩进问题 (Issue #123)

缩进是在 word 中设置的，CSL 无法控制。序号后的符号不是空格而是制表符，你需要同时修改“悬挂缩进”和“制表符宽度”两个参数（比如设成稍微宽一点的 3.5字宽）才能完美对齐。

**Comment by Anphetamine** [comment]
> **描述错误**
> 
> CSL 样式：418huazhong-university-of-science-and-technology.csl
> 
> 参考文献在个位数时，缩进格式正确，但参考文献达到两位甚至三位数时缩进显示错误。
> 
> **屏幕截图**
> 
> ![6T~{3F2A0MGTNU7U435(YGK](https://user-images.githubusercontent.com/79521568/217239152-02c856b4-00a3-46e6-befa-bdacb51f60e0.png) 可能是由于序号增加了一位，导致序号后的空格位置减少
> 
> **其他相关信息**
> 
> 在此处添加有关该问题的其他信息。

同学你好，请问你知道如何修改了吗？我试了好多次还是不行，和模板相比，的编号后与文字之间的距离还是很小

**Comment by TangHUST** [comment]
还是只能调整制表符和悬挂缩进的字符，我调整的是制表符0.8字符，接着去调整合适的悬挂缩进量，看起来和论文模板差不多的。我是这样操作的

**Comment by Anphetamine** [comment]
非常感谢你的回复，我去试试看

**Comment by zepinglee** [comment]
> 还是只能调整制表符和悬挂缩进的字符，我调整的是制表符0.8字符，接着去调整合适的悬挂缩进量，看起来和论文模板差不多的。我是这样操作的

先调悬挂缩进的宽度，再调制表符宽度，跟缩进设成一样才能对对齐。
