### ISSUE TITLE
英文文献不能自动切换et al.

### ISSUE THREAD

**Issue by lon91ong** [redleafnew/Chinese-STD-GB-T-7714-related-csl#126]
**描述错误**

CSL 样式：[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)

英文文献默认语言为空的情况下，依旧使用“等”没有使用“et al.”
必须手动设置语言为“en”或“en-us”才行，“English”都不行

**Comment by zepinglee** [comment]
> 英文文献默认语言为空的情况下，依旧使用“等”没有使用“et al.” 

这里设置了默认语言为 `zh-CN`。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/4805b409eedd483d6a284ef09439005733a6cdfa/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L2

> 必须手动设置语言为“en”或“en-us”才行，“English”都不行

Zotero （<https://www.zotero.org/support/kb/item_types_and_fields#general_fields>）要求 `language` 字段为 “two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) (e.g., en-US for American English, or de-DE for German)”。

可以用茉莉花插件批量设置语言。

**Comment by lon91ong** [comment]
Zotero插件采集的文献信息中，中文文献默认都由语言信息，`中文;`或`zh-CN`；
英文文献多有语言信息为空的，或者`en`, `English`

希望能改进一下

**Comment by zepinglee** [comment]
> Zotero插件采集的文献信息中，中文文献默认都由语言信息，`中文;`或`zh-CN`；

`中文;` 不合规范，建议向对应的 translator 作者反馈信息。

> 英文文献多有语言信息**为空**的，或者`en`, `English`

提供两种方案：

1. 将 CSL 样式的默认语言改为 `en-US`，这样 `language` 为空的条目会使用默认的英文格式。另外需要将 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/4805b409eedd483d6a284ef09439005733a6cdfa/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L433-L436> 的 `en` 改为 `zh`，参考 <https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension>。
2. 使用茉莉花插件批量修改 `language` 字段。
