### ISSUE TITLE
cls安装错误

### ISSUE THREAD

**Issue by krisfans** [redleafnew/Chinese-STD-GB-T-7714-related-csl#127]
**描述错误**
CSL 样式：`002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl`  ，无法安装
**屏幕截图**
![Snipaste_2023-02-13_10-00-15](https://user-images.githubusercontent.com/57793534/218354548-0837fbca-56df-493f-aedd-3182b6c351bc.png)
**版本信息**
`zotero 6.0.20`

**Comment by krisfans** [comment]
zotero提示错误,不过在word好像也能用

**Comment by redleafnew** [comment]
正常的。有两个layout就是这样的提示。

**Comment by redleafnew** [comment]
正常的。有两个layout就是这样的提示。

**Comment by zepinglee** [comment]
我在 README 中加一些说明把。

**Comment by redleafnew** [comment]
这个主意好。
