### ISSUE TITLE
中英文引文中的空格问题

### ISSUE THREAD

**Issue by lianrongxu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#128]
7714-2015给的中文、英文示例都是没有空格的。知网导出的引文都是不加空格的，但google scholar给出的英文引文都是有空格的。英文引文中没有空格的话，不少地方通不过拼写检查，红色波浪线让人不舒服。最好的解决办法是一个csl文件，通过识别出文献的语言类型，然后决定加不加空格。

**Comment by zepinglee** [comment]
> 7714-2015给的中文、英文示例都是没有空格的。知网导出的引文都是不加空格的，但google scholar给出的英文引文都是有空格的。英文引文中没有空格的话，不少地方通不过拼写检查，红色波浪线让人不舒服。最好的解决办法是一个csl文件，通过识别出文献的语言类型，然后决定加不加空格。

参考 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/70> 的讨论，国标并非没有空格，而是空格不一致。除了空格，中文文献使用全角/半角符号也有争议。所以我们最后决定按照原标准作者的一份 slides 《[GB/T 7714一2015 的新点、实施要点及其他](http://www.cessp.org.cn/uploads/1/file/public/201607/20160705202202_0airiqt165.pdf)》的风格（原 URL 已经失效，slides 发在附件中）。

[GB:T 7714一2015的新点、实施要点及其他.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10779966/GB.T.7714.2015.pdf)

**Comment by lianrongxu** [comment]
接上。看了一些资料，没看到针对中文、文献的if...else...处理。
使用同一个CSL文件，中文引文去掉空格，英文引文保留空格，这是否可以实现，或实现思路是什么。

**Comment by zepinglee** [comment]
大概是将每个 macro 都复制一份，分别使用中文和英文的格式。

如果你打算在中文文献中使用西文符号，不建议去掉逗号。大部分字体的字体的西文逗号和点号不足半字宽，没有逗号的话显得太紧凑。除非你的期刊/学校要求使用这么紧凑的格式。

**Comment by lianrongxu** [comment]
感谢回复，已按此思路完成了样式修改，目前可以对中文、英文文献使用不同的符号。

**Comment by lianrongxu** [comment]
关键点是对不同的语种去调用不的entry-layout，然后在entry-layout中加载不同的macro
`
  <bibliography entry-spacing="0" et-al-min="4" et-al-use-first="3" second-field-align="flush">
    <layout suffix="." locale="en">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout-en"/>
    </layout>
    <layout suffix=".">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout"/>
    </layout>
  </bibliography>`

**Comment by lianrongxu** [comment]
完结，请关闭此条目吧。
