### ISSUE TITLE
CSL in Mendeley

### ISSUE THREAD

**Issue by YangSiri** [redleafnew/Chinese-STD-GB-T-7714-related-csl#129]
@redleafnew  

请问大佬的csl文件可以直接复制到mendeley吗？

我导入后，中英文文献排序功能没有保留（如207，416号csl），即：英文在前，中文在后，大佬会使用mendeley的CSL editor吗？

**Comment by redleafnew** [comment]
应该是可以，但是我没有测试过。他们好像都是用的同一个编辑器？

**Comment by YangSiri** [comment]
他好像有代码编辑器和界面编辑器；

那请问这个排序功能如何实现？导入您的csl无法在它的编辑器里编辑

**Comment by YangSiri** [comment]
需要给您原始XML代码吗？

**Comment by redleafnew** [comment]
不大了解它的csl，可以在https://editor.citationstyles.org/visualEditor/上测试。

**Comment by YangSiri** [comment]
是的，请问这个排序功能如何实现？

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/c7e64c4b32abe0a527b0c99287d59fd43127a3c8/207chinas-industrial-economics.csl#L326-L329
可以在这里面加个` <key variable= "language"/>`试试。

**Comment by YangSiri** [comment]
好像没有language这个变量

**Comment by redleafnew** [comment]
Zotero中有，csl中有的，M不清楚。

**Comment by YangSiri** [comment]
好像207的代码中没有这句？

**Comment by YangSiri** [comment]
好像207的代码中没有这句？

**Comment by redleafnew** [comment]
所以才加上啊

**Comment by YangSiri** [comment]
我的意思是原始的207不是带有这个功能吗？

另外，加上了好像也不行

**Comment by redleafnew** [comment]
M中不清楚

**Comment by YangSiri** [comment]
你是说这个要在zot的info中设置语言吗

**Comment by redleafnew** [comment]
是的。也可以用这个插件设置语言。
导出附件，删除条目时删除附件，自动根据题目批量修改语言的插件：https://github.com/redleafnew/delitemwithatt

**Comment by YangSiri** [comment]
好的 那这个顺序可以变吗？比如想要中文的在前还是英文的在前面

**Comment by redleafnew** [comment]
在Zotero中是可以的，有升级降序的参数。

**Comment by YangSiri** [comment]
那在代码里怎么写？

<key variable= "language"/>

**Comment by redleafnew** [comment]
https://docs.citationstyles.org/en/stable/specification.html

**Comment by YangSiri** [comment]
好的 我学习一下 麻烦您了

**Comment by redleafnew** [comment]
参考这个写法
```
<citation>
  <sort>
    <key macro="author" names-min="3" names-use-first="3"/>
    <key variable="issued" sort="descending"/>
  </sort>
  <layout>
    <!-- rendering elements -->
  </layout>
</citation>
```

**Comment by YangSiri** [comment]
明白
