### ISSUE TITLE
正文内连续引用两个文献上标显示样式问题

### ISSUE THREAD

**Issue by lianrongxu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#130]
CSL 样式：002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl
错误描述：正文内连续引用两个文献时上标样式为[1,2]
相关参考：GB/T 7714-2015标准的第14页，以及北京师范大学学报(自然科学版)编辑部陈浩元编辑的[《GB/T 7714一2015 的新点、实施要点及其他》](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10779966/GB.T.7714.2015.pdf)第52-53张PPT均指出对连续引用两个文献的上标形式应为[1-2]。
解决目标：把上标的[1,2]形式修改为[1-2]形式
进一步说明：对于连续引用3个（包括）及以上文献时，会生成[1-3]样式。但未在CSL文档中找到相关设定的地方。

**Comment by zepinglee** [comment]
是的，但 CSL 无法控制两个连续编号之间的分隔符。

**Comment by lianrongxu** [comment]
好像是程序硬编码的，没有提供配置选项。
既然无解，关闭此条吧。
