### ISSUE TITLE
生成的样式中序号和作者之间的空格是tab产生的 不是正常的空格，请问这个可以在csl中修改吗？

### ISSUE THREAD

**Issue by she529** [redleafnew/Chinese-STD-GB-T-7714-related-csl#131]
**描述错误**

CSL 样式：xxx-xxx-xxx.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```
![屏幕截图 2023-03-01 121409](https://user-images.githubusercontent.com/75371769/222043548-b055ee48-d89d-435a-9d76-07fe39309c7b.png)
而正常的应该是
![image](https://user-images.githubusercontent.com/75371769/222043634-87e38b77-1da7-4a97-aaf3-aa883b368b70.png)

**Comment by zepinglee** [comment]
空格在序号位数变化时不能对齐。正确的方法是使用制表符（tab），并且将制表符宽度和悬挂缩进设成相同的距离。

<img width="237" alt="Screenshot 2023-03-01 at 15 00 47" src="https://user-images.githubusercontent.com/12290822/222067339-82d5aae8-1e5d-4e83-ae21-5309106bbf01.png">

**Comment by redleafnew** [comment]
我原来试图将Tab换为空格，但效果很差，所以还是用tab合适。

**Comment by she529** [comment]
> 我原来试图将Tab换为空格，但效果很差，所以还是用tab合适。

ok  谢谢  明白了
