### ISSUE TITLE
电子科大的样式中会议名会出现两个

### ISSUE THREAD

**Issue by XDhyao** [redleafnew/Chinese-STD-GB-T-7714-related-csl#132]
**描述错误**

CSL 样式：university-of-electronic-science-and-technology-of-china.csl

插入的会议论文题目会出现两次，是因为’title‘和’container-title‘显示的是一样的东西，都是论文题目，如下图所示。我删除<text variable="title"/>之后显示正常。
此外，我发现我导入的是英文论文，采用的样式是对应下面那一块的代码，我对比了中文和英文的样式代码是一样的，不知道这个会不会有什么bug，目前我的论文里没有什么问题

![image](https://user-images.githubusercontent.com/52654892/222712663-3f6b9893-560c-4720-8aa4-133bd0031732.png)

**Comment by zepinglee** [comment]
`title` 是论文标题，`container-title` 是会议论文集的标题。参考 <https://docs.citationstyles.org/en/stable/specification.html#standard-variables>。

**Comment by XDhyao** [comment]
> `title` 是论文标题，`container-title` 是会议论文集的标题。参考 https://docs.citationstyles.org/en/stable/specification.html#standard-variables。

非常感谢给出的连接，很有用。我不知道别的软件是怎么回事，我用的mendeley，没有论文集的名字，我用这个csl文件会有两个论文名，而且还是连在一起的，中间没有别的符号隔开。不知道是不是不适用mendeley

**Comment by zepinglee** [comment]
> 我用的mendeley，没有论文集的名字

不应该呀，是不是文献类型选错了？

> 我用这个csl文件会有两个论文名，而且还是连在一起的，中间没有别的符号隔开。

建议将该文献的字段信息截图发上来，以及输出的格式化的参考文献。

> 不知道是不是不适用mendeley

Mendeley 应该也是将文献数据转为 CSL-JSON 格式交给 citeproc-js 处理的，按理是兼容的。你试一下将文献导出为 CSL-JSON 格式贴上来（如果可以）。

**Comment by XDhyao** [comment]
> 

![image](https://user-images.githubusercontent.com/52654892/222745238-9d7cc455-00aa-48e9-a54d-d6b7e1a38f8e.png)
我的mendeley里面是这样的

![image](https://user-images.githubusercontent.com/52654892/222745368-af2c258c-758d-428a-9585-089fa561c0dc.png)
目前删除掉csl文件里的title，word里的文档是这样的

![image](https://user-images.githubusercontent.com/52654892/222746345-5ac35903-e9da-4b42-b41e-7f4189ad8219.png)
删除之前是这个样子，论文名重复且连接在一起

![image](https://user-images.githubusercontent.com/52654892/222745608-862c6553-63fa-4c32-ac7c-ecd99e0fea07.png)
删除之后的csl文件对应位置是这样的，其他东西没有变化。

我没有在csl文件修改的这一段代码里面找到对应的会议名是哪个变量，但是word里面确实有会议名。

**Comment by zepinglee** [comment]
这个“Conference Proceedings”类型有些奇怪呀。你将文献导出为 CSL-JSON 或者 BibTeX 贴上来？

**Comment by XDhyao** [comment]
> 这个“Conference Proceedings”类型有些奇怪呀。你将文献导出为 CSL-JSON 或者 BibTeX 贴上来？

![image](https://user-images.githubusercontent.com/52654892/222752343-5c5220e1-631b-44b3-8ce3-6ab894077d95.png)
bibtex是这样的

**Comment by zepinglee** [comment]
把文字贴过来，我转到 Zotero 中试一下。

**Comment by XDhyao** [comment]
> 把文字贴过来，我转到 Zotero 中试一下。

@inproceedings{Wang2017,
archivePrefix = {arXiv},
arxivId = {1704.06904},
author = {Wang, Fei and Jiang, Mengqing and Qian, Chen and Yang, Shuo and Li, Cheng and Zhang, Honggang and Wang, Xiaogang and Tang, Xiaoou},
booktitle = {Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},
doi = {10.1109/CVPR.2017.683},
eprint = {1704.06904},
file = {:D\:/Downloads/Residual_Attention_Network_for_Image_Classification.pdf:pdf},
isbn = {9781538604571},
pages = {6450--6458},
title = {{Residual attention network for image classification}},
volume = {2017-Janua},
year = {2017}
}

**Comment by zepinglee** [comment]
我能复现这个问题。看了一下 CSL 的代码，发现下面这两行重复了。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/6811da2c58170384c6de3dc69ff4488c6b4ebaed/427university-of-electronic-science-and-technology-of-china.csl#L333

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/6811da2c58170384c6de3dc69ff4488c6b4ebaed/427university-of-electronic-science-and-technology-of-china.csl#L394

**Comment by zepinglee** [comment]
这是 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/6a71fea9947dca3da066b661ec3004bf0d3c7d24> 中我尝试修复一些无效的变量名导致的。应该将这些 `<text variable="*"/>` 删掉。

**Comment by zepinglee** [comment]
@XDhyao 试一下 [4b1d37f](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/4b1d37f646b874ad1fe2c24dfdf068adb8d59f8f) 修改后的版本？

426～435 的样式没有经过完整测试（见 #106），可能还存在其他问题，欢迎及时反馈。

**Comment by XDhyao** [comment]
> @XDhyao 试一下 [4b1d37f](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/4b1d37f646b874ad1fe2c24dfdf068adb8d59f8f) 修改后的版本？
> 
> 426～435 的样式没有经过完整测试（见 #106），可能还存在其他问题，欢迎及时反馈。

ok，我删掉了<text variable="title"/>，目前没有问题了，我之前以为container-title也是论文名，不好意思
