### ISSUE TITLE
CSL的sort相关的语法问题

### ISSUE THREAD

**Issue by Ziheng56** [redleafnew/Chinese-STD-GB-T-7714-related-csl#133]
操作：（基于GB7714-2015-numeric）Zotero中的CSL的bibliography 下的sort下根据variable=“language”进行排序。Zotero中已经把中文文献的language改成C，英文文献改成en了。（如图1）
![图1](https://user-images.githubusercontent.com/77152768/222940617-af2b933a-d94b-4194-90a7-9fdf0fa2e04a.png)

不想要的结果：正文中的引用序号变了：原来是1234，现在变成bibliography中出现的顺序了。（如图2）
<img width="1277" alt="图2" src="https://user-images.githubusercontent.com/77152768/222940618-9fe23ce5-73a1-4ea7-bb92-cb1e585db5f5.png">

想要实现的结果：bibliography中数字是按照文中出现顺序排列，同时分为两个组，中文文献和英文文献。类似用endnote的categrorize实现的效果.（如图3）

<img width="1280" alt="图3" src="https://user-images.githubusercontent.com/77152768/222940622-46f68720-97c4-47c1-9473-b402298fd222.png">

**Comment by zepinglee** [comment]
CSL 无法实现。而且几乎没有期刊用这种分组格式的。

**Comment by redleafnew** [comment]
我试着也出不了这种效果

**Comment by Ziheng56** [comment]
那请问bibliography先按照language排序如何不影响正文中序号的顺序，即正文中还是12345的顺序。

**Comment by redleafnew** [comment]
应该是无法实现。

**Comment by Ziheng56** [comment]
嗯嗯 感谢您的解答

**Comment by Ziheng56** [comment]
> CSL 无法实现。而且几乎没有期刊用这种分组格式的。



> 应该是无法实现。

感谢您的解答。

**Comment by Ziheng56** [comment]
> CSL 无法实现。而且几乎没有期刊用这种分组格式的。

感谢您的解答

**Comment by redleafnew** [comment]
如果正文中的作者年代的，这样倒是可以。

**Comment by Ziheng56** [comment]
> 如果正文中的作者年代的，这样倒是可以。

正文中是（author，1998）这样的吗

**Comment by redleafnew** [comment]
是的。

**Comment by Ziheng56** [comment]
> 

嗯嗯 那我明白如何操作了的。谢谢。
