### ISSUE TITLE
申请新的csl样式-期刊-外国经济与管理

### ISSUE THREAD

**Issue by olivia0317** [redleafnew/Chinese-STD-GB-T-7714-related-csl#135]
**样式信息**

- 期刊： 外国经济与管理

- 英文名称：Foreign Economies and Management | Fore Econ Manag

- 参考文献格式要求的**官网**链接：https://qks.sufe.edu.cn/J/WJGL/Channel/19/CN

- （期刊的）ISSN 号： 1001-4950

- （期刊的）相关领域：Economies and Managemen，
- 设有“创业研究”、“创新研究”、“公司治理”、“营销”、“人力资源管理”、“战略管理”、“组织研究”、“公司财务”、“跨国经营”等栏目

**测试条目**

文中：
（王康等，2019）
（陈恒等，2018；许可等，2021；王海军等，2020）
（Jones等，2020）
（Gilly和Gelb，1982）

**参考文献（中文在前，英文在后，分别按首字母排序）
[1]姓名1，姓名2，姓名3.（作者超过3位的，英文文献用“,et al.”，中文文献用“,等.”）文题[来源代码].刊名、报纸名等，年份，卷数（期数）：起止页码.
以上为基本格式，具体要求见下面：

(1) 著作：[序号]主要责任者.文献题名[M].版本.出版地：出版者，出版年：起止页码（任选）.
示例：[1]Tom A Stewart. Intelligent capital: The new wealth of organizations[M]. London: Nicholas Bbready,1997.。

(2) 期刊文章：[序号] 主要责任者.文献题名[J].刊名，年，卷（期）：起止页码.
示例：[2]Speckman R E, Hesterly J M. Alliance management: A view from the past and a look to the future[J]. Journal of Management Studies, 1998, 35(6):102-110.；[3]范秀成,杜琰琰.顾客参与是一把“双刃剑”——顾客参与影响价值创造的研究述评[J].管理评论，2012,24（12）：64-71.。

(3) 报纸文章：[序号] 主要责任者.文献题名[N].报纸名，出版日期（版次）.

(4) 论文集中的析出文章：[序号]析出文献主要责任者.析出文献题名[A].原文献主要责任者.原文献题名[C].出版地：出版者，出版年：析出文献起止页码.
示例：[4]Hewison K. Emerging social forces in Thailand[A]. in Robison R, Goodman D S G(Eds.). The new rich in Asia: Mobile phones, McDonald’s and middle-class revolution[C]. London: Routledge, 1996: 137-140.。

(5) 译著：[序号]（国名或地区）主要责任者，译者.文献题名[M].出版地：出版者，出版年：起止页码（任选）.

（6）工作论文：[序号] 主要责任者.文献题名[R].Working Paper，年份.

(7) 电子文献：主要责任者.电子文献题名[EB/OL].文献出处或可获得地址，发表或更新.**

**Comment by zepinglee** [comment]
请将测试条目录入到 Zotero 中并传到 https://www.zotero.org/groups/4677213/chinese_csl_development 群组。

**Comment by olivia0317** [comment]
尊敬的zotero的csl文件开发者，由于平时使用zotero不太多，运用的不是很熟练，不知如何将测试条目录入到zotero中，请问是否有具体的操作步骤或指南可以分享？不胜感激～～

**Comment by zepinglee** [comment]
> 由于平时使用zotero不太多，运用的不是很熟练，不知如何将测试条目录入到zotero中，请问是否有具体的操作步骤或指南可以分享？

那你需要 CSL 样式用于哪个软件？跟你正常录入文献一样，在 google scholar/知网等网站搜索，使用 Zotero Connector 导入；或者在 Zotero 中新建文献，填入字段信息。

参考 <http://www.mwm.net.cn/Web/Format> 和 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/8QMGX3PR>，我们需要 [tests/styles/202journal-of-management-world/test-data.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/202journal-of-management-world/test-data.json) 这样结构化的数据，生成 [tests/styles/202journal-of-management-world/README.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/202journal-of-management-world/README.md) 的结果跟原格式要求进行比较，用于测试 CSL 样式。

**Comment by redleafnew** [comment]
上传了吗？
@olivia0317

**Comment by olivia0317** [comment]
不好意思，我加入群组之后，我的zotero突然增加很多文献，导致我无法正常使用了。我只好退出群组。最后决定，找一个相近的csl文件，然后手工改动。非常感谢您还在关心这件事～～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月29日 11:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请新的csl样式-期刊-外国经济与管理 (Issue #135) |

上传了吗？
@olivia0317

**Comment by redleafnew** [comment]
ok
