### ISSUE TITLE
422CAAS：参考文献作者首字母排序混乱

### ISSUE THREAD

**Issue by butsnow** [redleafnew/Chinese-STD-GB-T-7714-related-csl#136]
**描述错误**

CSL 样式：422caas-thesis.csl

已调整zotero条目语言为zh-CN，Word文档里语言是US
引用后文末作者首字母排序混乱，同首字母下也混乱（“王彦林”应该在“王林”后）
麻烦大佬帮忙检查一下到底哪里又出问题了，万分感谢！

**屏幕截图**

![image](https://user-images.githubusercontent.com/116549714/224468783-a2cd06c9-2ce3-400d-b63f-b20bbad156cd.png)

**条目信息**

[422caas-首字母排序-导出的条目.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10947792/422caas-.-.zip)

**Comment by zepinglee** [comment]
参考文献表是要求中文在前、英文在后吗？

**Comment by butsnow** [comment]
是的，中文在前，英文在后，中英文分别按照作者首字母排序
“中文文献在前，英文文献在后，按字顺和出版年排序。”


..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 422CAAS：参考文献作者首字母排序混乱 (Issue #136)





 
参考文献表是要求中文在前、英文在后吗？

**Comment by zepinglee** [comment]
试一下 821590b 的效果？

**Comment by butsnow** [comment]
感谢大佬，更新后参考文献顺序正常了！
但是我还有点疑问，之前试用是完全好用的，怎么就突然不能用了呢？是我哪个插件又自动更新什么了吗？
以下是我的现有插件







..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 422CAAS：参考文献作者首字母排序混乱 (Issue #136)





 
试一下 821590b 的效果？

**Comment by zepinglee** [comment]
> 但是我还有点疑问，之前试用是完全好用的，怎么就突然不能用了呢？

没明白你的意思，什么是“突然不能用”？

**Comment by butsnow** [comment]
之前参考文献顺序都是正常的，中间也没有更改csl文件
今天更新了文末的参考文献，首字母顺序就是乱的了




..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 晚上7:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 422CAAS：参考文献作者首字母排序混乱 (Issue #136)





  
但是我还有点疑问，之前试用是完全好用的，怎么就突然不能用了呢？
  
没明白你的意思，什么是“突然不能用”？

**Comment by zepinglee** [comment]
不清楚，原来的代码有问题。
