### ISSUE TITLE
重庆大学研究生学位论文

### ISSUE THREAD

**Issue by TOMsworkspace** [redleafnew/Chinese-STD-GB-T-7714-related-csl#138]
**样式信息**

- 期刊/学校名称：[重庆大学研究生学位论文]

- 英文名称：[ChongQing University]

- **官网**链接[<https://cqu.edu.cn/>]

- 参考文献格式要求的**官网**链接[<http://hgxy.cqu.edu.cn/info/1216/2950.htm>]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:shytom

**其他样式信息**

**Comment by zepinglee** [comment]
<img width="854" alt="Screenshot 2023-03-11 at 18 59 16" src="https://user-images.githubusercontent.com/12290822/224480487-8ea31d1a-6252-4b27-b86c-e1692582c883.png">

已提升为管理员。

**Comment by TOMsworkspace** [comment]
已上传参考引用文献

**Comment by zepinglee** [comment]
<img width="639" alt="Screenshot 2023-03-11 at 20 05 30" src="https://user-images.githubusercontent.com/12290822/224483401-bc9f0c02-3892-4703-b622-1467cfc471ec.png">

这几篇文献对应了官网 <http://hgxy.cqu.edu.cn/info/1216/2950.htm> 的示例文献，其余的是来自哪里？

**Comment by zepinglee** [comment]
另外我注意到你们学校在 2019 年修订了格式要求（<http://www.cfl.cqu.edu.cn/info/1367/8626.htm>），建议确认一下你们学院依然要使用 2007 年版。

**Comment by TOMsworkspace** [comment]
多余的文献是为了测试英文文献引用情况。 关于具体版本的格式要求，确认后回复。

**Comment by TOMsworkspace** [comment]
确认使用2019版的格式要求，使用其中的顺序编码制进行排版

示例参考文献已更新

2019版参考文献格式要求的官网链接[http://www.cfl.cqu.edu.cn/info/1367/8626.htm]

**Comment by zepinglee** [comment]
> 确认使用2019版的格式要求，使用其中的顺序编码制进行排版

幸好我搜了一下，不然就做无用功了。

> 示例参考文献已更新

好滴感谢！

**Comment by zepinglee** [comment]
简单看了一下，主要部分跟国标一致，可以在 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 的基础上修改。专利、标准、报纸、电子文献的格式有细节的修改。

<img width="640" alt="Screenshot 2023-03-13 at 20 25 22" src="https://user-images.githubusercontent.com/12290822/224701289-84ad3e97-30d2-4131-86a1-03742f478bf1.png">

其次是英文姓名的格式需要修改：

**Comment by zepinglee** [comment]
已添加 [444chongqing-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/444chongqing-university.csl)。完整的测试结果见 [tests/styles/444chongqing-university/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/444chongqing-university/test.md)。

@TOMsworkspace 试一试有没有别的问题。
