### ISSUE TITLE
001 GB/T 7714—2015 著者-出版年制的文中引用可否更改为中文括号？

### ISSUE THREAD

**Issue by rheasteele** [redleafnew/Chinese-STD-GB-T-7714-related-csl#139]
CSL 样式：001gb-t-7714-2015-author-date-bilingual.csl

非常感谢作者的无私付出！

不过在论文插入文献过程中需要更改文中引用为中文括号。
如(杨保军, 2012)
修改为（杨保军, 2012）

我导入到csl编辑器中想做修改，但是显示错误，错误信息为“Citeproc exception: TypeError: Cannot read properties of undefined (reading 'suppress_decorations')”

**Comment by redleafnew** [comment]
是哪个期刊或学校的要求

**Comment by rheasteele** [comment]
中国科学院大学

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/440university-of-chinese-academy-of-sciences.csl

**Comment by rheasteele** [comment]
谢谢作者，不过可能各学科要求不一样，我在此基础上再更改一下，谢谢！

**Comment by redleafnew** [comment]
欢迎修改后提交的仓库

**Comment by zepinglee** [comment]
> CSL 样式：001gb-t-7714-2015-author-date-bilingual.csl
> 
> 非常感谢作者的无私付出！
> 
> 不过在论文插入文献过程中需要更改文中引用为中文括号。 如(杨保军, 2012) 修改为（杨保军, 2012）

需要修改这里的标点符号
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/0b829559a6e07e5e62885c9a82bf2f2021ea66d6/001gb-t-7714-2015-author-date-bilingual.csl#L461-L466

> 我导入到csl编辑器中想做修改，但是显示错误，错误信息为“Citeproc exception: TypeError: Cannot read properties of undefined (reading 'suppress_decorations')”

哪个“csl编辑器”？

**Comment by Sharon2023s** [comment]
同问这个问题，求小土解答
“Citeproc exception: TypeError: Cannot read properties of undefined (reading 'suppress_decorations')”

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/139#issuecomment-1464907623 
按这个来修改

**Comment by Sharon2023s** [comment]
> 

确实，直接在zotero样式编辑器里可以直接把半角括号改成全角
不知道为啥，在citationstyles visualEditor里不可以
