### ISSUE TITLE
缩进的问题？

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#14]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/china-national-standard-gb-t-7714-2015-numeric.csl
对应的缩进如下：
![image](https://user-images.githubusercontent.com/13982749/140703742-0d11885d-96da-4705-9a9f-2b948cdd0aba.png)

https://raw.githubusercontent.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/main/china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl
对应的缩进如下：
![image](https://user-images.githubusercontent.com/13982749/140703823-5f435401-f6fd-47fc-8d01-d3f21ca82020.png)

其中，第二个应该统一为第一个吧，不知道应该修改代码哪里的部分？

**Comment by redleafnew** [comment]
https://docs.citationstyles.org/en/stable/specification.html#whitespace

**Comment by fredericky123** [comment]
上面两个文件中，second-field-align都是设置的flush，所以显示怎么不同呢？

**Comment by redleafnew** [comment]
可能的原因是` <text variable="citation-number" prefix="[" suffix="]"/>`这个字段的位置，是在macro中还是在layout中，显示的效果不同。第二个是放在了macro中，第一个是默认的在layout中。

**Comment by fredericky123** [comment]
> 可能的原因是` <text variable="citation-number" prefix="[" suffix="]"/>`这个字段的位置，是在macro中还是在layout中，显示的效果不同。第二个是放在了macro中，第一个是默认的在layout中。

我也有同感，感觉是第二个的宏导致将整个宏视为first field?
老师方便update第二个么

**Comment by redleafnew** [comment]
修改了。

**Comment by zepinglee** [comment]
> 请问最后一句，为什么要出现两个layout呢？

这是 citperoc-js 的扩展功能 <https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension>，可以提供多语言支持。

**Comment by fredericky123** [comment]
I see 这回搞明白了！
感谢！

**Comment by redleafnew** [comment]
@zepinglee 这个citperoc-js是怎么起作用的，我在电脑上搜不到这个文件，是集成到了Zotero还是集成到了Zotero工具条？

**Comment by redleafnew** [comment]
@zepinglee 有办法解决吗？https://github.com/Juris-M/citeproc-js/issues/180

**Comment by zepinglee** [comment]
> @zepinglee 这个citperoc-js是怎么起作用的，我在电脑上搜不到这个文件，是集成到了Zotero还是集成到了Zotero工具条？

我也没找到，我怀疑是直接从网上下载的？

**Comment by zepinglee** [comment]
> @zepinglee 有办法解决吗？[Juris-M/citeproc-js#180](https://github.com/Juris-M/citeproc-js/issues/180)

严肃的出版物的中文不会用斜体的。西文中的斜体一般表示强调或者书名，在中文分别对应的是粗体/黑体/楷体和书名号。在参考文献中一般是后者。建议联系编辑改掉这个中文的斜体书名。

**Comment by redleafnew** [comment]
> > @zepinglee 这个citperoc-js是怎么起作用的，我在电脑上搜不到这个文件，是集成到了Zotero还是集成到了Zotero工具条？
> 
> 我也没找到，我怀疑是直接从网上下载的？

不知道Word是怎么调用它的。

**Comment by redleafnew** [comment]
> > @zepinglee 有办法解决吗？[Juris-M/citeproc-js#180](https://github.com/Juris-M/citeproc-js/issues/180)
> 
> 严肃的出版物的中文不会用斜体的。西文中的斜体一般表示强调或者书名，在中文分别对应的是粗体/黑体/楷体和书名号。在参考文献中一般是后者。建议联系编辑改掉这个中文的斜体书名。

这个有正式的标准文件吗？中文斜体这个是自然基金的模板文件上，要让自然基金委修改，估计要有正式的文件。

**Comment by fredericky123** [comment]
> > > @zepinglee 有办法解决吗？[Juris-M/citeproc-js#180](https://github.com/Juris-M/citeproc-js/issues/180)
> > 
> > 
> > 严肃的出版物的中文不会用斜体的。西文中的斜体一般表示强调或者书名，在中文分别对应的是粗体/黑体/楷体和书名号。在参考文献中一般是后者。建议联系编辑改掉这个中文的斜体书名。
> 
> 这个有正式的标准文件吗？中文斜体这个是自然基金的模板文件上，要让自然基金委修改，估计要有正式的文件。

除了基金委，确实还有少数期刊这样做，估计是为了方便在参考文献中一眼看出期刊名，阅读之前的帖子，感觉是开发者们阻止了自定义中文斜体，是不是建议开发者将这个自定义权限放开更好？有没有国际合作的基金申请规范，将guide 发给老外们看一看，感觉基金委难以说服吧，毕竟是规范制定者

**Comment by redleafnew** [comment]
应该将选择权交给使用者

确实说服规范制定者比较困难，哪怕他们是错的。

**Comment by zepinglee** [comment]
> 这个有正式的标准文件吗？中文斜体这个是自然基金的模板文件上，要让自然基金委修改，估计要有正式的文件。

据我了解这应该是个不成文的习惯。

**Comment by zepinglee** [comment]
> 除了基金委，确实还有少数期刊这样做，估计是为了方便在参考文献中一眼看出期刊名，阅读之前的帖子，感觉是开发者们阻止了自定义中文斜体，是不是建议开发者将这个自定义权限放开更好？有没有国际合作的基金申请规范，将guide 发给老外们看一看，感觉基金委难以说服吧，毕竟是规范制定者

不是，参考文献的西文书名或期刊名用斜体是为了表示书名，相当于中文带书名号。这些编辑没搞懂所以才会把西文的斜体照搬到汉字上。

**Comment by zepinglee** [comment]
> 应该将选择权交给使用者
> 
> 确实说服规范制定者比较困难，哪怕他们是错的。

自然基金委的话确实有点难。

目前 citeproc-js 处理的方式是，纯 CJK 文字的 `font-style=italic` 属性不会生效，比如 `<i>English</i>, 中文, <i>中文 English</i>`。我感觉这个功能可以整合到多语言支持里。

**Comment by redleafnew** [comment]
> > 应该将选择权交给使用者
> > 确实说服规范制定者比较困难，哪怕他们是错的。
> 
> 自然基金委的话确实有点难。
> 
> 目前 citeproc-js 处理的方式是，纯 CJK 文字的 `font-style=italic` 属性不会生效，比如 `<i>English</i>, 中文, <i>中文 English</i>`。我感觉这个功能可以整合到多语言支持里。

在题目添加 `<i>和</i>,`可以实现斜体
