### ISSUE TITLE
410样式引用后依然部分有等，而不是et al.

### ISSUE THREAD

**Issue by shiyang1997** [redleafnew/Chinese-STD-GB-T-7714-related-csl#140]
<img width="924" alt="截屏2023-03-13 09 51 16" src="https://user-images.githubusercontent.com/111226222/224590494-f5b82b29-e81d-40e3-9e35-865b1dbe207d.png">
**描述错误**

CSL 样式：xxx-xxx-xxx.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

<img width="1266" alt="Snipaste_2023-03-13_09-53-03" src="https://user-images.githubusercontent.com/111226222/224590569-247a52c6-6c0e-4c03-9d6b-fe9216f27196.png">

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by IcanGoAnyWhere** [comment]
![image](https://user-images.githubusercontent.com/109728914/224603452-ca0d3652-9d78-426b-ab56-af00a547970c.png)

可以试试把“语言”添加上

**Comment by redleafnew** [comment]
如无问题将关闭。
