### ISSUE TITLE
成都理工大学研究生学位论文

### ISSUE THREAD

**Issue by zzflybird** [redleafnew/Chinese-STD-GB-T-7714-related-csl#142]
**样式信息**

- 学校名称：成都理工大学

- 期刊/学校官网链接：https://www.cdut.edu.cn/

- 英文名称：Chengdu University of Technology

- 参考文献格式要求的**官网**链接: 无公开链接和文件，有word文档。https://wwyw.lanzoum.com/iSQQs0q8urli   密码:47pt

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:mzor

**其他样式信息**

**Comment by redleafnew** [comment]
mzor
已赋予管理权限。请上传示例文献条目。

另外，看一下与现在仓库哪个最接近，详细列出区别。

**Comment by zzflybird** [comment]
已上传示例文献条目到群组中的学位论文/成都理工大学目录下。
自己目前尝试使用的是：`010gb-t-7714-2015-author-date-bilingual-no-uppercase.csl`，极为相似；
不过要注意修改每篇文献的语言信息。
目前参考文献没有发现特别明显的区别。

**Comment by redleafnew** [comment]
如果没有区别，就用它好了。



导出附件，删除条目时删除附件，自动根据题目批量修改语言的插件：https://github.com/redleafnew/delitemwithatt

**Comment by zzflybird** [comment]
好的，感谢！

**Comment by redleafnew** [comment]
> **样式信息**
> 
> * 学校名称：成都理工大学
> * 期刊/学校官网链接：https://www.cdut.edu.cn/
> * 英文名称：Chengdu University of Technology
> * 参考文献格式要求的**官网**链接: 无公开链接和文件，有word文档。https://wwyw.lanzoum.com/iSQQs0q8urli   密码:47pt
> 
> **测试条目**
> 
> 加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。
> 
> Zotero ID:mzor
> 
> **其他样式信息**

这个word文件除了云盘有没有下载链接？

**Comment by redleafnew** [comment]
> 你好，我发现了区别，学校文件要求的示例中的括号是全角的中文的括号，`010gb-t-7714-2015-author-date-bilingual-no-uppercase.csl` 中的是英文的括号。
> 
> > Park等人（1995）根据Laurentia西缘放射状基性岩墙的研究以及与地幔柱有关的澳大利亚Gairdner岩墙群的研究，首次提出约780Ma地幔柱导致Rodinia超大陆的裂解。
> > 其中关于成冰系顶底界时限和冰川活动年龄、超大陆裂解的起始时间和持续时间……是当前中国地球科学界十分活跃并得到迅速发展的研究领域（王平，2003）。

括号内为中文或英文都是用中文括号吗？

试试这个行不行
https://www.jianguoyun.com/p/Db8NLh0QtOD-BRjUo_sEIAA

**Comment by zzflybird** [comment]
你好，没有在网上找到成都理工大学研究生硕士论文格式相关下载链接。
括号内为中文或英文都是用的中文括号。

**Comment by zzflybird** [comment]
`https://www.jianguoyun.com/p/Db8NLh0QtOD-BRjUo_sEIAA`，这个显示的括号是可以的，不过word格式要求中的中文参考文献标注（作者，年份）中的逗号应该是中文的逗号，这个显示的中文参考文献的标注是英文的逗号。

**Comment by redleafnew** [comment]
> 你好，没有在网上找到成都理工大学研究生硕士论文格式相关下载链接。 括号内为中文或英文都是用的中文括号。

http://www.gra.cdut.edu.cn/info/1023/2130.htm   不是这个要求吗？

**Comment by zzflybird** [comment]
就是这个要求，非常抱歉，我搜索相关关键字没有找到 T^T

**Comment by redleafnew** [comment]
如没有问题，则关闭了。

**Comment by zzflybird** [comment]
还有一个问题，中文参考文献的标注中，`（郭剑毅 等，2009）`，等字之前会有一个空格，可以麻烦您把空格删除掉吗？非常感谢！

**Comment by redleafnew** [comment]
> 还有一个问题，中文参考文献的标注中，`（郭剑毅 等，2009）`，等字之前会有一个空格，可以麻烦您把空格删除掉吗？非常感谢！

再试一下，按说有空格是对的。你确定一下。

**Comment by zzflybird** [comment]
现在是删掉空格的，是对的的。非常感谢您。
我参考了几篇学校论文库中的硕士毕业论文，发现中文引用中等前面是没有空格的。

**Comment by redleafnew** [comment]
如果没有问题我上传到仓库了。

**Comment by zzflybird** [comment]
好哒，我这边没有问题啦，再次感谢您。

**Comment by redleafnew** [comment]
已经上传为443

**Comment by zzflybird** [comment]
收到
