### ISSUE TITLE
文中引用希望可以不只保留第一作者的姓

### ISSUE THREAD

**Issue by 17-panyx** [redleafnew/Chinese-STD-GB-T-7714-related-csl#144]
**描述错误**

CSL 样式：[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)

对于两位作者共同署名文章，现行版本再文中引用时只保留了第一个作者的姓，随后便显示et al.

比如，wang et al., 2020, 希望改成 wang and zhang, 2020

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

  <macro name="author-intext-en">
    <names variable="author">
      <name form="short"/>
      <substitute>
        <names variable="composer"/>
        <names variable="illustrator"/>
        <names variable="director"/>
        <choose>
          <if variable="container-title" match="none">
            <names variable="editor"/>
          </if>
        </choose>
        <text macro="anonymous"/>
      </substitute>
    </names>
  </macro>
  
  <macro name="author-intext-zh">
    <names variable="author">

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by redleafnew** [comment]
1. 这是哪个学校或期刊的要求？
2. 请提供测试条目。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/28bb456b4c3c3026f9a0a8c26d326ca0e635435b/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl#L466
修改为：
`<citation and="text" et-al-min="2" et-al-use-first="2" disambiguate-add-givenname="true" disambiguate-add-year-suffix="true" collapse="year">`

试试。

**Comment by zepinglee** [comment]
应该改成 `et-al-min="3" et-al-use-first="1"`。

**Comment by redleafnew** [comment]
ok

**Comment by 17-panyx** [comment]
> 应该改成 `et-al-min="3" et-al-use-first="1"`。
昨晚我自己也试了一下，这样修改是对的

**Comment by 17-panyx** [comment]
关于 在两个作者间添加“和”或者“and”的问题，应该在csl中的文献和著作格式部分进行修改，在name form=“short” 部分修改为 name form=“short” and=“text”

**Comment by redleafnew** [comment]
这是哪个期刊或学校的要求，欢迎修改后提交到仓库，方便更多的人。

**Comment by 17-panyx** [comment]
哈，是一个课程作业里老师要求的，他只给了一个参考范例让我们照着修改其他的文献
