### ISSUE TITLE
关于正文中参考文献格式

### ISSUE THREAD

**Issue by LYR07** [redleafnew/Chinese-STD-GB-T-7714-related-csl#148]
**描述错误**

基于7714-2015-author-date.csl 修改
论文中多次引用同意文献，要在后面显示前面引用的页面并以上角标的形式标注。如何实现，例如
![508b162ee17873d8594532fbf47e4cf](https://user-images.githubusercontent.com/103244838/226785173-bf1f3f74-6bcc-4cbd-89e5-414cae2c0f3b.png)

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
在 CSL 中，页码在括号外跟同一处引用多个文献的情况冲突（比如“(Doe, 1984; Roe, 2001)”）。目前大多数式选择了后者，无法同时实现前者。
