### ISSUE TITLE
安徽理工大学研究生学位论文

### ISSUE THREAD

**Issue by shaoshuai6666** [redleafnew/Chinese-STD-GB-T-7714-related-csl#151]
**样式信息**

- 期刊/学校名称：安徽理工大学研究生学位论文

- 英文名称：Anhui University of Science and Technology

- 参考文献格式要求的**官网**链接 https://yjsc.aust.edu.cn/info/1013/4736.htm

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:[shaoshuai2023](https://www.zotero.org/shaoshuai2023)

**其他样式信息**
![学位论文排版模版-硕士_16](https://user-images.githubusercontent.com/67473921/228485582-f928316f-b6cd-437d-a110-0e68bfc25600.png)
![学位论文排版模版-硕士_17](https://user-images.githubusercontent.com/67473921/228485615-5124b72f-11fe-4f89-a1d6-f3fddbe91832.png)

**Comment by zepinglee** [comment]
需要将示例文献录入 zotero 群组供我们测试。

**Comment by zepinglee** [comment]
已通过申请。

**Comment by shaoshuai6666** [comment]
感谢通过，示例文献已录入到学位论文文件夹下。

**Comment by zepinglee** [comment]
> 感谢通过，示例文献已录入到学位论文文件夹下。

好滴，我晚些时候写一下样式。

**Comment by zepinglee** [comment]
@shaoshuai6666 试一下 [447anhui-university-of-science-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/447anhui-university-of-science-and-technology.csl)，测试结果在 [test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/447anhui-university-of-science-and-technology/test.md)。
