### ISSUE TITLE
请求添加脚注形式的南京农业大学学位论文样式和GB7714样式

### ISSUE THREAD

**Issue by thetaaaaa** [redleafnew/Chinese-STD-GB-T-7714-related-csl#153]
**样式信息**

- 期刊/学校名称：南京农业大学研究生学位论文（人文社科类）2023版

- 英文名称：Nanjing Agricultural University（Humanities and Social Sciences）

- 参考文献格式要求的**官网**链接[<https://grasch.njau.edu.cn/info/1011/4128.htm>]

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:thetaaaaa

**其他样式信息**
南京农业大学于2023年更新了研究生学位论文的格式要求，其中要求以脚注的形式在每页注明参考文献。当前仓库中的GB7714-2015和南京农业大学学位论文样式均不支持以脚注的形式插入。因此，希望1.添加新版南京农业大学硕士论文样式；2.为仓库当前的GB7714-2015类样式添加对应脚注形式。

**Comment by redleafnew** [comment]
对脚注类型的不大熟悉，具体是怎么引用的

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/229130248-20b6de9c-2cc1-4737-a7ef-6bdbc462c581.png)
提供Zotero ID，然后把这些条目录入到Zotero群组中吧

**Comment by zepinglee** [comment]
只需要将 305 的中文文献改为全角符号，我来处理吧。

**Comment by zepinglee** [comment]
@thetaaaaa 试一下 [448nanjing-agricultural-university-note.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/448nanjing-agricultural-university-note.csl)。

**Comment by zepinglee** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/229141033-674f1126-c327-45a4-b82f-02b7fc891a28.png) 还要按类别进行排序？这个很少见。

这种排序方式会在 note 式出现。

**Comment by thetaaaaa** [comment]
> @thetaaaaa 试一下 [448nanjing-agricultural-university-note.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/448nanjing-agricultural-university-note.csl)。
不胜感激！已可以同时生成脚注和尾注。现有如下待完善之处：标（1）处应为英文括号，现为中文；标（2）处，期刊期号应省略0。如，当前为06，正确应为6。（3）已经设置题录中的语言为en-US，但文末英文参考文献仍出现”等“字。
其它期望改进的地方：1.希望将脚注的引文标号设置为带中括号的数字，如[1]，当前为1。2.脚注的行间距看起来较大，希望能自动设为单倍行距。3.文末尾注式参考文献行间距过小，希望能自动设置为单倍行距。
![image](https://user-images.githubusercontent.com/66288540/229178612-2520eb1a-e8d7-4db3-a6de-d6ecf1b5ca22.png)
![image](https://user-images.githubusercontent.com/66288540/229179153-c453afab-3961-4e69-9467-6eccba21d0a5.png)

**Comment by zepinglee** [comment]
1. 给出的示例中这里为全角括号。
<img width="673" alt="Screenshot 2023-04-01 at 08 50 27" src="https://user-images.githubusercontent.com/12290822/229257465-7e95e6ff-2472-4b14-bae7-ce32b564373f.png">
2. CSL 无法省略“0”，需要在 Zotero 的原始中去掉 0（早些版本的网页抓取器没有去掉多余的 0，建议更新一下）。
3. 建议将文献导出为 CSL-JSON 格式并贴上来。
4. 可以。

**Comment by redleafnew** [comment]
删除期号中的0,可以用quicker动作，
https://getquicker.net/Sharedaction?code=b3fb127d-344e-4a6e-50f8-08dabc15aa8f&fromMyShare=true

如果你打算用Quicker专业版，可以使用我的推荐码：467528-5244，我们两个的时长都可以增加3个月。

**Comment by thetaaaaa** [comment]
> 1. 学校给出的示例中这里为全角括号。
> 
> <img alt="Screenshot 2023-04-01 at 08 50 27" width="673" src="https://user-images.githubusercontent.com/12290822/229257465-7e95e6ff-2472-4b14-bae7-ce32b564373f.png">
> 
> 2. CSL 无法省略“0”，需要在 Zotero 的原始中去掉 0（早些版本的网页抓取器没有去掉多余的 0，建议更新一下）。 3. 建议将文献导出为 CSL-JSON 格式并贴上来。 4. 可以。

感谢！测试最新版448样式后，发现如下问题：
1. 脚注中的中英文“等”和“et al."正常，但是尾注中的英文文献”et al."仍然显示为“等”。
2. 中文和英文文参考文献（脚注和尾注），页码之间的横线应为"-"，现为“——"。

以下给出一条英文”等“在尾注中显示不正确的cls-json英文文献题录：
    [
	{
		"id": "http://zotero.org/users/9443785/items/9MI7EL69",
		"type": "article-journal",
		"container-title": "Advances in neural information processing systems",
		"language": "en-US",
		"title": "Translating embeddings for modeling multi-relational data",
		"volume": "26",
		"author": [
			{
				"family": "Bordes",
				"given": "Antoine"
			},
			{
				"family": "Usunier",
				"given": "Nicolas"
			},
			{
				"family": "Garcia-Duran",
				"given": "Alberto"
			},
			{
				"family": "Weston",
				"given": "Jason"
			},
			{
				"family": "Yakhnenko",
				"given": "Oksana"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2013"
				]
			]
		}
	}
]

**Comment by zepinglee** [comment]
1. 原来是这里不小心多了个空格，已经修复。 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/df41e05c307a05758591d582dc418a65b2c26cab/448nanjing-agricultural-university-note.csl#L696>
2. 吐槽一下，中文文献都用的全角符号，页码这里确不用 GB/T 15834—2011《标点符号用法》规定的一字线。已在 4aec6b7 中修改。
<img width="466" alt="Screenshot 2023-04-01 at 15 04 23" src="https://user-images.githubusercontent.com/12290822/229271179-0b8b31db-8d73-49d8-9250-3d7d16510b6b.png">

**Comment by redleafnew** [comment]
@zepinglee 现在445和448title都是南京农业大学，
根据https://grasch.njau.edu.cn/info/1011/4128.htm
将445改为 南京农业大学（自然科学类）
448为 南京农业大学（社会科学类）
或是添加： 著者年代 脚注

**Comment by redleafnew** [comment]
csl名称可以不用修改

**Comment by zepinglee** [comment]
> @zepinglee 现在445和448title都是南京农业大学， 根据https://grasch.njau.edu.cn/info/1011/4128.htm 将445改为 南京农业大学（自然科学类） 448为 南京农业大学（社会科学类） 或是添加： 著者年代 脚注

我看了一下他们的要求，自然科学类只允许使用“著者-出版年”，人文社科类可以选择脚注或著者-出版年。我觉得还是按照第二套方案吧。

**Comment by zepinglee** [comment]
> 2. 中文和英文文参考文献（脚注和尾注），页码之间的横线应为"-"，现为“——"。

@thetaaaaa 那个叫“参考文献表”（bibliography），不是“尾注”。

**Comment by redleafnew** [comment]
我来修改一下吧。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/229271964-8d0da825-ee64-43ac-9b8c-e7ede6be14bd.png)
@thetaaaaa 可以使编号变为圆圈。

**Comment by zepinglee** [comment]
再吐槽一下，自然科学类格式规范的示例页码用的是一字线。没看出这两者有什么理由不采用一致的格式。

<img width="686" alt="Screenshot 2023-04-01 at 15 22 38" src="https://user-images.githubusercontent.com/12290822/229272111-7f2f16f1-c541-4aeb-acb6-f25026711269.png">

**Comment by redleafnew** [comment]
按说自科这个更能说通。

**Comment by zepinglee** [comment]
@thetaaaaa 247d08c 又修改了几处标点符号。

**Comment by thetaaaaa** [comment]
1. 有个小问题，readme中这里的超链接是”安徽理工大学“而非”南京农业大学“。 
![Uploading image.png…]()

2.条目类型为”预印本“的文献，在GB7714-2015及衍生样式中，文献标识符被标注成了“[M]”，似乎应为”[J]"。

**Comment by zepinglee** [comment]
> 1. 有个小问题，readme中这里的超链接是”安徽理工大学“而非”南京农业大学“。
>    ![image](https://user-images.githubusercontent.com/66288540/229296068-c3fa56ae-34bb-475e-b858-5cde55829450.png)

已经修改。

> 2.条目类型为”预印本“的文献，在GB7714-2015及衍生样式中，文献标识符被标注成了“[M]”，似乎应为”[J]"。

预印本用“A”最合适，绝对不是对应期刊的“J”，参考 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/89> 的讨论。

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f2b519b7bd34f0b3a03281255cca344c8a6a53ad/000gb-t-7714-2015-numeric-bilingual.csl#L121-L130

我又读了一遍 <https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types> 对 `article` 类型的描述，感觉没必要根据是否有 `archive` 选择“A”或“M”，直接设为“A”就行。“posted on a platform where some level of persistence or stewardship is expected”符合“分类保存以备查考的文件和材料”、“科技档案”的描述。

**Comment by redleafnew** [comment]
这个解决了就关闭？

**Comment by thetaaaaa** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f2b519b7bd34f0b3a03281255cca344c8a6a53ad/000gb-t-7714-2015-numeric-bilingual.csl#L121-L130
> 
> 我又读了一遍 https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types 对 `article` 类型的描述，感觉没必要根据是否有 `archive` 选择“A”或“M”，直接设为“A”就行。“posted on a platform where some level of persistence or stewardship is expected”符合“分类保存以备查考的文件和材料”、“科技档案”的描述。

预印本的文献类型标识符是不是还没改，是否有必要改一下？

**Comment by redleafnew** [comment]
@thetaaaaa

**Comment by redleafnew** [comment]
问一下学校的要求？

**Comment by zepinglee** [comment]
标准本身也没说清楚，估计学校也不确定。我直接改成 “A” 吧。

**Comment by thetaaaaa** [comment]
非常感谢两位老师！ @zepinglee @redleafnew
