### ISSUE TITLE
请求添加北京大学研究生学位论文

### ISSUE THREAD

**Issue by linbeyoung** [redleafnew/Chinese-STD-GB-T-7714-related-csl#155]
**样式信息**

- 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式要求的**官网**链接[例如 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8141633/default.pdf>]

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
这个和7714有什么区别？

**Comment by zepinglee** [comment]
最新的是 2014 年版的《写作指南》？

**Comment by redleafnew** [comment]
如果不需要了请关闭。
