### ISSUE TITLE
天津大学研究生学位论文

### ISSUE THREAD

**Issue by Elena0811** [redleafnew/Chinese-STD-GB-T-7714-related-csl#156]
**样式信息**

- 学校名称：天津大学研究生学位论文

- 英文名称：Tianjin University

- 参考文献格式要求的**官网**链接 http://gs.tju.edu.cn/info/1013/1100.htm
- 
[参考文献格式要求-已高亮重点内容.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11176147/-.pdf)

小小总结了下需要注意的点（如下），希望能更好的提供信息，谢谢！

1.希望作者姓名显示完整，如 [2] Li X N, L X Y……，自动导出参考文献列表时就会变成 Li X， Li X，……
2.文献题目首字母大写，其余全小写；期刊名称每个单词首字母大写
3.中文文献：中文，全角，英文标点，标点后直接接后续内容；英文文献：英文，半角，英文标点，标点后空一格再接后续内容
4.作者3人以上，中文用“，等”，英文用“，et al”

实在找不到官网要求示例中的文献，我自己按照学位论文要求写了几个。

<img width="624" alt="截屏2023-04-07 20 36 03" src="https://user-images.githubusercontent.com/130125383/230609876-03b771d8-7e15-4fe1-b11a-7220cee9fb01.png">

pdf如下：
[1. Cloud manufacturing From concept to practice.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178926/1.Cloud.manufacturing.From.concept.to.practice.pdf)
[2. Supply regulation under the exclusion policy in a ride-sourcing market.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178930/2.Supply.regulation.under.the.exclusion.policy.in.a.ride-sourcing.market.pdf)
[3. 考虑服务水平的产能分享平台定价策略.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178927/3.pdf)
[4. 考虑产能需求方交期和价格敏感的产能分享平台定价策略.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178932/4.pd
[5. Quantity vs. Quality and Exclusion by Two-Sided Platforms.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178933/5.Quantity.vs.Quality.and.Exclusion.by.Two-Sided.Platforms.pdf)
f)
[6. 中国共享经济发展年度报告（2023）.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178935/6.2023.pdf)
[7. 产能分享供应链参与主体定价和服务水平决策及协调研究.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11178936/7.pdf)

谢谢！

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
1. 正文中是什么？[数字]上标，还是（作者，年）？
2. 看看与仓库中哪个类似？
3. 将上述文献导出为CSL JSON格式或提供Zotero ID添加到群组。

**Comment by Elena0811** [comment]
您好！
正文中是[数字]上标
格式要求中写的是根据  GB/T 7714-2005  书写参考文
Zotero ID：YangXue811
薛洋 博士
天津大学 管理科学与工程专业
地址:中国 天津市 南开区 卫津路 92 号
***@***.***
电话：+86 13821796705
微信：qinglang0811


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月7日 20:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 天津大学研究生学位论文 (Issue #156) |

正文中是什么？[数字]上标，还是（作者，年）？
看看与仓库中哪个类似？
将上述文献导出为CSL JSON格式或提供Zotero ID添加到群组。

**Comment by redleafnew** [comment]
群组中没有搜到 YangXue811，加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，新建 天津大学 目录，将示例文献添加。

**Comment by Elena0811** [comment]
> 群组中没有搜到 YangXue811，加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，新建 天津大学 目录，将示例文献添加。

加入组群了~~请问如何创建新的目录呀？

**Comment by redleafnew** [comment]
在学位论文上右击：
![image](https://user-images.githubusercontent.com/22135631/230613651-6343a449-1146-4858-9dee-12352b232cf0.png)

**Comment by redleafnew** [comment]
文末参考文献表是不是和
https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#445nanjing-agricultural-universitycsl
类似。
或是和哪个类似，指出来方便修改。

**Comment by zepinglee** [comment]
002 就可以，只需要将会议文献的 `"//"` 改成 `". "`。

**Comment by Elena0811** [comment]
> 

确实类似，但正文中要[数字]上标
您发的这个我没看见 报告  书籍 等的参考文献，不知道是不是类似


以及，参考文献列表的作者姓名总是显示不全，不知道怎么解决？

**Comment by redleafnew** [comment]
但

> 002 就可以，只需要将会议文献的 `"//"` 改成 `". "`。
> 
> 修改：还需要处理全角标点。

是的，要处理中文标点。

**Comment by redleafnew** [comment]
如果没有其他更类似的，我在445上修改一下。

**Comment by redleafnew** [comment]
@Elena0811 不要导入PDF，导入条目才可以完整引用。

**Comment by redleafnew** [comment]
https://www.jianguoyun.com/p/DeoEnRUQtOD-BRj_uv8EIAA   先试一下效果

**Comment by zepinglee** [comment]
> 以及，参考文献列表的作者姓名总是显示不全，不知道怎么解决？

@Elena0811 这个只能在 Zotero 数据库的原始信息中将名的两个拼音拆开，比如“Li, Xin Nan”。

**Comment by Elena0811** [comment]
谢谢！
有一些不一样的：
1.姓名只需要首字母大写，其他字母小写
2.文献名字只需要句首单词的首字母大写，例如现在的[6]是每个单词首字母大写，这点不一样
3.中文文献的符号这里不是全角，而是半角加空格，需要是全角
4.中文用等，英文需要用, et al
5.不知道为啥[1]和[4]显示了[J/OL]，应该是[J]

6.[1][2][4]不需要网址链接
7.报告的格式，年份那里也需要全角符号，因为是中文文献






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月7日 21:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 天津大学研究生学位论文 (Issue #156) |

https://www.jianguoyun.com/p/DeoEnRUQtOD-BRj_uv8EIAA 先试一下效果

**Comment by redleafnew** [comment]
> 谢谢！ 有一些不一样的： 1.姓名只需要首字母大写，其他字母小写 2.文献名字只需要句首单词的首字母大写，例如现在的[6]是每个单词首字母大写，这点不一样 3.中文文献的符号这里不是全角，而是半角加空格，需要是全角 4.中文用等，英文需要用, et al 5.不知道为啥[1]和[4]显示了[J/OL]，应该是[J] 6.[1][2][4]不需要网址链接 7.报告的格式，年份那里也需要全角符号，因为是中文文献 <img width="616" alt="截屏2023-04-07 22 20 10" src="https://user-images.githubusercontent.com/130125383/230624547-3225e642-6444-46f6-b080-1896bba83ecf.png">
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年04月7日 21:38 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 天津大学研究生学位论文 (Issue #156) | https://www.jianguoyun.com/p/DeoEnRUQtOD-BRj_uv8EIAA 先试一下效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

把你图中的这些文献传到群组中方便测试。

**Comment by redleafnew** [comment]
要正常条目而不是PDF

**Comment by Elena0811** [comment]
> 要正常条目而不是PDF

已经导出了一个csl.json格式的文件了，请教下怎么导入……

**Comment by redleafnew** [comment]
可以上传附件或网盘。

**Comment by Elena0811** [comment]
> 可以上传附件或网盘。
谢谢耐心指导~~
链接: https://pan.baidu.com/s/1DG1QNzf8oKeCUGusxRdflQ 提取码: nihc

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/230696341-29feb042-e9e8-4a6c-bf15-fe823007168b.png)
用你的条目的显示效果，什么地方还需要修改？

**Comment by Elena0811** [comment]
看着和格式模板要求非常像了~有两个小地方
1.中文文献部分：
文献类型的中括号是半角的[J]，页码的小括号也是半角的()，页码链接的横线也是半角的；中文文献只有逗号、句号、冒号是全角
2.英文文献部分：
文献[7]的文献名字，只需要首个单词的首字母大写，其他全小写

谢谢！



---- 回复的原邮件 ----

| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月8日 08:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 天津大学研究生学位论文 (Issue #156) |


用你的条目的显示效果，什么地方还需要修改？

**Comment by zepinglee** [comment]
这种从三个地方进行对比是真的麻烦。@redleafnew 下次让他们录入期刊/学校官方文档的示例文献，可以直接比较。

<img width="587" alt="Screenshot 2023-04-08 at 11 07 02" src="https://user-images.githubusercontent.com/12290822/230700696-4fc93738-d591-4f70-bcde-5683d11cbbe9.png">

**Comment by Elena0811** [comment]
> 这种从三个地方进行对比是真的麻烦。@redleafnew 下次让他们录入期刊/学校官方文档的示例文献，可以直接比较。
> 
> <img alt="Screenshot 2023-04-08 at 11 07 02" width="587" src="https://user-images.githubusercontent.com/12290822/230700696-4fc93738-d591-4f70-bcde-5683d11cbbe9.png">

是的是的，麻烦大佬们……

**Comment by redleafnew** [comment]
是的，所以要自己学校也参与测试。

@Elena0811 再试下

**Comment by Elena0811** [comment]
我在……哪里试？

**Comment by redleafnew** [comment]
重新下载样式，450 

另外，尽管可以调整样式显示为题目首字母大写，但是会带来其它问题，如一些专有名词也会为小写，如WHO会显示为who，DNA显示dna，所以最好在条目中自己修改为合适的大小写（如句首字母大写）。

**Comment by Elena0811** [comment]
> 重新下载样式，450
> 
> 另外，尽管可以调整样式显示为题目首字母大写，但是会带来其它问题，如一些专有名词也会为小写，如WHO会显示为who，DNA显示dna，所以最好在条目中自己修改为合适的大小写（如句首字母大写）。

我第一次用，实在是没找到哪里下载，是这个页面么？哪里有下载键……
![截屏2023-04-08 11 38 50](https://user-images.githubusercontent.com/130125383/230701584-b91b1bda-7670-42b1-b124-bf432ccac47d.png)

好的，那我还是手动改文献名字吧~~谢谢提醒！

**Comment by redleafnew** [comment]
看https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl  或  https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl 的readme

**Comment by Elena0811** [comment]
> 看https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl 或 https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl 的readme
其他都没问题了，
中文文献：
文献类型的中括号半角、小括号半角、页码链接的横线半角没问题了，但逗号、句号、冒号又变成半角了……（我们这要求也是很辛苦大佬了……）

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/230704378-7eb40800-21fa-4b6b-8562-d465fcbfa307.png)

我的显示效果，哪个不正常

**Comment by Elena0811** [comment]
> 

您这里看着是对的，但我这里输出后中文里逗号、句号、冒号显示的是半角
<img width="633" alt="截屏2023-04-08 13 21 37" src="https://user-images.githubusercontent.com/130125383/230704841-8afdee58-ff27-48dc-981e-71aa42fc23bc.png">

**Comment by redleafnew** [comment]
用群组里的文献条目插入。

我怀疑你条目语言没有设置对。中文条目应该为zh-CN，英文为en-US

**Comment by Elena0811** [comment]
设置了语言，变成了全角，但还是跟您这不一样……

<img width="626" alt="截屏2023-04-08 13 44 43" src="https://user-images.githubusercontent.com/130125383/230705605-53bab3e6-753c-4334-b5ec-9b482aa227f4.png">

**Comment by redleafnew** [comment]
> 看着和格式模板要求非常像了~有两个小地方 1.中文文献部分： 文献类型的中括号是半角的[J]，页码的小括号也是半角的()，页码链接的横线也是半角的；中文文献只有逗号、句号、冒号是全角 

你不是要全角嘛

> 格式突然变了，没有悬挂之类的了……

悬挂可以在Word中设置

**Comment by Elena0811** [comment]
是对的是对的，把字体改成宋体就一样了～～～完美，谢谢您！

**Comment by Elena0811** [comment]
<img width="630" alt="截屏2023-04-08 14 01 51" src="https://user-images.githubusercontent.com/130125383/230706126-28695dd3-037a-4823-9298-64a0335e3e87.png">

这是我最终输出的结果，感谢！

**Comment by redleafnew** [comment]
如果没有问题了，请关闭。

**Comment by Elena0811** [comment]
谢谢！

**Comment by lincolnelectric** [comment]
> 

非常感谢各位的辛苦工作！
我测试发现会议论文引用的“[c]//会议集”这个问题依旧存在，我修改为了“[c]. 会议集”，并commit了450-tianjin university。希望能修复这个问题。

感谢大家

**Comment by zepinglee** [comment]
> 非常感谢各位的辛苦工作！ 我测试发现会议论文引用的“[c]//会议集”这个问题依旧存在，我修改为了“[c]. 会议集”，并commit了450-tianjin university。希望能修复这个问题。
> 
> 感谢大家

确实应该是 “[C].”，那你发个 PR？

**Comment by lincolnelectric** [comment]
> > 非常感谢各位的辛苦工作！ 我测试发现会议论文引用的“[c]//会议集”这个问题依旧存在，我修改为了“[c]. 会议集”，并commit了450-tianjin university。希望能修复这个问题。
> > 感谢大家
> 
> 确实应该是 “[C].”，那你发个 PR？

ok
