### ISSUE TITLE
请求添加大连理工大学的硕博学位论文样式，

### ISSUE THREAD

**Issue by yxl-loading** [redleafnew/Chinese-STD-GB-T-7714-related-csl#157]
**样式信息**

-  学校名称：大连理工大学

- 英文名称：Dalian University of Technology 

- 参考文献格式要求的**官网**链接[例如 https://gs.dlut.edu.cn/info/1210/13319.htm

 
 

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:  dutyxl

**其他样式信息**

**Comment by redleafnew** [comment]
模板上的信息要写啊，如学校英文名称、学校要求的地址，Zotero ID...

**Comment by redleafnew** [comment]
网址上的附件下载不了，请将示例条目上传到[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)群组方便测试。

**Comment by yxl-loading** [comment]
> 网址上的附件下载不了，请将示例条目上传到[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)群组方便测试。

抱歉抱歉，马上修改一下

**Comment by yxl-loading** [comment]
> 模板上的信息要写啊，如学校英文名称、学校要求的地址，Zotero ID...

大佬，已经提供

**Comment by redleafnew** [comment]
已经赋予管理权限，可以在群组中新建文件夹，并上传示例条目文献了。

**Comment by redleafnew** [comment]
这个与002有区别吗？

**Comment by yxl-loading** [comment]
> **样式信息**
> 
> * 学校名称：大连理工大学
> * 英文名称：Dalian University of Technology
> * 参考文献格式要求的**官网**链接[例如 https://gs.dlut.edu.cn/info/1210/13319.htm
> 
> **测试条目**
> 
> 加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。
> 
> Zotero ID: dutyxl
> 
> **其他样式信息**



> **样式信息**
> 
> * 学校名称：大连理工大学
> * 英文名称：Dalian University of Technology
> * 参考文献格式要求的**官网**链接[例如 https://gs.dlut.edu.cn/info/1210/13319.htm
> 
> **测试条目**
> 
> 加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。
> 
> Zotero ID: dutyxl
> 
> **其他样式信息**



> 已经赋予管理权限，可以在群组中新建文件夹，并上传示例条目文献了。

已经上传结束了

**Comment by yxl-loading** [comment]
> 这个与002有区别吗？

有点区别，比如会议录和科技报告不太一样

**Comment by redleafnew** [comment]
具体区别是什么，详细列出。

**Comment by yxl-loading** [comment]
> 具体区别是什么，详细列出。

论文集要求：[序号] 主要责任者. 标题: 会议名称[C], 会议地点. 年份: 起止页码.
002格式：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计[C]//广东省教师继续教育学会第六届教学研讨会. 中国广东广州: 广东省教师继续教育学会, 2023: 230-232.
要求格式：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C], 中国广东广州. 2023: 230-232.

报纸要求：[序号] 作者. 题名[N]. 报纸名, 年,月,日(版次).
002格式：丁文祥. 数字革命与竞争国际化[N]. 中国青年报, 2000-11-20(15).
要求格式：丁文祥. 数字革命与竞争国际化[N]. 中国青年报, 2000,11,20(15).

书籍要求：[序号] 作者. 书名[M]. 出版地: 出版者, 出版年: 起止页码.
002格式：蒋有绪, 郭泉水, 马娟, et al. 中国森林群落分类及其群落学特征: Vols. 23-30[M]. 北京: 科学出版社, 1998.
要求格式：蒋有绪, 郭泉水, 马娟, et al. 中国森林群落分类及其群落学特征[M]. 北京: 科学出版社, 1998：23-30.

**Comment by redleafnew** [comment]
试试452
书籍页码引用需要将页码填入Extra，见群组中录入方式。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/452dalian-university-of-technology.csl

**Comment by yxl-loading** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/452dalian-university-of-technology.csl
牛啊，没问题，非常好用，nice！！！！

**Comment by redleafnew** [comment]
如果没有问题，请关闭。

**Comment by yxl-loading** [comment]
> 如果没有问题，请关闭。



> 如果没有问题，请关闭。
发现一个问题，插入会议论文的时候，不显示[C]标识
452：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计//广东省教师继续教育学会第六届教学研讨会. 中国广东广州: 广东省教师继续教育学会, 2023: 230-232.
要求：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C], 中国广东广州. 2023: 230-232.

**Comment by redleafnew** [comment]
@yxl-loading @wuxueqian98 现在主要是会议论文问题是吧。
你们两个的要求一致吗？

**Comment by yxl-loading** [comment]
> @yxl-loading @wuxueqian98 现在主要是会议论文问题是吧。 你们两个的要求一致吗？
是的，要求一致

**Comment by yxl-loading** [comment]
> 
条目已上传

原来显示：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计//广东省教师继续教育学会第六届教学研讨会. 中国广东广州: 广东省教师继续教育学会, 2023: 230-232.
想显示为：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C], 中国广东广州: 广东省教师继续教育学会. 2023: 230-232.

**Comment by redleafnew** [comment]
这个数据条目是手动填的还是抓取的，前面内容应该是...论文集才合理。
![image](https://user-images.githubusercontent.com/22135631/232053220-d2f8a2a7-ce48-4f80-b9f9-2b11529d3efd.png)

**Comment by yxl-loading** [comment]
> 这个数据条目是手动填的还是抓取的，前面内容应该是...论文集才合理。这两个字段内容怎么一样？ ![image](https://user-images.githubusercontent.com/22135631/232053220-d2f8a2a7-ce48-4f80-b9f9-2b11529d3efd.png)

已在条目中更改

**Comment by redleafnew** [comment]
那需要显示为什么？

**Comment by zepinglee** [comment]
> 这个数据条目是手动填的还是抓取的，前面内容应该是...论文集才合理。这两个字段内容怎么一样？ ![image](https://user-images.githubusercontent.com/22135631/232053220-d2f8a2a7-ce48-4f80-b9f9-2b11529d3efd.png)

前者对应的 CSL 字段是 `container-title`，相当于论文集的书名，后者是 `event-title`。考虑到有些会议没有论文集，但空着更不合适。所以代码中是优先使用前者，后者作为备用。我在代码中备注一下。

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/00b82a2a076a986132861f9963ab5654ec900134/000gb-t-7714-2015-numeric-bilingual.csl#L209-L216>

**Comment by redleafnew** [comment]
> > 这个数据条目是手动填的还是抓取的，前面内容应该是...论文集才合理。这两个字段内容怎么一样？ ![image](https://user-images.githubusercontent.com/22135631/232053220-d2f8a2a7-ce48-4f80-b9f9-2b11529d3efd.png)
> 
> 前者对应的 CSL 字段是 `container-title`，相当于论文集的书名，后者是 `event-title`。考虑到有些会议没有论文集，但空着更不合适。所以代码中是优先使用前者，后者作为备用。我在代码中备注一下。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/00b82a2a076a986132861f9963ab5654ec900134/000gb-t-7714-2015-numeric-bilingual.csl#L209-L216

我看很多会议论文的例子中conference name是空的，包括test文件夹中的json数据，所以测试的时候不显示[C]

**Comment by yxl-loading** [comment]
> 那需要显示为什么？


想显示为：陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C], 中国广东广州: 广东省教师继续教育学会. 2023: 230-232.

**Comment by redleafnew** [comment]
现在是这样。[C]确定改为`，`？

`[7]	陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C]. 中国广东广州: 广东省教师继续教育学会, 2023: 230-232.`

**Comment by yxl-loading** [comment]
> 现在是这样。[C]确定改为`，`？
> 
> `[7] 陈元洪. 探究“双减”之下如何进行初中英语作业的优化设计. 广东省教师继续教育学会第六届教学研讨会[C]. 中国广东广州: 广东省教师继续教育学会, 2023: 230-232.`

对的

**Comment by redleafnew** [comment]
为了显示正常打了很多“补丁”，可能不符合规范，再试试效果。

**Comment by yxl-loading** [comment]
> 为了显示正常打了很多“补丁”，可能不符合规范，再试试效果。已经上传。

好的，明天测试一下，辛苦辛苦

**Comment by zepinglee** [comment]
<img width="564" alt="Screenshot 2023-04-15 at 10 23 37" src="https://user-images.githubusercontent.com/12290822/232178646-e5292af6-00a3-46ed-89f3-d3e20064c045.png">

学校这里描述的是“论文集”，但给出的示例是“论文集的析出文献”，[C] 的位置完全不符合国标。建议跟学校沟通一下。

**Comment by yxl-loading** [comment]
> <img alt="Screenshot 2023-04-15 at 10 23 37" width="564" src="https://user-images.githubusercontent.com/12290822/232178646-e5292af6-00a3-46ed-89f3-d3e20064c045.png">
> 
> 学校这里描述的是“论文集”，但给出的示例是“论文集的析出文献”，[C] 的位置完全不符合国标。建议跟学校沟通一下。

好的，我们学校确实弄得很混乱，到时候我自己把代码改了就行

**Comment by yxl-loading** [comment]
> 为了显示正常打了很多“补丁”，可能不符合规范，再试试效果。已经上传。

基本没啥问题了，多谢多谢

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/bd32b191a02a7a69f1c3136e2eba8e453a1d37e0/452dalian-university-of-technology.csl#L214-L234

这里的逻辑还有些问题，如果 `container-title` 为空则不显示文献类型标识等信息。我改成了

```xml
    <choose>
      <if type="paper-conference">
        <!-- 会议论文优先使用会议名称，并且加文献类型标识 -->
        <group>
          <choose>
            <if variable="event-title">
              <text variable="event-title"/>
            </if>
            <else>
              <text variable="container-title"/>
            </else>
          </choose>
          <group delimiter="/" prefix="[" suffix="]">
            <text macro="type-code"/>
            <text macro="medium-code"/>
          </group>
        </group>
      </if>
      <else>
        <text variable="container-title"/>
      </else>
    </choose>
```

**Comment by redleafnew** [comment]
这个太不好搞了。

**Comment by zepinglee** [comment]
我再校对一下别的，稍后发上来。

**Comment by zepinglee** [comment]
已在 e821610 中修改。顺便将“会议地点”和“年份”之间的分隔符改为“.”。

**Comment by redleafnew** [comment]
> 已在 [e821610](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/e82161028dc3602795559126a4321271e667ca6d) 中修改。顺便将“会议地点”和“年份”之间的分隔符改为“.”。

辛苦，我没有注意。我pull一下。
