### ISSUE TITLE
请求添加兰州大学研究生毕业论文参考文献格式

### ISSUE THREAD

**Issue by ZhangzhongWa** [redleafnew/Chinese-STD-GB-T-7714-related-csl#158]
**样式信息**

- 期刊/学校名称：[兰州大学研究生学位论文]

- 英文名称：[Lanzhou University]

- 参考文献格式要求的**官网**链接[例如<https://ge.lzu.edu.cn/yjsxw/upload/files/20230404/61cd8e5356084aa28c55ed238ba871bc.pdf>]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:   ZhangzhongWa

**其他样式信息**

**Comment by redleafnew** [comment]
提供Zotero ID，加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development) 将要求上的示例文献条目录入到群组中方便测试。

**Comment by chechehua** [comment]
已经更新Zotero ID

**Comment by redleafnew** [comment]
群组成员中没有搜到 [1793918736@qq.com](mailto:1793918736@qq.com)

**Comment by chechehua** [comment]
抱歉。Zotero ID是ZhangzhongWa

**Comment by redleafnew** [comment]
以前就加入过？已经赋予管理权限，可以在群组中新建文件夹，并上传示例条目文献了。

**Comment by redleafnew** [comment]
这个是不是与https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#450tianjin-university-numbericcsl 天津大学的很类似？

**Comment by ZhangzhongWa** [comment]
是的，但英文文献的作者格式不一样

**Comment by redleafnew** [comment]
在哪个的基础上修改？
详细列出区别。

**Comment by ZhangzhongWa** [comment]
在北航的基础上修改https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/420beihang-university.csl，需要修改的地方：（1）文献结尾需要有点，（2）英文文献作者姓和名直接有逗号隔开，例如北航的是Poisson J. B.,需要修改成Poisson, J. B.,

**Comment by redleafnew** [comment]
请提供测试的条目到群组

**Comment by redleafnew** [comment]
> 在北航的基础上修改[https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/420beihang-university.csl，需要修改的地方：（1）文献结尾需要有点，（2）英文文献作者姓和名直接有逗号隔开，例如北航的是Poisson](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/420beihang-university.csl%EF%BC%8C%E9%9C%80%E8%A6%81%E4%BF%AE%E6%94%B9%E7%9A%84%E5%9C%B0%E6%96%B9%EF%BC%9A%EF%BC%881%EF%BC%89%E6%96%87%E7%8C%AE%E7%BB%93%E5%B0%BE%E9%9C%80%E8%A6%81%E6%9C%89%E7%82%B9%EF%BC%8C%EF%BC%882%EF%BC%89%E8%8B%B1%E6%96%87%E6%96%87%E7%8C%AE%E4%BD%9C%E8%80%85%E5%A7%93%E5%92%8C%E5%90%8D%E7%9B%B4%E6%8E%A5%E6%9C%89%E9%80%97%E5%8F%B7%E9%9A%94%E5%BC%80%EF%BC%8C%E4%BE%8B%E5%A6%82%E5%8C%97%E8%88%AA%E7%9A%84%E6%98%AFPoisson) J. B.,需要修改成Poisson, J. B.,

这样作者姓名和逗号，姓名之间的逗号就分不开了。不知道逗号分隔的姓与名，还是不同作者了。

**Comment by ZhangzhongWa** [comment]
这是显示效果，测试条目添加到群组的测试文件夹下面了
[4] Schinstock, D.E., Cuttino, J.F. Real time kinematic solutions of a non-contacting, three
dimensional metrology frame[J]. Precision Engineering. 2000, 24(1): 70-76.

**Comment by redleafnew** [comment]
> 这是显示效果，测试条目添加到群组的测试文件夹下面了 [4] Schinstock, D.E., Cuttino, J.F. Real time kinematic solutions of a non-contacting, three dimensional metrology frame[J]. Precision Engineering. 2000, 24(1): 70-76.

你上传的条目里面没有这个文献啊

**Comment by ZhangzhongWa** [comment]
上传好了

**Comment by redleafnew** [comment]
放入到“学位论文”-“兰州大学”中，多放几篇，最好把格式要求文档中示例文献都放进去。

**Comment by zepinglee** [comment]
> > 在北航的基础上修改[https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/420beihang-university.csl，需要修改的地方：（1）文献结尾需要有点，（2）英文文献作者姓和名直接有逗号隔开，例如北航的是Poisson](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/420beihang-university.csl%EF%BC%8C%E9%9C%80%E8%A6%81%E4%BF%AE%E6%94%B9%E7%9A%84%E5%9C%B0%E6%96%B9%EF%BC%9A%EF%BC%881%EF%BC%89%E6%96%87%E7%8C%AE%E7%BB%93%E5%B0%BE%E9%9C%80%E8%A6%81%E6%9C%89%E7%82%B9%EF%BC%8C%EF%BC%882%EF%BC%89%E8%8B%B1%E6%96%87%E6%96%87%E7%8C%AE%E4%BD%9C%E8%80%85%E5%A7%93%E5%92%8C%E5%90%8D%E7%9B%B4%E6%8E%A5%E6%9C%89%E9%80%97%E5%8F%B7%E9%9A%94%E5%BC%80%EF%BC%8C%E4%BE%8B%E5%A6%82%E5%8C%97%E8%88%AA%E7%9A%84%E6%98%AFPoisson) J. B.,需要修改成Poisson, J. B.,
> 
> 这样作者姓名和逗号，姓名之间的逗号就分不开了。不知道逗号分隔的姓与名，还是不同作者了。

APA 就是这种姓名格式

**Comment by redleafnew** [comment]
@ZhangzhongWa 上传的信息都不全

**Comment by ZhangzhongWa** [comment]
刚用的移动端，现在换电脑弄

**Comment by ZhangzhongWa** [comment]
@redleafnew 文献信息已补全

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/230755122-3d3b4e6b-2c83-4504-857e-4df25b0336dd.png)
只有一个题目啊

**Comment by ZhangzhongWa** [comment]
刚才同步失败，现在好了

**Comment by redleafnew** [comment]
现在效果是这样，不知道英文的页码是`-`还是`–`

> [1]
> [2]
> [2–10]
> [1]	Frese K.S., Katus H.A., Meder B. Next-generation sequencing: from understanding biology to personalized medicine[J]. Biology, 2013, 2(1): 378-398.
> [2]	Manglik, A., Lin, H., Aryal, D.K., et al. Structure-based discovery of opioid analgesics with reduced side effects.[J]. Nature, England: 2016, 537(7619): 185-190.
> [3]	Schinstock, D.E., Cuttino, J.F. Real time kinematic solutions of a non-contacting, three dimensional metrology frame[J]. Precision Engineering, 2000, 24(1): 70-76.
> [4]	杨瑞林, 李力军, 李玉成. 新型低合金高强韧性耐磨钢的研究[J]. 钢铁, 1999, 07: 43-47.
> [5]	杨伟国, 黄伟. 中央企业战略社会责任审计报告[M]. 北京: 中国人民大学出版社, 2018.
> [6]	Estrin S., Brada J.C., Gelb A., 等. Restructuring and Privatization in Central Eastern Europe: Case Studies of Firms in Transition:Case Studies of Firms in Transition[M]. New York: Routledge, 1996.
> [7]	张迪. 新中国成立以来中央与地方经济关系演进的历程及经验[D]. 长春: 吉林大学, 2022.
> [8]	郭风旗. 机关党的建设研究—基于党的建设科学化的视角[D]. 北京: 中共中央党校, 2013.
> [9]	Wang, H., Hetzer, F., Huang, W., et al. Structure-Based Evolution of G Protein-Biased μ-Opioid Receptor Agonists.[J]. Angewandte Chemie (International ed. in English), Germany: 2022, 61(26): e202200269.
> [10]	Pomfret, R. The Central Asian Economies Since Independence[M]. Princeton: Princeton University Press, 2006.
>

**Comment by ZhangzhongWa** [comment]
英文页码都是短的杠-

**Comment by ZhangzhongWa** [comment]
除了第一个参考文献，其他参考文献的显示效果和要求的格式一致。

**Comment by redleafnew** [comment]
第一个有什么不对。

**Comment by ZhangzhongWa** [comment]
Frese K.S., Katus H.A., Meder B. 应该是这样Frese, K.S., Katus, H.A., Meder, B.

姓和名之间缺个逗号

**Comment by redleafnew** [comment]
那个文献设置语言错误，不是你的测试条目。随机加的。用你的条目试试。
451

**Comment by ZhangzhongWa** [comment]
OK。大佬能发布一下cls文件吗

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/451lanzhou-university.csl

**Comment by ZhangzhongWa** [comment]
文中引用和参考文献的输出格式都合适。感谢大佬！！！

**Comment by redleafnew** [comment]
如果没有问题，请关闭。
