### ISSUE TITLE
关于大小写的问题

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#16]
我注意到仓库中一些 CSL 有大小写方面的问题。

1. 有的样式去掉了姓全大写的设置，但是将 `<name-part name="family"/>` 的 `text-case` 设为 `capitalize-first` 或者 `capitalize-all` 会有问题，比如“von Neumann” 或者 “al-Aswānī”，这两个姓的首字母是小写的。建议将 `<name-part/>` 的 `text-case` 直接去掉即可。
2. `china-national-standard-gb-t-7714-2015-numeric-aulower-bilan.csl` 和 `china-national-standard-gb-t-7714-2015-numeric-pageout.csl` 中 `<text variable="title"/>` 设置了 `text-case="sentence"`，但是会有副作用：它会把已经大写的专有名词转为小写，比如 “englang” 或者 “who”其实 CSL 已经假定用户输入的内容是 sentence case，应去掉 `text-case="sentence"`。而且 CSL v1.0.2 的文档中（<https://github.com/citation-style-language/documentation/blob/master/specification.rst#sentence-case-conversion>）提到：
> Sentence case conversion is deprecated and will be removed in a future version.

**Comment by redleafnew** [comment]
题目的大小写删除了。作者的碰到再说了。
