### ISSUE TITLE
[question] 咨询关于 Language 字段存储时 ISO 3166 代码的选择

### ISSUE THREAD

**Issue by northword** [redleafnew/Chinese-STD-GB-T-7714-related-csl#160]
晚上好，我想咨询一个问题：

我注意到 Zotero 文档建议将 Language 字段存储为 `ISO 639-1 语言代码`-`ISO 3166-1-aplha2 国家地区代码`：

> The language of publication for an item. We recommend storing these as two letter ISO language codes followed by two letter ISO country codes (e.g., en-US for American English, or de-DE for German).   
> 
> The Language field is used to determine whether English Title Casing rules should be applied when formatting item titles. If the stored item data is in English (e.g., for translated titles), enter en-US or en-UK, even if the item content is in another language.

但是不少 translator 在保存期刊时候并没有保存 Language 字段，所以需要我们自己修改。但很多自动识别语言的库仅能返回 ISO 639 代码，无法确定 ISO 3166 代码，且 ISO 639 代码与 ISO 3166 代码之间也并没有一一对应关系。目前也没有一个较为完整记录期刊与其所在地的列表。在这种情况下仅存储 ISO 639 代码是否也符合规范，并且可以保证 CSL 相关功能正常呢？

我目前计划通过对每一种语言代码直接指定其主要国家代码的方式来组成完整的区域代码，例如，语言代码为 `zh` 时，直接匹配国家代码为 `CN`，类似的，`en` 直接匹配 `US`。我查询到了一份 ISO 639-1 代码对应 ISO 3166 代码的列表，见：https://github.com/oldboyxx/Mapped-Country-Language-Codes/blob/master/language_countries/language_countries_codes.rb ，也即在这份列表中，值为多个的，只保留1个最常用的国家。但这样会损失一部分国家代码，例如`zh-HK`, `en-UK` 等，我也想了解一下 `en-US` 与 `en-HK` 对 CSL 的影响大不大，以及我这样做是否合适。

**Comment by redleafnew** [comment]
导出附件，删除条目时删除附件，自动根据题目批量修改语言的插件：https://github.com/redleafnew/delitemwithatt

只有两种 en-US和zh-CN

https://github.com/northword/zotero-format-metadata
支持更多语种

csl只用语言代码即可

**Comment by zepinglee** [comment]
> 在这种情况下仅存储 ISO 639 代码是否也符合规范，并且可以保证 CSL 相关功能正常呢？

对于 CSL 来说，ISO 3166 国家和地区码是可选的，见 CSL 的文档 <https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables>。

> language
The language of the item;
Should be entered as an ISO 639-1 two-letter language code (e.g. “en”, “zh”), optionally with a two-letter country code (e.g. “de-DE”, “de-AT”)

我记得以前 Zotero 文档中的 country code 也是 optional 的，不知什么时候改了。


> 我目前计划通过对每一种语言代码直接指定其主要国家代码的方式来组成完整的区域代码，例如，语言代码为 `zh` 时，直接匹配国家代码为 `CN`，类似的，`en` 直接匹配 `US`。

我不建议这么做。对于中文来说相当于过度推测了简繁体，可能对港澳台地区的用户不太友好。


> 但这样会损失一部分国家代码，例如`zh-HK`, `en-UK` 等

是 `en-GB` 不是 UK。


> 我也想了解一下 `en-US` 与 `en-HK` 对 CSL 的影响大不大，以及我这样做是否合适。

没有影响，多语言版本的样式一般会写成 `<layout locale="en">`，`en-US` 和 `en-HK` 都满足这个条件。

**Comment by northword** [comment]
收到，明白辽，感谢两位的回复~
