### ISSUE TITLE
请求添加中南林业科技大学研究生学位论文

### ISSUE THREAD

**Issue by jiangcsuft** [redleafnew/Chinese-STD-GB-T-7714-related-csl#161]
**样式信息**

- 期刊/学校名称：[中南林业科技大学研究生学位论文]

- 英文名称：[Central South University of Forestry and Technology]

- 参考文献格式要求的**官网**链接[例如 <https://yjsb.csuft.edu.cn/zlxz/zlxz1/201710/t20171016_66849.html>]

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部期刊/学校官网的示例文献录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

**Comment by redleafnew** [comment]
可以手动录入。

**Comment by jiangcsuft** [comment]
感谢回复，我已经录入了常见的7种示例文献，群组会去测试开发csl吗？

**Comment by zepinglee** [comment]
> 感谢回复，我已经录入了常见的7种示例文献，群组会去测试开发csl吗？

好的，我晚上实现一下这个样式。

**Comment by zepinglee** [comment]
@jiangcsuft 有个问题，中文标点符号是要用全角的吗？建议翻一下往年论文看看实际是怎么操作的。

从示例来看，逗号、冒号是全角，句点却是半角，甚至后面连个空格都没有。这就很不搭配。

**Comment by jiangcsuft** [comment]
> @jiangcsuft 有个问题，中文标点符号是要用全角的吗？建议翻一下往年论文看看实际是怎么操作的。
> 
> 从示例来看，逗号、冒号是全角，句点却是半角，甚至后面连个空格都没有。这就很不搭配。

你说的没错，我去看了往年的论文发现有些排版不对劲，我看了官网的word（https://yjsb.csuft.edu.cn/zlxz/zlxz1/201710/t20171016_66849.html），发现的确存在这个问题，我建议不论中英文，所有标点符号统一全角（我认为这个模板可能是所有标点都是半角之后在空一格），我觉得全部全角也能实现我括号里面说的情况。你看看哪一种容易实现。感谢大佬回复

**Comment by zepinglee** [comment]
“统一全角”的排版效果对英文文献不太友好。在 GB/T 7714 系列的实践中，一般是“统一半角符号+空格”或者“中文文献全角、英文半角”。而且前者的数量比较多。

我先做成“统一半角”，后续有需求再调整。

**Comment by zepinglee** [comment]
> “参照国家标准GB7713-87《科学技术报告、学位论文和学术论文的编写格式》，结合我校具体情况，特制定本规范。”这是我在学校学位论文里面看到的，应该不是按GB7714而是7713，不知道这两种标准不同会造成影响吗？大佬你酌情判断下。

GB/T 7713 引用了 GB/T 7714。像这种带“[J]”文献类型标识符的都是 [GB/T 7714](https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A) 系列的。

**Comment by zepinglee** [comment]
d904f0f 中添加了 [453central-south-university-of-forestry-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/453central-south-university-of-forestry-and-technology.csl)，测试效果见 [tests/styles/453central-south-university-of-forestry-and-technology/README.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/453central-south-university-of-forestry-and-technology/README.md)。

**Comment by jiangcsuft** [comment]
感谢大佬，太强了。

**Comment by jiangcsuft** [comment]
> [d904f0f](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/d904f0f3f2cd256c76f96fefd613463b0dc4d22f) 中添加了 [453central-south-university-of-forestry-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/453central-south-university-of-forestry-and-technology.csl)，测试效果见 [tests/styles/453central-south-university-of-forestry-and-technology/README.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/453central-south-university-of-forestry-and-technology/README.md)。

我看了往年的英文期刊引注，期刊名字需要全称而不是缩写，可能是编者在编辑word的时候搞错了，示例： PéREZ-HARGUINDEGUY N, DiAZ S,GARNIER E,et al. New handbook for standardised measurement of plant functional traits worldwide [J].Australian Joumal of Botany,2013,61(3): 167-235.

**Comment by zepinglee** [comment]
<img width="707" alt="Screenshot 2023-04-19 at 16 36 37" src="https://user-images.githubusercontent.com/12290822/233018222-dd30d8eb-9a23-44e8-a613-1a67401dfe2c.png">

缩写是因为这个示例，确定用全称？

**Comment by zepinglee** [comment]
b366876 改成了全称。
