### ISSUE TITLE
关于NSFC的格式“中英文”混排能否实现呢？

### ISSUE THREAD

**Issue by llity** [redleafnew/Chinese-STD-GB-T-7714-related-csl#162]
目前是中文和英文分开排序，是否有机会实现拼音字母和英文字母的顺序混合排序。

谢谢

**Comment by redleafnew** [comment]
应该是不可以

**Comment by llity** [comment]
zotero v7 会支持吗？等了很久现在beta11

**Comment by redleafnew** [comment]
与Zotero关系不大，是csl规定的。

**Comment by redleafnew** [comment]
可以到csl的github上问问。


> csl能更新支持吗？

@zepinglee

**Comment by zepinglee** [comment]
CSL 团队没别的中国人，估计对这个不太感兴趣。我也不太感兴趣。

如果能在 JavaScript 实现这种排序方法，可以考虑给 <https://github.com/Juris-M/citeproc-js> 提交 PR。据我的了解，`citeproc-js` 用的是 JavaScript 内置的 Unicode 排序排序方法。参考 [UCA](https://unicode.org/reports/tr10/) 和 <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/collation>。

**Comment by llity** [comment]
好的，按首字母排序的功能有一定必要性吧，与中英文分开排序是两种形式区分。

**Comment by redleafnew** [comment]
现在可以做到中英文先分开，然后中文按拼音，英文按字母。仓库中有很多支持的样式。

**Comment by llity** [comment]
endnote应该是支持的，期待大佬帮助实现一下，通过 @zepinglee 说的JS的方式。
