### ISSUE TITLE
请求添加南开管理评论样式

### ISSUE THREAD

**Issue by laixiup** [redleafnew/Chinese-STD-GB-T-7714-related-csl#163]
**样式信息**

- 期刊/学校名称：南开管理评论

- 英文名称：Nankai Business Review

- 参考文献格式要求的**官网**链接: https://nbr.nankai.edu.cn/mainx_concept.aspx?psu=D272C35A2C538F7063C0445C15A99651&jid=nkglpl&login_flag=author
- 南开管理评论参考文献要求：稿件采用哈佛注释法，请务必确保正文和文后参考文献的一一对应。具体要求如下：

① 正文中的中文文献引用

l  单个作者文献以（作者姓名，出版年份）或作者姓（出版年份）形式引用，如（张三,1993）或张三（1993）；

l  两个及以上作者文献以（第一作者等，出版年份）形式引用，如（张三等，2005）。

② 正文中的英文文献引用

l  单个作者文献以（作者姓，出版年份）或作者姓（出版年份）形式引用，如（Edward,1993）或Edward（1993）；

l  两个及以上作者文献以（第一作者et al.，出版年份）形式引用，如（Edward et al.,2005）。

③ 正文后的参考文献格式

l  中英文参考文献分开，中文在前，英文在后，并分别按姓氏的26个字母排序；

l  被引用的作者在同一年中出版了两部以上著作或发表了两篇以上的论文，用小写字母a.b.c等予以区别，放在年份后，如，Johnson（1989a)；

l  中文参考文献中的标点符号都用全角；英文文献实词首字母大写，虚词首字母小写；中英文参考文献最好能标出卷号；注意文后参考文献将所有作者姓名列全，各个作者之间用“，”隔开，不用“and”；英文作者姓氏写全（包括复姓），名字采用大写首字母加“.”的缩写形式；特别注意，英文末位作者名字缩写符“.”之后，还需要再加一个“.”，以示作者与文章的分隔。

l  具体格式举例为：

张闯, 鄂嫚迪, 顾芳. 渠道建言:多层面驱动因素及其对渠道绩效的影响. 南开管理评论, 2020, 23(2):169-180.

Monserrat, S. I., Simmers, C. A.. Human and Social Capital as Influencers on Women’s Careers: Rosemary Pledger’s Path to Career Success and Mobility. Journal of Management History, 2020, 26(4):471-489.

（5）专著、会议论文、学位论文、报刊文章、网站文章、专著或文集析出的文献等引用按如下举例格式：

张玉利. 管理学.南开大学出版社, 2013-12-01.

白长虹. 商学院，在全球变局中坚守引领使命. 第八届全球商学院院长论坛, 2020.

郝胜宇.基于顾客视角的城市品牌评价研究.南开大学, 2011.

白长虹.科学精神与家国情怀. 湖南日报, 2014-12-02.

白长虹.数字化时代，品牌价值变得更加复杂. https://new.qq.com/omn/20201220/ 20201220A0BU0H00.html, 2020-12-20.

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：sociology

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
@laixiup 已经准许加入群组。

参考文献要求有对应的官网链接吗？<https://nbr.nankai.edu.cn/mainx_concept.aspx?psu=D272C35A2C538F7063C0445C15A99651&jid=nkglpl&login_flag=author> 在未登录的情况下无法访问。

**Comment by redleafnew** [comment]
不需要了吗？

**Comment by ZYC22** [comment]
怎么没有了
