### ISSUE TITLE
427电子科技大学学位论文参考文献标题大小写问题

### ISSUE THREAD

**Issue by caimumuxin** [redleafnew/Chinese-STD-GB-T-7714-related-csl#164]
**描述错误**

CSL 样式：427university-of-electronic-science-and-technology-of-china.csl

电子科技大学学位论文格式
要求：（5）除特殊名词外，英文文献标题（论文题目、书名）仅第一个单词的首字母大写，其余全部小写；
在github项目首页预览里面论文标题是只有第一个单词首字母大写，实际导入csl格式后是标题里每个单词都首字母大写
实际示例：Ren S, He K, Girshick R B, et al. Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks[J]. IEEE Trans. Pattern Anal. Mach. Intell., 2017, 39(6): 1137-1149.
PS：Zotero里面存储的论文标题信息是每个单词首字母大写

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/9367501/items/U9NPNQNY",
		"type": "article-journal",
		"container-title": "IEEE Trans. Pattern Anal. Mach. Intell.",
		"DOI": "10.1109/TPAMI.2016.2577031",
		"issue": "6",
		"language": "en-US",
		"page": "1137–1149",
		"title": "Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks",
		"URL": "https://doi.org/10.1109/TPAMI.2016.2577031",
		"volume": "39",
		"author": [
			{
				"family": "Ren",
				"given": "Shaoqing"
			},
			{
				"family": "He",
				"given": "Kaiming"
			},
			{
				"family": "Girshick",
				"given": "Ross B."
			},
			{
				"family": "Sun",
				"given": "Jian"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2017"
				]
			]
		}
	}
]
```

**Comment by redleafnew** [comment]
用这个插件，在Zotero中将题目修改为句首字母大写吧。
导出附件，删除条目时删除附件，自动根据题目批量修改语言的插件：https://github.com/redleafnew/delitemwithatt

**Comment by caimumuxin** [comment]
OK 感谢 ，虽然有点麻烦，不过解决问题了。
有没有直接从csl文件解决问题的方法？

**Comment by redleafnew** [comment]
可以选择多个条目同时修改，也不麻烦。

csl可以设置为句首字母大写，但会带来一些问题，一些专有名词会修改为小写，如DNA，USA。

**Comment by caimumuxin** [comment]
嗯嗯，感谢

**Comment by caimumuxin** [comment]
嗯嗯，我所谓麻烦是指以后投其他论文的时候可能这个标题还得再改，不过还是感谢了

**Comment by redleafnew** [comment]
不用，一般改为句首大写后，如果需要词首大写，csl中就可以方便实现。

**Comment by zepinglee** [comment]
@caimumuxin Zotero 要求 `title` 字段使用 sentence case，见 <https://www.zotero.org/support/kb/item_types_and_fields#general_fields> 和 <https://www.zotero.org/support/kb/sentence_casing>。

> 嗯嗯，我所谓麻烦是指以后投其他论文的时候可能这个标题还得再改，不过还是感谢了

使用 sentence case 就不需要再改了。CSL 样式可以将 sentence case 自动转为 title case。但是反过来一般不能直接转换，因为不能自动识别专有名词。

**Comment by caimumuxin** [comment]
> @caimumuxin Zotero 要求 `title` 字段使用 sentence case，见 https://www.zotero.org/support/kb/item_types_and_fields#general_fields 和 https://www.zotero.org/support/kb/sentence_casing。
> 
> > 嗯嗯，我所谓麻烦是指以后投其他论文的时候可能这个标题还得再改，不过还是感谢了
> 
> 使用 sentence case 就不需要再改了。CSL 样式可以将 sentence case 自动转为 title case。但是反过来一般不能直接转换，因为不能自动识别专有名词。

明白
