### ISSUE TITLE
请求添加中国农业大学研究生学位论文参考文献格式

### ISSUE THREAD

**Issue by cuihaoyanggithub** [redleafnew/Chinese-STD-GB-T-7714-related-csl#167]
**样式信息**

期刊/学校 名称：中国农业大学研究生学位论文
英文名称：Journal of China Agricultural University(Social Science)
参考文献格式要求的官网链接：<http://zgnydxsk.cnjournals.net/ch/first_menu.aspx?parent_id=20130507011716001>
ISSN号：1009-508X
相关领域：social science

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
不需要了？
