### ISSUE TITLE
请求添加中国药科大学毕业论文规范

### ISSUE THREAD

**Issue by Enceladus6** [redleafnew/Chinese-STD-GB-T-7714-related-csl#169]
样式信息

- 期刊/学校名称：[中国药科大学本科生学位论文]

- 英文名称：[China Pharmaceutical University （CPU）]

- 参考文献格式要求的官网链接：http://jwc.cpu.edu.cn/23/27/c924a140071/page.htm

测试条目

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部期刊/学校官网的示例文献录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: Enceladus6

**Comment by zepinglee** [comment]
<img width="843" alt="Screenshot 2023-05-26 at 09 30 23" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/636a7d99-0fb4-48fa-876e-64624304fc9e">

已提升为 admin 权限。

**Comment by Enceladus6** [comment]
文献已添加

**Comment by zepinglee** [comment]
<img width="468" alt="Screenshot 2023-05-28 at 11 32 06" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/78c6d4c1-b391-4c56-a25e-50abd8adfc6f">

官方的示例只录入了 3 篇？

<img width="859" alt="Screenshot 2023-05-28 at 11 33 49" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/076b4e79-1a68-4a5f-83aa-0a92ce976390">

另外还有这么一堆重复的。

**Comment by Enceladus6** [comment]
已重新录入，学校要求中文参考资料翻译成英文，需要我手动添加标题翻译吗？
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/51427409/0f434ae7-e32b-416d-a09a-a897431b115c)

**Comment by zepinglee** [comment]
> 已重新录入，学校要求中文参考资料翻译成英文，需要我手动添加标题翻译吗？

是的，姓名也要填英文。

**Comment by Enceladus6** [comment]
标题、姓名已翻译为英文

**Comment by zepinglee** [comment]
好的。

@Enceladus6 这个 `titleTranslation` 是用什么插件填的吗？

<img width="374" alt="Screenshot 2023-05-31 at 21 15 58" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/c61fffb4-7b64-4691-abf3-1998298833ee">

**Comment by zepinglee** [comment]
已添加 [455china-pharmaceutical-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/455china-pharmaceutical-university.csl)。测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/main/tests/styles/455china-pharmaceutical-university>。

**Comment by Enceladus6** [comment]
感谢大佬，目前发现有两个问题
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/51427409/6135b947-eaf6-4178-910b-0b44d346cb81)
chegn
如图：
1. 橙色框中，最外侧的括号可以自动识别为中括号吗？比如“[化学品 分配系数(正辛醇-水)摇瓶法试验]”
2.  红色框应为斜体

**Comment by zepinglee** [comment]
> 1. 橙色框中，最外侧的括号可以自动识别为中括号吗？比如“[化学品 分配系数(正辛醇-水)摇瓶法试验]”

这个无法实现。参考文献又不是数学式，没搞懂为何要转成方括号。

> 2. 红色框应为斜体

OK，我改一下。

**Comment by zepinglee** [comment]
已在 4b577b7 中修改。

**Comment by zepinglee** [comment]
> 此外我看到不同类型的文献有字段缺失，或者补充在“其他”中。那么以后新增此类文献，以测试的这些作为模板修改元数据就可以了吗？

是的。

> 我看到其他中有“citation key”这个字段是什么意思呢？

这个主要是为了导出 CSL-JSON 有固定的 id 进行排序，这样生成的文献顺序跟示例一样，比较时更方便。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/358ac959a1155cd8819bdfe8f62bac7cc69bc08c/tests/styles/455china-pharmaceutical-university/test-data.json#L2-L4

**Comment by Enceladus6** [comment]
专利的题名（Line 52）原先的CSL在识别中文专利时，无法自动添加翻译，是不是在中间加一行，改了冒号位置就可以
<else-if type="patent">
    <text variable="title"/>
        <group delimiter=": ">
            **<text variable="original-title" prefix="(" suffix=")"/>**
                <group delimiter=", ">
                    <text macro="patent-country" font-style="italic"/>
                    <text variable="number"/>
                </group>
        </group>
</else-if>

**Comment by huyuanbo** [comment]
> > 此外我看到不同类型的文献有字段缺失，或者补充在"其他"中。那么以后新增此类文献，以测试的这些作为模板修改元数据就可以了吗？
> 
> 是的。
> 
> > 我看到其他中有“citation key”这个字段是什么意思呢？
> 
> 这个主要是为了导出 CSL-JSON 有固定的 id 进行排序，这样生成的文献顺序跟示例一样，比较时更方便。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/358ac959a1155cd8819bdfe8f62bac7cc69bc08c/tests/styles/455china-pharmaceutical-university/test-data.json#L2-L4

帮忙看一下第七个请求（格乐大学）

**Comment by huyuanbo** [comment]
Can you help with this document format? The number is #190




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月29日(周六) 凌晨0:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 请求添加中国药科大学毕业论文规范 (Issue #169)




 
Closed #169 as completed.
