### ISSUE TITLE
部分期刊论文显示为[Z]标识

### ISSUE THREAD

**Issue by earthmoon** [redleafnew/Chinese-STD-GB-T-7714-related-csl#171]
**部分期刊论文显示为`[Z]`标识**

CSL 样式：001gb-t-7714-2015-author-date-bilingual.csl

比如这篇文章：
```
@article{李浩2021,
  type = {10.19694/j.cnki.issn2095-2457.2021.15.10},
  title = {基于遗传算法的城市湖面污染监测及溯源系统},
  author = {{李浩}},
  date = {2021},
  journaltitle = {科技视界},
  volume = {345},
  number = {15},
  pages = {31--32},
  doi = {10.19694/j.cnki.issn2095-2457.2021.15.10},
  abstract = {为了增强监管人员对城市湖泊的感知与管理能力,文章基于低功耗广域网通信技术设计了湖泊污染监测及溯源系统。通过将水质感知浮标阵列部署于湖泊水面,采集湖面各处的水体状况,而后在云服务器上建立湖泊污染扩散模型,通过遗传算法分析数据追溯污染源头。},
  isbn = {2095-2457},
  langid = {chinese},
  keywords = {Read,遗传算法;低功耗广域网;污染溯源},
}

```

显示为：
>李浩, 2021. 基于遗传算法的城市湖面污染监测及溯源系统[Z/OL]//科技视界: 卷 345. 31-32. DOI:10.19694/j.cnki.issn2095-2457.2021.15.10.

为什么是`[Z]`标识而不是`[J]`?

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/45897471/17555f85-422f-45e6-b723-7fdce13909ee)

**条目信息**

```json
[
	{
		"id": "李浩2021",
		"type": "article-journal",
		"abstract": "为了增强监管人员对城市湖泊的感知与管理能力,文章基于低功耗广域网通信技术设计了湖泊污染监测及溯源系统。通过将水质感知浮标阵列部署于湖泊水面,采集湖面各处的水体状况,而后在云服务器上建立湖泊污染扩散模型,通过遗传算法分析数据追溯污染源头。",
		"archive_location": "CNKI",
		"call-number": "31-2065/N",
		"container-title": "科技视界",
		"DOI": "10.19694/j.cnki.issn2095-2457.2021.15.10",
		"issue": "15",
		"language": "zh",
		"note": "ISBN: 2095-2457\ntype: 10.19694/j.cnki.issn2095-2457.2021.15.10",
		"page": "31-32",
		"title": "基于遗传算法的城市湖面污染监测及溯源系统",
		"volume": "345",
		"author": [
			{
				"literal": "李浩"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2021"
				]
			]
		}
	}
]
```

谢谢！

**Comment by zepinglee** [comment]
因为 Zotero 的 `Extra` 字段（对应 CSL-JSON 的 `note`）有 `type: 10.19694/j.cnki.issn2095-2457.2021.15.10`，所以被当成 `10.19694/j.cnki.issn2095-2457.2021.15.10` 类型处理而不是 `article-journal`，对应 GB/T 7714 中的“其他”类型标识符“Z”。

删掉这一行即可。

另外建议更新 CNKI 的translator，应该修复了这一抓取的问题。

**Comment by earthmoon** [comment]
> 因为 Zotero 的 `Extra` 字段（对应 CSL-JSON 的 `note`）有 `type: 10.19694/j.cnki.issn2095-2457.2021.15.10`，所以被当成 `10.19694/j.cnki.issn2095-2457.2021.15.10` 类型处理而不是 `article-journal`，对应 GB/T 7714 中的“其他”类型标识符“Z”。
> 
> 删掉这一行即可。
> 
> 另外建议更新 CNKI 的translator，应该修复了这一抓取的问题。

删除这一行可以了，是这个问题。该怎么更新CNKIde translator呢？  谢谢

**Comment by zepinglee** [comment]
> 删除这一行可以了，是这个问题。该怎么更新CNKIde translator呢？ 谢谢

茉莉花插件。

**Comment by earthmoon** [comment]
> > 删除这一行可以了，是这个问题。该怎么更新CNKIde translator呢？ 谢谢
> 
> 茉莉花插件。

谢谢！
