### ISSUE TITLE
请求添加 西南政法大学研究生学位论文格式

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#172]
**样式信息**

- 学校名称：[西南政法大学]

- 英文名称：[Southwest University of Political Science & Law]

- 参考文献格式要求的**官网**链接[<https://yjsy.swupl.edu.cn/xwgl/lwgsgf/f3a70c007f8b46a2b8790270af297222.html>]

-->

**测试条目**
加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:-yzy-

**其他样式信息**

**Comment by redleafnew** [comment]
使用note格式的样式？

**Comment by yzy1228682367** [comment]
好的，稍等我做一份~

**Comment by yzy1228682367** [comment]
[2023西南政法大学硕士学位论文格式要求-20230301.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11611332/2023.-20230301.docx)
您看这样可以吗？在每一种引注下面给了样例。

**Comment by redleafnew** [comment]
就是这个正文引注的参考文献样式是数字的还是作者年代的，还是note格式的？

**Comment by yzy1228682367** [comment]
是数字
这个是模板
![CleanShot 2023-05-31 at 18 24 43@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/e6f360cf-55fe-4710-af13-186309f7ddaa)
[个人数据跨境流动的充分保护原则研究_李煜.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/11611839/_.pdf)

**Comment by zepinglee** [comment]
这种属于 note 类。

这份格式要求没有给出示例文献，制作样式时很不方便。我在《法学引注手册》样式（[301manual-of-legal-citation-multi-lingual.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/301manual-of-legal-citation-multi-lingual.csl)）的基础上修改了一份 [456southwest-university-of-political-science-and-law.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/456southwest-university-of-political-science-and-law.csl)。可能还有格式问题，建议检查一下。显示效果见 [test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/456southwest-university-of-political-science-and-law/test.md)。

**Comment by yzy1228682367** [comment]
太感谢了❤️ 我看了一遍，大致没有问题啦。唯一的问题可能就是选集没有办法比较好的去直接引注，因为zotero也没有选集这个类别。再次感谢❤️
![CleanShot 2023-06-01 at 13 35 25@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/439cc472-a119-4db3-b19c-e7f7dfacab0c)

**Comment by zepinglee** [comment]
<img width="775" alt="Screenshot 2023-06-01 at 13 46 21" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/6ebb775b-65a2-4bdd-81bc-39679c6e5b85">

这几类其实没有本质区别，都用 `book` 类型。

《毛选》这篇文献是官网格式要求的示例吗？我好想没有看到？

**Comment by yzy1228682367** [comment]
是我根据官网格式要求做的例子～
