### ISSUE TITLE
您好，Pandoc似乎并不支持CSL-M，因而导致无法使用markdown插入引用文献，请问有什么解决的方法吗？

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#177]
![CleanShot 2023-06-06 at 00 38 41@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/0c6aa4f0-ac2b-4960-a94d-a6b5155983e7)
报错信息
Error: Command failed: pandoc --from=markdown-raw_tex+tex_math_single_backslash --to=html --katex --citeproc
CiteprocParseError: Multiple layout elements present in bibliography

**Comment by zepinglee** [comment]
没有办法，见 <https://github.com/jgm/citeproc/issues/120>。

可以考虑：

1. 给 <https://github.com/jgm/citeproc> 写 patch 支持改功能（我尝试学了一下 haskell，但是放弃了）；
2. 说服 jgm 教授实现这个功能。

**Comment by yzy1228682367** [comment]
好的感谢~

**Comment by yzy1228682367** [comment]
![CleanShot 2023-06-06 at 14 40 07@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/8e157849-c366-4e24-b3fd-86aef9a6c567)
请问我要怎么把默认语言改为中文呢？

**Comment by zepinglee** [comment]
具体哪个样式？某些功能只有在默认语言为英语时才能正确输出，比如 title case 转换。

**Comment by yzy1228682367** [comment]
![CleanShot 2023-06-06 at 15 23 02@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/a341738e-7ff8-418f-976d-2d2183bdc7c0)
您好，即使只输出中文，格式似乎也不正确？第一，“@wangliming2019”应当仅仅转为“1”这个角标，但是转为了‘王利明1’。第二，尾注少了作者。请问这个可以加上作者吗？或者可以只输出脚注而不输出尾注吗？

**Comment by zepinglee** [comment]
建议找一下 pandoc 的文档。

> 第一，“@wangliming2019”应当仅仅转为“1”这个角标，但是转为了‘王利明1’。

 <https://pandoc.org/MANUAL.html#citations-in-note-styles>

<https://pandoc.org/MANUAL.html#extension-citations>

<img width="851" alt="Screenshot 2023-06-06 at 15 44 46" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/e47625c9-903d-4770-8490-450df7aee60b">


第二，尾注少了作者。请问这个可以加上作者吗？或者可以只输出脚注而不输出尾注吗？

<https://pandoc.org/MANUAL.html#placement-of-the-bibliography>

**Comment by yzy1228682367** [comment]
好的，感谢，我研究一下，谢谢~

**Comment by yzy1228682367** [comment]
哦吼 我发现可以直接用zotero做笔记，然后插入笔记到word就可以了。谢啦

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/78457ca8-8a98-491e-beec-fe495a529308

**Comment by davidchen1996** [comment]
没有办法，rmd的pandoc也存在这个不完美的问题。在混排中英文文档时很头疼

**Comment by a76854** [comment]
过了九个月了，使用pandoc将LaTeX转为docx还是不支持CSL-M。

**Comment by zepinglee** [comment]
作者应该没打算支持吧。

**Comment by rLry** [comment]
org-cite导出也有同样问题，原来是不支持CLS-M。

**Comment by TomBener** [comment]
我写了一个 [Lua filter](https://github.com/TomBener/quarto-cn-tools/blob/main/_extensions/localize-cnbib.lua)，可以基本实现用 Pandoc Citeproc 中英双语排版。在 CSL 语言设置为 `en` 的前提下：

- 将中文文献的 `et al.` 替换为 `等`
- `vol. X` 替换为 `第X卷`
- `trans.` 替换为 `译`
- `ed.` 或 `eds.` 替换为 `编`
- `ed.` 替换为 `编` 或 `第X版`

需要注意的是，这个 Lua filter 是基于特定的 CSL 样式写的，也就是仓库中的 `gb-author-date.csl` 和 `gb-numeric.csl`，其他 CSL 样式可能不会起作用。另外，如果在 Quarto 中使用，无法在 YAML 文件中指定这个 Lua filter，只能在命令行中使用 `-L _extensions/localize-cnbib.lua`，这是因为 Quarto 目前 [不支持在 Citeproc 之后](https://github.com/quarto-dev/quarto-cli/issues/7888) 执行 Lua filter。

**Comment by zepinglee** [comment]
> 我写了一个 [Lua filter](https://github.com/TomBener/quarto-cn-tools/blob/main/_extensions/localize-cnbib.lua)，可以基本实现 Pandoc Citeproc 中英双语排版参考文献。在 CSL 语言设置为 `en` 的前提下，能够：
> 
> * 将中文文献的 `et al.` 替换为 `等`
> * `vol. X` 替换为 `第X卷`
> * `trans.` 替换为 `译`
> * `ed.` 或 `eds.` 替换为 `编`
> * `ed.` 替换为 `编` 或 `第X版`

我没试过但仅作为提醒，“et al.”有时会与后续的句点合并，所以替换为“等”时需要考虑是否保留句点。

<img width="763" alt="Screenshot 2024-06-20 at 10 53 21" src="https://github.com/zotero-chinese/styles/assets/12290822/e9e19843-9497-4b71-913d-72ce3e552c64">

另外国标的版本项是“x 版”不是“第 x 版”。

<img width="803" alt="Screenshot 2024-06-20 at 10 56 24" src="https://github.com/zotero-chinese/styles/assets/12290822/10f41b28-049e-4614-8e52-83f71a1d83f2">

**Comment by zepinglee** [comment]
> org-cite导出也有同样问题，原来是不支持CLS-M。

@rLry 与之相关的项目应该是 https://github.com/andras-simonyi/citeproc-el

**Comment by TomBener** [comment]
> 我没试过但仅作为提醒，“et al.”有时会与后续的句点合并，所以替换为“等”时需要考虑是否保留句点。

代码中考虑了这种情况。

> 另外国标的版本项是“x 版”不是“第 x 版”。

这个还真没注意，主要是因为我看到 [hushidong/biblatex-gb7714-2015](https://github.com/hushidong/biblatex-gb7714-2015) 生成的是 `第X版`，不过稍微修改一下 Lua 代码就可以。

**Comment by rLry** [comment]
> > org-cite导出也有同样问题，原来是不支持CLS-M。
> 
> @rLry 与之相关的项目应该是 https://github.com/andras-simonyi/citeproc-el

citeproc-el一样是支持CSL1.0.2，还是希望csl-m进标准吧，源头push
