### ISSUE TITLE
请求添加《经济学（季刊）》参考文献样式

### ISSUE THREAD

**Issue by ivorycanoe** [redleafnew/Chinese-STD-GB-T-7714-related-csl#178]
**样式信息**

- 期刊/学校名称：经济学（季刊）

- 英文名称：[ＣｈｉｎａＥｃｏｎｏｍｉｃＱｕａｒｔｅｒｌ

- 参考文献格式要求的**官网**链接：https://www.nsd.pku.edu.cn/cbw/jjxjk/tgzg/250625.htm
- 参考文献格式要求：、
-4) 正文中对文献的引用采用如“根据Black (1948：pp.66)的结论 ……” 、“单峰偏好 …… (Black, 1948)”、或“正如吉登斯所言：‘……’（吉登斯，2000：第53页）”的形式。
5) 文末的参考文献应包括且仅包括正文中引用过的文献。参考文献按作者姓名首位字母顺序编号排列（中英文混排），体例如下：
[1] 布伦纳, “中国农村财产分配的重新考察”, 载赵人伟、李实、李思勤主编《中国居民收入分配再研究》。 北京：中国财政经济出版社, 1999年。
[2] Ehtisham, A., and Y. Wang,“Inequality and Poverty in China：Institutional Change and Public Policy, 1978 to 1988”，The World Bank Economic Review, 1991, 5(2), 231-257.
[3] Riskin, C., R. Zhao, and S. Li, China’s Retreat from Equality: Income Distribution and Economic Transition. New York: M.E. Sharpe, 2001.
[4] 王今美、张松，“中国新股弱势问题研究”，《经济研究》，2000年第9期，第49－56页。

- （期刊的）ISSN 号：2095-1086

- （期刊的）相关领域：sociology

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**Comment by zepinglee** [comment]
“参考文献按作者姓名首位字母顺序编号排列”实现不了。

另外将这几篇录入群组方便测试。

**Comment by ivorycanoe** [comment]
已加入群组，Zotero ID: jingalaxy

**Comment by zepinglee** [comment]
<img width="863" alt="Screenshot 2023-06-08 at 10 40 05" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/4bbddd78-34a2-453a-b9c3-104a53762fd8">

已提升为 admin 赋予编辑权限。

**Comment by ivorycanoe** [comment]
参考文献2-4已录入群组。
参考文献1未能找到相关链接，且形式不常用，未录入。感谢

**Comment by zepinglee** [comment]
在 587a81b 中添加了对应的 CSL 样式。

不过还有个问题：从格式要求来看，英文文献的引用使用半角括号，中文文献使用全角括号。但是目前生成的中文文献效果是，左侧是半角括号，右侧是全角括号。@redleafnew 有没有遇到过这个问题？

> 4) 正文中对文献的引用采用如“根据Black (1948：pp.66)的结论 ……” 、“单峰偏好 …… (Black, 1948)”、或“正如吉登斯所言：‘……’（吉登斯，2000：第53页）”的形式。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/587a81b17e5293a4eb0a0b38ea7f47a64e1f59a3/tests/styles/219china-economic-quarterly/README.md?plain=1#L7-L13

@ivorycanoe 能不能从该期刊的文章中找一下哪种括号样式。

**Comment by ivorycanoe** [comment]
> @ivorycanoe 能不能从该期刊的文章中确认一下实际使用的是哪种括号样式。

从该期刊最新刊出的文章上看，无论中文和英文文献的引用都使用半角括号。中文文献引用使用全角逗号，英文文献使用半角逗号。具体实例如下：

"就教育减负政策效果收效甚微的影响机制而言，有文献将其归因于减负政策的制定、实施或保障存在系统性缺陷 (王建琴，2007;王小利，2009)。"
"与教育减负密切相关的教育不平等问题一直是经济学的重要研究对象 (Mincer, 1974; Becker, 1975; Becker et al., 1990; Barro, 2001)。"

**Comment by zepinglee** [comment]
> > @ivorycanoe 能不能从该期刊的文章中确认一下实际使用的是哪种括号样式。
> 
> 从该期刊最新刊出的文章上看，无论中文和英文文献的引用都使用半角括号。中文文献引用使用全角逗号，英文文献使用半角逗号。具体实例如下：
> 
> "就教育减负政策效果收效甚微的影响机制而言，有文献将其归因于减负政策的制定、实施或保障存在系统性缺陷 (王建琴，2007;王小利，2009)。" "与教育减负密切相关的教育不平等问题一直是经济学的重要研究对象 (Mincer, 1974; Becker, 1975; Becker et al., 1990; Barro, 2001)。"

可以给一段截图吗？

**Comment by ivorycanoe** [comment]
图 1: PDF 截图
<img width="763" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/79591003/d2eaf781-a333-47d8-8156-767882598771">
图2:HTML截图
<img width="1094" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/79591003/7b2eb46b-63d7-4f98-8c58-724ea97c2e9a">

**Comment by zepinglee** [comment]
从 PDF 来看，括号、逗号、分号都是全角的。“et al.”的句点是半角的。一个证据是，这里的逗号不在基线位置上，不符合西文字体的设计习惯。

<img width="170" alt="244381966-d2eaf781-a333-47d8-8156-767882598771" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/7ce65141-254d-4784-8c44-c1184e631628">

我暂时改成全角。后续如果编辑反馈什么意见的话我再修改。

**Comment by ivorycanoe** [comment]
感谢！
