### ISSUE TITLE
安装csl时发生未可预知的错误

### ISSUE THREAD

**Issue by yangtzech** [redleafnew/Chinese-STD-GB-T-7714-related-csl#18]
安装b-t-7714-2015-numeric-aulower-bilan(1).csl和china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi (1).csl时发生未可预知的错误

zotero版本是5.0.97-beta.57+07df7d0de

![image](https://user-images.githubusercontent.com/41911522/145780370-6c291026-f5e6-4902-9a0c-958046320be7.png)
![image](https://user-images.githubusercontent.com/41911522/145780647-337cfd2d-21c6-4d21-9297-b529994cc713.png)

**Comment by redleafnew** [comment]
csl网址贴一下，印象中仓库中的文件名没有带（1）的

**Comment by yangtzech** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl

https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl/blob/main/china-national-standard-gb-t-7714-2015-numeric-aulower-bilan.csl
这两个，（1）应该是我重复下载的时候添加的

**Comment by redleafnew** [comment]
我安装没有问题啊，你把原来重名的删除再重新安装试试。

**Comment by yangtzech** [comment]
第一次下载不带（1），安装失败，在zotero里面点 “—”会把文件删掉，所以我重启，再次下载（文件带（1）），还是不行。可能因为我是beta版吧。

**Comment by redleafnew** [comment]
beta的我没有试过

**Comment by redleafnew** [comment]
不用下载，在网址点击raw，如果Zotero是打开会直接安装。

**Comment by redleafnew** [comment]
点击raw下载，然后再添加，尽管提示不是合法的csl，但可以添加，使用也没有问题。

**Comment by yangtzech** [comment]
直接点raw不行
![image](https://user-images.githubusercontent.com/41911522/145794231-c0e04a62-69a9-4ca8-bac3-774efdabdbc8.png)

不会提示不合法而是直接失败

下面这个会提示失败但可以用
https://www.jianguoyun.com/p/DTQa_l8QtOD-BRj3y9AD
![image](https://user-images.githubusercontent.com/41911522/145794861-a818b10b-7ada-41d8-824c-d977725e4310.png)

**Comment by zepinglee** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl
> 
> https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl/blob/main/china-national-standard-gb-t-7714-2015-numeric-aulower-bilan.csl 这两个，（1）应该是我重复下载的时候添加的

我这边的 macOS Zotero 5.0.96.3 可以正常导入这两个文件（除了 CSL 1.0.1 schema 的警告），没有报错。

**Comment by zepinglee** [comment]
我觉得需要整理一下 `china-national-standard-gb-t-7714-2015-*.csl` 和 `gb-t-7714-2015-*.csl`，感觉不看代码都不知道这些文件改了哪些格式。

**Comment by redleafnew** [comment]
有的有显示效果，有人需要就用了，懒得搞了

**Comment by yangtzech** [comment]
退回到win10 Zotero 5.0.96.3还是不行

**Comment by zepinglee** [comment]
> 有的有显示效果，有人需要就用了，懒得搞了

主要是整理一下文件名，另外在 `<title>` 标签记录简要的修改信息，详细的修改的内容记录到 `<summary>` 标签。
<img width="693" alt="Screen Shot 2021-12-13 at 19 43 17" src="https://user-images.githubusercontent.com/12290822/145806352-10c8d56f-ac4d-4360-93a2-fd1292f465c7.png">

**Comment by zepinglee** [comment]
> 退回到win10 Zotero 5.0.96.3还是不行

我怀疑是因为从 `D:\Program\Data\Zotero\style` 安装的，你试试从别的地方安装？

**Comment by yangtzech** [comment]
> > 退回到win10 Zotero 5.0.96.3还是不行
> 
> 我怀疑是因为从 `D:\Program\Data\Zotero\style` 安装的，你试试从别的地方安装？

还是不行。。。
![image](https://user-images.githubusercontent.com/41911522/145807157-78aeda15-133f-46d1-ae20-c81fa53849a5.png)

**Comment by zepinglee** [comment]
> 还是不行。。。 

GG 搞不定

**Comment by redleafnew** [comment]
> > 有的有显示效果，有人需要就用了，懒得搞了
> 
> 主要是整理一下文件名，另外在 `<title>` 标签记录简要的修改信息，详细的修改的内容记录到 `<summary>` 标签。 <img alt="Screen Shot 2021-12-13 at 19 43 17" width="693" src="https://user-images.githubusercontent.com/12290822/145806352-10c8d56f-ac4d-4360-93a2-fd1292f465c7.png">

这倒是可以，我早就想搞了，现在文件名太长，在csl窗口有时显示不全。

**Comment by yangtzech** [comment]
我不理解，现在好像又可以了
![image](https://user-images.githubusercontent.com/41911522/145812651-26ef0476-5af3-496a-aa82-cbe6b3637db5.png)
但是之前的china-national-standard-gb-t-7714-2015-numeric-BiLan（https://www.jianguoyun.com/p/DTQa_l8QtOD-BRj3y9AD ）又不行了
![image](https://user-images.githubusercontent.com/41911522/145812836-1f17d729-af5d-4b43-a0ee-58a5543ed945.png)

然后我又看了下，之前下载的文件有问题，但不知道为啥从GitHub点raw安装也不行
![image](https://user-images.githubusercontent.com/41911522/145812984-f472928f-5cd4-45e9-9cf3-88493eec481b.png)

总之，谢谢两位了😁

**Comment by zepinglee** [comment]
> 然后我又看了下，之前下载的文件有问题，但不知道为啥从GitHub点raw安装也不行 ![image](https://user-images.githubusercontent.com/41911522/145812984-f472928f-5cd4-45e9-9cf3-88493eec481b.png)

这个是显示的 HTML 不是 CSL 文件的格式。raw 不行可能是科学上网的问题，可以考虑 Gitee 的镜像 <https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl>。

**Comment by redleafnew** [comment]
点raw Zotero中无法直接安装，因为代码中有两个layout，只能下载下csl本地安装，Jurism倒是可以。

**Comment by yangtzech** [comment]
> > 然后我又看了下，之前下载的文件有问题，但不知道为啥从GitHub点raw安装也不行 ![image](https://user-images.githubusercontent.com/41911522/145812984-f472928f-5cd4-45e9-9cf3-88493eec481b.png)
> 
> 这个是显示的 HTML 不是 CSL 文件的格式。raw 不行可能是科学上网的问题，可以考虑 Gitee 的镜像 https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl。

好的😁

**Comment by yangtzech** [comment]
> 点raw Zotero中无法直接安装，因为代码中有两个layout，只能下载下csl本地安装，Jurism倒是可以。

好了

**Comment by redleafnew** [comment]
是什么原因造成的呢

**Comment by yangtzech** [comment]
> 是什么原因造成的呢

应该是网络问题吧，虽然一直科学着

**Comment by redleafnew** [comment]
ok，那关闭issue了啊

**Comment by ludedage** [comment]
直接用txt打开Zotero\styles\中的某个xx.csl文件；将要导入的.csl文件中的代码复制，替换原xx.csl文件内容，保存；使用时选择xx.csl格式也可

**Comment by xianchengyue** [comment]
我刚才也遇到这个问题了，假设我想安装的是“A.csl”，解决方案是打开zotero的数据文件夹，以我的为例是“E:\Zotero\styles”，我发现这个路径下已经有“A.csl”文件，删掉后，在安装新下载的样式就不会报错了
