### ISSUE TITLE
请求添加华中科技大学-计算机学院-硕士-学位论文参考文献格式

### ISSUE THREAD

**Issue by sheli00** [redleafnew/Chinese-STD-GB-T-7714-related-csl#180]
**样式信息**

- 期刊/学校名称：[华中科技大学计算机学院研究生学位论文]

- 英文名称：[HUST SCHOOL of COMPUTER of SCIENCE and TECHNOLOGY]

- 参考文献格式要求的**官网**链接[<http://www.cs.hust.edu.cn/info/1399/2101.htm>]

Zotero ID: sheli00

**其他样式信息**

**Comment by zepinglee** [comment]
这个跟 [418huazhong-university-of-science-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology.csl) 不一样吗？
