### ISSUE TITLE
请添加北京理工大学的样式

### ISSUE THREAD

**Issue by jiahui90** [redleafnew/Chinese-STD-GB-T-7714-related-csl#182]
**样式信息**

- 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式要求的**官网**链接[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
所需要的样式名称到底是什么？北京理工大学？心理学报？清华大学研究生学位论文？
模板中信息都要正确填写。

**Comment by huyuanbo** [comment]
> 所需要的样式名称到底是什么？北京理工大学？心理学报？清华大学研究生学位论文？ 模板中信息都要正确填写。
红老师，你可以看一下第7个问题吗？帮忙处理一下（格乐大学）
