### ISSUE TITLE
法学引注手册引用国家标准之时出错

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#183]
**描述错误**

CSL 样式：301manual-of-legal-citation-multi-lingual.csl
法学引注手册引用国家标准之时出错：第一，没有冒号；第二，最后应为标准号，而非日期（翻译器没有抓取标准号，但是我试过无论填在哪个框最后都无法显示出标准号）。

**屏幕截图**
法学引注手册格式：![CleanShot 2023-07-07 at 20 54 13@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/e5ddf9ca-4f0f-409d-9d52-4b7eaff3e263)
Zotero输出格式：全国信息与文献标准化技术委员会：《信息与文献  参考文献著录规则》，2015年版。

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/11021824/items/MKSH2AUA",
		"type": "standard",
		"language": "zh",
		"note": "Report Number: GB/T 7714—2015",
		"source": "全国标准信息公共服务平台",
		"title": "信息与文献  参考文献著录规则",
		"title-short": "信息与文献  参考文献著录规则",
		"URL": "https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A",
		"author": [
			{
				"literal": "全国信息与文献标准化技术委员会"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					7,
					7
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2015",
					5,
					15
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
确实没实现“标准”类型。不过我这几天略忙，稍等几天处理。在 2023年7月7日，21:06，yzy ***@***.***> 写道：﻿
描述错误
CSL 样式：301manual-of-legal-citation-multi-lingual.csl
法学引注手册引用国家标准之时出错：第一，没有冒号；第二，最后应为标准号，而非日期（翻译器没有抓取标准号，但是我试过无论填在哪个框最后都无法显示出标准号）。
屏幕截图

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/a94d2766-ebf6-4ae1-9de8-75cb67cc98e5
全国信息与文献标准化技术委员会：《信息与文献  参考文献著录规则》，2015年版。
条目信息

[
{
"id": "http://zotero.org/users/11021824/items/MKSH2AUA",
"type": "standard",
"language": "zh",
"note": "Report Number: GB/T 7714—2015",
"source": "全国标准信息公共服务平台",
"title": "信息与文献  参考文献著录规则",
"title-short": "信息与文献  参考文献著录规则",
"URL": "https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D8055ED3A7E05397BE0A0AB82A",
"author": [
{
"literal": "全国信息与文献标准化技术委员会"
}
],
"accessed": {
"date-parts": [
[
"2023",
7,
7
]
]
},
"issued": {
"date-parts": [
[
"2015",
5,
15
]
]
}
}
]
其他相关信息
在此处添加有关该问题的其他信息。

**Comment by yzy1228682367** [comment]
好的 感谢❤️

**Comment by yzy1228682367** [comment]
补充：茉莉花抓取条目的标准号在其他。
![CleanShot 2023-07-09 at 11 05 14@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/eec775de-3d13-41c6-b1f4-ee0a5a096276)

**Comment by zepinglee** [comment]
在 b5ddaf1 中解决。

translator 的问题我再看一下。

**Comment by zepinglee** [comment]
translator 的问题已经在 https://github.com/l0o0/translators_CN/pull/186 处理，等待 merge。

你可以先使用 <https://github.com/rnicrosoft-studio/translators_CN> 的版本。
