### ISSUE TITLE
409西北农林科技大学毕业论文格式

### ISSUE THREAD

**Issue by 777Wyatt** [redleafnew/Chinese-STD-GB-T-7714-related-csl#184]
**描述错误**

CSL 样式：409northwest-a-and-f-university.csl
错误示例
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/139113816/31fa5eda-83c1-438d-a567-0de768c2d895)

所有期刊人名不需要缩略，中文和英文作者名全部引用；
英文期刊的题目应该斜体表示；
中文期刊的逗号和引号应该用全角；
学位论文的学校前需要显示省份地区，这个功能应该比较难实现吧T-T

**屏幕截图**
正确格式参见图片
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/139113816/7f44e1ff-2c9c-4598-b189-6b2f62103f85)

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by redleafnew** [comment]
提供Zotero ID，赋予权限后，将示例文献填写入群组的“西北农林科技大学”文件夹。

**Comment by redleafnew** [comment]
群组中没有搜索到这个ID，邀请你了。

**Comment by 777Wyatt** [comment]
没有权限编辑

**Comment by redleafnew** [comment]
提升权限了

**Comment by 777Wyatt** [comment]
已添加，示例样式见https://ch.nwafu.edu.cn/mpa/zlzxmpa/325900.htm和https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fyjshy.nwsuaf.edu.cn%2Fdocs%2F%2F2022-04%2F962430faf48c42eba7130ab61f19e770.docx&wdOrigin=BROWSELINK

**Comment by zepinglee** [comment]
根据 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/41#issuecomment-1105212246> 和 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/41#issuecomment-1107443772> 的记录，[409northwest-a-and-f-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/6ed807f34063ba10ecb52cee959df39bd19bc6c6/409northwest-a-and-f-university.csl) 是按照你们 2009 年版的格式要求制作的。在给出的两个链接中，<https://ch.nwafu.edu.cn/mpa/zlzxmpa/325900.htm> 是 2009 年版，但 <https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fyjshy.nwsuaf.edu.cn%2Fdocs%2F%2F2022-04%2F962430faf48c42eba7130ab61f19e770.docx&wdOrigin=BROWSELINK> 是 2021 年版。

建议 @777Wyatt 再确认一下要求使用哪个版本的格式。是 <https://yjshy.nwafu.edu.cn/xwgl/xwsy/xwlwxzgf/e1432691f154489e91273f888c8b38e5.htm> 的吗？

**Comment by 777Wyatt** [comment]
是的，按照2021年最新版参考文献格式

**Comment by zepinglee** [comment]
在 e548ffb 中更新为 2021 版。

> 所有期刊人名不需要缩略，中文和英文作者名全部引用； 

已修改。

> 英文期刊的题目应该斜体表示； 

已修改。

> 中文期刊的逗号和引号应该用全角； 

从官方的示例来看，中文文献的逗号、括号、冒号是全角，但是句点又是半角。建议再确认一下。可以考虑将中文文献的全部符号改为全角，包括全角句点“．”（U+FF0E）。

> 学位论文的学校前需要显示省份地区，这个功能应该比较难实现吧T-T

需要作者在“Place”字段填写地址信息。

@777Wyatt 看看有没有其他格式问题？<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/e548ffbee914e1727ee06586f9833838260698f0/tests/styles/409northwest-a-and-f-university/README.md>

**Comment by 777Wyatt** [comment]
参考文献中作者人名需要全部罗列，不用“等”或者“et al”，其余问题不大。&nbsp;


Choice
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping ***@***.***&gt;; 
发送时间: 2023年7月19日(星期三) 上午8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 409西北农林科技大学毕业论文格式 (Issue #184)





 
在 e548ffb 中更新为 2021 版。
  
所有期刊人名不需要缩略，中文和英文作者名全部引用；
  
已修改。
  
英文期刊的题目应该斜体表示；
  
已修改。
  
中文期刊的逗号和引号应该用全角；
  
从官方的示例来看，中文文献的逗号、括号、冒号是全角，但是句点又是半角。建议再确认一下。可以考虑将中文文献的全部符号改为全角，包括全角句点“．”（U+FF0E）。
  
学位论文的学校前需要显示省份地区，这个功能应该比较难实现吧T-T
  
需要作者在“Place”字段填写地址信息。
 
@777Wyatt 看看有没有其他格式问题？https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/e548ffbee914e1727ee06586f9833838260698f0/tests/styles/409northwest-a-and-f-university/README.md

**Comment by zepinglee** [comment]
> 参考文献中作者人名需要全部罗列，不用“等”或者“et al”，其余问题不大。

@777Wyatt 确实。在 ab1d88b 中修复。

**Comment by 777Wyatt** [comment]
出现了新问题，英文期刊的名称不能缩写，应该全拼出来；引用学位论文时，应显示的是[硕士学位论文]or[博士学位论文]。
作者大大辛苦了！
&nbsp;


Choice
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping ***@***.***&gt;; 
发送时间: 2023年7月27日(星期四) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 409西北农林科技大学毕业论文格式 (Issue #184)





  
参考文献中作者人名需要全部罗列，不用“等”或者“et al”，其余问题不大。
  
@777Wyatt 确实。在 ab1d88b 中修复。

**Comment by zepinglee** [comment]
> 出现了新问题，英文期刊的名称不能缩写，应该全拼出来；

<img width="866" alt="Screenshot 2023-07-29 at 11 36 11" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/3ca4af7d-804e-49ee-ac7c-3579e567b85a">

而且两个示例中用的是缩写。

<img width="878" alt="Screenshot 2023-07-29 at 11 36 53" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/8bce2b08-e98e-4441-a67e-e3b5582d670f">

> 引用学位论文时，应显示的是[硕士学位论文]or[博士学位论文]。

目前的就是“[博士学位论文]”。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/e548ffbee914e1727ee06586f9833838260698f0/tests/styles/409northwest-a-and-f-university/README.md?plain=1#L36

另外参考 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/173#issuecomment-1571789633>。
