### ISSUE TITLE
506export-author-et-al-year 建议et al 出现的作者人数至少为3人

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#185]
根据APA 至少3人以上才会用et al
无论是中文还是英文，一个人用et al会导致条目不易被精准定位
建议云端也改写，这样每次同步时不需要再本地改
谢谢呀

**Comment by redleafnew** [comment]
这个是专门用的，印象中是用于导出在PPT中展示的。

**Comment by fredericky123** [comment]
我想利用zutilo快速复制导出用于笔记用的，需要知道导出的是哪个
只保留citation格式就行，您除了修改参考文献格式，还有什么建议吗

**Comment by redleafnew** [comment]
根据自己需要修改就可以了。

**Comment by fredericky123** [comment]
就是得重命名 重新设置 不然下次您这边更新 就覆盖了

**Comment by redleafnew** [comment]
修改文件名和ID就可以了。

**Comment by fredericky123** [comment]
好嘞
