### ISSUE TITLE
请求添加上海大学学位论文格式

### ISSUE THREAD

**Issue by zh3yu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#188]
- 期刊/学校名称：上海大学

- 英文名称：Shanghai University

- 参考文献格式要求的**官网**链接 https://gs.shu.edu.cn/pygl.htm[https://gs.shu.edu.cn/pygl.htm]

我自己修改了一下格式， 已经通过答辩。
具体参考：https://github.com/zh3yu/CSL-Format-for-Dissertations-SHU

**Comment by zepinglee** [comment]
感谢分享！
