### ISSUE TITLE
请求添加《新金融》样式

### ISSUE THREAD

**Issue by artemith** [redleafnew/Chinese-STD-GB-T-7714-related-csl#189]
**样式信息**

- 期刊/学校名称：新金融

- 英文名称：New Finance

- 参考文献格式要求的**官网**链接 [链接](https://xjro.cbpt.cnki.net/WKC/WebPublication/wkDownFileByLink.aspx?fid=02d8c331-5fb6-4c50-a202-86652abb0931&mid=xjro&cid=eaf499e4-5e56-4b65-bf00-a5305c9c5eaf)

- （期刊的）ISSN 号：1006-1770

- （期刊的）相关领域：social_science

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: hy_0943

**其他样式信息**

**格式要求**

**citation**
数字化转型使行业和社会发生深刻的变化，促进组织实施创新与变革活动（严子淳等，2021；周雷等，2021）。既有研究发现数字化转型有利于提升企业财务绩效（白福萍等，2022）、提升股票流动性、促进企业绿色创新、提高企业全要素生产率、再造企业的全产业链流程。刘淑春等（2021）认为数字化转型改变了企业内部的管理流程，使得不同部门、环节和板块之间的数据联合，降低了信息搜集成本和交易成本，提高了资源配置和供应链管理能力。
……
正文中引用文献时，超过一位作者时仅列示第一位作者，中文采用“等”表示省略，英文用“et al.”表示省略，“等”与“et al.”之前应留一空格；各篇文献的标注内容由第一作者姓氏或团体作者与出版年份构成，并置于小括号内。

**bibliography**
参考文献
作者，2015．著作名．上海：上海人民出版社：50-51．
作者1，作者2，作者3，等，2018．文章标题．期刊名称（11）：35-50．
作者，2021．论文标题．城市：授予单位．
NUNN N, QIAN N, et al. 2014. US food aid and civil conflict. The American Economic Review, 104(6): 1630-1666.
……
请务必保证所列示的参考文献在文中被引用过；同时，文中被引用过的文献也应列示在参考文献中；转引文献无须列入。
参考文献采用“作者-出版年制”著录格式，按照中文在前（按姓氏拼音排序）、英文在后（按姓氏全拼排序）的原则。其中，专著要注明出版社所在城市，期刊文章要注明所在期次及起止页码，**学位论文要注明所在城市及学位授予单位**。文章标题中的破折号，在参考文献中要改为冒号。
根据“著者-出版年制”，参考文献按照拼音排序，不要序号，“年份”提到作者名字后面、论文题目前面。
英文参考文献，也按照上述原则，作者姓名必须是“姓在前，名在后”；**“姓”字母全部大写不缩写，“名”只以大写首字母缩写（且不用加“.”）；英文文章标题和期刊名的首字母大写（专有名词按有关规则书写）。

**期刊论文示例**
[金融科技发展与商业银行数字化转型：影响与建议_蔡普华.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12122207/_.pdf)

**修改**

该样式只需要在[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)的基础上进行不多的修改即可。citation没有问题，需要修改的只有bibliography部分。具体修改如下
1. [J]、[D]等标识需要去掉
2. 学位论文的格式需要加入“城市：”
3. 中文文献的bib除了"."，其他的都是全角符号，英文文献是半角（英文文献不需要改动）
4. bibliography需要序号"[1]"、"[2]"...etc

**Comment by zepinglee** [comment]
> 该样式只需要在[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)的基础上进行不多的修改即可。citation没有问题，需要修改的只有bibliography部分。具体修改如下
> 
> 1\. [J]、[D]等标识需要去掉
> 4. bibliography需要序号"[1]"、"[2]"...etc

这两条不难实现。

> 2. 学位论文的格式需要加入“城市：”

需要在 Zotero 文献的“Place”字段录入城市。

> 3. 中文文献的bib除了"."，其他的都是全角符号，英文文献是半角（英文文献不需要改动）

其实可以用全角句点“．”（U+FF0E）。半角句点的宽度比全角逗号还小，就很不合理。

<img width="422" alt="Screenshot 2023-07-22 at 12 10 48" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/df7a5cd5-e74b-4a82-a452-e385dbc8e418">

另外页码的连接号用什么符号？示例文章的中英文文献都用是的一字线（em dash），但是 en dash 更符合西文的习惯。建议询问一下他们期刊的编辑。

**Comment by artemith** [comment]
> 另外页码的连接号用什么符号？示例文章的中英文文献都用是的一字线（em dash），但是 en dash 更符合西文的习惯。建议询问一下他们期刊的编辑。

这里之前没有说，是因为他们杂志社给的《论文模板》和期刊论文实例不一致。论文模板中中英文bib都是en dash，示例文章中都是em dash

**Comment by artemith** [comment]
> > 另外页码的连接号用什么符号？示例文章的中英文文献都用是的一字线（em dash），但是 en dash 更符合西文的习惯。建议询问一下他们期刊的编辑。
> 
> 这里之前没有说，是因为他们杂志社给的《论文模板》和期刊论文实例不一致。论文模板中中英文bib都是en dash，示例文章中都是em dash

刚才又下载了两篇示例文章，中英文bib都是em dash

**示例文章**
[数字金融能促进创新创业吗？...—来自280个地级市的证据_杜念宇.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12135986/280._.pdf)
[企业ESG表现对债务期限结...中国A股上市公司的经验证据_王丽娟.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12135987/ESG.A._.pdf)

**Comment by artemith** [comment]
> > 另外页码的连接号用什么符号？示例文章的中英文文献都用是的一字线（em dash），但是 en dash 更符合西文的习惯。建议询问一下他们期刊的编辑。
> 
> 这里之前没有说，是因为他们杂志社给的《论文模板》和期刊论文实例不一致。论文模板中中英文bib都是en dash，示例文章中都是em dash

还有一点《论文模板》和示例文章中矛盾的地方

**论文模板中规定**

> “等”与“et al.”之前应留一空格

**示例论文中**

> 中文“等”字前没有空格

我个人觉得，按照示例文章来较好

**Comment by zepinglee** [comment]
在 3ce8c9e 中添加样式，测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/221new-finance/test.md>。@artemith 你再看看有没有别的问题。

> 这里之前没有说，是因为他们杂志社给的《论文模板》和期刊论文实例不一致。论文模板中中英文bib都是en dash，示例文章中都是em dash

《论文模板》中的其实是 hyphen 不是 en dash。我暂且统一为 hyphen。如果编辑有回复我再修改。

**Comment by zepinglee** [comment]
> > > 另外页码的连接号用什么符号？示例文章的中英文文献都用是的一字线（em dash），但是 en dash 更符合西文的习惯。建议询问一下他们期刊的编辑。
> > 
> > 
> > 这里之前没有说，是因为他们杂志社给的《论文模板》和期刊论文实例不一致。论文模板中中英文bib都是en dash，示例文章中都是em dash
> 
> 还有一点《论文模板》和示例文章中矛盾的地方
> 
> **论文模板中规定**
> 
> > “等”与“et al.”之前应留一空格
> 
> **示例论文中**
> 
> > 中文“等”字前没有空格
> 
> 我个人觉得，按照示例文章来较好

我目前按照《论文模板》的要求处理，加空格。

**Comment by artemith** [comment]
> 

OK，感谢您！
