### ISSUE TITLE
整理文件名以及标题信息

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#19]
提议整理一下 `china-national-standard-gb-t-7714-2015-*.csl` 和 `gb-t-7714-2015-*.csl`，这个工作交给我吧。@redleafnew 对以下修改的意见怎样？

1. 去掉文件名的 `china-national-standard-` 前缀。这部分信息在官方的仓库中有用，但是在本仓库中显得多余。
2. 目前的文件名中记录修改信息的主要有 `aulower`, `bilan`, `nodoi`，不过这几个词不太容易理解（比如我第一次看到时想了半天 `bilan` 是拼音还是啥东西），建议改成`lower-name`, `bilingual`。`nodoi` 的设置其实是同时去掉了 URL 和 DOI，建议改为完整一点的信息，比如 `no-url-doi`, `nourldoi` 或者 `nolink`。
3. 在 `<title>` 标签中使用中文填写简要的修改信息，每条修改都有一词。这部分内容会显示在 Zotero 选择 style 的界面，可以方面用户查找。
<img width="693" alt="Screen Shot 2021-12-13 at 19 43 17" src="https://user-images.githubusercontent.com/12290822/145810501-dc6cae43-aa34-41a3-b033-c82161e10756.png">

4. 在 `<summary>` 标签中使用中文记录详细的修改信息，这主要是修改代码时阅读和记录。
5. 同时修改 README 中的文件名和链接。

**Comment by redleafnew** [comment]
可以，可以，谢谢。

我家里的git不知道出了什么问题，pull，push不同time out，就是什么reset，
试了网上各种办法，就是不行。

修改过hosts, 

设置代理：

git config --global --get http.proxy
git config --global --get https.proxy

取消代理：

git config --global --unset http.proxy
git config --global --unset https.proxy

科学上网...

都不行
。。。。

**Comment by zepinglee** [comment]
我用的是 `all_proxy=http://localhost:1087 git push`，因为有时需要科学上网有时有不需要，所以就没配置 `config --global`。

**Comment by redleafnew** [comment]
> 我用的是 `all_proxy=http://localhost:1087 git push`，因为有时需要科学上网有时又不需要，所以就没配置 `config --global`。

放入到.config中吗？

**Comment by zepinglee** [comment]
> 放入到.config中吗？

不是，直接在命令行中这样使用。

**Comment by redleafnew** [comment]
直接运行：
all_proxy=http://localhost:1087 git push
报错，
'all_proxy' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
我对git命令不了解。

**Comment by zepinglee** [comment]
> 直接运行： all_proxy=http://localhost:1087 git push 报错， 'all_proxy' 不是内部或外部命令，也不是可运行的程序 或批处理文件。 我对git命令不了解。

噢，我用的是 Unix 系统命令行，Windows 的不太一样。

**Comment by redleafnew** [comment]
这个是已经整理完毕了吗？

**Comment by zepinglee** [comment]
还没

**Comment by zepinglee** [comment]
上次只改了 README，CSL  文件改了一半还没 push。

**Comment by redleafnew** [comment]
ok，辛苦了。我的git还是不正常。

**Comment by redleafnew** [comment]
可以合并了吗？

**Comment by zepinglee** [comment]
嗯嗯可以合并了。
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/22#issuecomment-997846229
