### ISSUE TITLE
跪求添加泰国格乐大学文献格式

### ISSUE THREAD

**Issue by huyuanbo** [redleafnew/Chinese-STD-GB-T-7714-related-csl#190]
**样式信息**

- 期刊/学校名称：[泰国格乐大学博士学位论文]

- 英文名称：[例如 krirk University]

- 参考文献格式要求的**官网**链接[例如 [<无链接，只有附件>]
[(2) 格乐大学国际学院格式.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12179392/2.docx)

- （期刊的）ISSN 号：[例如 0439-755X]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by huyuanbo** [comment]
泰国格乐大学文献格式是基于APA格式的

**Comment by redleafnew** [comment]
直接用APA不行吗?与APA有什么区别？
提供Zotero ID，赋予权限后将测试条目上传到Zotero群组。

**Comment by huyuanbo** [comment]
> 直接用APA不行吗?与APA有什么区别？ 提供Zotero ID，赋予权限后将测试条目上传到Zotero群组。
我加入群组了，这是我的账号：https://www.zotero.org/hyb1988

**Comment by huyuanbo** [comment]
> 直接用APA不行吗?与APA有什么区别？ 提供Zotero ID，赋予权限后将测试条目上传到Zotero群组。

账号是Hyb1988

**Comment by redleafnew** [comment]
加入群组了吗？

**Comment by redleafnew** [comment]
已经赋予权限，请上传测试条目。
指出需要的样式与apa的区别，详细列出，现在是什么样子，需要改成什么。

**Comment by huyuanbo** [comment]
> 已经赋予权限，请上传测试条目。 指出需要的样式与apa的区别，详细列出，现在是什么样子，需要改成什么。

上传了

**Comment by redleafnew** [comment]
指出需要的样式与apa的区别，详细列出，现在是什么样子，需要改成什么。

**Comment by redleafnew** [comment]
在学位论文文件夹中新建学校名称的文件夹，将测试文件放到里面。

**Comment by huyuanbo** [comment]
> 指出需要的样式与apa的区别，详细列出，现在是什么样子，需要改成什么。

1.APA里面没有引用中文的格式，泰国格乐大学规定了引用中文的格式：
其中，文献引用格式为：
中文文献（1人）：姓名（出版或发表年代）或（姓名，出版或发表年代）。例如：
前引用：游燕（2016）认为不同的责任归因会使应对方式的主动性产生差异。
后引用：责任归因的不同会影响应对方式的主动性（游燕，2016）。
中文文献（2人）：作者为两人时，两人的姓名全列，并用“和”连接。
例如：
前引用：赵红丹和周君（2017）认为员工为了获得工作资源以及晋升机会等有利于个人的利益就会做出这种行为。
后引用：员工通过这种行为获得工作资源以及晋升机会等有利于个人的利益（赵红丹和周君，2017）。
中文文献（3人以上）：作者为三人及以上时，不论第几次出现，都仅写出第一位作者并加“等”
例如；
前引用：邵小珍等（2007）强调情绪的稳定性对工作中的感知和行为的影响。
后引用：情绪的稳定性会影响工作中的感知和行为(邵小珍等，2007)。
其中参考文献格式为：
中文期刊：作者姓名（年份）。文章名称。期刊名称，卷号（期别），页码。DOI
罗瑾琏、易明、钟竞（2018）。双元领导对亲社会性沉默的影响。管理科学，31（2），105-119。https://doi.org/10.1037/rev0000126
2.英文的文献引用时，引用外国学者时，只需书写姓氏，切勿写英文全名！
英文文献（1人）：姓氏（出版或发表年代）或（姓氏，出版或发表年代）。例如：
前引用：Porter (2001) described the method…
后引用：The study also showed that... (Porter, 2001).
引用外国学者时，只需书写姓氏，切勿写英文全名！
英文文献（2人）：作者为两人时，两人的姓氏全列，并且，前引用通过“and”连接；后引用通过“&”连接。例如：
前引用：Wassertein and Rosen (1994) described the method.…
后引用：The study also showed that... (Wassertein & Rosen, 1994).
引用外国学者时，只需书写姓氏，切勿写英文全名！
英文文献（3人）：
作者：Wasserstein, Zappula, Rosen and Rock (1994)
前引用：Wasserstein et al. (1994) described the method.…
后引用：The study also showed that... (Wasserstein et al., 1994)…
3.在参考文献中，要先中后英，不论作者数量为多少，都需全部列出。文献目录：字体，中文为宋体，英文及数字为Times New Roman，字号为12，单倍行距，悬挂缩进2字符。首字母排序，中文文献在前，英文文献在后（基本原则：中文部分为全角，英文部分为半角）。
Powers, J. M., & Cookson, P. W. Jr. (1999). The politics of school choice research. Educational Policy, 13(1), 104-122. https://doi.org/10.1037/rev0000126

**Comment by huyuanbo** [comment]
> 在学位论文文件夹中新建学校名称的文件夹，将测试文件放到里面。

这个怎么弄，不是很会哦，可以帮忙一下吗？
[(2) 格乐大学国际学院格式.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12206283/2.docx)

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22135631/a67b3ecf-4dae-4561-987c-6dad513f0961)
Zotero中右击，新建文件夹，把你你上面提到的文献，放进去。

**Comment by huyuanbo** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/256965126-a67b3ecf-4dae-4561-987c-6dad513f0961.png) Zotero中右击，新建文件夹，把你你上面提到的文献，放进去。

我找不到入口，这个图片的网址有吗？

**Comment by redleafnew** [comment]
在Zotero中，加入群组后，Zotero左下角会有Group

**Comment by huyuanbo** [comment]
> 1.APA里面没有引用中文的格式，泰国格乐大学规定了引用中文的格式：
> 其中，文献引用格式为：
> 中文文献（1人）：姓名（出版或发表年代）或（姓名，出版或发表年代）。例如：
> 前引用：游燕（2016）认为不同的责任归因会使应对方式的主动性产生差异。
> 后引用：责任归因的不同会影响应对方式的主动性（游燕，2016）。
> 中文文献（2人）：作者为两人时，两人的姓名全列，并用“和”连接。
> 例如：
> 前引用：赵红丹和周君（2017）认为员工为了获得工作资源以及晋升机会等有利于个人的利益就会做出这种行为。
> 后引用：员工通过这种行为获得工作资源以及晋升机会等有利于个人的利益（赵红丹和周君，2017）。
> 中文文献（3人以上）：作者为三人及以上时，不论第几次出现，都仅写出第一位作者并加“等”
> 例如；
> 前引用：邵小珍等（2007）强调情绪的稳定性对工作中的感知和行为的影响。
> 后引用：情绪的稳定性会影响工作中的感知和行为(邵小珍等，2007)。
> 其中参考文献格式为：
> 中文期刊：作者姓名（年份）。文章名称。期刊名称，卷号（期别），页码。DOI
> 罗瑾琏、易明、钟竞（2018）。双元领导对亲社会性沉默的影响。管理科学，31（2），105-119。https://doi.org/10.1037/rev0000126
> 2.英文的文献引用时，引用外国学者时，只需书写姓氏，切勿写英文全名！
> 英文文献（1人）：姓氏（出版或发表年代）或（姓氏，出版或发表年代）。例如：
> 前引用：Porter (2001) described the method…
> 后引用：The study also showed that... (Porter, 2001).
> 引用外国学者时，只需书写姓氏，切勿写英文全名！
> 英文文献（2人）：作者为两人时，两人的姓氏全列，并且，前引用通过“and”连接；后引用通过“&”连接。例如：
> 前引用：Wassertein and Rosen (1994) described the method.…
> 后引用：The study also showed that... (Wassertein & Rosen, 1994).
> 引用外国学者时，只需书写姓氏，切勿写英文全名！
> 英文文献（3人）：
> 作者：Wasserstein, Zappula, Rosen and Rock (1994)
> 前引用：Wasserstein et al. (1994) described the method.…
> 后引用：The study also showed that... (Wasserstein et al., 1994)…
> 3.在参考文献中，要先中后英，不论作者数量为多少，都需全部列出。文献目录：字体，中文为宋体，英文及数字为Times New Roman，字号为12，单倍行距，悬挂缩进2字符。首字母排序，中文文献在前，英文文献在后（基本原则：中文部分为全角，英文部分为半角）。
> Powers, J. M., & Cookson, P. W. Jr. (1999). The politics of school choice research. Educational Policy, 13(1), 104-122. https://doi.org/10.1037/rev0000126

**Comment by huyuanbo** [comment]
> 在Zotero中，加入群组后，Zotero左下角会有Group

好了

**Comment by redleafnew** [comment]
格式不对，参考其它学校的条目录入方式。

**Comment by huyuanbo** [comment]
我是在泰国读的博士，能不能按照学校文件要求给我做一个csl，上面都有说明了，弄那个太麻烦了，我可以给报酬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月29日(星期六) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 跪求添加泰国格乐大学文献格式 (Issue #190)





 
格式不对，参考其它学校的条目录入方式。

**Comment by redleafnew** [comment]
那可以到Zotero官方论坛去求助

**Comment by huyuanbo** [comment]
大神，麻烦和我说一下怎么求助吗？步骤详细说一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月29日(周六) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 跪求添加泰国格乐大学文献格式 (Issue #190)




 
那可以到Zotero官方论坛去求助

**Comment by redleafnew** [comment]
论坛上经常有，找一下吧。

**Comment by redleafnew** [comment]
https://[forums.zotero.org](https://forums.zotero.org/)/

**Comment by huyuanbo** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月29日(周六) 中午1:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 跪求添加泰国格乐大学文献格式 (Issue #190)




 
https://forums.zotero.org/
