### ISSUE TITLE
您好，法学引注手册中的网页以及播客帖子格式错误了。

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#192]
**描述错误**

CSL 样式：306manual-of-legal-citation-multi-lingual-no-ibid.csl
法学引注手册，网页以及播客帖子格式错误。第一：作者之后应为“：”而非“，”；第二，标题应加“《》”；第三，来源（网站标题或者播客标题）之前应有“载”；第四，日期中的年月日应为中文；第五，最后应以“。”结尾。

**屏幕截图**
数博会, 贵阳大数据交易所正式发布全国首个交易激励计划, 微信公众号“数博会” (7 April 2023), http://mp.weixin.qq.com/s?__biz=MzAwMzE4MDY3NQ==&mid=2675898652&idx=6&sn=85741409daa3d4d810b06ea979973c5e&chksm=81b548f0b6c2c1e6a2dc89ce29a2fc588cf3b7848e9fb52f04c4d3d384f4a12327695e57b45a#rd.
![CleanShot 2023-08-04 at 00 23 51@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/438525cc-9448-4a63-b8c0-50e37097ab5c)

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/11021824/items/R7JAZYXX",
		"type": "webpage",
		"abstract": "数实相融 · 算启未来",
		"container-title": "微信公众号“数博会”",
		"title": "贵阳大数据交易所正式发布全国首个交易激励计划",
		"title-short": "贵阳大数据交易所正式发布全国首个交易激励计划",
		"URL": "http://mp.weixin.qq.com/s?__biz=MzAwMzE4MDY3NQ==&mid=2675898652&idx=6&sn=85741409daa3d4d810b06ea979973c5e&chksm=81b548f0b6c2c1e6a2dc89ce29a2fc588cf3b7848e9fb52f04c4d3d384f4a12327695e57b45a#rd",
		"author": [
			{
				"literal": "数博会"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					8,
					4
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2023",
					4,
					7
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
1. 样式默认语言为英文，中文文献需要在 `language` 填入 `zh-CN`；
2. “个人博客、微信公众号”应使用文献类型 `post-weblog`（对应 Zotero 类型“Blog Post”）。

修改后测试文献

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/b6225b09fc9546a89e4edf80215d734ffcab9669/tests/styles/306manual-of-legal-citation-multi-lingual-no-ibid/test-data.json#L1932-L1964

效果见

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/b6225b09fc9546a89e4edf80215d734ffcab9669/tests/styles/306manual-of-legal-citation-multi-lingual-no-ibid/test.md?plain=1#L186

**Comment by yzy1228682367** [comment]
好的，感谢❤️

**Comment by yzy1228682367** [comment]
您好，请问有什么办法在language一行中，默认填写zh-CN吗？

**Comment by zepinglee** [comment]
> 您好，请问有什么办法在language一行中，默认填写zh-CN吗？

<https://github.com/l0o0/jasminum> 和 <https://github.com/redleafnew/delitemwithatt> 应该都可以。

**Comment by yzy1228682367** [comment]
感谢感谢~
