### ISSUE TITLE
求添加一个书稿的csl

### ISSUE THREAD

**Issue by bi-wei** [redleafnew/Chinese-STD-GB-T-7714-related-csl#193]
**样式信息**

- 期刊/学校名称：[例如 人民出版社]

- 英文名称：[例如 Renmin Press]

- 参考文献格式要求的**官网**链接[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

- （期刊的）ISSN 号：[例如 /]

- （期刊的）相关领域：[例如 psychology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**
[书稿csl求助.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12258736/csl.docx)
[书稿测试-导出的条目.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12258739/-.zip)

**Comment by zepinglee** [comment]
@bi-wei 格式要求有没有官网链接？

**Comment by zepinglee** [comment]
在 3420a5f 中添加样式，测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/324peoples-publishing-house/test.md>。

另外有一点不确定的是，格式要求“参考文献列的资料不需要精确到具体页码”。但是比如期刊论文在 339–374 页，是否要在参考文献表列出？按照《法学引注手册》的解释是，“具体页码”指的是引文出处的页码，比如该论文第 340 页。

**Comment by bi-wei** [comment]
您好，测试页非常完美！
  关于具体页码的问题，我仔细理解了格式要求，似乎编辑区分了“脚注”和“参考文献”，是两种不同的东西。
  示例里对于脚注需要页码，比如期刊论文在 “339–374 页”是需要添加的，正如所指出的：“中文页码之间连字符用一字线；英文页码之间连字符用半字线，页码如果是单个用“p.”（如p.5），如果是页码之间用“pp.”（如pp.18-25）表示”。而如果作为文末的“参考文献”，则不需要任何页码。
  我打算所有引用都以脚注格式添加，不作为参考文献，所以仍然需要页码。我使用csl的时候可以不在文末再次添加一遍不包含页码此外完全相同的“参考文献”吗？（或者自动生成后，我手动删掉重复的“参考文献”。）
  谢谢！

**Comment by zepinglee** [comment]
> 我打算所有引用都以脚注格式添加，不作为参考文献，所以仍然需要页码。

那就不需要修改了。

> 我使用csl的时候可以不在文末再次添加一遍不包含页码此外完全相同的“参考文献”吗？（或者自动生成后，我手动删掉重复的“参考文献”。） 谢谢！

使用 Word 插件的话估计不行。

**Comment by bi-wei** [comment]
您好，那我关闭issue了
