### ISSUE TITLE
“法学引注手册”的图书引注格式不会对“卷次”作出反应。

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#195]
**描述错误**

CSL 样式：Chinese-STD-GB-T-7714-related-csl
您好，“法学引注手册”的图书引注格式不会对“卷次”作出反应。按照《法学引注手册》，下列条目信息应为：张五常：《经济解释》（增订版第1卷）， 中信出版社2019年版。

**屏幕截图**
![CleanShot 2023-08-14 at 20 39 40@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/63118b81-10e7-47e1-9841-64ad3ec7e48b)
![CleanShot 2023-08-14 at 20 39 15@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/a1669dbd-d908-4c46-94a5-f458736dbe61)

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/11021824/items/QNC2ZINU",
		"type": "book",
		"abstract": "《经济解释》是经济学家张五常的经典著作，被世人公认为是集张五常平生学术功力之大成，也是具有深远影响的经济学经典作品。\n\n这次推出的《经济解释五卷本：二O一九增订版》,包括《科学说需求》《收入与成本》《受价与觅价》《制度的选择》《国家的经济理论》，共五卷。\n\n张五常对之前四卷本再次进行增补，对卷一、卷二、卷三都有修订，对原来的卷四进行了拆分大修，形成现在的卷四和卷五。这一版《经济解释》是完整修订版，也算是其封笔之作。",
		"edition": "增订版",
		"ISBN": "978-7-5086-9825-0",
		"language": "zh",
		"number-of-pages": "1500",
		"publisher": "中信出版社",
		"source": "Jd",
		"title": "经济解释",
		"title-short": "【自营包邮】经济解释2019 五卷本增订版 张五常 科学说需求 收入与成本 受价与觅价 制度的选择",
		"URL": "https://item.jd.com/12700420.html",
		"volume": "第1卷",
		"author": [
			{
				"literal": "张五常"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					8,
					14
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2019",
					10,
					1
				]
			]
		}
	}
]
```

**其他相关信息**

**Comment by zepinglee** [comment]
在 50ff569 中修复。

最开始写 CSL 样式的时候，《法学引注手册》第 24～57 节录入用于测试的文献较少，所以没覆盖到这个问题。如果愿意的话可以放榜将其中的文献录入群组。

<img width="897" alt="Screenshot 2023-08-14 at 23 15 46" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/ca9a89ff-c6e3-4040-be1b-735cdff1106e">

另外，像“第1卷”这样的形式可以只填“1”；`title-short` 字段用于略写标题，不应填入“【自营包邮】经济解释2019”这样的无关信息。

<img width="708" alt="Screenshot 2023-08-14 at 23 20 33" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/bdae0704-23e1-4369-a7b9-c1896a4619ef">

**Comment by yzy1228682367** [comment]
万分感谢~

**Comment by zepinglee** [comment]
> 感谢❤️。好的，请问我要怎么录入呢？

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID。然后由我提升为 admin 用户组赋予编辑权限，才能添加文献。

> 🤣那个简写是抓取京东的时候自带的，多谢提醒~。

你是用的 <https://github.com/l0o0/translators_CN> 吗？最新版应该不会抓取这些信息，建议更新一下。

**Comment by zepinglee** [comment]
<img width="886" alt="Screenshot 2023-08-14 at 23 33 33" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/f20912a6-89fe-4b1e-b670-51c1f08596df">

这个应该是你吧？已经修改为 admin 权限。

**Comment by yzy1228682367** [comment]
对的，请问就是把这些样例加入进去，看有没有存在问题是吗？
![CleanShot 2023-08-14 at 23 34 49@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/0ee678ac-6143-4800-9c3f-57b41884fb68)

**Comment by zepinglee** [comment]
> 对的，请问就是把这些样例加入进去，看有没有存在问题是吗？ ![CleanShot 2023-08-14 at 23 34 49@2x](https://user-images.githubusercontent.com/50101175/260498830-0ee678ac-6143-4800-9c3f-57b41884fb68.png)

是的。

大部分应该没有问题。不过作为软件的测试，那当然多多益善。

**Comment by yzy1228682367** [comment]
> > 对的，请问就是把这些样例加入进去，看有没有存在问题是吗？ ![CleanShot 2023-08-14 at 23 34 49@2x](https://user-images.githubusercontent.com/50101175/260498830-0ee678ac-6143-4800-9c3f-57b41884fb68.png)
> 
> 是的。
> 
> 大部分应该没有问题。不过作为软件的测试，那当然多多益善。

好嘞，感谢你们维护的样式。希望可以做出一点自己的贡献~

**Comment by yzy1228682367** [comment]
好耶 谢谢❤️
