### ISSUE TITLE
自己DIV核心社科期刊《管理评论》的csl，如何上传并进一步请求各位开发者检查

### ISSUE THREAD

**Issue by xjtusjtu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#196]
各位开发者好，我手工自己DIV了管理学期刊《管理评论》的csl，想上传分享给更多的朋友。由于是第一次编辑csl文件，可能存在一些问题，需要麻烦各位检查。请问我应该如何操作？
    

**样式信息**

- 期刊/学校名称：管理评论

- 英文名称：Management Review

- 参考文献格式要求的**官网**链接 http://journal05.magtech.org.cn/jweb_glpl/CN/column/column6.shtml 下的《 稿件格式要求 [2020-07-10]》
- （期刊的）ISSN 号：1003-1952
- （期刊的）相关领域：social_science

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**Additional style information**

**Comment by redleafnew** [comment]
可以在[这个网站上](https://validator.citationstyles.org/)检验下语法合理性。
在本仓库提交Pull request.  修改readme,写上显示效果。
或是我们代为上传。

**Comment by zepinglee** [comment]
大致是：fork 仓库，提交修改（commit），然后发 pull request。

**Comment by xjtusjtu** [comment]
好的，感谢两位。今晚发现样式依然存在一些问题，我先找时间尝试自己修正，修正后再尝试上传，实在不行的话再求助各位！

**Comment by xjtusjtu** [comment]
检验语法的合理性，提示如下错误，但不知道如何修改
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/57665402/6df112f7-e726-4c1f-a5ad-c699f12818fb)

已pull request，麻烦各位检查~

如果对已经存在的问题有解决的方法，或者检查出来有其它问题，麻烦在这里告知下我，我顺便进一步学习一下，谢谢！

**Comment by redleafnew** [comment]
后面两个错误忽略即可。

**Comment by redleafnew** [comment]
除了suffix其它地方修改了吗？

**Comment by xjtusjtu** [comment]
我又重新下载了 002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl，结果发现中文文献后面的点可以通过这种方式删除，英文文献通过这种方式删除就报错，你们可以试下

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/57665402/5969ced3-1b4a-471d-a914-57c9528fd86d)

**Comment by zepinglee** [comment]
> 我又重新下载了 002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl，结果发现中文文献后面的点可以通过这种方式删除，英文文献通过这种方式删除就报错，你们可以试下
> 
> ![image](https://user-images.githubusercontent.com/57665402/261893710-5969ced3-1b4a-471d-a914-57c9528fd86d.png)

可能是这个 visual editor 对 CSL-M 扩展的处理有些问题，还是直接修改 xml 代码靠谱。

**Comment by xjtusjtu** [comment]
@zepinglee 是的，我通过vscode打开源代码直接删除，确实成功了，非常感谢！
额外的问题，直接修改源代码的方式，各位对快速入门的教程有推荐吗？是否可以借助VSCode等配置本地化的csl编辑环境（提供自动补全、效果预览等代码增强功能）？

**Comment by zepinglee** [comment]
> 是否可以借助VSCode等配置本地化的csl编辑环境（提供自动补全、效果预览等代码增强功能）？如果可以，具体如何配置？

可以使用 [XML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) 的语法高亮以及自动格式化功能，但是没有自动补全。

效果预览可以考虑 [CSL Preview](https://marketplace.visualstudio.com/items?itemName=igorjrd.cslpreview) 插件。但是我个人不怎么用这个，因为我需要关注每次修改 CSL 后输出的变化。所以我通常用本仓库的 [tests/test-style.py](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/test-style.py) 脚本（需要安装 Python 和 Node.js），可以生成 markdown/HTML 用于比对 diff，比如 [tests/styles/116management-review/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/116management-review/test.md?plain=1)。

**Comment by redleafnew** [comment]
自动补全的插件没有找到，
预览的插件：[CSL Preview](https://marketplace.visualstudio.com/items?itemName=igorjrd.cslpreview)挺好用的。

**Comment by xjtusjtu** [comment]
好的，我后续有时间再尝试，有问题再请教各位，感谢！
