### ISSUE TITLE
7714的csl中delimiter=","是否为delimiter=", "

### ISSUE THREAD

**Issue by redleafnew** [redleafnew/Chinese-STD-GB-T-7714-related-csl#198]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/853319c1ad90127d17ae4b6e507f9e7cec9094f6/000gb-t-7714-2015-numeric-bilingual.csl#L404

即`,`后面有个空格？
@zepinglee

**Comment by zepinglee** [comment]
1. 国准的示例没有空格（尽管这份标准对空格不够讲究）。

<img width="789" alt="Screenshot 2023-08-21 at 18 16 17" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/05bc52b5-8324-4bb9-b05e-57bd730d217e">

2. Nature 的上标式逗号不加空格。
<img width="434" alt="Screenshot 2023-08-21 at 18 20 43" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/8b27f37c-18fa-4a46-88d0-981fb0889feb">

所以总的来看我倾向于不加空格。

**Comment by redleafnew** [comment]
ok
