### ISSUE TITLE
引用同一作者同年出版的多篇文献时，没有自动出现a b c编号加以区别

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#2]
用的csl是这个，https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/gb-t-7714-2015-author-date-aulower-bilan-nodoi.csl

导出两个参考文献作为示例：
[
	{
		"id": "http://zotero.org/groups/2321158/items/3AC34A2N",
		"type": "article-journal",
		"container-title": "Strategic Management Journal",
		"DOI": "10.1002/smj.4250090706",
		"issue": "S1",
		"language": "en",
		"page": "41–58",
		"title": "First-mover advantages",
		"volume": "9",
		"author": [
			{
				"family": "Lieberman",
				"given": "Marvin B"
			},
			{
				"family": "Montgomery",
				"given": "David B"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1988"
				]
			]
		}
	},
	{
		"id": "http://zotero.org/groups/2321158/items/VM6HGUB8",
		"type": "article-journal",
		"abstract": "This article reflects upon and updates our prize‐winning paper, ‘First‐mover advantages,’ which was published in SMJ 10 years ago. We discuss the evolution of the literature over the past decade and suggest opportunities for continuing research. In particular, we see benefits from linking empirical findings on first‐mover advantages with the complementary stream of research on the resource‐based view of the firm. © 1998 John Wiley & Sons, Ltd.",
		"container-title": "Strategic Management Journal",
		"DOI": "10.1002/(SICI)1097-0266(1998120)19:12<1111::AID-SMJ21>3.0.CO;2-W",
		"ISSN": "0143-2095",
		"issue": "12",
		"language": "en",
		"note": "01497",
		"page": "1111–1125",
		"source": "tsinghua-primo.com",
		"title": "First‐mover (dis)advantages: retrospective and link with the resource‐based view",
		"title-short": "First‐mover (dis)advantages",
		"volume": "19",
		"author": [
			{
				"family": "Lieberman",
				"given": "Marvin B."
			},
			{
				"family": "Montgomery",
				"given": "David B."
			}
		],
		"issued": {
			"date-parts": [
				[
					"1998"
				]
			]
		}
	}
]

**Comment by redleafnew** [comment]
这两个不是一年的文献

**Comment by fredericky123** [comment]
我去 我眼睛花了

**Comment by redleafnew** [comment]
没有其它问题了吧。

**Comment by fredericky123** [comment]
是的，可以关issue了，多谢~
