### ISSUE TITLE
法学引注手册要求“v. 用斜体”

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#202]
**描述错误**

CSL 样式：301manual-of-legal-citation-multi-lingual.csl
法学引注手册要求“v. 用斜体”但是在条目信息中好像改不了，请问csl可以改这个的格式吗？

**屏幕截图**
![CleanShot 2023-09-02 at 14 30 02@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/ba5f2a11-f8e1-4f35-aa1e-d901d4ca7ce0)

**条目信息**

```json
[
	{
		"id": "http://zotero.org/groups/4677213/items/MV9YG9LK",
		"type": "legal_case",
		"container-title": "EWHC",
		"language": "en",
		"page": "2808",
		"title": "Sheffield City Council v. E and S",
		"volume": "2004",
		"issued": {
			"date-parts": [
				[
					"2004"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
目前 CSL 无法处理，只能手动在标题中著录 `<i>v.</i>`。

这个问题在 CSL 和 Zotero 的论坛中有过讨论，但是没纳入 CSL 的计划。

**Comment by yzy1228682367** [comment]
另外请问如果可以调整格式的话，可不可以统一把标题中的“《》”改为“<>”呢？

**Comment by yzy1228682367** [comment]
> 目前 CSL 无法处理，只能手动在标题中著录 `<i>v.</i>`。
> 
> 这个问题在 CSL 和 Zotero 的论坛中有过讨论，但是没纳入 CSL 的计划。

哦哦好咧，谢谢。

**Comment by zepinglee** [comment]
> > 目前 CSL 无法处理，只能手动在标题中著录 `<i>v.</i>`。
> > 这个问题在 CSL 和 Zotero 的论坛中有过讨论，但是没纳入 CSL 的计划。
> 
> 哦哦好咧，谢谢。那请问翻译器有没有可能实现这种转换呢？

可以实现，但是对标题不使用书名号的样式（比如 GB/T 7714）不太友好。

我也尝试过在 CSL 样式中将 `open-quote` 和 `close-quote` 设置为书名号，但是会将正常的引号转为书名号。

我觉得可以在插件中实现转换单双书名号的转行，不妨在给插件（比如茉莉花）作者提 feature request。

**Comment by yzy1228682367** [comment]
感谢~
