### ISSUE TITLE
请问法学引注手册可否针对不同法律文件形成不同样式？

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#203]
**描述错误**
CSL 样式：法学引注手册
法学引注手册针对不同法律格式并不一致，或许法学引注手册可以默认输出“法律名称”“公法号”“颁布日期”，让使用者自己决定删除哪一field，或者可以通过识别其他里面的“法律”“决定”“法规”“规章”“规范性文件”字样，形成不同样式？

**屏幕截图**
![CleanShot 2023-09-04 at 21 28 49@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/ea5220d0-f8bf-4cae-85bf-b047aacb0755)
![CleanShot 2023-09-04 at 21 29 34@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/7a3c663d-5f79-4620-a490-d12212547627)

**条目信息**

```json
[
	{
		"id": "http://zotero.org/groups/4677213/items/JBCBMVXP",
		"type": "legislation",
		"language": "zh",
		"note": "法宝引证码: CLI.12.5537956",
		"number": "德办规[2022]10号",
		"title": "德阳市人民政府办公室关于印发<德阳市数据要素市场管理暂行办法>的通知",
		"URL": "https://www.pkulaw.com/lar/03e98798ef205f4a1faf9c788c472e25bdfb.html?keyword=%E6%95%B0%E6%8D%AE%E8%A6%81%E7%B4%A0&way=listView",
		"accessed": {
			"date-parts": [
				[
					"2023",
					6,
					16
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2022",
					9,
					1
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
法律和法律性质的决定使用 `legislation`，规章和规范需要在 `Exra` 填写 `Type: regulation`。可以参考 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/GTTN32IE/items/MIN98AEI/collection>
 的测试文献。（可以按照 `extra` 字段排序，其中 `Citation Key` 对应《手册》的章节。）

<img width="457" alt="Screenshot 2023-09-05 at 00 35 00" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/5516c0ac-67c4-4663-b290-66d07a152dc1">

**Comment by yzy1228682367** [comment]
好咧，谢谢~

**Comment by zepinglee** [comment]
另外，示例文献缺失 `Type: regulation` 是 translator 的 bug 导致到。<https://github.com/l0o0/translators_CN/pull/208> 修复了这一问题。

**Comment by yzy1228682367** [comment]
天呐，大佬YYDS！！！
