### ISSUE TITLE
011gb样式文献列表没有生成被引用页码信息

### ISSUE THREAD

**Issue by David-Csy** [redleafnew/Chinese-STD-GB-T-7714-related-csl#205]
**描述错误**
CSL 样式：[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)

错误：参考文献列表没有引用的页码，而是文献本身的页码。

需求：需要体现引用的页码。

如：
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/145189277/7223a73c-d874-476c-8e89-b35766c479be)

**Comment by zepinglee** [comment]
如果要在参考文献表中列出具体引用的页码，只能修改 `page` 字段，或者在 `extra` 填写 `Pages: 42`。

如果要在引注处标出，需要修改样式。国标的页码样式（括号外上标）与引用多篇文献（如 “(Doe, 1984; Roe, 2001)”）在 CSL 中冲突，无法同时实现，所以本样式做了取舍，只实现后者。

**Comment by David-Csy** [comment]
您好！已经在引用时填写了page字段，但是参考文献表中依然没有列出所引用的页码，谢谢！

**Comment by zepinglee** [comment]
> 您好！已经在引用时填写了page字段，但是参考文献表中依然没有列出所引用的页码

引用时的 `page` 跟参考文献表无关，文献本身的 `page` 字段才会出现在参考文献表中。

国标要求的是引文页码是标注在引用处的。

<img width="784" alt="Screenshot 2023-09-16 at 23 03 14" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/53a68e08-042a-4640-bf77-2f7bffe6ceb0">

但是这一要求在 CSL 与多篇文献并列冲突。以上面的文献为例，CSL 要么输出“(Brown et al., 1983)<sup>1</sup> (Hyland, 2011)<sup>171</sup>” 但不能将两篇文献同时放进括号中，要么输出“(Brown et al., 1983; Hyland, 2011)”但无法在括号外显示页码。如果你接受非标准的页码标注形式，可以进一步修改样式。

**Comment by David-Csy** [comment]
好的谢谢以上都明白，但目前想实现的是如下“山西师范大学学报”这样的效果，即所引用页码“147”不显示在正文，而是显示在参考文献中，与多次引用同一文献或同一处引用多个文献无关：
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/145189277/606bd12e-c0cc-47f3-bd30-ea3ab394e36b)
谢谢！

**Comment by zepinglee** [comment]
> 好的谢谢以上都明白，但目前想实现的是如下“山西师范大学学报”这样的效果，即所引用页码“147”不显示在正文，而是显示在参考文献中。

你所描述的在 CSL 中无法实现。《山西师范大学学报》这篇文献只显示一个页码是因为著录的数据中只有一个页码，不是引用的特定页码。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/767b115e7f8085f1c5c001f271c6bad3336b212e/tests/default-data.json#L2080-L2085

**Comment by David-Csy** [comment]
好的好的明白了，谢谢您，十分感谢！
