### ISSUE TITLE
华中科技大学学位论文格式错误

### ISSUE THREAD

**Issue by G-hc** [redleafnew/Chinese-STD-GB-T-7714-related-csl#207]
**描述错误**

CSL 样式：418huazhong-university-of-science-and-technology.csl

华中科技大学学位论文参考文献格式应包含文献类型标识和末尾的标点符号，示例如下：
[1]	卓振宇, 张宁, 谢小荣, 李浩志, 康重庆. 高比例可再生能源电力系统关键技术及发展挑战[J]. 电力系统自动化, 2021, 45(9): 171-191.

**Comment by zepinglee** [comment]
这里的模板没有文献类型标识和末尾的标点。<https://aia.hust.edu.cn/info/1122/5294.htm>

附件1：理工科-博士-华中科技大学学位论文参考模板-20220419更新（word版）.docx

<img width="472" alt="Screenshot 2023-09-20 at 18 46 48" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/0814e52a-ca2f-4a2d-84c8-2472f5cf070c">

如果你的格式要求跟这个不一致，请提供链接

**Comment by G-hc** [comment]
感谢您的回复，我先前提出的issue有些片面，华中科技大学人工智能与自动化学院官网给出的模板确实不包含文献类型标识和末尾的标点符号，但在具体落实时，不同学院存在差异，电气与电子工程学院对参考文献格式的要求包含文献类型标识和末尾的标点符号（模板在线地址：https://www.overleaf.com/read/shrxrpccvmks）：
![华中科技大学](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/43783200/c8194d50-967e-43fc-9288-505496a234c6)

是否可以提供两个版本供选择使用呢？

**Comment by zepinglee** [comment]
> 感谢您的回复，我先前提出的issue有些片面，华中科技大学人工智能与自动化学院官网给出的模板确实不包含文献类型标识和末尾的标点符号，但在具体落实时，不同学院存在差异，电气与电子工程学院对参考文献格式的要求包含文献类型标识和末尾的标点符号。

有没有学院官网的链接？或者学院官方的文件？

> （模板在线地址：[https://www.overleaf.com/read/shrxrpccvmks）：](https://www.overleaf.com/read/shrxrpccvmks%EF%BC%89%EF%BC%9A) ![华中科技大学](https://user-images.githubusercontent.com/43783200/269281640-c8194d50-967e-43fc-9288-505496a234c6.png)

这个模板应该是 <https://github.com/Lianghao93/HUST-PhD-Thesis-Latex-v3.1>，最后更新于 2022-05-22。建议找学院的官方文件确认一下具体要求。

> 是否可以提供两个版本供选择使用呢？

其实这个带文献类型标识的格式比较接近 [003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl)。你可以先用着。

**Comment by G-hc** [comment]
参考您仓库中“更多 Zotero 使用教程及技巧”这部分内容，已自行修改csl文件使其能显示末尾的标点符号，但未能成功添加文献类型标识。请问需要在csl文件中添加哪些内容才可以正常显示文献类型标识呢？

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/fbadbb86482ffe4ab20d3d78ecef1be2003ab48e/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl#L95-L98

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/fbadbb86482ffe4ab20d3d78ecef1be2003ab48e/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl#L118-L185

**Comment by G-hc** [comment]
非常感谢您的帮助！已成功将参考文献格式修改为包含文献类型标识和末尾的标点符号。
