### ISSUE TITLE
对电子资源载体类型标识代码的完整支持

### ISSUE THREAD

**Issue by jiaojiaodubai** [redleafnew/Chinese-STD-GB-T-7714-related-csl#208]
**描述错误**

CSL 样式：000gb-t-7714-2015-numeric-bilingual.csl

错误：无法支持完整的电子资源载体类型标识代码。
预期效果：按照《GB/T-7714-2015》的规定，著录格式中以`[文献类型标识\文献载体标识]`标出载体，电子资源载体的标识码包括磁带（MT）、磁盘（DK）、光盘（CD）和联机网络（OL）。

**其他相关信息**
我注意到[Zotero的标准条目类型](https://[aurimasv.github.io/z2csl/typeMap.xml#map-book](https://aurimasv.github.io/z2csl/typeMap.xml#map-book))中确实没有类似“media-code”的字段，现有CSL样式是通过检测DOI或URL非空来判断条目是否为联机网络资源。`000gb-t-7714-2015-numeric-bilingual.csl`会考虑在将来支持剩下的载体类型标识代码吗？
我现在要引用一些含有音像出版物（CD）的条目，不得不手动标注类型并对`000gb-t-7714-2015-numeric-bilingual.csl`作一些修改。是否有推荐使用的字段？是在”Archive“这个字段标注类型还是另外在Extra开辟一个字段去标识呢？

**Comment by redleafnew** [comment]
给出具体的条目JSON格式？

**Comment by jiaojiaodubai** [comment]
> 给出具体的条目JSON格式？

我认为这是个一般性的问题，与具体的条目无关，不过我可以给出一个例子，如
```json
[
	{
		"id": "YinQingChangZheng2018",
		"type": "book",
		"event-place": "北京",
		"ISBN": "978-7-88331-049-5",
		"language": "zh-CN",
		"publisher": "北京荣辅景音像公司",
		"publisher-place": "北京",
		"source": "Dangdang",
		"title": "长征",
		"URL": "http://product.dangdang.com/11057615852.html",
		"author": [
			{
				"literal": "印青"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					27
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2018",
					6,
					11
				]
			]
		}
	}
]
```
类似这样的音像出版物有ISBN，是可供引用的文献（音乐、电影、历史等专业的论文可能需要引用这些音像出版物）。不过由于Zotero标准条目的字段限制，我无法在上面的例子中显著地表明它的载体类型是CD。

**Comment by zepinglee** [comment]
在 extra 字段填写 medium: CD在 2023年9月27日，23:59，jiaojiaodubai ***@***.***> 写道：﻿

给出具体的条目JSON格式？

我认为这是个一般性的问题，与具体的条目无关，不过我可以给出一个例子，如
[
	{
		"id": "YinQingChangZheng2018",
		"type": "book",
		"event-place": "北京",
		"ISBN": "978-7-88331-049-5",
		"language": "zh-CN",
		"publisher": "北京荣辅景音像公司",
		"publisher-place": "北京",
		"source": "Dangdang",
		"title": "长征",
		"URL": "http://product.dangdang.com/11057615852.html",
		"author": [
			{
				"literal": "印青"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					27
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2018",
					6,
					11
				]
			]
		}
	}
]
类似这样的音像出版物有ISBN，是可供引用的文献（音乐、电影、历史等专业的论文可能需要引用这些音像出版物）。不过由于Zotero标准条目的字段限制，我无法在上面的例子中显著地表明它的载体类型是CD。

**Comment by jiaojiaodubai** [comment]
问题得到解决。
