### ISSUE TITLE
法学引注手册：法规没有文件号则标明发布日期

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#210]
**描述错误**

CSL 样式：法学引注手册
因为有的文件没有标明公法号，例如这个文件https://www.tjcac.gov.cn/wxdt/tjs/202201/t20220130_5795524.html
个人以为似乎可以当没有公法号的时候，输出颁布日期。

**屏幕截图**
![CleanShot 2023-09-30 at 18 07 06@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/7ecefbd7-de66-47ff-9a69-f2339890e0f1)
如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/11021824/items/SAQLR5ZB",
		"type": "legislation",
		"language": "zh",
		"note": "type: regulation",
		"title": "天津市互联网信息办公室关于印发天津市数据交易管理暂行办法的通知",
		"URL": "https://www.tjcac.gov.cn/wxdt/tjs/202201/t20220130_5795524.html",
		"author": [
			{
				"literal": "天津市互联网信息办公室"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					6,
					24
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2022",
					1,
					25
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
我觉得有道理。

**Comment by yzy1228682367** [comment]
> 我觉得有道理。

哈哈哈，感谢大佬~
大佬节日快乐呐~

**Comment by zepinglee** [comment]
在 d273a20 中修改。

另外这篇示例的`"title"`应该填 `天津市数据交易管理暂行办法`。

**Comment by yzy1228682367** [comment]
> 在 [d273a20](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/d273a204d27ccbe5b86178d33ae7b8598966f42a) 中修改。
> 
感谢大佬~

> 另外这篇示例的`"title"`应该填 `天津市数据交易管理暂行办法`。
> 
![CleanShot 2023-10-03 at 13 43 26@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/ace9b755-fb08-452b-b694-ba67ca71297d)
应该就是填“天津市互联网信息办公室关于印发天津市数据交易管理暂行办法的通知”的，因为这是个规范性文件，应该加制定机关。
