### ISSUE TITLE
申请添加中南民族大学硕士学位论文格式

### ISSUE THREAD

**Issue by Tinny00** [redleafnew/Chinese-STD-GB-T-7714-related-csl#211]
**样式信息**

- 学校名称：中南民族大学研究生学位论文

- 英文名称：South-central Minzu University

- 参考文献格式要求的**官网**链接：https://www.scuec.edu.cn/yjsy/info/1038/1252.htm （注：官网链接中写的很粗略，详细格式请参照附件）

- （期刊的）ISSN 号：

- （期刊的）相关领域：

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: Emma543654

**其他样式信息**
详细格式要求请参见以下附件：
[中南民族大学外语学院教育硕士学位论文格式规范.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12774992/default.pdf)

**Comment by redleafnew** [comment]
已经赋予管理权限。

在群组新建`中南民族大学`文件夹。

将这个文件上的示例录入群组中、
> 详细格式要求请参见以下附件：
[中南民族大学外语学院教育硕士学位论文格式规范.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12774992/default.pdf)

另外，看一下与仓库中哪个样式效果最接近，方便修改。

**Comment by redleafnew** [comment]
`https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/019gb-t-7714-1987-numeric-bilingual.csl`

有1987的，看看直接应用，哪还不符合。

**Comment by zepinglee** [comment]
@Tinny00 研究生院的格式基本按照 GB/T 7714—1987，但是外语学院的格式似乎是 GB/T 7714—2015 跟 MLA 格式的混合版，比较复杂。需要将第二节“参考文献的格式及举例”的示例文献录入 Zotero 方便我们进行测试。

<img width="733" alt="Screenshot 2023-10-03 at 12 11 40" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/305cbacb-6886-4985-94ff-73b351e3acf3">
