### ISSUE TITLE
申请添加《中国生态农业学报(中英文)》 CSL 样式

### ISSUE THREAD

**Issue by liandmin1314** [redleafnew/Chinese-STD-GB-T-7714-related-csl#212]
**样式信息**

- 期刊/学校名称：[《中国生态农业学报(中英文)》]

- 英文名称：[Chinese Journal of Eco-Agriculture]

- 参考文献格式要求的**官网**链接[例如 <http://www.ecoagri.ac.cn/news_list.htm?column=xiazaizhongxin>(具体可参考附件)]

- （期刊的）ISSN 号：[2096-6237 ]

- （期刊的）相关领域：[biology]

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:MINandLI

**其他样式信息**
[《中国生态农业学报（中英文）》文末参考文献著录格式2020.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12837266/2020.pdf)

**Comment by zepinglee** [comment]
感觉在 [003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl) 的基础上去掉末尾的点即可。

**Comment by liandmin1314** [comment]
> 感觉在 003GB-t-7714-2015-numeric-bilingual-no-url-doi.csl 的基础上去掉末尾的点即可。

好的，我看下。谢谢啦

**Comment by zepinglee** [comment]
试一下 [117chinese-journal-of-eco-agriculture.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/117chinese-journal-of-eco-agriculture.csl) 有没有其他问题。

这个样式比较简单，就不需要录入官网的示例文献测试了。

**Comment by liandmin1314** [comment]
> 试一下 [117Chinese-journal-of-eco-agriculture.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/117chinese-journal-of-eco-agriculture.csl) 有没有其他问题。
> 
> 这个样式比较简单，就不需要录入官网的示例文献测试了。
你好，我查看了期刊的参考文献发现，每个中文的参考文献下还需要有对应的英文翻译，本身就是英文文献的不用。现在这个样式还不能达到这个要求，只能是全中文的在中文文献下面没有与其对应的翻译的英文文献。是否可以修改下

**Comment by liandmin1314** [comment]
> > 试一下 [117Chinese-journal-of-eco-agriculture.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/117chinese-journal-of-eco-agriculture.csl) 有没有其他问题。
> > 这个样式比较简单，就不需要录入官网的示例文献测试了。
> > 你好，我查看了期刊的参考文献发现，每个中文的参考文献下还需要有对应的英文翻译，本身就是英文文献的不用。现在这个样式还不能达到这个要求，只能是全中文的在中文文献下面没有与其对应的翻译的英文文献。是否可以修改下


参考如下
[1]	都江雪, 柳开楼, 黄晶, 等. 中国稻田土壤有效磷时空演变特征及其对磷平衡的响应[J]. 土壤学报, 2021, 58(2): 476-486 
	DU J X, LIU K L, HUANG J, et al. Spatio-temporal evolution characteristics of soil available phosphorus and its response to phosphorus balance in paddy soil in China[J]. Acta Pedologica Sinica, 2021, 58(2): 476-486
[2]	FORKUOR G, HOUNKPATIN O K L, WELP G, et al. High resolution mapping of soil properties using remote sensing variables in South-Western Burkina Faso: A comparison of machine learning and multiple linear regression models[J]. Plos One, 2017, 12(1): e0170478

**Comment by liandmin1314** [comment]
参考如下
[1]	都江雪, 柳开楼, 黄晶, 等. 中国稻田土壤有效磷时空演变特征及其对磷平衡的响应[J]. 土壤学报, 2021, 58(2): 476-486 
	DU J X, LIU K L, HUANG J, et al. Spatio-temporal evolution characteristics of soil available phosphorus and its response to phosphorus balance in paddy soil in China[J]. Acta Pedologica Sinica, 2021, 58(2): 476-486
[2]	HENGL T, LEENAARS J G B, SHEPHERD K D, et al. Soil nutrient maps of Sub-Saharan Africa: Assessment of soil nutrient content at 250 m spatial resolution using machine learning[J]. Nutrient Cycling in Agroecosystems, 2017, 109(1): 77-102

**Comment by liandmin1314** [comment]
[《中国生态农业学报（中英文）》论文模版2020.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12840828/2020.pdf)
还有一些对于字体字号以及间距的要求，不知可否麻烦您帮助修改一下

**Comment by zepinglee** [comment]
> 你好，我查看了期刊的参考文献发现，每个中文的参考文献下还需要有对应的英文翻译，本身就是英文文献的不用。现在这个样式还不能达到这个要求，只能是全中文的在中文文献下面没有与其对应的翻译的英文文献。是否可以修改下

这个实现起来比较复杂，需要一定工作量。

参考 211《植物保护学报》样式，中文文献需要将作者姓名、标题、期刊、出版地、出版社的英文翻译分别填写在 extra 中的 original-author, original-title, original-container-title, original-publisher-place, original-publisher 字段。

**Comment by zepinglee** [comment]
> [《中国生态农业学报（中英文）》论文模版2020.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/12840828/2020.pdf) 还有一些对于字体字号以及间距的要求，不知可否麻烦您帮助修改一下

字体和行距并不在 CSL 的范围。CSL 可以设置单倍或者双倍行距，但是像”中文为小五号宋体, 西文为小五号 Times New Roman; 14 磅行距“就无法设置了。

**Comment by liandmin1314** [comment]
> > 你好，我查看了期刊的参考文献发现，每个中文的参考文献下还需要有对应的英文翻译，本身就是英文文献的不用。现在这个样式还不能达到这个要求，只能是全中文的在中文文献下面没有与其对应的翻译的英文文献。是否可以修改下
> 
> 这个实现起来比较复杂，需要一定工作量。
> 
> 参考 211《植物保护学报》样式，中文文献需要将作者姓名、标题、期刊、出版地、出版社的英文翻译分别填写在 extra 中的 original-author, original-title, original-container-title, original-publisher-place, original-publisher 字段。
211《植物保护学报》样式和中国生态农业学报格式不太一样，修改的话可以直接在zotero自带的样式编辑器里更改吗

**Comment by zepinglee** [comment]
> 211《植物保护学报》样式和中国生态农业学报格式不太一样，修改的话可以直接在zotero自带的样式编辑器里更改吗

我的意思是这类需要英文翻译的样式修改起来比较复杂，需要等些时间。如果你想自己修改当然也可以。

**Comment by liandmin1314** [comment]
> > 211《植物保护学报》样式和中国生态农业学报格式不太一样，修改的话可以直接在zotero自带的样式编辑器里更改吗
> 
> 我的意思是这类需要英文翻译的样式修改起来比较复杂，需要等些时间。如果你想自己修改当然也可以。

好的，那我等您修改好，自己不太会修改，非常感谢

**Comment by liandmin1314** [comment]
> > 211《植物保护学报》样式和中国生态农业学报格式不太一样，修改的话可以直接在zotero自带的样式编辑器里更改吗
> 
> 我的意思是这类需要英文翻译的样式修改起来比较复杂，需要等些时间。如果你想自己修改当然也可以。

你好，想问一下，这个中英文对照的已经修改好了吗？

**Comment by zepinglee** [comment]
上周末做了一部分。预计这周末处理完。

**Comment by liandmin1314** [comment]
> 上周末做了一部分。预计这周末处理完。

好的，麻烦您啦

**Comment by zepinglee** [comment]
b10f9e9 添加了英文翻译。需要注意：
1. CSL 无法在英文翻译前换行，需要手动将 `; ` 替换为换行。
2. 英文翻译的数据录入方式参照 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA/items/W6G72RST/collection>。
<img width="331" alt="Screenshot 2023-10-22 at 23 43 06" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/8c61dcaf-e56c-4e76-92cd-be6f42405dd1">

**Comment by liandmin1314** [comment]
收到，作者这个是需要把每一个英文翻译手动按照您上面给出的例子填进去才可以正确显示使用把

**Comment by zepinglee** [comment]
> 收到，作者这个是需要把每一个英文翻译手动按照您上面给出的例子填进去才可以正确显示使用把

是的。
