### ISSUE TITLE
申请添加同济大学硕士学位论文格式

### ISSUE THREAD

**Issue by guoyurr** [redleafnew/Chinese-STD-GB-T-7714-related-csl#213]
**样式信息**

- 期刊/学校名称：同济大学研究生学位论文

- 英文名称：Tongji University

- 参考文献格式要求的**官网**链接 <https://gs.tongji.edu.cn/info/1063/1754.htm>

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: guoyu700

**其他样式信息**
我们的要求与451兰大的样式类似，只是有以下不同：
1.	中文文献的所有符号都是全角，比如逗号；
2.	中文文献的“.”后面不接空格，字体是宋体；
3.	英文文献3个作者的写法是：A姓 A名首字母. A名首字母., B姓 B名首字母. B名首字母. & C姓 C名首字母. C名首字母., 
4.	[D]博士论文的标识是：[博士学位论文]；

**Comment by zepinglee** [comment]
> 我们的要求与451兰大的样式类似，只是有以下不同：

451lanzhou-university.csl 有很多 bug，不建议在此基础上修改。

> 3. 英文文献3个作者的写法是：A姓 A名首字母. A名首字母., B姓 B名首字母. B名首字母. & C姓 C名首字母. C名首字母.,

两份文件的姓名格式与你的描述有些差异。

`【参阅】同济大学研究生学位论文写作规范（2023）.doc` 第 8 页：

<img width="719" alt="Screenshot 2023-10-07 at 23 14 14" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/85559b77-6075-49ad-9784-3e218d4b24d2">

`【参阅】同济大学研究生学位论文写作示例（2023）.doc`：

<img width="677" alt="Screenshot 2023-10-07 at 23 16 12" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/47f51c67-579b-4ee8-85d7-0deeee81d1ae">

**Comment by guoyurr** [comment]
> > 我们的要求与451兰大的样式类似，只是有以下不同：
> 
> 451lanzhou-university.csl 有很多 bug，不建议在此基础上修改。
> 
> > 3. 英文文献3个作者的写法是：A姓 A名首字母. A名首字母., B姓 B名首字母. B名首字母. & C姓 C名首字母. C名首字母.,
> 
> 两份文件的姓名格式与你的描述有些差异。
> 
> `【参阅】同济大学研究生学位论文写作规范（2023）.doc` 第 8 页：
> 
> <img alt="Screenshot 2023-10-07 at 23 14 14" width="719" src="https://user-images.githubusercontent.com/12290822/273393957-85559b77-6075-49ad-9784-3e218d4b24d2.png">
> `【参阅】同济大学研究生学位论文写作示例（2023）.doc`：
> 
> <img alt="Screenshot 2023-10-07 at 23 16 12" width="677" src="https://user-images.githubusercontent.com/12290822/273394066-47f51c67-579b-4ee8-85d7-0deeee81d1ae.png">

按照下面那份文件的就好

**Comment by zepinglee** [comment]
我建议联系学校老师确认一下具体的格式。

下面那份文件（写作示例）的“年卷期”有“Vol.”，跟其他文献明显不一致，感觉像是从哪随便拷贝的。

**Comment by guoyurr** [comment]
> 我建议联系学校老师确认一下具体的格式。
> 
> 
> 
> 下面那份文件（写作示例）的“年卷期”有“Vol.”，跟其他文献明显不一致，感觉像是从哪随便拷贝的。

其实我也发现了，不过我看之前他们就用的第二种格式，所以我也打算用第二种了。

**Comment by zepinglee** [comment]
> 其实我也发现了，不过我看之前他们就用的第二种格式，所以我也打算用第二种了。

建议联系老师确认一下。

另外英文中没有“559~565”这样用波浪号表示数值范围的用法。所以在我看来第二种很不规范。

**Comment by zepinglee** [comment]
> 反而按照我们学校所给的格式写会被外校专家否定，

这个不能 rebuttal 吗？

> 所以很多人直接就用的中科大的格式。

USTC 的是 GB/T 7714 加微小修改，与你们第一种格式（`同济大学研究生学位论文写作规范（2023）.doc`）更为接近。我打算按这份文件的格式。如果你们有需要可以找 USTC 的样式。

**Comment by redleafnew** [comment]
@zepinglee 这个搞完了吗？

**Comment by zepinglee** [comment]
我把这个给忘了，马上处理。

**Comment by zepinglee** [comment]
在 226fb1f 中添加。

同济大学的样式跟 1993 年的《中国高等学校自然科学学报编排规范》格式一致，基本跟 GB/T 7714—1987 相同，但略有差异。

**Comment by redleafnew** [comment]
@zepinglee 辛苦了。
@guoyurr 麻烦看看是不是符合要求了。

**Comment by guoyurr** [comment]
> @zepinglee 辛苦了。 @guoyurr 麻烦看看是不是符合要求了。

我这里暂时没看到问题，不过我们学校没一个统一标准。我师兄师姐参考文献格式都是用的中科大没用学校的，看起来更加规范。

**Comment by Jone-Chan** [comment]
感谢作者 @zepinglee 
同时也想请问一下 @guoyurr ，用学校的标准范围会盲审不过吗？中科大USTC的格式和我们的区别大不大呀？不大的话我也想直接用USTC的了

**Comment by Jone-Chan** [comment]
> 感谢作者 @zepinglee 同时也想请问一下 @guoyurr ，用学校的标准范围会盲审不过吗？中科大USTC的格式和我们的区别大不大呀？不大的话我也想直接用USTC的了

顺便想问问大家有没有同济大学2023最新版的硕士毕业论文latex模板呀

**Comment by Jone-Chan** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/57897644/168fbe9b-c5b7-41e7-96a3-c208027e2793)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/57897644/c5785bda-6cd2-4dc2-86ed-8e7672b97d5a)

更新后的硕博论文标识不太对，显示的是“[硕士]”和“[博士]”，而要求的是“[硕士学位论文]”和“[博士学位论文]”，烦请作者修改一下。
[D]博士论文的标识是：[博士学位论文]；

**Comment by zepinglee** [comment]
> ![image](https://private-user-images.githubusercontent.com/57897644/289753470-168fbe9b-c5b7-41e7-96a3-c208027e2793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjIyNDcsIm5iZiI6MTcwMjM2MTk0NywicGF0aCI6Ii81Nzg5NzY0NC8yODk3NTM0NzAtMTY4ZmJlOWItYzViNy00MWU3LTk2YTMtYzIwODAyN2UyNzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA2MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGZiZGIyZjFkMWRlYzQ5YzM5ZDliNmRjOGY4OTcwNDU0NTE1NzcxMGRlN2JmOTMzZTcxZjQ2Y2IzZTMyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ab2q9h8cXY6fi2IRAHqiEBYKPnZ22c9X0yMcXI3fdwk) ![image](https://private-user-images.githubusercontent.com/57897644/289753570-c5785bda-6cd2-4dc2-86ed-8e7672b97d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjIyNDcsIm5iZiI6MTcwMjM2MTk0NywicGF0aCI6Ii81Nzg5NzY0NC8yODk3NTM1NzAtYzU3ODViZGEtNmNkMi00ZGMyLTg2ZWQtOGU3NjcyYjk3ZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA2MTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTI2ZGFlOTZjYzE0NmY4ZGFhNDQzMmU1ODgxM2QwNGQ1ZjBmZDMwNDJiZmMyNjcxYjI5ODk2YTkzMjJkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAqZcejSnu0gCkxvUN9OvKvVoNixx6pjdKnBLxoHVGg)
> 
> 更新后的硕博论文标识不太对，显示的是“[硕士]”和“[博士]”，而要求的是“[硕士学位论文]”和“[博士学位论文]”，烦请作者修改一下。 [D]博士论文的标识是：[博士学位论文]；

https://www.zotero.org/support/kb/item_types_and_fields#fields_for_reports_and_theses
<img width="846" alt="Screenshot 2023-12-12 at 14 20 06" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/1021b455-2521-4ee8-acd8-e28404249919">

**Comment by zepinglee** [comment]
另外“in”应该大写，需要改一下。

**Comment by zepinglee** [comment]
> 另外“in”应该大写，需要改一下。

在 8fffd05 中修复。
