### ISSUE TITLE
华中科技大学模板会议论文开会日期不显示

### ISSUE THREAD

**Issue by RuiDream** [redleafnew/Chinese-STD-GB-T-7714-related-csl#214]
**描述错误**

华中科技大学会议论文没有开会日期，

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/bdd3b967-31d2-4d63-aabc-f0e78645f49e)

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
按照模板填写 CSL-JSON 等信息。

另外学校的官方文件是怎么要求的？有没有链接和截图？

**Comment by RuiDream** [comment]
> 按照模板填写 CSL-JSON 等信息。
> 
> 另外学校的官方文件是怎么要求的？有没有链接和截图？
在会议论文中，目前在工具的配置界面日期处对应代码前端展示是issued-date中的issued-year字段 并且右侧有年月日解析的展示
但是在代码中使用<date variable="event-date" form="text">字段显示无效
请问能否告知issued-date对应的年 月 日 字段名称
或者给出一个event-date的配置输入样例
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/cc084d04-6f11-4660-8601-80ad8ddab430)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/a1e337f6-7f1c-41f2-8527-2766d5be8747)

**Comment by zepinglee** [comment]
会议日期需要在 `extra` 字段填写 `Event Date: yyyy-mm-dd/yyyy-mm-dd`，参考示例 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/G9SXAV8Z/items/GD8X7GAE/collection> 以及 Zotero 文档 <https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero>。

**Comment by RuiDream** [comment]
> 会议日期需要在 `extra` 字段填写 `Event Date: yyyy-mm-dd/yyyy-mm-dd`，参考示例 https://www.zotero.org/groups/4677213/chinese_csl_development/collections/G9SXAV8Z/items/GD8X7GAE/collection 以及 Zotero 文档 https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero。
> 
> Zotero 的 `Date`（日期）是出版日期，对应 CSL 的 `issued`，与 `event-date` 含义不同。

解决了！非常感谢！！！

**Comment by zepinglee** [comment]
因为你们学校的这个示例用的是缩写的形式（华中科技大学学位论文参考模板-理工科-博士-20220419更新（word版））。

<img width="785" alt="Screenshot 2023-10-10 at 10 36 27" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/8f338dde-5618-48d7-809c-7b6212037411">

**Comment by zepinglee** [comment]
> 不过，我还有一个问题。 日期写入之后因为要求月份要缩写，我在zotero是这样写的

> 但是有几个月份按理说是没有缩写的，在显示中一律按照三个字母进行了显示，因此导致June和July中成为这个样子

我查了一下，国外大部分体例的“May”, “June”, “July” 是不缩写的，比如下面的 Chicago Manual of Style，但是 “March”和“Aprl”可能有些差异。这个比较好改。

<img width="604" alt="Screenshot 2023-10-10 at 10 43 29" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/da3a10f4-9a45-4215-8091-3ac845479d7d">

**Comment by RuiDream** [comment]
> > 不过，我还有一个问题。 日期写入之后因为要求月份要缩写，我在zotero是这样写的
> 
> > 但是有几个月份按理说是没有缩写的，在显示中一律按照三个字母进行了显示，因此导致June和July中成为这个样子
> 
> 这个主要是因为 CSL 官方提供的 locales-en-US 是缩写的形式：https://github.com/citation-style-language/locales/blob/fe37f30df9d11e43f5f727c9b46c067bdc543b55/locales-en-US.xml#L641-L642。
> 
> 我查了一下，国外大部分体例的“May”, “June”, “July” 是不缩写的，比如下面的 Chicago Manual of Style，但是 “March”和“Aprl”可能有些差异。这个比较好改，见 [1913f3b](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/1913f3baa037a5c65c980a8ca7c2e5f713e3b8fb)。
> 
> <img alt="Screenshot 2023-10-10 at 10 43 29" width="604" src="https://user-images.githubusercontent.com/12290822/273760534-da3a10f4-9a45-4215-8091-3ac845479d7d.png">

谢谢您！解决了。又遇到下一个问题，对于有些开会日期是跨月的，类似这种：
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/8c782a79-708b-4b0a-840a-47e6af29e0db)

它是这样显示的：
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/78c7e2ea-db3e-4047-af4d-cf529b3f4f1b)
后面日和月就会连在一起，是我填入的方式不对吗？

**Comment by zepinglee** [comment]
> 谢谢您！解决了。又遇到下一个问题，对于有些开会日期是跨月的，类似这种：
>
> 它是这样显示的： 
> 后面日和月就会连在一起，是我填入的方式不对吗？

Zotero 官方文档（<https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra>）要求 `Extra` 的日期应使用 ISO 8601 的格式（yyyy-mm-dd/yyyy-mm-dd）。前面的“12 Oct. 2022”能够正常显示可能是因为 citeproc-js 有一定的解析（parse）能力，但是应该不能处理更复杂的情况。

**Comment by RuiDream** [comment]
> > 谢谢您！解决了。又遇到下一个问题，对于有些开会日期是跨月的，类似这种：
> > 它是这样显示的：
> > 后面日和月就会连在一起，是我填入的方式不对吗？
> 
> Zotero 官方文档（https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra）要求 `Extra` 的日期应使用 ISO 8601 的格式（yyyy-mm-dd/yyyy-mm-dd）。前面的“12 Oct. 2022”能够正常显示可能是因为 citeproc-js 有一定的解析（parse）能力，但是应该不能处理更复杂的情况。

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/22195864/508a9f49-b303-4d92-8785-869b59b720a4)
我这样填入也是一样，还是会出现连起来的情况

**Comment by zepinglee** [comment]
感觉是 citeproc-js 的 bug。我改了一下分隔符的形式就可以了（789ff02）。

**Comment by RuiDream** [comment]
> 感觉是 citeproc-js 的 bug。我改了一下分隔符的形式就可以了（ [789ff02](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/789ff0231b28db5e1fcc053d8167aa5182316a5c) ）。

解决了！！！感谢
