### ISSUE TITLE
财经研究格式，报错“CiteprocParseError: Multiple layout elements present in citation”

### ISSUE THREAD

**Issue by hyc173** [redleafnew/Chinese-STD-GB-T-7714-related-csl#215]
我在rmarkdown中使用财经研究格式csl时，出现了“CiteprocParseError: Multiple layout elements present in citation”的报错。我在试用一部分csl时也出现过这个报错，有些csl文件就能正常输出参考文献。请问这是哪一块出现了问题？该如何解决
CSL 样式：222journal-of-finance-and-economics.csl

**Comment by zepinglee** [comment]
这是 CSL-M 的 [layout 扩展](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension)，主要功能更是根据语言输出“等”或者“et al.”。可能是 Rmarkdown 不支持。
