### ISSUE TITLE
添加引用后无内容

### ISSUE THREAD

**Issue by Link-123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#216]
**描述错误**

CSL 样式：000gb-t-7714-2015-numeric-bilingual.csl

清晰简洁地描述错误是什么，预期的结果是什么。
添加引用后除了数字标注什么都没有

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141601098/b40aceec-2295-41fa-b966-ee7f6152de49)

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141601098/516bcfca-9e6b-4910-a013-51326715e974)

**条目信息**

所尝试的任何文献
``[
	{
		"id": "http://zotero.org/users/10726903/items/ITVURVLM",
		"type": "article-journal",
		"abstract": "为了深入探究七芯光子晶体光纤的传感特性,本利用有限元法研究七芯光子晶体对温度的传感特性,找到七芯光子晶体纤芯基模与包层高阶模的有效折射差与温度的关系,算出波谷波长与温度的变化关系,即理论灵敏度,并基于单模-七芯光子晶体-单模结构的马赫-曾德尔干涉结合水浴法进行温度传感实验检测。研究结果表明:七芯光子晶体光纤的理论灵敏值为-47.14 pm/℃,实验测出的灵敏度为-48.86 pm/℃。可以发现七芯光子晶体光纤对温度具有良好的线性传感特性,而且稳定性好、线性拟合度高、制作工艺简单,在海洋环境监测、生物制药和食品检测等领域具有良好的应用价值。",
		"archive_location": "6 📊",
		"container-title": "光学精密工程",
		"ISSN": "1004-924X",
		"issue": "5",
		"language": "中文;",
		"page": "951-957",
		"source": "CNKI",
		"title": "七芯光子晶体光纤温度传感器",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iy_Rpms2pqwbFRRUtoUImHcHuj-q1wNidbI4opp_cKYafGIWOCkzbh0jaPJYQwyvH&uniplatform=NZKPT",
		"volume": "29",
		"author": [
			{
				"literal": "吴根柱"
			},
			{
				"literal": "林春婷"
			},
			{
				"literal": "卢俊城"
			},
			{
				"literal": "马倩倩"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					14
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2021"
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/10726903/items/9B9KNETV",
		"type": "article-journal",
		"abstract": "During the last decade, IR MEMS thermopile detectors have become a topic of increasing interest because of their reliable characteristics and excellent cost-performance ratio. Because of their many attractive characteristics, thermopile detectors have been frequently used in various IR detection applications. In this paper, we present an overview of the recent advances on MEMS based infrared detectors. The first part deals with the IR MEMS thermopile concepts and discusses the recent state of the art of IR absorber designs, thermocouple designs, and their materials processing. The status of IR MEMS detectors performances is examined in the second part and summarized by presenting findings from the last decade. It is concluded that the latest developments in MEMS technology and thermoelectric materials offer high potential for innovative solutions to improve the IR thermopile performances.",
		"archive_location": "4 📊",
		"call-number": "4",
		"container-title": "Microsystem Technologies",
		"DOI": "10.1007/s00542-022-05306-8",
		"ISSN": "0946-7076",
		"issue": "8",
		"journalAbbreviation": "Microsyst Technol",
		"language": "en",
		"note": "number-of-pages: 14\npublisher-place: Heidelberg\npublisher: Springer Heidelberg\nWeb of Science ID: WOS:000799672100001",
		"page": "1751-1764",
		"source": "2.012 (Q3)",
		"title": "Recent advances on MEMS based Infrared Thermopile detectors",
		"URL": "https://link.springer.com/10.1007/s00542-022-05306-8",
		"volume": "28",
		"author": [
			{
				"family": "Mbarek",
				"given": "Sofiane Ben"
			},
			{
				"family": "Alcheikh",
				"given": "Nouha"
			},
			{
				"family": "Younis",
				"given": "Mohammad I."
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					25
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2022",
					8
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/10726903/items/NPRLUM27",
		"type": "thesis",
		"abstract": "温湿度是与人类紧密相联的两个环境因素,在社会生产生活中起着重要的作用。在现代工业应用中,传统的温湿度传感器已经不能满足某些特定的环境监测需求,集成传感器系统由此应运而生。集成传感器系统以大规模集成电路工艺和现代传感器为两大基础,将敏感元件、信号调理电路、微处理器以及通信接口模块等集成在一起。本文对MEMS温湿度传感器集成系统进行开发。该集成系统由温度传感器、湿度传感器、信号处理芯片等组成。本文所采用的温度传感器为MEMS微加工工艺制备的薄膜结构的铂电阻传感器,湿度传感器为三明治电容式湿度传感器。温湿度传感器与信号处理芯片被封装到一起,封装尺寸为16mm*8mm*3mm。信号调理电路能够将温度传感器的电阻量和湿度传感器的电容量转换成数字信号,实现高精度的温湿度测量。信号处理芯片通过软件控制实现温湿度测量,将测量得到的数字信号转换成实际的温湿度值,并通过IIC协议实现数据输出。同时,为了减小温度的影响,集成系统中对湿度传感器进行温度补偿,提高了湿度测试精度。为了进行实验验证,本文设计了相关测试系统。测试系统包括通信电路、双压湿度发生器以及数字温度表等。实验数据显示,该MEMS温湿度传感器集成系统湿度测量精度达到±3%RH,温度测量精度±0.5℃,吸湿响应时间2.4s,脱湿响应时间2.7s。",
		"archive_location": "14 📊",
		"genre": "硕士",
		"language": "中文;",
		"publisher": "东南大学",
		"source": "CNKI",
		"title": "MEMS温湿度传感器集成系统设计",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C475KOm_zrgu4lQARvep2SAkkyu7xrzFWukWIylgpWWcEqW7FKtoMtCsYE-Yy_9AIjQ75ErNz_PElnY8rZYfN8U2&uniplatform=NZKPT",
		"author": [
			{
				"literal": "赵敏"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					10,
					9
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2016"
				]
			]
		}
	}
]
```

**其他相关信息**

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141601098/89d7a70e-c28f-4611-8eee-bd986cc0022e)



在此处添加有关该问题的其他信息。

**Comment by Link-123** [comment]
> **描述错误**
> 
> CSL 样式：000gb-t-7714-2015-numeric-bilingual.csl
> 
> 清晰简洁地描述错误是什么，预期的结果是什么。 添加引用后除了数字标注什么都没有
> 
> **屏幕截图**
> 
> 如果必要，请添加屏幕截图以帮助解释。 ![image](https://user-images.githubusercontent.com/141601098/275514985-b40aceec-2295-41fa-b966-ee7f6152de49.png)
> 
> ![image](https://user-images.githubusercontent.com/141601098/275515515-516bcfca-9e6b-4910-a013-51326715e974.png)
> 
> **条目信息**
> 
> 所尝试的任何文献 ``[ { "id": "http://zotero.org/users/10726903/items/ITVURVLM", "type": "article-journal", "abstract": "为了深入探究七芯光子晶体光纤的传感特性,本利用有限元法研究七芯光子晶体对温度的传感特性,找到七芯光子晶体纤芯基模与包层高阶模的有效折射差与温度的关系,算出波谷波长与温度的变化关系,即理论灵敏度,并基于单模-七芯光子晶体-单模结构的马赫-曾德尔干涉结合水浴法进行温度传感实验检测。研究结果表明:七芯光子晶体光纤的理论灵敏值为-47.14 pm/℃,实验测出的灵敏度为-48.86 pm/℃。可以发现七芯光子晶体光纤对温度具有良好的线性传感特性,而且稳定性好、线性拟合度高、制作工艺简单,在海洋环境监测、生物制药和食品检测等领域具有良好的应用价值。", "archive_location": "6 📊", "container-title": "光学精密工程", "ISSN": "1004-924X", "issue": "5", "language": "中文;", "page": "951-957", "source": "CNKI", "title": "七芯光子晶体光纤温度传感器", "URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iy_Rpms2pqwbFRRUtoUImHcHuj-q1wNidbI4opp_cKYafGIWOCkzbh0jaPJYQwyvH&uniplatform=NZKPT", "volume": "29", "author": [ { "literal": "吴根柱" }, { "literal": "林春婷" }, { "literal": "卢俊城" }, { "literal": "马倩倩" } ], "accessed": { "date-parts": [ [ "2023", 9, 14 ] ] }, "issued": { "date-parts": [ [ "2021" ] ] } }, { "id": "http://zotero.org/users/10726903/items/9B9KNETV", "type": "article-journal", "abstract": "During the last decade, IR MEMS thermopile detectors have become a topic of increasing interest because of their reliable characteristics and excellent cost-performance ratio. Because of their many attractive characteristics, thermopile detectors have been frequently used in various IR detection applications. In this paper, we present an overview of the recent advances on MEMS based infrared detectors. The first part deals with the IR MEMS thermopile concepts and discusses the recent state of the art of IR absorber designs, thermocouple designs, and their materials processing. The status of IR MEMS detectors performances is examined in the second part and summarized by presenting findings from the last decade. It is concluded that the latest developments in MEMS technology and thermoelectric materials offer high potential for innovative solutions to improve the IR thermopile performances.", "archive_location": "4 📊", "call-number": "4", "container-title": "Microsystem Technologies", "DOI": "10.1007/s00542-022-05306-8", "ISSN": "0946-7076", "issue": "8", "journalAbbreviation": "Microsyst Technol", "language": "en", "note": "number-of-pages: 14\npublisher-place: Heidelberg\npublisher: Springer Heidelberg\nWeb of Science ID: WOS:000799672100001", "page": "1751-1764", "source": "2.012 (Q3)", "title": "Recent advances on MEMS based Infrared Thermopile detectors", "URL": "https://link.springer.com/10.1007/s00542-022-05306-8", "volume": "28", "author": [ { "family": "Mbarek", "given": "Sofiane Ben" }, { "family": "Alcheikh", "given": "Nouha" }, { "family": "Younis", "given": "Mohammad I." } ], "accessed": { "date-parts": [ [ "2023", 9, 25 ] ] }, "issued": { "date-parts": [ [ "2022", 8 ] ] } }, { "id": "http://zotero.org/users/10726903/items/NPRLUM27", "type": "thesis", "abstract": "温湿度是与人类紧密相联的两个环境因素,在社会生产生活中起着重要的作用。在现代工业应用中,传统的温湿度传感器已经不能满足某些特定的环境监测需求,集成传感器系统由此应运而生。集成传感器系统以大规模集成电路工艺和现代传感器为两大基础,将敏感元件、信号调理电路、微处理器以及通信接口模块等集成在一起。本文对MEMS温湿度传感器集成系统进行开发。该集成系统由温度传感器、湿度传感器、信号处理芯片等组成。本文所采用的温度传感器为MEMS微加工工艺制备的薄膜结构的铂电阻传感器,湿度传感器为三明治电容式湿度传感器。温湿度传感器与信号处理芯片被封装到一起,封装尺寸为16mm_8mm_3mm。信号调理电路能够将温度传感器的电阻量和湿度传感器的电容量转换成数字信号,实现高精度的温湿度测量。信号处理芯片通过软件控制实现温湿度测量,将测量得到的数字信号转换成实际的温湿度值,并通过IIC协议实现数据输出。同时,为了减小温度的影响,集成系统中对湿度传感器进行温度补偿,提高了湿度测试精度。为了进行实验验证,本文设计了相关测试系统。测试系统包括通信电路、双压湿度发生器以及数字温度表等。实验数据显示,该MEMS温湿度传感器集成系统湿度测量精度达到±3%RH,温度测量精度±0.5℃,吸湿响应时间2.4s,脱湿响应时间2.7s。", "archive_location": "14 📊", "genre": "硕士", "language": "中文;", "publisher": "东南大学", "source": "CNKI", "title": "MEMS温湿度传感器集成系统设计", "URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C475KOm_zrgu4lQARvep2SAkkyu7xrzFWukWIylgpWWcEqW7FKtoMtCsYE-Yy_9AIjQ75ErNz_PElnY8rZYfN8U2&uniplatform=NZKPT", "author": [ { "literal": "赵敏" } ], "accessed": { "date-parts": [ [ "2023", 10, 9 ] ] }, "issued": { "date-parts": [ [ "2016" ] ] } } ]
> 
> ```
> 
> **其他相关信息**
> 
> ![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141601098/89d7a70e-c28f-4611-8eee-bd986cc0022e)
> 
> 
> 
> 在此处添加有关该问题的其他信息。
> ```
重新提交了json
```
[
	{
		"id": "http://zotero.org/users/10726903/items/ITVURVLM",
		"type": "article-journal",
		"abstract": "为了深入探究七芯光子晶体光纤的传感特性,本利用有限元法研究七芯光子晶体对温度的传感特性,找到七芯光子晶体纤芯基模与包层高阶模的有效折射差与温度的关系,算出波谷波长与温度的变化关系,即理论灵敏度,并基于单模-七芯光子晶体-单模结构的马赫-曾德尔干涉结合水浴法进行温度传感实验检测。研究结果表明:七芯光子晶体光纤的理论灵敏值为-47.14 pm/℃,实验测出的灵敏度为-48.86 pm/℃。可以发现七芯光子晶体光纤对温度具有良好的线性传感特性,而且稳定性好、线性拟合度高、制作工艺简单,在海洋环境监测、生物制药和食品检测等领域具有良好的应用价值。",
		"archive_location": "6 📊",
		"container-title": "光学精密工程",
		"ISSN": "1004-924X",
		"issue": "5",
		"language": "中文;",
		"page": "951-957",
		"source": "CNKI",
		"title": "七芯光子晶体光纤温度传感器",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iy_Rpms2pqwbFRRUtoUImHcHuj-q1wNidbI4opp_cKYafGIWOCkzbh0jaPJYQwyvH&uniplatform=NZKPT",
		"volume": "29",
		"author": [
			{
				"literal": "吴根柱"
			},
			{
				"literal": "林春婷"
			},
			{
				"literal": "卢俊城"
			},
			{
				"literal": "马倩倩"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					14
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2021"
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/10726903/items/9B9KNETV",
		"type": "article-journal",
		"abstract": "During the last decade, IR MEMS thermopile detectors have become a topic of increasing interest because of their reliable characteristics and excellent cost-performance ratio. Because of their many attractive characteristics, thermopile detectors have been frequently used in various IR detection applications. In this paper, we present an overview of the recent advances on MEMS based infrared detectors. The first part deals with the IR MEMS thermopile concepts and discusses the recent state of the art of IR absorber designs, thermocouple designs, and their materials processing. The status of IR MEMS detectors performances is examined in the second part and summarized by presenting findings from the last decade. It is concluded that the latest developments in MEMS technology and thermoelectric materials offer high potential for innovative solutions to improve the IR thermopile performances.",
		"archive_location": "4 📊",
		"call-number": "4",
		"container-title": "Microsystem Technologies",
		"DOI": "10.1007/s00542-022-05306-8",
		"ISSN": "0946-7076",
		"issue": "8",
		"journalAbbreviation": "Microsyst Technol",
		"language": "en",
		"note": "number-of-pages: 14\npublisher-place: Heidelberg\npublisher: Springer Heidelberg\nWeb of Science ID: WOS:000799672100001",
		"page": "1751-1764",
		"source": "2.012 (Q3)",
		"title": "Recent advances on MEMS based Infrared Thermopile detectors",
		"URL": "https://link.springer.com/10.1007/s00542-022-05306-8",
		"volume": "28",
		"author": [
			{
				"family": "Mbarek",
				"given": "Sofiane Ben"
			},
			{
				"family": "Alcheikh",
				"given": "Nouha"
			},
			{
				"family": "Younis",
				"given": "Mohammad I."
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					9,
					25
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2022",
					8
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/10726903/items/NPRLUM27",
		"type": "thesis",
		"abstract": "温湿度是与人类紧密相联的两个环境因素,在社会生产生活中起着重要的作用。在现代工业应用中,传统的温湿度传感器已经不能满足某些特定的环境监测需求,集成传感器系统由此应运而生。集成传感器系统以大规模集成电路工艺和现代传感器为两大基础,将敏感元件、信号调理电路、微处理器以及通信接口模块等集成在一起。本文对MEMS温湿度传感器集成系统进行开发。该集成系统由温度传感器、湿度传感器、信号处理芯片等组成。本文所采用的温度传感器为MEMS微加工工艺制备的薄膜结构的铂电阻传感器,湿度传感器为三明治电容式湿度传感器。温湿度传感器与信号处理芯片被封装到一起,封装尺寸为16mm*8mm*3mm。信号调理电路能够将温度传感器的电阻量和湿度传感器的电容量转换成数字信号,实现高精度的温湿度测量。信号处理芯片通过软件控制实现温湿度测量,将测量得到的数字信号转换成实际的温湿度值,并通过IIC协议实现数据输出。同时,为了减小温度的影响,集成系统中对湿度传感器进行温度补偿,提高了湿度测试精度。为了进行实验验证,本文设计了相关测试系统。测试系统包括通信电路、双压湿度发生器以及数字温度表等。实验数据显示,该MEMS温湿度传感器集成系统湿度测量精度达到±3%RH,温度测量精度±0.5℃,吸湿响应时间2.4s,脱湿响应时间2.7s。",
		"archive_location": "14 📊",
		"genre": "硕士",
		"language": "中文;",
		"publisher": "东南大学",
		"source": "CNKI",
		"title": "MEMS温湿度传感器集成系统设计",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C475KOm_zrgu4lQARvep2SAkkyu7xrzFWukWIylgpWWcEqW7FKtoMtCsYE-Yy_9AIjQ75ErNz_PElnY8rZYfN8U2&uniplatform=NZKPT",
		"author": [
			{
				"literal": "赵敏"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					10,
					9
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2016"
				]
			]
		}
	}
]
```

**Comment by Link-123** [comment]
```
 ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"AOUNblI3","properties":{"formattedCitation":"\\super [1]\\nosupersub{}","plainCitation":"[1]","noteIndex":0},"citationItems":[{"id":57,"uris":["http://zotero.org/users/10726903/items/9B9KNETV"],"itemData":{"id":57,"type":"article-journal","abstract":"During the last decade, IR MEMS thermopile detectors have become a topic of increasing interest because of their reliable characteristics and excellent cost-performance ratio. Because of their many attractive characteristics, thermopile detectors have been frequently used in various IR detection applications. In this paper, we present an overview of the recent advances on MEMS based infrared detectors. The first part deals with the IR MEMS thermopile concepts and discusses the recent state of the art of IR absorber designs, thermocouple designs, and their materials processing. The status of IR MEMS detectors performances is examined in the second part and summarized by presenting findings from the last decade. It is concluded that the latest developments in MEMS technology and thermoelectric materials offer high potential for innovative solutions to improve the IR thermopile performances.","archive_location":"4 📊","call-number":"4","container-title":"Microsystem Technologies","DOI":"10.1007/s00542-022-05306-8","ISSN":"0946-7076","issue":"8","journalAbbreviation":"Microsyst Technol","language":"en","note":"number-of-pages: 14\npublisher-place: Heidelberg\npublisher: Springer Heidelberg\nWeb of Science ID: WOS:000799672100001","page":"1751-1764","source":"2.012 (Q3)","title":"Recent advances on MEMS based Infrared Thermopile detectors","URL":"https://link.springer.com/10.1007/s00542-022-05306-8","volume":"28","author":[{"family":"Mbarek","given":"Sofiane Ben"},{"family":"Alcheikh","given":"Nouha"},{"family":"Younis","given":"Mohammad I."}],"accessed":{"date-parts":[["2023",9,25]]},"issued":{"date-parts":[["2022",8]]}}}],"schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json"}
```

**Comment by zepinglee** [comment]
这个样式的引用只包括数字。参考文献表需要另外添加。
