### ISSUE TITLE
《经济研究》期刊文末参考文献遗漏

### ISSUE THREAD

**Issue by yhruc** [redleafnew/Chinese-STD-GB-T-7714-related-csl#221]
**描述错误**

开发者大大，203《经济研究》的文末参考格式好像有一点问题：英文一作的姓和名之间少了一个逗号。

**Comment by zepinglee** [comment]
确实，在 0b1a9f0 中修复。

另外我在阅读代码时候有个疑问，如果是两个英文姓名的“and”前有没有逗号（比如下面的例子）？我在期刊官网没有找到示例，你能不能从该刊最近的文章确认一下这个问题？

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/0b1a9f0831685d2ddbc8c66922a0ad40356a47a3/tests/styles/203economic-research-journal/test.md?plain=1#L48
