### ISSUE TITLE
请问如何修改华中科技大学学位论文文件来实现这种作者名格式

### ISSUE THREAD

**Issue by Youngphone** [redleafnew/Chinese-STD-GB-T-7714-related-csl#222]
作者按英文习惯写法，名在前、姓在后，名和姓均用全称，如果作者名超过两个单词，中间名使用简称，如“C.”。

**Comment by zepinglee** [comment]
> 作者按英文习惯写法，名在前、姓在后


> 名和姓均用全称，如果作者名超过两个单词，中间名使用简称，如“C.”。

**Comment by Youngphone** [comment]
> > 作者按英文习惯写法，名在前、姓在后
> 
> 这个样式本来就是名在前、姓在后的
> 
> > 名和姓均用全称
> 
> 这里加上 `initialize="false"`。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/83fe5b8de1902d437ab3b5b066743d8f28f25107/418huazhong-university-of-science-and-technology.csl#L2
> 
> > 如果作者名超过两个单词，中间名使用简称，如“C.”。
> 
> 这个实现不了。

好的，谢谢

**Comment by shandianchengzi** [comment]
> 作者按英文习惯写法，名在前、姓在后，名和姓均用全称，如果作者名超过两个单词，中间名使用简称，如“C.”。

这个最新的commit里实现了，加个initial false就行了。你也是按网安的要求在做吗？我发现好像只有网安学院的有这个要求
