### ISSUE TITLE
正文引用中想添加页码，在pages输入框中输入后，文内不显示内容，使用的是011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses

### ISSUE THREAD

**Issue by ilsjwy** [redleafnew/Chinese-STD-GB-T-7714-related-csl#224]
CSL 样式：011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses

在正文中需要添加具体的引用页码，比如小张（2022：100-130），在zotero经典视图的窗口中的pages一栏输入对应的页码时，word文档中显示不出来页码，只能自己在文档中或者editor手动输入来显示。自己研究了一下csl源文件，但是没怎么弄明白应该怎么修改显示，所以来向博主求助。

**Comment by redleafnew** [comment]
1. 现在还没有直接的办法生成Author(Year)这种形式。
2. 要在引文中显示页码需要加`locator`，可以参考能正常显示的，修改一下，添加上。
