### ISSUE TITLE
324peoples-publishing-house.csl 部分文献导出条目抓取不到期刊名

### ISSUE THREAD

**Issue by HelenS2ODS** [redleafnew/Chinese-STD-GB-T-7714-related-csl#225]
[324peoples-publishing-house.csl]人民出版社样式部分文献导出条目抓取不到期刊名，zotero内期刊名字和发行期数显示正常。
如文献白雪洁,宋培,艾阳等.中国构建自主可控现代产业体系的理论逻辑与实践路径[J].经济学家,2022(06):48-57.DOI:10.16158/j.cnki.51-1312/f.2022.06.008.，zotero导出参考文献后为：
白雪洁、宋培、艾阳、李琳：《中国构建自主可控现代产业体系的理论逻辑与实践路径》，2022年版。

**Comment by redleafnew** [comment]
请将条目JSON格式上传。

**Comment by HelenS2ODS** [comment]
> 请将条目JSON格式上传。

[
	{
		"id": "http://zotero.org/users/local/WIPBamYM/items/QV4GDVE5",
		"type": "article-journal",
		"abstract": "本文首先立足新阶段—新理念—新格局的社会主义现代化国家建设总体目标，对自主可控的现代产业体系进行具有中国特色的概念界定与内涵丰富，接着采用系统论方法构建包含“要素—主体—结构—制度环境”四个层次的理论逻辑，梳理出我国产业体系发展面临“有创新，无精尖”“有要素，弱协同“”有主体，缺活力“”有产业，少融合“”促开放，需调整“”推改革，要深化”等瓶颈制约，最后从构筑能发挥创新驱动“定力”的重点产业关键核心技术自主可控的产业技术体系、培育“链主”企业的价值链“控制力”，构建“以我为主”的价值链体系、建立提升体系“协同力”的全方位协同融合发展机制、完善释放改革“动力”的制度政策环境四个方面为我国构建自主可控的现代产业体系提供实践路径。",
		"archive_location": "CNKI",
		"call-number": "51-1312/F",
		"container-title": "经济学家",
		"issue": "06",
		"language": "zh",
		"note": "ISBN: 1003-5656\ntype: 10.16158/j.cnki.51-1312/f.2022.06.008",
		"page": "48-57",
		"title": "中国构建自主可控现代产业体系的理论逻辑与实践路径",
		"author": [
			{
				"family": "白雪洁",
				"given": ""
			},
			{
				"family": "宋培",
				"given": ""
			},
			{
				"family": "艾阳",
				"given": ""
			},
			{
				"family": "李琳",
				"given": ""
			}
		],
		"issued": {
			"date-parts": [
				[
					"2022"
				]
			]
		}
	}
]

**Comment by zepinglee** [comment]
不要在 `note` 中写 `type: 10.16158/j.cnki.51-1312/f.2022.06.008`，会被当成 `10.16158/j.cnki.51-1312/f.2022.06.008` 类型而不是 `article-journal`.

**Comment by HelenS2ODS** [comment]
多谢，删了type后导出正常了
