### ISSUE TITLE
华中科技大学中文引文出现错误

### ISSUE THREAD

**Issue by cyxnxd** [redleafnew/Chinese-STD-GB-T-7714-related-csl#226]
描述错误
CSL 样式：418huazhong-university-of-science-and-technology.csl  
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/151513084/8d273b2c-b664-4ec5-9505-486c6d54b38d)
中文期刊引文出现错误，6人以上应该写“等”，而不是“et al”（标红的地方）

条目信息

[导出的条目.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/13412954/default.json)

**Comment by zepinglee** [comment]
按照模板填写。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by redleafnew** [comment]
将条目语言设置为：zh-CN
