### ISSUE TITLE
Zotero导入错误

### ISSUE THREAD

**Issue by cdsjdk** [redleafnew/Chinese-STD-GB-T-7714-related-csl#227]
**试了不同的csl，都没有导入成功**
Zotero版本6.0.30
CSL 样式：438xi-an-jiaotong-university.csl
000gb-t-7714-2015-numeric-bilingual.csl

错误提醒：
An unexpected error occurred while installing "/home/abc/Downloads/438xi-an-jiaotong-university.csl"
An unexpected error occurred while installing "/home/abc/Downloads/000gb-t-7714-2015-numeric-bilingual.csl"

**Comment by zepinglee** [comment]
无法复现你的问题。
