### ISSUE TITLE
法学引注手册bug

### ISSUE THREAD

**Issue by hunanchenhunanchen** [redleafnew/Chinese-STD-GB-T-7714-related-csl#228]
**描述错误**

CSL 样式：[306manual-of-legal-citation-multi-lingual-no-ibid.csl]

清晰简洁地描述错误是什么，预期的结果是什么。

正文引注处和脚注处的数字字体是新罗马，希望改成宋体，因为新罗马无法和六角括号配合，宋体却可以，想求宋体数字的引注文件，还有就是想求一个数字序号分别是六角括号、[]、①的引注文件，或者教教我们怎么搞，求求了，祝您长生不老

**屏幕截图**
![Uploa
![引注](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/148081528/7d8e2bb7-5774-4347-b921-e99e378280b8)
ding 引注.png…]()

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by hunanchenhunanchen** [comment]
![Uploading 引注.png…]()

**Comment by redleafnew** [comment]
csl文件中应该没有规定字体，可以在word中设置。

**Comment by zepinglee** [comment]
1. 那个字体叫 Times 不叫新罗马。
2. CSL 不控制具体的字体。可以在 Word 的 style sheet 将默认的西文字体改为需要的。
3. 序号脸变的括号可以修改这行，但是圈码在 CSL 中实现不了。
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/83fe5b8de1902d437ab3b5b066743d8f28f25107/306manual-of-legal-citation-multi-lingual-no-ibid.csl#L1667C46-L1667C47
