### ISSUE TITLE
西工大硕士论文格式

### ISSUE THREAD

**Issue by lpf2215** [redleafnew/Chinese-STD-GB-T-7714-related-csl#229]
申请添加西北工业大学的参考文献格式
可参考：https://gitee.com/lpf1754/npu_reference.git

**Comment by redleafnew** [comment]
https://www.zotero.org/groups/4677213/chinese_csl_development  群组中搜索不到 LPF1754
另外，与仓库中哪个最接近，方便修改。

**Comment by zepinglee** [comment]
有没有英文文献的示例？主要是确定英文的姓是否全大写。

003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl 可以基本满足需求，可以不必录入测试文献了。其中专利、标准、条例的格式需要再调整一下。

**Comment by redleafnew** [comment]
那就方便了

**Comment by lpf2215** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/93112729/ec49f2b2-9df1-4ab1-976e-88ef137b880a)
这是英文参考文献的截图，姓是全大写的。
 已加入群组。

**Comment by redleafnew** [comment]
例子中姓大小写这好像都不统一

**Comment by zepinglee** [comment]
> 例子中姓大小写这好像都不统一

这是是统一的保持原大小写。

在 002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl 的基础上修改即可。

**Comment by lpf2215** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/93112729/fb0968a7-9448-4a60-8dd0-aba7970eb2d3)
姓的首字母大写，名只有大写的首字母

**Comment by redleafnew** [comment]
> 有没有英文文献的示例？主要是确定英文的姓是否全大写。
> 
> 003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl 可以基本满足需求，可以不必录入测试文献了。其中专利、标准、条例的格式需要再调整一下。

把专利、标准等需要调整的条目上传一下？

**Comment by lpf2215** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/93112729/9b78a9f3-efa8-451f-b7d9-cb0b532813c2)
这是专利和标准的模板

**Comment by redleafnew** [comment]
不要模板，要具体的条目。

**Comment by zepinglee** [comment]
这几篇文献经常出现在别的样式示例中，数据库中已经有，拷贝一下就行。

我晚些时候处理吧。

**Comment by zepinglee** [comment]
在 e838be1 中添加。

@lpf2215 看看有没有格式问题。

**Comment by redleafnew** [comment]
这么迅速，点赞

**Comment by zepinglee** [comment]
> 中英文期刊的参考文献格式无问题，但是换行后对齐有点小问题

这个需要在 Word 中设置悬挂缩进，并且将“制表符”设成相同的宽度。
