### ISSUE TITLE
1gb-t-7714-2015-numeric-no-date-url文献名重复

### ISSUE THREAD

**Issue by DaMiBear** [redleafnew/Chinese-STD-GB-T-7714-related-csl#23]
导入`1gb-t-7714-2015-numeric-no-date-url`csl文件后，创建印文目录的生成的文献引用格式会包含两个文件名,比如下面这样，使用`20gb-t-7714-2015-numeric-bilingual-lower-name-prefer-nodoi.csl`就没用这个问题。新手刚刚接触，难道是我错误使用了么？

> [2] 吴雨霏. 基于剪枝的深度神经网络性能优化与应用基于剪枝的深度神经网络性能优化与应用[D]. 上海交通大学, 2020.
> [25] Mujahid A, Awan M J, Yasin A, et al. Real-Time Hand Gesture Recognition Based on Deep Learning YOLOv3 ModelReal-Time Hand Gesture Recognition Based on Deep Learning YOLOv3 Model[J]. Applied Sciences, 2021, 11(9): 4164.

**Comment by zepinglee** [comment]
Bug, 这里重复了。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/45e6afceaa45bb3d3eb5949d4dba77d9bf9b390f/1gb-t-7714-2015-numeric-no-date-url.csl#L177-L178

这个仓库里所有的文件都是在国标的基础上有所修改，建议先确定你所需要的格式再选择 `.csl`。

**Comment by DaMiBear** [comment]
好的，非常感谢！

**Comment by redleafnew** [comment]
@DaMiBear 修复了一下，看看还有问题吗？

**Comment by DaMiBear** [comment]
没问题了！: D
