### ISSUE TITLE
请问目前能通过修改CSL实现直接引用和间接引用混排么？

### ISSUE THREAD

**Issue by yanyu2015** [redleafnew/Chinese-STD-GB-T-7714-related-csl#232]
由于很多时候需要采用author(year) 或者作者等[1]的格式，请问这个能通过修改CSL格式实现嘛？目前我看到的都是使用zotero的classic view 然后omitted author再手动添加author信息的方法。

**Comment by zepinglee** [comment]
citeproc-js 其实有 `"mode": "composite"`，但是目前 Zotero Word 插件没有对应的接口。
