### ISSUE TITLE
426北京林业大学的样式引用的时候少了最后的点，且学校引用样式更改成顺序编码制，目前这版不适用了

### ISSUE THREAD

**Issue by zhoumiao0130** [redleafnew/Chinese-STD-GB-T-7714-related-csl#235]
**描述错误**

CSL 样式：426beijing-forestry-university.csl

下载之后的引用，每一条末尾都缺少了一个“.”

**屏幕截图**
下载之后的引用，每一条末尾都缺少了一个“.”
![屏幕截图 2023-12-03 205041](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/152787526/80fa27bb-014b-4d09-8240-862da0356b8d)
这个是学校的参考样式
![屏幕截图 2023-12-03 205057](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/152787526/84e597fd-10c4-47f0-b47f-d456be7bf211)

**Comment by zhoumiao0130** [comment]
刚刚去学校官网上看，发现学校刚更新了引用方式，我发的图片是旧版的，以前是作者年份法，今年11月份的新文件改成了顺序编码法。这个是新版的网址，在附件里边写了。
http://graduate.bjfu.edu.cn/xwgl/xwlw/349457.html

**Comment by redleafnew** [comment]
这个要求与https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl#002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doicsl 有无差别？
