### ISSUE TITLE
求助湖南师范大学参考文献样式

### ISSUE THREAD

**Issue by fq8550046** [redleafnew/Chinese-STD-GB-T-7714-related-csl#239]
**样式信息**

- 期刊/学校名称：湖南师范大学

- 英文名称：Hunan Normal University

- 参考文献格式要求的**官网**链接[例如 <extension://emelgiiiemoiljnmikcgbmjkapalgcme/assets/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fyjsy.hunnu.edu.cn%2F__local%2F3%2F04%2F8A%2F26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf>]官网链接找不到了，详情见这个文档内容。

**测试条目**

**其他样式信息**
① 作者姓名采用“姓在前名在后”原则，具体格式是：姓，
名字的首字母. 如： Malcolm Richard Cowley 应为：Cowley,
M.R.，如果有两位作者，第一位作者方式不变，&之后第二
位作者名字的首字母放在前面，姓放在后面，如：Frank Norris
与 Irving Gordon 应为：Norris, F. & I.Gordon.；

Edited: <https://yjsy.hunnu.edu.cn/__local/3/04/8A/26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf>

**Comment by redleafnew** [comment]
按照新issue要求提供信息，如Zotero ID，测试条目等。
另外，学校样式要求与仓库中哪个最接近。

**Comment by fq8550046** [comment]
Zotero ID:liliLiya 请问如何赋予编辑权限
我我不太清楚和哪个最接近

**Comment by zepinglee** [comment]
@fq8550046 再发一遍格式要求的链接？目前的打不开。

已经提升为 admin 权限。将格式要求的示例文献录入 Zotero 种，方便我们测试对比。

<img width="913" alt="Screenshot 2023-12-22 at 22 36 41" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/70149100-ff01-45b6-9c26-2d15bb720e5b">

**Comment by fq8550046** [comment]
复制链接，粘贴在浏览器时可以被直接打开为pdf的：extension://emelgiiiemoiljnmikcgbmjkapalgcme/assets/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fyjsy.hunnu.edu.cn%2F__local%2F3%2F04%2F8A%2F26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf
马上录入文献

**Comment by fq8550046** [comment]
和GB7714-1987格式差不多，不一样的有（下面粘贴的时湖师大的要求，括号里面的是与GB-1897的不一样的地方）：
④ 论文集
【格式】[序号]作者.篇名[C].出版地：出版者，出版年份：起始页码.（不要，论文集名）
　⑤ 学位论文
【格式】[序号]作者.篇名[D].出版地：保存者，出版年份：起始页码.（多了起始页码）
⑥ 研究报告
【格式】[序号]作者.篇名[R].出版地：出版者，出版年份：起始页码.（多了起始页码）
⑧ 标准
【格式】[序号]标准编号，标准名称[S].（不要，出版地：出版者，出版年.）
⑨ 条例
【格式】[序号]颁布单位.条例名称.发布日期（GB中没有，但一般用不到吧）

其他
1.各种未定义类型的文献
【格式】[序号] 主要责任者.文献题名[Z].出版地：出版
者, 出版年.
2.（1） 作者姓名采用“姓在前名在后”原则，具体格式是：姓，
名字的首字母.如： Malcolm Richard Cowley 应为：Cowley， M.R.，如果有两位作者，第一位作者方式不变，&之后第二
位作者名字的首字母放在前面，姓放在后面，如：Frank Norris与 Irving Gordon 应为：Norris，F. & I.Gordon.;

有些文献我在浏览器中搜索不到。

**Comment by zepinglee** [comment]
> 复制链接，粘贴在浏览器时可以被直接打开为pdf的：extension://emelgiiiemoiljnmikcgbmjkapalgcme/assets/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fyjsy.hunnu.edu.cn%2F__local%2F3%2F04%2F8A%2F26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf 马上录入文献

URL 不带 `extension://` 前缀的。把后面的再发一遍。

**Comment by zepinglee** [comment]
> 有些文献我在浏览器中搜索不到。

手动录入。

<img width="380" alt="Screenshot 2023-12-23 at 10 03 50" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/846029a0-a6e3-48c6-ba36-b43ffdb0c726">

**Comment by zepinglee** [comment]
> 复制链接，粘贴在浏览器时可以被直接打开为pdf的：extension://emelgiiiemoiljnmikcgbmjkapalgcme/assets/pdf-viewer/web/viewer.html?file=https%3A%2F%2Fyjsy.hunnu.edu.cn%2F__local%2F3%2F04%2F8A%2F26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf 马上录入文献

非得让我自己手动把里面的 `%2F` 替换成 `/`：<https://yjsy.hunnu.edu.cn/__local/3/04/8A/26688DAF90A1EDD477ADBE21D15_88680BF7_56B1F.pdf>。

在 ceef15e 中添加了样式，测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/464hunan-normal-university/test.md>，只测试了已录入的文献。

**Comment by fq8550046** [comment]
不好意思、才刚看到。测试结果很不错，十分感谢。接下来，我应该如何把代码放入zotero，用这个参考文献格式呢

**Comment by redleafnew** [comment]
看readme，上面有说明

**Comment by fq8550046** [comment]
哇，太棒了，谢谢大佬。

**Comment by redleafnew** [comment]
这个完成了吧

**Comment by fq8550046** [comment]
大佬，请问参考文献正文如何把作者+年份，改成数字上标呢

**Comment by zepinglee** [comment]
这个样式本来就是数字上标，见测试效果。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/91d7d0ee0b807e3a0ef812d593cc05fdc2c5e382/tests/styles/464hunan-normal-university/test.md?plain=1#L34-L41
