### ISSUE TITLE
华南农业大学毕业论文样式添加

### ISSUE THREAD

**Issue by WenHZhang** [redleafnew/Chinese-STD-GB-T-7714-related-csl#240]
**样式信息**

- 期刊/学校名称：华南农业大学本科学位论文

- 英文名称：South China Agricultural University

- 参考文献格式要求的**官网**链接
- [无链接]
参考文献按照作者姓氏的汉语拼音或者英文字母升序排列，首先是中文，然后是英文。
参考文献采用“著者－出版年”制.
        引用同一作者在同一年出版的多篇文献时，出版年后加一小写字母a、b、c等以示区别。3人和3人以下作者全部列出，3人以上作者只列前3人，后写“等”（中文文献适用）或“et al.” （英文文献适用）字。
        期刊类文献著录格式 作者.题名[J].期刊名(外文可缩写，并省略缩写点)，出版年，卷号(期号)：起止页码.如期刊无卷号，则为：“出版年，(期号)：起止页码.”。
        专著类文献著录格式 作者.书名[M].其他责任者.版次(第1版不标注).出版地：出版者，出版年:起止页码。
        论文集类文献著录格式 论文作者.论文题目[A]//编者.论文集名[C]：其他题名信息.出版地（或会议城市）：出版者，出版年:起止页码。
        学位论文类著录格式 作者.题名[D].保存地点（城市）：保存单位，年份。
        科技报告著录格式 作者.题名[R].地点（城市）：主办单位，年份。
        专利文献著录格式 专利申请者或所有者[P].题名：专利国别，专利号.公告日 期或公开日期［引用日期］.获取和访问路径（联机文献必备）。
        网络文献著录格式 作者.题名［EB/OL］.出版地：出版者，出版年(更新日期)［引用日期］.获取和访问路径。
        其他凡上面没有规定的其他类型参考文献，按照中华人民共和国国家标准GB/T7714-2005执行。

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID: wenhuizhang2020

**其他样式信息**
英文期刊文中引文样式
(BESADA-PORTAS, E, de la TORRE, L and JESUS, M, et al.,2010)
英文期刊尾注/脚注样式
Eva Besada-Portas, de la Torre Luis, Jesus M., et al. 2010. Evolutionary trajectory planner for multiple {UAVs} in realistic scenarios. IEEE Transactions on Robotics. 26(4): 619-634.

中文期刊文中引文样式
(张鹏，王桂玲，徐学辉,2013)
中文期刊尾注/脚注样式
张鹏，王桂玲，徐学辉. 2013. 云计算环境下适于工作流的数据布局方法. 计算机研究与发展. 50(3): 636-647.

会议文中引文样式
[于海洋，温凌云，韩丹，2010]
会议尾注/脚注样式
[1] 于海洋，温凌云，韩丹. 关于建设地方特色文化资源数据库的思考与建议--以江西省图书馆为例. 南昌: 20101-3.

学位论文文中引文样式
(任瑞,2011)
学位论文尾注/脚注样式
任瑞. 2011. 逐步I型删失数据下的一些统计推断问题的研究. 南京师范大学.

书文中引文样式
(余秋雨, 2007)
书尾注/脚注样式
余秋雨.(2007). 余秋雨人生哲言.: 上海人民出版社.

似乎与gb-t-7714-2005-author-date更为相似。

**Comment by redleafnew** [comment]
已经是管理权限，可以将示例中的条目录入到群组中。
另与 7714 2015有什么区别，请详细列出，以方便修改。

**Comment by zepinglee** [comment]
@WenHZhang 已设为 admin 权限。
<img width="914" alt="Screenshot 2023-12-28 at 13 19 18" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/94149699-e83f-4f41-947a-de1f974e411d">

学校官网没有链接吗？是不是这个 <https://yjsy.scau.edu.cn/_upload/article/files/8f/60/ad6c68bc4c8181e8fa46982ced10/1d8619e0-908f-4a3b-bbef-5b772ca1c6ba.docx>？

另外你提供的格式要求和示例文献不完全一致，比如是否有文献类型标识。还有 citation 中的姓要全大写，而参考文献表中的姓不需要处理？这比较少见，建议将该格式要求的文档传上来。

那个应该叫“参考文献表”（bibliography/refernces）不是“尾注/脚注”。

**Comment by WenHZhang** [comment]
[2016毕业论文撰写规范(1).docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/13785032/2016.1.docx)
格式要求文档已上传。

参考文献列表原问题中的参考文献列表复制ne中的格式复制错了，以下为更正示例：
【英文期刊】
文中引文样式
(Hashem, Yaqoob and Anuar et al., 2015)
bibliography/refernces
Hashem I A T, Yaqoob I, Anuar N B, et al. The rise of “big data” on cloud computing: review and open research issues[J]. Inf. Syst., 2015,47(0):98-115.
【中文期刊】
文中引文样式
(李昕龙，张玲，李坤等, 2013)
bibliography/refernces
李昕龙, 张玲, 李坤, 等. 面向物联网传感器信息的数据分配策略[J]. 计算机研究与发展, 2013,50(z1):297-305.
【会议】
文中引文样式
(李欣荣, 2008)
bibliography/refernces
李欣荣. 图书馆数据储存的选择——NAS-SAN存储技术: 2008年文献影像技术的发展与应用学术研讨会, 天津, 2008[C].
【学位论文】
文中引文样式
(任瑞, 2011)
bibliography/refernces
任瑞. 逐步I型删失数据下的一些统计推断问题的研究[D]. 南京师范大学, 2011.
【书】
文中引文样式
(余秋雨, 2007)
bibliography/refernces
余秋雨. 余秋雨人生哲言[M]. 上海人民出版社, 2007:316.

与gb-t-7714-2005-author-date的主要区别应该在于：
（1）正文中的引文标注
参考文献采用“著者－出版年”制.引用同一作者在同一年出版的多篇文献时，出版年后加一小写字母a、b、c等以示区别。3人和3人以下作者全部列出，3人以上作者只列前3人，后写“等”（中文文献适用）或“et al.” （英文文献适用）字。

（2）参考文献列表
参考文献按照作者姓氏的汉语拼音或者英文字母升序排列，首先是中文，然后是英文。

示例中的条目已录入到群组中。

**Comment by zepinglee** [comment]
官网链接：<https://jwc.scau.edu.cn/2016/0331/c5197a147427/page.htm>，随便搜一下就能搜出来。

**Comment by zepinglee** [comment]
f81425d 添加了该样式，测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/465south-china-agricultural-university/test.md>。

> 【英文期刊】 文中引文样式 (Hashem, Yaqoob and Anuar et al., 2015) bibliography/refernces Hashem I A T, Yaqoob I, Anuar N B, et al. The rise of “big data” on cloud computing: review and open research issues[J]. Inf. Syst., 2015,47(0):98-115. 

这些示例文献是在哪里找到的？似乎官方的《华南农业大学本科生毕业论文(设计)撰写规范》并没有这些示例。

另外需要确认一下，文中的引用也是“3人和3人以下作者全部列出”吗？在我看来，“3人和3人以下作者全部列出，3人以上 作者只列前3人，后写“等”(中文文献适用)或“et al.” (英文文献适用)字。”是描述文后的参考文献表的。理由如下：

1. 原 GB/T 7714—2005 中只标注第一著者。
2. 我了解的国内外“著者-出版年”制体例的 citation 之多标注两位作者。
3. 《华南农业大学本科生毕业论文(设计)撰写规范》第5 页的示例中略写为一位作者加“等”（“曾德超等”）。
<img width="760" alt="Screenshot 2023-12-29 at 11 17 22" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/3b2beee2-29ba-4779-8997-390dc2cdbc3a">

**Comment by WenHZhang** [comment]
> [f81425d](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/f81425db8d8748c0b7d903adef064c3c45480f9f) 添加了该样式，测试效果见 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/465south-china-agricultural-university/test.md。
> 
> > 【英文期刊】 文中引文样式 (Hashem, Yaqoob and Anuar et al., 2015) bibliography/refernces Hashem I A T, Yaqoob I, Anuar N B, et al. The rise of “big data” on cloud computing: review and open research issues[J]. Inf. Syst., 2015,47(0):98-115.
> 
> @WenHZhang 这些示例文献是在哪里找到的？似乎官方的《华南农业大学本科生毕业论文(设计)撰写规范》并没有这些示例。
> 
> 另外需要确认一下，文中的引用也是“3人和3人以下作者全部列出”吗？在我看来，“3人和3人以下作者全部列出，3人以上 作者只列前3人，后写“等”(中文文献适用)或“et al.” (英文文献适用)字。”是描述文后的参考文献表的。理由如下：
> 
> 1. 原 GB/T 7714—2005 中只标注第一著者。
> 2. 我了解的国内外“著者-出版年”制体例的 citation 之多标注两位作者。
> 3. 《华南农业大学本科生毕业论文(设计)撰写规范》第5 页的示例中略写为一位作者加“等”（“曾德超等”）。
> 
> <img alt="Screenshot 2023-12-29 at 11 17 22" width="760" src="https://private-user-images.githubusercontent.com/12290822/293304290-3b2beee2-29ba-4779-8997-390dc2cdbc3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjI0NDgsIm5iZiI6MTcwMzgyMjE0OCwicGF0aCI6Ii8xMjI5MDgyMi8yOTMzMDQyOTAtM2IyYmVlZTItMjliYS00Nzc5LTg5OTctMzkwZGMyY2RiYzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzNTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYzRlMGMzMGJlNTY4MmQ2ZGE3ZGZhY2Y1MGU4MGM2MzM0MTkwMTM2ODAzMmNlNzA0MTczYTgzYzY2MWQ3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILhAkRY2GJHPyxYaSlQNVRyQzI2CNlplKx-k6UC63CM">

官方文件中似乎未提供完整的示例，以上示例是我使用学校集团版的noteexpress提供的nes文件生成的。

在该nes文件中，正文引用同样是设置为“如作者3人以上，则列出前3人”，参考文献列表中全部作者列出。

测试效果除上述困惑外，未见异常，感谢您！

**Comment by zepinglee** [comment]
> 官方文件中似乎未提供完整的示例，以上示例是我使用学校集团版的noteexpress提供的nes文件生成的。

这个 noteexpress 有没有官方链接？

> 在该nes文件中，正文引用同样是设置为“如作者3人以上，则列出前3人”，参考文献列表中全部作者列出。

那我还是按照这个格式修改一下吧。

另外还有一点，学校格式的出版年在后，而目前的 CSL 样式跟国标一样出版年在前。稍后一并修改。
<img width="736" alt="Screenshot 2023-12-29 at 12 49 26" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/8a900eeb-e05d-4261-9f82-bf4c409bf062">
<img width="867" alt="Screenshot 2023-12-29 at 12 51 07" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/68f8f3c1-8aa5-4f04-abeb-d4e280499e3b">

**Comment by WenHZhang** [comment]
> > 官方文件中似乎未提供完整的示例，以上示例是我使用学校集团版的noteexpress提供的nes文件生成的。
> 
> 这个 noteexpress 有没有官方链接？
> 
> > 在该nes文件中，正文引用同样是设置为“如作者3人以上，则列出前3人”，参考文献列表中全部作者列出。
> 
> 那我还是按照这个格式修改一下吧。
> 
> 另外还有一点，学校格式的出版年在后，而目前的 CSL 样式跟国标一样出版年在前。稍后一并修改。
> 
> 学校： <img alt="Screenshot 2023-12-29 at 12 49 26" width="736" src="https://private-user-images.githubusercontent.com/12290822/293311044-8a900eeb-e05d-4261-9f82-bf4c409bf062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MjYzODAsIm5iZiI6MTcwMzgyNjA4MCwicGF0aCI6Ii8xMjI5MDgyMi8yOTMzMTEwNDQtOGE5MDBlZWItZTA1ZC00MjYxLTlmODItYmY0YzQwOWJmMDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA1MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ODBkN2IyY2VlNDAzYTMxNTQ5ZmI0YThhNzY2ZmYxNzVjMDNjODJhNmUzM2RkNzlhNzJjMTU0ODIzNzFkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvAaCvXgGYmn0_8Pa1_XDcMCuhlLqoCZeNqlDgn_eAo">
> 
> 国标： <img alt="Screenshot 2023-12-29 at 12 51 07" width="867" src="https://private-user-images.githubusercontent.com/12290822/293311048-68f8f3c1-8aa5-4f04-abeb-d4e280499e3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MjYzODAsIm5iZiI6MTcwMzgyNjA4MCwicGF0aCI6Ii8xMjI5MDgyMi8yOTMzMTEwNDgtNjhmOGYzYzEtOGFhNS00ZjA0LWFiZWItZDRlMjgwNDk5ZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA1MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MGI2NzExODY5NjM1NGQyM2FhNmRhMzFiYTllNjQ2MmI5MzcwMzZjYmMxMmEwNjE0Zjg5OTMxN2I5YzUxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vK4KCZXgTWRC7R8mi4SZs3rEHl3-xnOrGOyeCXLxoQg">

该版本noteexpress的下载链接：https://lib.scau.edu.cn/2020/0218/c14674a247972/page.htm

再次感谢！

**Comment by zepinglee** [comment]
在 04eab6f 和 dbfee7c 中修正。

**Comment by WenHZhang** [comment]
> 在 [04eab6f](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/04eab6f94f10cdb4c26a5bb980a618707df12868) 和 [dbfee7c](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/dbfee7c87c7e088c7b5e198146ff71eaf9cc88bc) 中修正。

这一版本已测试，未见问题。

再次感谢您二位！

**Comment by redleafnew** [comment]
如果可以了请关闭此issue

**Comment by WenHZhang** [comment]
> 如果可以了请关闭此issue

不好意思，忘了，再次感谢二位！
