### ISSUE TITLE
中国农业大学硕博论文样式请求

### ISSUE THREAD

**Issue by qyx99** [redleafnew/Chinese-STD-GB-T-7714-related-csl#241]
**样式信息**

- 学校名称：中国农业大学研究生学位论文

- 英文名称：China agriculture University
[附件：中国农业大学研究生学位论文格式及书写规范（2019年修订）（研生[2019]10号）.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/13784403/2019.2019.10.pdf)

- 参考文献格式要求的**官网**链接

- （期刊的）ISSN 号：
- （期刊的）相关领域：

**测试条目**

加入 Zotero 群组 [Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)，提供 Zotero ID，赋予编辑权限后，将全部**期刊/学校官网的示例文献**录入 Zotero 并拖动到群组中，方便测试 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
Zotero ID请提供。
以前好像有人提过。
需要配合测试。

**Comment by qyx99** [comment]
感谢回复，Zotero ID：gyq1

**Comment by zepinglee** [comment]
@qyx99 自然科学版还是社会科学类型？

这个样式跟 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 非常接近，主要是标注和专利需要修改，所以不必录入示例文献测试了。

另外需要确认一下，作者是要全部列出吗？

**Comment by qyx99** [comment]
您好，应该是自然科学版，作者需要全部列出。谢谢！

**Comment by zepinglee** [comment]
在 edc1b15 中添加。测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/main/tests/styles/466china-agriculture-university-natural-science>。

**Comment by qyx99** [comment]
好的，非常感谢Thanks♪(･ω･)ﾉ

**Comment by redleafnew** [comment]
还有需要修改的吗？

**Comment by qyx99** [comment]
您好，我现在看着没有什么要修改的，非常感谢🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月31日 19:46 |
| 收件人 | redleafnew/Chinese-STD-GB-T-7714-related-csl ***@***.***> |
| 抄送人 | qyx99 ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 中国农业大学硕博论文样式请求 (Issue #241) |

还有需要修改的吗？
