### ISSUE TITLE
求助，如何将论文正文的引用（作者+年份）改成数字上标，以湖南师范大学的参考文献样式为例

### ISSUE THREAD

**Issue by fq8550046** [redleafnew/Chinese-STD-GB-T-7714-related-csl#243]
**描述错误**

CSL 样式：xxx-xxx-xxx.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by fq8550046** [comment]
如，将Fraser (1981)改成国外学者[1] 可以直接通过修改湖南师范大学.csl样式来实现吗

**Comment by redleafnew** [comment]
学校要求到底是什么样子的，这是两个完全不同的类型。

**Comment by fq8550046** [comment]
![参考文献表](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/112161740/ef26b699-ffa7-4f91-924b-6bb70f571b61)
想请教下图片中的上标是怎么自动设置的

**Comment by redleafnew** [comment]
有的数字样式是上标的。样式规定的。

**Comment by fq8550046** [comment]
clsy样式么，能烦请修改下吗。刚弄了好久不会~~~

**Comment by fq8550046** [comment]
我发现了如果引用在后面，可以自动变成上标的形式。

**Comment by zepinglee** [comment]
@fq8550046 你的具体需求是什么？

[464hunan-normal-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/464hunan-normal-university.csl) 本来就是顺序编码制。

如果你想了解 CSL 代码中顺序编码与著者-出版年的差异，可以比较 [001gb-t-7714-2015-author-date-bilingual.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/001gb-t-7714-2015-author-date-bilingual.csl) 和 [000gb-t-7714-2015-numeric-bilingual.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/000gb-t-7714-2015-numeric-bilingual.csl)。

<img width="1145" alt="Screenshot 2023-12-31 at 11 37 50" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/ad8d55dd-db38-440b-a2ee-6a3cc794cb44">
