### ISSUE TITLE
中国农业大学学报 论文样式请求

### ISSUE THREAD

**Issue by treasure-lxl** [redleafnew/Chinese-STD-GB-T-7714-related-csl#244]
**样式信息**

- 期刊/学校名称：中国农业大学学报

- 英文名称：Journal of China Agricultural University 

- 参考文献格式：
[jcau投稿模板2024.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/13809941/jcau.2024.pdf)
- 参考文献格式下载地址：
<http://zgnydxxb.ijournals.cn/zgnydxxb/ch/first_menu.aspx?parent_id=20161229035248001>
- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:Treasurelxl

**其他样式信息**

**Comment by zepinglee** [comment]
这个格式跟 GB/T 7714 非常接近，不必录入测试文献了。

**Comment by zepinglee** [comment]
在 13e90c0 中添加：

1. CSL 无法在英文翻译前换行，需要手动将 `; ` 替换为换行。
2. 英文翻译的数据录入方式参照 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/7SP7XX8X/items/36XBJUA8/collection>。

<img width="346" alt="Screenshot 2024-01-04 at 18 30 36" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/98233aa3-484a-480b-b2a8-2ea069da4782">
