### ISSUE TITLE
申请添加气象学报英文版Journal of Meteorological Research样式

### ISSUE THREAD

**Issue by kk-sci** [redleafnew/Chinese-STD-GB-T-7714-related-csl#245]
- 期刊/学校名称：气象学报英文版

- 英文名称：Journal of Meteorological Research

- 参考文献格式：http://jmr.cmsjournal.net/author_guide

- （期刊）相关领域：geology

Zotero ID: txwlkk

**其他样式信息**
1.申请样式与Zotero样式编辑器中可以搜索到的American Meteorological Society样式非常接近
2.英文文献的第一作者姓在前（后加“, ”）、名在后（全部用缩写，即首字母加“.”），其余作者则名在前、姓在后。
3.参考文献的通用格式：作者名+逗号+年份+冒号+题目+句号+刊物名（斜体）+逗号+卷号（黑体）+逗号+页码+句号
4.同一作者的不同文章，按照年代排序。（注意：第一作者姓名不再使用“——”代替）

**Comment by zepinglee** [comment]
我检查了一下，似乎只有“第一作者姓名不再使用“——”代替”这一点差异。

**Comment by zepinglee** [comment]
还有 `and coauthors` => `et al.`。

在 0e1f16c 中添加了该 CSL 样式，在 American Meteorological Society 基础上修改了以上两点。你可以先用着，有什么格式问题再反馈修改。如果要严格一些的话，可以将全部示例文献录入 Zotero 群组供我们测试（已提升为 admin 权限）。

<img width="869" alt="Screenshot 2024-01-04 at 21 45 11" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/35ab42a9-25b4-4797-98c6-6d135f58c59e">

**Comment by kk-sci** [comment]
好的，非常感谢！！
















在 2024-01-04 21:45:57，"Zeping Lee" ***@***.***> 写道：

还有 and coauthors => et al.。

在 0e1f16c 中添加了该 CSL 样式，在 American Meteorological Society 基础上修改了以上两点。你可以先用着，有什么格式问题再反馈修改。如果要严格一些的话，可以将全部示例文献录入 Zotero 群组供我们测试（已提升为 admin 权限）。

Screenshot.2024-01-04.at.21.45.11.png (view on web)
