### ISSUE TITLE
插入美国专利时，输出的国家为“中国”，希望能更正为“United States”

### ISSUE THREAD

**Issue by Lv-ocean** [redleafnew/Chinese-STD-GB-T-7714-related-csl#246]
**描述错误**
插入美国专利时，输出的国家为“中国”，希望能更正为“United States”

**屏幕截图**
插入的专利信息
![微信图片_20240103121250](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/87459946/54bc8e4d-81f0-4b92-8d52-a1ca0108ef67)
输出的信息
![微信截图_20240103121355](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/87459946/c1f7c8db-16d7-4656-9fec-21ff53e0ffee)

**条目信息**

[
	{
		"id": "minakawaMethodApparatusHot2007",
		"type": "patent",
		"abstract": "A hot stretch wrap forming apparatus includes a die having a work surface formed of a thermally and/or electrically insulative material, and a set of spaced jaws for stretching and wrapping the metal form around the work surface. A preferred insulative material is a flexible blanket of woven ceramic fibers. A heat source is used to heat the metal form prior to stretching and wrapping. The metal form is preferably heated resistively to maintain a uniform temperature throughout the metal form. The die is typically formed primarily of metal and thus the insulative material thermally insulates the metal form from the metal of the die to prevent the formation of hot spots which would otherwise occur therebetween. The insulative material also electrically insulates the metal form from the metal of the die to prevent shunting therebetween.",
		"call-number": "11/432045",
		"number": "20070261461",
		"title": "Method and apparatus for hot forming elongated metallic bars",
		"URL": "https://www.freepatentsonline.com/y2007/0261461.html",
		"author": [
			{
				"family": "Minakawa",
				"given": "Kuninori"
			},
			{
				"family": "Keskar",
				"given": "Arvind R."
			},
			{
				"family": "Barb",
				"given": "Adrian"
			}
		],
		"contributor": [
			{
				"family": "Sullivan",
				"given": "Debra M."
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2024",
					1,
					2
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2007",
					11,
					15
				]
			]
		},
		"submitted": {
			"date-parts": [
				[
					"2006",
					5,
					11
				]
			]
		}
	}
]

**Comment by zepinglee** [comment]
使用了哪个样式？

**Comment by Lv-ocean** [comment]
> 使用了哪种款式？

使用了”北京航空航天大学”这个

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/13e90c0725b5303417336b0f912d2487c101c20c/420beihang-university.csl#L91-L94

主要是因为 hard code 在这里了。

这个样式质量较低，有很多 bug，我稍后重制一下。北航的格式要求还是 <http://graduate.buaa.edu.cn/info/1039/7831.htm> 吗？

**Comment by Lv-ocean** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/13e90c0725b5303417336b0f912d2487c101c20c/420beihang-university.csl#L91-L94
> 
> 主要是因为硬代码就在这里了。
> 
> 这个风格质量较低，有很多bug，我稍后重制一下。北航的格式要求还是http://graduate.buaa.edu.cn/info/1039/7831.htm吗？
是的，格式还是以上的要求，辛苦作者，感谢~！

**Comment by zepinglee** [comment]
83d7439 重制了该样式。

规定的格式跟示例不太一致：“专利类型”一般指“发明型专利”等，但是示例中并未出现；标点符号也不一致。重制版按照示例的格式。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/83d74395003acb6cd664ff2ec8f8fab2f8218765/tests/styles/420beihang-university/test.md?plain=1#L84-L86

**Comment by zepinglee** [comment]
另外国别需要填在 `Place` 字段，目前 Zotero 导出 CSL-JSON 时 `country` 没有对应的字段。

<img width="353" alt="Screenshot 2024-01-05 at 00 20 48" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/da5639a8-4f1d-4f24-8699-d35fcda118f0">

**Comment by Lv-ocean** [comment]
> 另外国别需要填在 `Place` 字段，目前 Zotero 导出 CSL-JSON 时 `country` 没有对应的字段。
> 
> <img alt="Screenshot 2024-01-05 at 00 20 48" width="353" src="https://private-user-images.githubusercontent.com/12290822/294237594-da5639a8-4f1d-4f24-8699-d35fcda118f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTc5NDYsIm5iZiI6MTcwNDQxNzY0NiwicGF0aCI6Ii8xMjI5MDgyMi8yOTQyMzc1OTQtZGE1NjM5YTgtNGYxZC00ZjI0LTg2OTktZDM1ZmNkYTExOGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAxMjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhODEzYzVhY2E3ZjkyODc2MjIzYjY1ZjNlZjAyZTIyMTIxOGFkNmNhMTEwNTI0ZWY0ODk0MGQ3Y2QwZjJjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZF3uTQSmiVcquvmTNk8lDuJgbhUxce6zyw436LzP4s">

感谢作者！功德无量~~！
