### ISSUE TITLE
法学引注手册样式在微信公众号上似乎存在可以改进的地方。

### ISSUE THREAD

**Issue by yzy1228682367** [redleafnew/Chinese-STD-GB-T-7714-related-csl#248]
**描述错误**

CSL 样式：法学引注手册
法学引注手册对微信公众号有特殊要求，一是会在微信公众号名称需要加引号并在前方注明属于微信公众号，例如载微信公众号“中国法律评论”；二是微信公众号的链接，有的微信公众号的链接很长，但是期刊版面有限，可否设置为如果链接字符数超过70个字符时，引注就不出现链接？

**屏幕截图**
![CleanShot 2024-01-14 at 14 47 23@2x](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/50101175/23e6c178-5b31-4fa1-b331-3a20e082edcc)

**条目信息**

```json
[
	{
		"id": "http://zotero.org/users/11021824/items/KQUHQE4R",
		"type": "post-weblog",
		"abstract": "对信用问题加强宣传舆论引导，可能是较好的办法，不宜过于依赖立法惩戒",
		"container-title": "中国法律评论",
		"genre": "微信公众平台",
		"language": "zh",
		"title": "【重磅】刘松山：失信惩戒立法的三大问题",
		"URL": "http://mp.weixin.qq.com/s?__biz=MzA5NDI0MzgyMA==&mid=2651888963&idx=1&sn=493aca87821f9370967d360bcbeb110d&chksm=8bb5a3c0bcc22ad69a3e5210e2a1b60e3a29ffe4deffd62d2ff8e9230ccd143aa51086318c66#rd",
		"author": [
			{
				"literal": "中国法律评论"
			},
			{
				"literal": "刘松山"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2024",
					1,
					14
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2019",
					11,
					19
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
> **描述错误**
> 
> CSL 样式：法学引注手册 法学引注手册对微信公众号有特殊要求，一是会在微信公众号名称需要加引号并在前方注明属于微信公众号，例如载微信公众号“中国法律评论”；

嗯，有道理。

我之前对“post-weblog”类型不太熟，所以当时的设计是将 `微信公众号“中国法律评论”` 填在 `container-title`。

> 二是微信公众号的链接，有的微信公众号的链接很长，但是期刊版面有限，可否设置为如果链接字符数超过70个字符时，引注就不出现链接？

CSL 无法判断字段信息的内容。只能手动删掉，或者想办法替换成较短的 URL，比如 <https://mp.weixin.qq.com/s/wA3Jj923WNctVATeSkIhCw>。

**Comment by zepinglee** [comment]
在 f10669d 中修正。

**Comment by yzy1228682367** [comment]
感谢大佬！

**Comment by yzy1228682367** [comment]
大佬，请问如果genre一列显示“微信公众平台”的话（茉莉花抓取规则），引注有没有可能输出成“微信公众号”呢？就是法学引注手册上的这种格式呢？刘松山：《失信惩戒立法的三大问题》， 载微信公众号“中国法律评论"2019年11月19Enttps://mp.weixin.qq.com/s/wA3Jj923WNctVATeSk IhC。

**Comment by zepinglee** [comment]
> 大佬，请问如果genre一列显示“微信公众平台”的话（茉莉花抓取规则），引注有没有可能输出成“微信公众号”呢？就是法学引注手册上的这种格式呢？刘松山：《失信惩戒立法的三大问题》， 载微信公众号“中国法律评论"2019年11月19Enttps://mp.weixin.qq.com/s/wA3Jj923WNctVATeSk IhC。

CSL 无法替换字段的信息。你可以向 <https://github.com/l0o0/translators_CN> 提一下修改需求。

**Comment by yzy1228682367** [comment]
好的谢谢❤️
