### ISSUE TITLE
CSL 样式语言识别和引注上的部分词语错误

### ISSUE THREAD

**Issue by aurora-w** [redleafnew/Chinese-STD-GB-T-7714-related-csl#251]
**描述错误**

CSL 样式：[463tongji-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/463tongji-university.csl)

这个样式对中英文文献识别还是出现问题。简单地说，当mendeley中引注语言选择为中文时，英文文献不会使用如In，而是使用中文的”见“，不会使用et al. 而是使用“等”，不会使用edt，而是使用主编等问题。

**屏幕截图**
![截屏2024-01-23 18 41 25](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/19618648/7d282fa5-d7d5-4810-9f4d-23eba8fd6aae)
![截屏2024-01-23 18 44 33](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/19618648/7e907ab5-d9dd-4622-bf1d-b0ada81b7281)

**Comment by zepinglee** [comment]
这是 CSL 的输出语言，你需要对每条文献单独设置语言。参考 Zotero

<img width="362" alt="Screenshot 2024-01-23 at 21 21 33" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/fbcb7888-e5df-4b05-b446-ab8f0edf2f53">

**Comment by aurora-w** [comment]
我使用的是Mendeley。在新旧版本的Mendeley客户端中都没有类似的语言标注选项。是不是意味着Mendeley无法实现这个功能？

另外，当我试图上传至Mendeley cite在word上的插件时候，显示错误已损坏，我使用[CSL Style and Locale Validator](https://validator.citationstyles.org/)来检查代码之后显示如下的结果。
![截屏2024-01-24 11 11 28](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/19618648/0193f730-b35d-46c8-b527-ffdcb6c2fd3f)

**Comment by zepinglee** [comment]
我没用过 Mendeley。`463tongji-university.csl` 使用了 CSL-M 扩展的 multi-`layout` 功能（参考 [FAQ#为何英文文献会显示中文“等”、“卷”而不是“et al.”, “vol.”？](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/wiki/FAQ#为何英文文献会显示中文等卷而不是et-al-vol)）。<https://validator.citationstyles.org/> 只支持标准 CSL，不支持 CSL-M 扩展，所以会判定为错误。

**Comment by aurora-w** [comment]
我换到了Zotero。还是非常好用的。但是遇到了一些问题。我稍微修改了一下tongji的这份文件，我正准备要博士毕业。要求上是说要上角标标注，而文件里是[1]。这个我成功了。另外就是学位显示，你这里标注的是[学位论文]，学校是要求[博士学位论文]或[硕士~~]。我同时也做了修改，删掉了之前的[学位论文]和thesis的关系，这样英文显示正常。然后我把判断条件加了一下，并在zotero里的论文类型中分别标注的博士或硕士。可是我不知道为什么，博士学位显示正常，硕士却不行。

以下是截图：其中，陈梦梦这个是硕士论文。
![截屏2024-01-25 13 17 01](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/19618648/c21bdc7a-ef15-4e3b-94d0-c702a81cfc46)

基于你之前的代码，我修改后的代码文件：

<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" name-as-sort-order="all" sort-separator=" " demote-non-dropping-particle="never" initialize-with=" " initialize-with-hyphen="false" page-range-format="expanded" default-locale="zh-CN">
  <info>
    <title>同济大学</title>
    <id>http://www.zotero.org/styles/tongji-university</id>
    <link href="http://www.zotero.org/styles/tongji-university" rel="self"/>
    <link href="http://www.zotero.org/styles/chinese-gb7714-1987-numeric" rel="template"/>
    <link href="https://gs.tongji.edu.cn/info/1063/1754.htm" rel="documentation"/>
    <author>
      <name>Zeping Lee</name>
      <email>zepinglee@gmail.com</email>
    </author>
    <category citation-format="numeric"/>
    <category field="generic-base"/>
    <summary>同济大学学位论文写作规范（2023更新）</summary>
    <updated>2024-01-21T15:32:15+08:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
  <locale xml:lang="en">
    <terms>
      <term name="thesis">dissertation</term>
    </terms>
  </locale>
  <locale xml:lang="zh">
    <terms>
      <term name="edition" form="short">版</term>
      <term name="in">见</term>
      <term name="patent">专利</term>
      <term name="thesis"></term>
      <term name="open-quote">“</term>
      <term name="close-quote">”</term>
      <term name="open-inner-quote">‘</term>
      <term name="close-inner-quote">’</term>
      <term name="editor" form="short">主编</term>
    </terms>
  </locale>
  <locale>
    <date form="numeric">
      <date-part name="year" range-delimiter="/"/>
      <date-part name="month" form="numeric-leading-zeros" prefix="-" range-delimiter="/"/>
      <date-part name="day" form="numeric-leading-zeros" prefix="-" range-delimiter="/"/>
    </date>
    <terms>
      <term name="page-range-delimiter">～</term>
    </terms>
  </locale>
  
  <macro name="author-en">
    <names variable="author">
      <name/>
      <label form="short" prefix=", "/>
      <substitute>
        <names variable="composer"/>
        <names variable="illustrator"/>
        <names variable="director"/>
        <choose>
          <if variable="container-title" match="none">
            <names variable="editor"/>
          </if>
        </choose>
      </substitute>
    </names>
  </macro>
  <macro name="author-zh">
    <names variable="author">
      <name delimiter="，"/>
      <label form="short"/>
      <substitute>
        <names variable="composer"/>
        <names variable="illustrator"/>
        <names variable="director"/>
        <choose>
          <if variable="container-title" match="none">
            <names variable="editor"/>
          </if>
        </choose>
      </substitute>
    </names>
  </macro>
  
  <macro name="title-en">
    <group delimiter=": ">
      <group delimiter=" ">
        <choose>
          <if type="standard">
            <text variable="number"/>
          </if>
        </choose>
        <text variable="title"/>
        <choose>
          <if variable="container-title" type="chapter paper-conference" match="none">
            <text macro="volume"/>
          </if>
        </choose>
        <choose>
          <if type="bill legal_case legislation regulation report" match="any">
            <text variable="number"/>
          </if>
        </choose>
      </group>
      <choose>
        <if type="thesis">
          <text term="thesis" prefix="[" suffix="]"/>
        </if>
      </choose>
    </group>
  </macro>
  <macro name="title-zh">
    <group delimiter="：">
      <group delimiter=" ">
        <choose>
          <if type="standard">
            <text variable="number"/>
          </if>
        </choose>
        <group delimiter="：">
          <text variable="title"/>
          <group delimiter="&#8195;">
            <choose>
              <if variable="container-title" type="chapter paper-conference" match="none">
                <text macro="volume"/>
              </if>
            </choose>
            <choose>
              <if type="bill legal_case legislation regulation report" match="any">
                <text variable="number"/>
              </if>
            </choose>
          </group>
        </group>
      </group>
      <choose>
        <if type="thesis">
          <text term="thesis" prefix="[" suffix="]"/>
        <choose>
          <if variable="genre" match="any" contains="博士">
            <text value="[博士学位论文]"/>
          </if>
          <else-if variable="genre" match="any" contains="硕士">
            <text value="[硕士学位论文]"/>
          </else-if>
        </choose>
        </if>
      </choose>
    </group>
  </macro>
  
  <macro name="volume">
    <choose>
      <if type="article article-journal article-magazine article-newspaper periodical" match="none">
        <choose>
          <if is-numeric="volume">
            <group delimiter=" ">
              <label variable="volume" form="short" text-case="capitalize-first"/>
              <text variable="volume"/>
            </group>
          </if>
          <else>
            <text variable="volume"/>
          </else>
        </choose>
      </if>
    </choose>
  </macro>
  
  <macro name="secondary-contributors-en">
    <names variable="translator">
      <name/>
      <label form="short" prefix=", "/>
    </names>
  </macro>
  <macro name="secondary-contributors-zh">
    <names variable="translator">
      <name delimiter="，"/>
      <label form="short"/>
    </names>
  </macro>
  
  <macro name="container-contributors-en">
    <names variable="editor">
      <name/>
      <label form="short" prefix=", "/>
      <substitute>
        <names variable="editorial-director"/>
        <names variable="collection-editor"/>
        <names variable="container-author"/>
      </substitute>
    </names>
  </macro>
  <macro name="container-contributors-zh">
    <names variable="editor">
      <name delimiter="，"/>
      <label form="short"/>
      <substitute>
        <names variable="editorial-director"/>
        <names variable="collection-editor"/>
        <names variable="container-author"/>
      </substitute>
    </names>
  </macro>
  
  <macro name="container-booklike-en">
    <group delimiter=": ">
      <text term="in" text-case="capitalize-first"/>
      <group delimiter=". ">
        <text macro="container-contributors-en"/>
        <group delimiter=", ">
          <choose>
            <if variable="container-title">
              
              <group delimiter=": ">
                <text variable="container-title"/>
                <text macro="volume"/>
              </group>
            </if>
            <else-if type="paper-conference">
              
              <text variable="event-title"/>
            </else-if>
          </choose>
          
          <choose>
            <if type="paper-conference" variable="event-date" match="all">
              <date variable="event-date" form="numeric" date-parts="year"/>
              <text variable="event-place"/>
            </if>
          </choose>
        </group>
      </group>
    </group>
  </macro>
  <macro name="container-booklike-zh">
    <group delimiter="：">
      <text term="in" text-case="capitalize-first"/>
      <group delimiter="．">
        <text macro="container-contributors-zh"/>
        <group delimiter="，">
          <choose>
            <if variable="container-title">
              
              <group delimiter="：">
                <text variable="container-title"/>
                <text macro="volume"/>
              </group>
            </if>
            <else-if type="paper-conference">
              
              <text variable="event-title"/>
            </else-if>
          </choose>
          
          <choose>
            <if type="paper-conference" variable="event-date" match="all">
              <date variable="event-date" form="numeric" date-parts="year"/>
              <text variable="event-place"/>
            </if>
          </choose>
        </group>
      </group>
    </group>
  </macro>
  
  <macro name="container-periodical-en">
    <choose>
      <if type="article-newspaper">
        
        <group delimiter=", ">
          <text variable="container-title" form="short" strip-periods="true"/>
          <date variable="issued" form="numeric"/>
        </group>
        <text variable="page" prefix="(" suffix=")"/>
      </if>
      <else>
        
        <group delimiter=": ">
          <group>
            <group delimiter=", ">
              <text variable="container-title" form="short" strip-periods="true"/>
              <date variable="issued" form="numeric" date-parts="year"/>
              <text variable="volume"/>
            </group>
            <text variable="issue" prefix="(" suffix=")"/>
          </group>
          <text variable="page"/>
        </group>
      </else>
    </choose>
  </macro>
  <macro name="container-periodical-zh">
    <choose>
      <if type="article-newspaper">
        
        <group delimiter="，">
          <text variable="container-title" form="short" strip-periods="true"/>
          <date variable="issued" form="numeric"/>
        </group>
        <text variable="page" prefix="（" suffix="）"/>
      </if>
      <else>
        
        <group delimiter="：">
          <group>
            <group delimiter="，">
              <text variable="container-title" form="short" strip-periods="true"/>
              <date variable="issued" form="numeric" date-parts="year"/>
              <text variable="volume"/>
            </group>
            <text variable="issue" prefix="（" suffix="）"/>
          </group>
          <text variable="page"/>
        </group>
      </else>
    </choose>
  </macro>
  
  <macro name="edition-en">
    <choose>
      <if is-numeric="edition">
        <group delimiter=" ">
          <number variable="edition" form="ordinal"/>
          <label variable="edition" form="short"/>
        </group>
      </if>
      <else>
        <text variable="edition"/>
      </else>
    </choose>
  </macro>
  <macro name="edition-zh">
    <choose>
      <if is-numeric="edition">
        <text value="第"/>
        <number variable="edition"/>
        <label variable="edition" form="short"/>
      </if>
      <else>
        <text variable="edition"/>
      </else>
    </choose>
  </macro>
  
  <macro name="year-volume-issue-en">
    <group delimiter=", ">
      <date variable="issued" form="numeric" date-parts="year"/>
      <text variable="volume"/>
    </group>
    <text variable="issue" prefix="(" suffix=")"/>
  </macro>
  <macro name="year-volume-issue-zh">
    <group delimiter="，">
      <date variable="issued" form="numeric" date-parts="year"/>
      <text variable="volume"/>
    </group>
    <text variable="issue" prefix="（" suffix="）"/>
  </macro>
  
  <macro name="publisher-en">
    <choose>
      <if type="patent">
        
        <group delimiter=". ">
          <group delimiter=", ">
            <group delimiter=" ">
              <text macro="patent-country-en"/>
              <text term="patent"/>
            </group>
            <text variable="number"/>
          </group>
          <date variable="issued" form="numeric"/>
        </group>
      </if>
      <else>
        <group delimiter=": ">
          <group delimiter=", ">
            <group delimiter=": ">
              <text variable="publisher-place"/>
              <text variable="publisher" strip-periods="true"/>
            </group>
            <date variable="issued" form="numeric" date-parts="year"/>
          </group>
          <text variable="page"/>
        </group>
      </else>
    </choose>
  </macro>
  <macro name="publisher-zh">
    <choose>
      <if type="patent">
        
        <group delimiter="．">
          <group delimiter="，">
            <group>
              <text macro="patent-country-zh"/>
              <text term="patent"/>
            </group>
            <text variable="number"/>
          </group>
          <date variable="issued" form="numeric"/>
        </group>
      </if>
      <else>
        <group delimiter="：">
          <group delimiter="，">
            <group delimiter="：">
              <text variable="publisher-place"/>
              <text variable="publisher" strip-periods="true"/>
            </group>
            <date variable="issued" form="numeric" date-parts="year"/>
          </group>
          <text variable="page"/>
        </group>
      </else>
    </choose>
  </macro>
  
  <macro name="patent-country-en">
    <choose>
      
      <if variable="jurisdiction">
        <text variable="jurisdiction"/>
      </if>
      <else-if variable="publisher-place">
        <text variable="publisher-place"/>
      </else-if>
      <else>
        <text value="US"/>
      </else>
    </choose>
  </macro>
  <macro name="patent-country-zh">
    <choose>
      
      <if variable="jurisdiction">
        <text variable="jurisdiction"/>
      </if>
      <else-if variable="publisher-place">
        <text variable="publisher-place"/>
      </else-if>
      <else>
        <text value="中国"/>
      </else>
    </choose>
  </macro>
  
  <macro name="access">
    <choose>
      <if type="dataset post post-weblog software webpage" match="any">
        
        <text variable="URL"/>
      </if>
    </choose>
  </macro>
  
  <macro name="entry-layout-en">
    <group delimiter=". ">
      <text macro="author-en"/>
      <choose>
        <if type="periodical">
          
          <text macro="title-en"/>
          <text macro="year-volume-issue-en"/>
          <text macro="publisher-en"/>
        </if>
        <else-if type="article-journal article-magazine article-newspaper" match="any">
          
          <text macro="title-en"/>
          <text macro="container-periodical-en"/>
        </else-if>
        <else-if type="patent">
          
          <text macro="title-en"/>
          <text macro="publisher-en"/>
        </else-if>
        <else-if type="dataset post post-weblog software webpage" match="any">
          
          <text macro="title-en"/>
          <text macro="publisher-en"/>
        </else-if>
        <else-if type="chapter entry-dictionary entry-encyclopedia paper-conference" variable="container-title" match="any">
          
          <text macro="title-en"/>
          <text macro="secondary-contributors-en"/>
          <text macro="container-booklike-en"/>
          <text macro="edition-en"/>
          <text macro="publisher-en"/>
        </else-if>
        <else>
          
          <text macro="title-en"/>
          <text macro="edition-en"/>
          <text macro="secondary-contributors-en"/>
          <text macro="publisher-en"/>
        </else>
      </choose>
      <text macro="access"/>
    </group>
  </macro>
  <macro name="entry-layout-zh">
    <group delimiter="．">
      <text macro="author-zh"/>
      <choose>
        <if type="periodical">
          
          <text macro="title-zh"/>
          <text macro="year-volume-issue-zh"/>
          <text macro="publisher-zh"/>
        </if>
        <else-if type="article-journal article-magazine article-newspaper" match="any">
          
          <text macro="title-zh"/>
          <text macro="container-periodical-zh"/>
        </else-if>
        <else-if type="patent">
          
          <text macro="title-zh"/>
          <text macro="publisher-zh"/>
        </else-if>
        <else-if type="dataset post post-weblog software webpage" match="any">
          
          <text macro="title-zh"/>
          <text macro="publisher-zh"/>
        </else-if>
        <else-if type="chapter entry-dictionary entry-encyclopedia paper-conference" variable="container-title" match="any">
          
          <text macro="title-zh"/>
          <text macro="secondary-contributors-zh"/>
          <text macro="container-booklike-zh"/>
          <text macro="edition-zh"/>
          <text macro="publisher-zh"/>
        </else-if>
        <else>
          
          <text macro="title-zh"/>
          <text macro="edition-zh"/>
          <text macro="secondary-contributors-zh"/>
          <text macro="publisher-zh"/>
        </else>
      </choose>
      <text macro="access"/>
    </group>
  </macro>
  <citation collapse="citation-number" after-collapse-delimiter=",">
    <sort>
      <key variable="citation-number"/>
    </sort>
    <layout delimiter=", " prefix="[" suffix="]" vertical-align="sup">
      <text variable="citation-number"/>
    </layout>
  </citation>
  <bibliography entry-spacing="0" et-al-min="4" et-al-use-first="3" second-field-align="flush">
    <layout locale="en">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout-en"/>
    </layout>
    <layout>
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout-zh"/>
    </layout>
  </bibliography>
</style>

**Comment by aurora-w** [comment]
[xml version.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14047085/xml.version.docx)
代码上传有问题，我就放在了word文档里附上。

**Comment by zepinglee** [comment]
> 我换到了Zotero。还是非常好用的。但是遇到了一些问题。我稍微修改了一下tongji的这份文件，我正准备要博士毕业。

> 要求上是说要上角标标注，而文件里是[1]。

这个是 bug，我修改一下。

> 另外就是学位显示，你这里标注的是[学位论文]，学校是要求[博士学位论文]或[硕士~~]。

这里也是 bug。大概是因为这个同济的样式是从《中国高等学校自然科学学报编排规范》的样式修改的，而后者的只需要“学位论文”或“dissertation”。我稍后一并修改。

> 我同时也做了修改，删掉了之前的[学位论文]和thesis的关系，这样英文显示正常。然后我把判断条件加了一下，并在zotero里的论文类型中分别标注的博士或硕士。可是我不知道为什么，博士学位显示正常，硕士却不行。

CSL 应该没有 `contains="..."` 的用法，参考 <https://docs.citationstyles.org/en/stable/specification.html> 和 <https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html>。正确的用法是在文献数据的 `Type` 字段填 `硕士学位论文`，CSL 只输出 `<text variable="genre">`。

另外建议不要贴这么长的代码，可以 fork 本仓库（如果会用 git）或者保存为 `.txt` 文件传上来。

**Comment by aurora-w** [comment]
我的天。我没有意识到这个文件贴上去这么长。非常抱歉。你简直是救星！我从未学过如何编辑CSL。已经折腾了好几天了。但是卡在了这个问题上。我不知道怎么解决。非常感谢你。如果你修改完毕，不知道是否可以发给我一份呢？谢谢！我刚刚上传的文件里主要是把[1]改成了上角标形式，可能还需要麻烦你主要解决的是[学位论文]，学校是要求[博士学位论文]或[硕士~~]的识别问题。

**Comment by zepinglee** [comment]
在 0210f66 中修正。

> 如果你修改完毕，不知道是否可以发给我一份呢？

下载最新版（2024-01-25T14:13:23+08:00）即可。

**Comment by aurora-w** [comment]
最后这个版本有一个小问题。就是显示的时候只有[博士]或者[硕士]，而不是[博士学位论文]。

**Comment by zepinglee** [comment]
> 最后这个版本有一个小问题。就是显示的时候只有[博士]或者[硕士]，而不是[博士学位论文]。

参考 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/wiki/FAQ#为何学位论文类型显示博士而不是博士学位论文> 和 <https://github.com/northword/zotero-format-metadata/issues/132>。

**Comment by aurora-w** [comment]
太棒了！成功了！！！
