### ISSUE TITLE
申请添加中国人民大学研究生学位论文参考文献格式

### ISSUE THREAD

**Issue by SimonGideonRaymond** [redleafnew/Chinese-STD-GB-T-7714-related-csl#252]
**样式信息**

- 期刊/学校名称：[中国人民大学研究生学位论文]

- 英文名称：[Renmin University of China]

- 参考文献格式：[2021级研究生手册p258-260， PDFp265-267<https://grs.ruc.edu.cn/info/1140/2509.htm>]

- 参考文献格式的更新日期：[2021级（2022、2023级研究生手册中未找到参考文献相关要求，一般而言只要前后一致就行，人大仅在部分条目上提出要求，如英文斜体期刊，中文引号文章名称，地点：出版社等）]

- （学校）文件号：[2020一2021学年研政字2号]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
这个格式跟《中国社会科学》比较接近，但还是有些区别。需要将示例文献录入 Zotero 群组方便我们进行测试。需要加入群组 <https://www.zotero.org/groups/4677213/chinese_csl_development> 并提供 zotero id。

<img width="780" alt="Screenshot 2024-01-29 at 19 44 30" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/32bbc51f-04a9-4525-aa18-8ee5af8a265d">

另外吐槽一下：

1. “Smith M.L.”和“Wright, P.”姓和名之间的逗号不一致。
2. 我怀疑作者不知道西文的点号后要加空格。
3. “173～183”的波浪号是中文特有的用法，西文不用波浪号表示数值范围。

建议跟学校反馈一下。

**Comment by SimonGideonRaymond** [comment]
收到！已申请加入，id是GideonRaymond

**Comment by zepinglee** [comment]
> 收到！已申请加入，id是GideonRaymond

<img width="907" alt="Screenshot 2024-01-30 at 12 42 50" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/9ac90652-c3da-49dc-a182-901b3ae8d4fc">

已设为 admin。

**Comment by zepinglee** [comment]
<img width="376" alt="Screenshot 2024-01-30 at 12 49 04" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/cc113ba5-c26a-4ccb-92b5-ab353f8b1057">

@SimonGideonRaymond 你的插件自动破坏了群组原有的数据。你都用了哪些的插件，以及对应的版本号是多少？

**Comment by SimonGideonRaymond** [comment]
实在抱歉，我刚看到消息，可能是因为我使用的是zotero7的最新版55，插件是zotero one 5.4.8，Jasminum1.0.0-6，Ethereal Style3.3.6



在 2024-01-30 12:49:57，"Zeping Lee" ***@***.***> 写道：

Screenshot.2024-01-30.at.12.49.04.png (view on web)

@SimonGideonRaymond 你的插件自动破坏了群组原有的数据。你都用了哪些的插件，以及对应的版本号是多少？

**Comment by zepinglee** [comment]
> 实在抱歉，我刚看到消息，可能是因为我使用的是zotero7的最新版55，插件是zotero one 5.4.8，Jasminum1.0.0-6，Ethereal Style3.3.6

zotero one 5.4.8 是哪个插件？有没有链接？

**Comment by zepinglee** [comment]
测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/main/tests/styles/468renmin-university-of-china>，你看看还有什么问题。

**Comment by SimonGideonRaymond** [comment]
非常抱歉，我刚看到消息。
马怀德，“公务法人问题研究”，《中国教育法制评论》，北京，教育科学出版社，2002，31–42。
这一行缺少《中国教育法制评论》的主编姓名，补全应为：
马怀德，“公务法人问题研究”，劳凯声，《中国教育法制评论》，北京，教育科学出版社，2002，31–42。
非常非常感谢

**Comment by zepinglee** [comment]
> 非常抱歉，我刚看到消息。 马怀德，“公务法人问题研究”，《中国教育法制评论》，北京，教育科学出版社，2002，31–42。 这一行缺少《中国教育法制评论》的主编姓名，补全应为： 马怀德，“公务法人问题研究”，劳凯声，《中国教育法制评论》，北京，教育科学出版社，2002，31–42。 非常非常感谢

在 b76ba92 中修正。

主编一般用 `editor` 不用 `book author`。
