### ISSUE TITLE
无法更改引注显示类型为脚注

### ISSUE THREAD

**Issue by AlieZVzz** [redleafnew/Chinese-STD-GB-T-7714-related-csl#253]
**描述错误**

CSL 样式：003gb-t-7714-2015-numeric-bilingual-no-url-doi

清晰简洁地描述错误是什么，预期的结果是什么。
在引用界面无法更改引用类型为脚注

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

**其他相关信息**

在此处添加有关该问题的其他信息。
这个是正常的
<img width="613" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/47358078/4184777c-d071-4abb-a601-b2acd1cc8f68">

这个是没有脚注的
<img width="624" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/47358078/a9548ea6-3671-4abe-989d-66c6fb834a33">

**Comment by zepinglee** [comment]
003 是 numeric 样式，note 式应该用 [305gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/305gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi.csl)。

**Comment by AlieZVzz** [comment]
@zepinglee 好的好的感谢，还有现在添加csl文件会出现这个弹窗，是有什么问题吗
<img width="435" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/47358078/73f1ccb8-901f-457e-9113-53f253f37fb0">

**Comment by zepinglee** [comment]
<img width="858" alt="Screenshot 2024-01-30 at 17 17 27" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/2a46694b-d362-4078-9dd5-86b9f1a73f9c">

**Comment by AlieZVzz** [comment]
懂了感谢😊
