### ISSUE TITLE
[咨询] 使用西安交大参考文献格式csl，中国作者的英文表达里(Yu Y), 预期为(Yu YD)

### ISSUE THREAD

**Issue by echo1115** [redleafnew/Chinese-STD-GB-T-7714-related-csl#256]
- 西安交大中文人名的英文表达方式：
简写时，采用姓在前，名在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，如，“钱学森”，简写为“Qian XS”。
全拼时，名在前，姓在后的著录法，名的第一个字母大写，名连写，名后空1格写姓，姓的第一个字母大写。如，“钱学森”，写为“Xuesen Qian”。

- 当我使用[438xi-an-jiaotong-university.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/8da61996c185fae4490504fd5ab2afc816c65484/438xi-an-jiaotong-university.csl)引用zotero中的以下文献时：

![1706757295576](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/69078335/e6b0e2ac-24bd-491a-99b4-9fa85b0c1d55)

显示效果：

> [1]Yu Y, Zheng Y, Liu X, et al. Microstructure evolution of YSZ/Al2O3 supersaturated solid solution[J]. Applied Surface Science, 2021, 549: 149260.

实际上我希望Yu Y 显示成Yu YD, 即如下：

> [1]Yu YD, Zheng YT, Liu XD, et al. Microstructure evolution of YSZ/Al2O3 supersaturated solid solution[J]. Applied Surface Science, 2021, 549: 149260.

我可以通过手动修改zotero中的作者名字达到该效果(如修改zotero中作者**Yu, Yongdong**为**Yu, Yong-Dong** ), 但我的zotero中类似格式的名字太多了，全部手动修改很繁琐

咨询一下如何通过csl解决，或者是否有zotero插件能实现？

感谢！

**Comment by zepinglee** [comment]
CSL 可以将 `Xue Sen` 缩写为 `XS`，但 `Xuesen` 就没有办法了。

插件可以部分实现该功能，之前有人提过这个需求（<https://github.com/l0o0/jasminum/issues/140>）。@northword 有没有兴趣实现？

实际使用一般对拼音姓名的要求不是很严格，像国标自己的示例都没有完全遵守。比如第 3 页的示例“FAN X”，实际姓名为“Fan Xuetong”（见 <https://catalog.lib.msu.edu/Record/hlm.ebs1438731e>）。当然，这位大概率是美籍华人。但是参考文献格式要取决于作者国籍也太扯了。

<img width="767" alt="Screenshot 2024-02-01 at 11 38 17" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/33a0a63f-c7a9-4354-a8bc-93b875731740">

**Comment by northword** [comment]
@zepinglee 准确截断拼音是比较困难的，你有什么想法吗？

**Comment by zepinglee** [comment]
> @zepinglee 准确截断拼音是比较困难的，你有什么想法吗？

拼音的组合是有限的（<https://pinyin.info/rules/initials_finals.html>），用回溯进行匹配？

**Comment by echo1115** [comment]
@zepinglee 感谢你的回复！目前我只能手动在zotero中进行名字截断了。如果有更好的点子请告诉我，也期待你们未来可能进行的功能实现 @northword

**Comment by northword** [comment]
[linter-beta-1.12.0-splitName.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14121518/linter-beta-1.12.0-splitName.zip)

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44738481/c46f01d7-4206-47eb-b9fc-31d45728bcba)

按回溯写的，供测试。139 中事项的还没实现姓判断（所以可能会对外国人名误伤，以及无法区分外籍华人名）

**Comment by echo1115** [comment]
@northword 感谢你快速的功能实现！遗憾的是我注意到[zotero-format-metadata Release 1.12.0](https://github.com/northword/zotero-format-metadata/releases/tag/v1.12.0)目前只支持zotero 7 版本了，出于稳定性的考虑我当前使用的还是zotero 6版本。仍然感激你的卓越贡献与帮助！

**Comment by pencilheart** [comment]
大佬，为你点赞👍，已经成功解决`Yu, YongDong`→`Yu, Yong Dong`。请求是否可添加支持`Yu, Yong-Dong`为`Yu, Yong Dong`?

**Comment by northword** [comment]
> 大佬，为你点赞👍，已经成功解决`Yu, YongDong`→`Yu, Yong Dong`。请求是否可添加支持`Yu, Yong-Dong`为`Yu, Yong Dong`?

@zepinglee 这两种哪种更规范呢？还是说都可以，看用户个人习惯？

（应该没有短横线就是人名一部分的这种情况吧（主要是外国人），我没遇到过）

**Comment by zepinglee** [comment]
> @zepinglee 这两种哪种更规范呢？还是说都可以，看用户个人习惯？

如果按照 GB/T 16159—2012《汉语拼音正词法基本规则》两种都不规范。我建议保留文章中原来的姓名格式。这样如果使用国标的 CSL 样式输出都是“Yu Y D”，没有区别。

> （应该没有短横线就是人名一部分的这种情况吧（主要是外国人），我没遇到过）

有：

- [Pierre-Simon Laplace](https://en.wikipedia.org/wiki/Pierre-Simon_Laplace)
- [Fei-Fei Li](https://en.wikipedia.org/wiki/Fei-Fei_Li)

**Comment by TIANYUZHOU** [comment]
实测有一定概率把外国人的名字识别成拼音，不过是少数，比如：Lucia

**Comment by TIANYUZHOU** [comment]
> https://github.com/northword/zotero-format-metadata/releases/tag/v1.12.0
> 
> ![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44738481/c46f01d7-4206-47eb-b9fc-31d45728bcba)
> 
> 按回溯写的，供测试。
实测有一定概率把外国人的名字识别成拼音，不过是少数，比如：Lucia
