### ISSUE TITLE
申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。

### ISSUE THREAD

**Issue by 1355356** [redleafnew/Chinese-STD-GB-T-7714-related-csl#259]
**描述错误**

CSL 样式：xxx-xxx-xxx.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
[
	{
		"id": "doe1984his",
		"type": "book",
		"title": "His anonymous life",
		"author": [
			{
				"family": "Doe",
				"given": "John"
			}
		],
		"issued": {
			"date-parts": [
				[
					"1984"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by redleafnew** [comment]
是原来的不对？还是学校的要求改了。
有要求的网址或截图吗？

**Comment by redleafnew** [comment]
和404的主要区别是什么？
学校论文格式要求的地址是什么？

**Comment by redleafnew** [comment]
有没有网址，需要写入到csl文件中，供其他人参考。文件看不到。老师不按学校的要求自己规定一套？

**Comment by 1355356** [comment]
咨询了一下学校老师，说正文要用（作者，年份）标注。
谢谢您啦！



&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上9:01
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
有没有网址，需要写入到csl文件中，供其他人参考。文件看不到。老师不按学校的要求自己规定一套？

**Comment by redleafnew** [comment]
学校要求的具体网址是什么？

**Comment by 1355356** [comment]
https://grs.sxau.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&amp;owner=1668180822&amp;wbfileid=291188




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上9:19
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
学校要求的具体网址是什么？

**Comment by redleafnew** [comment]
https://grs.sxau.edu.cn/info/1056/1397.htm 是这个地址吗？

**Comment by redleafnew** [comment]
试一下470，刚上传的

**Comment by redleafnew** [comment]
如何不对，请上传错误的条目JSON格式。

**Comment by 1355356** [comment]
我也不知道哪里不对，这个代码我看不懂，就是用您刚跟我说的470尝试了几次。唯一的问题就是：参考文献还是没有按照正文中的插入顺序排列。


















&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上9:59
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
如何不对，请上传错误的条目JSON格式。

**Comment by redleafnew** [comment]
请提供测试的例子，

**Comment by 1355356** [comment]
比如这一段话，我要添加3篇文献进去。
希望最后在结尾处&nbsp; 参考文献按照插入顺序自动生成：









&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上10:30
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
请提供测试的例子，

**Comment by 1355356** [comment]
好啦好啦！！！你简直太牛了。
这大晚上的还在帮我们，十分感动！
新年好！




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月13日(星期二) 晚上10:37
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
你直接通过回复邮件的方式，在帖子显示得不全。
 再试一下，修改了。

**Comment by zepinglee** [comment]
404 的质量不高，不要在那个样式基础上修改。

如果正文的引用是著者-出版年，后面的参考文献表按论文中出现的先后顺序排列，读者就没法根据前者在参考文献表中查找。所以学校的要求是默认引用序号的。

**Comment by zepinglee** [comment]
> 您好，首先感谢您的回复。我们是山西农业大学，研究生论文格式。我找的这个是最类似我们要求的

一开始不写清楚要干嘛也是服了。

**Comment by zepinglee** [comment]
> 这都理解不了？本身404后面的文献就是乱得。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/404jinan-university/test.md

这是按照姓名排序的。建议了解一下“著者-出版年”制。

**Comment by 1355356** [comment]
是这样啊，我不清楚是怎么个情况，如果默认是应用序号的话，麻烦您可否抽空将470另外改为一个引用序号的版本。




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月14日(星期三) 中午12:43
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 申请将404 jinan-university这个版本，最后的参考文献顺序可以与文章中应用顺序保持一致。 (Issue #259)





 
404 的质量不高，不要在那个样式基础上修改。
 
如果正文的引用是著者-出版年，后面的参考文献表按论文中出现的先后顺序排列，读者就没法根据前者在参考文献表中查找。所以学校的要求是默认引用序号的。

**Comment by zepinglee** [comment]
> 咨询了一下学校老师，说正文要用（作者，年份）标注。

先按照你们学校老师的要求吧。
