### ISSUE TITLE
无法正确使用“等”和“et.al”

### ISSUE THREAD

**Issue by carlludwig** [redleafnew/Chinese-STD-GB-T-7714-related-csl#26]
大佬你好
我测试过好几个csl文件都不能正常使用“等”和“et.al”
![image](https://user-images.githubusercontent.com/40169089/155642073-c3fa7ced-dd40-4fdf-81d3-38e09135c30b.png)

**Comment by redleafnew** [comment]
需要将条目语言设置为en，里面有使用说明

**Comment by carlludwig** [comment]
条目语言我按照知乎上的教程确认过了 是en
还是不行

**Comment by redleafnew** [comment]
将不行的条目导出，发上来看一下。

**Comment by carlludwig** [comment]
抱歉 是我的问题
那些出错的条目是语言设置是eng
改正之后问题已解决
感谢您的耐心指导！

**Comment by redleafnew** [comment]
导出附件，删除条目时删除附件的插件：https://github.com/redleafnew/delitemwithatt，这个插件也可以设置语言。
