### ISSUE TITLE
413tsinghua-university-numeric.csl的参考文献列表格式有误

### ISSUE THREAD

**Issue by PhD-Mn** [redleafnew/Chinese-STD-GB-T-7714-related-csl#261]
**描述错误**

CSL 样式：413tsinghua-university-numeric.csl

应该的格式：参考文献表用五号字，汉字用宋体，英文用 Times New Roman 体，行距采用
固定值 16 磅，段前 3 磅，段后 0 磅。 采用悬挂格式，将序号悬挂在外。

当前问题：序号没有悬挂在外，而是缩进了。行距、段前后均不对。

**屏幕截图**
当前错误样式如图：

![1707925627014](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/98349924/5e50191d-cc0a-4f10-91f6-a4722ad5f202)

正确示例如图

![微信截图_20240214234839](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/98349924/15c0ef77-2f33-4400-a7c0-64b0929e1269)

**Comment by zepinglee** [comment]
这些需要在 Word 中设置：样式窗格（Styles Pane）-> 书目（Bibliography）。
