### ISSUE TITLE
002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl期刊名加粗

### ISSUE THREAD

**Issue by FengJunJian** [redleafnew/Chinese-STD-GB-T-7714-related-csl#263]
**样式信息**
**样式如下：**
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/30363292/06e9a14f-dfa4-462e-9563-5cb3e0da68b6)

- 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式：[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/c7bd994c63ed1d6924dc85a3a0824a221c793ede/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L252

这一行改成 `<text variable="container-title" font-weight="bold"/>`。

这是哪个期刊/学校的格式？

**Comment by FengJunJian** [comment]
Thanks，不是特定哪个期刊，只是用GB-T这个格式时，其他文档有一些另外要求，非常感谢！

**Comment by FengJunJian** [comment]
作者. 博士论文题目[D]. 北京: **清华大学**, 2018.

**Comment by FengJunJian** [comment]
请问：博士论文中，学校名称加粗又如何修改，谢谢！
csl依然是：002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl
如：
作者. 博士论文题目[D]. 北京: **清华大学**, 2018

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/c7bd994c63ed1d6924dc85a3a0824a221c793ede/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L300

学校名称和图书的出版社都是 `publisher`。

如果指需要学校名称加粗，需要将这行改成：

```xml
<choose>
  <if type="thesis">
    <text variable="publisher" font-weight="bold"/>
  </if>
  <else>
    <text variable="publisher"/>
  </else>
</choose>
```

**Comment by FengJunJian** [comment]
您好！再次打扰！

**Comment by FengJunJian** [comment]
您好！再次打扰！
002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl中，问题有两个：
1. et al 和等 怎么改为_斜体_
2. 期刊名改为斜体，如：
作者. 博士论文题目[D]. 北京: **_清华大学_**, 2018

感谢！

**Comment by zepinglee** [comment]
正式出版物的中文一般不用斜体。

> 1. et al 和等 怎么改为_斜体_

在每个 `<names>` 中添加 `<et-al font-style="italic"/>`，习惯上一般放在 `<name>` 后。可能中文的“等”依然不是斜体，但应该没有解决办法了。在我看来“等”用斜体真的很蠢。人家“et al.”用斜体是因为拉丁文，中文凑什么热闹。

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/2608f6e9d59eb9edc03be4f467885e5603ec11b3/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L53-L65>

> 2. 期刊名改为斜体，如：
>    作者. 博士论文题目[D]. 北京: **_清华大学_**, 2018

这里改成 
```xml
<group font-style="italic">
  <text variable="container-title"/>
</group>
```
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/2608f6e9d59eb9edc03be4f467885e5603ec11b3/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl#L252
