### ISSUE TITLE
420beihang-university格式有误

### ISSUE THREAD

**Issue by XadBo** [redleafnew/Chinese-STD-GB-T-7714-related-csl#264]
**描述错误**

CSL 样式：420beihang-university.csl

要求半角标点符号+空格

**屏幕截图**
<img width="294" alt="yaoqiu" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/0381b250-c4db-4ae8-ad4f-7c50b6cf6fa4">

现有引用格式为：

**屏幕截图**
<img width="478" alt="oral" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/2208c7d4-65ed-41d9-b04d-07e4b37b28e6">

**屏幕截图**
<img width="443" alt="Snipaste_2024-02-26_19-13-44" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/faa2d39a-2fdd-47a5-a7d8-dbd8eb36327d">

**Comment by zepinglee** [comment]
见 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/154>。

<https://graduate.buaa.edu.cn/info/1039/7831.htm>

<img width="807" alt="Screenshot 2024-02-26 at 21 17 29" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/64edc990-570f-49b5-b8f0-90301480ed63">

**Comment by XadBo** [comment]
> 见 [zepinglee/gbt7714-bibtex-style#154](https://github.com/zepinglee/gbt7714-bibtex-style/issues/154)。
> 
> https://graduate.buaa.edu.cn/info/1039/7831.htm
> 
> <img alt="Screenshot 2024-02-26 at 21 17 29" width="807" src="https://private-user-images.githubusercontent.com/12290822/307803829-64edc990-570f-49b5-b8f0-90301480ed63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDM4NzQsIm5iZiI6MTcwOTA0MzU3NCwicGF0aCI6Ii8xMjI5MDgyMi8zMDc4MDM4MjktNjRlZGM5OTAtNTcwZi00OWI1LWI4ZjAtOTAzMDE0ODBlZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE0MTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZGExYzc5NGRkNzE1OTQxZDM3NDUyYjk4OGYxMzhiMWYxMzg1MTVhZGE2NWUxMjBjOTZmOWYyN2VjYmY5MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UPC4htuUfqJeBF6bZdf0wBrxt7IUfiReHQs50V1A9M">

感谢回复，刚上学校图书馆登录并在知网上下载学位论文后发现，应该是存在空格

## 图书馆展示 ##
<img width="608" alt="1" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/c60db59a-2a37-48c2-9e74-0793cd22b3c8">

## 知网北航学位论文 ##
见https://kns.cnki.net/kcms2/article/abstract?v=F5NaIWgMQ1BvIjRWxxvzgzDeZhwfILpu_9KgoCpQdHgAt6w6NDYLOvOUwr5oxxQSe3h5iTvi0wu85TJ4FRZViYzNYMqUHZpprtjsKfj8De6QwsJOpZJh7_xF-kohriG0w1_yPfnPjpMeVc8_fXNVWA==&uniplatform=NZKPT&language=CHS
<img width="1150" alt="Snipaste_2024-02-27_22-41-20" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/d61ea85a-de15-437d-9079-8e2adb8de36a">

**Comment by XadBo** [comment]
> 见 [zepinglee/gbt7714-bibtex-style#154](https://github.com/zepinglee/gbt7714-bibtex-style/issues/154)。
> 
> https://graduate.buaa.edu.cn/info/1039/7831.htm
> 
> <img alt="Screenshot 2024-02-26 at 21 17 29" width="807" src="https://private-user-images.githubusercontent.com/12290822/307803829-64edc990-570f-49b5-b8f0-90301480ed63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDU1MzQsIm5iZiI6MTcwOTA0NTIzNCwicGF0aCI6Ii8xMjI5MDgyMi8zMDc4MDM4MjktNjRlZGM5OTAtNTcwZi00OWI1LWI4ZjAtOTAzMDE0ODBlZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE0NDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZjgwMWQ2M2M0MDY0OGM5YzZkMDg2OWQyM2RlNTE0MTA0OTJmMTI0NmVkZjMwOTVmNDRkYWY1MjIzNWVkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U0hfHc1HXrKV4M1epXkx0q15iGpgr2yZQMX9dL52Xuk">

感谢回复，在图书馆以及知网学位论文查证后确认应该是存在空格的

#### 图书馆展示 ####
<img width="608" alt="1" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/9439da02-9345-4521-9653-441e0b0bc7a8">

#### 知网北航学位论文 ####
见https://kns.cnki.net/kcms2/article/abstract?v=F5NaIWgMQ1BvIjRWxxvzgzDeZhwfILpu_9KgoCpQdHgAt6w6NDYLOvOUwr5oxxQSe3h5iTvi0wu85TJ4FRZViYzNYMqUHZpprtjsKfj8De6QwsJOpZJh7_xF-kohriG0w1_yPfnPjpMeVc8_fXNVWA==&uniplatform=NZKPT&language=CHS

<img width="1150" alt="Snipaste_2024-02-27_22-41-20" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/127165314/7df3089d-7ff1-41cb-bc61-6ef1b352da2b">

**Comment by zepinglee** [comment]
> 在图书馆以及知网学位论文查证后确认应该是存在空格的

图书馆的格式是按照《[北京航空航天大学研究生撰写学位论文的规定](https://graduate.buaa.edu.cn/info/1039/7831.htm)》吗？知网给出的是国标的格式吧？

@ll930512 在 <https://github.com/zepinglee/gbt7714-bibtex-style/issues/154#issuecomment-1925693609> 提到：

> 最近的毕业论文格式检查项中列举了这个

你们两个讨论一下。
