### ISSUE TITLE
中国农业大学硕博论文（人文与发展学院）样式请求

### ISSUE THREAD

**Issue by caucohd** [redleafnew/Chinese-STD-GB-T-7714-related-csl#265]
**样式信息**

- 期刊/学校名称：[中国农业大学人文与发展学院研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式：[研究生学位论文<http://cohd.cau.edu.cn/module/download/downfile.jsp?filename=c549e3ebc7884cefb61658eacc284fee.pdf>]

- 参考文献格式的更新日期：[2020-02-5]

- （学校）文件号：[院发〔2020〕 04 号]

**测试条目**

Zotero ID:ssci

**其他样式信息**

**Comment by zepinglee** [comment]
我看了一下，似乎跟校研究生院的格式要求 <https://gradsch1.cau.edu.cn/art/2019/3/18/art_41503_770264.html> （社会科学）也不完全一样。需要将示例文献录入 Zotero 群组。

已经设为 admin 编辑权限。
<img width="919" alt="Screenshot 2024-02-27 at 19 18 15" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/416749b7-47a0-4b75-bc23-64635e659f0d">

**Comment by caucohd** [comment]
> 我看了一下，似乎跟校研究生院的格式要求 https://gradsch1.cau.edu.cn/art/2019/3/18/art_41503_770264.html （社会科学）也不完全一样。需要将示例文献录入 Zotero 群组。
> 
> 已经设为 admin 编辑权限。 <img alt="Screenshot 2024-02-27 at 19 18 15" width="919" src="https://private-user-images.githubusercontent.com/12290822/308146429-416749b7-47a0-4b75-bc23-64635e659f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzM5NDIsIm5iZiI6MTcwOTAzMzY0MiwicGF0aCI6Ii8xMjI5MDgyMi8zMDgxNDY0MjktNDE2NzQ5YjctNDdhMC00Yjc1LWJjMjMtNjQ2MzVlNjU5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDExMzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzYyMjRkYjU2MmQ0YzU0MjFiMzc5OGQxODhkMjY1NjZiZmQ4ZTU2MWZlNWRmYWRhMTk4ODcwOWNiNWFkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M15892ikY7rnRRwFOlRwgNMlKqaEsJsa5RTLK-07yoQ">

感谢，有个问题需要咨询，Zotero条目中没有“电子文献”选项，可以用“博客帖子”代替吗？另外，条目中没有“析出文献”选项，涉及到不同作者，如何添加呢？（周凡. 2008. 导论: 激进政治视域中的农业与农民问题[A]. 何增
科， 周凡主编. 农业的政治经济分析[C]. 重庆： 重庆出版社： 1-32.）

**Comment by caucohd** [comment]
> 我看了一下，似乎跟校研究生院的格式要求 https://gradsch1.cau.edu.cn/art/2019/3/18/art_41503_770264.html （社会科学）也不完全一样。需要将示例文献录入 Zotero 群组。
> 
> 已经设为 admin 编辑权限。 <img alt="Screenshot 2024-02-27 at 19 18 15" width="919" src="https://private-user-images.githubusercontent.com/12290822/308146429-416749b7-47a0-4b75-bc23-64635e659f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzM5NDIsIm5iZiI6MTcwOTAzMzY0MiwicGF0aCI6Ii8xMjI5MDgyMi8zMDgxNDY0MjktNDE2NzQ5YjctNDdhMC00Yjc1LWJjMjMtNjQ2MzVlNjU5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDExMzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzYyMjRkYjU2MmQ0YzU0MjFiMzc5OGQxODhkMjY1NjZiZmQ4ZTU2MWZlNWRmYWRhMTk4ODcwOWNiNWFkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M15892ikY7rnRRwFOlRwgNMlKqaEsJsa5RTLK-07yoQ">

感谢，有个问题需要咨询，Zotero条目中没有“电子文献”选项，可以用“博客帖子”代替吗？另外，条目中没有“析出文献”选项，涉及到不同作者，如何添加呢？（周凡. 2008. 导论: 激进政治视域中的农业与农民问题[A]. 何增
科， 周凡主编. 农业的政治经济分析[C]. 重庆： 重庆出版社： 1-32.）

**Comment by zepinglee** [comment]
> 有个问题需要咨询，Zotero条目中没有“电子文献”选项，可以用“博客帖子”代替吗？

先按 blogPost 填写，然后点击类型转为 webpage。

<img width="426" alt="Screenshot 2024-02-27 at 19 40 19" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/9e0cb6b7-af7a-47fe-887f-4031c5d38db7">

> 另外，条目中没有“析出文献”选项，涉及到不同作者，如何添加呢？（周凡. 2008. 导论: 激进政治视域中的农业与农民问题[A]. 何增 科， 周凡主编. 农业的政治经济分析[C]. 重庆： 重庆出版社： 1-32.）

使用 `bookSection` 类型。

**Comment by caucohd** [comment]
> > 有个问题需要咨询，Zotero条目中没有“电子文献”选项，可以用“博客帖子”代替吗？
> 
> 先按 blogPost 填写，然后点击类型转为 webpage。
> <img alt="Screenshot 2024-02-27 at 19 40 19" width="426" src="https://private-user-images.githubusercontent.com/12290822/308152539-9e0cb6b7-af7a-47fe-887f-4031c5d38db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzQ0MjgsIm5iZiI6MTcwOTAzNDEyOCwicGF0aCI6Ii8xMjI5MDgyMi8zMDgxNTI1MzktOWUwY2I2YjctYWY3YS00N2ZlLTg4N2YtNDAzMWM1ZDM4ZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDExNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzQyN2U4MDRlMDlmMjJiOTNkYzQ0YTJkZTI5ZjMwNTBhMGU3MDM2MWU5YmJhMjhjODIyOTU4OWRhN2I2NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1SMtYXkLb4VuI2-Ch8nGPAJSyEnmV4NE55yLID-hGk">
> 
> > 另外，条目中没有“析出文献”选项，涉及到不同作者，如何添加呢？（周凡. 2008. 导论: 激进政治视域中的农业与农民问题[A]. 何增 科， 周凡主编. 农业的政治经济分析[C]. 重庆： 重庆出版社： 1-32.）
> 
> 使用 `bookSection` 类型。
感谢帮助，已经导入完成。路径为：学位论文—0227中国农业大学，请查收。

**Comment by zepinglee** [comment]
已添加样式 [472china-agricultural-university-college-of-humanities-and-development-studies.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/472china-agricultural-university-college-of-humanities-and-development-studies.csl)。测试效果见 [tests/styles/472china-agricultural-university-college-of-humanities-and-development-studies/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/472china-agricultural-university-college-of-humanities-and-development-studies/test.md)。

**Comment by caucohd** [comment]
> 已添加样式 [472china-agricultural-university-college-of-humanities-and-development-studies.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/472china-agricultural-university-college-of-humanities-and-development-studies.csl)。测试效果见 [tests/styles/472china-agricultural-university-college-of-humanities-and-development-studies/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/472china-agricultural-university-college-of-humanities-and-development-studies/test.md)。你看看还有没有别的问题。

核对无误，感谢您的工作，祝您生活愉快，谢谢。
