### ISSUE TITLE
引文到100之后首个单词与编号之间的空格变大，看起来不统一

### ISSUE THREAD

**Issue by suetme** [redleafnew/Chinese-STD-GB-T-7714-related-csl#266]
**描述错误**

CSL 样式：GB/T7714-2015（顺序编码，双语，姓名取消大写，无URL DIO）

引文到100之后首个单词与编号之间的空格变大，看起来不统一。

**屏幕截图**

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/101245167/f3fa2083-d0ce-496f-ab38-24334a10c325)

**Comment by zepinglee** [comment]
这个需要在 Word 中设置悬挂缩进和制表符的宽度，调大一些即可。

**Comment by suetme** [comment]
> 这个需要在 Word 中设置悬挂缩进和制表符的宽度，调大一些即可。

解决了，非常感谢！！大家遇到这个问题把圈出来的数值修改即可。

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/101245167/80f7b85d-7315-47c9-86c9-e5f0750eb084)
