### ISSUE TITLE
重庆大学硕、博论文样式（2023修订）样式制作请求-著者年份制

### ISSUE THREAD

**Issue by wmcjkl123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#267]
**样式信息**

- 期刊/学校名称：[重庆大学硕、博学位论文样式（2023修订）]

- 英文名称：[ Chongqing University]

- 参考文献格式：[请见附件，项目里已经更新顺序编码制，希望能补充**著者年份制** ]

[附件2：“著者-出版年制” 的参考文献的引用和著录格式.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14428474/2.-.pdf)

-->

**测试条目**

Zotero ID:

**其他样式信息**

[附件2：“著者-出版年制” 的参考文献的引用和著录格式.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14428481/2.-.pdf)
[重庆大学博士、硕士学位论文格式标准（2023年修订）.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14428482/2023.pdf)

**Comment by zepinglee** [comment]
这份格式要求有些前后不一致。前文要求“缩写名后省略缩写点”，后面的示例“Crane, D.”和“Stieg, M. F.”却有缩写点，而且还有姓与名之间的逗号。你倾向于按照哪种格式？

<img width="740" alt="Screenshot 2024-02-28 at 12 37 19" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/d6fd650e-6eda-46c5-92ef-1f85e91a587b">

参考文献示例:

<img width="740" alt="Screenshot 2024-02-28 at 12 38 04" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/df88a728-8405-475a-b2ca-fda8743129b5">

**Comment by wmcjkl123** [comment]
十分感谢。文件确实有不一致之处，请使用：姓与名之间的逗号，并保留缩写点。

**Comment by zepinglee** [comment]
在 9a28106 中添加。测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/473chongqing-university-author-date/test.md>。

**Comment by wmcjkl123** [comment]
您好，根据测试结果，能否实现引文叙述式时，作者名和等之间没有空格；而在引文括号式时，实现空格
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55068708/8b86ced9-656a-4e50-a6e8-17cefaf3348b)
具体而言,
引文叙述式：张三等（2018）
引文括号式：（张三 等, 2018）

**Comment by zepinglee** [comment]
可以倒是可以，需要加一段代码。但是 Zotero 的 Word 插件没有对应的接口，所以实际中无法使用。

**Comment by wmcjkl123** [comment]
非常感谢。不知能否实现文中引文按指定的顺序排列
比如
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55068708/68e12992-591c-4b95-813a-a25f26057d50)
中英文混排时，按年份递增顺序排列，且英文在前中文在后

**Comment by zepinglee** [comment]
> 非常感谢。不知能否实现文中引文按指定的顺序排列

你们学校的要求以及国标都没有规定引注中的顺序。我理解为你的个人需求。需要在这两行之间添加下面的代码。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/ba2e339507c122cffb1fe98bd065390603c6e625/473chongqing-university-author-date.csl#L505-L506

```xml
    <sort>
      <key variable="language"/>
      <key macro="issued-year"/>
    </sort>
```

而且需要确保每条文献的 `language` 字段都填写了语言。

> 中英文混排时，按年份递增顺序排列，且英文在前中文在后

优先按照语言还是时间排序？你可以自己调整两个 `<key>` 的先后顺序。

**Comment by wmcjkl123** [comment]
谢谢您的反馈。目前我改变这两个顺序，似乎无法实现我的需求。
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55068708/7641563a-2d7a-430d-aa32-b64947cd6116)
我希望中文部分，也能按年份从小到大排序。目前英文部分可以，但中文不行。

**Comment by zepinglee** [comment]
> 谢谢您的反馈。目前我改变这两个顺序，似乎无法实现我的需求。

> 我希望中文部分，也能按年份从小到大排序。目前英文部分可以，但中文不行。

那将这几篇文献导出为 CSL-JSON 格式贴上来，我测试一下。

**Comment by wmcjkl123** [comment]
[导出的条目.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14492172/default.json)
谢谢您的反馈，已上传相应格式文件

**Comment by zepinglee** [comment]
> 已上传相应格式文件

把链接发出来呀

**Comment by wmcjkl123** [comment]
> 把链接发出来呀

您好，我这里上传了，不知您能否正常显示
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55068708/7ec1b92e-c2b8-4770-ac2b-a773b59beb46)

[导出的条目.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14493323/default.json)
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14493323/default.json

**Comment by zepinglee** [comment]
> 您好，我这里上传了，不知您能否正常显示

不好意思，我看错了。

经排查发现是 `citeproc-js` 的 bug，见 <https://github.com/zepinglee/citeproc-js/blob/0f5b9f3e2bcb7204b57c09ae49e3e3baae2e24c6/fixtures/local/sort_CitationBugReport2.txt#L7>。该项目作者最近不是很活跃，不太可能在近期修复。

**Comment by zepinglee** [comment]
可行的方案建议

> > 您好，我这里上传了，不知您能否正常显示
> 
> 不好意思，我看错了。
> 
> 经排查发现是 `citeproc-js` 的 bug，见 <https://github.com/zepinglee/citeproc-js/blob/fe2fb83a13f528aa3371a9419f8d0fcc776edf1b/fixtures/local/sort_CitationBugReport2.txt#L7>。该项目作者最近不是很活跃，不太可能在近期修复。

**Comment by wmcjkl123** [comment]
谢谢您的建议。目前使用以下顺序：
    ```
    <sort>
      <key macro="issued-year"/>
      <key variable="language"/>
    </sort>
    ```
英文没有问题，再手动排中文的年份，可以解决
