### ISSUE TITLE
《经济研究》样式中，英文标题单词首字母未大写

### ISSUE THREAD

**Issue by muxi89** [redleafnew/Chinese-STD-GB-T-7714-related-csl#269]
**描述错误**

CSL 样式：203economic-research-journal

题录中如果英文标题只有句首单词首字母大写时，引用后会原样显示，未能将其他单词首字母大写，希望可以像《管理世界》中期刊论文标题一样变成单词首字母大写（of, and类单词除外）

《经济研究》目前引文格式如下：
Feng, J., J. W. Goodell, and D. Shen, 2022, “ESG rating and stock price crash risk: Evidence from China”, Finance Research Letters, 46, 102476.

《管理世界》目前引文格式如下：
Feng, J., Goodell, J. W. and Shen, D., 2022, “ESG Rating and Stock Price Crash Risk: Evidence from China”, Finance Research Letters, vol.46, p.102476.

感谢！

**Comment by redleafnew** [comment]
这是格式要求的吗？如果是麻烦提供一下要求的网址及地截图。

**Comment by muxi89** [comment]
http://www.erj.cn/cn/Info.aspx?m=20220223162358523953

> 这是格式要求的吗？如果是麻烦提供一下要求的网址及地截图。

**Comment by muxi89** [comment]
> 这是格式要求的吗？如果是麻烦提供一下要求的网址及地截图。
网址：

**Comment by muxi89** [comment]
> http://www.erj.cn/cn/Info.aspx?m=20220223162358523953
> 
> > 这是格式要求的吗？如果是麻烦提供一下要求的网址及地截图。

网址：http://www.erj.cn/cn/Info.aspx?m=20220223162358523953
截图如下
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/25908796/ac236e08-4272-4894-a2bd-9c35a18e7bce)
感谢！

> 这是格式要求的吗？如果是麻烦提供一下要求的网址及地截图。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/943df7d51fcd296bbb736099c6624d051b4e6f33

**Comment by zepinglee** [comment]
嗯，确实。

但是要使用 title case 必须将 CSL 的默认语言设为英文。

**Comment by redleafnew** [comment]
好像这个是英文的 `default-locale="en-US"`

**Comment by zepinglee** [comment]
> 好像这个是英文的 `default-locale="en-US"`

噢我看错了。

**Comment by zepinglee** [comment]
@redleafnew 另外不建议在 `prefix` 和 `suffix` 中 直接设置引号，应该使用 `quotes="true"`（[d019caa](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/d019caa97effca1c5b8b73620282276ac32f869d#diff-190e420602fc1a986f54b98d03aa3d594de3949385c1054874630188ff832a19)）。这样的好处是可以将标题中原来的双引号转为单引号（[d019caa#test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/d019caa97effca1c5b8b73620282276ac32f869d#diff-3d025cf4584a3ed82ae47c94c31572881d00897223d7ca2dff821c2c85a4fd1d)）。

**Comment by redleafnew** [comment]
好的，我看到了，但没有改。

**Comment by muxi89** [comment]
> [943df7d](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/943df7d51fcd296bbb736099c6624d051b4e6f33)

收到，感谢！
另外，《经济研究》这个样式里，参考文献中3个以上的作者就被作为et al.了，按照期刊样式要求，还是需要列示全面，可否修改呢？

**Comment by redleafnew** [comment]
> > [943df7d](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/943df7d51fcd296bbb736099c6624d051b4e6f33)
> 
> 收到，感谢！ 另外，《经济研究》这个样式里，参考文献中3个以上的作者就被作为et al.了，按照期刊样式要求，还是需要列示全面，可否修改呢？

把要求作者全部显示的要求截图一下

**Comment by muxi89** [comment]
网址：http://www.erj.cn/cn/Info.aspx?m=20220223162358523953
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/25908796/7072586c-4653-496b-abc1-69d25bc0a656)
截图中可见，四名作者都列示完全了。
感谢！

**Comment by redleafnew** [comment]
有没有明确说明，几个作者如何如何？

**Comment by muxi89** [comment]
没有明确说明几个作者如何，但从已发表论文来看，最后的参考文献中作者姓名都列全了

**Comment by zepinglee** [comment]
> 没有明确说明几个作者如何，但从已发表论文来看，最后的参考文献中作者姓名都列全了

在 ba2e339 中修改。

**Comment by muxi89** [comment]
> > 没有明确说明几个作者如何，但从已发表论文来看，最后的参考文献中作者姓名都列全了
> 
> 在 [ba2e339](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/ba2e339507c122cffb1fe98bd065390603c6e625) 中修改。

感谢大神
