### ISSUE TITLE
需求北京大学研究生学位论文参考文献的csl模板

### ISSUE THREAD

**Issue by crliu95** [redleafnew/Chinese-STD-GB-T-7714-related-csl#27]
对csl文件的理解还不透彻，所以暂时没法自己上手做，希望能获得支持！我可以帮忙测试~

附件中是北京大学的研究生学位论文格式要求，关于参考文献的注意事项在附录A中：
[北京大学研究生学位论文写作指南.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8141633/default.pdf)

根据附件中的陈述，这份要求很大程度上参考了清华博士论文的格式要求，但有改动，所以可能从清华的csl文件出发会比较省事。

**Comment by redleafnew** [comment]
麻烦
1.看一下与现在的哪个最接近；
2.与最接近的有哪些差异；
3.提供测试的例子，Zotero可以导入；
4.提供规则的链接地址，
谢谢。

**Comment by redleafnew** [comment]
> 

与清华大学的有哪些不同，这里面有清华大学的。

**Comment by crliu95** [comment]
迟复为歉，还未来得及一一对比，目前发现有以下问题：

- 关于电子文献

我看到当前清华CSL文件中设置的逻辑是只要有url或者doi字段其中之一（any），则认为该文献属于电子文献，并增加文献类型标记[OL]和对应的url、doi。结果如下所示：

> 刘秉镰, 武鹏, 刘玉海, 2010. 交通基础设施与中国全要素生产率增长——基于省域数据的空间面板计量分析[J/OL]. 中国工业经济(03): 54-64. DOI:10.19581/j.cnki.ciejournal.2010.03.005.

而如果该文献不属于电子文献，则效果应该如下：

> 刘秉镰, 武鹏, 刘玉海, 2010. 交通基础设施与中国全要素生产率增长——基于省域数据的空间面板计量分析[J]. 中国工业经济(03): 54-64.

想问下可以实现手动选择对应文献是否属于电子文献的逻辑吗？即使Zotero记录里面有url、doi字段，也可以通过额外设置某个选项，标记该文献属于/不属于电子文献。

- 关于文内引用的括号格式

在当前“著者-年”格式的文内引用格式下，正文中插入参考文献时会自动用英文半角括号将插入的文献信息包住。但按照上述两个写作格式，可能需要使用中文全角括号。

**Comment by redleafnew** [comment]
现在Zotero字段还不能自定义，你可以自己找一个现在不用的字段，在csl写一个规则，如果某个字段含有或是什么，可以认为是电子文献。
括号的容易修改。

**Comment by crliu95** [comment]
感谢回复！

电子文献那里我已经改好了，方案是书籍、期刊等几种文献不设置为电子资源，而其他类型的保留原来的判断。其实Zotero字段应该可以在extra里面自己定义的，比如“status:forthcoming”这样，它会保留该信息作为一个新字段。

括号的应该怎么改呢？我查了半天还没有头绪。

**Comment by redleafnew** [comment]
1. 现在很多字定义的是在Extra中添加东西。
2. 欢迎把csl提交到这个仓库，造福更多人。
3. 可以把改好的发上来，看一下具体改哪。

**Comment by crliu95** [comment]
我整理一下发上来

**Comment by xpengkang** [comment]
老师好，下载了这里的csl ,导入zetora ， 报错Chinese-STD-GB-T-7714-related-csl-main\20gb-t-7714-2015-numeric-bilingual-lower-name-prefer-nodoi.csl" 不是有效的 CSL 1.0.1 样式文件，它可能不能在 Zotero 正常工作。
这种问题咋解决呀，谢谢回复！

**Comment by zepinglee** [comment]
> 老师好，下载了这里的csl ,导入zetora ， 报错Chinese-STD-GB-T-7714-related-csl-main\20gb-t-7714-2015-numeric-bilingual-lower-name-prefer-nodoi.csl" 不是有效的 CSL 1.0.1 样式文件，它可能不能在 Zotero 正常工作。 这种问题咋解决呀，谢谢回复！

1. 话题无关的讨论开新 issue；
2. 这是警告不是报错；
3. 直接忽略即可。

**Comment by redleafnew** [comment]
如有需要请提供相关信息，如无，此issue即将关闭。

**Comment by linbeyoung** [comment]
> 我整理一下发上来

请问北大研究生的论文格式是否完成可以提供一下呢？
