### ISSUE TITLE
华中科技大学论文引用格式错误

### ISSUE THREAD

**Issue by Pengyuyan-Hust** [redleafnew/Chinese-STD-GB-T-7714-related-csl#271]
1. 华中科技大学硕博论文引用文献要求达到6个作者，超过6个作者采用et al
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/144187705/1036fd25-cb69-46d0-85ec-027b54f5e3ed)

2. 对于中文引用要求姓在前名在后
3. 对于英文参考文献应用要求名在前姓在后
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/144187705/66fdd325-61c4-41ef-9431-1836f518118e)

感谢修改，辛苦了

**Comment by zepinglee** [comment]
按照 bug report 的 issue 模板填写，提供格式要求的官方链接。

另外是哪个学院的？你们学校各个学院格式不一样，见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/230#issuecomment-1836468781>。
