### ISSUE TITLE
华中科技大学硕士毕业论文格式

### ISSUE THREAD

**Issue by Pengyuyan-Hust** [redleafnew/Chinese-STD-GB-T-7714-related-csl#272]
当前您给出的Zotero文献格式

1. 为作者超过3人后直接用“et al”
2. 但是官方要求是作者超过6人之后再用“et al”
3. 同时要求文献作者姓氏在前
[理工科-硕士-华中科技大学学位论文参考模板 (1).docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14489314/-.-.1.docx)

**华中科技大学研究生院官网**——理工科硕士毕业论文参考文献模板下载地址如下(http://gs.hust.edu.cn/info/1041/5462.htm)
 参考文献格式要求如下
中文书刊：作者按中文写法，姓在前、名在后；英文书刊：作者按英文习惯写法，如在前、姓在后，名用首字母缩写、姓用全称。一般6人以内须列出全部作者，6人以上写6人再加“等”（英文加“et al”））。每个参考文献的最后不加标点符号。
（1）图书：最多列出6个作者，作者与作者之间用逗号分隔. 书名. 版本（第×版）. 译者. 出版地: 出版者, 出版年. 起页-止页（可选）
（2）期刊：最多列出6个作者，作者与作者之间用逗号分隔. 文章名. 期刊名（全称）. 年号, 卷号（期号）: 起页-止页或论文编号
（3）会议论文集：最多列出6个作者，作者之间用逗号分隔. 文章名. 见（英文用“in”）：会议名称（或论文集）. 会议城市, 国家, 会议时间, 出版者, 出版年: 起页-止页
（4）专利：专利申请者. 专利题名. 专利国别, 专利文献种类, 专利号, 出版年
（5）学位论文：作者. 题名：[博士（或硕士）学位论文]. 保存地点: 保存单位（如华中科技大学, 年份）

**Comment by zepinglee** [comment]
1. #271 还没回复就又新开一个 issue？
2. 目前仓库中跟华中科大相关的样式有 `418huazhong-university-of-science-and-technology-school-of-artificial-intelligence-and-automation.csl`, `441huazhong-university-of-science-and-technology-tongji-medical-college.csl`, `462huazhong-university-of-science-and-technology-school-of-cyber-science-and-engineering.csl`，都是各学院的样式。你用的是哪个样式？
3. <https://gs.hust.edu.cn/info/1041/5462.htm>  发布于 2023-02-10，而 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/230#issuecomment-1836468781> 记录的“研究生院格式”是发布于 2022-09-22 的<https://gs.hust.edu.cn/info/1022/1027.htm>，后者已经过时。

**Comment by zepinglee** [comment]
我发现人工智能与自动化学院的格式其实与校研究生院 <http://gs.hust.edu.cn/info/1041/5462.htm> 的格式一样，所以在 047361d 中将 418 更名为研究生院样式。

**Comment by Ziy1-Tan** [comment]
您好，请问会议时间要如何添加，元数据中貌似没有这一项

**Comment by zepinglee** [comment]
> 您好，请问会议时间要如何添加，元数据中貌似没有这一项

参考 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/G9SXAV8Z/items/GD8X7GAE/collection>。
