### ISSUE TITLE
怎么把gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses里参考文献列表的作者缩写改为全称

### ISSUE THREAD

**Issue by ddcxxx** [redleafnew/Chinese-STD-GB-T-7714-related-csl#273]
写国自然基金本子老板要求的格式，尝试按照https://zhuanlan.zhihu.com/p/393376982这个里的教程把<name>字修改为 <name initialize='false'>，但没有生效

**Comment by redleafnew** [comment]
用得哪个csl？
把条目的JSON格式上传上来，以供测试。

**Comment by zepinglee** [comment]
> 写国自然基金本子老板要求的格式，尝试按照[https://zhuanlan.zhihu.com/p/393376982这个里的教程把](https://zhuanlan.zhihu.com/p/393376982%E8%BF%99%E4%B8%AA%E9%87%8C%E7%9A%84%E6%95%99%E7%A8%8B%E6%8A%8A)字修改为 ，但没有生效

把你修改后的 CSL 发到 https://gist.github.com/ 。

**Comment by ddcxxx** [comment]
> > 写国自然基金本子老板要求的格式，尝试按照[https://zhuanlan.zhihu.com/p/393376982这个里的教程把](https://zhuanlan.zhihu.com/p/393376982%E8%BF%99%E4%B8%AA%E9%87%8C%E7%9A%84%E6%95%99%E7%A8%8B%E6%8A%8A)字修改为 ，但没有生效
> 
> 把你修改后的 CSL 发到 https://gist.github.com/ 。

这样吗？
https://gist.github.com/ddcxxx/c4d42ccaf721dd003ece889935f9af89

我就是在[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)的基础上，想要把参考文献列表的作者缩写改为全称，参照知乎的教程把<name>字段修改为 <name initialize='false'>，但zotero直接就识别不了这个csl了

**Comment by ddcxxx** [comment]
> 用得哪个csl？ 把条目的JSON格式上传上来，以供测试。

我就是在[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)的基础上，想要把参考文献列表的作者缩写改为全称，参照知乎的教程把”<name>“字段修改为“<name initialize='false'>” ，但zotero直接就识别不了这个csl了

**Comment by zepinglee** [comment]
第 59 行 `<name initialize='false'>` 后面缺了 `/`，应该是 `<name initialize="false"/>`（另外建议使用双引号跟前后保持一致）。

**Comment by ddcxxx** [comment]
> name initialize="false"/

OK，非常感谢
