### ISSUE TITLE
中国人民大学本科生毕业论文csl申请

### ISSUE THREAD

**Issue by timturing** [redleafnew/Chinese-STD-GB-T-7714-related-csl#274]
**样式信息**
期刊/学校名称：[中国人民大学本科生毕业论文]

英文名称：[Renmin University of China]

参考文献格式：[本科生毕业论文](http://jiaowu.ruc.edu.cn/docs/2023-01/f90c79b8b21c4229bbe7f9c79abb7c14.doc)

参考文献格式的更新日期：[2022-12-29]

（学校）文件号：2014-2015学年校办字33号

**Comment by zepinglee** [comment]
请按照 issue 模板 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/.github/ISSUE_TEMPLATE/feature_request.md?plain=1> 补充官网链接、更新日期等信息。我们需要记录这些信息方便后续讨论（比如 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/230#issuecomment-1836468781> 这里复杂的情况）。

另外该格式与国标比较接近，不必录入示例文献了。

**Comment by zepinglee** [comment]
在 d754452 中添加。

其中英文文献只有两个示例，都是按照 APA 格式。所以样式中其他类型英文文献也按照 APA 的格式处理。测试结果见  <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/477renmin-university-of-china-undergranduate/test.md>。

**Comment by timturing** [comment]
感谢您的付出！目前测试可以使用，若之后有其他需修改的地方再麻烦您了！
