### ISSUE TITLE
华中科技大学电气学院博士论文样式申请

### ISSUE THREAD

**Issue by HandlerXu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#276]
**样式信息**

- 期刊/学校名称：[华中科技大学电气学院博士学位论文样式]

- 英文名称：[Thesis Citation Style for SEEE, HUST ]

- 参考文献格式：[学院修改了学校研究生院的论文格式，见附件1中2.13章节内容]
[附件1：理工科-博士-华中科技大学学位论文参考模板_电气.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14526391/1.-.-._.docx)

- 文献格式说明：附件1中的格式规范为电气学院所限定的规则，与学校模板不同。改文档中2.13章提供的“示例”并不准确，与格式规范有所出入，为便于矫正，我重新提供附件2作为电气学院博士论文参考文献的引用规则说明，并提供正确的示例（根据上一届毕业学生经学术委员会认定后的文献样本提供的参考文献引用示例）
[附件2_参考文献格式说明及示例.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14527482/2_.docx)

- 参考文献格式的更新日期：[2023-04]
- （相关领域：[engineering]

**测试条目**

Zotero ID: Hongwei_X

**其他样式信息**
这是我目前按照国标GB/T 7714—2015使用的.csl样式，但依然存在问题！
[china-national-standard-gb-t-7714-2015-numeric-xhw.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14527603/china-national-standard-gb-t-7714-2015-numeric-xhw.zip)

**Comment by zepinglee** [comment]
两份文件有没有学院官网的链接？

这个格式跟国标比较接近，不必录入测试文献了。

> 标点符号:中文文献采用中文、全角、英文标点输入法输入

这是什么意思？中文标点是全角的，英文标点是半角的。另外说清楚用哪个字符就行了，跟输入法有什么关系？

> 起草责任者是 zotero “标准”条目中的委员会:ISO/TC 108/SC，或者作者一 栏写ISO/TC 108/SC也可。

我改成优先使用 `committee`，而 `author` 作为备选。

> 其余的“标准代号 标准顺序号-发布年 标准名称”都写在标题里即可

我建议“标准代号 标准顺序号-发布年”写在 `number` 字段。

> 注意 [P].2019-10-18 这部分采用了半角标点，针对于专利格式的“[ ]”和“-”到底是半角还是全角很模糊，这两个先默认半角标点即可。 (201910533880.1[P]数字直接接上全角符号会非常奇怪)

我可以先将专利文献特殊处理成半角。另外期刊的年，卷（期）：起止页码部分也是数字接上全角符号，例如“2022，26（1）：24-31”。

**Comment by zepinglee** [comment]
顺便吐槽下你们学校怎么每个学院的格式都不一样。

**Comment by zepinglee** [comment]
在 ce21728 中添加，测试效果见 [475huazhong-university-of-science-and-technology-school-of-electrical-and-electronic-engineering/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/475huazhong-university-of-science-and-technology-school-of-electrical-and-electronic-engineering/test.md)。

> 建议在 csl 源码中对于页码的分隔符写入两种情况，默认用半角“-”，全角的 “—”先注释掉

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/ce21728c02dafe587e0b43170549a65a0c4f0b60/475huazhong-university-of-science-and-technology-school-of-electrical-and-electronic-engineering.csl#L32-L33>

**Comment by HandlerXu** [comment]
> 两份文件有没有学院官网的链接？
> 
> 这个格式跟国标比较接近，不必录入测试文献了。
> 
> > 标点符号:中文文献采用中文、全角、英文标点输入法输入
> 
> 这是什么意思？中文标点是全角的，英文标点是半角的。另外说清楚用哪个字符就行了，跟输入法有什么关系？
> 
> > 起草责任者是 zotero “标准”条目中的委员会:ISO/TC 108/SC，或者作者一 栏写ISO/TC 108/SC也可。
> 
> 我改成优先使用 `committee`，而 `author` 作为备选。
> 
> > 其余的“标准代号 标准顺序号-发布年 标准名称”都写在标题里即可
> 
> 我建议“标准代号 标准顺序号-发布年”写在 `number` 字段。
> 
> > 注意 [P].2019-10-18 这部分采用了半角标点，针对于专利格式的“[ ]”和“-”到底是半角还是全角很模糊，这两个先默认半角标点即可。 (201910533880.1[P]数字直接接上全角符号会非常奇怪)
> 
> 我可以先将专利文献特殊处理成半角。另外期刊的年，卷（期）：起止页码部分也是数字接上全角符号，例如“2022，26（1）：24-31”。

**Comment by HandlerXu** [comment]
> 两份文件有没有学院官网的链接？
> - 附件1是学院老师在学校论文模板基础上修改后给出的模板，没有官网链接；附件2是我个人对附件1中存在问题的地方所作的解释。
> 

> > 标点符号:中文文献采用中文、全角、英文标点输入法输入
> 
> 这是什么意思？中文标点是全角的，英文标点是半角的。另外说清楚用哪个字符就行了，跟输入法有什么关系？
> 
> - 中文文献内的标点符号：在英文输入法下切换全角模式后打出的标点：即［］，：．（）
> - 英文文献内的标点符号：在英文输入法下切换半角模式后打出的标点：即 [] , : . () -
![Snipaste_2024-03-08_10-40-32](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141417970/ed06eacb-aae4-41b6-ac2f-304ac136b9b6)

> > 起草责任者是 zotero “标准”条目中的委员会:ISO/TC 108/SC，或者作者一 栏写ISO/TC 108/SC也可。
> 
> 我改成优先使用 `committee`，而 `author` 作为备选。
> 
> > 其余的“标准代号 标准顺序号-发布年 标准名称”都写在标题里即可
> 
> 我建议“标准代号 标准顺序号-发布年”写在 `number` 字段。
> 
> - okkk

> > 注意 [P].2019-10-18 这部分采用了半角标点，针对于专利格式的“[ ]”和“-”到底是半角还是全角很模糊，这两个先默认半角标点即可。 (201910533880.1[P]数字直接接上全角符号会非常奇怪)
> 
> 我可以先将专利文献特殊处理成半角。另外期刊的年，卷（期）：起止页码部分也是数字接上全角符号，例如“2022，26（1）：24-31”。
>
> - okkk

**Comment by HandlerXu** [comment]
@zepinglee 非常感谢，已下载您修改后的csl样式，符合学院要求。但存在个小问题：

- 英文文献：famliy name的所有字母都要大写
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/141417970/96a0125b-cd0a-4c6d-a794-e640131304e9)

**Comment by HandlerXu** [comment]
> 顺便吐槽下你们学校怎么每个学院的格式都不一样。

- 每个学院职能都很独立，都很有想法，主打一个百花齐放

**Comment by zepinglee** [comment]
> 但存在2个小问题：
> 
> * 英文文献：famliy name的所有字母都要大写

在 3eded8e 中修正。

> * 标准的引文格式：英文标准的标点都要用半角符号，有几处标点没有改过来。中文标准则是全角。另外，引用最后面不用接日期 2006

大概率是 `language` 字段没填写英文吧。这个样式默认语言为中文，`language` 填写 `en-US` 才会按照英文格式处理。

**Comment by zepinglee** [comment]
> * 中文文献内的标点符号：在英文输入法下切换全角模式后打出的标点：即［］，：．（）
> * 英文文献内的标点符号：在英文输入法下切换半角模式后打出的标点：即 [] , : . () -

这个只跟全/半角有关，跟中/英文输入法无关。中文文献在中间为了输入标点符号“切换英文输入法再切换全角”是真的蠢。纯吐槽。

**Comment by HandlerXu** [comment]
样式完美适配，感谢大佬付出🎉🎉🎉
