### ISSUE TITLE
华中科技大学模板无法选择英文

### ISSUE THREAD

**Issue by WaterHyacinthInNANHU** [redleafnew/Chinese-STD-GB-T-7714-related-csl#278]
**描述错误**

CSL 样式：[418huazhong-university-of-science-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/3eded8ebdf3310afb0e3b82a20b84d32dd987059/418huazhong-university-of-science-and-technology.csl#L2)

您好，语言似乎被硬编码成了中文，无法在zotero中切换为英文

移除[ln 2, Col 237](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/3eded8ebdf3310afb0e3b82a20b84d32dd987059/418huazhong-university-of-science-and-technology.csl#L2)的
```
default-locale="zh-CN"
```
后正常

**Comment by zepinglee** [comment]
[FAQ-为何英文文献会显示中文“等”、“卷”而不是“et al.”, “vol.”？](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/wiki/FAQ#%E4%B8%BA%E4%BD%95%E8%8B%B1%E6%96%87%E6%96%87%E7%8C%AE%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%AD%E6%96%87%E7%AD%89%E5%8D%B7%E8%80%8C%E4%B8%8D%E6%98%AFet-al-vol)

**Comment by zepinglee** [comment]
如果你有需求也可以自行将默认语言设为 `en-US`，并调整这里两个 `layout`。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/3eded8ebdf3310afb0e3b82a20b84d32dd987059/418huazhong-university-of-science-and-technology.csl#L462-L471

**Comment by WaterHyacinthInNANHU** [comment]
非常感谢!
