### ISSUE TITLE
您好，希望可以添加首都医科大学的学位论文引用样式。

### ISSUE THREAD

**Issue by yuicyborg** [redleafnew/Chinese-STD-GB-T-7714-related-csl#279]
**样式信息**

- 期刊/学校名称：[首都医科大学研究生学位论文]

- 英文名称：[Capital Medical University]

- 参考文献格式：<https://yjsh.ccmu.edu.cn/xwgz/lwdb/65d371968cab4a54ad9a1531f3538700.htm>

- 参考文献格式的更新日期：[2023-04-26]

**其他样式信息**

[需要列出全部作者姓名，英文姓名和期刊名采用缩写，不列出文献类型，不列出DOI等要求，本项目内没有找到很相近的，自己也不太会改代码。希望可以得到帮助，非常感谢。]

**Comment by zepinglee** [comment]
在 002 的基础上修改就可以。我稍后处理一下。

**Comment by zepinglee** [comment]
在 8c34d48 中添加。

测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/478capital-medical-university/test.md>。

**Comment by yuicyborg** [comment]
您好，感谢您的回复。反馈如下问题：
1. 未显示全部作者名称，目前仍对三个以上的作者名用“等”和“et al”缩写；
2. 英文作者名缩写后，缩写的大写字母其后不需“.”和“ ”空格。
范例：
<img width="587" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/163104792/f50c8fe7-3d8f-4cbf-8a93-7e177a3f25d9">
当前效果：
<img width="598" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/163104792/25e210ac-1f07-40ce-ba44-22ad33af1c64">

**Comment by zepinglee** [comment]
> 您好，感谢您的回复。反馈如下问题：
> 
> 1. 未显示全部作者名称，目前仍对三个以上的作者名用“等”和“et al”缩写；
> 2. 英文作者名缩写后，缩写的大写字母其后不需“.”和“ ”空格。

在 e703675 中修正。

<img width="781" alt="Screenshot 2024-03-13 at 18 47 19" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/206f7f25-2647-45c9-9ebe-e3a29b526541">

另外这个示例中编者名缩写有空格，我暂时保留了空格。

**Comment by yuicyborg** [comment]
关于这点我查阅了既往的博士学位论文，缩写间是没有空格的，可否请您再次修正？
<img width="642" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/163104792/56e1f098-c533-4330-afa5-047b8c2224e1">
暂时没有发现其他问题了，非常感谢您项目组提供的帮助。祝您生活工作顺利。

**Comment by zepinglee** [comment]
注意是编者有空格不是作者。作者名的缩写已经去掉空格了。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/e7036758c4ca10c0b1cfccfcf56f2cc28de02888/tests/styles/478capital-medical-university/test.md?plain=1#L50-L51

**Comment by yuicyborg** [comment]
收到，感谢您的回复。
