### ISSUE TITLE
422chinese-academy-of-agricultural-sciences.csl bibliography有些微错误 

### ISSUE THREAD

**Issue by Winlover10** [redleafnew/Chinese-STD-GB-T-7714-related-csl#281]
条目：422chinese-academy-of-agricultural-sciences.csl 
在文末参考文献list中，书写规范提示每一条参考文献的首行顶格。次行开始缩进两个英文字符，如图所示![截屏2024-03-17 22 23 30](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/100359641/b7cd11f5-b106-40ed-bcaa-535311d25975)
但是目前我使用422条目时，文末参考样式的次行提示是缩进特殊值1.27cm，如图所示：
![截屏2024-03-17 22 23 45](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/100359641/3f2f2a3c-de4f-424a-a3f5-de3c5517e137)
盼望您能在百忙中修改这个小问题，感激不尽

**Comment by redleafnew** [comment]
缩进及其它排版问题，请在Word/WPS中解决，可以使用格式中的悬挂或缩进。CSL文件不处理这些问题。

**Comment by zepinglee** [comment]
> 书写规范提示每一条参考文献的首行顶格。次行开始缩进两个英文字符

西文使用比例字体不存在“两个字符宽度”的说话。一般是固定宽度。

**Comment by Winlover10** [comment]
问题已解决，感谢
