### ISSUE TITLE
《地质学报》中文版样式申请

### ISSUE THREAD

**Issue by Thomas-TVV** [redleafnew/Chinese-STD-GB-T-7714-related-csl#282]
[**样式信息**](url)

- 期刊/学校名称：[ 地质学报 ]

- 英文名称：[ Acta Geologica Sinica ]

- 参考文献格式：[地质学报文章修改要求.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14734782/default.pdf)
[](url)

- 参考文献格式的更新日期：[ 2018-12-24 ]

- （期刊）ISSN 号：[ CN 11-1951/P ]

- （期刊）相关领域：[ geology ]

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by Thomas-TVV** [comment]
正文中的参考文献：
1、英文文献姓写全，名不写，姓和“et al.”之间留适当空隙；中文文献姓和名写全，姓名和“等”之间不留空隙。
例：（李三郎等，2022; Tom et al., 1997, 2003）

**Comment by redleafnew** [comment]
这个参考文献要求的地址是什么？
需要写入的csl中。

**Comment by Thomas-TVV** [comment]
> 这个参考文献要求的地址是什么？ 需要写入的csl中。

我不太明白“地址”是指的什么

**Comment by redleafnew** [comment]
网址

**Comment by redleafnew** [comment]
另外，提供Zotero ID把要求几个条目上传到Zotero群组中。

**Comment by Thomas-TVV** [comment]
> 网址
这里是我查到的两个网址，不知道您指的是不是这个：
https://www.geojournals.cn/dzxb/dzxb/site/menu/2008061202354001 期刊的投稿指南网页
http://geo.ijournals.cn/dzxb/dzxb/news/view/20181224123756124 期刊的下载中心网页有可供下载的《地质学报文章修改要求》，也就是我上传的PDF文件。

**Comment by redleafnew** [comment]
另外与011的差别是什么？请详细列出。

**Comment by redleafnew** [comment]
> > 网址
> > 这里是我查到的两个网址，不知道您指的是不是这个：
> > https://www.geojournals.cn/dzxb/dzxb/site/menu/2008061202354001 期刊的投稿指南网页
> > http://geo.ijournals.cn/dzxb/dzxb/news/view/20181224123756124 期刊的下载中心网页有可供下载的《地质学报文章修改要求》，也就是我上传的PDF文件。

http://geo.ijournals.cn/dzxb/uploadfile/dzxb/20210914/%E5%9C%B0%E8%B4%A8%E5%AD%A6%E6%8A%A5%E6%96%87%E7%AB%A0%E4%BF%AE%E6%94%B9%E8%A6%81%E6%B1%82.pdf 
如果这个文件在用，可以用这个地址。

**Comment by Thomas-TVV** [comment]
> 另外与011的差别是什么？请详细列出。

主要差别如下：

011样式正文引用中：姓氏与”et al.“  ”等“之间均留有空隙。
例：（李三郎 等，2022; Tom et al., 1997, 2003）

《地质学报》期刊要求在正文引用中：英文文献姓和“et al.”之间留适当空隙；中文文献 姓名和 “等” 之间不留空隙。
例：（李三郎等，2022; Tom et al., 1997, 2003）

**Comment by redleafnew** [comment]
如果只有这几点，我修改一下试试，提供几个条目供测试吧，JSON格式（右击条目，导出）

**Comment by Thomas-TVV** [comment]
> 如果只有这几点，我修改一下试试，提供几个条目供测试吧，JSON格式（右击条目，导出）
[英文-1.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735493/-1.json)
[英文-2.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735494/-2.json)
[英文-3.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735495/-3.json)
[中文-1.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735496/-1.json)
[中文-2.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735497/-2.json)
[中文-3.json](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14735498/-3.json)
英文和中文文献各提供了三个。拜托啦！

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/225acta-geologica-sinica.csl

**Comment by redleafnew** [comment]
试一下效果

**Comment by Thomas-TVV** [comment]
> 试一下效果

太赞了！正文中文文献引用姓名与 ”等“ 之间测试之后没有空隙了。万分感谢！！！

**Comment by Thomas-TVV** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/80264905/36595585-b074-40bd-8336-9140fbfade4b)
还有一个问题，下午的时候得到回复是不能自动区分，但是能不能请您再试试，如果这个问题不解决，我就要一个个手动去改了，会很麻烦。

后面参考文献：
1、中国人姓和名要全拼，西洋人姓写全，名缩写。
例：
Beaumont C, Jamieson R A, Nguyen M H, Lee B. 2001. Himalayan tectonics explained by extrusion of a low-viscosity crustal channel coupled to focused surface denudation. Nature, 414: 738~742.
Ma Xuxuan, Meert J G, Xu Zhiqin, Zhao Zhongbao. 2017a. Evidence of magma mixing identified in the Early Eocene Caina pluton from the Gangdese Batholith, southern Tibet. Lithos, 278- 281: 126~139.

**Comment by redleafnew** [comment]
确实是不行的，
要么全是缩写，要么都是全称。
如果一篇文章既有中国人，也有西洋人，怎么处理？Zotero和csl好像没有那么智能可以区分不同国籍的。
倒是可以根据参考文献的语言进行区分，中文的条目作者全称，外文的作者缩写，但区分作者的国籍，没有办法。

**Comment by Thomas-TVV** [comment]
好吧，谢谢啦！！！
