### ISSUE TITLE
四川农业大学 论文样式申请

### ISSUE THREAD

**Issue by FfLagom** [redleafnew/Chinese-STD-GB-T-7714-related-csl#283]
**样式信息**

- 期刊/学校名称：四川农业大学研究生学位论文

- 英文名称：

- 参考文献格式：[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

[四川农业大学研究生学位论文写作指南.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14744107/default.pdf)

- 参考文献格式的更新日期：2024-03-26

- （学校）文件号：研发[2024]1号

- （期刊）ISSN 号：

- （期刊）相关领域：

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
基本跟 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl) 格式一致。

**Comment by zepinglee** [comment]
在 441b965 中添加。

刚发现会议论文的格式略有差异，已修改。

@FfLagom 有没有《四川农业大学研究生学位论文写作指南》这份文件的官网链接？

**Comment by FfLagom** [comment]
链接在这里 https://yan.sicau.edu.cn/info/1331/10727.htm
我现在用的408南农好像也差不多，插进去之后再改行距这些。像段落和段落格式可以通过样式直接生成吗

**Comment by FfLagom** [comment]
> 行距、段落这个由Word负责。

好的 收到。生成后再改嘛

**Comment by redleafnew** [comment]
用书目样式

**Comment by FfLagom** [comment]
> 使用书目风格
这是什么高级东西 研究研究

**Comment by redleafnew** [comment]
仓库的readme上有

**Comment by FfLagom** [comment]
> 仓库的readme上有

收到，谢谢，学会啦

**Comment by redleafnew** [comment]
这个没有问题了吧
