### ISSUE TITLE
科学学研究 样式

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#287]
**样式信息**

- 期刊/学校名称：
科学学研究
- 英文名称：

参考111acta-agriculurae-boreali-sinica.csl
需要在此基础上取消显示doi，不知道现有的代码能否搞定多个空行的原因
<img width="597" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/13982749/6a28a60e-6963-465f-82ab-2da60ccc88fb">
https://journal08.magtechjournal.com/journalx_kxxyj/authorLogOn.action#
- 参考文献格式的更新日期：[例如 2020-07-30]

- （期刊）ISSN 号：[例如 0439-755X]
1003-2053
- （期刊）相关领域：
social_science

**Comment by fredericky123** [comment]
> https://www.zotero.org/groups/4677213/chinese_csl_development/collections/7SP7XX8X/items/G9HATF8I/collection

哦哦！这样可以加个English title:……了对吧，假设有这个信息，csl如何效应修改呢
感谢！（我把示例里那些删一下）

**Comment by fredericky123** [comment]
> > 哦哦！这样可以加个English title:……了对吧，
> 
> 中间有空格恐怕不行。另外 `extra` 中的姓名字段有特殊的用法，即重复多次表示多个作者，而且必须使用 CSL 的姓名变量名才能实现这个效果。其中 `original-author` 最适合表示翻译的英文名（尽管也不完全符合字段含义）。所以我建议其他字段的翻译也使用 `original-` 前缀。
> 
> <img alt="Screenshot 2024-04-01 at 22 57 03" width="276" src="https://private-user-images.githubusercontent.com/12290822/318470438-5d5dd682-42a3-42af-8975-d0f4fa12ff67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQzMzcsIm5iZiI6MTcxMTk4NDAzNywicGF0aCI6Ii8xMjI5MDgyMi8zMTg0NzA0MzgtNWQ1ZGQ2ODItNDJhMy00MmFmLTg5NzUtZDBmNGZhMTJmZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE1MDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwODYxMTUyYzIyN2UwZjE4MTQ5ZjZhZmZiZWZhNTIxMDljMTNmMTgzNjdlYzExMjI4YmI3NDNhNmJiYzY0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.npaxugrexrQhh954flx4YY7bH2HSGGQtHFdmJLkuJxg">
> > 假设有这个信息，csl如何效应修改呢
> 
> 略麻烦。我看看能不能写个脚本自动生成。
> 
> > 似乎用新的key value的方式是不是就可以解决存在空行的那个问题了
> 
> 空行的问题比较容易解决，去掉 `display="block"` 就行了。

感谢！那就用original-title这个字段了

**Comment by fredericky123** [comment]
关闭是因为制好了吗

**Comment by redleafnew** [comment]
***@***.***
________________________________

**Comment by zepinglee** [comment]
还没有。这个假期我出去玩了。

**Comment by fredericky123** [comment]
> 还没有。这个假期我出去玩了。

不急不急，大佬假期愉快😁（尽管假期余额不足了）

**Comment by fredericky123** [comment]
请问这个有一些进展不，感谢大佬！

**Comment by zepinglee** [comment]
> 请问这个有一些进展不，感谢大佬！

目前脚本已经实现了一大半。

**Comment by fredericky123** [comment]
大佬有时间的话能帮忙试试吧，如果有些难度，能实现部分功能也好的，自己再手动修改些内容，感激！

**Comment by zepinglee** [comment]
在 041fe5d 中添加。

**Comment by fredericky123** [comment]
太感谢大牛了！我试试
这里面的ZHtoEN都是自动的吗，还是手动生成一下呢

**Comment by zepinglee** [comment]
自动的。

之前做《心理学报》时是手动的，非常繁杂。所以这次才写脚本处理。

**Comment by fredericky123** [comment]
太牛了！马上试试！

**Comment by redleafnew** [comment]
在Extra中加入条目的英文信息，见
https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl?tab=readme-ov-file#115advances-in-water-sciencecsl 使用说明

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/287#issuecomment-2029815041

> 更推荐使用《心理学报》样式的方法，将字段信息按照 key-value 的方式填在 `extra` 字段中。这样适用于不同格式的期刊。见 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/7SP7XX8X/items/G9HATF8I/collection>。

<img width="346" alt="Screenshot 2024-04-01 at 22 04 37" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/65080f9b-8f69-4a53-a5ca-e6fefc9c64cd">
