### ISSUE TITLE
希望增加中文文献中外籍作者国籍——《法学引注手册》

### ISSUE THREAD

**Issue by Sorocs** [redleafnew/Chinese-STD-GB-T-7714-related-csl#288]
**描述错误**

CSL 样式：manual-of-legal-citation-multi-lingual.csl

《法学引注手册》要求中文译文文献中，外籍作者需要在姓名之前用
方括号注明国籍；台港澳作者无需特别标明。
国籍以版权页为准，可以使用简称，如 [德]、 [英]；但，如果可能引起歧义，不得使用简称。例如，阿富汗学者不能简称[阿]，而应该写[阿富汗] 。

**屏幕截图**
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/165707042/4d80415d-ee8d-435c-b2a8-d4ab93d221bc)

**Comment by Sorocs** [comment]
这可能需要在zetero中文献的具体信息栏中增加“国籍”一栏，可能要制作一个相关插件，不知道您能否帮忙解决

**Comment by zepinglee** [comment]
如果使用额外的字段，以目前 CSL 的功能，两个以上作者则无法分别输出国籍。所以可行的办法是在原始数据的姓名前添加国籍。

目前部分 translator 可以抓取作者国籍信息并以结构化数据的形式保存在 `extra` 字段中，可以使用 <https://github.com/northword/zotero-format-metadata> 插件添加到姓名中，或着从姓名中删掉。

**Comment by Sorocs** [comment]
好的，多谢
