### ISSUE TITLE
中国矿业大学硕士毕业论文参考文献样式

### ISSUE THREAD

**Issue by Andy-one1** [redleafnew/Chinese-STD-GB-T-7714-related-csl#289]
**样式信息**

- 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式：[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
把上面信息填完整

**Comment by Andy-one1** [comment]
[1] Marquez-Andrade M A, Roumani H, Vlajic N. Chapter 20 - CSRF and Big Data: Rethinking Cross-Site Request Forgery in Light of Big Data[M]//Akhgar B, Arabnia H R. Emerging Trends in ICT Security. Boston: Morgan Kaufmann, 2014:315-334.



[1] 王国法, 庞义辉, 任怀伟, 等. 矿山智能化建设的挑战与思考[J]. 智能矿山, 2022,3(10):2-15.

**Comment by Andy-one1** [comment]
谢谢楼主

**Comment by redleafnew** [comment]
> **样式信息**
> 
> * 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]
> * 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]
> * 参考文献格式：[例如 https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf]
> 
> * 参考文献格式的更新日期：[例如 2020-07-30]
> * （学校）文件号：[例如“研生[2019]10号”]
> * （期刊）ISSN 号：[例如 0439-755X]
> * （期刊）相关领域：[例如 psychology]
> 
> **测试条目**
> 
> Zotero ID:
> 
> **其他样式信息**

把这些信息填充完整，
另外需要的样式与仓库中哪个最接近。

**Comment by redleafnew** [comment]
> [1] Marquez-Andrade M A, Roumani H, Vlajic N. Chapter 20 - CSRF and Big Data: Rethinking Cross-Site Request Forgery in Light of Big Data[M]//Akhgar B, Arabnia H R. Emerging Trends in ICT Security. Boston: Morgan Kaufmann, 2014:315-334.
> 
> [1] 王国法, 庞义辉, 任怀伟, 等. 矿山智能化建设的挑战与思考[J]. 智能矿山, 2022,3(10):2-15.

提供Zotero ID把这些条目录入到群组文献，或上传JSON格式。

**Comment by redleafnew** [comment]
与002有什么区别？

**Comment by Andy-one1** [comment]
在002的基础上，学校有以下要求：
1.中文均采用宋体，英文和阿拉伯数字均采用Times New Roman，五号，两端对齐，悬挂缩进1.5字符，段前段后0磅，行距固定值20磅
2.大纲级别为正文文本，参考文献标注采用顺序编码制，文献编号用阿拉伯数字置于方括号“[ ]”中，编号后空1个半角字符。

**Comment by redleafnew** [comment]
> 在002的基础上，学校有以下要求： 1.中文均采用宋体，英文和阿拉伯数字均采用Times New Roman，五号，两端对齐，悬挂缩进1.5字符，段前段后0磅，行距固定值20磅 2.大纲级别为正文文本，参考文献标注采用顺序编码制，文献编号用阿拉伯数字置于方括号“[ ]”中，编号后空1个半角字符。

这些内容不在CSL体现，是Word中设置的。用Word的书目样式。

**Comment by Andy-one1** [comment]
我需要打断链接再进行修改行距等参数吗？还是直接就可以修改，如果可以（002-即中国矿业大学硕士论文参考文献样式）

**Comment by redleafnew** [comment]
> **样式信息**
> 
> * 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]
> * 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]
> * 参考文献格式：[例如 https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf]
> 
> * 参考文献格式的更新日期：[例如 2020-07-30]
> * （学校）文件号：[例如“研生[2019]10号”]
> * （期刊）ISSN 号：[例如 0439-755X]
> * （期刊）相关领域：[例如 psychology]
> 
> **测试条目**
> 
> Zotero ID:
> 
> **其他样式信息**

这些信息麻烦补充一下，我们把002改名一下，需要这些信息。

**Comment by Andy-one1** [comment]
中国矿业大学：[中国矿业大学研究生学位论文]
英文名称：[China University of Mining and Technology]
参考文献格式：[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl]+
学校有以下要求： 1.中文均采用宋体，英文和阿拉伯数字均采用Times New Roman，五号，两端对齐，悬挂缩进1.5字符，段前段后0磅，行距固定值20磅 2.大纲级别为正文文本，参考文献标注采用顺序编码制，文献编号用阿拉伯数字置于方括号“[ ]”中，编号后空1个半角字符。
参考文献的更新日期：2024-4-4
文件号：[中矿大〔2022〕45号]
ISSN号：[无]
相关领域：[矿业方向]

**Comment by redleafnew** [comment]
> 中国矿业大学：[中国矿业大学研究生学位论文] 英文名称：[China University of Mining and Technology] 参考文献格式：[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl]+ 学校有以下要求： 1.中文均采用宋体，英文和阿拉伯数字均采用Times New Roman，五号，两端对齐，悬挂缩进1.5字符，段前段后0磅，行距固定值20磅 2.大纲级别为正文文本，参考文献标注采用顺序编码制，文献编号用阿拉伯数字置于方括号“[ ]”中，编号后空1个半角字符。 参考文献的更新日期：2024-4-4 文件号：[中矿大〔2022〕45号] ISSN号：[无] 相关领域：[矿业方向]

> 2024-4-4 文件号：[中矿大〔2022〕45号]

这个文件有没有网址

**Comment by Andy-one1** [comment]
样式网址：https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl

**Comment by Andy-one1** [comment]
2024-4-4 文件号：[中矿大〔2022〕45号]
这个网址我直接百度搜的

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/482china-university-of-mining-and-technology.csl

**Comment by redleafnew** [comment]
https://gs.cumt.edu.cn/info/1049/3149.htm  这有个2021的

**Comment by Andy-one1** [comment]
我们学校2021的部分显示链接，你刚更新的和0002差别大吗？我这边word无法修改字体大小，一直是小四

**Comment by redleafnew** [comment]
和002没有本质差异，只是修改了ID，文件名等。

字体、字号等都是Word负责。

**Comment by Andy-one1** [comment]
但是我字号无法按照你的样式教程修改为五号，还是“小四”

**Comment by redleafnew** [comment]
新建一个Word，完全按照上面步骤来操作。

**Comment by Andy-one1** [comment]
前人栽树：002文献导入之后，直接选中文献段落进行学校段落等设置，字号最后再进行手动修改为五号即可。不敢refresh了。

**Comment by redleafnew** [comment]
定稿后这样操作也可以，但参考文献一变动就会恢复。

**Comment by Andy-one1** [comment]
好的，谢谢

**Comment by Andy-one1** [comment]
谢和平, 张吉雄, 高峰, 等. 煤矿负碳高效充填开采理论与技术构想[J]. 煤炭学报: 1-11.
第110页第10段-[9]	谢和平,...: 1-11.
-错误-(条目[9])缺少年卷期项，或者年前面不是逗号（可参阅GB7714-2015的4.3和4.4小节）

2024-4-5-00:00,002出现错误。缺少年份或者期卷项

**Comment by redleafnew** [comment]
> 谢和平, 张吉雄, 高峰, 等. 煤矿负碳高效充填开采理论与技术构想[J]. 煤炭学报: 1-11. 第110页第10段-[9] 谢和平,...: 1-11. -错误-(条目[9])缺少年卷期项，或者年前面不是逗号（可参阅GB7714-2015的4.3和4.4小节）
> 
> 2024-4-5-00:00,002出现错误。缺少年份或者期卷项

大概率不是csl的问题，是你条目的问题。
如果不确定，把条目的JSON格式上传上来。
