### ISSUE TITLE
您好，我想求一下Zotero软件里面中国矿业大学的参考文献格式，我在您的帖子上面没有找到，请问可以测试一下吗？ 参考文献格式示例如下： [1]	Marquez-Andrade M A, Roumani H, Vlajic N. Chapter 20 - CSRF and Big Data: Rethinking Cross-Site Request Forgery in Light of Big Data[M]//Akhgar B, Arabnia H R. Emerging Trends in ICT Security. Boston: Morgan Kaufmann, 2014:315-334.  [1]	王国法, 庞义辉, 任怀伟, 等. 矿山智能化建设的挑战与思考[J]. 智能矿山, 2022,3(10):2-15.

### ISSUE THREAD

**Issue by Andy-one1** [redleafnew/Chinese-STD-GB-T-7714-related-csl#290]
**样式信息**

- 期刊/学校名称：[例如 心理学报/清华大学研究生学位论文]

- 英文名称：[例如 Acta Psychologica Sinica / Tsinghua University]

- 参考文献格式：[例如 <https://journal.psych.ac.cn/xlxb/fileup/0439-755X/ITEM/20220223114333.pdf>]

- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
按照模板格式修改 #289。同一件事不要新开 issue。
