### ISSUE TITLE
您好，能否申请一下JOURNAL OF MODERN POWER SYSTEMS AND CLEAN ENERGY（MPCE）

### ISSUE THREAD

**Issue by han-pf** [redleafnew/Chinese-STD-GB-T-7714-related-csl#294]
**样式信息**

- 期刊/学校名称：JOURNAL OF MODERN POWER SYSTEMS AND CLEAN ENERGY

- 英文名称：JOURNAL OF MODERN POWER SYSTEMS AND CLEAN ENERGY

- 参考文献格式：[ <http://www.mpce.info/uploadfile/mpce/20240408/MPCE%20Word%20Template.docx>]

- 参考文献格式的更新日期：[2022-10-4]

- （学校）文件号：[ ]

- （期刊）ISSN 号：[2196-5420]

- （期刊）相关领域：[engineering]

**测试条目**

Zotero ID:sjtu666

**其他样式信息**

**Comment by zepinglee** [comment]
官方的仓库有 <https://github.com/citation-style-language/styles/blob/master/dependent/journal-of-modern-power-systems-and-clean-energy.csl>，使用的是 springer-basic-brackets 样式。

**Comment by han-pf** [comment]
明白啦，谢谢您~

从 Windows 版邮件发送

发件人: Zeping Lee
发送时间: 2024年4月11日 18:15
收件人: redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送: han-pf; Author
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 您好，能否申请一下JOURNAL OF MODERN POWER SYSTEMS AND CLEAN ENERGY（MPCE） (Issue #294)

官方的仓库有 https://github.com/citation-style-language/styles/blob/master/dependent/journal-of-modern-power-systems-and-clean-energy.csl，使用的是 springer-basic-brackets 样式。

**Comment by han-pf** [comment]
很抱歉啊，刚才回复有点急了。
您连接中这个我试了（之前也试过），和MPCE现在用的格式不一样了（如果我没有弄错的话）。所以想请您更新一下。

从 Windows 版邮件发送

发件人: Zeping Lee
发送时间: 2024年4月11日 18:15
收件人: redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送: han-pf; Author
主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 您好，能否申请一下JOURNAL OF MODERN POWER SYSTEMS AND CLEAN ENERGY（MPCE） (Issue #294)

官方的仓库有 https://github.com/citation-style-language/styles/blob/master/dependent/journal-of-modern-power-systems-and-clean-energy.csl，使用的是 springer-basic-brackets 样式。

**Comment by zepinglee** [comment]
从这个示例来看很像 IEEE 的。你不妨先用 IEEE，有什么差异列出来方便我们修改。

**Comment by han-pf** [comment]
在期刊类型的文献上的区别是：
1、IEEE中作者是全部给出的，MPCE是最多三个作者，然后用et al。
2、IEEE中用的是期刊缩写，MPCE用的是期刊全称。
谢谢哈~

**Comment by redleafnew** [comment]
用

> 在期刊类型的文献上的区别是：
> 1、IEEE中作者是全部给出的，MPCE是最多三个作者，然后用et al。
> 2、IEEE中用的是期刊缩写，MPCE用的是期刊全称。
> 

要求，修改这个？
[https://github.com/citation-style-language/styles/blob/master/dependent/journal-of-modern-power-systems-and-clean-energy.csl](https://github.com/citation-style-language/styles/blob/master/dependent/journal-of-modern-power-systems-and-clean-energy.csl%EF%BC%8C%E4%BD%BF%E7%94%A8%E7%9A%84%E6%98%AF)

**Comment by zepinglee** [comment]
在 81c89b6 中添加。

**Comment by han-pf** [comment]
> 在 [81c89b6](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/81c89b6b1f997727068dffedd4b8d4c347703bb9) 中添加。

收到，万分感谢！

**Comment by redleafnew** [comment]
如果完成，请关闭。

**Comment by dyy-08** [comment]
> 在期刊类型的文献上的区别是： 1、IEEE中作者是全部给出的，MPCE是最多三个作者，然后用et al。 2、IEEE中用的是期刊缩写，MPCE用的是期刊全称。 谢谢哈~

请问是否有MPCE的tex模版

**Comment by redleafnew** [comment]
> > 在期刊类型的文献上的区别是： 1、IEEE中作者是全部给出的，MPCE是最多三个作者，然后用et al。 2、IEEE中用的是期刊缩写，MPCE用的是期刊全称。 谢谢哈~
> 
> 请问是否有MPCE的tex模版

可以到期刊主页上找找
