### ISSUE TITLE
您好，可以添加中国林科院毕业论文的样式吗？

### ISSUE THREAD

**Issue by tom100to** [redleafnew/Chinese-STD-GB-T-7714-related-csl#295]
**样式信息**

<中文期刊例如：[1] 洪伟，吴承祯，林成来等．福建龙栖山森林群落林窗边缘效应研究[J]．林业科学，2000，36(2)：33-38.
西文期刊例如：[1] Chavez A S，Saltzberg C J, Kenagy G J．Genetic and phenotypic variation across a hybrid zone between ecologically divergent tree squirrels (Tamiasciurus) [J]．Molecular Ecology，2001，20(6)：3350-3366.
[2] 李博．生态学[M]．北京：中国林业出版社，1992，7-13.
[3] 陈善元．中国家养山羊和绵羊的起源与遗传多样性研究[D]．云南大学博士学位论文，2006，75-78.
[4] 周海滨，费本华，江泽慧．结构用规格材刚度性能的动态评价. 2006年全国博士生学术论坛-林业及生态建设领域相关学科论文集（下），2006，1773-1777.

>

- 期刊/学校名称：[中国林科院研究生学位论文]

**其他样式信息**

<与南京农业大学的主要在标点符号上有差异 1.xxx，等 变为xx等 2.学位论文页数前面为逗号>

**Comment by cafzjw** [comment]
1.7.2.1文后参考文献编写项目
文后参考文献书写，只列作者阅读过、在正文中被引用过的正式发表的文献资料。书写格式包括作者、题目、来源，外文文献应列出原名，应符合GB/T 7714-2015《文后参考文献著录规则》。常用参考文献编写项目规定如下：
（1）期刊
序号└┘（该符号表示空格，下同）作者（超过3人时，仅列出3人，其余作者用“等”字概括，作者之间用逗号区分开）．论文题目．期刊名，发表年份，卷号（期号）：起止页码.
中文期刊例如：[1] 洪伟，吴承祯，林成来等．福建龙栖山森林群落林窗边缘效应研究[J]．林业科学，2000，36(2)：33-38.
西文期刊例如：[1] Chavez A S，Saltzberg C J, Kenagy G J．Genetic and phenotypic variation across a hybrid zone between ecologically divergent tree squirrels (Tamiasciurus) [J]．Molecular Ecology，2001，20(6)：3350-3366.
（2）专著
序号└┘作者．专著名称．版次（第一版应省略）．地点：出版社，年份，引用部分起止页
例如：[2] 李博．生态学[M]．北京：中国林业出版社，1992，7-13.
翻译图书文献还需加译者，格式如下：
序号└┘作者．书名．译者．版次．出版地：出版社，年份：引用部分起止页.
（3）学位论文
序号└┘作者．论文题目．作者所在院校硕（博）士学位论文，年份，起止页码
例如：[3] 陈善元．中国家养山羊和绵羊的起源与遗传多样性研究[D]．云南大学博士学位论文，2006，75-78.
（4）论文集
序号└┘作者．论文名称．论文集名称，出版年份，起止页码
例如：[4] 周海滨，费本华，江泽慧．结构用规格材刚度性能的动态评价. 2006年全国博士生学术论坛-林业及生态建设领域相关学科论文集（下），2006，1773-1777.
注意：西文文献中第一个词的第一个字母大写，余者小写；俄文文献名第一个词和专有名词的第一个字母大写，余者小写；日文文献中的汉字须用日文汉字，不得用中文汉字、简化汉字代替。文献中的外文字母一律用正体，拉丁名除外。外文姓名按国际惯例，将作者名的缩写置前，作者姓置后。

**Comment by zepinglee** [comment]
按照 issue 模板给出格式要求的官方链接、更新日期等信息。

**Comment by cafzjw** [comment]
[林科院必读2024.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14955107/2024.zip)
没有官方链接，只有个压缩包

**Comment by cafzjw** [comment]
> 按照 issue 模板给出格式要求的官方链接、更新日期等信息。

没有官方链接，只有个压缩包

**Comment by redleafnew** [comment]
> **样式信息**
> 
> <中文期刊例如：[1] 洪伟，吴承祯，林成来等．福建龙栖山森林群落林窗边缘效应研究[J]．林业科学，2000，36(2)：33-38. 西文期刊例如：[1] Chavez A S，Saltzberg C J, Kenagy G J．Genetic and phenotypic variation across a hybrid zone between ecologically divergent tree squirrels (Tamiasciurus) [J]．Molecular Ecology，2001，20(6)：3350-3366. [2] 李博．生态学[M]．北京：中国林业出版社，1992，7-13. [3] 陈善元．中国家养山羊和绵羊的起源与遗传多样性研究[D]．云南大学博士学位论文，2006，75-78. [4] 周海滨，费本华，江泽慧．结构用规格材刚度性能的动态评价. 2006年全国博士生学术论坛-林业及生态建设领域相关学科论文集（下），2006，1773-1777.
> 
> > 
> 
> * 期刊/学校名称：[中国林科院研究生学位论文]
> 
> **其他样式信息**
> 
> <与南京农业大学的主要在标点符号上有差异 1.xxx，等 变为xx等 2.学位论文页数前面为逗号>

把这些参考文献条目导出为JSON格式，选中条目，右击，导出 JSON格式。

**Comment by tom100to** [comment]
> > **样式信息**
> > <中文期刊例如：[1] 洪伟，吴承祯，林成来等．福建龙栖山森林群落林窗边缘效应研究[J]．林业科学，2000，36(2)：33-38. 西文期刊例如：[1] Chavez A S，Saltzberg C J, Kenagy G J．Genetic and phenotypic variation across a hybrid zone between ecologically divergent tree squirrels (Tamiasciurus) [J]．Molecular Ecology，2001，20(6)：3350-3366. [2] 李博．生态学[M]．北京：中国林业出版社，1992，7-13. [3] 陈善元．中国家养山羊和绵羊的起源与遗传多样性研究[D]．云南大学博士学位论文，2006，75-78. [4] 周海滨，费本华，江泽慧．结构用规格材刚度性能的动态评价. 2006年全国博士生学术论坛-林业及生态建设领域相关学科论文集（下），2006，1773-1777.
> > > 
> > 
> > 
> > 
> > * 期刊/学校名称：[中国林科院研究生学位论文]
> > 
> > **其他样式信息**
> > <与南京农业大学的主要在标点符号上有差异 1.xxx，等 变为xx等 2.学位论文页数前面为逗号>
> 
> 把这些参考文献条目导出为JSON格式，选中条目，右击，导出 JSON格式。 与南京农业大学最接近？csl编号是什么？

405

**Comment by tom100to** [comment]
> > > **样式信息**
> > > <中文期刊例如：[1] 洪伟，吴承祯，林成来等．福建龙栖山森林群落林窗边缘效应研究[J]．林业科学，2000，36(2)：33-38. 西文期刊例如：[1] Chavez A S，Saltzberg C J, Kenagy G J．Genetic and phenotypic variation across a hybrid zone between ecologically divergent tree squirrels (Tamiasciurus) [J]．Molecular Ecology，2001，20(6)：3350-3366. [2] 李博．生态学[M]．北京：中国林业出版社，1992，7-13. [3] 陈善元．中国家养山羊和绵羊的起源与遗传多样性研究[D]．云南大学博士学位论文，2006，75-78. [4] 周海滨，费本华，江泽慧．结构用规格材刚度性能的动态评价. 2006年全国博士生学术论坛-林业及生态建设领域相关学科论文集（下），2006，1773-1777.
> > > > 
> > > 
> > > 
> > > 
> > > * 期刊/学校名称：[中国林科院研究生学位论文]
> > > 
> > > **其他样式信息**
> > > <与南京农业大学的主要在标点符号上有差异 1.xxx，等 变为xx等 2.学位论文页数前面为逗号>
> > 
> > 
> > 把这些参考文献条目导出为JSON格式，选中条目，右击，导出 JSON格式。 与南京农业大学最接近？csl编号是什么？
> 
> 405

怎样导json没有发现

**Comment by redleafnew** [comment]
选中需要导出的条目，右击，导出，JSON格式。

**Comment by tom100to** [comment]
> 选中需要导出的条目，右击，导出，JSON格式。

你好，这些是压缩包里的，不是我的，我无法导出

**Comment by tom100to** [comment]
> 你好，这些是压缩包里的，不是我的，我无法导出

你好，这些是压缩包里的，不是我的，我无法导出

**Comment by redleafnew** [comment]
可以想办法录入到Zotero，方便测试。

**Comment by zepinglee** [comment]
在 25c59fd 中添加。

顺便吐槽一下，“注意”里说“将外文作者名的缩写置前，作者姓置后”，但后面的示例都是姓前名后。

<img width="793" alt="Screenshot 2024-04-21 at 12 38 32" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/3571c0b3-3412-4100-a653-dfd48b9ab543">

<img width="788" alt="Screenshot 2024-04-21 at 12 39 59" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/7d6a3340-c4c8-4249-9064-2010559cde06">
