### ISSUE TITLE
你好！北航格式中，文献编号从2位增加到3位（【99】到【100】）编号后的文本未对齐

### ISSUE THREAD

**Issue by Lv-ocean** [redleafnew/Chinese-STD-GB-T-7714-related-csl#296]
**描述错误**

CSL 样式：中文-STD-GB-T-7714-相关-csl/420beihang-university.csl
（之前请作者修改过一次，在#246）

文献编号从2位增加到3位（【99】到【100】）编号后的文本未对齐，麻烦作者帮忙完善。

**屏幕截图**

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/87459946/9e1dca30-8aa5-44a2-96ac-47d0572c632a)

再附上一个期望达到的效果图
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/87459946/ddd68135-516d-4c7d-be6e-17edf180a6d0)

**条目信息**

[
	{
		"id": "maitlandBackscatteringDetectorEBSD2006",
		"type": "chapter",
		"container-title": "Scanning Microscopy for Nanotechnology: Techniques and Applications",
		"page": "41–75",
		"publisher": "Springer",
		"source": "Google Scholar",
		"title": "Backscattering detector and EBSD in nanomaterials characterization",
		"author": [
			{
				"family": "Maitland",
				"given": "Tim"
			},
			{
				"family": "Sitzman",
				"given": "Scott"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2006"
				]
			]
		}
	}
]

**其他相关信息**

再次感谢作者~！

**Comment by redleafnew** [comment]
https://zhuanlan.zhihu.com/p/366711117
不知道是不是适合2→3位的

**Comment by zepinglee** [comment]
@Lv-ocean 你需要增加悬挂缩进和制表符的宽度，这些都在 Word 中设置，与 CSL 无关。

**Comment by Lv-ocean** [comment]
> @Lv-ocean 你需要增加悬挂缩进和制表符的宽度。这些都在 Word 中设置，与 CSL 无关。

感谢帮忙，我最终参考了这个[https://www.dentalearner.com/archives/4539](url)，将原有字段改成了  <bibliography entry-spacing=”0″ et-al-min=”6″ et-al-use-first=”5″ second-field-align=”flush”>

现在可以完全对齐了

**Comment by northword** [comment]
这个应该是切换一次样式就正常了的吧（zo的老bug了

**Comment by sandyowlet** [comment]
> 这个应该是切换一次样式就正常了的吧（zo的老bug了

+1, 这是真正的解决方案.
