### ISSUE TITLE
《生态学报》引文样式

### ISSUE THREAD

**Issue by yzj-ai** [redleafnew/Chinese-STD-GB-T-7714-related-csl#298]
**样式信息**

- 期刊名称：生态学报

- 英文名称：Acta Ecologica Sinica 

- 参考文献格式：[<https://www.ecologica.cn/stxb/ch/first_menu.aspx?parent_id=20080722101552001>]

- 参考文献格式的更新日期：不确定

- （期刊）ISSN 号：[1000-0933]

- （期刊）相关领域：[ biology]

**测试条目**

Zotero ID:1034421302@qq.com

**其他样式信息**

**Comment by redleafnew** [comment]
提供测试条目，选中需要导出的条目，右击，导出，JSON格式。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
另外，这样要求与仓库中哪个最拉扯，需要做什么修改。

**Comment by zepinglee** [comment]
这个格式跟国标很接近，不必录入文献了。去掉文献类型标识和 `et-al-min` 即可。

**Comment by yzj-ai** [comment]
好的，我这边不需要再操作了吧




YZJ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 《生态学报》引文样式 (Issue #298)





 
这个格式跟国标很接近，不必录入文献了。去掉文献类型标识和 et-al-min 即可。

**Comment by yzj-ai** [comment]
它这个特别要求：正文内参考文献按顺序号标注在文字右上角时，连续文献号请一定确认使用一字线符号“—”。怎么处理呀
特别要求：正文内参考文献按顺序号标注在文字右上角时，连续文献号请一定确认使用一字线符号“—”。


YZJ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 《生态学报》引文样式 (Issue #298)





 
这个格式跟国标很接近，不必录入文献了。去掉文献类型标识和 et-al-min 即可。

**Comment by zepinglee** [comment]
> 它这个特别要求：正文内参考文献按顺序号标注在文字右上角时，连续文献号请一定确认使用一字线符号“—”。怎么处理呀

CSL 无法实现，会固定使用 en dash “–”。只能全局搜索替换一下。

**Comment by yzj-ai** [comment]
好的，谢谢了


YZJ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 《生态学报》引文样式 (Issue #298)





  
它这个特别要求：正文内参考文献按顺序号标注在文字右上角时，连续文献号请一定确认使用一字线符号“—”。怎么处理呀
  
CSL 无法实现，会固定使用 en dash “–”。只能全局搜索替换一下。

**Comment by zepinglee** [comment]
在 e9af12d 中添加，测试效果见 [tests/styles/121acta-ecologica-sinica/test.md](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/121acta-ecologica-sinica/test.md)。你看看还有没有别的问题。

**Comment by yzj-ai** [comment]
暂时没有了，谢谢




YZJ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 《生态学报》引文样式 (Issue #298)





 
在 e9af12d 中添加，测试效果见 tests/styles/121acta-ecologica-sinica/test.md。你看看还有没有别的问题。

**Comment by zepinglee** [comment]
@redleafnew 与国标相近的样式可以直接利用仓库中已录入的国标示例文献作为测试，就不必要求他们录入测试文献了。

另外他们大都不太熟悉参考文献以及国标，所以之前找的相似样式大都不靠谱。还是由我们判断与国标的相似度，以及是否需要录入测试文献。
