### ISSUE TITLE
希望能提供北京大学硕士学位论文的引文格式，非常感谢！

### ISSUE THREAD

**Issue by obtx** [redleafnew/Chinese-STD-GB-T-7714-related-csl#299]
**样式信息**

- 期刊/学校名称：[北京大学研究生学位论文]

- 英文名称：[Peking University]

- 参考文献格式：[ <https://grs.pku.edu.cn/xwgz11/xwsy11/ssxw111/clxz08/346393.htm>]

- 参考文献格式的更新日期：[ 2024-02-29 ]

- （北京大学）文件：硕士研究生学位论文格式模板(2024)

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by obtx** [comment]
顺序编码制的格式如下，供参考

[1] Intel Corperation, http://download.intel.com/pressroom/kits/IntelProcessorHistory.pdf.
[2] Intel Corperation, http://www.intel.com/content/dam/www/public/us/en/documents/presentation/
revolutionary-22nm-transistor-technology-presentation.pdf.
[3] I. Žutić, J. Fabian and S. Das Sarma, Spintronics: Fundamentals and applications, Reviews of Modern Physics 76 (2), 323-410 (2004).
[4] R. Hanson, L. Kouwenhoven, J. Petta, S. Tarucha and L. Vandersypen, Spins in few-electron quantum dots, Reviews of Modern Physics 79 (4), 1217 (2007).
[5] D. Loss and D. P. DiVincenzo, Quantum computation with quantum dots,Physical Review A 57 (1), 120 (1998).

**Comment by redleafnew** [comment]
提供测试条目，选中需要导出的条目，右击，导出，JSON格式。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
这个格式略奇怪，尤其是出版年的位置。而且示例类型也很有限，只有网页和期刊文章。所有有没有更完整的格式要求？我印象中你们有“写作指南”之类的吧。

**Comment by obtx** [comment]
@zepinglee 确实有写作指南这是写作指南中有关参考文献的部分![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/9ede7591-6675-4ec8-8bfd-eafbe00f3a41)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/1b697417-40c2-4593-b7b5-ad02e9271d33)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/dc7af647-9803-45dc-860f-2cd1b2c10909)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/4bf76dc9-a02e-4c55-b163-9406790c089c)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/f739e922-d3cc-47cf-91ae-b689e2f44cfe)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/0c308c92-b7e2-452c-a1c7-66da6753c455)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/63de28f2-db34-456d-978b-7116bd42e75a)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/7ff4aada-0bdb-4578-87b6-0f36d3485c9a)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/11d7a5bb-baa3-4429-8889-a7ece7e57193)

**Comment by obtx** [comment]
@redleafnew 官网提供的模板参考文献格式是文本的格式，无法导出json[<https://grs.pku.edu.cn/xwgz11/xwsy11/ssxw111/clxz08/346393.htm>]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/58609430/0dd4aefe-5fe8-4392-b8cf-d6397148acb1)

**Comment by zepinglee** [comment]
> 确实有写作指南，以下写作指南中有关参考文献的部分，可供参考

有没有学校官网的链接？我们需要记录下来。

这个跟国标差不多，可以不必录入测试文献了。

《写作指南》要求的是“年卷期页”，而模板中变成了“卷期页年”，实际按哪个执行？

<img width="828" alt="Screenshot 2024-04-23 at 14 07 30" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/db545675-b6a4-43e9-b01f-e4b3c956a666">

<img width="768" alt="Screenshot 2024-04-23 at 14 08 13" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/664c8947-921e-4fc8-ac02-81f87f3c0992">

哈哈哈

<img width="591" alt="Screenshot 2024-04-23 at 14 10 23" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/00ac4704-ee63-46c2-895d-f36d62909244">

**Comment by obtx** [comment]
@redleafnew 北京大学研究生学位论文写作指南的链接如下，可供参考，写作指南和模板的冲突该选哪个其实我也不太清楚[捂脸]：[<https://www.chem.pku.edu.cn/page/gaofenzi/docs/20201115160553622376.pdf>]
