### ISSUE TITLE
英文et al仍然显示为等

### ISSUE THREAD

**Issue by xiangrong7** [redleafnew/Chinese-STD-GB-T-7714-related-csl#3]
您好，我用这个csl文件
![image](https://user-images.githubusercontent.com/24288935/107481620-77ebdc80-6bb9-11eb-9dae-2ef6bb92018c.png)
英文et al仍然显示为等
如图
![image](https://user-images.githubusercontent.com/24288935/107481861-d3b66580-6bb9-11eb-923b-2b2c7ac03f40.png)
请问这个使用和zotero版本有关吗

**Comment by redleafnew** [comment]
应该没有关系，修改文献语言了吗？

**Comment by xiangrong7** [comment]
![image](https://user-images.githubusercontent.com/24288935/107484417-58ef4980-6bbd-11eb-864a-6808625cd2a9.png)

是指这个语言吗？这个我也不能修改。用其他的英文样式，就是et al

**Comment by redleafnew** [comment]
如果使用了支持中文作者超过3个为“等”，英文为“et al”的csl，但显示不正常需要在Zotero或JurisM中将英文文献Info中language字段修改为en。或是需要将显示不正常的文献删除后重新插入。

使用详情参见基于GB/T-7714-2015的Style实现同时生成“et al”和“等”的方法https://zhuanlan.zhihu.com/p/320253145。

修改语言参见https://zhuanlan.zhihu.com/p/341989158或https://zhuanlan.zhihu.com/p/314928204。

**Comment by redleafnew** [comment]
解决了吗？解决后我就关闭了。
