### ISSUE TITLE
申请添加钢铁研究学报中文版的参考文献格式

### ISSUE THREAD

**Issue by lcc1247** [redleafnew/Chinese-STD-GB-T-7714-related-csl#300]
**样式信息**

- 期刊/学校名称：钢铁研究学报中文版

- 英文名称：JOURNAL OF IRON AND STEEL RESEARCH

- 参考文献格式：http://www.chinamet.cn/Jweb_gtyjxb_cn/CN/column/column7.shtml

- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：1001-0963

- （期刊）相关领域：[例如 psychology]

[钢铁研究学报中文版模板.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15071820/default.pdf)

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
感觉直接使用 002 就可以。这个似乎只有期刊论文的示例？

**Comment by lcc1247** [comment]
我上传了期刊格式要求，最后面有参考文献样式。

**Comment by lcc1247** [comment]
麻烦在于他要求名只大写首字母，全部按照姓+名的格式。其它的应该和主流的一样

**Comment by zepinglee** [comment]
> 我上传了期刊格式要求，最后面有参考文献样式。

哪个？我好像没注意到。

**Comment by lcc1247** [comment]
它罗列的那几个文献就是大致的引用格式。退修的格式，那是指出来哪些有问题的

**Comment by zepinglee** [comment]
在 4a413f3 中添加。

**Comment by lcc1247** [comment]
感谢感谢
