### ISSUE TITLE
申请添加水利水运工程学报的参考文献格式

### ISSUE THREAD

**Issue by sjqfy** [redleafnew/Chinese-STD-GB-T-7714-related-csl#301]
**样式信息**

- 期刊/学校名称：水利水运工程学报

- 英文名称：HYDRO-SCIENCEANDENGINEERING

- 参考文献格式：http://slsy.nhri.cn/

- 参考文献格式的更新日期：2017

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：1009-640X

- （期刊）相关领域：engineering

**测试条目**

Zotero ID:

**其他样式信息**
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/122252136/037ba8a3-4119-43c7-952e-27cf20996e20)
中文文献需要跟随英文翻译

**Comment by sjqfy** [comment]
[投稿论文格式模板.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15077949/default.pdf)

**Comment by zepinglee** [comment]
在 cc6a852 中添加。英文翻译填写方式参考《心理学报》的示例文献 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/7SP7XX8X>。
