### ISSUE TITLE
pubmed格式参考文献

### ISSUE THREAD

**Issue by anshangtangyuan** [redleafnew/Chinese-STD-GB-T-7714-related-csl#302]
pubmed格式 全部作者. 题目. 期刊缩写. 年份; 期(卷): 页码.     每个标点符号后 有一个空格

[1] Zhang Z, Liu Y, Lin S, Wang Q. Preparation and properties of glutaraldehyde crosslinked poly(vinyl alcohol) membrane with gradient structure. J Polym Res. 2020; 27(7): 228.
确需中文小组进行修改 感谢!!!

**Comment by redleafnew** [comment]
什么意思？这是哪个期刊或学校要求的吗？

**Comment by anshangtangyuan** [comment]
> 什么意思？这是哪个期刊或学校要求的吗？
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/125590994/3d95317d-1375-417d-83fa-4abe48d1921e)
https://pubmed.ncbi.nlm.nih.gov/37407517/
图片中的格式，删除doi

**Comment by zepinglee** [comment]
这个不是 pubmed 的格式，而是你选择的 AMA 格式。直接使用官方仓库的 <https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl> 即可。

**Comment by anshangtangyuan** [comment]
> 这个不是 pubmed 的格式，而是你选择的 AMA 格式。直接使用官方仓库的 https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl 即可。

那  标点符号后需要后空格  应该怎么改啊

**Comment by zepinglee** [comment]
> > 这个不是 pubmed 的格式，而是你选择的 AMA 格式。直接使用官方仓库的 https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl 即可。
> 
> 那 标点符号后需要后空格 应该怎么改啊

英文每个体例有自己的空格要求，不要乱改。

**Comment by anshangtangyuan** [comment]
> > > 这个不是 pubmed 的格式，而是你选择的 AMA 格式。直接使用官方仓库的 https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl 即可。
> > 
> > 
> > 那 标点符号后需要后空格 应该怎么改啊
> 
> 英文每个体例有自己的空格要求，不要乱改。

不改没法用啊  看了下格式并不一样，每个标点符号后没有空格，还有序号不是[1],而是1

**Comment by zepinglee** [comment]
> 不改没法用啊 看了下格式并不一样，每个标点符号后没有空格，还有序号不是[1],而是1

你投稿的期刊到底要求什么格式？按照 issue 模板提供官方链接等信息。

**Comment by anshangtangyuan** [comment]
> > 不改没法用啊 看了下格式并不一样，每个标点符号后没有空格，还有序号不是[1],而是1
> 
> 你投稿的期刊到底要求什么格式？按照 issue 模板提供官方链接等信息。

pubmed格式 全部作者. 题目. 期刊缩写. 年份; 期(卷): 页码. 每个标点符号后 有一个空格   就这种格式啊

[1] Zhang Z, Liu Y, Lin S, Wang Q. Preparation and properties of glutaraldehyde crosslinked poly(vinyl alcohol) membrane with gradient structure. J Polym Res. 2020; 27(7): 228.
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/125590994/a12cd8a8-9071-457d-989d-000a48399f14)

**Comment by zepinglee** [comment]
> 这个不是 pubmed 的格式，而是你选择的 AMA 格式。直接使用官方仓库的 https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl 即可。

那你就用 AMA 格式。DOI 是 AMA 要求的，不要修改。

**Comment by zepinglee** [comment]
我查了一下，根据 <https://www.nlm.nih.gov/bsd/policy/cit_format.html>，PubMed 使用的是 NLM 格式（<https://www.ncbi.nlm.nih.gov/books/NBK7256/>）。该样式也称为 Vancouver 格式（<https://en.wikipedia.org/wiki/Vancouver_system>）。所以你应该使用的是 <https://github.com/citation-style-language/styles/blob/master/vancouver.csl>。

NLM 格式会输出 DOI。如果你自己需要去掉 DOI，请提供某期刊的官网链接，其中要求使用没有 DOI 的 PubMed 格式。因为我们一般不会针对个人的需求进行定制。
