### ISSUE TITLE
卷号缺失导致参考文献种年后无“,”

### ISSUE THREAD

**Issue by 90zm** [redleafnew/Chinese-STD-GB-T-7714-related-csl#303]
**描述错误**

CSL 样式：[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)

卷号缺失，年份后无逗号。

**屏幕截图**

![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44014367/8e2aa17d-ecbb-451c-9af6-1d139c5f81e2)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44014367/5f81b300-b58c-478b-836c-3e58bf7c6113)
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44014367/3725ef71-e37a-4e72-80aa-e672396b921a)

**条目信息**

```json
[
	{
		"id": "QianHuiTianZuoTianDeZhiYuYuHuaXing1978",
		"type": "article-journal",
		"abstract": "<正>滞育是昆虫系统发育中所形成的一种生理遗传特性,是为了它自身的生存必须保持的比较保守的一种属性,因此,其形式、生理功能和对环境因素的反应都是受遗传基因的控制的。滞育的机制愈完善,则生命的活动时期与一年中对其最有利的时期(气候条件和食物条件等)的配合愈能园满地实现,有机体在滞育时对各种不利于其活动的客观条件的稳定性也愈高,可以说:滞育是有机体对环境适应的标志。 滞育的发生,决定于它发生前的个体发育阶段中的生活条件,滞育涉及比较复杂的生理机制,有机体显然地有它特殊的新陈代谢型式,即与异化作用的抑制,贮存物质和结合水的积存相联系的。",
		"container-title": "广西蚕业通讯",
		"ISSN": "1006-1657",
		"issue": "02",
		"language": "zh-CN",
		"page": "19-26",
		"title": "柞蚕的滞育与化性",
		"author": [
			{
				"family": "钱惠田",
				"given": ""
			}
		],
		"editor": [
			{
				"family": "钱惠田",
				"given": ""
			}
		],
		"issued": {
			"date-parts": [
				[
					"1978"
				]
			]
		}
	}
]
```

**Comment by zepinglee** [comment]
另外期号一般不带前缀“0”，建议使用最新的网站 translator。

**Comment by 90zm** [comment]
> <img alt="Screenshot 2024-04-28 at 10 49 40" width="805" src="https://private-user-images.githubusercontent.com/12290822/326225381-08f96a04-4622-4feb-a3a6-2c4b58265a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM1MjksIm5iZiI6MTcxNDI3MzIyOSwicGF0aCI6Ii8xMjI5MDgyMi8zMjYyMjUzODEtMDhmOTZhMDQtNDYyMi00ZmViLWEzYTYtMmM0YjU4MjY1YTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAzMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmJhY2IzNmMyYzNjMjlkMWIwZGQ1NjQxMzQ1MzdkMGM5NDQzMjNmODAxOGRmYjQ0NGUwMGFiYWQwNzlhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rWFwj2snRkGO92uyP53UXUrkMxpxu_S0tFIXBRYrvuE">
> 另外还有国标起草人的文章 http://bjxb.cessp.org.cn/ch/reader/view_abstract.aspx?file_no=20150411&flag=1。
> 
> <img alt="Screenshot 2024-04-28 at 10 51 03" width="481" src="https://private-user-images.githubusercontent.com/12290822/326225648-5893e5df-2dd7-4eee-8f6c-e16bad69a08a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM1MjksIm5iZiI6MTcxNDI3MzIyOSwicGF0aCI6Ii8xMjI5MDgyMi8zMjYyMjU2NDgtNTg5M2U1ZGYtMmRkNy00ZWVlLThmNmMtZTE2YmFkNjlhMDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAzMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmFjMWQxMThkMTVjNGIyY2YyOWJjYzk3MjIyYWRkOTViZGE2ZTlkNWQ0NWY3Yzk4YzgyMjI0MWQyMWI3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zT_kIzO5NWjmtDx-bc9WPe5lpvnuJcgVmlFzlEYHbW8">

感谢您的回复，又学到了些新的知识。

**Comment by 90zm** [comment]
> 最新的网站 translator

最新的网站 translator是指什么？知网的新版吗？向您请教一下。

**Comment by zepinglee** [comment]
> 最新的网站 translator是指什么？知网的新版吗？向您请教一下。

是的，<https://github.com/l0o0/translators_CN>。可以使用茉莉花更新。

**Comment by 90zm** [comment]
> > 最新的网站 translator是指什么？知网的新版吗？向您请教一下。
> 
> 是的，https://github.com/l0o0/translators_CN。可以使用茉莉花更新。

收到，再次感谢您！
