### ISSUE TITLE
申请《传播与社会学刊》

### ISSUE THREAD

**Issue by lequn-F** [redleafnew/Chinese-STD-GB-T-7714-related-csl#307]
**样式信息**

- 期刊名称：传播与社会学刊

- 参考文献格式：http://cschinese.com/submission03.asp

**四、參考文獻**

（一）僅需羅列文稿曾徵引之文獻。

（二）中西文書目並存時，先排中文，後排西文。

（三）中文作者（或編者）以姓氏筆劃排序；英文作者（或編者）以字母次序排列。中文作者（或編者）用全名，英文作者（或編者）姓在前，名縮寫於後。

（四）同一作者的著作，按出版年份排列，舊著在前，新著在後。若出自同一年份，在年份後標示abc，如（2002a）、（2002b）、（2002c）。

（五）文獻資料一般包括作者姓名、出版時間、標題、卷／期數、頁數、出版地、出版社等。

（六）範例

1、期刊論文

例1：祝建華（2001）。〈中文傳播研究之理論化與本土化：以受眾及媒介效果整合理論為例〉。《新聞學研究》，第68期，頁1–22。

例2：Huang, Y. H. (2000). The personal in\_uence model and gao guanxi in Taiwan Chinese public relations. _Public Relations Review_, _26_, 216–239.

例3：（作者多於一位）Grunig, J. E., Grunig, L. A., Sriramesh, K., Huang, Y. H., & Lyra, A. (1995). Models of public relations in an international setting. _Journal of Public Relations Research_, _7_(3), 163–187.

2、研討會論文

例1：徐美苓（2004 年7 月）。〈新聞乎？廣告乎？醫療風險資訊的媒體再現與倫理〉，「中華傳播學會2004 年學術研討會」論文，澳門。

例2：Peng, B. (2003, May). _Voter cynicism, perception of media negativism and voting behavior in Taiwan’s 2001 election_.Paper presented at 2003 International Communication Association Annual Conference, San Diego.

3、書籍

例1：李金銓（2004）。《超越西方霸權：傳媒與文化中國的現代性》。香港：牛津大學出版社。

例2：陳國明（編）（2004）。《中華傳播理論與原則》。台北：五南。

例3：Grunig, J. E., & Hunt, T. (1984). _Managing public relations_.New York: Holt, Rinehart & Winston.

例4：（修訂版）：Rosenthal, R. (1987). _Meta-analytic procedures for social research_ (Rev. ed.). Newbury Park, CA: Sage.

例5：（文集）：Sheppard, B. H., Bazerman, M. H., & Lewicki, R. J. (Eds). (1990). _Research on negotiation in organizations_. Greenwich, CT: JAI Press.

4、文集篇章

例1：汪琪（2004）。〈全球化與文化產品的混雜化〉。郭鎮之（編），《全球化與文化間傳播》（頁240–254）。北京：北京廣播學院出版社。

例2：Grunig, J. E. (1992). Communication, public relations, and effective organizations: An overview of the book. In J. E. Grunig (Ed.), _Excellence in public relations and communication_ _management_ (pp. 1–30). Hillsdale, NJ: Lawrence Erlbaum Associates.

5、譯著

例1：約瑟夫．斯特勞巴哈、羅伯特．拉羅斯（2002）。《資訊時代的傳播媒介》（熊澄宇等譯）。北京：清華大學出版社。（原書 Straubhaar, J., & LaRose, R. \[2000\]. _Media now: Communication media in the information age_ \[2nd ed.\]. Belmont, CA:Wadsworth.）

例2：Laplace, P. S. (1951). _A philosophical essay on probabilities_ (F. W. Truscott & F. L. Emory, Trans.). New York: Dover. (Original work published 1814)

6、學位論文

例1：張榮顯（2005）。《公眾的想像：媒介使用與中國人的國家主義建構》。浸會大學傳理學院博士論文。

例2：楊怡珊（2002）。《新聞記者之社會智慧與消息來源互動策略之人際關係研究》。政治大學新聞研究所碩士論文。

例3：Wilfley, D. E. (1989). _Interpersonal analyses of bulimia: Normal-weight and obese_. Unpublished doctoral dissertation, University of Missouri, Columbia.

例4：Almeida, D. M. (1990). _Fathers’ participation in family work: Consequences for fathers’ stress and father-child relations_. Unpublished master’s thesis, University of Victoria, Victoria, British Columbia, Canada.

7、雜誌

例1：張圭陽（2003年5月）。〈香港傳媒「非典」一役的總結〉。《信報財經月刊》，第315期，頁35–37。

例2：Kandel, E. R., & Squire, L. R. (2000, November 10). Neuroscience:

Breaking down scienti\_c barriers to the study of brain and mind. _Science_, _290_, 1113–1120.

8、報紙

例1：林鶴玲（2001年10月30日）。〈媒體如何擺脫政治糾葛？〉。《中國時報》，第15版。

例2：《明報》（2000年7月26日）。〈報評會成立，接受私隱投訴〉，第A5版。

例3：Schwartz, J. (1993, September 30). Obesity affects economic, social status. _The Washington Post_, pp. A1, A4.

9、網上文章／文件

例1：潘知常（2004 年10 月8 日）。〈新意識形態與中國傳媒—新世紀新聞傳媒研究的一個前沿課題〉。取自中華傳播網，http://academmic.mediachina.net/xsjd\_view.jps?id=1802。

例2：TVBS民意調查中心（2002年2月20日）。〈財劃法後政治人物聲望民調〉。上網日期：2002年3月6日，取自http://www.tvbs.com.tw/code/tvbsnews/poll/2002-02/20020222/020222.asp。

例3：Canarie, Inc. (1997, September 27). _Towards a Canadian health_

_IWAY: Vision, opportunities and future steps_. Retrieved November 8, 2000, from http://www.canarie.ca/press/publications/pdf/health/healthvision.doc.

10、其他範例請參考英文APA格式。

**Comment by zepinglee** [comment]
这个体例与其他格式差异较大，需要将示例文献录入 Zotero 群组方便我们测试。

另外我最近略忙，预计周末才有时间处理。

**Comment by lequn-F** [comment]
这是官网下载的已发表文献，谢谢！
[啟動可供性：社區微信群與健康知識分享行為 —來自上海的經驗證據.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15371779/default.pdf)

**Comment by zepinglee** [comment]
> 需要将示例文献录入 Zotero 群组

**Comment by lequn-F** [comment]
请问具体怎么操作呢，新手不是太懂

**Comment by lequn-F** [comment]
您好，已加入群组，ID：lqFu

**Comment by zepinglee** [comment]
已修改为 admin 权限。
<img width="929" alt="Screenshot 2024-05-21 at 17 01 02" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/7648612e-59ae-4508-84a1-f6d9cf71ebd6">

**Comment by lequn-F** [comment]
已添加完成

**Comment by lequn-F** [comment]
非常感谢！

**Comment by zepinglee** [comment]
这周略忙。[issue\#307](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/issue%23307) 分支已经完成了部分，但还没校对完。

**Comment by lequn-F** [comment]
辛苦辛苦，非常感谢！！！
