### ISSUE TITLE
大连理工大学硕士学位论文模板修改请求

### ISSUE THREAD

**Issue by zhang-dut** [redleafnew/Chinese-STD-GB-T-7714-related-csl#313]
**样式信息**

- 期刊/学校名称：大连理工大学硕士研究生学位论文

- 英文名称：Dalian University of Technology

- 参考文献格式：[新修改网站](https://gs.dlut.edu.cn/info/1210/13916.htm)、[新修改网站的Endnote格式参考文件](https://gs.dlut.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1502106601&wbfileid=B75C0928A95E9E44C2B4050868A78C81)、[新修改网站的docx格式参考文件](https://gs.dlut.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1502106601&wbfileid=2CBE67D6CDEF005C538BDC978ABF2C50)、[新修改网站的PDF格式参考文件](https://gs.dlut.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1502106601&wbfileid=AF0A5FBD8DC14815BB8A0EDC1A3FBC03)。

- 参考文献格式的更新日期：2024-04-19

- （学校）文件号：[例如“研生[2019]10号”]

- （期刊）ISSN 号：[例如 0439-755X]

- （期刊）相关领域：[例如 psychology]

**测试条目**

Zotero ID:

**其他样式信息**

在目前[452dalian-university-of-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/452dalian-university-of-technology.csl)的基础上，有以下修改：
- 参考文献格式略作调整，新的“大工endnote.ens”文件已放入压缩包。更改部分有：参考文献、C会议、J期刊正常应该在标题后边 模版都在会议名或期刊名后边，现已更正；
- 外国人名缩写不再是Summons R. E.，而是Summons R E，即由A. B.改成了A B;
- 引用硕士和博士论文作参考文献后为具体到引用的是哪一页的论文添加了起止页码部分，如果不需要写具体的起止页码可以不用管这一部分。
  - 参考样式：[序号] 主要责任者. 学位论文名[D]. 保存单位, 年份: 起止页码.
[1] 张志祥. 间断动力系统的随机扰动及其在守恒律方程中的应用[D]. 北京大学, 1998: 25-37.
[2] 张志祥. 间断动力系统的随机扰动及其在守恒律方程中的应用[D]. [S. 1.]: 北京大学, 1998: 25-37.
  - 其中[2]为修改文件上的参考样式，学校给的word模板上的参考样式仍为[1]，故个人认为此条可修改可不修改。

- 网页信息修改部分参考：
  - [序号] 主要责任者. 题名[文献类型标识/文献载体标识]. 年份, 链接.
[1] 国家发展改革委. 中华人民共和国国民经济和社会发展第十四个五年规划和2035年远景目标纲要[EB/OL]. 2021, http://gbdy.ndrc.gov.cn/gbdyzcjd/t20210323_1270126.html.

**Comment by zepinglee** [comment]
已在 ab9792c 中修改。

**Comment by zhang-dut** [comment]
经测试各类文献，符合大连理工大学参考文献的要求，感谢您！
