### ISSUE TITLE
更新《无机材料学报》

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#317]
@northword 我在 003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl 的基础上重制了《无机材料学报》的样式（ bcd9f19 ）。主要修改有以下：

1. 期刊页码只显示起始页。
2. 日期的分隔符由 en dash 改为 hyphen。
3. 纯网络版期刊文献（无卷、期、页码），将起始页换成文章编号。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/bcd9f194c37fb4df8ec6a928cdcda19e1852b336/tests/styles/106journal-of-inorganic-materials/test.md?plain=1#L171

另外有个问题是，目前的图书出版社为斜体。这是近期发表的论文的格式吗？《写作及排版规范》并未要求。

**Comment by northword** [comment]
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/44738481/9bfac860-4875-4ba4-9c4c-58a5340a045b)

我查了最新一期的文章 PDF ，看起来是不需要斜体的，当时写这个样式的时候只考虑了期刊文章，其他类别的没有详细适配，所以会有错误。

**Comment by zepinglee** [comment]
> 我查了最新一期的文章 PDF ，看起来是不需要斜体的，当时写这个样式的时候只考虑了期刊文章，其他类别的没有详细适配，所以会有错误。

在 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/125ac38ff0072236fab7495765685579e990a63a> 中修改。
