### ISSUE TITLE
Zotero 更新到6.0后英文文献后面也是"等“

### ISSUE THREAD

**Issue by strikebai** [redleafnew/Chinese-STD-GB-T-7714-related-csl#36]
GBT系列的CSL文件在以前的Zotero版本上对中英文都能正确识别；但是，更新到6.0后英文文献后面也是"等“啦。

**Comment by redleafnew** [comment]
这个与版本没有关系，主要是还是把语言设置为en。或是升级版本把语言修改了？
https://gitee.com/zotero-chinese/zotero-chinese/issues/I4YKIN

**Comment by redleafnew** [comment]
如果仍然解决不了，请指出用的具体csl，并把测试的条目导出为zotero 的RDF格式，上传到附件或网盘，以供测试。如果解决了请关闭issue

**Comment by strikebai** [comment]
27zju-thesis.csl](https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl/blob/main/27zju-thesis.csl
[导出的条目.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8355150/default.zip)
经测试，英语文也是”等“，英文文献信息已经改为”en"。

**Comment by strikebai** [comment]
> 27zju-thesis.csl](https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl/blob/main/27zju-thesis.csl [导出的条目.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8355150/default.zip) 经测试，英语文也是”等“，英文文献信息已经改为”en"。

![image](https://user-images.githubusercontent.com/102399648/160235832-2dd876e3-8bc7-426d-a0e7-4e9a8d8e9a4c.png)

**Comment by strikebai** [comment]
您好！
测试了好几个双语的CSL文件，Zotero升级到6.0以后，包括原来可以正常处理“等”和“et. al"的csl文件。升级后中英文文件都显示为”等“。
谢谢！



柏帅蛟&nbsp;博士
Shuaijiao Bai, Ph. D.
Email: ***@***.***; ***@***.***


 

&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/Chinese-STD-GB-T-7714-related-csl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月26日(星期六) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] Zotero 更新到6.0后英文文献后面也是"等“ (Issue #36)





 
如果仍然解决不了，请指出用的具体csl，并把测试的条目导出为zotero 的RDF格式，上传到附件或网盘，以供测试。如果解决了请关闭issue

**Comment by redleafnew** [comment]
你确定都是“en”而不是“English”？
我导入的你这两个中，那个英文的语言显示是<code>English</code>
<img width="615" alt="20220326190829" src="https://user-images.githubusercontent.com/22135631/160236817-489645ea-f2d7-4710-b8b8-08c0c29a3f16.png">

**Comment by redleafnew** [comment]
请帮忙测试下，现在语言设为<code>English</code>也可以了。@strikebai

**Comment by redleafnew** [comment]
需要重新下载csl。

**Comment by zepinglee** [comment]
不建议这么改，CSL 的标准中指明了使用 ISO 695-1。

https://docs.citationstyles.org/en/stable/specification.html#standard-variables

<img width="723" alt="Screen Shot 2022-03-26 at 20 02 10" src="https://user-images.githubusercontent.com/12290822/160238461-e916b862-5aca-458d-85bc-f5977105ddf4.png">

**Comment by redleafnew** [comment]
这样好像语言English也可以了，
那就不迁就错误的了？

**Comment by strikebai** [comment]
> 请帮忙测试下，现在语言设为`English`也可以了。@strikebai

可以了。太棒啦！非常感谢！

**Comment by zepinglee** [comment]
> 这样好像语言English也可以了， 那就不迁就错误的了？

我也觉得不要迁就错误的。在实际过程中，这是因为找不到 `locales-English.xml` 才 fall back 到 `en-US` 的，所以 `locale="Chinese"` 也会 fall back 到 `en-US`，这就很混乱。

**Comment by redleafnew** [comment]
好吧，我再改回来，但总是有的人反馈这个问题，也很麻烦。
说得很清楚，要改语言为en，唉....
