### ISSUE TITLE
关于南农硕博论文模板“专著中析出的文献”格式中双斜杠的位置问题

### ISSUE THREAD

**Issue by ginkgo97** [redleafnew/Chinese-STD-GB-T-7714-related-csl#37]
参见《GB/T 7714-2015》第19页“A.7 专著中析出的文献”格式。涉及图书中析出的文献（图书章节）、会议论文集中析出的文献（会议论文）。
一、图书章节
1.正确：图书作者设置为“李承森”时“//”位置正确
标准格式：[1]白书农. 植物开花研究[M]//李承森. 植物科学进展. 北京: 高等教育出版社, 1998: 146-163.
当前格式：[1]白书农. 植物开花研究[M]//李承森. 植物科学进展. 北京: 高等教育出版社, 1998: 146-163.
2.错误：编辑设置为“李承森”或Biffl S和Sabou M时“//”位置不正确
1）标准格式：[1]白书农. 植物开花研究[M]//李承森. 植物科学进展. 北京: 高等教育出版社, 1998: 146-163.
当前格式：[1]白书农. 植物开花研究[M]. 李承森, 编. //植物科学进展. 北京: 高等教育出版社, 1998: 146-163.
2）标准格式：[1]Sabou M, Kovalenko O, Ekaputra F J, et al. Semantic Web Solutions in Engineering[M]//Biffl S, Sabou M. Semantic Web Technologies for Intelligent Engineering Applications. Cham: Springer International Publishing, 2016: 281–296.
当前格式：[1]Sabou M, Kovalenko O, Ekaputra F J, et al. Semantic Web Solutions in Engineering[M]. Biffl S, Sabou M, eds.//Semantic Web Technologies for Intelligent Engineering Applications. Cham: Springer International Publishing, 2016: 281–296.
二、会议论文
1.错误：任何情况下“//”的位置都不正确以及会议论文集出版地缺失
标准格式：[1]Hyvönen E, Tuominen J, Alonen M, et al. Linked Data Finland: A 7-star Model and Platform for Publishing and Re-using Linked Datasets[C]//Presutti V, Blomqvist E, Troncy R, et al. The Semantic Web: ESWC 2014 Satellite Events. Cham: Springer International Publishing, 2014: 226–230.
当前格式：[1]Hyvönen E, Tuominen J, Alonen M, et al. Linked Data Finland: A 7-star Model and Platform for Publishing and Re-using Linked Datasets[C]. Presutti V, Blomqvist E, Troncy R, et al., eds.//The Semantic Web: ESWC 2014 Satellite Events. Springer International Publishing, 2014: 226–230.

感谢！

**Comment by ginkgo97** [comment]
以下是导出的测试目录。
[20220403.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8402920/20220403.zip)

**Comment by redleafnew** [comment]
图书导入时“李承森”是作者还是编辑？

**Comment by redleafnew** [comment]
修改了一下，请再试试。

**Comment by ginkgo97** [comment]
谢谢，但是我用visual editor在load style的时候显示了“error parsing csl code”？

**Comment by redleafnew** [comment]
Word可以用吗？在线编辑器我也不知道是怎么回事。

**Comment by ginkgo97** [comment]
嗯嗯，基本没问题。就是“, 编”和“, eds.”好像都不需要添加吧？

**Comment by redleafnew** [comment]
不用，那个会自动显示。

**Comment by redleafnew** [comment]
如果是编辑会显示为“, 编”

**Comment by redleafnew** [comment]
现在应该也可以用在线编辑器了

**Comment by ginkgo97** [comment]
呃，我的意思是国标2015好像已经不需要显示“, 编”和“, eds.”了。除了译者要注明“, 译”外，其它责任者都不需要著录责任类型了。

**Comment by redleafnew** [comment]
再试试？

**Comment by ginkgo97** [comment]
ok，感谢！

**Comment by zepinglee** [comment]
这个 CSL 是根据 buffalo_d 的版本写的，其中对于 editor 和 translator 的处理不太严谨，比如会议论文的 translator 应该是作为「析出文献的其他责任者」放在「//」前，不应作为「专著的主要责任者」跟 editor 一起放到「//」后。
 
<img width="708" alt="Screen Shot 2022-04-03 at 21 34 59" src="https://user-images.githubusercontent.com/12290822/161430670-23a7f6a8-1b96-4c39-997f-5a1e155ec9d4.png">

**Comment by redleafnew** [comment]
我看例子中//都是放在文献类型的后面，所以就修改了。

**Comment by zepinglee** [comment]
> 我看例子中//都是放在文献类型的后面，所以就修改了。

有时间的话可以在我重构的版本上修改 njau 的样式，应该会少一些类似的问题。

**Comment by redleafnew** [comment]
ok。搞新的时候再弄。老的凑合着用。

**Comment by redleafnew** [comment]
@zepinglee 你的重构版本在哪，给个地址呗

**Comment by redleafnew** [comment]
https://github.com/zepinglee/gb-t-7714-csl-style/blob/main/china-national-standard-gb-t-7714-2015-numeric.csl是这个吗

**Comment by redleafnew** [comment]
多谢，在这个基础上修改一个《物理学报》试试。https://wulixb.iphy.ac.cn/news/tougaoxuzhi.htm
