### ISSUE TITLE
请问只有两个作者如何设置”等“，直接改 et-al-min无效

### ISSUE THREAD

**Issue by choutung** [redleafnew/Chinese-STD-GB-T-7714-related-csl#38]
老师好，我正在使用的是04zuel-thesis.csl，
对于
王越溪, 王鹏. 鸡肉早餐肠加工技术研究进展[J]. 中国家禽, 2018, 40(23): 37–42.
一文，现在的效果是（王越溪和王鹏, 2018）
我想达到的效果是（王越溪等, 2018），
请问改如何修改呢，我尝试修改了第320行的 et-al-min="2"，无效
320行<citation et-al-min="2" et-al-use-first="1" disambiguate-add-year-suffix="true" collapse="year">
恳请老师解答

**Comment by redleafnew** [comment]
中文的：https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/23cc3800f21cb02713c91c75981462865dc95bbb/04zuel-thesis.csl#L78
英文的：https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/23cc3800f21cb02713c91c75981462865dc95bbb/04zuel-thesis.csl#L64
改这两行试试。
改为et-al-min="1"

**Comment by choutung** [comment]
解决了，谢谢您
