### ISSUE TITLE
zotero不能识别cls样式文件

### ISSUE THREAD

**Issue by zgq2020** [redleafnew/Chinese-STD-GB-T-7714-related-csl#39]
![image](https://user-images.githubusercontent.com/61308133/162408743-f24307bf-7ec7-49cb-a073-c83a76bb2c5e.png)
问题：\Chinese-STD-GB-T-7714-related-csl-main\00gb-t-7714-2015-numeric-zepingli-rework.csl" 不是有效的 CSL 1.0.1 样式文件，它可能不能在 Zotero 正常工作。
版本：zotero 6.0

**Comment by redleafnew** [comment]
点ok

**Comment by zgq2020** [comment]
好的，谢谢

**Comment by Andyyoung0507** [comment]
我也是这样的情况，添加之后英文文献多余三个作者变成了“等”

**Comment by zepinglee** [comment]
> 我也是这样的情况，添加之后英文文献多余三个作者变成了“等”

将英文文献的 `language` 域设为 `en-US`，因为这个 CSL 将 `zh-CN` 设为了默认语言。如果英文文献较多，可以修改 CSL 将 `default-locale` 去掉并且将中文文献 `language` 设为 `zh-CN`。总之跟这个“是有效的 CSL 1.0.1 样式文件”的警告无关。

**Comment by Andyyoung0507** [comment]
解决啦，多谢！
