### ISSUE TITLE
关于在ZepingLee版本基础上添加语言“en”对应多作者“et al”

### ISSUE THREAD

**Issue by ginkgo97** [redleafnew/Chinese-STD-GB-T-7714-related-csl#40]
njau-thesis.csl似乎仍存在一些小问题，这些问题在ZepingLee版本中处理得比较好。
1）对无作者、无创建日期的网页的参考文献著录：
南农当前版本：[1] Anonymous. OntologWiki: OntologySummit2013 Communique[EB/OL]. ([no date])[2022-03-31]. http://ontolog.cim3.net/wiki/OntologySummit2013_Communique.html.
ZepingLee版本：[1] OntologWiki: OntologySummit2013 Communique[EB/OL]. [2022-03-31]. http://ontolog.cim3.net/wiki/OntologySummit2013_Communique.html.
2）对报告的参考文献著录：
南农当前版本：[1] Noy N F, McGuinness D L. Ontology Development 101: A Guide to Creating Your First Ontology[R].（2001）.
ZepingLee版本：[1] NOY N F, MCGUINNESS D L. Ontology Development 101: A Guide to Creating Your First Ontology[R]. Stanford knowledge systems laboratory technical report KSL-01-05, 2001: 25.

综上，是否可以在ZepingLee版本基础上添加语言“en”对应多作者“et al”这一设定？这样一来，该版本应当即可作为GB/T 7714-2015的最终版本了。

**Comment by ginkgo97** [comment]
以下是用于测试的json文件。
[无创建日期和作者的网页+报告.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8456070/%2B.zip)

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/eb5a356cef7602d371b6c2f26d85a4a196824d67/00gb-t-7714-2015-numeric-zepingli-rework.csl#L427-L437

**Comment by ginkgo97** [comment]
好的吧，没细看csl文件。多谢！

**Comment by ginkgo97** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/eb5a356cef7602d371b6c2f26d85a4a196824d67/00gb-t-7714-2015-numeric-zepingli-rework.csl#L427-L437

好的吧，没细看csl文件。多谢！

**Comment by redleafnew** [comment]
我修改一下njau的

**Comment by zepinglee** [comment]
> 我修改一下njau的

00gb-t-7714-2015-numeric-zepingli-rework.csl 这个文件中也可以取消注释 `layout locale="en"`。原文件是为了给官方仓库的 PR 准备的，只能用标准 CSL 的功能，所以注释掉了 CSL-M 的部分。

**Comment by redleafnew** [comment]
根据你的重构臲重新修改了一下。
