### ISSUE TITLE
language 域应设为 `zh` 或 `zh-CN`

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#43]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/c5f0d5d1aacbb654dd4fe6f5a32ccfe1c4a0d87e/README.md?plain=1#L462

README 中提到：

> 将 `language` 英文设为 `en`，中文为`中文`

但是跟 [CSL 的要求](https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables)，应设置为 `zh` 或者 `zh-CN`。

<img width="695" alt="Screen Shot 2022-04-24 at 21 11 18" src="https://user-images.githubusercontent.com/12290822/164978188-b8349700-2fde-4dad-b3e7-2d731f12a694.png">

**Comment by redleafnew** [comment]
ok。回头修改一下。谢谢。
