### ISSUE TITLE
同一文献引用bug

### ISSUE THREAD

**Issue by 1918141147** [redleafnew/Chinese-STD-GB-T-7714-related-csl#45]
同一文献[1]上下文引用会显示[2]为两篇文献[1]。
参考文献
[1]关于zotero使用......
[2]引文......
[3]关于zotero使用......
如上所述

**Comment by zepinglee** [comment]
这个跟 CSL 无关。

可能是你的 Zotero 数据库已经重复了，你引用的“同一文献”在数据库中其实是两篇文献。

**Comment by 1918141147** [comment]
> 这个跟 CSL 无关。
> 
> 可能是你的 Zotero 数据库已经重复了，你引用的“同一文献”在数据库中其实是两篇文献。

**Comment by 1918141147** [comment]
> > 跟这个 CSL 其他的。
> > 可能是你的 Zotero 数据库已经重复了，你在数据库中引用的“同一篇文献”实际上是两篇文献。

感谢回复！确实是文献的问题。谢谢谢谢。
