### ISSUE TITLE
请帮写一下这样的脚注：

### ISSUE THREAD

**Issue by smal1fish1** [redleafnew/Chinese-STD-GB-T-7714-related-csl#47]
![image](https://user-images.githubusercontent.com/102558605/166099569-4370e84e-4070-4263-8646-403c85700af5.png)

**Comment by smal1fish1** [comment]
标点符号就是这样了

**Comment by redleafnew** [comment]
[控制、法定与自称：唐宋之际归义军辖区变迁的多维度考察_李军.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8596533/_.pdf)
<img width="686" alt="20220430172318" src="https://user-images.githubusercontent.com/22135631/166099938-af00b038-1515-4591-b493-8c8403955568.png">
@zepinglee 这个带圈的数字是怎么实现的来着？

**Comment by redleafnew** [comment]
https://forums.zotero.org/discussion/87328/is-it-possible-to-use-circled-numbers-in-csl
@zepinglee 是不是无法实现。

**Comment by smal1fish1** [comment]
[Uploading 案例-书.zip…]()

**Comment by smal1fish1** [comment]
[案例-期刊.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/8596574/-.zip)

**Comment by redleafnew** [comment]
期刊只显示第一作者吗？
把想显示的效果也写一下吧。
用你刚才提供的条目。

**Comment by smal1fish1** [comment]
尾注：
期刊：
![image](https://user-images.githubusercontent.com/102558605/166100540-38acb72d-a4f9-4769-ac54-696875f26d37.png)
书籍：
![image](https://user-images.githubusercontent.com/102558605/166100548-0f402637-23bc-44eb-a3c7-83da5b5e81fb.png)

**Comment by zepinglee** [comment]
> https://forums.zotero.org/discussion/87328/is-it-possible-to-use-circled-numbers-in-csl @zepinglee 是不是无法实现。

CSL 无法实现。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/302historical-research.csl
