### ISSUE TITLE
减少借用其他的文献类型和域

### ISSUE THREAD

**Issue by zepinglee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#48]
目前仓库中有一些 CSL 需要借用其他文献类型和域，比如：

1. 003gb-t-7714-2005-numeric-book-pages.csl 需要将书籍的引用页码填入 `# of Pages` 域；
2. 405njau-thesis.csl 要求“标准”类型使用 “Bill”，并在在 `Code` 填入出版地和出版社（如 “北京：中国标准出版社”），`Code Pages` 中填入引用的页码。

我最近发现，这两种情况都可以使用 `Extra` 的功能实现：

1. 书籍的引用页码可以在 `Extra` 中填写 `Pages: 105`。
2. “标准”类型可以使用“报告”类型，并且在 `Extra` 中填写 `Type: standard`。标准号、出版地和出版社可以分别填入 `Report Number`, `Place` 和 `Institution`，这几个域会映射到 CSL-JSON 的 `number`, `publisher-place` 和 `publisher`，所以不需要在 CSL 中进行特殊处理。

所以，我提议修改仓库中的 CSL 时减少借用其他的类型和域，而是改为尽可能使用 `Extra` 的功能实现。这样有几个好处：填写的内容更符合域的描述；可以兼容更多的 CSL。@redleafnew 意见怎样？

**Comment by redleafnew** [comment]
确实可以这样，我觉得再搞新的csl可以更加规范些，
老的我不太想花精力修改了，如果你有时间可以搞，最近事情一大堆。

**Comment by zepinglee** [comment]
> 确实可以这样，我觉得再搞新的csl可以更加规范些， 老的我不太想花精力修改了，如果你有时间可以搞，最近事情一大堆。

好的。
