### ISSUE TITLE
您好，请问如何对参考文献进行排序呢？

### ISSUE THREAD

**Issue by chunibyo-wly** [redleafnew/Chinese-STD-GB-T-7714-related-csl#5]
您好，首先谢谢您的工作。
学校要求对参考文献进行排序，具体规则如下所示，请问有好的解决办法吗？

![image](https://user-images.githubusercontent.com/33208530/115105455-a0b19900-9f91-11eb-8f7e-ade061880631.png)

**Comment by redleafnew** [comment]
用得哪个csl文件？里面有按语言进行排序的（），中文在前，外文在后，如4，5，hzau-thesis。如有特殊需求，请给出例子。

**Comment by chunibyo-wly** [comment]
原来如此，我忽略了学校版本的，谢谢您，我看一下您说的。

**Comment by redleafnew** [comment]
如果没有问题，issue即将关闭
