### ISSUE TITLE
关于中南财大硕博论文引用文献-文末文献排序

### ISSUE THREAD

**Issue by waitingleeee** [redleafnew/Chinese-STD-GB-T-7714-related-csl#51]
老师好，我正在使用的是416zuel-thesis.csl，
现在遇到关于文末参考文献排序的如下问题：
1、文末参考是先英文后中文的排序（要求先中文后英文）；
2、中文文献和英文文献内部没有按照作者姓名首字母顺序排列。

<img width="752" alt="0517" src="https://user-images.githubusercontent.com/105722978/168815562-3246cfb6-2bf1-44cd-ac9d-7536218917e1.PNG">

<img width="472" alt="0517-2" src="https://user-images.githubusercontent.com/105722978/168815600-29933b77-0c4c-4c2e-834c-08fea482bc54.PNG">

恳请老师解答

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/4027a439b8579736b190683aa2fa2210d8dfb03a/416zuel-thesis.csl#L347-L349

这个地方不应该使用 language 作为 sort-key，而是应该像 author-date 样式一样用 author 和 issued。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/4027a439b8579736b190683aa2fa2210d8dfb03a/001gb-t-7714-2015-author-date-bilingual.csl#L469-L472

**Comment by redleafnew** [comment]
他们要求按语言排序的，
需要再上面加上下面的key。

**Comment by waitingleeee** [comment]
老师们，我已把截图里的几篇文献放到zotero群组的“错误”文件夹里面了

<img width="871" alt="0517-3" src="https://user-images.githubusercontent.com/105722978/168820183-76df8025-6c53-443c-8066-3434deb9b8b3.PNG">
这是中南财大硕博论文参考文献的一部分要求

**Comment by redleafnew** [comment]
新添加的文献加了标签吧，不知道哪个是新添加的。

**Comment by zepinglee** [comment]
> 他们要求按语言排序的， 需要再上面加上下面的key。

`default-locale="zh-CN"`就已经是中文在前，英文在后了。

**Comment by waitingleeee** [comment]
已添加0517 标签

> 新添加的文献加了标签吧，不知道哪个是新添加的。

**Comment by redleafnew** [comment]
> <sort> 
>    <key macro="author"/> 
>    <key macro="issued-year"/> 
>  </sort>

果然可以，谢谢。

如果要英文排前面呢。

**Comment by waitingleeee** [comment]
> > 已添加0517 标签
> > > 新添加的文献加了标签吧，不知道哪个是新添加的。
> 
> 更新了，你再试一下。

我刚更新了试过，成功啦！非常感谢老师们的帮助！我准备关闭issue啦

**Comment by redleafnew** [comment]
欢迎给同学们推荐本仓库和Zotero。

**Comment by waitingleeee** [comment]
> 欢迎给同学们推荐本仓库和Zotero。

好的  老师  正在向周围同学们疯狂安利中

**Comment by waitingleeee** [comment]
感谢老师们的帮助！

**Comment by waitingleeee** [comment]
<img width="144" alt="0528" src="https://user-images.githubusercontent.com/105722978/170805556-860a296f-4045-4343-a8b9-247c63fe05cd.PNG">
老师们好，我又来请教了。目前的416zuel-thesis.csl在文中使用加注法引用的时候，当中文文献是2位作者时，第一个作者的后面多了一个逗号。
在这个调整参考文献排序的issue修改之前没有发现这个问题，所以我就在这个issue的后面补充评论了。
我努力看了代码，真的不太会，还想请老师们帮忙调整一下。

**Comment by redleafnew** [comment]
我猜是你的作者进行过拆分、合并处理，不要对导入的题录中的作者进行任何处理。
[404jnu-thesis.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/404jnu-thesis.csl)使用说明中有写

**Comment by waitingleeee** [comment]
> 

是的老师  我动过中文作者的姓名  那我再试下还原回去

**Comment by zepinglee** [comment]
> <img alt="0528" width="144" src="https://user-images.githubusercontent.com/105722978/170805556-860a296f-4045-4343-a8b9-247c63fe05cd.PNG">
> 
> 老师们好，我又来请教了。目前的416zuel-thesis.csl在文中使用加注法引用的时候，当中文文献是2位作者时，第一个作者的后面多了一个逗号。 在这个调整参考文献排序的issue修改之前没有发现这个问题，所以我就在这个issue的后面补充评论了。 我努力看了代码，真的不太会，还想请老师们帮忙调整一下。

我无法复现这个问题。请将测试的文献发到群组 <https://www.zotero.org/groups/4677213/gbt_7714_csl_development> 中，在学位论文目录下新建一个 ZUEL 的。

**Comment by zepinglee** [comment]
> 我猜是你的作者进行过拆分、合并处理

@redleafnew 这个茉莉花插件进行姓名的合并是出于什么目的？

**Comment by waitingleeee** [comment]
> > <img alt="0528" width="144" src="https://user-images.githubusercontent.com/105722978/170805556-860a296f-4045-4343-a8b9-247c63fe05cd.PNG">
> > 老师们好，我又来请教了。目前的416zuel-thesis.csl在文中使用加注法引用的时候，当中文文献是2位作者时，第一个作者的后面多了一个逗号。 在这个调整参考文献排序的issue修改之前没有发现这个问题，所以我就在这个issue的后面补充评论了。 我努力看了代码，真的不太会，还想请老师们帮忙调整一下。
> 
> 我无法复现这个问题。请将测试的文献发到群组 https://www.zotero.org/groups/4677213/gbt_7714_csl_development 中，在学位论文目录下新建一个 ZUEL 的。

老师们，我已经根据@[redleafnew](https://github.com/redleafnew) 老师说的，调整了作者姓名，现在果然没有问题了。

**Comment by waitingleeee** [comment]
> > 我猜是你的作者进行过拆分、合并处理
> 
> @redleafnew 这个茉莉花插件进行姓名的合并是出于什么目的？

老师，不是插件合并的，是我手动合并的。我又还原回去了，现在没有问题了。打扰了老师们

**Comment by redleafnew** [comment]
> > 我猜是你的作者进行过拆分、合并处理
> 
> @redleafnew 这个茉莉花插件进行姓名的合并是出于什么目的？

应该是有些人的需求，在Zotero中间的窗口，显示的作者中国人可以显示全名，如张无忌 et al，张无忌 and 赵敏，而不是显示 张 et al ， 张 and 赵。
还有如果给作者加个粗，通讯作者加个*，如果不合并显示也会不正常。
其它我还不知道合并了有什么好处。

**Comment by zepinglee** [comment]
> 应该是有些人的需求，在Zotero中间的窗口，显示的作者中国人可以显示全名，如张无忌 et al，张无忌 and 赵敏，而不是显示 张 et al ， 张 and 赵。 

这是只是显示的问题，应该修改 Zotero 显示方式，为此修改原始数据很不合适。

**Comment by redleafnew** [comment]
是的，修改Zotero显示方式，估计Zotero开发团队不关心，所以他们只好就修改原始数据了。
好像有一个插件（https://github.com/normanfoster/zotero-fullcreator）可以修改显示方式，没有深入研究过这个插件。
