### ISSUE TITLE
格式问题-重复出现

### ISSUE THREAD

**Issue by isaac3203** [redleafnew/Chinese-STD-GB-T-7714-related-csl#52]
使用时发现最后参考文献会被转换两遍。
<img width="626" alt="image" src="https://user-images.githubusercontent.com/84989111/168844461-a0f2d150-ba4f-4752-a0b4-3426ad511fbd.png">

**Comment by zepinglee** [comment]
用了哪个 CSL 格式？

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
如果无进一步消息，本issue即将关闭。
