### ISSUE TITLE
语言改为en仍然中英文格式混淆

### ISSUE THREAD

**Issue by bi-wei** [redleafnew/Chinese-STD-GB-T-7714-related-csl#53]
作者您好！感谢无私提供zotero样式！我在使用《经济社会体制比较》的样式，但英文参考文献格式有的正确，而有的与中文一样了。最初发现是一些英文文章没有设置语言为en，但使用delitemwithatt批量修改为en后仍然无法refresh为中英文对应格式，英文的有一些还是与中文的一样。请问如何解决呢，十分感谢！

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

现在是怎么样？
想显示什么样？

**Comment by redleafnew** [comment]
显示错误的条目拖过去就可以。

**Comment by bi-wei** [comment]
您好，我已经加入群组，拖动了两条添加到了tests文件夹。
1、 Akkerman Tjitske, 2015：“Immigration policy and electoral competition in Western Europe: A fine-grained analysis of party positions over the past two decades”，《Party Politics》，2015, 1: 54–67。
2、Hall Peter A、Soskice David, 2009：“Varieties of capitalism”，《Emerging trends in the social and behavioral sciences》，2009。
  然而，我用的是《经济社会体制比较》的样式，因此上面这两个英文格式不正确，我还有其他的英文引用也像这样。请问是哪里出了bug？谢谢！

**Comment by redleafnew** [comment]
（Hall & Soskice, 2009）
（Akkerman, 2015）
Akkerman T., 2015. “Immigration policy and electoral competition in Western Europe: A fine-grained analysis of party positions over the past two decades.” Party Politics. 21(1): 54–67.
Hall P.A. & Soskice D., 2009. “Varieties of capitalism.” Emerging trends in the social and behavioral Sciences.

我这插入正常啊。
是用的这个样式吗？https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/201comparative-economic-and-social-systems.csl

**Comment by bi-wei** [comment]
您好， 是的。目前这个样式下，中文能够正确显示这个格式，而英文是有的正确，有的错误。刚才那两篇英文在我这，就是中文的格式显示英文引用（正确的情况下，这个样式下中英文应该格式不同）。我尝试1）删除了bibliography重新添加 2）直接refresh都不行。这里issue好像无法留言，您有qq交流群我可以提交截图请您看看bug吗？

**Comment by zepinglee** [comment]
同样无法复现你所描述的错误。

<img width="888" alt="Screen Shot 2022-05-18 at 18 51 39" src="https://user-images.githubusercontent.com/12290822/169022619-b071541e-3a0e-4e3d-a0de-c237c3551ecd.png">

**Comment by redleafnew** [comment]
可以加入Zotero中文插件 QQ群：
913637964

**Comment by redleafnew** [comment]
我和@zepinglee 都在群里

**Comment by zepinglee** [comment]
建议优先使用 issues 功能讨论，这里也可以上传截图。

**Comment by bi-wei** [comment]
问题已解决，不是bug，问题是同样一个文献的题录在多个群组出现，因此我批量修改某一群组的该文献为en后，引用的是来自其他群组的这篇，因此格式仍然不变，所以只要不出现重复的题录，保证为en，即可正常显示
