### ISSUE TITLE
参考文献部分"等"和"et al."处存在多余符号的问题

### ISSUE THREAD

**Issue by x-researcher** [redleafnew/Chinese-STD-GB-T-7714-related-csl#55]
您好，我有个小问题希望您能不吝赐教。

我采用 [404jnu-thesis.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/404jnu-thesis.csl) 格式修改，使参考文献部分只显示前三个姓名。仅修改第358行的代码：
```csl
<bibliography entry-spacing="0" et-al-min="4" et-al-use-first="3" line-spacing="1" second-field-align="flush">
```
如图，会导致参考文献部分中文"等"前多了一个","，英文“et al.”后多了一个"."，请问该如何修改能将此两处去除？期待您的答复。

![微信截图_20220526030958](https://user-images.githubusercontent.com/59728212/170349733-c8965001-4414-4008-8a80-cfc55b30def2.png)

另：引文部分正常

**Comment by x-researcher** [comment]
期望得到的结果为：
![微信截图_20220526034040](https://user-images.githubusercontent.com/59728212/170354004-5e7b6696-c1f6-4790-84a8-6e46edd4d028.png)

希望我的描述能让您理解，十分感谢！

**Comment by zepinglee** [comment]
`et al..`的用法确实不对。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L35

@redleafnew 有没有印象这里为何特殊设置？

**Comment by redleafnew** [comment]
> `et al..`的用法确实不对。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L35
> 
> @redleafnew 有没有印象这里为何特殊设置？

这个两个点的估计是写错了吧。
但等前面有逗号是正常的吧。

**Comment by zepinglee** [comment]
@x-researcher 你修改的是哪个期刊的？

如果去掉“等”前面的“, ”会导致跟西文的“, et al.”格式不一致，需要将中文和西文的名字分开处理，比较麻烦。

另外 404jnu-thesis.csl 比较旧，还有别的 bug（比如“中国互联网络信息中心. 第 29 次中国互联网络发展现状统计报告[R]. .”多了一个点号）。建议从 000～011 这些最近修订过的 CSL 的基础上进行修改。

**Comment by x-researcher** [comment]
> > `et al..`的用法确实不对。
> > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L35
> > 
> > @redleafnew 有没有印象这里为何特殊设置？
> 
> 这个两个点的估计是写错了吧。 但等前面有逗号是正常的吧。

此处我试过，如果去掉一个点，会导致引文部分少个点。

虽然有不加符号的写法，但”等“前面的”,“应该是正确的，感谢您。

**Comment by x-researcher** [comment]
> @x-researcher 你修改的是哪个期刊的？
> 
> 如果去掉“等”前面的“, ”会导致跟西文的“, et al.”格式不一致，需要将中文和西文的名字分开处理，比较麻烦。
> 
> 另外 404jnu-thesis.csl 比较旧，还有别的 bug（比如“中国互联网络信息中心. 第 29 次中国互联网络发展现状统计报告[R]. .”多了一个点号）。建议从 000～011 这些最近修订过的 CSL 的基础上进行修改。

我发现保留“等”前面的“, ”也是可以的，感谢您。

**Comment by zepinglee** [comment]
> 此处我试过，如果去掉一个点，会导致引文部分少个点。

不太可能吧，举个例子？

**Comment by zepinglee** [comment]
> 此处我试过，如果去掉一个点，会导致引文部分少个点。

我明白了，原来是这里多了 `strip-periods`。总之这个 csl 有很多问题，不建议使用。

**Comment by x-researcher** [comment]
> > 此处我试过，如果去掉一个点，会导致引文部分少个点。
> 
> 我明白了，原来是这里多了 `strip-periods`。总之这个 csl 有很多问题，不建议使用。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L339

好的，感谢您，我试着用其他模板修改。👍

**Comment by x-researcher** [comment]
> > 此处我试过，如果去掉一个点，会导致引文部分少个点。
> 
> 我明白了，原来是这里多了 `strip-periods`。总之这个 csl 有很多问题，不建议使用。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L339

的确，35行删除个点，339行将`strip-periods="true"`删除就解决了 👍
先迁就着用了，后面再补这方面知识。感谢大佬 🌹

**Comment by redleafnew** [comment]
> > > 此处我试过，如果去掉一个点，会导致引文部分少个点。
> > 
> > 
> > 我明白了，原来是这里多了 `strip-periods`。总之这个 csl 有很多问题，不建议使用。
> > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/f932a4d21e1582807d2f3f4283017df4279eb1d4/404jnu-thesis.csl#L339
> 
> 好的，感谢您，我试着用其他模板修改。👍

如果解决了，方便提交一个PR吗？

**Comment by x-researcher** [comment]
> 

我觉得您来改这两处就行了，我对这方面还了解的不够透彻，等将来学习了再为大家做贡献。
~~（我不是程序员，不懂PR，这一点就不提了 😂）~~

如果您指的是我所在高校的硕博学位模板，等我改成功了倒是可以联系您提交。

**Comment by redleafnew** [comment]
ok

**Comment by redleafnew** [comment]
> 35行删除个点，339行将strip-periods="true" 

修改这两个是吧

**Comment by x-researcher** [comment]
> > 35行删除个点，339行将strip-periods="true"
> 
> 修改这两个是吧

是的。

**Comment by redleafnew** [comment]
已更新，期待你学校的csl.

**Comment by zepinglee** [comment]
测试了一下，发现 404 还有几个问题：

1. author-date 式的参考文献表中通常将出版年紧跟在作者姓名后（国标的要求），比如：
> <div class="csl-entry">CRANE D, 1972. Invisible college[M]. Chicago: Univ. of Chicago Press.</div>

但是 404 给出的是在出版社后：
> <div class="csl-entry">[6] Crane D. Invisible College[M]. Chicago: Univ. of Chicago Press, 1972.</div>

2. > <div class="csl-entry">[82] Anonymous. Geoecology and computers: Proceedings of the Third International Conference on Advances of Computer Methods in Geotechnical and Geoenvironmental Engineering[M]. Yufin S A, ed.. Rotterdam: A. A. Balkema, 2000.</div>
“ed..” 这里的点号重复。

3. 网页文献文献类型标识后缺了点号，而且作为网页没有 URL 很奇怪。
> <div class="csl-entry">[5] Bawden D. Origins and concepts of digital Literacy[EB](2008-05-04).</div>

@x-researcher 再重复一遍，不要在 404 的基础上进行修改。
