### ISSUE TITLE
pandoc会重复两次

### ISSUE THREAD

**Issue by isaac3203** [redleafnew/Chinese-STD-GB-T-7714-related-csl#58]
通过pandoc转换，使用[011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl)时发现文中（人名，年份）会重复两次，最后参考文献也会被转换两遍。测试的每一个0开头csl都遇到这样的问题，但通过zotero官方的csl没有遇到。
想请问老师有没有办法解决。

个人比对了csl很久，找不到如何调整人名大小写，希望老师能指点一下，尝试自己在官方文档上直接改。
![image](https://user-images.githubusercontent.com/84989111/172497516-2a91dd47-016f-4a1e-9e85-bb63050343f8.png)
![image](https://user-images.githubusercontent.com/84989111/172497546-e8faffa9-0b8a-4257-ae01-050632f40e6f.png)

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
多语言支持是 [CSL-M](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension) 的扩展功能，只有 `citeproc-js` 支持。Pandoc 用的是 <https://github.com/jgm/citeproc>，没有实现这个扩展，所以错误地输出了两个 `layout` 中的内容。

**Comment by redleafnew** [comment]
@zepinglee 厉害了！

**Comment by zepinglee** [comment]
> 那能想办法让pandoc也用citeproc-js吗？@zepinglee

应该没什么办法，pandoc 和 <https://github.com/jgm/citeproc> 都是用 haskell 写的，跟 javascript 的 `citeproc-js` 没有共同的接口。

**Comment by isaac3203** [comment]
因为这是我的第一篇学术论文，我是obsidian的使用者，所以是通过citekey标注引文，在markdown编辑器中写作，进而通过pandoc转docx实现参考文献的插入。体验过markdown编辑的简洁与安全，不大愿意长时间面对word。

老师们有没有基于citekey用法的转换方式。

**Comment by redleafnew** [comment]
这个我们无法解决，暂时关闭了。

**Comment by Dagwbl** [comment]
> 因为这是我的第一篇学术论文，我是obsidian的使用者，所以是通过citekey标注引文，在markdown编辑器中写作，进而通过pandoc转docx实现参考文献的插入。体验过markdown编辑的简洁与安全，不大愿意长时间面对word。
> 
> 老师们有没有基于citekey用法的转换方式。

我同样遇到了这个问题，请问你有找到解决方法了吗

**Comment by zepinglee** [comment]
我对这一套方案不太了解，似乎需要在 pandoc 中设置缩进。
