### ISSUE TITLE
zotero引文样式403_hzau-thesis华中农业大学硕博论文

### ISSUE THREAD

**Issue by oceantrees** [redleafnew/Chinese-STD-GB-T-7714-related-csl#59]
感谢各位同学提供的论文样式，我是华中科技大学的，这版和我们学校的论文要求样式很相似。
     但是我在使用过程中遇到了一个问题无法解决，想请教下大家。
     **403hzau-thesis华中农业大学硕博论文版本**中，英文文章的第一个作者名字的姓和名顺序无法更改，姓一直以全称位于前面；后面的名字倒是可以，但是却做不到姓全称，名字缩写。
     我们学校论文要求 ”名在前、姓在后，名用首字母缩写、姓用全称”。类似这样：E. S. Lein，这个在7714-2015中可以通过修改实现，但是在该版本中却更改不了，请问该怎样在此版本上进行更改呢？
     附学校学位论文参考文献格式要求及示例。
![image](https://user-images.githubusercontent.com/107382067/173277444-fd375b1a-b2c6-43ca-993d-4f581fa6df6c.png)
![image](https://user-images.githubusercontent.com/107382067/173277524-ef3867f0-7c35-48be-afaf-18e1f954e4a4.png)

**Comment by zepinglee** [comment]
去掉 `name-as-sort-order`，参考 CSL 官方文档 <https://docs.citationstyles.org/en/stable/specification.html#name>。

**Comment by redleafnew** [comment]
@oceantrees 看看按
@zepinglee 的行不，可以的话把csl传到这个github上吧， 方便更多人。

**Comment by oceantrees** [comment]
感谢 @zepinglee ，问题已解决，name-as-sort-order="all"中的all删掉，其余部分已按照华科最新要求修改好，过会上传

**Comment by zepinglee** [comment]
> 感谢 @zepinglee ，问题已解决，name-as-sort-order="all"中的all删掉，其余部分已按照华科最新要求修改好，过会上传

整个 `name-as-sort-order="all"` 都删掉，`=""` 是未定义的行为，容易导致 bug。

**Comment by redleafnew** [comment]
如有文件上传，请PR到github，方便其他人，谢谢。这个issue暂时关闭。
