### ISSUE TITLE
韩老师能否改编个《管理世界》的zotero格式

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#6]
这是要求，和经济社会体制比较差不多。
文后中文参考文献的格式：

（1）一个中文作者的参考文献的格式：

戴治勇：《法治、信任与企业激励薪酬设计》，《管理世界》，2014年第2期。

（2）两个中文作者的参考文献的格式：

林乐、谢德仁：《分析师荐股更新利用管理层语调吗？——基于业绩说明会的文本分析》，《管理世界》，2017年第11期。

（3）三个中文作者的参考文献的格式：

王化成、曹丰、叶康涛：《监督还是掏空：大股东持股比列与股价崩盘风险》，《管理世界》，2015年第2期。

（4）参考文献为中文专著时的格式：

高琳：《分税制、地方财政自主权和经济发展绩效研究》，上海人民出版社，2016年。

（5）参考文献为中文论文集中的一篇论文时的格式：

佐藤宏：《外出务工、谋职和城市劳动力市场——市场支撑机制的社会网络分析》，载于李实、佐藤宏主编，《经济转型的代价──中国城市失业、贫困、收入差距的经验分析》，中国财政经济出版社，2004年。

（6）参考文献为毕业论文的格式：

黄超：《管理层利用语调管理配合盈余管理了吗？——来自我国上市公司年报的文本分析》，上海财经大学博士学位论文，2017年。

文后英文参考文献的格式（作者姓写在前，名写在后缩写为首字母；杂志名、书名需斜体；如同一作者在同一年刊登两篇以上文章，请在年份后区分a，b，……。）

（1）一个英文作者的参考文献的格式：

Weiss， D.， 2010，“Cost Behavior and Analysts’ Earnings Forecasts”，_The Accounting Review_， vol. 85， pp.1441~1471.

（2）两个英文作者的参考文献的格式：

Kang， J.  K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， _Journal of Finance_， 63(6)， pp.2817~2858.

（3）两个以上英文作者的参考文献的格式：

Banke， R. D.， Byzalov， D. and Chen， L. T.， 2013，“Employment Protection Legislation， Adjustment Costs and Cross-country Differences in Cost Behavior”，_Journal of Accounting and Economics_， vol. 55， pp.111~127.

（4）引用文献是工作论文的参考文献格式：

Hagedorn，M. ，Manovskii，I. and Mitman，K.，2019，“The Fiscal Multiplier”，NBER Working Paper，No. 25571.

（5）引用文献是论文集或合集中的某一篇论文的参考文献格式：

Fama，E. F.，1989，“Perspectives on October 1987，or What did We Learn from the Crash?”，in Barro，R. J.，R. W. Kamphuis，R. C. Kormendi and J. W. H. Watson，eds: _Black Monday and the Future of the Financial Markets_，Irwin，Homewood，III.    

（6）引用文献是专著时的参考文献格式：

Skolink， M. I.，1990，Radar handbook，New York:McGraw-Hill. 

**### _其中对于 中文文献，论文名称用书名号而不是引号，且出版时间只用某年某期。对于英文文献，论文名用引号。对于编号，用的是（num）_**

谢谢韩老师！

**Comment by fredericky123** [comment]
中英文参考文献分开，中文在前，英文在后，并分别按26个字母排序。中文参考文献中的标点符号都用全角。

**Comment by redleafnew** [comment]
我空余了搞一下，
中英文分开后，按作者的26个字母排序吗？
另外这个链接打不开。

**Comment by fredericky123** [comment]
> 我空余了搞一下，
> 中英文分开后，按作者的26个字母排序吗？
> 另外这个链接打不开。

谢谢韩老师！http://www.mwm.net.cn/Web/Instruction这里打得开。
对，是分别按作者的26个字母排序。

**Comment by redleafnew** [comment]
你看他的要求和哪个最类似，我修改一下比较方便。https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl
一些法学的是不是更相近。

**Comment by fredericky123** [comment]
> 你看他的要求和哪个最类似，我修改一下比较方便。https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl
> 一些法学的是不是更相近。

我感觉在《经济社会体制比较》的基础上修改更方便。

**Comment by redleafnew** [comment]
好的，我忙过这几天后修改一下。如果你有时间，麻烦你比较在《经济社会体制比较》上需要修改哪？另外麻烦提供几个zotero条目，用来测试和展示最终效果。

**Comment by fredericky123** [comment]
> 好的，我忙过这几天后修改一下。如果你有时间，麻烦你比较在《经济社会体制比较》上需要修改哪？另外麻烦提供几个zotero条目，用来测试和展示最终效果。

对于中文文献，论文名称用书名号而不是引号，且出版时间只用某年某期。
对于英文文献，论文名用引号，如同一作者在同一年刊登两篇以上文章，请在年份后区分a，b，……。
对于编号，用的是（num）


王化成、曹丰、叶康涛：《监督还是掏空：大股东持股比列与股价崩盘风险》，《管理世界》，2015年第2期。
黄超：《管理层利用语调管理配合盈余管理了吗？——来自我国上市公司年报的文本分析》，上海财经大学博士学位论文，2017年。

Kang， J. K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， _Journal of Finance_， 63(6)， pp.2817~2858.
Banke， R. D.， Byzalov， D. and Chen， L. T.， 2013，“Employment Protection Legislation， Adjustment Costs and Cross-country Differences in Cost Behavior”，_Journal of Accounting and Economics_， vol. 55， pp.111~127.
Skolink， M. I.，1990，Radar handbook，New York:McGraw-Hill.

**Comment by redleafnew** [comment]
文献格式是Zotero可以导入的

**Comment by redleafnew** [comment]
对于期刊，卷和期，你给的两个不一样，按哪个？
是写为63（6）还是vol 63？

（2）两个英文作者的参考文献的格式：

Kang， J. K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， Journal of Finance， 63(6)， pp.2817~2858.

（3）两个以上英文作者的参考文献的格式：

Banke， R. D.， Byzalov， D. and Chen， L. T.， 2013，“Employment Protection Legislation， Adjustment Costs and Cross-country Differences in Cost Behavior”，Journal of Accounting and Economics， vol. 55， pp.111~127.

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/9journal-of-management-world.csl
只改了一部分了，你看一下其他格式。

**Comment by fredericky123** [comment]
> 对于期刊，卷和期，你给的两个不一样，按哪个？
> 是写为63（6）还是vol 63？
> 
> （2）两个英文作者的参考文献的格式：
> 
> Kang， J. K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， Journal of Finance， 63(6)， pp.2817~2858.
> 
> （3）两个以上英文作者的参考文献的格式：
> 
> Banke， R. D.， Byzalov， D. and Chen， L. T.， 2013，“Employment Protection Legislation， Adjustment Costs and Cross-country Differences in Cost Behavior”，Journal of Accounting and Economics， vol. 55， pp.111~127.

我都没注意到这个细节，采用这个格式吧
Kang， J. K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， Journal of Finance， 63(6)， pp.2817~2858.

上面官网给的不统一，我看期刊发表文章也采用了不同的卷和期的表示

**Comment by redleafnew** [comment]
修改了，你看一下显示的效果和哪还需要修改。

**Comment by fredericky123** [comment]
> 修改了，你看一下显示的效果和哪还需要修改。

谢谢韩老师，我看看效果。

**Comment by fredericky123** [comment]
> 修改了，你看一下显示的效果和哪还需要修改。

感谢韩老师！目前看起来一切正常，感谢感谢！

**Comment by fredericky123** [comment]
这两个由于我的文献里没有暂时无法检测，不知需不需要特定的设置：
（1）引用文献是工作论文的参考文献格式：
Hagedorn，M. ，Manovskii，I. and Mitman，K.，2019，“The Fiscal Multiplier”，NBER Working Paper，No. 25571.
（期刊那里不用斜体，且书写为XX Working Paper）

（2）参考文献为毕业论文的格式：
黄超：《管理层利用语调管理配合盈余管理了吗？——来自我国上市公司年报的文本分析》，上海财经大学博士学位论文，2017年。
（格式为XX博士学位论文或XXX硕士学位论文，感觉这里比较难判断）

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/122882890-37724b80-d36f-11eb-95fc-6dc9c8762c6b.png)
第二个作者应该是zeng，排序在后面，然而zotero却将其视为ceng，排序靠前，这种能解决么

**Comment by fredericky123** [comment]
参考文献列表里的英文文献应为Title Case而不是sentence case，谢谢韩老师!

**Comment by redleafnew** [comment]
1.硕博论文可以正常显示了。
2.中文的逗号分号显示为全角了。
3. 英文文献的首字母大写如果设置为Title后在双语这种显示不正常，现在是没有设置，直接读取Zotero条目中的大小写。
4. 姓的多音字你的解决方法是latex的方法，Zotero中不知道怎么办，有时间在论坛上问一下。

**Comment by fredericky123** [comment]
> 1.硕博论文可以正常显示了。
> 2.中文的逗号分号显示为全角了。
> 3. 英文文献的首字母大写如果设置为Title后在双语这种显示不正常，现在是没有设置，直接读取Zotero条目中的大小写。
> 4. 姓的多音字你的解决方法是latex的方法，Zotero中不知道怎么办，有时间在论坛上问一下。

大赞！感谢韩老师！目前暂时遗留问题3、4，我在论坛问问，有思路了提供给您。
此外，英文文献的working paper还有个小bug
Hagedorn，M. ，Manovskii，I. and Mitman，K.，2019，“The Fiscal Multiplier”，NBER Working Paper，No. 25571.
（期刊那里不用斜体，且书写为XX Working Paper, No. XX编号）
给老师一个示例用于检测：https://www.nber.org/papers/w25432

目前需要补充为**”为XX Working Paper, No. XX“**

**Comment by redleafnew** [comment]
1.http://www.mwm.net.cn/Web/Instruction期刊网址的打不开了？
2.这个working paper的文献类型你导出一个示例给我吧，可以用于Zotero导入的格式就可以。
3.因为双语两个layout的官方Zotero是不支持的，以前在论坛上问过，应该是不行了。
4.如果在Zotero论坛上发了帖子告诉我一下地址，我也关注一下。

**Comment by fredericky123** [comment]
> 1.[http://www.mwm.net.cn/Web/Instruction期刊网址的打不开了？](http://www.mwm.net.cn/Web/Instruction%E6%9C%9F%E5%88%8A%E7%BD%91%E5%9D%80%E7%9A%84%E6%89%93%E4%B8%8D%E5%BC%80%E4%BA%86%EF%BC%9F)
> 2.这个working paper的文献类型你导出一个示例给我吧，可以用于Zotero导入的格式就可以。
> 3.因为双语两个layout的官方Zotero是不支持的，以前在论坛上问过，应该是不行了。
> 4.如果在Zotero论坛上发了帖子告诉我一下地址，我也关注一下。

这两天我也打不开期刊网站了，可能期刊网站在整改。

这是示例：
TY  - RPRT
TI  - Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey
AU  - Cheng, Hong
AU  - Fan, Hanbing
AU  - Hoshi, Takeo
AU  - Hu, Dezhuang
AB  - The Chinese government has been using various subsidies to encourage innovations by Chinese firms. This paper examines the allocation and impacts of innovation subsidies, using the data from the China Employer Employee Survey (CEES). We find that the innovation subsidies are preferentially allocated to state owned firms and politically connected firms. Of these two (state ownership and political connection), political connection is more important in determining the allocation. We also find that the firms that receive innovation subsidies file and receive more patents, are more likely to introduce new products, but do not necessarily file and receive more patents abroad. Finally, the firms that receive innovation subsidies do not have higher productivity, more profits, or larger market shares. Overall, the results point to inefficiency of allocation of innovation subsidies and show that the subsidies encourage only incremental innovations and not radical ones.
DA  - 2019/01//
PY  - 2019
DP  - National Bureau of Economic Research
LA  - en
M3  - Working Paper
PB  - National Bureau of Economic Research
SN  - 25432
ST  - Do Innovation Subsidies Make Chinese Firms More Innovative?
UR  - https://www.nber.org/papers/w25432
Y2  - 2021/06/22/07:36:04
ER  -

**Comment by redleafnew** [comment]
> > 1.[http://www.mwm.net.cn/Web/Instruction期刊网址的打不开了？](http://www.mwm.net.cn/Web/Instruction%E6%9C%9F%E5%88%8A%E7%BD%91%E5%9D%80%E7%9A%84%E6%89%93%E4%B8%8D%E5%BC%80%E4%BA%86%EF%BC%9F)
> > 2.这个working paper的文献类型你导出一个示例给我吧，可以用于Zotero导入的格式就可以。
> > 3.因为双语两个layout的官方Zotero是不支持的，以前在论坛上问过，应该是不行了。
> > 4.如果在Zotero论坛上发了帖子告诉我一下地址，我也关注一下。
> 
> 这两天我也打不开期刊网站了，可能期刊网站在整改。
> 
> 这是示例：
> TY - RPRT
> TI - Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey
> AU - Cheng, Hong
> AU - Fan, Hanbing
> AU - Hoshi, Takeo
> AU - Hu, Dezhuang
> AB - The Chinese government has been using various subsidies to encourage innovations by Chinese firms. This paper examines the allocation and impacts of innovation subsidies, using the data from the China Employer Employee Survey (CEES). We find that the innovation subsidies are preferentially allocated to state owned firms and politically connected firms. Of these two (state ownership and political connection), political connection is more important in determining the allocation. We also find that the firms that receive innovation subsidies file and receive more patents, are more likely to introduce new products, but do not necessarily file and receive more patents abroad. Finally, the firms that receive innovation subsidies do not have higher productivity, more profits, or larger market shares. Overall, the results point to inefficiency of allocation of innovation subsidies and show that the subsidies encourage only incremental innovations and not radical ones.
> DA - 2019/01//
> PY - 2019
> DP - National Bureau of Economic Research
> LA - en
> M3 - Working Paper
> PB - National Bureau of Economic Research
> SN - 25432
> ST - Do Innovation Subsidies Make Chinese Firms More Innovative?
> UR - https://www.nber.org/papers/w25432
> Y2 - 2021/06/22/07:36:04
> ER -

针对这个报告应该显示为什么样的具体格式？XX Working Paper, 这个XX是什么？No. XX编号 这个XX是25432？

**Comment by fredericky123** [comment]
> > > 1.[http://www.mwm.net.cn/Web/Instruction期刊网址的打不开了？](http://www.mwm.net.cn/Web/Instruction%E6%9C%9F%E5%88%8A%E7%BD%91%E5%9D%80%E7%9A%84%E6%89%93%E4%B8%8D%E5%BC%80%E4%BA%86%EF%BC%9F)
> > > 2.这个working paper的文献类型你导出一个示例给我吧，可以用于Zotero导入的格式就可以。
> > > 3.因为双语两个layout的官方Zotero是不支持的，以前在论坛上问过，应该是不行了。
> > > 4.如果在Zotero论坛上发了帖子告诉我一下地址，我也关注一下。
> > 
> > 
> > 这两天我也打不开期刊网站了，可能期刊网站在整改。
> > 这是示例：
> > TY - RPRT
> > TI - Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey
> > AU - Cheng, Hong
> > AU - Fan, Hanbing
> > AU - Hoshi, Takeo
> > AU - Hu, Dezhuang
> > AB - The Chinese government has been using various subsidies to encourage innovations by Chinese firms. This paper examines the allocation and impacts of innovation subsidies, using the data from the China Employer Employee Survey (CEES). We find that the innovation subsidies are preferentially allocated to state owned firms and politically connected firms. Of these two (state ownership and political connection), political connection is more important in determining the allocation. We also find that the firms that receive innovation subsidies file and receive more patents, are more likely to introduce new products, but do not necessarily file and receive more patents abroad. Finally, the firms that receive innovation subsidies do not have higher productivity, more profits, or larger market shares. Overall, the results point to inefficiency of allocation of innovation subsidies and show that the subsidies encourage only incremental innovations and not radical ones.
> > DA - 2019/01//
> > PY - 2019
> > DP - National Bureau of Economic Research
> > LA - en
> > M3 - Working Paper
> > PB - National Bureau of Economic Research
> > SN - 25432
> > ST - Do Innovation Subsidies Make Chinese Firms More Innovative?
> > UR - https://www.nber.org/papers/w25432
> > Y2 - 2021/06/22/07:36:04
> > ER -
> 
> 针对这个报告应该显示为什么样的具体格式？XX Working Paper, 这个XX是什么？No. XX编号 这个XX是25432？
TY  - RPRT
TI  - Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey
AU  - Cheng, Hong
AU  - Fan, Hanbing
AU  - Hoshi, Takeo
AU  - Hu, Dezhuang
AB  - The Chinese government has been using various subsidies to encourage innovations by Chinese firms. This paper examines the allocation and impacts of innovation subsidies, using the data from the China Employer Employee Survey (CEES). We find that the innovation subsidies are preferentially allocated to state owned firms and politically connected firms. Of these two (state ownership and political connection), political connection is more important in determining the allocation. We also find that the firms that receive innovation subsidies file and receive more patents, are more likely to introduce new products, but do not necessarily file and receive more patents abroad. Finally, the firms that receive innovation subsidies do not have higher productivity, more profits, or larger market shares. Overall, the results point to inefficiency of allocation of innovation subsidies and show that the subsidies encourage only incremental innovations and not radical ones.
DA  - 2019/01//
PY  - 2019
DP  - National Bureau of Economic Research
LA  - en
M3  - Working Paper
PB  - NBER
SN  - 25432
ST  - Do Innovation Subsidies Make Chinese Firms More Innovative?
UR  - https://www.nber.org/papers/w25432
Y2  - 2021/06/22/07:36:04
ER  - 
针对这个示例，应该显示为National Bureau of Economic Research Working Paper, No. 25432

**Comment by fredericky123** [comment]
TY  - RPRT
TI  - Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey
AU  - Cheng, Hong
AU  - Fan, Hanbing
AU  - Hoshi, Takeo
AU  - Hu, Dezhuang
AB  - The Chinese government has been using various subsidies to encourage innovations by Chinese firms. This paper examines the allocation and impacts of innovation subsidies, using the data from the China Employer Employee Survey (CEES). We find that the innovation subsidies are preferentially allocated to state owned firms and politically connected firms. Of these two (state ownership and political connection), political connection is more important in determining the allocation. We also find that the firms that receive innovation subsidies file and receive more patents, are more likely to introduce new products, but do not necessarily file and receive more patents abroad. Finally, the firms that receive innovation subsidies do not have higher productivity, more profits, or larger market shares. Overall, the results point to inefficiency of allocation of innovation subsidies and show that the subsidies encourage only incremental innovations and not radical ones.
DA  - 2019/01//
PY  - 2019
DP  - National Bureau of Economic Research
LA  - en
M3  - Working Paper
PB  - NBER
SN  - 25432
ST  - Do Innovation Subsidies Make Chinese Firms More Innovative?
UR  - https://www.nber.org/papers/w25432
Y2  - 2021/06/22/07:36:04
ER  - 
针对这个示例，应该显示为NBER Working Paper, No. 25432

**Comment by redleafnew** [comment]
Cheng H., Fan H., Hoshi T., et al., 2019, “Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey”, National Bureau of Economic Research Working Paper, No.25432.

现在显示成这样了。
在导入的Zotero中没有哪个变量的值是NBER，直接在Working Paper前加NBER？这样所有的文献类型的都成NBER Working Paper了，可以吗？

**Comment by fredericky123** [comment]
> Cheng H., Fan H., Hoshi T., et al., 2019, “Do Innovation Subsidies Make Chinese Firms More Innovative? Evidence from the China Employer Employee Survey”, National Bureau of Economic Research Working Paper, No.25432.
> 
> 现在显示成这样了。
> 在导入的Zotero中没有哪个变量的值是NBER，直接在Working Paper前加NBER？这样所有的文献类型的都成NBER Working Paper了，可以吗？

韩老师用上面这个最新的导入，我将institution改为nber了

**Comment by redleafnew** [comment]
或是你自己将Zotero中这个条目的Institution改为NBER，现在调用的是Institution这个变量值

**Comment by redleafnew** [comment]
我自己导入的也是National Bureau of Economic Research

**Comment by fredericky123** [comment]
Great,我想的就是调用instution

**Comment by redleafnew** [comment]
更新了，你再试一下效果。

**Comment by fredericky123** [comment]
> 更新了，你再试一下效果。

可以了！很完美，现在就差英文题目大写和中文作者排序的问题了，这两个看来暂时不好解决。

还有个刷新的小问题，为啥我每次zotero刷新完，参考文献的样式变为了正文，只得每次再选中文本应用自定义的格式

**Comment by fredericky123** [comment]
又发现个小问题，英文文献如果是期刊论文的话，期刊名需要斜体，如果是wokring paper，不用斜体，现在的效果两个都不是斜体

Kang， J. K. and Kim， J. M.， 2008，“The Geography of Block Acquisitions”， _Journal of Finance_， 63(6)， pp.2817~2858.

Hagedorn，M. ，Manovskii，I. and Mitman，K.，2019，“The Fiscal Multiplier”，NBER Working Paper，No. 25571.

**Comment by redleafnew** [comment]
> > 更新了，你再试一下效果。
> 
> 可以了！很完美，现在就差英文题目大写和中文作者排序的问题了，这两个看来暂时不好解决。
> 
> 还有个刷新的小问题，为啥我每次zotero刷新完，参考文献的样式变为了正文，只得每次再选中文本应用自定义的格式

https://zhuanlan.zhihu.com/p/58969571

**Comment by fredericky123** [comment]
> > > 更新了，你再试一下效果。
> > 
> > 
> > 可以了！很完美，现在就差英文题目大写和中文作者排序的问题了，这两个看来暂时不好解决。
> > 还有个刷新的小问题，为啥我每次zotero刷新完，参考文献的样式变为了正文，只得每次再选中文本应用自定义的格式
> 
> https://zhuanlan.zhihu.com/p/58969571

我就是参照这个的，我的理解是zotero会将参考文献的样式设为”书目“，所以修改相应的格式即可，然而我发现我一刷新，参考文献的样式为”正文“，好奇怪啊

**Comment by redleafnew** [comment]
<img width="874" alt="Snipaste_2021-06-23_20-12-58" src="https://user-images.githubusercontent.com/22135631/123094558-9616f280-d45f-11eb-81d9-a38b38126a7c.png">
斜体这两个我这显示是正常的，期刊斜体，报告没有斜体。

**Comment by fredericky123** [comment]
> <img alt="Snipaste_2021-06-23_20-12-58" width="874" src="https://user-images.githubusercontent.com/22135631/123094558-9616f280-d45f-11eb-81d9-a38b38126a7c.png">
> 
> 斜体这两个我这显示是正常的，期刊斜体，报告没有斜体。

找到原因了，zotero刷新后字体大小、编号等没有匹配，通过样式一刷新，斜体被改动了

**Comment by redleafnew** [comment]
如果没有其它问题，这个issue关闭了啊。
多音字那个你可以问一下。
Title case那个问题我在论坛上看到了。各种不同的效果，https://editor.citationstyles.org/visualEditor/ 可以在这上试试，如果只是一个layout显示是正常的，如果是我们现在这种显示就会异常。

**Comment by fredericky123** [comment]
> 如果没有其它问题，这个issue关闭了啊。
> 多音字那个你可以问一下。
> Title case那个问题我在论坛上看到了。各种不同的效果，https://editor.citationstyles.org/visualEditor/ 可以在这上试试，如果只是一个layout显示是正常的，如果是我们现在这种显示就会异常。

好的，多谢韩老师！

**Comment by fredericky123** [comment]
韩老师，这里应还是可以补充一个点，就是加上编号，编号格式是
（1）
（2）
（3）
括号是全角的

**Comment by redleafnew** [comment]
英文的也是全角？

**Comment by fredericky123** [comment]
> 英文的也是全角？

是的

**Comment by redleafnew** [comment]
再试一下呢

**Comment by fredericky123** [comment]
> 再试一下呢

完美，好像还能设置首行缩进两字符？这样就更方便了

**Comment by redleafnew** [comment]
这个可以在Word的书目样式中设置。Zotero中好像不可以或实现起来麻烦。
BTW，你是哪个学校的？

**Comment by fredericky123** [comment]
> 这个可以在Word的书目样式中设置。Zotero中好像不可以或实现起来麻烦。
> BTW，你是哪个学校的？

韩老师我之前加了您qq☺

**Comment by fredericky123** [comment]
关于title case的问题，感觉能解决
https://forums.zotero.org/discussion/87201/title-case-questions

不知道csl 1.2是不是已经发布了

**Comment by redleafnew** [comment]
呵呵，QQ说个话呢。

1.2说是去年就出来的。
https://citationstyles.org/2020/07/11/seeking-public-comment-on-CSL-1-0-2/

**Comment by fredericky123** [comment]
https://forums.zotero.org/discussion/87201/title-case-questions
我在论坛上检索了下较近的帖子，不过还没来得及看细节

**Comment by redleafnew** [comment]
有时间了研究了。

**Comment by fredericky123** [comment]
> 有时间了研究一下。

嗯嗯☺

**Comment by fredericky123** [comment]
韩老师，如果作者是两个人，文中的引用会多了一个逗号，如图
![image](https://user-images.githubusercontent.com/13982749/123427646-7a465480-d5f7-11eb-8e99-053012a29da5.png)

**Comment by redleafnew** [comment]
我的是正常的，把这个条目或下载地址给我测试一下。

**Comment by fredericky123** [comment]
> 我的是正常的，把这个条目或下载地址给我测试一下。

TY  - JOUR
TI  - 政府的科技激励政策对大中型工业企业 R&D 投入及其专利产出的影响——上海市的实证研究
AU  - 朱平芳
AU  - 徐伟民
T2  - 经济研究
DA  - 2003///
PY  - 2003
IS  - 6
SP  - 45
EP  - 53
LA  - 中文
KW  - ⛔ No DOI found
ER  -

**Comment by redleafnew** [comment]
![Uploading 录制_2021_06_25_21_45_14_733.gif…]()

**Comment by redleafnew** [comment]
作者的原因，改成这样就可以了：
AU  - 朱, 平芳
AU  - 徐, 伟民
在Zotero中
<img width="253" alt="Snipaste_2021-06-25_21-50-28" src="https://user-images.githubusercontent.com/22135631/123435809-8da9ed80-d600-11eb-9c7f-cd8a9d2e3138.png">

**Comment by fredericky123** [comment]
> 作者的原因，改成这样就可以了：
> AU - 朱, 平芳
> AU - 徐, 伟民
> 在Zotero中
> <img alt="Snipaste_2021-06-25_21-50-28" width="253" src="https://user-images.githubusercontent.com/22135631/123435809-8da9ed80-d600-11eb-9c7f-cd8a9d2e3138.png">

搞定了，感谢韩老师！
