### ISSUE TITLE
麻烦老师制作一个《中国工业经济》的样式

### ISSUE THREAD

**Issue by hwanghan** [redleafnew/Chinese-STD-GB-T-7714-related-csl#60]
011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses，如果是两位作者的中文文献，显示出来的效果是`（张三 李四, 2021）`，姓名之间能否将空格改为“和”？

**Comment by redleafnew** [comment]
这是哪个期刊或学校的要求，请提供详细信息。
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by hwanghan** [comment]
> 这是哪个期刊或学校的要求，请提供详细信息。 加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

《中国工业经济》杂志，格式要求见http://ciejournal.ajcass.org/CommonBlock/SiteContentDetail?contentID=147144，PDF文档中第14页开始为参考文献要求。

**Comment by redleafnew** [comment]
现在与011最接近吗？
请列出需要修改的地方。
加入Zotero群组，新建文件夹中国工业经济，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
011的显示是两个及以上作者只显示第一作者加et al或等的。

**Comment by redleafnew** [comment]
最好是将格式要求中的文献加入到群组中方便测试。

**Comment by hwanghan** [comment]
比较了一下，《中国工业经济》的样式应该和《经济管理》最为接近，主要区别如下：

1. 正文中的引用不需要[1]上标；
2. 正文中如果出现文献作者名，有 2 个作者，用“甲和乙（年份）”（英文名用“A and B（年份）”）连接。有 3 个或者更多作者，用“甲等（年份）”（英文名为“A et al.（年份）”）表示。
3. 文末的参考文献中文在前，英文在后。
另外已经在群组中增加了中国工业经济文件夹。

**Comment by redleafnew** [comment]
> (Abel et al, 2022)
> (Engers and Gans, 1998)
> (伊宪华等, 2009)
> (李幼平和王莉, 2010)
> (Li et al, 2021)
> [1] 伊宪华, 韩雅玲, 李毅, 等. 介入治疗开通慢性完全闭塞病变的长期临床疗效[J]. 中华心血管病杂志, 2009, 37(9): 773–776[2022-04-29].	
> [2] 李幼平, 王莉. 循证医学研究方法: 附视频[J]. 中华移植杂志(电子版), 2010, 4(3): 225–228[2014-06-09].	
> [3] Engers M. and J. S. Gans. Why Referees Are Not Paid (Enough)[J]. American Economic Review, 1998, 88(5): 1341–1349[2022-07-10].	
> [4] Li X., S. Shen, Y. Xu, et al. Application of membrane separation processes in phosphorus recovery: A review[J]. Science of The Total Environment, 2021, 767: 144346[2022-06-11].	
> [5] Abel N., B. T. Rotabakk, and J. Lerfall. Mild processing of seafood—A review[J]. Comprehensive Reviews in Food Science and Food Safety, 2022, 21(1): 340–370[2022-02-15].	

现在是这个效果。

**Comment by redleafnew** [comment]
@zepinglee 我记得你说过参考文献列表按语言排序不需要在`bibliography`添加这个来吗？
```
        <sort>
            <key variable="language" sort="descending" />
        </sort>
```

**Comment by redleafnew** [comment]
访问日期也删除了：

> (Abel et al, 2022)
> (Engers and Gans, 1998)
> (伊宪华等, 2009)
> (李幼平和王莉, 2010)
> (Li et al, 2021)
> [1] 伊宪华, 韩雅玲, 李毅, 等. 介入治疗开通慢性完全闭塞病变的长期临床疗效[J]. 中华心血管病杂志, 2009, 37(9): 773–776.	
> [2] 李幼平, 王莉. 循证医学研究方法: 附视频[J]. 中华移植杂志(电子版), 2010, 4(3): 225–228.	
> [3] Engers M. and J. S. Gans. Why Referees Are Not Paid (Enough)[J]. American Economic Review, 1998, 88(5): 1341–1349.	
> [4] Li X., S. Shen, Y. Xu, et al. Application of membrane separation processes in phosphorus recovery: A review[J]. Science of The Total Environment, 2021, 767: 144346.	
> [5] Abel N., B. T. Rotabakk, and J. Lerfall. Mild processing of seafood—A review[J]. Comprehensive Reviews in Food Science and Food Safety, 2022, 21(1): 340–370.

**Comment by hwanghan** [comment]
我对比了一下还有一些小问题：
文末参考文献列表中，无论中英文文献都列出所有作者，不用加`,等`；英文文献最后一个作者前加上`, and`（即使只有2个作者也是如此）。

**Comment by redleafnew** [comment]
这样？
> (Abel et al, 2022)
> (Engers and Gans, 1998)
> (伊宪华等, 2009)
> (李幼平和王莉, 2010)
> (Li et al, 2021)
> [1] 伊宪华, 韩雅玲, 李毅, 王守力, 荆全民, 马颖艳, 王效增, 栾波, 王耿. 介入治疗开通慢性完全闭塞病变的长期临床疗效[J]. 中华心血管病杂志, 2009, 37(9): 773–776.	
> [2] 李幼平, 王莉. 循证医学研究方法: 附视频[J]. 中华移植杂志(电子版), 2010, 4(3): 225–228.	
> [3] Engers M. and J. S. Gans. Why Referees Are Not Paid (Enough)[J]. American Economic Review, 1998, 88(5): 1341–1349.	
> [4] Li X., S. Shen, Y. Xu, T. Guo, H. Dai, and X. Lu. Application of membrane separation processes in phosphorus recovery: A review[J]. Science of The Total Environment, 2021, 767: 144346.	
> [5] Abel N., B. T. Rotabakk, and J. Lerfall. Mild processing of seafood—A review[J]. Comprehensive Reviews in Food Science and Food Safety, 2022, 21(1): 340–370.	
> 
>

**Comment by redleafnew** [comment]
两个英文作者的and前也加了逗号。

> (Abel et al, 2022)
> (Engers and Gans, 1998)
> (伊宪华等, 2009)
> (李幼平和王莉, 2010)
> (Li et al, 2021)
> [1] 伊宪华, 韩雅玲, 李毅, 王守力, 荆全民, 马颖艳, 王效增, 栾波, 王耿. 介入治疗开通慢性完全闭塞病变的长期临床疗效[J]. 中华心血管病杂志, 2009, 37(9): 773–776.	
> [2] 李幼平, 王莉. 循证医学研究方法: 附视频[J]. 中华移植杂志(电子版), 2010, 4(3): 225–228.	
> [3] Engers M., and J. S. Gans. Why Referees Are Not Paid (Enough)[J]. American Economic Review, 1998, 88(5): 1341–1349.	
> [4] Li X., S. Shen, Y. Xu, T. Guo, H. Dai, and X. Lu. Application of membrane separation processes in phosphorus recovery: A review[J]. Science of The Total Environment, 2021, 767: 144346.	
> [5] Abel N., B. T. Rotabakk, and J. Lerfall. Mild processing of seafood—A review[J]. Comprehensive Reviews in Food Science and Food Safety, 2022, 21(1): 340–370.	
> 
>

**Comment by hwanghan** [comment]
是的，非常感谢！

**Comment by redleafnew** [comment]
还有其它要修改的吗？

**Comment by hwanghan** [comment]
其他类型的文献对作者的处理也是这种规则，我加入了两篇`Book`到群组，您可以再测试一下。其他就没有什么问题了。

**Comment by zepinglee** [comment]
> @zepinglee 我记得你说过参考文献列表按语言排序不需要在`bibliography`添加这个来吗？
> 
> ```
>         <sort>
>             <key variable="language" sort="descending" />
>         </sort>
> ```

对的，`style` 的 `default-locale="zh-CN"` 就已经足够了。

**Comment by redleafnew** [comment]
> > @zepinglee 我记得你说过参考文献列表按语言排序不需要在`bibliography`添加这个来吗？
> > ```
> >         <sort>
> >             <key variable="language" sort="descending" />
> >         </sort>
> > ```
> 
> 对的，`style` 的 `default-locale="zh-CN"` 就已经足够了。

但中文在前就不行了吧

**Comment by zepinglee** [comment]
> 但中文在前就不行了吧

`default-locale="zh-CN"` 应该是中文在前的。

**Comment by redleafnew** [comment]
@hwanghan 看一下，可以的话就上传。
> (Abel et al, 2022)
> (Fan and Sommers, 2013)
> (Engers and Gans, 1998)
> (伊宪华等, 2009)
> (蒋有绪等, 1998)
> (李幼平和王莉, 2010)
> (Li et al, 2021)
> [1] 伊宪华, 韩雅玲, 李毅, 王守力, 荆全民, 马颖艳, 王效增, 栾波, 王耿. 介入治疗开通慢性完全闭塞病变的长期临床疗效[J]. 中华心血管病杂志, 2009, 37(9): 773–776.	
> [2] 蒋有绪, 郭泉水, 马娟, Others. 中国森林群落分类及其群落特征[M]. 北京: 科学出版社, 1998.	
> [3] 李幼平, 王莉. 循证医学研究方法: 附视频[J]. 中华移植杂志(电子版), 2010, 4(3): 225–228.	
> [4] Engers M., and J. S. Gans. Why Referees Are Not Paid (Enough)[J]. American Economic Review, 1998, 88(5): 1341–1349.	
> [5] Li X., S. Shen, Y. Xu, T. Guo, H. Dai, and X. Lu. Application of membrane separation processes in phosphorus recovery: A review[J]. Science of The Total Environment, 2021, 767: 144346.	
> [6] Abel N., B. T. Rotabakk, and J. Lerfall. Mild processing of seafood—A review[J]. Comprehensive Reviews in Food Science and Food Safety, 2022, 21(1): 340–370.	
> [7] Fan X., and C. H. Sommers. Food irradiation research and technology[M]. 2 edition. Ames, Iowa: Blackwell Publishing, 2013: 25–26.

**Comment by zepinglee** [comment]
> 其他类型的文献对作者的处理也是这种规则，我加入了两篇`Book`到群组，您可以再测试一下。其他就没有什么问题了。

将期刊的官方示例录入 Zotero。

**Comment by redleafnew** [comment]
> > 但中文在前就不行了吧
> 
> `default-locale="zh-CN"` 应该是中文在前的。

好像不是，我删除排序代码后是英文在前的。

**Comment by zepinglee** [comment]
> 好像不是，我删除排序代码后是英文在前的。

传到新建一个分支，我来看一下？

**Comment by redleafnew** [comment]
上传为207了，不知道怎么传到一个新建分支。

**Comment by hwanghan** [comment]
已经将群组中的文献全部更新为《中国工业经济》投稿指南中的示例

**Comment by hwanghan** [comment]
连续引用时，正文中的citation还有些问题，现在显示的是`(Raisch and Birkinshaw, 2008),(Khan et al, 2020)`，应该是`(Raisch and Birkinshaw, 2008; Khan et al, 2020)`才对。

**Comment by hwanghan** [comment]
连续引用时还有些问题，现在显示为`(Raisch and Birkinshaw, 2008),(Khan et al, 2020)`，应该是`(Raisch and Birkinshaw, 2008; Khan et al, 2020)`才对。

**Comment by redleafnew** [comment]
这个不是style的问题，连续插入即可。

**Comment by hwanghan** [comment]
> > 这个不是style的问题，连续插入即可。
> 
> 我再测试一下

我测试连续插入仍然不对

**Comment by zepinglee** [comment]
> 上传为207了，不知道怎么传到一个新建分支。

这是 author-date 样式，要按作者姓名排序的。
```xml
      <sort>
        <key macro="author-cn"/>
        <key macro="issued-year"/>
      </sort>
```

@redleafnew 另外你是从哪个 csl 改起的？原来的 csl 有好多问题没处理好。

**Comment by zepinglee** [comment]
> 我测试连续插入仍然不对

@hwanghan 引用时使用经典视图，左下角选择 multiple sources，然后选多个文献。
<img width="919" alt="Screen Shot 2022-07-10 at 12 10 37" src="https://user-images.githubusercontent.com/12290822/178130996-00310a19-cc98-4fb8-9e6a-525a9cbd2492.png">

**Comment by hwanghan** [comment]
> > 我测试连续插入仍然不对
> 
> @hwanghan 引用时使用经典视图，左下角选择 multiple sources，然后选多个文献。 <img alt="Screen Shot 2022-07-10 at 12 10 37" width="919" src="https://user-images.githubusercontent.com/12290822/178130996-00310a19-cc98-4fb8-9e6a-525a9cbd2492.png">

经测试，应该还是样式问题，采取经典视图连续插入仍然有问题，但是如果将样式文件更换为`GB/T 7714-2015 (著者-出版年, 双语, 姓名取消大写, 无 URL DOI, 全角括号`或者其他的就没有问题。

**Comment by zepinglee** [comment]
> 经测试，应该还是样式问题，采取经典视图连续插入仍然有问题，但是如果将样式文件更换为`GB/T 7714-2015 (著者-出版年, 双语, 姓名取消大写, 无 URL DOI, 全角括号`或者其他的就没有问题。

@hwanghan 确实，目前的 207 不支持多个引用连在一起。我还是从 011 再改一份吧。

**Comment by redleafnew** [comment]
已修复，github上传中，

**Comment by redleafnew** [comment]
再试一下

**Comment by hwanghan** [comment]
更新后的文件似乎有问题，总是提示无效的样式文件

**Comment by redleafnew** [comment]
再试一下

**Comment by hwanghan** [comment]
@redleafnew @zepinglee  好了，感谢二位

**Comment by redleafnew** [comment]
如果无问题就关闭了。
@zepinglee 原来的文件确实有些问题。

**Comment by zepinglee** [comment]
我在 011 的基础上改了一版 [208](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/208chinas-industrial-economics.csl)。

跟 207 对比了一下，发现 207 还有几个问题：
1. `引用中的 et al` 后缺少点号“.”。
2. `<text variable="citation-number">` 需要显式地写到 `<layout>` 中才能使 `second-field-align="flush"` 生效。
3. 析出文献的格式不用“//”（我补充了测试样例）。
4. 文后参考文献表中第一作者的姓后缺少逗号，如“Engers, M.”，应设置 `sort-separator=", "`。
5. editor 的名缺少缩写点，如“Aghion P”，建议全局设置 `initialize-with=". "`。
6. 原版《经济管理》存在的一些问题，比如
    - 出版年前缺少点号：“Broda C., G. Joshua, and W. David. From groundnuts to globalization: A structural estimate of trade and growth[Z](2006).”
    - 重复的点号：“中国互联网络信息中心. 第 29 次中国互联网络发展现状统计报告[R]. .”
  建议不要从这些旧的有问题的 csl 上开始修改了。

**Comment by redleafnew** [comment]
![33ZP(L0_BU5T9%IEMWO_`OE](https://user-images.githubusercontent.com/22135631/178136246-c31b61bd-bd1f-493c-a04a-86256e045925.png)
都忘了哪个有问题了。

**Comment by hwanghan** [comment]
> 我在 011 的基础上改了一版 [208](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/208chinas-industrial-economics.csl)。
> 
> 跟 207 对比了一下，发现 207 还有几个问题：
> 
> 1. `引用中的 et al` 后缺少点号“.”。
> 2. `<text variable="citation-number">` 需要显式地写到 `<layout>` 中才能使 `second-field-align="flush"` 生效。
> 3. 样式要求标题使用 title case，缺少 title case 的转换（似乎 `citeproc-js` 的处理有些问题，我去给他们反馈一下）。
> 4. 析出文献的格式不用“//”（我补充了测试样例）。
> 5. 文后参考文献表中第一作者的姓后缺少逗号，如“Engers M.”，应设置 `sort-separator=", "`。
> 6. editor 的名缺少缩写点，如“Aghion P”，建议全局设置 `initialize-with=". "`。
> 7. 原版《经济管理》存在的一些问题，比如
>    
>    * 出版年前缺少点号：“`Broda C., G. Joshua, and W. David. From groundnuts to globalization: A structural estimate of trade and growth[Z](2006).`”
>    * 重复的点号：“`中国互联网络信息中心. 第 29 次中国互联网络发展现状统计报告[R]. .`”
>      建议不要从这些旧的有问题的 csl 上开始修改了。

我刚刚试了下208版，大致存在以下几个问题：

1. 英文citation两个作者之间为“和”，应该改为and，多个作者结尾为“等”，应该改为et al.
2. 文末的英文参考文献中，最后一个作者前面为“和”，应该改为“, and"，例如：`Alexiev, A., J. Jansen, F. Bosch和H. Volberda. Top Management Team Advice Seeking and Exploratory Innovation: The Moderating Role of TMT Heterogeneity[J]. Journal of Management Studies, 2010, 47(7):1343-1364.`，应该改为`Alexiev, A., J. Jansen, F. Bosch, and H. Volberda. Top Management Team Advice Seeking and Exploratory Innovation: The Moderating Role of TMT Heterogeneity[J]. Journal of Management Studies, 2010, 47(7):1343-1364.`

**Comment by zepinglee** [comment]
> 我刚刚试了下208版，大致存在以下几个问题：
> 
> 1. 英文citation两个作者之间为“和”，应该改为and，多个作者结尾为“等”，应该改为et al.
> 2. 文末的英文参考文献中，最后一个作者前面为“和”，应该改为“, and"，例如：`Alexiev, A., J. Jansen, F. Bosch和H. Volberda. Top Management Team Advice Seeking and Exploratory Innovation: The Moderating Role of TMT Heterogeneity[J]. Journal of Management Studies, 2010, 47(7):1343-1364.`，应该改为`Alexiev, A., J. Jansen, F. Bosch, and H. Volberda. Top Management Team Advice Seeking and Exploratory Innovation: The Moderating Role of TMT Heterogeneity[J]. Journal of Management Studies, 2010, 47(7):1343-1364.`

引用时需要将默认语言设成 en-US。

这么做是为了避免 `citeproc-js` 处理标题大小写的 bug。
