### ISSUE TITLE
可否适配华中科技大学的学位论文参考文献样式

### ISSUE THREAD

**Issue by tangjyan** [redleafnew/Chinese-STD-GB-T-7714-related-csl#62]
> 参考文献格式
> 中文书刊：作者按中文写法，姓在前、名在后；英文书刊：作者按英文习惯写法，如名在前、姓在后，名用首字母缩写、姓用全称。一般6人以内须列出全部作者，6人以上写6人再加“等”（英文加“et al”））。每个参考文献的最后不加标点符号。
> （1）图书：最多列出6个作者，作者与作者之间用逗号分隔. 书名. 版本（第×版）. 译者. 出版地: 出版者, 出版年. 起页-止页（可选）
> （2）期刊：最多列出6个作者，作者与作者之间用逗号分隔. 文章名. 期刊名（全称）. 年号, 卷号（期号）: 起页-止页或论文编号
> （3）会议论文集：最多列出6个作者，作者之间用逗号分隔. 文章名. 见（英文用“in”）：会议名称（或论文集）. 会议城市, 国家, 会议时间, 出版者, 出版年: 起页-止页
> （4）专利：专利申请者. 专利题名. 专利国别, 专利文献种类, 专利号, 出版年
> （5）学位论文：作者. 题名：[博士（或硕士）学位论文]. 保存地点: 保存单位（如华中科技大学, 年份）
> 参考文献（举例）
> [1]	闫明礼, 张东刚. CFG桩复合地基技术及工程实践（第二版）. 北京: 中国水利水电出版社, 2006
> [2]	M. Chalfie, S. R. Kain. Green fluorescent protein: properties, applications, and protocols. Hoboken, New Jersey: Wiley-interscience, 1998
> [3]	詹向红, 李德新. 中医药防治阿尔茨海默病实验研究述要. 中华中医药学刊, 2004, 22(11): 2094-2096
> [4]	E. S. Lein, M. J. Hawrylycz, N. Ao, M. Ayres, A. Bensinger, A. Bernard, et al. Genome-wide atlas of gene expression in the adult mouse brain. Nature, 2007, 445(7124): 168-176
> [5]	M. L. Bouxsein, S. K. Boyd, B. A. Christiansen, R. E. Guldberg, K. J. Jepsen, R. Müller. Guidelines for assessment of bone microstructure in rodents using micro–computed tomography. Journal of Bone and Mineral Research, 2010, 25(7): 1468-1486
> [6]	Y. Shunsuke, A. Masahide, K. Masayuki, M. Yoshizawa. Performance evaluation of phase-only correlation functions from the viewpoint of correlation Filters, in: 2018 Asia-Pacific Signal and Information Processing Association Annual Summit and Conference (APSIPA ASC), Honolulu, HI, USA, 12-15 Nov. 2018, Proceedings of the IEEE, 2019: 1361-1364
> [7]	T. Yao, J. Wan, P. Huang, X. He, F. Wu, C. Xie. Building efficient key-value stores via a lightweight compaction tree. ACM Transactions on Storage, 2017, 13(4): 1-28
> [8]	刘加林. 多功能一次性压舌板: 中国, ZL92214985. 2 [P]. 1993
> [9]	李清泉. 基于混合数据结构的三维GIS数据模型与空间分析研究[博士学位论文]. 武汉: 武汉测绘科技大学, 1998
> 

![image](https://user-images.githubusercontent.com/21167731/181920094-9e8cb5f6-fe1c-4c51-81b9-92aa694d7333.png)

**Comment by zepinglee** [comment]
这个比较接近 GB/T 7714 但是仍有一定的细节需要调整。另外有没有学校官网样式文件的链接？

**Comment by redleafnew** [comment]
加入Zotero群组，将上面的条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

同时如
@zepinglee 所言提供样式官方地方。

**Comment by tangjyan** [comment]
> 这个比较接近 GB/T 7714 但是仍有一定的细节需要调整。另外有没有学校官网样式文件的链接？

http://gs.hust.edu.cn/info/1019/11815.htm 这是官方【2009】年的文件，2021年重申。里面介绍了学位论文参考文献的格式。

**Comment by tangjyan** [comment]
> 加入Zotero群组，将上面的条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development
> 
> 同时如 @zepinglee 所言提供样式官方地方。

已加入群组并建立 \HUST测试文件

**Comment by redleafnew** [comment]
> 参考文献（举例）
> [1] 闫明礼, 张东刚. CFG桩复合地基技术及工程实践（第二版）. 北京: 中国水利水电出版社, 2006
> [2] M. Chalfie, S. R. Kain. Green fluorescent protein: properties, applications, and protocols. Hoboken, New Jersey: Wiley-interscience, 1998
> [3] 詹向红, 李德新. 中医药防治阿尔茨海默病实验研究述要. 中华中医药学刊, 2004, 22(11): 2094-2096
@tangjyan 
把这些参考文献条目录入到那个群组中吧，方便调试时对照查看。

**Comment by redleafnew** [comment]
另外只有专利标注一个[P]，其它文献类型不标注？

**Comment by tangjyan** [comment]
> 

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/62#issuecomment-1200356414

**Comment by tangjyan** [comment]
> > 参考文献（举例）
> > [1] 闫明礼, 张东刚. CFG桩复合地基技术及工程实践（第二版）. 北京: 中国水利水电出版社, 2006
> > [2] M. Chalfie, S. R. Kain. Green fluorescent protein: properties, applications, and protocols. Hoboken, New Jersey: Wiley-interscience, 1998
> > [3] 詹向红, 李德新. 中医药防治阿尔茨海默病实验研究述要. 中华中医药学刊, 2004, 22(11): 2094-2096
> 
> @tangjyan
> 
> 把这些参考文献条目录入到那个群组中吧，方便调试时对照查看。

![image](https://user-images.githubusercontent.com/21167731/182017325-89cc976a-2963-4456-b0ee-57a4c948bdd7.png)
我加了呀，单独建立了一个文件夹。

**Comment by tangjyan** [comment]
> 参考文献格式
> 中文书刊：作者按中文写法，姓在前、名在后；英文书刊：作者按英文习惯写法，如名在前、姓在后，名用首字母缩写、姓用全称。一般6人以内须列出全部作者，6人以上写6人再加“等”（英文加“et al”））。每个参考文献的最后不加标点符号。
> （1）图书：最多列出6个作者，作者与作者之间用逗号分隔. 书名. 版本（第×版）. 译者. 出版地: 出版者, 出版年. 起页-止页（可选）
> （2）期刊：最多列出6个作者，作者与作者之间用逗号分隔. 文章名. 期刊名（全称）. 年号, 卷号（期号）: 起页-止页或论文编号
> （3）会议论文集：最多列出6个作者，作者之间用逗号分隔. 文章名. 见（英文用“in”）：会议名称（或论文集）. 会议城市, 国家, 会议时间, 出版者, 出版年: 起页-止页
> （4）专利：专利申请者. 专利题名. 专利国别, 专利文献种类, 专利号, 出版年
> （5）学位论文：作者. 题名：[博士（或硕士）学位论文]. 保存地点: 保存单位（如华中科技大学, 年份）
> 参考文献（举例）
> [1] 闫明礼, 张东刚. CFG桩复合地基技术及工程实践（第二版）. 北京: 中国水利水电出版社, 2006
> [2] M. Chalfie, S. R. Kain. Green fluorescent protein: properties, applications, and protocols. Hoboken, New Jersey: Wiley-interscience, 1998
> [3] 詹向红, 李德新. 中医药防治阿尔茨海默病实验研究述要. 中华中医药学刊, 2004, 22(11): 2094-2096
> [4] E. S. Lein, M. J. Hawrylycz, N. Ao, M. Ayres, A. Bensinger, A. Bernard, et al. Genome-wide atlas of gene expression in the adult mouse brain. Nature, 2007, 445(7124): 168-176
> [5] M. L. Bouxsein, S. K. Boyd, B. A. Christiansen, R. E. Guldberg, K. J. Jepsen, R. Müller. Guidelines for assessment of bone microstructure in rodents using micro–computed tomography. Journal of Bone and Mineral Research, 2010, 25(7): 1468-1486
> [6] Y. Shunsuke, A. Masahide, K. Masayuki, M. Yoshizawa. Performance evaluation of phase-only correlation functions from the viewpoint of correlation Filters, in: 2018 Asia-Pacific Signal and Information Processing Association Annual Summit and Conference (APSIPA ASC), Honolulu, HI, USA, 12-15 Nov. 2018, Proceedings of the IEEE, 2019: 1361-1364
> [7] T. Yao, J. Wan, P. Huang, X. He, F. Wu, C. Xie. Building efficient key-value stores via a lightweight compaction tree. ACM Transactions on Storage, 2017, 13(4): 1-28
> [8] 刘加林. 多功能一次性压舌板: 中国, ZL92214985. 2 [P]. 1993
> [9] 李清泉. 基于混合数据结构的三维GIS数据模型与空间分析研究[博士学位论文]. 武汉: 武汉测绘科技大学, 1998

我询问了我们学校负责Latex模版的团队，他们以文字描述为准，案例不准确。
https://github.com/Lianghao93/HUST-PhD-Thesis-Latex-v3.1

**Comment by redleafnew** [comment]
> > > 参考文献（举例）
> > > [1] 闫明礼, 张东刚. CFG桩复合地基技术及工程实践（第二版）. 北京: 中国水利水电出版社, 2006
> > > [2] M. Chalfie, S. R. Kain. Green fluorescent protein: properties, applications, and protocols. Hoboken, New Jersey: Wiley-interscience, 1998
> > > [3] 詹向红, 李德新. 中医药防治阿尔茨海默病实验研究述要. 中华中医药学刊, 2004, 22(11): 2094-2096
> > 
> > 
> > @tangjyan
> > 把这些参考文献条目录入到那个群组中吧，方便调试时对照查看。
> 
> ![image](https://user-images.githubusercontent.com/21167731/182017325-89cc976a-2963-4456-b0ee-57a4c948bdd7.png) 我加了呀，单独建立了一个文件夹。

这里面的条目要是你例子中的条目方便对照。

**Comment by redleafnew** [comment]
@zepinglee @tangjyan  我们在这个基础上修改如何？https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doicsl

**Comment by zepinglee** [comment]
> > 另外只有专利标注一个[P]，其它文献类型不标注？
> 
> 我询问了我们学校负责Latex模版的团队，他们以文字描述为准，案例不准确，不加[P]。附Latex模版，可供参考。 https://github.com/Lianghao93/HUST-PhD-Thesis-Latex-v3.1

我也觉得不应该加“[P]”。

**Comment by zepinglee** [comment]
> @zepinglee @tangjyan 我们在这个基础上修改如何？https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doicsl

嗯，这个应该最接近了。

**Comment by tangjyan** [comment]
> @zepinglee @tangjyan 我们在这个基础上修改如何？https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl#002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doicsl

我也不是很懂，不过我感觉更像英文的参考文献格式，没有文献类型标识符，六个以上才缩写，人名写成 S. Feng 这种形式

**Comment by redleafnew** [comment]
正在修改中...

**Comment by zepinglee** [comment]
@tangjyan 你怎么将全部中文文献的语言改成“cn”了？跟据 <https://github.com/l0o0/translators_CN/issues/73>，中文只能用 `zh`, `zh-CN`, `zh-TW`，使用 `cn` 可能导致输出的参考文献语言错误。
<img width="333" alt="Screen Shot 2022-08-01 at 11 24 14" src="https://user-images.githubusercontent.com/12290822/182066028-3d67ea5e-bfc8-440b-a375-1c79413455d9.png">

应该是你调用的插件自动修改的吧？所以都用了哪些插件？

**Comment by zepinglee** [comment]
我稍微整理了一下，按照惯例“HUST”改为学校官方提供的示例文献，“HUST-测试”则是非官方的测试示例。
<img width="892" alt="Screen Shot 2022-08-01 at 13 12 42" src="https://user-images.githubusercontent.com/12290822/182076709-988c9c98-2fea-4ff5-9d41-931629de67ca.png">

**Comment by tangjyan** [comment]
> @tangjyan 你怎么将全部中文文献的语言改成“cn”了？跟据 [l0o0/translators_CN#73](https://github.com/l0o0/translators_CN/issues/73)，中文只能用 `zh`, `zh-CN`, `zh-TW`，使用 `cn` 可能导致输出的参考文献语言错误。 <img alt="Screen Shot 2022-08-01 at 11 24 14" width="333" src="https://user-images.githubusercontent.com/12290822/182066028-3d67ea5e-bfc8-440b-a375-1c79413455d9.png">
> 
> 应该是你调用的插件自动修改的吧？所以都用了哪些插件？
不好意思，就是茉莉花，我自定义成的cn，因为我觉得en和cn比较对称/

**Comment by zepinglee** [comment]
> 不好意思，就是茉莉花，我自定义成的cn，因为我觉得en和cn比较对称/

你是手动选择全部文献并点击修改语言的，还是插件在你不知情的状态下自动修改的？

**Comment by tangjyan** [comment]
> > 不好意思，就是茉莉花，我自定义成的cn，因为我觉得en和cn比较对称/
> 
> 你是手动选择全部文献并点击修改语言的，还是插件在你不知情的状态下自动修改的？

我没有手动调整过，我加入的文献是直接用浏览器插件采集的，这样是最接近实际使用的过程。

**Comment by zepinglee** [comment]
> 我没有手动调整过，我加入的文献是直接用浏览器插件采集的，这样是最接近实际使用的过程。

反馈给茉莉花那边了：<https://github.com/l0o0/jasminum/issues/112>。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl
匆忙之中完成了一点，你先试一下，详细列出还有哪些需要增加

**Comment by redleafnew** [comment]
1.测试文件中需要提供网页的条目
2.行间距这些是Word调整的。
3. 我想一下
4. 会议论文in或见前到底是逗号还是点，规定中是点，例子中是逗号

**Comment by redleafnew** [comment]
会议论文条目中没有 Proceedings of the IEEE 和开会地点等信息

**Comment by redleafnew** [comment]
规定中专利的名称和国名之间是点，例子是冒号也不统一。

**Comment by tangjyan** [comment]
> 会议论文条目中没有 Proceedings of the IEEE 和开会地点等信息

开会地点已经加上，IEEE这个应该是出版社，我也加进去了

**Comment by tangjyan** [comment]
> 1.测试文件中需要提供网页的条目 2.行间距这些是Word调整的。 3. 我想一下 4. 会议论文in或见前到底是逗号还是点，规定中是点，例子中是逗号

网页已提供
已描述为准，应该是点。感觉规定中，点是主分隔符，逗号是并列分隔符。后面专利的那里也应该是点而不是冒号我感觉。官方给的太乱了，我看了隔壁LaTeX，他们好像就没特别处理专利，国名都没加

**Comment by zepinglee** [comment]
> 3、100以后的文件标号有点挤 ![image](https://user-images.githubusercontent.com/21167731/182164179-16903b6b-05e9-4397-8ad8-9c70336dd22e.png)

编号的缩进是完全由 Word 控制的。

**Comment by zepinglee** [comment]
> 2.行间距这些是Word调整的。

建议在 csl 中配置 `line-spacing`。

**Comment by zepinglee** [comment]
再警告一次，不要修改其他 collection 的内容，尤其是不要把 `language` 字段改成 `cn`。
<img width="340" alt="Screen Shot 2022-08-02 at 12 10 04" src="https://user-images.githubusercontent.com/12290822/182290007-9d3dd699-161e-473c-b111-0b41677d674d.png">

**Comment by tangjyan** [comment]
> 再警告一次，不要修改其他 collection 的内容，尤其是不要把 `language` 字段改成 `cn`。 <img alt="Screen Shot 2022-08-02 at 12 10 04" width="340" src="https://user-images.githubusercontent.com/12290822/182290007-9d3dd699-161e-473c-b111-0b41677d674d.png">

从未手动操作HUST以外的文件，也未手动操作过所有文献的语言栏。目前已退出测试群组

**Comment by redleafnew** [comment]
> > 会议论文条目中没有 Proceedings of the IEEE 和开会地点等信息
> 
> 开会地点已经加上，IEEE这个应该是出版社，我也加进去了

Proceedings of the IEEE 应该不是出版社，是论文集的名称。

**Comment by tangjyan** [comment]
> 

我查了一下，这好像是一本期刊名，但是在会议论文中好像没找到合适的空填这个

**Comment by redleafnew** [comment]
放入proceedings title是合适的，这个字段的中文翻译不对。

**Comment by zepinglee** [comment]
> 从未手动操作HUST以外的文件，也未手动操作过所有文献的语言栏。目前已退出测试群组

你可以关掉插件的“自动设置语言”功能。

**Comment by zepinglee** [comment]
> > > 会议论文条目中没有 Proceedings of the IEEE 和开会地点等信息
> > 
> > 
> > 开会地点已经加上，IEEE这个应该是出版社，我也加进去了
> 
> Proceedings of the IEEE 应该不是出版社，是论文集的名称。

@redleafnew 这个示例的“Proceedings of the IEEE”有问题，按照格式要求应该填出版社（IEEE）才对，不应该带“Proceedings of”。

<img width="698" alt="Screen Shot 2022-08-02 at 14 52 14" src="https://user-images.githubusercontent.com/12290822/182310758-8cfb1216-51d6-49f4-9700-13fc281a7a89.png">

**Comment by redleafnew** [comment]
会议时间和出版年调用哪个变量？Date对应issue好像是出版时间？

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl再看看效果？修改了会议论文、网页的显示（删除了访问日期）。

**Comment by tangjyan** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl
> 
> 再看看效果？修改了会议论文、网页的显示（删除了访问日期）。

非常棒，我目前没有问题，非常感谢！

**Comment by redleafnew** [comment]
如果问题暂时关闭

**Comment by zepinglee** [comment]
> 会议时间和出版年调用哪个变量？Date对应issue好像是出版时间？

会议时间是 `event-date`，根据 <https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero>，需要填到 Extra 中。

**Comment by redleafnew** [comment]
好的，有需要再说了。

**Comment by zepinglee** [comment]
我正在 review 并进行修改。

**Comment by zepinglee** [comment]
b09ec34 中修改了样式，示例的变化：[b09ec34#diff-b335630](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/b09ec34cc8387c6a8d575ea07d9fdd543a29bfba#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)。

**Comment by SuperOwenX** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl
> 
> 再看看效果？修改了会议论文、网页的显示（删除了访问日期）。

你好，文件目前是删除了吗，页面找不到了

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology-school-of-artificial-intelligence-and-automation.csl

**Comment by SuperOwenX** [comment]
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology-school-of-artificial-intelligence-and-automation.csl

看到了，谢谢

**Comment by zepinglee** [comment]
> > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl
> > 再看看效果？修改了会议论文、网页的显示（删除了访问日期）。
> 
> 你好，文件目前是删除了吗，页面找不到了

见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/230#issuecomment-1836468781>，华中科大不同学院要求的格式不一样。所以我们修改了 418 的文件名，加了学院后缀。

建议确认一下需要的格式是不是跟 CSL 样式匹配。

**Comment by dujingwen** [comment]
> > > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418hust-thesis.csl
> > > 再看看效果？修改了会议论文、网页的显示（删除了访问日期）。
> > 
> > 
> > 你好，文件目前是删除了吗，页面找不到了
> 
> 见 [#230 (comment)](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/230#issuecomment-1836468781)，华中科大不同学院要求的格式不一样。所以我们修改了 418 的文件名，加了学院后缀。
> 
> 建议确认一下需要的格式是不是跟 CSL 样式匹配。

最新合并的hust研究生院样式的CSL样式，不能显示会议时间，求助！
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/13390837/5b9d5f6e-95de-4720-9cb9-802c8453e4d5)

即学院要求的标黄部分不能满足。
![image](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/13390837/791b9c67-95ac-48b2-919c-0c2b43f56270)

**Comment by zepinglee** [comment]
> 最新合并的hust研究生院样式的CSL样式，不能显示会议时间，求助！ 
> 
> 即学院要求的标黄部分不能满足。

参考示例文献的填写方式。

https://www.zotero.org/groups/4677213/chinese_csl_development/collections/G9SXAV8Z/items/GD8X7GAE/collection

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/2608f6e9d59eb9edc03be4f467885e5603ec11b3/tests/styles/418huazhong-university-of-science-and-technology/test.md?plain=1#L19

**Comment by dujingwen** [comment]
> > 最新合并的hust研究生院样式的CSL样式，不能显示会议时间，求助！
> > 即学院要求的标黄部分不能满足。
> 
> 参考示例文献的填写方式。
> 
> https://www.zotero.org/groups/4677213/chinese_csl_development/collections/G9SXAV8Z/items/GD8X7GAE/collection
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/2608f6e9d59eb9edc03be4f467885e5603ec11b3/tests/styles/418huazhong-university-of-science-and-technology/test.md?plain=1#L19


感谢你的及时帮助！可以解决问题！
顺便请教这个会议日期只能手动改吗？有没有什么自动获取的插件或工具啊？

**Comment by zepinglee** [comment]
> 感谢你的及时帮助！可以解决问题！ 顺便请教这个会议日期只能手动改吗？有没有什么自动获取的插件或工具啊？

大部分网站不会提供会议日期信息。

**Comment by northword** [comment]
我们的领域极少涉及会议论文，所以我对会议论文不太了解。

在我了解的范围内，没有可信来源提供会议时间、会议缩写等信息。

**Comment by jiaojiaodubai** [comment]
知网大部分都有会议时间和会议地点啊，印象中读秀导出的会议条目也不错。---原始邮件---发件人: "Zeping ***@***.***>发送时间: 2024年3月10日(周日) 晚上9:44收件人: ***@***.***>;抄送: ***@***.***>***@***.***>;主题: Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] 可否适配华中科技大学的学位论文参考文献样式 (Issue #62)

感谢你的及时帮助！可以解决问题！ 顺便请教这个会议日期只能手动改吗？有没有什么自动获取的插件或工具啊？

据我了解大部分网站不会提供会议日期信息。
顺便请教一下 @northword 和 @jiaojiaodubai 。

**Comment by BrotherCao** [comment]
你好，在使用https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology.csl引用样式时，出现了学位论文引用的一点问题，
![Snipaste_2024-03-22_10-31-35](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/71328187/5a112cca-b9fc-4ae9-8a5d-2358247e5542)，学校提供的格式是....[博士学位论文]，而这里只有...[博士]，我没看明白源码不知道怎么解决，希望得到您的帮助，谢谢。

**Comment by zepinglee** [comment]
> 你好，在使用 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology.csl 引用样式时，出现了学位论文引用的一点问题，学校提供的格式是....[博士学位论文]，而这里只有...[博士]，我没看明白源码不知道怎么解决，希望得到您的帮助，谢谢。

@BrotherCao [FAQ-为何学位论文类型显示“[博士]”而不是“[博士学位论文]”？](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/wiki/FAQ#%E4%B8%BA%E4%BD%95%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E7%B1%BB%E5%9E%8B%E6%98%BE%E7%A4%BA%E5%8D%9A%E5%A3%AB%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8D%9A%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87)

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=91f406b6-0026-496a-c143-08db62390742
也可以用这个动作

**Comment by BrotherCao** [comment]
我明白了，谢谢你们的帮助！

**Comment by Junix-honor** [comment]
> 如果问题暂时关闭

请问有没有这个issue的csl文件的下载链接，之前的好像都过期了，感谢🙏

**Comment by zepinglee** [comment]
> > 如果问题暂时关闭
> 
> 请问有没有这个issue的csl文件的下载链接，之前的好像都过期了，感谢🙏

推荐使用 <https://zotero-chinese.com/styles/> 这个网站。
