### ISSUE TITLE
经济研究(economic-research-journal.csl)有两处错误

### ISSUE THREAD

**Issue by artemith** [redleafnew/Chinese-STD-GB-T-7714-related-csl#63]
1. 经济研究要求中文文献在前，英文文献在后，而这里生成的的英文在前中文在后
见http://www.erj.cn/cn/Info.aspx?m=20220223162358523953

2. 英文期刊的姓名与要求的不同

要求的
![图片](https://user-images.githubusercontent.com/14881525/183051370-5fb49c5f-ef7c-4d61-b4ee-fd9154208454.png)

我生成的
Bartov E., Mohanram P., Seethamraju C., 2002, “Valuation of Internet Stocks—An IPO Perspective”, Journal of Accounting Research, 40(2), 321—346.

有两点不同：
(1) 从第二个作者开始，缩写的顺序不同了，应该是缩写在前，姓在后
(2) 第三个如果有三个作者，第三个作者前有个"and"

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
群组中所有中文文献的 `language` 字段又被人乱改了。我打算把群组改成“仅限 admin 修改”。

<img width="351" alt="Screen Shot 2022-08-06 at 12 52 41" src="https://user-images.githubusercontent.com/12290822/183234509-458f1540-82cb-4130-9681-ac2f2921cbd7.png">

@artemith 加入后在这里发一下 id，我把你提升为管理员后再把条目加进来。

**Comment by artemith** [comment]
id: hy_0943

**Comment by zepinglee** [comment]
> id: hy_0943

改为 admin 了，现在你可以新增和修改了。

**Comment by artemith** [comment]
> > id: hy_0943
> 
> 改为 admin 了。相关的测试条目放到 https://www.zotero.org/groups/4677213/chinese_csl_development/collections/L3AH5Q2F。

已加入

**Comment by redleafnew** [comment]
已更新

**Comment by artemith** [comment]
> 已更新

我之前没有说清楚，在"and"前还有个", "，所以应该是", and"
供参考：http://www.erj.cn/userfiles/%E3%80%8A%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E7%A8%BF%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83%E8%8C%83%E6%9C%AC%EF%BC%88%E4%BE%9B%E5%8F%82%E8%80%83%EF%BC%89%E5%AE%9A%E7%A8%BF_02.jpg
[项后军 和 周雄 - 2022 - 流动性囤积视角下的影子银行及其监管.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9277839/-.2022.-.pdf)

**Comment by redleafnew** [comment]
> > 已更新
> 
> 我之前没有说清楚，在"and"前还有个", "，所以应该是", and" 供参考：
> 
> 1. [经济研究样稿](http://www.erj.cn/userfiles/%E3%80%8A%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E7%A8%BF%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83%E8%8C%83%E6%9C%AC%EF%BC%88%E4%BE%9B%E5%8F%82%E8%80%83%EF%BC%89%E5%AE%9A%E7%A8%BF_02.jpg)
> 2. [项后军 和 周雄 - 2022 - 流动性囤积视角下的影子银行及其监管.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9277839/-.2022.-.pdf)

已更新

**Comment by artemith** [comment]
> > 已更新
> 
> 我之前没有说清楚，在"and"前还有个", "，所以应该是", and" 供参考：
> 
>     1. [经济研究样稿](http://www.erj.cn/userfiles/%E3%80%8A%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E7%A8%BF%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83%E8%8C%83%E6%9C%AC%EF%BC%88%E4%BE%9B%E5%8F%82%E8%80%83%EF%BC%89%E5%AE%9A%E7%A8%BF_02.jpg)
> 
>     2. [项后军 和 周雄 - 2022 - 流动性囤积视角下的影子银行及其监管.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9277839/-.2022.-.pdf)

又试了试新版。这个杂志要求的两个作者之间依然是用", and"来连接的，而不是"and"
![图片](https://user-images.githubusercontent.com/14881525/183326752-a1745f2b-d1a7-4601-80bb-ef199781cc59.png)

**Comment by redleafnew** [comment]
> > > 已更新
> > 
> > 
> > 我之前没有说清楚，在"and"前还有个", "，所以应该是", and" 供参考：
> > ```
> > 1. [经济研究样稿](http://www.erj.cn/userfiles/%E3%80%8A%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E7%A8%BF%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83%E8%8C%83%E6%9C%AC%EF%BC%88%E4%BE%9B%E5%8F%82%E8%80%83%EF%BC%89%E5%AE%9A%E7%A8%BF_02.jpg)
> > 
> > 2. [项后军 和 周雄 - 2022 - 流动性囤积视角下的影子银行及其监管.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9277839/-.2022.-.pdf)
> > ```
> 
> 又试了试新版，还有一点小瑕疵。这个杂志要求的两个作者之间依然是用", and"来连接的，而不是"and" ![图片](https://user-images.githubusercontent.com/14881525/183326752-a1745f2b-d1a7-4601-80bb-ef199781cc59.png)

将这个条目加到群组中方便测试。

**Comment by redleafnew** [comment]
又更新了，再测试一下。

**Comment by artemith** [comment]
> > > > 已更新
> > > 
> > > 
> > > 我之前没有说清楚，在"and"前还有个", "，所以应该是", and" 供参考：
> > > ```
> > > 1. [经济研究样稿](http://www.erj.cn/userfiles/%E3%80%8A%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E7%A8%BF%E4%BB%B6%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83%E8%8C%83%E6%9C%AC%EF%BC%88%E4%BE%9B%E5%8F%82%E8%80%83%EF%BC%89%E5%AE%9A%E7%A8%BF_02.jpg)
> > > 
> > > 2. [项后军 和 周雄 - 2022 - 流动性囤积视角下的影子银行及其监管.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9277839/-.2022.-.pdf)
> > > ```
> > 
> > 
> > 又试了试新版，还有一点小瑕疵。这个杂志要求的两个作者之间依然是用", and"来连接的，而不是"and" ![图片](https://user-images.githubusercontent.com/14881525/183326752-a1745f2b-d1a7-4601-80bb-ef199781cc59.png)
> 
> 将这个条目加到群组中方便测试。

已加入

**Comment by artemith** [comment]
> 又更新了，再测试一下。

测试了，没有问题

**Comment by artemith** [comment]
经济研究两个中文作者的citation格式产生问题

正常应该是（陈工孟和高宁，2000）
目前显示为（陈工孟, 和高宁，2000）

两个英文作者的citation格式正常

**Comment by redleafnew** [comment]
注意：使用author+year 样式的时，如果中文两个作者的和前面有逗号(, )，如显示为（金红兰, 和金龙勋, 2021），请确认条目的作者是是否经过合并操作，如果合并过请拆分(可以使用茉莉花插件https://github.com/l0o0/jasminum)。

**Comment by artemith** [comment]
> 注意：使用author+year 样式的时，如果中文两个作者的和前面有逗号(, )，如显示为（金红兰, 和金龙勋, 2021），请确认条目的作者是是否经过合并操作，如果合并过请拆分(可以使用茉莉花插件[https://github.com/l0o0/jasminum)。](https://github.com/l0o0/jasminum)%E3%80%82)

的确合并过。拆开之后正常了

**Comment by zepinglee** [comment]
> 注意：使用author+year 样式的时，如果中文两个作者的和前面有逗号(, )，如显示为（金红兰, 和金龙勋, 2021），请确认条目的作者是是否经过合并操作，如果合并过请拆分(可以使用茉莉花插件[https://github.com/l0o0/jasminum)。](https://github.com/l0o0/jasminum)%E3%80%82)

@redleafnew  这个“合并姓名”的功能是用于设么目的？

**Comment by redleafnew** [comment]
应该主要是在Zotero界面的作者栏可以显示完成的姓名，而不是只显示姓。
![image](https://user-images.githubusercontent.com/22135631/184471308-8590a830-ba2e-4708-bb0e-6060efbf9687.png)

**Comment by zepinglee** [comment]
感觉不对呀，“and” 前有没有逗号是 `delimiter-precedes-last` 控制的，跟姓名有没有合并应该无关才对。

**Comment by zepinglee** [comment]
研究了一下，应该是 `citeproc-js` 的 bug。MRE:
```xml
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text" delimiter-precedes-last="always" default-locale="zh-CN">
  <info>
    <id />
    <title />
    <updated>2022-08-07T03:28:57+00:00</updated>
  </info>
 <citation>
    <layout prefix="（" suffix="）" delimiter="；">
        <names variable="author">
          <name delimiter="" and="text"/>
        </names>
    </layout>
  </citation>
</style>
```

**Comment by zepinglee** [comment]
我修改了一下逻辑，现在应该不受姓名是否合并的影响了。
<img width="301" alt="Screen Shot 2022-08-13 at 18 42 33" src="https://user-images.githubusercontent.com/12290822/184480170-a0ec694a-37a1-491f-9650-83f74fa7d3d5.png">
<img width="752" alt="Screen Shot 2022-08-13 at 18 42 41" src="https://user-images.githubusercontent.com/12290822/184480172-90d8885e-24de-4f36-b0d8-52f6a3ecd133.png">

**Comment by redleafnew** [comment]
不错

**Comment by artemith** [comment]
> 我修改了一下逻辑，现在应该不受姓名是否合并的影响了。 <img alt="Screen Shot 2022-08-13 at 18 42 33" width="301" src="https://user-images.githubusercontent.com/12290822/184480170-a0ec694a-37a1-491f-9650-83f74fa7d3d5.png"> <img alt="Screen Shot 2022-08-13 at 18 42 41" width="752" src="https://user-images.githubusercontent.com/12290822/184480172-90d8885e-24de-4f36-b0d8-52f6a3ecd133.png">

感谢！
