### ISSUE TITLE
金融研究(204financial-research-journal.csl)有一些错误

### ISSUE THREAD

**Issue by artemith** [redleafnew/Chinese-STD-GB-T-7714-related-csl#64]
1. 应该是中文在前英文在后
2. 从第二个作者开始，缩写在前，姓在后
3. 英文页码前有"pp."

参考：
[《金融研究》投稿指南](http://www.jryj.org.cn/CN/column/column3.shtml)
[张 和 王 - 2022 - 方言多样化和企业创新——中国的事实及机制.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9278582/-.2022.-.pdf)

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by artemith** [comment]
> 加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

已加入

**Comment by redleafnew** [comment]
加的是哪几个条目，放在哪了？

**Comment by redleafnew** [comment]
页码范围好像是~，这个的ASCII是什么？类似长横是&#x2014;
@zepinglee

**Comment by redleafnew** [comment]
@artemith 这个期刊样式是数字格式的？而不是作者+年代的？

**Comment by artemith** [comment]
> 加的是哪几个条目，放在哪了？

之前理解错了，现在加入了`金融研究/金融融研究-测试`

**Comment by artemith** [comment]
> @artemith 这个期刊样式是数字格式的？而不是作者+年代的？

该期刊正文中citation是作者+年代格式
![图片](https://user-images.githubusercontent.com/14881525/183369674-02a9be4d-ef3d-4981-aefe-eeb7fa005a5f.png)

末尾的bibliography是按照先中文后英文，作者姓名顺序排列的
![图片](https://user-images.githubusercontent.com/14881525/183369928-106f4c09-5d9a-4f34-bfb0-581c43fb6f96.png)

**Comment by zepinglee** [comment]
> 页码范围好像是~，这个的ASCII是什么？类似—是`&#x2014;` @zepinglee

@redleafnew 直接写 `page-range-delimiter="~"` 应该就可以。

这个其实很不规范，英文的波浪号没有“pp. 12~34”这种用法，中文的波浪号应该用“～”（U+FF5E）。@artemith 如果方便可以给他们编辑提一下。

**Comment by redleafnew** [comment]
> > @artemith 这个期刊样式是数字格式的？而不是作者+年代的？
> 
> 该期刊正文中citation是作者+年代格式 ![图片](https://user-images.githubusercontent.com/14881525/183369674-02a9be4d-ef3d-4981-aefe-eeb7fa005a5f.png)
> 
> 末尾的bibliography是按照先中文后英文，作者姓名顺序排列的 ![图片](https://user-images.githubusercontent.com/14881525/183369928-106f4c09-5d9a-4f34-bfb0-581c43fb6f96.png)

但前面有序号是吧。

**Comment by artemith** [comment]
> > > @artemith 这个期刊样式是数字格式的？而不是作者+年代的？
> > 
> > 该期刊正文中citation是作者+年代格式 ![图片](https://user-images.githubusercontent.com/14881525/183369674-02a9be4d-ef3d-4981-aefe-eeb7fa005a5f.png)
> > 
> > 末尾的bibliography是按照先中文后英文，作者姓名顺序排列的 ![图片](https://user-images.githubusercontent.com/14881525/183369928-106f4c09-5d9a-4f34-bfb0-581c43fb6f96.png)
> 
> 但前面有序号是吧。

对的

**Comment by redleafnew** [comment]
```
<layout suffix="." locale="en">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="bib-full-en"/>
    </layout>
```

@zepinglee 这样写为什么编号和作者之间没有制表符了？

**Comment by redleafnew** [comment]
> second-field-align="flush"

![33ZP(L0_BU5T9%IEMWO_`OE](https://user-images.githubusercontent.com/22135631/183389815-47002e88-46af-4964-8d01-66f601c66362.png)
以前不了解各个部分的意思，只是修改......

**Comment by redleafnew** [comment]
@artemith 试一下效果行不行

**Comment by artemith** [comment]
> @artemith 试一下效果行不行

问题有一个：bibliography中从编号[10]开始，"[10]"和后面的内容中间的空格比较大，与[1]~[9]的空格不同

还有一个情况供参考：
有许多《金融研究》期刊上英文文献没有页码前没有"pp."，似乎该杂志对此处要求并不严格

![图片](https://user-images.githubusercontent.com/14881525/183462608-711fabde-e5f6-4195-9e92-4c8b2c169a0d.png)
![图片](https://user-images.githubusercontent.com/14881525/183462641-5b7b7bd1-9899-4f4a-935b-1fa64b73cc8f.png)

[刘 和 步 - 2022 - 民营企业债务违约是内因驱动吗.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9283313/-.2022.-.pdf)
[魏 和 韩 - 2022 - 绿色PPP项目组合的最优契约：经济与环境效应的福利视角.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9283316/-.2022.-.PPP.pdf)

**Comment by redleafnew** [comment]
> > @artemith 试一下效果行不行
> 
> 问题有一个：bibliography中从编号[10]开始，"[10]"和后面的内容中间的空格比较大，与[1]~[9]的空格不同
> 

> 
> ![图片](https://user-images.githubusercontent.com/14881525/183462608-711fabde-e5f6-4195-9e92-4c8b2c169a0d.png) ![图片](https://user-images.githubusercontent.com/14881525/183462641-5b7b7bd1-9899-4f4a-935b-1fa64b73cc8f.png)
> 
> [刘 和 步 - 2022 - 民营企业债务违约是内因驱动吗.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9283313/-.2022.-.pdf) [魏 和 韩 - 2022 - 绿色PPP项目组合的最优契约：经济与环境效应的福利视角.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9283316/-.2022.-.PPP.pdf)

对齐是由Word控制的

> 还有一个情况供参考： 许多《金融研究》上文章参考文献中英文文献页码前没有"pp."，似乎该杂志对此处要求并不严格

先加上pp., 如果不需要可以在Word替换。
