### ISSUE TITLE
您好，301 法学引注手册没法使用

### ISSUE THREAD

**Issue by tonshead** [redleafnew/Chinese-STD-GB-T-7714-related-csl#65]
添加时提示：“不是一个有效的csl1.0.2样式文件，你可能不能和Zetero一起正常工作。”
在使用时，添加脚注时出现的样式还是之前其他的样式。茉莉花等插件已经安装了，也已经调整语言标签为zh-CN。
比如：黄楚新 & 彭韵佳, 2017年中国媒体融合发展报告, 40 现代传播(中国传媒大学学报) 9 (2018).

**Comment by zepinglee** [comment]
> 添加时提示：“不是一个有效的csl1.0.2样式文件，你可能不能和Zetero一起正常工作。” 

直接忽略这个警告。

> 在使用时，添加脚注时出现的样式还是之前其他的样式。茉莉花等插件已经安装了，也已经调整语言标签为zh-CN。 比如：黄楚新 & 彭韵佳, 2017年中国媒体融合发展报告, 40 现代传播(中国传媒大学学报) 9 (2018).

第一次添加引用时需要选择样式“法学引注手册”，或者在 Word 的 Zotero 插件中修改样式。

**Comment by tonshead** [comment]
> 
感谢回复。当然已经选择样式了啊……在word里可以在多个样式之间切换，其他都没问题，就法学这个不行

**Comment by zepinglee** [comment]
> 比如：黄楚新 & 彭韵佳, 2017年中国媒体融合发展报告, 40 现代传播(中国传媒大学学报) 9 (2018).

这个是法学引注手册的英文期刊格式。可能是你的条目语言没有设置正确，建议给个截图。

**Comment by tonshead** [comment]
![图片](https://user-images.githubusercontent.com/12131552/183414622-5750b8ce-84d6-4d56-bfe0-78e2580fcb99.png)
您看下能看到图吗？

**Comment by zepinglee** [comment]
> ![图片](https://user-images.githubusercontent.com/12131552/183414622-5750b8ce-84d6-4d56-bfe0-78e2580fcb99.png) 您看下能看到图吗？

分辨率太低，几乎看不清楚。只需要把右边的字段部分截图就可以。

另外 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/GTTN32IE> 的文献都是经过测试没有问题的，可以作为参考。

**Comment by tonshead** [comment]
![图片](https://user-images.githubusercontent.com/12131552/183421939-718eb669-e2ef-4fce-bef0-9011f4404c08.png)这样呢

**Comment by redleafnew** [comment]
> > 
> 
> 感谢回复。当然已经选择样式了啊……在word里可以在多个样式之间切换，其他都没问题，就法学这个不行

如何不行？

**Comment by zepinglee** [comment]
> ![图片](https://user-images.githubusercontent.com/12131552/183421939-718eb669-e2ef-4fce-bef0-9011f4404c08.png)这样呢

看起来没啥问题。

那你加入 <https://www.zotero.org/groups/4677213/chinese_csl_development/>，然后发一下你的 Zotero id。在我讲你提升为管理员后再将文献放到这个 subcollection <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/KWYXSNSI>。

**Comment by zepinglee** [comment]
> > > 
> > 
> > 
> > 感谢回复。当然已经选择样式了啊……在word里可以在多个样式之间切换，其他都没问题，就法学这个不行
> 
> 如何不行？

@redleafnew 中文文献错误地调用了英文的格式。

**Comment by tonshead** [comment]
![图片](https://user-images.githubusercontent.com/12131552/183424671-3a47e3e2-c98c-4e5f-bd5f-05dbf7a0d084.png)
这是 301的样式
![图片](https://user-images.githubusercontent.com/12131552/183424731-00875e01-b716-4246-be48-abc9e14b126b.png)
这是302的样式
可见同一个文献，前者的样式没有如预期般呈现

> > > 
> > 
> > 
> > 感谢回复。当然已经选择样式了啊……在word里可以在多个样式之间切换，其他都没问题，就法学这个不行
> 
> 如何不行？

您看下

**Comment by tonshead** [comment]
> > ![图片](https://user-images.githubusercontent.com/12131552/183421939-718eb669-e2ef-4fce-bef0-9011f4404c08.png)这样呢
> 
> 看起来没啥问题。
> 
> 那你加入 https://www.zotero.org/groups/4677213/chinese_csl_development/，然后发一下你的 Zotero id。在我讲你提升为管理员后再将文献放到这个 subcollection https://www.zotero.org/groups/4677213/chinese_csl_development/collections/KWYXSNSI。

非常感谢，id是tonshead，同github的

**Comment by tonshead** [comment]
> > > ![图片](https://user-images.githubusercontent.com/12131552/183421939-718eb669-e2ef-4fce-bef0-9011f4404c08.png)这样呢
> > 
> > 
> > 看起来没啥问题。
> > 那你加入 [https://www.zotero.org/groups/4677213/chinese_csl_development/，然后发一下你的](https://www.zotero.org/groups/4677213/chinese_csl_development/%EF%BC%8C%E7%84%B6%E5%90%8E%E5%8F%91%E4%B8%80%E4%B8%8B%E4%BD%A0%E7%9A%84) Zotero id。在我讲你提升为管理员后再将文献放到这个 subcollection [https://www.zotero.org/groups/4677213/chinese_csl_development/collections/KWYXSNSI。](https://www.zotero.org/groups/4677213/chinese_csl_development/collections/KWYXSNSI%E3%80%82)
> 
> 非常感谢，id是tonshead，同github的
那个地方用不来，没找到添加的办法，您能看下这个知网链接么，就是刚刚作为例子的这个文献
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2018&filename=XDCB201804004&uniplatform=NZKPT&v=bFyShH8RdECrnHGCFFBm-wEWpB8p4z9OWmjDHIdHHinMhMGttSbVxmcz-r7tlzR4

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/183428493-44ff435f-749f-4e93-b973-2499789eaf19.png)

**Comment by zepinglee** [comment]
> 如何在Zotero软件中生成这个链接？ @zepinglee

Zotero 软件似乎不行，我是从网页端拷贝的。

**Comment by redleafnew** [comment]
`
〔1〕	黄楚新、彭韵佳：《2017年中国媒体融合发展报告》，载《现代传播(中国传媒大学学报)》2018年第4期。`

**Comment by redleafnew** [comment]
> > 如何在Zotero软件中生成这个链接？ @zepinglee
> 
> Zotero 软件似乎不行，我是从网页端拷贝的。

ok

**Comment by tonshead** [comment]
> ` 〔1〕 黄楚新、彭韵佳：《2017年中国媒体融合发展报告》，载《现代传播(中国传媒大学学报)》2018年第4期。`

您这里就没问题啊……所以是我哪一步设置有问题吗？

**Comment by redleafnew** [comment]
大概率是条目的问题。你用我这个条目复试一下

**Comment by zepinglee** [comment]
@tonshead 我无法复现你的问题。
<img width="328" alt="Screen Shot 2022-08-08 at 21 28 36" src="https://user-images.githubusercontent.com/12290822/183429351-dcf5ae1d-7942-4b74-8fdf-3bc45c0ddbf0.png">
<img width="862" alt="Screen Shot 2022-08-08 at 21 29 23" src="https://user-images.githubusercontent.com/12290822/183429474-8b83250b-2c1b-48ff-ab56-ccfca2380eac.png">

注意语言字段要填 `zh` 或 `zh-CN`，不是 `zh_CN`。

**Comment by redleafnew** [comment]
@tonshead 把你的条目也上传一下，我的是从你给的网址上直接导入的，没有做任何修改。

**Comment by tonshead** [comment]
> @tonshead 把你的条目也上传一下，我的是从你给的网址上直接导入的，没有做任何修改。

我该怎么上传条目啊。况且，我不止是这个文献，其他文献也不行的。

**Comment by redleafnew** [comment]
把条目从上面自己的文件夹拖到群组中文件夹就可以了，只要一个可以了，其他原因应该一样。

**Comment by tonshead** [comment]
![图片](https://user-images.githubusercontent.com/12131552/183432182-cf82e2eb-cc6f-4da2-a5c1-2bcf134bd5ca.png)
感谢二位的耐心啊，不知道我是哪里出了问题。现在在我这里，是所有的文献使用这个样式都有问题，其他样式（试过的几个）都没问题。已经改过zh或者zh-CN，都不行

**Comment by tonshead** [comment]
> 把条目从上面自己的文件夹拖到群组中文件夹就可以了，只要一个可以了，其他原因应该一样。

原来是在程序里就能操作，已经拖好了

**Comment by redleafnew** [comment]
> > 把条目从上面自己的文件夹拖到群组中文件夹就可以了，只要一个可以了，其他原因应该一样。
> 
> 原来是在程序里就能操作，已经拖好了

拖哪去了？
`法学引注手册-测试3`中没有看到，只有我导入的那个

**Comment by tonshead** [comment]
> 把条目从上面自己的文件夹拖到群组中文件夹就可以了，只要一个可以了，其他原因应该一样。

顺带说一下，我用另几个测试文件夹中的示例也是不行

**Comment by redleafnew** [comment]
条目好像也没有问题，有没有试过把这个csl删除重新添加，新建一个Word

**Comment by redleafnew** [comment]
甚至新建一个profile

**Comment by zepinglee** [comment]
<img width="332" alt="Screen Shot 2022-08-08 at 21 59 42" src="https://user-images.githubusercontent.com/12290822/183435848-89d2518f-d88e-44c7-9a7c-240c13b243cb.png">

@tonshead 似乎你的插件自动将语言改成 `zh_CN` 了。

另外这个 hy_0943 在乱改我们的内容，我取消他的修改权限了。
<img width="328" alt="Screen Shot 2022-08-08 at 22 01 17" src="https://user-images.githubusercontent.com/12290822/183436309-9e4ce59d-0c06-4b79-84a6-b93220b333e4.png">

**Comment by zepinglee** [comment]
@tonshead 你的插件自动将原有的文献 `language` 字段改成 `zh_CN` 了，我必须取消你的修改权限。
<img width="1522" alt="Screen Shot 2022-08-08 at 22 05 55" src="https://user-images.githubusercontent.com/12290822/183437004-a1f055d2-f37d-4112-aaa8-8b78e8703ca2.png">
 
应该就是插件的问题了，是不是用的茉莉花插件？

**Comment by tonshead** [comment]
我找到问题原因了，感谢两位。简而言之，需要在word里把需要改为英文，如图

再次感谢二位的耐心，谢谢

**Comment by redleafnew** [comment]
> @tonshead 你的插件自动将原有的文献 `language` 字段改成 `zh_CN` 了，我必须取消你的修改权限。 <img alt="Screen Shot 2022-08-08 at 22 05 55" width="1522" src="https://user-images.githubusercontent.com/12290822/183437004-a1f055d2-f37d-4112-aaa8-8b78e8703ca2.png">
> 
> 应该就是插件的问题了，是不是用的茉莉花插件？

我试着zh-CN和zh_CN效果一样。

**Comment by zepinglee** [comment]
> 我找到问题原因了，感谢两位。简而言之，需要在word里把语言改为英文，如图
> 
> 再次感谢二位的耐心，谢谢

<img width="600" alt="Screen Shot 2022-08-08 at 22 24 46" src="https://user-images.githubusercontent.com/12290822/183440994-b533422b-58f0-4b0f-b56c-b57630be223a.png">

这里设置的语言？据我对 CSL 了解不应该呀。

另外你都用了哪些插件？其中不负责任地乱改 `language` 字段的我要去给他们反馈。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/183442434-cf94777c-63ca-44f6-94d6-42984fa7cb20.png)
茉莉花中有这个功能，但默认好像没有打开。

**Comment by zepinglee** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/183442434-cf94777c-63ca-44f6-94d6-42984fa7cb20.png) 茉莉花中有这个功能，但默认好像没有打开。

这个功能非常坑。一是给出的两个选项不合 Zotero 的规范，二是开启后会在用户不知情的情况下修改所有文献的 `language` 字段，甚至会把合规的 `zh` 改成 `cn` 之类的。我已经给他们反馈过，见 <https://github.com/l0o0/jasminum/issues/112>。

**Comment by redleafnew** [comment]
如果解决请关闭。
@tonshead

**Comment by redleafnew** [comment]
@tonshead @zepinglee 这个关闭？
