### ISSUE TITLE
【中国行政管理期刊】引文样式求助

### ISSUE THREAD

**Issue by bi-wei** [redleafnew/Chinese-STD-GB-T-7714-related-csl#67]
尊敬的zotero互助群的老师 ：
  首先非常感谢您建立并维护这样有高度价值的社群，作为一名粉丝和学习者，由衷感谢这个社区和您们工作所体现的开源精神。
  我最近注意到【中国行政管理期刊】引文样式与目前repo中所有格式都不太相同，且具有特点，由于此期刊是公共管理领域的顶刊（类似于管理世界这种分量），其他使用者应该也有需求，因此寻求帮助。该期刊官网链接为http://www.cpaj.com.cn/ggzz_jj.shtml。 但没有格式指引，只能以已发表文章为准。
  详见两个截图附件。若大佬/老师们有时间开发一个专用csl那就更是感谢啦！具体格式如下：

- 总体上是顺序编码制。但重复的引用既不是ibid，也不是重复完整地列出，而是并列两个引文序号（详见第二张图的[4]和[9]引用并列在一起），这个问题之前群里咨询过，说无法通过csl实现，必须手动调整。
- 中文：基本是国标，但有两个不同 （1）作者全部列出 （2）不加页码
- 英文：
（1）期刊和书籍名称是斜体。
（2）作者姓名全部列出：姓前名后，名缩写且不加点号（.），首字母大写。若为中文两个名字要列出两个名的缩写，如王天广为Wang T G这种只能修改条目作者实现。
（3）题名（paper的标题）是实词首字母大写，其他小写，包括of and这种虚词。

请教如何可以满足上述格式。
再次感谢您无私地分享有关zotero的学习资料，祝工作生活一切顺利！

-附件为
![中国行政管理示例2](https://user-images.githubusercontent.com/65751479/186077075-2e93bd58-b3ec-4a65-a90d-b2e83f490b46.PNG)
![中国行政管理示例1](https://user-images.githubusercontent.com/65751479/186077082-5cd54912-a7b2-4f0c-bf36-3cf3b68cb419.PNG)

**Comment by redleafnew** [comment]
1. 加入Zotero群组，将参考文献列表中的条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development
2. 看看与仓库中的哪个最接近，我们在那个基础上修改。
3. [4][9]这样的应该是没有办法。

**Comment by bi-wei** [comment]
谢谢您回复！
1、已加入群组，但是只能view而不能添加新的题录 显示为Library Access: You can only view
2、对比多个csl，目前看来最相似的是，但仍有不少差异，尤其是英文斜体引用，供您参考 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)

谢谢！

**Comment by redleafnew** [comment]
英文斜体不难实现。
@zepinglee 设置一下群组权限吧。

**Comment by zepinglee** [comment]
> 谢谢您回复！ 1、已加入群组，但是只能view而不能添加新的题录 显示为Library Access: You can only view 2、对比多个csl，目前看来最相似的是，但仍有不少差异，尤其是英文斜体引用，供您参考 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)
> 
> 谢谢！

Zotero ID 是什么？

**Comment by bi-wei** [comment]
您好，ID是 540794105@qq.com 
谢谢！

**Comment by zepinglee** [comment]
简单看了一下，纠正一下期刊是需要页码的。不过这两篇文章的格式都不统一，感觉期刊对格式的要求比较随意。

![186077075-2e93bd58-b3ec-4a65-a90d-b2e83f490b46](https://user-images.githubusercontent.com/12290822/186101802-fc0e27d4-eff9-4f20-8a4a-bff007042bd7.png)

![186077082-5cd54912-a7b2-4f0c-bf36-3cf3b68cb419](https://user-images.githubusercontent.com/12290822/186101777-e87be4bf-7790-4174-90e3-ad46da287528.png)

至于“[4]和[9]并列在一起”，这是全球独有、仅此一篇。可能作者不太了解学术写作，可以忽略这个需求。

**Comment by zepinglee** [comment]
> 您好，ID是 [540794105@qq.com](mailto:540794105@qq.com) 谢谢！

<img width="939" alt="Screen Shot 2022-08-23 at 15 51 23" src="https://user-images.githubusercontent.com/12290822/186102665-1a9d97ce-7534-4a96-ad5a-8ca637ea56b8.png">

我这里看不到邮箱，只能看到显示的名称。

**Comment by redleafnew** [comment]
英文的有页码，中文的没有

**Comment by zepinglee** [comment]
> 英文的有页码，中文的没有

也不完全是这样，比如这里就有页码。
<img width="939" alt="Screen Shot 2022-08-23 at 15 51 23" src="https://user-images.githubusercontent.com/12290822/186113269-a2d05ffe-20eb-465e-ba5a-0854fd987598.png">

@bi-wei 建议给期刊的编辑发邮件问一下具体格式，免得我们做无用功。

**Comment by bi-wei** [comment]
您好，群组截图中我的id是biwei。
关于具体格式：这个期刊编辑部估计回信可能比较慢，且已刊文章呈现出的引用格式在细微之处的不同，说明格式本身就可能没有一致标准。我目前想到最好的办法就是先对应大部分文章做一个csl，后续我投稿后若收到对参考文献格式的要求再相应微调。
阅览了今年的这个期刊（稍后会加入把题录拖入群组），发现：
- 关于页码：中文期刊都没有页码；英文期刊的确有的标注页码，有的没有标注，但以表明页码的为多
- 关于英文斜体：仍然是采用斜体的为多。
- 关于姓名顺序。仍然是姓前名后，名缩写，如Tsamados A，Aggarwal N，Cowls J，et al. 这也说明超过三人作者的英文文献，可以用et al.
- 关于“至于“[4]和[9]并列在一起”，这是全球独有、仅此一篇”。实际上还，有多篇是这样的（例如，，稍后我会拖入几个题录放入群组），说明这种方式是编辑部的要求。

反馈如上，谢谢！

**Comment by zepinglee** [comment]
<img width="904" alt="Screen Shot 2022-08-23 at 19 54 32" src="https://user-images.githubusercontent.com/12290822/186151546-08c5c4bc-4f1e-426d-89da-9a7e6dafa378.png">

已经修改权限。

> * 关于“至于“[4]和[9]并列在一起”，这是全球独有、仅此一篇”。实际上，还有多篇是这样的（例如：李震国,端利涛,吕本富.智能化系统建设中的实用伦理规则设计原则[J].中国行政管理,2022(06):41-48. ，稍后我会拖入几个题录放入群组），说明这种方式是编辑部的要求。

那就是全球独此一家期刊。

**Comment by bi-wei** [comment]
您好，已经在群组新建《中国行政管理》文件夹并拖入了5篇典型的题录。
供参考，谢谢！

**Comment by redleafnew** [comment]
英文的也拖几篇吧，最好是你提供的截图中的，方便对照。

**Comment by redleafnew** [comment]
什么情况下是期刊类型带OL，

**Comment by zepinglee** [comment]
“[4]和[9]并列在一起”的不合理之处在于，这样的格式对读者很不友好。比如在正文读到引用“[9]”，然后在文后参考文献表中找 [9]，发现缺失后，就只能在参考文献表中依次找有没有额外的编号[9]，就完全失去了索引的功能。其实这里引用“[9]”直接用编号[4]即可。比如国标的例子：

<img width="719" alt="Screen Shot 2022-08-23 at 20 08 50" src="https://user-images.githubusercontent.com/12290822/186154330-931d73cd-d772-4cdd-b28b-cfe7fbe92118.png">

**Comment by zepinglee** [comment]
> 什么情况下是期刊类型带OL，

按照国标的习惯是，有 URL 或 DOI 的加“/OL”的载体类型标识。

**Comment by redleafnew** [comment]
> “[4]和[9]并列在一起”的不合理之处在于，这样的格式对读者很不友好。比如在正文读到引用“[9]”，然后在文后参考文献表中找 [9]，发现缺失后，就只能在参考文献表中依次找有没有额外的编号[9]，就完全失去了索引的功能。其实这里引用“[9]”直接用编号[4]即可。比如国标的例子：
> 
> <img alt="Screen Shot 2022-08-23 at 20 08 50" width="719" src="https://user-images.githubusercontent.com/12290822/186154330-931d73cd-d772-4cdd-b28b-cfe7fbe92118.png">

确实，不知道期刊是怎么想的

**Comment by redleafnew** [comment]
windows下有办法通过命令提示行查看csl的预览效果吗？

**Comment by bi-wei** [comment]
您好
-英文的已拖动，来自《数字政府发展的理论框架与评估体系研究》这篇里的引用序号2和21。此外，发现《数字政府发展的理论框架与评估体系研究》这篇的参考文献序号22和26是同一篇文章，而并未并列序号，这也说明该刊的引用格式比较随缘。
- 有EB/OL引用的，也已拖入题录，来自《技术执行的拼凑应对偏差：数字治理形式主义的发生逻辑分析》，不过不是期刊带有OL，而是网页
- 关于并列序号的问题：同意您的看法，但编辑部貌似不这样想，所以也没办法

**Comment by bi-wei** [comment]
> windows下有办法通过命令提示行查看csl的预览效果吗？

看到B站有通过https://editor.citationstyles.org 进行在线编辑csl和预览的。
供参考

**Comment by redleafnew** [comment]
> 您好 -英文的已拖动，来自《数字政府发展的理论框架与评估体系研究》这篇里的引用序号2和21。此外，发现《数字政府发展的理论框架与评估体系研究》这篇的参考文献序号22和26是同一篇文章，而并未并列序号，这也说明该刊的引用格式比较随缘。
> 
> * 有EB/OL引用的，也已拖入题录，来自《技术执行的拼凑应对偏差：数字治理形式主义的发生逻辑分析》，不过不是期刊带有OL，而是网页
> * 关于并列序号的问题：同意您的看法，但编辑部貌似不这样想，所以也没办法

其实通过Zotero生成参考文献目录后，后期再修改编号也是一件很麻烦的事情，除非不引用重复文献。

**Comment by redleafnew** [comment]
> > windows下有办法通过命令提示行查看csl的预览效果吗？
> 
> 看到B站有通过https://editor.citationstyles.org 进行在线编辑csl和预览的。 供参考

@bi-wei 把样例中希望生成的最终格式复制到同一个文件中，散落到不同的文件不方便对照。

**Comment by bi-wei** [comment]
所期望的格式请见doc附件，谢谢！
[中国行政管理希望的格式.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9402603/default.docx)

**Comment by redleafnew** [comment]
> > windows下有办法通过命令提示行查看csl的预览效果吗？
> 
> 我以前用的是 https://github.com/zepinglee/csl-development，可以参考 [molc](https://github.com/zepinglee/csl-development/tree/molc) 分支：需要先准备好 [`test-data.json`](https://github.com/zepinglee/csl-development/blob/molc/test-data.json) 和 [`test-cites.json`](https://github.com/zepinglee/csl-development/blob/molc/test-cites.json)，使用 `node generate.js` 生成 [`output-note.md`](https://github.com/zepinglee/csl-development/blob/molc/output-note.md)。需要安装 Node.js 环境。
> 
> https://github.com/zotero-cn/styles 也是类似的方法。

有时间学习配置一下

**Comment by redleafnew** [comment]
> > windows下有办法通过命令提示行查看csl的预览效果吗？
> 
> 我以前用的是 https://github.com/zepinglee/csl-development，可以参考 [molc](https://github.com/zepinglee/csl-development/tree/molc) 分支：需要先准备好 [`test-data.json`](https://github.com/zepinglee/csl-development/blob/molc/test-data.json) 和 [`test-cites.json`](https://github.com/zepinglee/csl-development/blob/molc/test-cites.json)，使用 `node generate.js` 生成 [`output-note.md`](https://github.com/zepinglee/csl-development/blob/molc/output-note.md)。需要安装 Node.js 环境。
> 
> https://github.com/zotero-cn/styles 也是类似的方法。

新做的style要改名为style.csl吗？

**Comment by zepinglee** [comment]
> > > windows下有办法通过命令提示行查看csl的预览效果吗？
> > 
> > 
> > 我以前用的是 [https://github.com/zepinglee/csl-development，可以参考](https://github.com/zepinglee/csl-development%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83) [molc](https://github.com/zepinglee/csl-development/tree/molc) 分支：需要先准备好 [`test-data.json`](https://github.com/zepinglee/csl-development/blob/molc/test-data.json) 和 [`test-cites.json`](https://github.com/zepinglee/csl-development/blob/molc/test-cites.json)，使用 `node generate.js` 生成 [`output-note.md`](https://github.com/zepinglee/csl-development/blob/molc/output-note.md)。需要安装 Node.js 环境。
> > https://github.com/zotero-cn/styles 也是类似的方法。
> 
> 新做的style要改名为style.csl吗？

是的，所以我以前都是改好了再拷贝到 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl。

建议可以学习配置 https://github.com/zotero-cn/styles 的，这个目录和文件结构更合理。我现在也在完善测试效果。

**Comment by zepinglee** [comment]
> 这个是不是一下生成所有src中csl的预览效果，如何生成某个csl的预览效果？

是的。这个很快的，可以不必考虑单个 csl 的效果。

**Comment by redleafnew** [comment]
生成的预览文件是哪个？

**Comment by zepinglee** [comment]
> 生成的预览文件是哪个？

每个样式目录下的 README.md 文件，比如 <https://github.com/zotero-cn/styles/tree/main/src/manual-of-legal-citation-multi-lingual>。不过 HTML 的现实效果更好 <https://zotero-cn.github.io/styles/manual-of-legal-citation-multi-lingual/>。

**Comment by redleafnew** [comment]
> 谢谢您回复！ 1、已加入群组，但是只能view而不能添加新的题录 显示为Library Access: You can only view 2、对比多个csl，目前看来最相似的是，但仍有不少差异，尤其是英文斜体引用，供您参考 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)
> 
> 谢谢！

辛苦再看看期刊期望得到的样式与002差别主要在什么地方？我一条条来修改试试。
@bi-wei

**Comment by redleafnew** [comment]
> # 启动开发服务器
> yarn dev:vite 

这是干什么用的？


> 如果贡献者使用 Windows ，请尽量不对 src/**/*.md 作提交，因为 CRLF -> LF 会带来大量无用的 Git 记录。

如果我用Win，怎么做？只提交csl吗？
@zepinglee

**Comment by northword** [comment]
> > 
> > yarn dev:vite
> 
> 这是干什么用的？
> 
> > 如果贡献者使用 Windows ，请尽量不对 src/**/*.md 作提交，因为 CRLF -> LF 会带来大量无用的 Git 记录。
> 
> 如果我用Win，怎么做？只提交csl吗？ @zepinglee

在 github/zotero-cn/styles 仓库中，使用 `lib/generate.js` 来调用 `citeproc-js` 生成对应的引注与参考文献表的预览，将其写入同目录下的 `README.md`，这个脚本通过 `yarn generate` 来运行。

VuePress 是一个静态页面生成器，可以将 Markdown 文件渲染为 HTML 文件，他在本地调试时候可以创建一个开发服务器，实时更新 Markdown 文件里的变动，`yarn dev:vite` 就是启动这个开发服务器的命令，启动后，命令行会返回一个本地地址（返回多个时候通常选 localhost 那个），打开这个地址就是渲染出来的网页。

如果使用 win ，只提交 csl 文件就好，其余的 markdown 文件全部选择放弃更改就好，如果全部提交了也没影响。

在 zotero-cn/styles 仓库中，之需要将 csl 文件放在 src/ 下的子目录里就好，不用重命名为 style.csl ，脚本会遍历 src/ 下的所有 csl 文件。在 csl-development 仓库中，因为 generate.js 直接写入了读取 ./style.csl ，所以需要重命名。

**Comment by bi-wei** [comment]
> > 谢谢您回复！ 1、已加入群组，但是只能view而不能添加新的题录 显示为Library Access: You can only view 2、对比多个csl，目前看来最相似的是，但仍有不少差异，尤其是英文斜体引用，供您参考 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)
> > 谢谢！
> 
> 辛苦再看看期刊期望得到的样式与002差别主要在什么地方？我一条条来修改试试。 @bi-wei

您好，与002样式的差别在于
- 中文期刊：无需显示页码。作者超过三人的“等”可以保留
- 中文图书：外文译本的原作者前用方括号标注国家，例如［美］
- 英文：题名（title）的实词首字母都大写，002是只有首字母大写；不用[J]等标识符，而是斜体标明期刊名或图书题名（title）。英文的格式与[106journal-of-inorganic-materials.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/106journal-of-inorganic-materials.csl) 比较像，但作者姓名是只有首字母大写。

谢谢！

**Comment by redleafnew** [comment]
> > > 谢谢您回复！ 1、已加入群组，但是只能view而不能添加新的题录 显示为Library Access: You can only view 2、对比多个csl，目前看来最相似的是，但仍有不少差异，尤其是英文斜体引用，供您参考 [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)
> > > 谢谢！
> > 
> > 
> > 辛苦再看看期刊期望得到的样式与002差别主要在什么地方？我一条条来修改试试。 @bi-wei
> 
> 您好，与002样式的差别在于
> 
> * 中文期刊：无需显示页码。作者超过三人的“等”可以保留
> * 中文图书：外文译本的原作者前用方括号标注国家，例如［美］
> * 英文：
>   （1）题名（title）的实词首字母都大写，002是只有首字母大写；
>   （2）不用[J]等标识符，而是斜体标明期刊名或图书题名（title）。
>   （3）英文的格式与[106journal-of-inorganic-materials.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/106journal-of-inorganic-materials.csl) 比较像，但作者姓名是只有首字母大写，若为中国作者则两个名都要要列出两个名的缩写，如王天广为Wang T G，且实词首字母都大写
> 
> 谢谢！

中文作者超过3个要加“等”，英文的列出所有作者，这个无法实现吧？
@zepinglee 

你前面说中文也列出所有作者的。
@bi-wei

**Comment by bi-wei** [comment]
> 

您好，英文有引用明确用了et al. 而中文我看了很多篇都没有超过三个作者因此全部显示。且考虑到csl显示作者必须对中英文同时操作，所以都

**Comment by redleafnew** [comment]
```
 <choose>
            <if language="en-US">
              <text variable="page"/>
            </if>
          </choose>
```
@zepinglee 好像不能做这样的判断，只能用不同locale实现是吧。

**Comment by zepinglee** [comment]
> ```
>  <choose>
>             <if language="en-US">
>               <text variable="page"/>
>             </if>
>           </choose>
> ```
> 
> @zepinglee 好像不能做这样的判断，只能用不同locale实现是吧。

不能。只能用不同的 `layout locales="en"`  实现。

**Comment by redleafnew** [comment]
写个不规范的吧，如果语言字段不为空(英文的），显示页码，默认的为中文，语言字段为空。
否则里面要分开的东西太多。
```
        <choose>
          <if variable="language" >
            <text variable="page"/>
          </if>
        </choose>
```

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/109chinese-public-administration.csl 
@bi-wei 试一下，保留了文献类型标识，你给的两个例子中有个有，有个没有，像
@zepinglee 说的，感觉这具期刊不严谨。

**Comment by bi-wei** [comment]
@redleafnew 
您好，首先非常感谢。由于我没有本地环境，所以用https://editor.citationstyles.org/ 将源码生成了csl格式并导入zotero试用了一下。
总体非常好用，不过也发现几点不知可否烦请调整：
（1）英文期刊的引用，参考了今年发表的多篇文章，还是想去掉文献类型标识，并将期刊名称斜体。
（2）英文期刊作者超过三人，可以自动为“et al.”吗，目前显示的是“等”、
（3）中文期刊的引用里，只用“年份（期号）”，目前是“年份，卷次（期号）”，不用标出卷次，且此处的括号是中文全角括号，目前是英文半角的括号。

谢谢，麻烦老师了！感谢！

**Comment by redleafnew** [comment]
https://www.jianguoyun.com/p/DSoZYTQQtOD-BRjZ19IEIAA 
（1）已删除
（2）需要将英文条目的语言字段修改为en-US
（3）中文的全角括号不大好看
![image](https://user-images.githubusercontent.com/22135631/186423581-e7a7018b-d014-40fb-bcc5-232d909757c8.png)

**Comment by bi-wei** [comment]
> https://www.jianguoyun.com/p/DSoZYTQQtOD-BRjZ19IEIAA 仓库中也已经更新。 （1）已删除 （2）需要将英文条目的语言字段修改为en-US （3）中文的全角括号不大好看 ![image](https://user-images.githubusercontent.com/22135631/186423581-e7a7018b-d014-40fb-bcc5-232d909757c8.png)

您好，测试后发现：
- 文献标志类型：英文的删去了，然而中文的标志，例如[J]也没了。是否可以使中文的保留而英文的删去吗？
- 中文期刊名与“年份（期）”之间的半角逗号缺失

十分感谢！

**Comment by bi-wei** [comment]
关于英文期刊title的实词大写，目前能想到的办法是在csl的capitalize-all基础上，手动在word里查找IN AND FROM FOR 等词语并替换为小写

**Comment by redleafnew** [comment]
> > https://www.jianguoyun.com/p/DSoZYTQQtOD-BRjZ19IEIAA 仓库中也已经更新。 （1）已删除 （2）需要将英文条目的语言字段修改为en-US （3）中文的全角括号不大好看 ![image](https://user-images.githubusercontent.com/22135631/186423581-e7a7018b-d014-40fb-bcc5-232d909757c8.png)
> 
> 您好，测试后发现：
> 
> * 文献标志类型：英文的删去了，然而中文的标志，例如[J]也没了。是否可以使中文的保留而英文的删去吗？
> * 中文期刊名与“年份（期）”之间的半角逗号缺失
> 
> 十分感谢！

再试一下坚果云中的csl

**Comment by redleafnew** [comment]
> 关于英文期刊title的仅实词大写，目前能想到的办法是在csl的capitalize-all基础上，手动在word里查找IN AND FROM FOR 等虚词并替换为小写

这个没有好办法。
或是在Zotero的title改为正确大小写的，csl中不设置大小写，只是读取Zotero中的字段。但再切换其它csl时比较麻烦。

**Comment by bi-wei** [comment]
> > > https://www.jianguoyun.com/p/DSoZYTQQtOD-BRjZ19IEIAA 仓库中也已经更新。 （1）已删除 （2）需要将英文条目的语言字段修改为en-US （3）中文的全角括号不大好看 ![image](https://user-images.githubusercontent.com/22135631/186423581-e7a7018b-d014-40fb-bcc5-232d909757c8.png)
> > 
> > 
> > 您好，测试后发现：
> > 
> > * 文献标志类型：英文的删去了，然而中文的标志，例如[J]也没了。是否可以使中文的保留而英文的删去吗？
> > * 中文期刊名与“年份（期）”之间的半角逗号缺失
> > 
> > 十分感谢！
> 
> 再试一下坚果云中的csl

老师您好，最新版堪称完美！
唯一似乎剩下的是中文引用年份逗号之后多了一个空格，使得与“期”多隔了一个空格。见截图。
我也可以用之前的在线csl编辑器自行修改。

谢谢！
![最新样式多了空格](https://user-images.githubusercontent.com/65751479/186437468-47487145-87fc-4229-86d2-289440395fdd.png)
！

**Comment by redleafnew** [comment]
再试一下！

**Comment by redleafnew** [comment]
现在只是测试了期刊，其它的文献类型没有测试。

**Comment by bi-wei** [comment]
> 现在只是测试了期刊，其它的文献类型没有测试。
谢谢，目前来看已没有问题，其他文献类型等后续仔细使用再反馈。
感谢各位老师的帮助  @zepinglee @redleafnew @northword @RisenL ，我本人也在这个过程中学到了很多。

我是否就可以close issue了？

祝好！

**Comment by redleafnew** [comment]
如果没有其它问题了可以关闭

**Comment by bi-wei** [comment]
祝一切顺利！

**Comment by zepinglee** [comment]
不要修改其他 collection 的字段！
<img width="314" alt="Screen Shot 2022-11-02 at 14 13 33" src="https://user-images.githubusercontent.com/12290822/199412058-2b10620a-2989-40ec-91d0-d78c731112fb.png">

Language 字段的是 zh-CN 不是 zh_CN！
