### ISSUE TITLE
正文中参考文献引用角标格式调整

### ISSUE THREAD

**Issue by yangtzech** [redleafnew/Chinese-STD-GB-T-7714-related-csl#68]
目前使用GB/T7714-2015格式，正文中引用参考文献会以角标的形式呈现，请问下这个能不能被改成以正文显示？

![image](https://user-images.githubusercontent.com/41911522/186368970-e136826f-241e-4bbb-9cbe-b101cefde5e6.png)

**Comment by redleafnew** [comment]
具体用得哪个csl

**Comment by yangtzech** [comment]
之前下载的GB/T7714-2015(顺序编码制，双语，姓名小写，无DOI)，应该和这个比较接近。
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/32557eb8e25c898d17735250e52681f3f58cd35d/003gb-t-7714-2015-numeric-bilingual-no-url-doi.csl#L427 中的`vertical-align="sup" `删除试试。

**Comment by yangtzech** [comment]
可以了，多谢！
