### ISSUE TITLE
中国行政管理csl-英文图书样式

### ISSUE THREAD

**Issue by bi-wei** [redleafnew/Chinese-STD-GB-T-7714-related-csl#69]
老师您好
- 继昨天的issue #67 之后，我在最后版上修改了中文图书的macro，目前中文期刊、英文期刊、中文图书应该都是正确的。
- 但英文图书无法正确显示出书名斜体并去掉［M］，并且csl里似乎都是使用的chapter-in-book这个macro，不知可否分开为book和chapter两种。另外能不能只显示place而不是publisher-place呢，我在编辑器里找不到只显示place的选项了。
- 辛苦您看看这个编辑后的csl～谢谢！

可供下载的链接为https://www.jianguoyun.com/p/DXRH784QnPHiCBiV69MEIAA

祝好！

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

贴出现在的格式和希望得到的格式，两者的区别。

**Comment by bi-wei** [comment]
收到，已将3本英文书籍题录拖入群组。
- 同样都是英文图书，不知为何第二张截图高亮部分的第[2]条引用格式显示就是正确的，这两篇都拖入了群组供测试使用。
谢谢！

![未正确显示的英文图书](https://user-images.githubusercontent.com/65751479/186587742-d6337fd3-4902-4819-a3cd-95e79a1a2034.PNG)

![希望的英文图书格式](https://user-images.githubusercontent.com/65751479/186590695-2b3c5285-c112-4e8b-b501-26196fd8e32a.PNG)

**Comment by zepinglee** [comment]
没看懂改修改的内容。

`chapter-in-book-layout` 对应 [GB/T 7714](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf) 的“专著中的析出文献”。而 `book` 类型属于“专著” `monograph-layout`。

**Comment by zepinglee** [comment]
> 另外能不能只显示place而不是publisher-place呢，我在编辑器里找不到只显示place的选项了。

去掉后面的 `publisher`。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/d4fb3bec8bcb06b3f04c60623b31b6df535d860d/109chinese-public-administration.csl#L217-L218

**Comment by bi-wei** [comment]
> 没看懂改修改的内容。
> 
> `chapter-in-book-layout` 对应 [GB/T 7714](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf) 的“专著中的析出文献”。而 `book` 类型属于“专著” `monograph-layout`。

- 您好，由于我修改水平有限，如果有不妥之处您也可以在当前repo里的版本上修改。
- 简而言之，想让目前的csl能够正确显示英文的“专著”，其他的可以暂不调整。
- 如下截图中，红色是错误的英文专著格式，黄色高亮是正确的。但我也不知道为啥都是英文专著题录，却显示了不一致的格式。这两个题录都已经拖入群组。
![微信截图_20220825154236](https://user-images.githubusercontent.com/65751479/186605798-7086021a-ba14-4cf1-bee6-15bb1fa76549.png)

- 辛苦您帮忙看看，谢谢

**Comment by zepinglee** [comment]
d2cf17d 中将英文书名改为了斜体。
<img width="578" alt="Screen Shot 2022-08-25 at 19 27 09" src="https://user-images.githubusercontent.com/12290822/186652926-b622d966-7615-4db8-bf5a-09373c53b909.png">

另外我将 Zotero 群组中“中国行政管理”移到“期刊”目录下了。
