### ISSUE TITLE
感谢作者，再求个《经济研究》的格式

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#7]
周黎安， 2004： 《晋升博弈中政府官员的激励与合作———兼论我国地方保护主义和重复建设问题长期存在的原因》，《经济研 究》第 6 期。
Bottazzi，L．，M． D． Ｒin，and T． Hellmann，2016，“The Importance of Trust for Investment： Evidence from Venture Capital”，Ｒeview of Financial Studies，29（ 9） ，2283—2318．

与《管理世界》相比，需要做如下改动：
中文：作者后标点为逗号，然后是年份：，期刊位置删除”XX年“
英文：页码之间的符号为”—“,而不是”~“
文献排序不用编号

http://www.erj.cn/cn/Info.aspx?m=20100913105301153616&page=1

谢谢老师~

**Comment by redleafnew** [comment]
1.与《管理世界》最接近？
2.页码之间的符号为”—“,而不是”-“？

**Comment by fredericky123** [comment]
> 1.与《管理世界》最接近？
> 2.页码之间的符号为”—“,而不是”-“？

是的，以上写出了相较于管理世界的变动，这些期刊一人一个格式，😌

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/10economic-research-journal.csl

**Comment by fredericky123** [comment]
感谢韩老师，目前看来一切完美！

**Comment by redleafnew** [comment]
再试一下？

**Comment by fredericky123** [comment]
> 再试一下？

完美，感谢韩老师！
