### ISSUE TITLE
关于011gb-t-7714-2015-author-date中两位作者的显示问题

### ISSUE THREAD

**Issue by lijush** [redleafnew/Chinese-STD-GB-T-7714-related-csl#70]
您好！我一直在您的GitHub上学习Zotero的使用，发现 011gb-t-7714-2015-author-date这个csl特别合适，但是它有一个地方没法满足要求，就是两个作者的时候也是“XX等”或者“XX et al.”，不知这种情况下如何改成“XX和XX”“XX & XX”呢？【例如，图片中的例子如何改成（谭羚雁和娄成武, 2012）（Ekstrom & Moser, 2014）】其他的csl文件我也都试了，往往满足正文的要求，但是后面参考文献的格式又不对。我对编程实在不擅长，故冒昧打扰您，不知您能否指导一下？
![1](https://user-images.githubusercontent.com/26033215/189008481-edcb3ca4-5cbb-48e2-91bd-f7559b9ae437.jpg)
![2](https://user-images.githubusercontent.com/26033215/189008485-f97adf53-8996-4e48-b289-a4811c8c2ff3.jpg)

**Comment by redleafnew** [comment]
1. 加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development。
2. 最好写下现在是什么样子的，希望改成什么样子的，方便对照。

**Comment by redleafnew** [comment]
`加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test`

已经加入这个也可以。

**Comment by redleafnew** [comment]
这是哪个期刊或学校的要求，修改好后我们重新添加一个csl。

**Comment by lijush** [comment]
已经加入群组，将截图中两个条目放在了“测试条目0908”文件夹下，就是希望两个作者的情况下，（谭羚雁等, 2012）（Ekstrom et al., 2014）改成（谭羚雁和娄成武, 2012）（Ekstrom & Moser, 2014），但三个或更多作者的情况下，还是用“等”或“et al.”。正在写北师大的学位论文，学校要求用gb-t-7714-2015，可以用数字格式，也可以用author-date，其他并没有要求太多，但用author-date、有两位作者的情况下往届的论文大都是（谭羚雁和娄成武, 2012）（Ekstrom & Moser, 2014）这种形式。

**Comment by redleafnew** [comment]
如果方便把北师大的格式要求网址发一下吧，写入到csl中。

**Comment by lijush** [comment]
http://bs.bnu.edu.cn/docs/20150408171708698394.pdf
![image](https://user-images.githubusercontent.com/26033215/189012687-5eb416d1-320d-4872-be53-ef99c6f0764b.png)
学校的要求很简单，就给了几个例子，也没有详细说，而且15年以后一直没有更新。我是参考了很多其他人论文的用法，觉得用011gb-t-7714-2015-author-date是最好的。

**Comment by lijush** [comment]
而且这一版格式出来的时候还是GB2005

**Comment by redleafnew** [comment]
> （Ekstrom & Moser, 2014）
> （谭羚雁和娄成武, 2012）
> 谭羚雁, 娄成武, 2012. 保障性住房政策过程的中央与地方政府关系——政策网络理论的分析与应用[J]. 公共管理学报, 9(1): 52-63+124-125.
> Ekstrom J A, Moser S C, 2014. Identifying and overcoming barriers in urban climate adaptation: case study findings from the San Francisco Bay Area, California, USA[J]. Urban climate, 9: 54-74.
> 

现在可以是这种效果了。

**Comment by lijush** [comment]
重新下载011gb-t-7714-2015-author-date这个csl文件就可以了吗？

**Comment by redleafnew** [comment]
我还没有上传。

**Comment by lijush** [comment]
哦哦，好嘞，您太厉害了！我昨天还尝试看一下代码，结果根本搞不懂，还是只能请您帮忙。非常感谢！

**Comment by lijush** [comment]
1.两个英文作者之间用“&”
2.文末两个作者之间不用加“和”或“&”

**Comment by redleafnew** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/419bnu-thesis.csl   试一下

**Comment by lijush** [comment]
已经可以了，非常感谢！

**Comment by redleafnew** [comment]
如果没有问题，请关闭此issue。

**Comment by lijush** [comment]
好的，再次感谢！
