### ISSUE TITLE
希望增加一种，文献在索引不是序号，但能按顺序排列的形式

### ISSUE THREAD

**Issue by llity** [redleafnew/Chinese-STD-GB-T-7714-related-csl#71]
让中文文献在英文文献内按顺序排列。谢谢
<img width="671" alt="image" src="https://user-images.githubusercontent.com/11771112/189373528-6a4fa2c8-50e5-4702-a322-e6363ade03bc.png">

**Comment by llity** [comment]
还有能显示全部作者的版本

**Comment by redleafnew** [comment]
这是哪的需求？需要提供地址（期刊或学校）
就是不按语言排序？只是按作者排序？
中文杂志斜体应该实现不了，其它可以。

**Comment by llity** [comment]
写基金的一般格式吧，没有序号，就是按照作者顺序即可，中英文分开有分割感觉，不太自然。

**Comment by llity** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11771112/189379688-749b8e8c-d4d9-4d78-a891-bc033dcb7847.png">
在这个版本基础上的，列出全部作者，文献只按顺序排列，不把中英文分开。

**Comment by redleafnew** [comment]
是仓库中的哪个？

**Comment by llity** [comment]
就是你的仓库啊

**Comment by redleafnew** [comment]
编号是什么？

**Comment by zepinglee** [comment]
> 让中文文献在英文文献内按顺序排列。

这里的意思是中文以拼音为 key 跟英文一起排序？这个目前无法实现。因为排序时只指定 locale，但是具体的顺序是由 `citeproc-js` 调用 [Unicode collation algorithm](https://en.wikipedia.org/wiki/Unicode_collation_algorithm) (UCA, <https://unicode.org/reports/tr10/>) 实现的。据我了解没有混合在一起的方法。

> 就是按照作者顺序即可，中英文分开有分割感觉，不太自然。

国标就是这么要求的。
<img width="744" alt="Screen Shot 2022-09-10 at 08 40 13" src="https://user-images.githubusercontent.com/12290822/189461856-679f74f6-7a17-4992-85a0-522d19d315f2.png">

**Comment by llity** [comment]
> > 让中文文献在英文文献内按顺序排列。
> 
> 这里的意思是中文以拼音为 key 跟英文一起排序？这个目前无法实现。因为排序时只指定 locale，但是具体的顺序是由 `citeproc-js` 调用 [Unicode collation algorithm](https://en.wikipedia.org/wiki/Unicode_collation_algorithm) (UCA, [unicode.org/reports/tr10](https://unicode.org/reports/tr10/)) 实现的。据我了解没有混合在一起的方法。
> 
> > 就是按照作者顺序即可，中英文分开有分割感觉，不太自然。
> 
> 国标就是这么要求的。 <img alt="Screen Shot 2022-09-10 at 08 40 13" width="744" src="https://user-images.githubusercontent.com/12290822/189461856-679f74f6-7a17-4992-85a0-522d19d315f2.png">

好的，记得Evernote能实现，以为zotero也行。谢谢

**Comment by llity** [comment]
就这个
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl

**Comment by redleafnew** [comment]
002是顺序编码的啊。
不是作者+年代的

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/189464798-5b3c3c44-59a7-438e-a1ba-0fe8a8008d9f.png)

**Comment by llity** [comment]
应该是这个格式的基础上 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses.csl
目前是中文在上面，英文下面。

1. 如果能安装英文/拼音首字母排序好，但 @zepinglee 前面提到不能实现。
2. 同时，能罗列出所有作者的姓名、杂志进行加粗或斜体等衍生版本。

<img width="649" alt="image" src="https://user-images.githubusercontent.com/11771112/189566959-e634cd7f-5428-4c68-8306-2c49a0ca8fdb.png">

**Comment by redleafnew** [comment]
1.确实实现不了。你需要中文在前面还是英文在前面。

**Comment by llity** [comment]
那就只能有序号的那种了，中文在前面蛮好的。顺序编码的索引不能正文（xxx），文献部分数字1xxx 2xxx这种吗？

**Comment by llity** [comment]
很多需要保留所有作者。(以下中文为小五，宋体，英文为Times New Roman，西文刊名斜体，保留全部引文作者姓名，参照NCBI网站写法，中文期刊同时配上英文对照，文章题目除句首和专有名词外全部小写。)
![image](https://user-images.githubusercontent.com/11771112/189568629-7b54fe43-60da-4c23-ad96-d5605916a6dc.png)

**Comment by redleafnew** [comment]
序号是指我截图中的那种吗？
顺序编码我觉得也可以写成：
张三等（2022）指出......[1]
参考文献：
张三，....2022.期刊.页码

**Comment by redleafnew** [comment]
还是给出具体的例子吧。

**Comment by llity** [comment]
遗传杂志，引用杂志斜体
[一例BBS12基因复合杂合突变导致Bardet-Biedl综合征的诊断和基因检测分析 代谢专刊 .pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9544365/BBS12.Bardet-Biedl.pdf)

**Comment by llity** [comment]
> 序号是指我截图中的那种吗？ 顺序编码我觉得也可以写成： 张三等（2022）指出......[1] 参考文献： 张三，....2022.期刊.页码
这样的形式。
<img width="665" alt="image" src="https://user-images.githubusercontent.com/11771112/189568935-cfa2d77f-6b4f-4780-90d0-0c211911d780.png">

**Comment by redleafnew** [comment]
> 遗传杂志，引用杂志斜体 [一例BBS12基因复合杂合突变导致Bardet-Biedl综合征的诊断和基因检测分析 代谢专刊 .pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9544365/BBS12.Bardet-Biedl.pdf)

斜体只能英文杂志实现，中文的实现不了。

**Comment by redleafnew** [comment]
> > 序号是指我截图中的那种吗？ 顺序编码我觉得也可以写成： 张三等（2022）指出......[1] 参考文献： 张三，....2022.期刊.页码
> 
> 这样的形式。这样中文和英文就能统一顺序排列了 <img alt="image" width="665" src="https://user-images.githubusercontent.com/11771112/189568935-cfa2d77f-6b4f-4780-90d0-0c211911d780.png">

文末是按什么排序的？按出现的顺序还是按作者姓名？

**Comment by llity** [comment]
按作者姓名首字母顺序

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/189571325-32323409-2597-4217-a633-855902fb911c.png)

**Comment by redleafnew** [comment]
如果需要斜体的话，只能是英文期刊名称，中文的不可以。

**Comment by llity** [comment]
谢谢了，等你更新。

**Comment by llity** [comment]
嗯，可以了。黑体+斜体可以

**Comment by redleafnew** [comment]
既加粗又斜体？

**Comment by llity** [comment]
弄成两个版本，加粗/斜体。

**Comment by redleafnew** [comment]
我在代码中注释一下吧。到时自己修改就可以了。

**Comment by llity** [comment]
好的，感谢。

**Comment by redleafnew** [comment]
016

**Comment by llity** [comment]
好的，如果我想把文献部分，数字的中括号去掉，在里面删掉[]就行了吧。
<img width="464" alt="image" src="https://user-images.githubusercontent.com/11771112/189635861-522821e8-2118-4146-b0aa-915a62ebf1b4.png">

**Comment by redleafnew** [comment]
已更新。

> 文献超过100个别错位哦，之前遇到过对不齐的情况

这个不知道怎么搞
@zepinglee 有办法吗？

**Comment by zepinglee** [comment]
需要在 Word 中设置悬挂缩进距离和制表符距离，跟 CSL 无关
