### ISSUE TITLE
请求《华北农学报》格式

### ISSUE THREAD

**Issue by Landscapelr** [redleafnew/Chinese-STD-GB-T-7714-related-csl#72]
老师，您好。
不知道能否麻烦做一个《华北农学报》的格式。相关地址为：[http://www.hbnxb.net/CN/column/column7.shtml#](http://www.hbnxb.net/CN/column/column7.shtml#)
最相近的为：[013gb-t-7714-2015-numeric-aulower-bilan-ce.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/013gb-t-7714-2015-numeric-aulower-bilan-ce.csl)
差异有：
1. 作者全部列出；
2. 添加DOI。

感谢！

**Comment by redleafnew** [comment]
DOI放最后，前面有无前缀之类的
最好给个例子。
加入Zotero群组，将例子条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
@Landscapelr 投稿指南（<http://www.hbnxb.net/CN/column/column7.shtml>）中提到「具体格式参见论文模板」，但是我并没有找到模板的链接。

模板的示例文献如果跟国标不同的话，最好全部录入群组中方便测试。

另外，加入群组后需要将 Zotero ID 发一下，由我提升为 admin 权限后才可以向其中添加文献条目。

**Comment by Landscapelr** [comment]
参考文献样式：
![图片](https://user-images.githubusercontent.com/26039583/190165682-62ef995b-6b8c-44c3-9c6a-4f7283ba17c9.png)
前面有前缀：“doi: "
对照国标，不同文献类型的标志代码一致；网站下载中心《[信息与文献 参考文献著录规则](http://www.hbnxb.net/CN/item/downloadFile.do?id=7)》为2015版国标，格式应该与国标一致。区别在红字说明文字：①参考文献作者全部列出；②中文文献添加英文信息，中英文对照；③添加doi号。
论文模板页面为空白，应该网站不提供论文模板了。
ID：Landscapex
邮箱：lanruolinx@outlook.com
我上传几篇华北农学报的文章做例子可以吗？

**Comment by zepinglee** [comment]
> 参考文献样式： ![图片](https://user-images.githubusercontent.com/26039583/190165682-62ef995b-6b8c-44c3-9c6a-4f7283ba17c9.png) 

这张图片有对应的官网链接吗？

> ID：Landscapex 

已经提升为 admin。

> 我上传几篇华北农学报的文章做例子可以吗？

OK。

**Comment by redleafnew** [comment]
[1] 李乾, 梁利群, 艾克达·热合曼, 孙博, 张立民, 董志国, 常玉梅. 不同盐度、碱度、pH值对瓦氏雅罗鱼精子活力及其受精率的影响[J/OL]. 华北农学报, 2021, 36(S1): 381-3892021, 36(S1): 381-389. [2022-09-14].
[2] 王亚, 王越涛, 申关望, 王付华, 王生轩, 白涛, 尹海庆. 聚合R基因Pigm和非R基因bsr-d1改良水稻稻瘟病抗性[J/OL]. 华北农学报, [日期不详]: 1-9[日期不详]: 1-9. [2022-09-14].
[3] 赵长江, 都梦翔, 宋巨奇, 徐尚缘, 贺琳, 徐晶宇, 杨克军, 李佐同. 玉米NRL基因家族鉴定与逆境表达分析[J/OL]. 华北农学报, 2022, 37(4): 1-102022, 37(4): 1-10. [2022-09-14].
[4] 闫留延, 李剑峰, 张世文, 张博, 王永芳, 张小梅, 祖超凡, 王振山, 桑璐曼, 何占祥, 贾小平, 董志平. 谷子SiPRR73基因的光温调控模式及非生物胁迫响应特性[J/OL]. 华北农学报, 2022, 37(4): 11-192022, 37(4): 11-19. [2022-09-14].

**Comment by Landscapelr** [comment]
图片是我截取发表文章里的。不过我拖拽PDF，似乎不能上传PDF到对应条目。我上传一个PDF到了阿里云盘
https://www.aliyundrive.com/s/HWmEEFzmUq2 提取码: [1234](https://www.aliyundrive.com/s/HWmEEFzmUq2)

我刚刚从知网拉取的，没有获取到doi，我去手动添加一下。不过我看类型里是没有”OL“的，直接为”[J]”

**Comment by redleafnew** [comment]
访问日期是不是也不需要？

**Comment by Landscapelr** [comment]
我已经手动添加了doi。
是的，访问日期也没有

**Comment by redleafnew** [comment]
> [1] 李乾, 梁利群, 艾克达·热合曼, 孙博, 张立民, 董志国, 常玉梅. 不同盐
 度、碱度、pH值对瓦氏雅罗鱼精子活力及其受精率的影响[J]. 华北农学报, 2021, 36(S1): 381-389. doi:10.7668/hbnxb.20192551.
> [2] 王亚, 王越涛, 申关望, 王付华, 王生轩, 白涛, 尹海庆. 聚合R基因Pigm和非R基因bsr-d1改良水稻稻瘟病抗性[J]. 华北农学报, [日期不详]: 1-9. [日期不详]: 1-9. . .
> [3] 赵长江, 都梦翔, 宋巨奇, 徐尚缘, 贺琳, 徐晶宇, 杨克军, 李佐同. 玉米NRL基因家族鉴定与逆境表达分析[J]. 华北农学报, 2022, 37(4): 1-10. doi:10.7668/hbnxb.20192757.
> [4] 闫留延, 李剑峰, 张世文, 张博, 王永芳, 张小梅, 祖超凡, 王振山, 桑璐曼, 何占祥, 贾小平, 董志平. 谷子SiPRR73基因的光温调控模式及非生物胁迫响应特性[J]. 华北农学报, 2022, 37(4): 11-19. doi:10.7668/hbnxb.20193022.
> [5] Des Marais D J, Strauss H, Summons R E, Hayes J M. Carbon isotope evidence for the stepwise oxidation of the Proterozoic environment[J]. Nature, 1992, 359(6396): 605-609. doi:10.1038/359605a0.

日期不详这个还是有问题

**Comment by Landscapelr** [comment]
日期不详的那个是网络首发，这个应该不多，手动改一下也不麻烦。
我在短标题里加入了随便加入了一篇英文的参考文献内容。麻烦老师再测试一下

**Comment by Landscapelr** [comment]
老师早点休息，我这个不急。
感谢两位老师，祝身体健康，工作生活顺利！

**Comment by redleafnew** [comment]
`<text variable="DOI" prefix=". doi:"/>` 
为了兼顾用了这个不优雅的方法。

@zepinglee 

> [1]
> [2]
> [3]
> [4]
> [5]
> [1] 李乾, 梁利群, 艾克达·热合曼, 孙博, 张立民, 董志国, 常玉梅. 不同盐度、碱度、pH值对瓦氏雅罗鱼精子活力及其受精率的影响[J]. 华北农学报, 2021, 36(S1): 381-389. doi:10.7668/hbnxb.20192551.
> Zhao X, Zhao Q P, Xu C Y, Wang J, Zhu J D, Shang B S, Zhang X. Phot2-regulated relocation of NPH3 mediates phototropic response to high-intensity blue light in Arabidopsis thaliana[J]. J Integr Plant Biol, 2018, 60(7):562-577.
> 
> [2] 王亚, 王越涛, 申关望, 王付华, 王生轩, 白涛, 尹海庆. 聚合R基因Pigm和非R基因bsr-d1改良水稻稻瘟病抗性[J]. 华北农学报, [日期不详]: 1-9.
> [3] 赵长江, 都梦翔, 宋巨奇, 徐尚缘, 贺琳, 徐晶宇, 杨克军, 李佐同. 玉米NRL基因家族鉴定与逆境表达分析[J]. 华北农学报, 2022, 37(4): 1-10. doi:10.7668/hbnxb.20192757.
> Zhao X, Zhao Q P, Xu C Y, Wang J, Zhu J D, Shang B S, Zhang X. Phot2-regulated relocation of NPH3 mediates phototropic response to high-intensity blue light in Arabidopsis thaliana[J]. J Integr Plant Biol, 2018, 60(7):562-577.
> 
> [4] 闫留延, 李剑峰, 张世文, 张博, 王永芳, 张小梅, 祖超凡, 王振山, 桑璐曼, 何占祥, 贾小平, 董志平. 谷子SiPRR73基因的光温调控模式及非生物胁迫响应特性[J]. 华北农学报, 2022, 37(4): 11-19. doi:10.7668/hbnxb.20193022.
> Zhao X, Zhao Q P, Xu C Y, Wang J, Zhu J D, Shang B S, Zhang X. Phot2-regulated relocation of NPH3 mediates phototropic response to high-intensity blue light in Arabidopsis thaliana[J]. J Integr Plant Biol, 2018, 60(7):562-577.
> 
> [5] Des Marais D J, Strauss H, Summons R E, Hayes J M. Carbon isotope evidence for the stepwise oxidation of the Proterozoic environment[J]. Nature, 1992, 359(6396): 605-609. doi:10.1038/359605a0.

现在是这个效果

**Comment by redleafnew** [comment]
测试一下 111 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/111acta-agriculurae-boreali-sinica.csl

**Comment by Landscapelr** [comment]
我觉得没问题了，再次感谢老师

**Comment by redleafnew** [comment]
如已完成，请关闭。
