### ISSUE TITLE
bnu学位论文引用书籍时如何添加页码

### ISSUE THREAD

**Issue by lijush** [redleafnew/Chinese-STD-GB-T-7714-related-csl#73]
老师，您好！

之前请您帮忙修改过bnu学位论文的csl文件，现在使用的过程中又发现一个小问题之前没有考虑到，就是在引用书籍的时候，正文中的（author, date）如何显示成（author, date, p.）或（author, date, pp.）的格式？例如，（秦明瑞, 2019）在引用第5页的时候如何改成（秦明瑞, 2019, p.5），在引用第15-17页的时候如何改成（秦明瑞, 2019, pp.15~17）?

相关的条目已放在共享文件夹0908子文件夹下面，不知您能否再帮忙修改一下？

十分感谢！

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/190301793-908b7638-730b-4b88-977d-db3395264215.png)
在这在插入的时候在page处写上试试。

**Comment by lijush** [comment]
![image](https://user-images.githubusercontent.com/26033215/190302636-55de5478-17a1-471b-946b-87e69a97809f.png)
我试过了，但是正文中还是显示不出来页码

**Comment by redleafnew** [comment]
我修改了一下，可以显示为：

> （Cheong et al., 2013, p. 99）
> （程根伟, 1999, 页 99-100）
> （Jha et al., 2004, pp. 99-100）

但中文显示
@zepinglee 有办法把页放到后面吗？

**Comment by redleafnew** [comment]
@lijush 这个“页”在前面可以吗？

**Comment by redleafnew** [comment]
实现了，已经上传。
方法：
https://forums.zotero.org/discussion/comment/417282#Comment_417282

**Comment by zepinglee** [comment]
嗯，就是这么处理。

**Comment by lijush** [comment]
> 

不好意思，刚注意到，已经可以了。非常感谢！

**Comment by redleafnew** [comment]
如果可以了请关闭。

**Comment by lijush** [comment]
再次感谢！
