### ISSUE TITLE
202管理世界参考文献顺序应为中文在前

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#74]
目前的参考文献顺序是英文在前，需要更新一下
感谢！

**Comment by redleafnew** [comment]
现在的实际效果是中文在前的，readme中的效果没有调整过来，一会儿调整一下。需要设置中文条目语言为cn，英文条目语言为en。

**Comment by fredericky123** [comment]
> 现在的实际效果是中文在前的，readme中的效果没有调整过来，一会儿调整一下。需要设置中文条目语言为cn，英文条目语言为en。

中文条目的语言是zh-cn,需要像《经济研究》把language的sort注释掉就好了

**Comment by redleafnew** [comment]
好的，注释也可以，改为降序也可以。谢谢。代码改为了降序。
