### ISSUE TITLE
希望增加日文文献引用

### ISSUE THREAD

**Issue by wr42325** [redleafnew/Chinese-STD-GB-T-7714-related-csl#75]
现有的日文文献引用是英文体例，希望可以增加《法学引注手册》上面的日文文献体例。（附期刊论文格式比较图：图一为现在的格式，图二为法学引注手册的格式）
![1663917420411](https://user-images.githubusercontent.com/114215379/191909598-7b1ea3e4-9ac4-4486-982e-c7690c84b00a.png)
![1663917459234](https://user-images.githubusercontent.com/114215379/191909674-20d99ae7-0b9e-4784-a843-d738c2a34118.png)

**Comment by zepinglee** [comment]
日文文献需要在 `language` 字段填写 `ja` 或 `ja-JP`，参考 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/66YU3G7J>。

这个 csl 的语言默认为英语，其他语言都需要在 language 字段填写语言代码。

**Comment by wr42325** [comment]
已改，谢谢！
