### ISSUE TITLE
求问如何将“同上注”这样的简略引注更改为完整引注格式

### ISSUE THREAD

**Issue by wr42325** [redleafnew/Chinese-STD-GB-T-7714-related-csl#76]
您好！谢谢您分享的引注文件，特别好用。我想请教您一个问题，我怎么修改您提供的文件才能把中外文的“同上注，XX书”这种简化引注改为完整版引注呢？投稿的时候，有的期刊会要求完整引注，如果自己用word的替换功能的话，略显繁琐。

**Comment by wr42325** [comment]
如果您这边能直接增加一种完整引注的形式就更好了！《法学引注手册》的格式实际没有推广开，各个期刊投稿还是要求按它们各自的格式来。所以一般写的时候会完整引注，投稿时候再视期刊要求决定要不要改为简略引注。一开始写的时候就简略引注的话，遇到要求完整引注的期刊会很麻烦。

**Comment by wr42325** [comment]
如果您这边能在现有《法学引注手册》的形式之上再增加一种完整引注的形式就好了。
现有的形式已经比较完善，但是实际写作时，往往会完整引注，投稿时候再视期刊要求决定是否改为“同前注X”这种。
如果写作时候就简略引注，遇到要求完整引注的期刊会很麻烦。

**Comment by zepinglee** [comment]
可以再加一个 `-no-ibid` 版本的 csl 样式。

**Comment by zepinglee** [comment]
《手册》中有提到：

> 同一文献在文中多次出现的，第一次必须引用完整信息，再次引用时可以 略写。是否略写，由各刊物、出版社或者出版社授权编辑自行决定。为防止修 改、编辑过程中发生错乱，作者投稿时不建议采用略写。

@wr42325 目前在实际中采取哪种方式的期刊/出版社更多？另外能不能举个具体期刊的例子？

**Comment by wr42325** [comment]
如果是作者投稿的底稿的话，现在的CSL样式和投稿用的底稿样式差不多，我现在刚用zotero，只发现两处可以改的地方。一处就是把略写改为完整引用，另一处是英文引注的体例，卷数后面可以增加“(期数)”，比如California Law Review的vol.47，no.2，现在的CSL样式是47 California Law Review，实际投稿时会把期数也标出来，如47 (2) California Law Review。 
如果是出版的定稿的话，略写的多一点，而且彼此之间有细微区别，比如有的不要“载”，有的要页码，整体处于很混乱的局面。具体可以参见法学领域那十几本核心期刊目录里的体例，CLSCI（ China Legal Science Citation Index）。
我这里说的完整引注的体例，可以参见《比较法研究》，https://bjfy.cbpt.cnki.net/WKC/WebPublication/wkTextContent.aspx?navigationContentID=2374b53a-65b2-4759-8863-86759c31cc9f&mid=bjfy
一般，投稿时作者用完整引注的底稿投，包括页码，编辑有要求的时候再对完整引注的底稿做对应的改动。

**Comment by zepinglee** [comment]
> 一处就是把略写改为完整引用，另一处是英文引注的体例，卷数后面可以增加“(期数)”，比如California Law Review的vol.47，no.2，现在的CSL样式是47 California Law Review，实际投稿时会把期数也标出来，如47 (2) California Law Review。 

目前的样式是依据 2020 年出版的《法学引注手册》，其中英文文献并没有文章期号。另外英文版其实是参照了 [Bluebook](https://www.legalbluebook.com/bluebook/v21/quick-style-guide) 其中也没有期号。

所以该 csl 样式最好严格执行《手册》的格式。如果有期刊额外要求期号，可以再次基础上修改期刊的定制版本。

> 如果是出版的定稿的话，略写的多一点

投稿时哪种格式更多一些呢？我想将较多的一种选为 manula-of-legal-citation.csl 的默认样式，另一种为修改版： `manula-of-legal-citation-with-ibid` 或 `manula-of-legal-citation-no-ibid`。

> 而且彼此之间有细微区别，比如有的不要“载”，有的要页码，整体处于很混乱的局面。

《手册》第 14 节“同一文献多次出现”并没有“载”字的示例；页码是由作者选择是否插入的。

**Comment by wr42325** [comment]
明白。如果严格执行投稿格式的话，法学核心期刊多为略写，法学普刊完整引注居多。从影响力和代表性的角度看，默认样式建议略写，《法学引注手册》也是这个考虑。
很赞成另外提供no-bid版本的想法，这样的话写作更便利~
“载”这个与多次引用无关，我只是举例表明投稿格式混乱，不用管了~

**Comment by zepinglee** [comment]
3774798 种新增无略写版 [306manual-of-legal-citation-multi-lingual-no-ibid.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/306manual-of-legal-citation-multi-lingual-no-ibid.csl)。详细的测试文献结果见 <https://github.com/zepinglee/csl-development/commit/43c5ee1db47fb5a936047bf715a786de2fce633d>。

**Comment by wr42325** [comment]
好的，谢谢。我还有两个与现有的CSL样式无关的问题，想请问您。
一、“中文司法案例援引裁判文书时需要在 Extra 字段填写文书名称，比如 genre: 民事判决书”，请问这个“Extra字段”指的是哪里呀？
二、我从北大法宝下载的中文裁判文书，ZOTERO不能识别为“司法案例”类型，而是识别为“网页”。手动更改为“司法案例”后，相应的信息也不符合格式。从Westlaw下载的英文裁判文书也是这种情况。只有从谷歌学术case law选项下下载的裁判文书才能正确生成格式。请问这种情况是ZOTERO本身的缺陷所导致吗？还是因为前两个案例库要付费，ZOTERO无法正确自动抓取的原因？

**Comment by zepinglee** [comment]
> 好的，谢谢。我还有两个与现有的CSL样式无关的问题，想请问您。 一、“中文司法案例援引裁判文书时需要在 Extra 字段填写文书名称，比如 genre: 民事判决书”，请问这个“Extra字段”指的是哪里呀？ 

参考 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/GTTN32IE/items/NA3IGSCJ/collection> 的中文司法案例。这些都是《手册》中的示例文献。

<img width="353" alt="Screen Shot 2022-09-24 at 16 12 36" src="https://user-images.githubusercontent.com/12290822/192087851-85f67928-9985-48e9-a547-b1e196589be6.png">

> 二、我从北大法宝下载的中文裁判文书，ZOTERO不能识别为“司法案例”类型，而是识别为“网页”。手动更改为“司法案例”后，相应的信息也不符合格式。从Westlaw下载的英文裁判文书也是这种情况。只有从谷歌学术case law选项下下载的裁判文书才能正确生成格式。请问这种情况是ZOTERO本身的缺陷所导致吗？还是因为前两个案例库要付费，ZOTERO无法正确自动抓取的原因？

从网页抓取文献的功能是由 <https://github.com/zotero/translators> 提供的，另外还有中文 translator 项目 <https://github.com/l0o0/translators_CN>。如果没有正确识别的话，可能是没有提供相应网站的 translator，也可能是其中的代码有 bug。你可以发 issue 跟他们沟通一下。

**Comment by wr42325** [comment]
谢谢！那我先关闭这个issue，有问题再请教你们~
