### ISSUE TITLE
作者年代格式

### ISSUE THREAD

**Issue by Shengyanwen** [redleafnew/Chinese-STD-GB-T-7714-related-csl#77]
使用（作者，年代）格式的时候，有没有办不拆分姓名，也不会出现（张xx，和张xx，2020）这样的情况？

**Comment by zepinglee** [comment]
> 使用（作者，年代）格式的时候

具体哪个 csl 样式？

> 有没有办不拆分姓名，也不会出现（张xx，和张xx，2020）这样的情况？

原始字段信息是什么？你希望得到什么样的格式？

**Comment by Shengyanwen** [comment]
> > 使用（作者，年代）格式的时候
> 
> 具体哪个 csl 样式？
> 
> > 有没有办不拆分姓名，也不会出现（张xx，和张xx，2020）这样的情况？
> 
> 原始字段信息是什么？你希望得到什么样的格式？

样式是：njau-thesis-author-date，中文条目在zotero中不拆分姓名的话，正文中引用为：（张xx，和张xx，2020），希望能不改变条目的情况下，变成（张xx和张xx，2020）

**Comment by zepinglee** [comment]
> 样式是：njau-thesis-author-date，中文条目在zotero中不拆分姓名的话，正文中引用为：（张xx，和张xx，2020），希望能不改变条目的情况下，变成（张xx和张xx，2020）

这个无法实现。

合并姓名的操作只是为了方便显示，但是不符合 CSL 样式的规范，无法正确识别为多个姓名。所以导出时还是需拆分姓名。

**Comment by Shengyanwen** [comment]
> > 样式是：njau-thesis-author-date，中文条目在zotero中不拆分姓名的话，正文中引用为：（张xx，和张xx，2020），希望能不改变条目的情况下，变成（张xx和张xx，2020）
> 
> 这个无法实现。
> 
> 合并姓名的操作只是为了方便显示，但是不符合 CSL 样式的规范，无法正确识别为多个姓名。所以导出时还是需拆分姓名。

ok, thanks. 那能把这个参考文献改成 按引用顺序排序，前面有编号的形式吗？，如：[1]

**Comment by zepinglee** [comment]
> > > 样式是：njau-thesis-author-date，中文条目在zotero中不拆分姓名的话，正文中引用为：（张xx，和张xx，2020），希望能不改变条目的情况下，变成（张xx和张xx，2020）
> > 
> > 
> > 这个无法实现。
> > 合并姓名的操作只是为了方便显示，但是不符合 CSL 样式的规范，无法正确识别为多个姓名。所以导出时还是需拆分姓名。
> 
> ok, thanks. 那能把这个参考文献改成 按引用顺序排序，前面有编号的形式吗？，如：[1]

[405njau-thesis.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/405njau-thesis.csl)

**Comment by zepinglee** [comment]
> > 样式是：njau-thesis-author-date，中文条目在zotero中不拆分姓名的话，正文中引用为：（张xx，和张xx，2020），希望能不改变条目的情况下，变成（张xx和张xx，2020）
> 
> 这个无法实现。
> 
> 合并姓名的操作只是为了方便显示，但是不符合 CSL 样式的规范，无法正确识别为多个姓名。所以导出时还是需拆分姓名。

好像不完全正确。

@Shengyanwen 显示为“（张xx，和张xx，2020）”的文献中 `author` 字段的原始信息是什么？
