### ISSUE TITLE
心理科学进展 csl 相关小问题

### ISSUE THREAD

**Issue by Boycottangent** [redleafnew/Chinese-STD-GB-T-7714-related-csl#78]
首先非常感谢能提供一份兼容中英混排相对比较完美的APA格式文件，我自己用心理科学进展这个的时候发现了一些小问题，想修改但不知道怎么下手。
1. **文末参考文献列表的中文期刊名不会斜体**：英文期刊会斜体，但是中文期刊就不会，不太清楚是哪里出了问题
2. **文末参考文献列表的中文期刊排序问题**：需要按照名称首字母顺序排序，目前没有办法做到

这些问题猜测可能和文献的语言设置有关，不过我更改了zh / zh-cn 似乎都没有解决问题

**Comment by redleafnew** [comment]
> 首先非常感谢能提供一份兼容中英混排相对比较完美的APA格式文件，我自己用心理科学进展这个的时候发现了一些小问题，想修改但不知道怎么下手。
> 
> 1. **文末参考文献列表的中文期刊名不会斜体**：英文期刊会斜体，但是中文期刊就不会，不太清楚是哪里出了问题

中文期刊名无法实现斜体，https://forums.zotero.org/discussion/88346/font-style-italic-doesnt-work-for-chinese-publication#latest

> 2. **文末参考文献列表的中文期刊排序问题**：需要按照名称首字母顺序排序，目前没有办法做到
> 
> 这些问题猜测可能和文献的语言设置有关，不过我更改了zh / zh-cn 似乎都没有解决问题

加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

英语是en-US，中文是zh-CN

**Comment by zepinglee** [comment]
1. 严肃的中文出版物不会使用斜体汉字。英文的斜体是为了表达“书名”，对应中文应该使用书名号。不过《心理科学进展》要求斜体中文，需要跟他们编辑沟通。
2. 没有设置 `default-locale` 是为了能够正确处理英文标题的大小写（title case），这也会导致没有按照中文顺序排序。可以设置 `default-locale-sort ="zh-CN"` 可以同时满足两者的需求。

**Comment by Boycottangent** [comment]
排序问题在加了`default-locale-sort ="zh-CN"`后解决了，斜体问题看起来只能手动调整了，感谢

**Comment by zepinglee** [comment]
另外，该样式仅在 apa.csl 的基础上调整了姓名的格式，没有进行完整的测试。所以其他部分可能不符要求。

如果需要修改的话请将官方的示例文献录入到 Zotero 群组中。
