### ISSUE TITLE
GB有没有author up, bi language的版本？

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/Chinese-STD-GB-T-7714-related-csl#8]
感谢老师！

**Comment by fredericky123** [comment]
china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl
就是想在这个基础上，只修改一个author up

**Comment by redleafnew** [comment]
什么叫只修改一个author up

**Comment by fredericky123** [comment]
我好想搞定了，就是将china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl
这个版本的author lower改为author up

**Comment by redleafnew** [comment]
好的。好像默认7714就是大写的。

我以为只是修改一个作者为大写，其他为小写。

那我关闭了。



Best regards!
 
Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University
 
 
发件人： fredericky123
发送时间： 2021-07-21 14:35
收件人： redleafnew/Chinese-STD-GB-T-7714-related-csl
抄送： redleafnew; Comment
主题： Re: [redleafnew/Chinese-STD-GB-T-7714-related-csl] GB有没有author up, bi language的版本？ (#8)
我好想搞定了，就是将china-national-standard-gb-t-7714-2015-numeric-aulower-bilan-nodoi.csl
这个版本的author lower改为author up

**Comment by fredericky123** [comment]
对，不过好像收录库里缺少bi-language的7714默认版本，我对比了差异就自己改动了
