### ISSUE TITLE
 能否去掉参考文献显示网址及DOI号

### ISSUE THREAD

**Issue by olivia0317** [redleafnew/Chinese-STD-GB-T-7714-related-csl#80]
更新后的csl文件，最后的参考文献会显示网址和doi号，请问能否去除～～

**Comment by redleafnew** [comment]
用得哪个csl，加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by zepinglee** [comment]
[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)

**Comment by redleafnew** [comment]
> [002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)

我测试这个是没有DOI的。

**Comment by zepinglee** [comment]
我的意思是 002 满足需求。

**Comment by redleafnew** [comment]
哦，好的，所以我问他用的哪个csl

**Comment by olivia0317** [comment]
你好，我用的是210advances-in-psychological-science.csl这个csl

**Comment by redleafnew** [comment]
提供一下测试条目吧。

**Comment by redleafnew** [comment]
如果需要修改请联系作者，并将期刊官方提供的全部示例文献录入 Zotero 群组。
加入Zotero群组，提供Zotero ID，然后请@zepingli赋予编辑权限，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by olivia0317** [comment]
你好，我是刚刚接触zotero这个软件，可能理解您说的测试条目不太到位，我去《心理科学进展》官网上下载了“参考文献要求格式”和一篇已发表的文献，供您参考。如果还需要其他文件，请邮件告知我，我再去找寻，谢谢您的回复和耐心解答～～

**Comment by redleafnew** [comment]
@zepinglee 当时这个csl 是要显示URL和DOI的吗？
我测试是显示类似：https://doi.org/10.1016/j.matpr.2020.12.922的，
我没有看期刊的要求。

**Comment by olivia0317** [comment]
这个210advances-in-psychological-science.csl文件显示URL和doi，但中文期刊的要求是不显示URL和doi，请问能否去掉URL和doi

**Comment by redleafnew** [comment]
请
@zepinglee 处理一下吧。

**Comment by zepinglee** [comment]
《心理科学进展》参考文献著录格式(著者-出版年制)详细要求第 7 页：

> 包括 APA 还要求文献后要有 DOI, 我们只当作可选项, 不做硬性规定

去掉 DOI 也可以。

**Comment by zepinglee** [comment]
在 c3ec5e7 中去掉了 URL 和 DOI。
