### ISSUE TITLE
按照语言显示“等”或“et al.”的问题

### ISSUE THREAD

**Issue by Celcnu** [redleafnew/Chinese-STD-GB-T-7714-related-csl#82]
**描述错误**

CSL 样式：007gb-t-7714-2015-numeric-bilingual-no-uppercase.csl
NOTE：00x的样式都有这个问题

虽然作者是中国人，但这是一篇英文论文，所以应该显示 et al，而不应该用“等”
错误样式：
Li Y, Lin T, Tang H, 等. A chunk caching location and searching scheme in Content Centric Networking[C/OL]//2012 IEEE International Conference on Communications (ICC). 2012: 2655-2659. DOI:10.1109/ICC.2012.6363958.
正确样式：
Li Y, Lin T, Tang H, et al. A chunk caching location and searching scheme in Content Centric Networking[C/OL]//2012 IEEE International Conference on Communications (ICC). 2012: 2655-2659. DOI:10.1109/ICC.2012.6363958.

**条目信息**
```json
[
	{
		"id": "http://zotero.org/users/9790334/items/T9JF7ZLJ",
		"type": "paper-conference",
		"abstract": "xxx",
		"archive": "CLS",
		"container-title": "2012 IEEE International Conference on Communications (ICC)",
		"DOI": "10.1109/ICC.2012.6363958",
		"event-title": "2012 IEEE International Conference on Communications (ICC)",
		"note": "ISSN: 1938-1883",
		"page": "2655-2659",
		"source": "IEEE Xplore",
		"title": "A chunk caching location and searching scheme in Content Centric Networking",
		"author": [
			{
				"family": "Li",
				"given": "Yang"
			},
			{
				"family": "Lin",
				"given": "Tao"
			},
			{
				"family": "Tang",
				"given": "Hui"
			},
			{
				"family": "Sun",
				"given": "Peng"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2012",
					6
				]
			]
		}
	}
]
```

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/c3ec5e7b0693248ee6ea50ee17d79e5022b62003/000gb-t-7714-2015-numeric-bilingual.csl#L2

这里设置了 `default-locale="zh-CN"`，默认语言为中文，所以英文文献需要在 `language` 字段填写 `en` 或 `en-US`。

**Comment by Celcnu** [comment]
thx，我设置默认en了，都显示et al. 对我来说是ok的
