### ISSUE TITLE
样式请求：Journal of Plant Protection（植物保护学报）

### ISSUE THREAD

**Issue by XK4959** [redleafnew/Chinese-STD-GB-T-7714-related-csl#84]
**样式信息**

- 期刊名称：植物保护学报
- 期刊英文名：Journal of Plant Protection
- ISSN 号：国内统一刊号：11-1983/S 
- 期刊官网：http://www.zwbhxb.com.cn/ch/index.aspx
- 参考文献格式要求的链接：
http://www.zwbhxb.com.cn/ch/first_menu.aspx?parent_id=20081122190830001

_与已有的哪个 CSL 样式最接近？__
 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/419bnu-thesis.csl
_与上一条格式的主要区别：_
1.文献著录时，**中文文献需给出对应的英文对照**，且英文在前，中文置于其后方括号中，如果原文献没有对应的英文，请一定自己翻译，尽可能正确。
2.所有中英文文献统一按照英文字母升序排列。
3.作者数在10位之内的需全部列出，超过10位的用“等”或“et al.”代替。
示例：
![image](https://user-images.githubusercontent.com/74860841/196845467-c9ecf284-0391-411b-894d-1b210b0b3e5b.png)

**Comment by redleafnew** [comment]
提供Zotero ID；
加入Zotero群组，将示例的条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
中文文献的把英文翻译放到Zotero的Short Title字段

**Comment by XK4959** [comment]
好的，我试试，十分感谢

**Comment by XK4959** [comment]
![image](https://user-images.githubusercontent.com/74860841/196847994-bdb6b0e4-93c3-4663-ba8e-d97b99d12105.png)
添加后还是不太行，我使用的以下格式：
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/419bnu-thesis.csl
![image](https://user-images.githubusercontent.com/74860841/196848109-a011f8a4-d719-4fba-a474-8717155b3fc5.png)

**Comment by redleafnew** [comment]
把中文文献条目自己转为英文的吧，每个字段都翻译为英文，相当于形成一个新条目，原来的中文所有信息添加到Short Title，因为这个翻译的在前，原来的不好处理。

**Comment by redleafnew** [comment]
需要重新制作

**Comment by XK4959** [comment]
好的，那我就自己将中文题目改成对应的英文题目；
随后，将原始题目添加到Short Title。

但目前的格式似乎不会在引文最后加上Short Title信息，我们有可以实现该功能的格式吗？
十分感谢！

**Comment by redleafnew** [comment]
需要修改原来的style来实现，但这个实现起来更麻烦些。

**Comment by XK4959** [comment]
嗯嗯，
您有时间和兴趣的话可以改改看；
没有时间的话，我手动改也可以。

总之，还是十分感谢！

**Comment by redleafnew** [comment]
先提供你图片上的例子吧，放入到Zoterohttps://www.zotero.org/groups/4677213/gbt_7714_csl_development群组中。

**Comment by XK4959** [comment]
请问以什么格式提供该例子呢？之前没有使用过该群组。

**Comment by redleafnew** [comment]
Zotero教程见：https://github.com/redleafnew/Zotero_introduction 有一章讲述群组使用的。
https://gitee.com/zotero-chinese/zotero-chinese/issues/I4Z8JP

**Comment by XK4959** [comment]
好的 谢谢

**Comment by redleafnew** [comment]
https://user-images.githubusercontent.com/74860841/196845467-c9ecf284-0391-411b-894d-1b210b0b3e5b.png
这上的例子，录入到Zotero，再拖动到群组，或直接录入到群组。

**Comment by XK4959** [comment]
好的好的

**Comment by XK4959** [comment]
![image](https://user-images.githubusercontent.com/74860841/196851213-e0489284-6a44-4f30-988d-81ac8a924c5a.png)
![image](https://user-images.githubusercontent.com/74860841/196851232-b53b70c2-9347-4c6c-9dbc-a0dcb603e0c1.png)
你好，我已成功加入该群组；
但我无法将我的文献加入群组文库；
也没法在群组文库中添加文献（显示的是黑圈禁止符号），似乎是没有权限。

另外，图片上的例子是该期刊提供的，我没有对应的信息；
我是应该将这些例子的期刊添加后上传，
还是将我自己的参考文献上传进行测试呢？

**Comment by XK4959** [comment]
![image](https://user-images.githubusercontent.com/74860841/196851569-5671d3b2-5782-4db9-a5a8-adfbb288cdc4.png)
似乎没有操作权限。

十分感谢，下午的时候我再进行测试。

**Comment by redleafnew** [comment]
将你的Zotero ID 发出来，然后 
@zepinglee 会处理。

**Comment by XK4959** [comment]
ID：XK4959
![image](https://user-images.githubusercontent.com/74860841/196852336-76dec679-0ed8-4833-a140-f60cea96127f.png)
我如果没有理解错的话，是这个ID。

**Comment by XK4959** [comment]
图片上的例子是该期刊提供的，我没有对应的信息；
我是应该将这些例子的期刊添加后上传，
还是将我自己的参考文献上传进行测试呢？

请问我提供哪些例子进行测试比较合适呢？

**Comment by redleafnew** [comment]
最好是期刊上的，方便对照看效果。

**Comment by XK4959** [comment]
好的 谢谢

**Comment by zepinglee** [comment]
<img width="870" alt="Screen Shot 2022-10-20 at 13 57 26" src="https://user-images.githubusercontent.com/12290822/196867668-c9a62325-dddb-49bb-8250-086b390495f0.png">

已经修改权限为 admin。

**Comment by zepinglee** [comment]
> ~中文文献的把英文翻译放到Zotero的Short Title字段~

@redleafnew 我最近写“北大法宝”的 translator 发现《法学引注手册》需要用到 `shortTitle`，所以不宜将英文翻译部分填到 `shortTitle` 中。

我的想法是将中文内容填到 `extra` 的 `original-author`, `original-title` 等字段。比如期刊官网的示例“Qin JD. 1987. The relationships between insects and plants. Beijing: Science Press, pp. 52-78 (in Chinese) [钦俊德. 1987. 昆虫与植物的关系. 北京: 科学出版社, pp. 52-78]”，在 `extra` 中填的内容是：
```
original-author: 钦俊德
original-author: 钦俊德
original-author: 钦俊德

```

**Comment by redleafnew** [comment]
@zepinglee 你有时间搞一下吗？
我这两天出差。

**Comment by zepinglee** [comment]
OK。初步改了一部分，周末再继续搞。

**Comment by zepinglee** [comment]
[plant-protection](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/plant-protection) 分支中添加了 CSL 样式。效果：

<blockquote>
  （Altieri &#38; Nicholls，2004）<br>
  （Biesmeijer et al.，2006）<br>
  （Garnsey et al.，1993）<br>
  （McDonald &#38; Nicol，2005）<br>
  （钦俊德，1987）<br>
  （孙玉凤等，2011）<br>
  （Tautz et al.，2002）<br>
  （吴孔明和郭予元，2000）<br>
  （叶恭银等，1998）<br>
  （曾士迈等，1979）<br>
  （张徐波，2013）<br>
  （曾士迈等，1979；吴孔明和郭予元，2000）<br>
</blockquote>

<blockquote>
  <div class="csl-bib-body">
    <div class="csl-entry">Altieri MA, Nicholls CI. 2004. Biodiversity and pest management in agroecosystems (2nd edition). New York: Food Products Press</div>
    <div class="csl-entry">Biesmeijer JC, Roberts SPM, Reemer M, Ohlemüller R, Edwards M, Peeters T, Schaffers AP, Potts SG, Kleukers R, Thomas CD, et al. 2006. Parallel declines in pollinators and insect-pollinated plants in Britain and the Netherlands. Science, 313(5785): 351-354</div>
    <div class="csl-entry">Garnsey SM, Permar TA, Cambra M, Henderson CT. 1993. Direct tissue blot immunoassay (DTBIA) for detection of citrus tristeza virus (CTV).//Moreno P, de Graca JV, Yokomi RK. Proceedings of the 12th Conference on International Organization of Citrus Virologist. Riverside. Riverside, USA, pp. 39-50</div>
    <div class="csl-entry">McDonald AH, Nicol JM. 2005. Nematode parasites of cereals.//Luc M, Sikora RA, Bridge J. Plant parasitic nematodes in subtropical and tropical agriculture. Wallingford, UK: CABI Publishing, pp. 131-191</div>
    <div class="csl-entry">Qin JD. 1987. The relationships between insects and plants. Beijing: Science Press, pp. 52-78 (in Chinese) [钦俊德. 1987. 昆虫与植物的关系. 北京: 科学出版社, pp. 52-78]</div>
    <div class="csl-entry">Sun YF, Zhang YJ, Lu YH, Wu KM. 2011. The sustainability control of blind stink bug based on the cotton volatile substances.//Wu KM, Guo YY. Plant protection science and technology innovation and specialization of the prevention and control of diseases and pests—Academic annual Conference of Botanical China Society of Plant Protection in 2011. Beijing: China Agricultural Science and Technology Press, pp. 823 (in Chinese) [孙玉凤, 张永军, 陆宴辉, 吴孔明. 2011. 基于棉花挥发性物质的盲椿象可持续性防治.//植保科技创新与病虫防控专业化——中国植物保护学会2011年学术年会论文集. 北京: 中国农业科学技术出版社, pp. 823]</div>
    <div class="csl-entry">Tautz D, Arctander P, Minelli A, Thomas RH, Vogler AP. 2002. DNA points the way ahead in taxonomy. Nature, 418(6897): 479</div>
    <div class="csl-entry">Wu KM, Guo YY. 2000. Field resistance evaluations of BT transgenic cotton GK series to cotton bollwoam. Journal of Plant Protection, 27(4): 317-321 (in Chinese) [吴孔明, 郭予元. 2000. 部分GK系列Bt棉对棉铃虫抗性的田间评价. 植物保护学报, 27(4): 317-321]</div>
    <div class="csl-entry">Ye GY, Hu C, Shu QY. 1998. The development of transgenic rice resistant to insect pests and its wise and sustainable use.//Agricultural Development and Research in the 21st Century. Beijing: China Environmental Science Press, pp. 406-414 (in Chinese) [叶恭银, 胡萃, 舒庆尧. 1998. 转基因抗虫水稻的转育及其合理持续利用.//世界农业发展与研究. 北京: 中国环境科学出版社, pp. 406-414]</div>
    <div class="csl-entry">Zeng SM, Wang PY, Wu XY, Zhang WY, Wang JQ, Song WZ, Wang SY. 1979. Preliminary study on the method of evaluation of horizontal resistance of wheat cultivars to stripe rust. Journal of Plant Protection, 6(1): 1-10 (in Chinese) [曾士迈, 王沛有, 武修英, 张万义, 王吉庆, 宋位中, 王生元, 郭予元. 1979. 小麦对条锈病的水平抗病性研究初报. 植物保护学报, 6(1): 1-10]</div>
    <div class="csl-entry">Zhang XB. 2013. Dpp-Omb信号以区域化的方式调控果蝇翅的生长. Ph.D Thesis. Beijing: China Agricultural University (in Chinese) [张徐波. 2013. Dpp-Omb信号以区域化的方式调控果蝇翅的生长. 博士毕业论文. 北京: 中国农业大学]</div>
  </div>
</blockquote>

**Comment by zepinglee** [comment]
目前关于双语的方案是：普通字段填入英文内容，并且在 `Extra` 中填写中文原文，比如：
```
original-author: 孙玉凤
original-author: 张永军
original-author: 陆宴辉
original-author: 吴孔明
original-title: 基于棉花挥发性物质的盲椿象可持续性防治
original-container-title: 植保科技创新与病虫防控专业化——中国植物保护学会2011年学术年会论文集
original-publisher-place: 北京
original-publisher: 中国农业科学技术出版社
```
详见 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA>。

这样有个缺点是，用户需要对每条中文文献新建英文条目。另一种方案是，普通字段填入中文内容，`Extra` 字段的 `original-` 填入英文翻译，这样就可以直接使用原来的英文条目，但是缺点是 `original-` 这些字段不太符合语义，毕竟英文是从中文原文翻译的。

@redleafnew 意见怎样？

**Comment by redleafnew** [comment]
挺好的，也没有其它办法了。
`original-container-title`在<https://docs.citationstyles.org/en/stable/specification.html>和<https://aurimasv.github.io/z2csl/typeMap.xml>搜索不到，csl还支持多少个这样的字段？
我记得还有`translated-...`，但上面也搜不到，难道是Jurism中支持的来着？

**Comment by redleafnew** [comment]
以后涉及到翻译的，可以用这个作为模板了。

**Comment by zepinglee** [comment]
> 挺好的，也没有其它办法了。 

> `original-container-title`在https://docs.citationstyles.org/en/stable/specification.html和https://aurimasv.github.io/z2csl/typeMap.xml搜索不到，csl还支持多少个这样的字段？ 

这是似乎是 citeproc-js 的后门，`Extra` 中形如 `key: value` 都可以被读取。

> 我记得还有`translated-...`，但上面也搜不到，难道是Jurism中支持的来着？

`translated-` 似乎还在 CSL v1.1 的讨论中 <https://github.com/citation-style-language/schema/issues/327>。

我试了一下 `translated-`，主要问题在于，`original-author` 被识别为姓名，多次出现可以表示多个作者。但是 citeproc-js 目前虽然可以读取 `translated-author`，但是没有把它当成姓名，所以无法表示多个作者。

**Comment by redleafnew** [comment]
那就先只能这样了。

**Comment by zepinglee** [comment]
> 那就先只能这样了。

那跟另一种方案相比你更倾向于哪种？

也就是在 `title` 中填写原中文标题，`original-title` 中填英文翻译。这样的好处在于用户可以直接在抓取的中文文献中填写，缺点是字段信息跟语义不太符合。

**Comment by redleafnew** [comment]
`translated-`能够解析我倾向于这种，意思更符合，但作者无法解析，就用`original-`的吧，在说明中写清楚就行。

**Comment by XK4959** [comment]
@zepinglee 我认为另一种方案是否更好一些？
title填写中文标题的话不仅可以保留原来的索引信息，方便其他的期刊（格式不要求翻译）引用；
而且似乎只用在最后手动添加英文题目？作者这些信息似乎可以自动翻译？这样会不会更加方便。

您说的缺点 字段信息与语义不太符合，我没有太理解。

我对这方面不是很了解，仅提供一些建议，具体看你们的来，十分感谢！

**Comment by zepinglee** [comment]
> `translated-`能够解析我倾向于这种，意思更符合，但作者无法解析，就用`original-`的吧，在说明中写清楚就行。

我的意思是 `title` 和 `original-title` 应该分别填中文信息还是英文。

目前是 `title` 填标题的英文翻译，`original-title` 填中文原文标题。另一种将将中文和英文的信息对调，`title` 填中文标题，`originla-title` 填英文翻译。

**Comment by XK4959** [comment]
好的 谢谢

**Comment by zepinglee** [comment]
还需要换一下 title 和 original-title在 2022年10月25日，10:58，Jarhan ***@***.***> 写道：﻿
好的 谢谢

**Comment by XK4959** [comment]
好的 十分感谢

**Comment by zepinglee** [comment]
89b250b 中将 `original-` 等字段改为填写英文翻译。

@XK4959 试一下 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/plant-protection/211journal-of-plant-protection.csl> 整体的效果？字段填写方式参考 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA>。

**Comment by redleafnew** [comment]
> original-title:

我没有理解你的意思，今天编写《营销科学学报》营销科学学报时才理解了。
我觉得用<code>title</code> 填中文标题，<code>originla-title</code> 填英文翻译，更方便，尽管从语义上相反。

因为如果另一种方式时，如果当前期刊不合适，改投其他不需要双语翻译的期刊，再调用title、author、container-title时就会发生错误的吧。

**Comment by zepinglee** [comment]
> 因为如果另一种方式时，如果当前期刊不合适，改投其他不需要双语翻译的期刊，再调用`title`、`author`、`container-title`时就会发生错误的吧。
> 
> 而且，还要把抓取得到的条目信息，如`作者`、`期刊题目`、`期刊名称`剪切到Extra中，而不如直接在Extra填写上翻译的作者等信息方便。

这种情况就需要新建一个条目，把英文信息填进去，投需要英文翻译的期刊时引用这个条目，投其他期刊时引用原条目。

确实这样处理起来比较麻烦。所以权衡之后我也赞成直接在 `original-` 中填翻译。

**Comment by redleafnew** [comment]
现在有个问题，就是最后一个作者之前的term，如果按原中文条目应该是“和”，按en应该是and，这个有办法解决吗？
只能生成这样？
`Jia J., Geng W., Xu G., Hao L.和Jia S.  ..... 贾建民、耿维、徐戈、郝辽钢和贾轼`

**Comment by zepinglee** [comment]
> 现在有个问题，就是最后一个作者之前的term，如果按原中文条目应该是“和”，按en应该是and，这个有办法解决吗？ 只能生成这样？ `Jia J., Geng W., Xu G., Hao L.和Jia S. ..... 贾建民、耿维、徐戈、郝辽钢和贾轼`

这个好像没法实现了……

**Comment by XK4959** [comment]
> [89b250b](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/89b250bf03b07608853028e1726497bb13d494bf)中将`original-`等换成英文翻译。
> 
> @XK4959重试一下https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/plant-protection/211journal-of-plant-protection.csl整体的效果？字段方式参考[https ://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA](https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA)。

经过测试，这个版本十分好用；
十分感谢两位的帮助！

**Comment by zepinglee** [comment]
好的，那我合并到主分支了。
