### ISSUE TITLE
希望能增加马克思主义研究等中文人文期刊的CSL

### ISSUE THREAD

**Issue by EroyalBoy** [redleafnew/Chinese-STD-GB-T-7714-related-csl#85]
**样式信息**

- 期刊名称：马克思主义研究
- ISSN 号：-ISSN 1006-5199
- 期刊官网：http://www.mkszyyj.net/
- 参考文献格式要求的链接：http://www.mkszyyj.net/Show/11787?itemid=47369

**Comment by EroyalBoy** [comment]
还有反馈一个点，这边提供的CSL在Pandoc语法转化这边，会出现重复两次的情况

**Comment by zepinglee** [comment]
将期刊的示例文献录入到 Zotero 群组 <https://www.zotero.org/groups/4677213/chinese_csl_development>。编辑群组中的内容需要 admin 权限，请在加入群组后提供 Zotero ID ，我们会提升你的权限。

> 还有反馈一个点，这边提供的CSL在Pandoc语法转化这边，会出现重复两次的情况

建议给出完整的具体示例复现问题。另外关于 pandoc 的 citeproc 引擎可能更适合发到 <https://github.com/jgm/citeproc> 讨论。

**Comment by EroyalBoy** [comment]
<img width="312" alt="CleanShot 2022-10-21 at 19 50 22@2x" src="https://user-images.githubusercontent.com/36374478/197189361-99179de2-ba05-4944-920b-d670be645f40.png">
如图所示，使用的是009gb-t-7714-2015-numeric-bilingual-no-uppercase-page-out

**Comment by redleafnew** [comment]
> **样式信息**
> 
> * 期刊名称：马克思主义研究
> * ISSN 号：-ISSN 1006-5199
> * 期刊官网：http://www.mkszyyj.net/
> * 参考文献格式要求的链接：http://www.mkszyyj.net/Show/11787?itemid=47369

这个期刊与https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl  或  https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl 中哪个最接近？

**Comment by EroyalBoy** [comment]
> > **样式信息**
> > 
> > * 期刊名称：马克思主义研究
> > * ISSN 号：-ISSN 1006-5199
> > * 期刊官网：http://www.mkszyyj.net/
> > * 参考文献格式要求的链接：http://www.mkszyyj.net/Show/11787?itemid=47369
> 
> 这个期刊与https://github.com/redleafnew/Chinese-std-GB-T-7714-related-csl 或 https://gitee.com/redleafnew00/Chinese-STD-GB-T-7714-related-csl 中哪个最接近？

我上面用的009可能比较接近。
文科的论文引用都以原著书籍为主，论文和著作的引用格式都不一样（具体还是建议看一下http://www.mkszyyj.net/Show/11787?itemid=47369），但是不要求参考文献当中有URL和dio，并且是脚注和尾注同时存在，上标是①这种，需要页码，后面的尾注是[1]这种，不需要页码

**Comment by redleafnew** [comment]
印象中①这种在正文中实现不了
https://forums.zotero.org/discussion/87328/is-it-possible-to-use-circled-numbers-in-csl/p1

**Comment by zepinglee** [comment]
> <img alt="CleanShot 2022-10-21 at 19 50 22@2x" width="312" src="https://user-images.githubusercontent.com/36374478/197189361-99179de2-ba05-4944-920b-d670be645f40.png">
> 
> 如图所示，使用的是009gb-t-7714-2015-numeric-bilingual-no-uppercase-page-out

这是是 pandoc 的 citeproc 没有实现 CSL-M 的 layout 功能（<https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension>），可以反馈给 <https://github.com/jgm/citeproc/issues>。

**Comment by zepinglee** [comment]
> 印象中①这种在正文中实现不了 https://forums.zotero.org/discussion/87328/is-it-possible-to-use-circled-numbers-in-csl/p1
> 
> 文末参考文献列表和009也差得挺多的，note类的编写我不大熟悉。
> 
> @zepinglee 有兴趣搞吗？

只要不是出现在注释内容中（比如“同前注 ①”）就可以实现。

我周末写一下这个吧。

**Comment by EroyalBoy** [comment]
> > 我上面用的009可能比较接近。 文科的论文引用都以原著书籍为主，论文和著作的引用格式都不一样，具体还是建议看一下http://www.mkszyyj.net/Show/11787?itemid=47369
> 
> 需要将其中的文献录入 Zotero 群组。

加入了，ID：zephyrchina

**Comment by zepinglee** [comment]
@EroyalBoy <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/XQC8NVJZ> 只录入了一篇文献？

<img width="743" alt="Screen Shot 2022-10-23 at 20 51 45" src="https://user-images.githubusercontent.com/12290822/197393171-2931439a-b456-45ec-8a58-45982abd25d3.png">

需要将 <http://www.mkszyyj.net/Show/11787?itemid=47369> 的文献都录入 Zotero 群组。

**Comment by EroyalBoy** [comment]
> @EroyalBoy https://www.zotero.org/groups/4677213/chinese_csl_development/collections/XQC8NVJZ 只录入了一篇文献？
> 
> <img alt="Screen Shot 2022-10-23 at 20 51 45" width="743" src="https://user-images.githubusercontent.com/12290822/197393171-2931439a-b456-45ec-8a58-45982abd25d3.png">
> 
> 需要将 http://www.mkszyyj.net/Show/11787?itemid=47369 的文献都录入 Zotero 群组。

是指他列出的各种资料都要放在这里吗？还是说再丰富几篇发表在他们期刊上的论文？

**Comment by redleafnew** [comment]
最好将期刊样式要求中的举例的各种类型都放上方便对照。

**Comment by zepinglee** [comment]
> 是指他列出的各种资料都要放在这里吗？

对，这样方便我们跟官网的体例进行对比，不容易出 bug。参考 #84 讨论的《植物保护学报》（<http://www.zwbhxb.com.cn/ch/first_menu.aspx?parent_id=20081122190830001>）以及录入的文献 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA>。

另外，<http://www.mkszyyj.net/Show/11787?itemid=47369> 的体例似乎无法直接复制。我使用 javascript 工具将其提取出来：

```
体例规范
                
《马克思主义研究》的编辑体例采用脚注和参考文献两种方式：（1）论文所引文献的出处，以及对文中内容作说明的文字，均放在脚注中，脚注标在被引用和说明内容的右上角，序号为①②③……，每页重新编号；（2）参考文献放在正文后面，序号为[1][2][3]……，具体格式参照脚注格式，无需标注页码。此外，文章标题的注释采用星号（*）标注。具体注释格式如下：一、中文注释1. 著作主要责任者：《著作名》，出版地：出版者，出版年，引文页码。对于编著的著作，主要责任者名字后须加“编”或“主编”的字样。例如：《马克思恩格斯选集》第2卷，北京：人民出版社，1995 年，第22、178页。《邓小平文选》第3卷，北京：人民出版社，1993年，第232－235页。孙冶方：《社会主义经济的若干理论问题》，北京：人民出版社，1979年，第70、76-77页。逄先知、金冲及主编：《毛泽东传1949-1976》,北京：中央文献出版社，2003年，第1032页。2. 译著〔国别〕主要责任者：《中文著作名》，翻译者译，出版地：出版者，出版年，引文页码。如翻译者为3人或以上，请采用“第一名翻译者等译”的省略形式。例如：〔德〕黑格尔：《逻辑学》（下），杨一之译，北京：商务印书馆，1976年，第427-428页。〔美〕塞缪尔•亨廷顿：《文明的冲突与世界秩序的重建》，周琪等译，北京：新华出版社，2002年，第56页。3. 期刊主要责任者：《文章篇名》，《期刊名》XXXX年第X期。例如：任平：《马克思“反思的问题视域”及其当代意义》，《中国社会科学》2006年第6期。4. 报纸主要责任者：《文章篇名》，《报纸名》XXXX年X月X日。例如：周扬:《三次伟大的思想解放运动》,《人民日报》1979年5月7日。5. 析出文献析出文献主要责任者：《析出文章篇名》，文献主要责任者：《著作名》，出版地：出版者，出版年，析出文献页码。例如：〔英〕特里·伊格尔顿：《文化之战》，王宁编：《全球化与文化：西方与中国》，北京：北京大学出版社，2002年，第145、148页。6. 网络文献主要责任者：《文章篇名》，网址。例如:郑易生：《论中国环境与经济至上主义》，http://www.net.cn/12/2/2006-12-05/3765.html.二、英文注释1. 著作主要责任者，书名(斜体，主体词首字母大写)，出版地：出版者，出版年，引文页码。例如：Stalin, J., Problems of Leninism, Moscow: Foreign Languages Publishing House, 1947, p. 356.2. 期刊主要责任者，“文章名”，刊物名(斜体)，卷期号，出版年。 例如： H. Leibenstein, “Allocative Efficiency vs. X-Efficiency”, American Economic Review, Vol.56，No.3, 1966.3. 析出文献析出文献主要责任者，“文章名”，文献主要责任者，文集名(斜体)，出版地：出版者，出版年，析出文献页码。三、俄文注释1. 著作作者姓 作者名和父称（可缩写，斜体） 空格 著作名.出版社，出版年代.页码.如多个作者，则作者之间用“,”连接。例如：Мартов Ю.О. Избранное. М., 2000. С. 66.2. 论文①发表在刊物中的论文作者姓 作者名和父称（可缩写，斜体） 空格 论文名//刊物名.出版年代.期号.页码.例如：Львов Д. С. Крест над Россией // Поиск. 19 апреля 2002 г.②发表在著作中的论文作者姓 作者名和父称（可缩写，斜体） 空格 论文名//著作名.出版社，出版年代.页码.例如：Картунова А. И. Коминтерн и некоторые вопросы реорганизации Гоминьдана // Коминтерн и Восток. М., 1969. С.233-235.
```

**Comment by EroyalBoy** [comment]
[20220620052219WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847978/20220620052219WU_FILE_0.pdf)
[20220630124457WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847979/20220630124457WU_FILE_0.pdf)
[0j1szksl.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847980/0j1szksl.pdf)
我找了这三篇，不知道够不够

**Comment by EroyalBoy** [comment]
> [20220620052219WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847978/20220620052219WU_FILE_0.pdf) [20220630124457WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847979/20220630124457WU_FILE_0.pdf) [0j1szksl.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847980/0j1szksl.pdf) 我找了这三篇，不知道够不够

我本地把文件拖到群组，好像zotero不支持……

**Comment by zepinglee** [comment]
> [20220620052219WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847978/20220620052219WU_FILE_0.pdf) [20220630124457WU_FILE_0.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847979/20220630124457WU_FILE_0.pdf) [0j1szksl.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9847980/0j1szksl.pdf) 我找了这三篇，不知道够不够

公开的群组不支持 PDF 附件。但是这里不是找文章的 PDF，主要是录入各个字段的信息。

比如《植物保护学报》（<http://www.zwbhxb.com.cn/ch/first_menu.aspx?parent_id=20081122190830001>）的示例中有 11 篇文献，就将这 11 篇的内容录入 `Zotero`（<https://www.zotero.org/groups/4677213/chinese_csl_development/collections/H9TE7BLA>）。

<img width="723" alt="Screen Shot 2022-10-24 at 08 58 10" src="https://user-images.githubusercontent.com/12290822/197428071-5b816ed7-dc51-43de-a290-25a10c698d6c.png">

**Comment by EroyalBoy** [comment]
已经加入了常用的几篇

**Comment by zepinglee** [comment]
> 已经加入了常用的几篇

只有两篇是期刊官网的示例，能把全部示例文献录进去吗？这主要是为了方便对比测试。

**Comment by EroyalBoy** [comment]
> http://www.net.cn/12/2/2006-12-05/3765.html

OK，我尽力了已经再找了几篇，俄文的和外文的，不好意思，我没有找到……

**Comment by zepinglee** [comment]
手动录入。

**Comment by zepinglee** [comment]
[studies-of-marxism](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/studies-of-marxism) 分支新增了样式 [213studies-of-marxism.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/studies-of-marxism/213studies-of-marxism.csl)，不过只在这四篇官方的文献上进行了测试，其余类型等录入官方示例后再继续。

<img width="680" alt="Screen Shot 2022-10-31 at 19 32 06" src="https://user-images.githubusercontent.com/12290822/198998475-8b2a62fd-3f79-4dc8-a1b1-f6a9020fe6ba.png">

显示效果：

<blockquote>
  <sup>1</sup> 《马克思恩格斯选集》第2卷，北京：人民出版社，1995年，第22、178页。<br>
  <sup>2</sup> 逄先知、金冲及主编：《毛泽东传》，2003年，第1032页。<br>
  <sup>3</sup> [德]黑格尔：《逻辑学》（上卷），杨一之译，商务印书馆，2001年，第427-428页。<br>
  <sup>4</sup> 任平：《马克思“反思的问题视域”及其当代意义》，《中国社会科学》2006年第6期。<br>
</blockquote>

<blockquote>
  <div class="csl-bib-body">
    <div class="csl-entry">[1] 《马克思恩格斯选集》第2卷，北京：人民出版社，1995年。</div>
    <div class="csl-entry">[2] 逄先知、金冲及主编：《毛泽东传》，2003年。</div>
    <div class="csl-entry">[3] [德]黑格尔：《逻辑学》（上卷），杨一之译，商务印书馆，2001年。</div>
    <div class="csl-entry">[4] 任平：《马克思“反思的问题视域”及其当代意义》，《中国社会科学》2006年第6期。</div>
  </div>
</blockquote>

**Comment by EroyalBoy** [comment]
> [studies-of-marxism](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/tree/studies-of-marxism) 分支新增了样式 [213studies-of-marxism.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/studies-of-marxism/213studies-of-marxism.csl)，不过只在这四篇官方的文献上进行了测试，其余类型等录入官方示例后再继续。
> 
> <img alt="Screen Shot 2022-10-31 at 19 32 06" width="680" src="https://user-images.githubusercontent.com/12290822/198998475-8b2a62fd-3f79-4dc8-a1b1-f6a9020fe6ba.png">
> 
> 显示效果：
> 
> > 1 《马克思恩格斯选集》第2卷，北京：人民出版社，1995年，第22、178页。
> >   2 逄先知、金冲及主编：《毛泽东传》，2003年，第1032页。
> >   3 [德]黑格尔：《逻辑学》（上卷），杨一之译，商务印书馆，2001年，第427-428页。
> >   4 任平：《马克思“反思的问题视域”及其当代意义》，《中国社会科学》2006年第6期。
> 
> > [1] 《马克思恩格斯选集》第2卷，北京：人民出版社，1995年。
> >     [2] 逄先知、金冲及主编：《毛泽东传》，2003年。
> >     [3] [德]黑格尔：《逻辑学》（上卷），杨一之译，商务印书馆，2001年。
> >     [4] 任平：《马克思“反思的问题视域”及其当代意义》，《中国社会科学》2006年第6期。

感谢！！！

**Comment by zepinglee** [comment]
已合并到主分枝。
