### ISSUE TITLE
样式请求：中国农业科学院硕博论文

### ISSUE THREAD

**Issue by butsnow** [redleafnew/Chinese-STD-GB-T-7714-related-csl#86]
您好！十分感谢您提供许多CSL样式，由于各校学位论文格式要求详细且不同，如果您近期有空能帮忙改下格式就太感谢啦！

_与已有的哪个 CSL 样式最接近？_
001gb-t-7714-2015-author-date-bilingual.csl

_与上一条格式的主要区别：_
1. 正文引用文献处为圆括号（中文括号非英文括号）；欧美著者只标注第一个著者的姓，且全大写
2. 文后参考文献重新排序：按著者字顺和出版年排序，中文文献在前，一般按汉语拼音升序排序，英文文献在后，按字母升序排序（即与原文引用顺序不同，不确定这个能否实现，如果不能就请忽略这条）
3. 文后参考文献--**期刊格式**：列出全部作者，汉语拼音书写或欧美著者人名，姓全大写，名缩写，如SU D P，CALMS R B。去除文献类型标识（如[J]、[D]等），去除URL，在最后列出DOI号
4. 文后参考文献--**学位论文格式**：作者, 年份. 标题. 大学. 
5. 文后参考文献--**图书格式**：全部作者, 年份. 书名. 出版地: 出版者: 页码-页码. 
6. **文后参考文献首行顶格书写，其余行缩进2个英文字符**。（汉字采用宋体、五号，英文采用Times New Roman、五号，行距18磅，段前、段后间距各0行。标点符号统一使用英文半角，后空1个英文字符）

_示例：_
1. 中文期刊：李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(09): 311-316. DOI: 10.13386/j.issn1002-03 06.2016.09.052.
2. 外文期刊：ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon- contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9). DOI: 10.1007/s41365-017-0274-z.
3. 中文学位论文：沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
4. 外文学位论文：CALMS R B, 1965. Infrared spectroscopic studies on solid oxygcn. Berkeley: Univ.of Califor¬nia:20. 
5. 中文图书：徐洪杰, 2015. 上海光源首批线站设计与研制. 上海: 上海科学技术出版社: 20-21.
6. 外文图书：WANG Z L, LIU Y, ZHANG Z, 2003. Handbook of Nanophase and Nanostructured Materials. Dordrecht: Kluwer Academic Publishers. DOI: 10.1007/0-387-23814-X.

_已加入Zotero群组~_
Zotero ID: snowonly

**Comment by redleafnew** [comment]
有样式要求的网址吗？

> 正文引用文献处为圆括号（中文括号非英文括号）；欧美著者只标注第一个著者的姓，且全大写
有例子吗？

> 文后参考文献重新排序：按著者字顺和出版年排序，中文文献在前，一般按汉语拼音升序排序，英文文献在后，按字母升序排序（即与原文引用顺序不同，不确定这个能否实现，如果不能就请忽略这条）
可以

> 
文后参考文献首行顶格书写，其余行缩进2个英文字符。（汉字采用宋体、五号，英文采用Times New Roman、五号，行距18磅，段前、段后间距各0行。标点符号统一使用英文半角，后空1个英文字符）
通过Word的书目样式实现。

**Comment by butsnow** [comment]
> 有样式要求的网址吗？
> 
参考文献样式要求学校暂时没有上传到网上，是直接下发的Word写作模板


> 有例子吗？
>
> >正文引用文献处为圆括号（中文括号非英文括号）；欧美著者只标注第一个著者的姓，且全大写
>
这个应该是标点符号全角和半角的区别。正确的是（张三 等, 2019）（STIEG et al., 2019），错误的是(张三 等, 2019)

**Comment by redleafnew** [comment]
> > 有样式要求的网址吗？
> 
> 参考文献样式要求学校暂时没有上传到网上，是直接下发的Word写作模板
> 
> > 有例子吗？
> > > 正文引用文献处为圆括号（中文括号非英文括号）；欧美著者只标注第一个著者的姓，且全大写
> 
> 这个应该是标点符号全角和半角的区别。正确的是（张三 等, 2019）（STIEG et al., 2019），错误的是(张三 等, 2019)

中文和英文的都是全角的括号是吧？如（STIEG et al., 2019）

@zepinglee  开通权限后，将上面的例子录入到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by butsnow** [comment]
> 中文和英文的都是全角的括号是吧？如（STIEG et al., 2019）
> 
> 农科院各个所的要求相同吗？
> 
嗯嗯是的，正文里引用文献的括号都是全角，文后参考文献符号是半角
格式也都是统一的，所有硕博生、不分学专硕

> @zepinglee 开通权限后，将上面的例子录入到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development
>
我想问一下是在Zotero-group library-学位论文-creat bibliography这里录入吗

**Comment by zepinglee** [comment]
<img width="903" alt="Screen Shot 2022-10-24 at 21 21 36" src="https://user-images.githubusercontent.com/12290822/197535663-8125f663-2dfd-4de2-9b60-9bbf588ce97b.png">

已修改权限。

**Comment by redleafnew** [comment]
> > 中文和英文的都是全角的括号是吧？如（STIEG et al., 2019）
> > 农科院各个所的要求相同吗？
> 
> 嗯嗯是的，正文里引用文献的括号都是全角，文后参考文献符号是半角 格式也都是统一的，所有硕博生、不分学专硕
> 
> > @zepinglee 开通权限后，将上面的例子录入到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development
> 
> 我想问一下是在Zotero-group library-学位论文-creat bibliography这里录入吗

建一个农科院的目录吧。

**Comment by zepinglee** [comment]
> > 有样式要求的网址吗？
> 
> 参考文献样式要求学校暂时没有上传到网上，是直接下发的Word写作模板

那给个“中国农业科学院”官网的链接？

**Comment by butsnow** [comment]
具体的格式要求在这里~官网上没有hhhh
[样式请求：中国农业科学院研究生学位论文写作模板.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9852085/default.pdf)

**Comment by redleafnew** [comment]
> 具体的格式要求在这里~官网上没有hhhh [样式请求：中国农业科学院研究生学位论文写作模板.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9852085/default.pdf)

@zepinglee 要的中国农科院的官网地址。类似www.cas.ac.cn之类的。

**Comment by butsnow** [comment]
> > 具体的格式要求在这里~官网上没有hhhh [样式请求：中国农业科学院研究生学位论文写作模板.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9852085/default.pdf)
> 
> @zepinglee 要的中国农科院的官网地址。类似www.cas.ac.cn之类的。

https://gs.caas.cn/index.htm

**Comment by redleafnew** [comment]
https://gs.caas.cn/xwxk/xwsy/227175.htm 是农科院的要求吗？和你上传的一样吗？

**Comment by butsnow** [comment]
嗯嗯是的！更新到202209版，我刚刚传的PDF就是把这两个文件中关于参考文献部分单独摘出来了

**Comment by redleafnew** [comment]
那就用这个网址了，写入到csl中。

**Comment by redleafnew** [comment]
上面的条目录入到群组后我有时间了修改一下。

**Comment by butsnow** [comment]
OKOK终于录入到群组里了

**Comment by zepinglee** [comment]
> OKOK终于录入到群组里了

最好将官方的示例录入到“中国农业科学院”这个 collection，方便我们进行对比测试。

<img width="688" alt="Screen Shot 2022-10-24 at 23 18 47" src="https://user-images.githubusercontent.com/12290822/197563053-110fbe8d-3bf6-4fae-8f89-73150b4e8729.png">

**Comment by butsnow** [comment]
已增加文献录入
有一些标准类（GB）Zotero没有对应的类型，暂时放在了图书章节下

**Comment by redleafnew** [comment]
-  [ ] 正文引用文献处为圆括号（中文括号非英文括号）；欧美著者只标注第一个著者的姓，且全大写
文后参考文献重新排序：按著者字顺和出版年排序，中文文献在前，一般按汉语拼音升序排序，英文文献在后，按字母升序排序
文后参考文献--期刊格式：列出全部作者，汉语拼音书写或欧美著者人名，姓全大写，名缩写，如SU D P，CALMS R B。去除文献类型标识（如[J]、[D]等），去除URL，在最后列出DOI号
文后参考文献--学位论文格式：作者, 年份. 标题. 大学.
文后参考文献--图书格式：全部作者, 年份. 书名. 出版地: 出版者: 页码-页码.

**Comment by redleafnew** [comment]
> 外文学位论文：CALMS R B, 1965. Infrared spectroscopic studies on solid oxygcn. Berkeley: Univ.of Califor¬nia:20.

nia:20.是什么，字段中没有。

> WANG Z L, LIU Y, ZHANG Z, 2003. Handbook of Nanophase and Nanostructured Materials. Dordrecht: Kluwer Academic Publishers. DOI: 10.1007/0-387-23814-X.
字段中没有DOI，需要将DOI填入到Extra中，DOI: 10.1007/0-387-23814-X
需要将书籍名称自己在Zotero调整为Title（词首字母大写格式）

**Comment by redleafnew** [comment]
当前显示效果：

> （李泽仟 等, 2016）
> （沈寿国, 2004）
> （邓一刚, 2006）
> （ZHANG et al., 2017）
> （ZHANG et al., 2017）
> （王临惠 等, 2010）
> （WANG, 2003）
> （霍斯尼, 1989）
> （DES MARAIS et al., 1992）
> （CAIRNS, 1965）
> 沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
> 邓一刚, 2006. 全智能节电器: 200610171314.3. 2006.
> 霍斯尼, 1989. 谷物科学与工艺学原理. 李庆龙, 译. 2 版. 北京: 中国食品出版社: 15-20.
> 李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI:10.13386/j.issn1002-0306.2016.09.052.
> 王临惠, 支建刚, 王忠一, 2010. 天津方言的源流关系刍议. 山西师大学报(社会科学版), 37(4): 147-151.
> CAIRNS B R, 1965. Infrared spectroscopic studies of solid oxygen. Berkeley: Univ. of California.
> DES MARAIS D J, STRAUSS H, SUMMONS R E, OTHERS, 1992. Carbon isotope evidence for the stepwise oxidation of the proterozoic environment. Nature, 359: 605-609. DOI:10.1038/359605a0.
> WANG Z L, 2003. Handbook of Nanophase and Nanostructured Materials. New York: Kluwer Academic/Plenum [u.a.]. DOI:10.1007/0-387-23814-X.
> ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon-contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9): 127. DOI:10.1007/s41365-017-0274-z.

**Comment by butsnow** [comment]
超级感谢！
部分格式如果能通过Zotero更改的话我也认为应该直接改，自动导入的题录信息如果有错误后期我再校对

> > 邓一刚, 2006. 全智能节电器: 200610171314.3. 2006.
> 
这个专利最后的2006是字段中包含了申请日期、公告日期两个日期的问题吗
如果是字段问题的话那我就在Zotero里删掉一个日期

> > 外文学位论文：CALMS R B, 1965. Infrared spectroscopic studies on solid oxygcn. Berkeley: Univ.of Califor¬nia:20.
> 
> nia:20.是什么，字段中没有。
>
这个应该是学校那边字段错了，自动生成的Univ. of California是对的

> > 李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI:10.13386/j.issn1002-0306.2016.09.052.
> > DES MARAIS D J, STRAUSS H, SUMMONS R E, OTHERS, 1992. Carbon isotope evidence for the stepwise oxidation of the proterozoic environment. Nature, 359: 605-609. DOI:10.1038/359605a0.
> > WANG Z L, 2003. Handbook of Nanophase and Nanostructured Materials. New York: Kluwer Academic/Plenum [u.a.]. DOI:10.1007/0-387-23814-X.
> > ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon-contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9): 127. DOI:10.1007/s41365-017-0274-z.
 >
中文及外文期刊的DOI冒号后面可以再加一个半角空格吗

**Comment by redleafnew** [comment]
> 中文及外文期刊的DOI冒号后面可以再加一个半角空格吗

已添加。

> 这个专利最后的2006是字段中包含了申请日期、公告日期两个日期的问题吗
> 如果是字段问题的话那我就在Zotero里删掉一个日期

专利没有显示效果，需要提供例子显示效果。

当前显示效果，
书籍不用在Zotero修改大小写了。
需要将英文条目语言改为en-US，中文改为zh-CN

> （李泽仟 等, 2016）
> （沈寿国, 2004）
> （邓一刚, 2006）
> （ZHANG et al., 2017）
> （王临惠 等, 2010）
> （WANG, 2003）
> （霍斯尼, 1989）
> （DES MARAIS et al., 1992）
> （CAIRNS, 1965）
> 李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI: 10.13386/j.issn1002-0306.2016.09.052.
> 沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
> 王临惠, 支建刚, 王忠一, 2010. 天津方言的源流关系刍议. 山西师大学报(社会科学版), 37(4): 147-151.
> 邓一刚, 2006. 全智能节电器: 200610171314.3. 2006.
> 霍斯尼, 1989. 谷物科学与工艺学原理. 李庆龙, 译. 2 版. 北京: 中国食品出版社: 15-20.
> CAIRNS B R, 1965. Infrared spectroscopic studies of solid oxygen. Berkeley: Univ. of California.
> DES MARAIS D J, STRAUSS H, SUMMONS R E, HAYES J M, 1992. Carbon isotope evidence for the stepwise oxidation of the proterozoic environment. Nature, 359(6396): 605-609. DOI: 10.1038/359605a0.
> WANG Z L, 2003. Handbook of Nanophase and Nanostructured Materials. New York: Kluwer Academic/Plenum [u.a.]. DOI: 10.1007/0-387-23814-X.
> ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon-contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9): 127. DOI: 10.1007/s41365-017-0274-z.

**Comment by zepinglee** [comment]
我将《写作规范》官方的示例挪到“中国农业科学院”目录下了。

<img width="878" alt="Screen Shot 2022-10-25 at 12 00 15" src="https://user-images.githubusercontent.com/12290822/197679931-5ee075b4-c385-4feb-adfc-27e22cfdac35.png">

> 这个专利最后的2006是字段中包含了申请日期、公告日期两个日期的问题吗

后面的申请日期是多余的。

**Comment by zepinglee** [comment]
另外“专利”的“国别“应该填在 `Place` 字段，`Country` 目前没有映射到 CSL 的字段，见 <https://aurimasv.github.io/z2csl/typeMap.xml#map-patent>。

**Comment by butsnow** [comment]
专利格式：邓一刚, 2006. 全智能节电器: 200610171314.3.
文段里申请日期已删除，国别已更改至地点（Place）
全部文献语言格式已相应设置

>李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI: 10.13386/j.issn1002-0306.2016.09.052.
>沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
>王临惠, 支建刚, 王忠一, 2010. 天津方言的源流关系刍议. 山西师大学报(社会科学版), 37(4): 147-151.
>邓一刚, 2006. 全智能节电器: 200610171314.3. 2006.
>霍斯尼, 1989. 谷物科学与工艺学原理. 李庆龙, 译. 2 版. 北京: 中国食品出版社: 15-20.

文后参考文献顺序会根据自动拼音字母更改吗
“沈”是不是因为多音字“chen”所以顺序不对，如果是单独情况不好调整的话，后续我可以手动更改
除此之外应该没有其他问题啦，感谢两位！

**Comment by redleafnew** [comment]
> 专利格式：邓一刚, 2006. 全智能节电器: 200610171314.3.

已修改。

> “沈”是不是因为多音字“chen”所以顺序不对

确实是多音字，
https://baike.baidu.com/item/%E6%B2%88/35776
应该解决不了，类似的还有“曾”

现在显示效果，如无问题则上传到仓库了。

> （李泽仟 等, 2016）
> （沈寿国, 2004）
> （邓一刚, 2006）
> （ZHANG et al., 2017）
> （王临惠 等, 2010）
> （WANG, 2003）
> （霍斯尼, 1989）
> （DES MARAIS et al., 1992）
> （CAIRNS, 1965）
> 李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI: 10.13386/j.issn1002-0306.2016.09.052.
> 沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
> 王临惠, 支建刚, 王忠一, 2010. 天津方言的源流关系刍议. 山西师大学报(社会科学版), 37(4): 147-151.
> 邓一刚, 2006. 全智能节电器: 200610171314.3.
> 霍斯尼, 1989. 谷物科学与工艺学原理. 李庆龙, 译. 2 版. 北京: 中国食品出版社: 15-20.
> WANG Z L, 2003. Handbook of Nanophase and Nanostructured Materials. New York: Kluwer Academic/Plenum [u.a.]. DOI: 10.1007/0-387-23814-X.
> ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon-contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9): 127. DOI: 10.1007/s41365-017-0274-z.
> CAIRNS B R, 1965. Infrared spectroscopic studies of solid oxygen. Berkeley: Univ. of California.
> DES MARAIS D J, STRAUSS H, SUMMONS R E, HAYES J M, 1992. Carbon isotope evidence for the stepwise oxidation of the proterozoic environment. Nature, 359(6396): 605-609. DOI: 10.1038/359605a0.

**Comment by butsnow** [comment]
> 现在显示效果，如无问题则上传到仓库了。
> 
> > （李泽仟 等, 2016）
> > （沈寿国, 2004）
> > （邓一刚, 2006）
> > （ZHANG et al., 2017）
> > （王临惠 等, 2010）
> > （WANG, 2003）
> > （霍斯尼, 1989）
> > （DES MARAIS et al., 1992）
> > （CAIRNS, 1965）
> > 李泽仟, 顾欢, 康乐, 张亚, 宋焕禄, 2016. 当归中关键气味活性化合物的鉴定及其在煎煮过程中变化规律研究. 食品工业科技, 37(9): 311-316. DOI: 10.13386/j.issn1002-0306.2016.09.052.
> > 沈寿国, 2004. 蛇床子素抑制植物病原真菌机制的初步研究. 南京农业大学.
> > 王临惠, 支建刚, 王忠一, 2010. 天津方言的源流关系刍议. 山西师大学报(社会科学版), 37(4): 147-151.
> > 邓一刚, 2006. 全智能节电器: 200610171314.3.
> > 霍斯尼, 1989. 谷物科学与工艺学原理. 李庆龙, 译. 2 版. 北京: 中国食品出版社: 15-20.
> > WANG Z L, 2003. Handbook of Nanophase and Nanostructured Materials. New York: Kluwer Academic/Plenum [u.a.]. DOI: 10.1007/0-387-23814-X.
> > ZHANG Y F, LUO H X, GUO Z, ZHEN X J, CHEN M, LIU J N, 2017. Cleaning of carbon-contaminated optics using O2/Ar plasma. Nuclear Science and Techniques, 28(9): 127. DOI: 10.1007/s41365-017-0274-z.
> > CAIRNS B R, 1965. Infrared spectroscopic studies of solid oxygen. Berkeley: Univ. of California.
> > DES MARAIS D J, STRAUSS H, SUMMONS R E, HAYES J M, 1992. Carbon isotope evidence for the stepwise oxidation of the proterozoic environment. Nature, 359(6396): 605-609. DOI: 10.1038/359605a0.

实际应用的时候这个顺序会自动变化嘛
如果可以的话就没有问题啦

**Comment by redleafnew** [comment]
什么顺序？

**Comment by butsnow** [comment]
> 什么顺序？

按著者字顺和出版年排序
中文文献在前，按汉语拼音升序排序，英文文献在后，按字母升序排序

**Comment by redleafnew** [comment]
已上传，试一下：
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/422caas-thesis.csl

**Comment by redleafnew** [comment]
关于多音字的姓氏，有办法解决吗？
如曾在姓名中读Zeng，但csl排序中以Ceng排。
@zepinglee

**Comment by redleafnew** [comment]
https://github.com/citation-style-language/styles/issues/5526
@fredericky123 问过，但无解决方案。

**Comment by zepinglee** [comment]
这个得改 JavaScript 底层关于排序的处理，大概是 UCA 和 CLDR 相关的东西。（https://www.cnblogs.com/huahuahu/p/unicode-zi-fu-chuan-pai-xu-gui-ze-yi-ru-he-que-din.html <https://www.cnblogs.com/huahuahu/p/unicode-zi-fu-chuan-pai-xu-gui-ze-yi-ru-he-que-din.html>）

**Comment by redleafnew** [comment]
那算了，少量的手动修改吧。

**Comment by butsnow** [comment]
OKOK试了一下超级好用！
感谢两位大佬的帮助~
一定给同学们大力安利！

**Comment by redleafnew** [comment]
书籍名称的大小写为什么只能在这进行设置？
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L280-L282
```
                <choose>
                    <if type="book chapter" match="any">
                        <text variable="title" text-case="title"/>
                    </if>
                    <else>
                        <text variable="title"/>
                    </else>
                </choose>
```

在https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L333下面的title macro 中修改了不起作用？
 `           <text macro="title"/>`

**Comment by zepinglee** [comment]
> 书籍名称的大小写为什么只能在这进行设置？
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L280-L282
> 
> 在
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L333
> 
> 下面的title macro 中修改了不起作用？
> 
> @zepinglee

是的，见 <https://github.com/citation-style-language/schema/issues/417>。

**Comment by zepinglee** [comment]
@butsnow 另外提醒一下 `language` 字段填的是 `zh-CN` 不是 `zh_CN`。

**Comment by redleafnew** [comment]
> > 书籍名称的大小写为什么只能在这进行设置？
> > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L280-L282
> > 
> > 在
> > https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/498eefbeab614ab029d74a65e5b5226f682733b5/422caas-thesis.csl#L333
> > 
> > 下面的title macro 中修改了不起作用？
> > @zepinglee
> 
> 是的，见 [citation-style-language/schema#417](https://github.com/citation-style-language/schema/issues/417)。

我以为我搞错了，那只能用这种不优雅的方式设置了。

**Comment by redleafnew** [comment]
无其他问题关闭了。

**Comment by zepinglee** [comment]
@butsnow 不要修改其他 collection 的字段！

<img width="334" alt="Screen Shot 2022-11-02 at 14 06 18" src="https://user-images.githubusercontent.com/12290822/199411144-e99aa0b2-70d5-42a2-92db-aa363fed7efe.png">


我再重复一遍，语言字段是 `zh-CN` 不是 `zh_CN`！

**Comment by butsnow** [comment]
@zepinglee 
首先，这个条目不是我上传的
其次，今天上午我也没更改这个条目信息
最后，知网文件上传后默认格式就是`zh_CN`

**Comment by zepinglee** [comment]
> @zepinglee 首先，这个条目不是我上传的 其次，今天上午我也没更改这个条目信息 最后，知网文件上传后默认格式就是`zh_CN`

可能是你的插件自动修改的。

这里显示的 Modified by 都是你的 id。比如 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/Q4RMB2JN/items/D4IDG79Q/collection>

<img width="338" alt="Screen Shot 2022-11-02 at 14 34 56" src="https://user-images.githubusercontent.com/12290822/199416220-b2928373-5c00-4b0a-8c21-cc9bb1ecbe60.png">

还有 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/Y7Z6YG2V/items/DD3UUKRP/collection>

<img width="323" alt="Screen Shot 2022-11-02 at 14 32 27" src="https://user-images.githubusercontent.com/12290822/199415305-62126852-eb0a-454f-97a7-acd69ba44254.png">

**Comment by butsnow** [comment]
@zepinglee 
我看到Modified ID了....
实际上不是我主观意愿想改的，应该是插件自动改的
希望你有批量修改语言的插件，这样会方便一点

**Comment by zepinglee** [comment]
> @zepinglee 我看到Modified ID了.... 实际上不是我主观意愿想改的，应该是插件自动改的 希望你有批量修改语言的插件，这样会方便一点

你都用了哪些插件（以及版本号）？我收集一下信息向插件作者反馈。

**Comment by butsnow** [comment]
> 你都用了哪些插件（以及版本号）？我收集一下信息向插件作者反馈。
> 
刚刚查了一下，应该是茉莉花（0.2.0）改的
设置里默认中文语言就是`zh_CN`，需要手动改为`zh-CN`

**Comment by zepinglee** [comment]
> > 你都用了哪些插件（以及版本号）？我收集一下信息向插件作者反馈。
> 
> 刚刚查了一下，应该是茉莉花（0.2.0）改的 设置里默认中文语言就是`zh_CN`，需要手动改为`zh-CN`

你是勾上了“中文条目时自动设置语言”选项并且在“默认中文语言(选择或输入)”设置了“zh_CN”吗？这个条目应该是导入知网的文献时才触发，不应该自动修改其他 collection 中的字段信息呀。
