### ISSUE TITLE
营销科学学报格式请求

### ISSUE THREAD

**Issue by chujiuzz** [redleafnew/Chinese-STD-GB-T-7714-related-csl#87]
**样式信息**

- 期刊名称：营销科学学报

- 期刊英文名：Journal of Marketing Science

- ISSN 号：2097-0099

- 期刊官网：http://www.jms.org.cn:8081/jms/CN/jms/home.shtml

- 参考文献格式要求的链接：<http://www.jms.org.cn:8081/jms/fileup/jms/ITEM/20220923110330.pdf>

**测试条目**

将期刊格式要求的示例文献录入 Zotero 群组“[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)”，用于测试、比对 CSL 样式的输出结果。

Zotero ID: limeranceZZZZ

**其他样式信息**在204的基础上将作者的姓氏改为大写全拼，名字用首字母大写

**Comment by chujiuzz** [comment]
在204的基础上将姓氏改为全拼大写，名字为只有首字母且大写

**Comment by chujiuzz** [comment]
![image](https://user-images.githubusercontent.com/105706562/198823397-5265cdba-f928-4e60-af8d-bccc099151fb.png)

**Comment by redleafnew** [comment]
请详细列出与204的区别

**Comment by chujiuzz** [comment]
![111](https://user-images.githubusercontent.com/105706562/198824475-0d5ddaec-1509-4452-b68e-535bfbbee776.png)

示例如下，中文的翻译后需要加in chinese
![222](https://user-images.githubusercontent.com/105706562/198824526-cee517e1-36da-42c7-847e-402de98f462e.png)

**Comment by redleafnew** [comment]
除了用图表示之外，列表说一下：
1.
2.
....
方便逐条修改。

**Comment by chujiuzz** [comment]
1、页码表示的“~”改为“-”
2、年份紧跟作者后面且将前后的“**，**“    改为”**.**”
3、中文文献在前，需要翻译为英文，文献译文与文献原文共用一个引文编号。并在译文结尾加注“（In Chinese）”。
4、英文翻译的中文作者姓前名后，姓氏全拼大写，名字首字母大写，姓、名间仅空一个字符，没有其他的标点符号
5、作者之间（中、英同）以及作者和年份之间，均为逗号（，）；年份后用句号（.）
6、期刊文献的文章标题只有标题和副标题的首词首字母大写，其余单词均小写；
7、期刊名首词首字母大写，其余单词均小写

要求比较繁琐，麻烦了，谢谢

**Comment by redleafnew** [comment]
@zepinglee 请调整权限。
另外我的常用ID是：johnmy。我可以调别人权限吗？

**Comment by redleafnew** [comment]
已经添加权限，
@chujiuzz 请在添加“营销科学学报”分类（文件夹），将例子录入到分类中，方便对照。

**Comment by redleafnew** [comment]
- [ ]页码表示的“~”改为“-”
2、年份紧跟作者后面且将前后的“，“ 改为”.”
3、中文文献在前，需要翻译为英文，文献译文与文献原文共用一个引文编号。并在译文结尾加注“（In Chinese）”。
4、英文翻译的中文作者姓前名后，姓氏全拼大写，名字首字母大写，姓、名间仅空一个字符，没有其他的标点符号
5、作者之间（中、英同）以及作者和年份之间，均为逗号（，）；年份后用句号（.）
6、期刊文献的文章标题只有标题和副标题的首词首字母大写，其余单词均小写；
7、期刊名首词首字母大写，其余单词均小写

**Comment by zepinglee** [comment]
<img width="910" alt="Screen Shot 2022-10-29 at 18 12 52" src="https://user-images.githubusercontent.com/12290822/198825887-97dd586c-b5c1-4177-a968-63d2d7490320.png">

> @zepinglee 请调整权限。 另外我的常用ID是：johnmy。我可以调别人权限吗？

应该也是可以的，毕竟 admin 权限。

<img width="903" alt="Screen Shot 2022-10-29 at 18 14 42" src="https://user-images.githubusercontent.com/12290822/198826002-98943fb6-c65c-414a-b781-0011a903ab42.png">

**Comment by redleafnew** [comment]
谢谢。我用另一个账号调整了一下，发现是可以的。

**Comment by chujiuzz** [comment]
已添加，麻烦了

**Comment by zepinglee** [comment]
这个要不要改成跟 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/84#issuecomment-1288105046> 一一样使用 `original-author`, `origin-title` 等字段？

**Comment by redleafnew** [comment]
> 这个要不要改成跟 [#84 (comment)](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/84#issuecomment-1288105046) 一一样使用 `original-author`, `origin-title` 等字段？

我觉得以后就按这样来搞吧

**Comment by redleafnew** [comment]
> 已添加，麻烦了

需要添加图片上的例子方便对照。

**Comment by chujiuzz** [comment]
> 

已重新添加

**Comment by redleafnew** [comment]
@chujiuzz 是不是进行了作者的拆分/合并操作，这在正文中的引用可能会出现问题。

**Comment by chujiuzz** [comment]
@redleafnew 中文文献姓名分开所以用了茉莉花插件进行合并，目前在正文的使用中没有发现问题

**Comment by chujiuzz** [comment]
按照这个
![333](https://user-images.githubusercontent.com/105706562/198835275-805f60aa-d951-49a6-b104-1dd49e5c9b1c.png)

**Comment by redleafnew** [comment]
题目两边的《》或”“是不是都不需要了？

**Comment by chujiuzz** [comment]
是的 ，而且也不用说第几期、第几页，直接显示数字即可

**Comment by redleafnew** [comment]
@zepinglee 
` display="block"` 和 `second-field-align="flush"`在`bibliography`不能共存吗？

` display="block"为了使中文期刊的英文翻译换行。
如果没有`second-field-align="flush"`，序号和作者之间就没有`tab`了，只能用后缀在序号的`]`后面加个空格。

**Comment by zepinglee** [comment]
我记得 https://github.com/citation-style-language/test-suite 有用 `delimiter="&#x0A;"` 表示换行的，不知道在 Word 中行不行。

**Comment by redleafnew** [comment]
```
              <group delimiter="&#x0A;">
               <text macro="serial-information-zh" prefix=", " suffix=". "/>  <!--中文最后的页码  -->
                <text macro="bib-zh"/> <!--翻译的英文  -->
              </group>
```
这样搞个组后好像在Word中也没有换行。

**Comment by redleafnew** [comment]
@chujiuzz 期刊中的卷到底是否显示，两个例子中一个显示了，一个没有。

**Comment by chujiuzz** [comment]
要显示的，没显示的可能是期刊本身提供例子的问题

**Comment by redleafnew** [comment]
@zepinglee 有办法吗？
用这种方式显示翻译的条目有这些问题，
1. 正文中引用显示`（陈国青等，2021）`是对的，但参考文献列表中对应的中文显示全部作者，但翻译的英文要三个作者后显示`et al`，本身这个条目中中文的，应该显示`等`
2. 文末参考文献列表排序一起不对，
用的排序代码：
```
    <sort>
      <key variable="language" sort="ascending"/>
      <key macro="author-intext" sort="descending"/>
      <key macro="issue-date-year" sort="ascending"/>
    </sort>
```
英文是降序，中文是升序，原因未知。
```
（杨国荣，2018）
（陈国青等，2021）
（贾建民等，2020）
（刘雨华和王霞，2022）
（Axon and Jortner，1996）

[1]	Bixon, M, J Jortner. 1996. The Dynamics of Predissociating High Rydberg States of NO, The Journal of Chemical Physics, 105: pp.1363-1382.
[2]	Alford, W. 1995. To Steal a Book Is an Elegant Offense: Intellectual Property Law in Chinese Civilization. Stanford University Press.
[3]	杨国荣. 2018. 信任及其伦理意义，中国社会科学, (3): 45-51. 
杨国荣. 2018. 信任及其伦理意义，中国社会科学, (3): 45-51. (in Chinese)

[4]	陈国青, 张瑾, 王聪, 卫强, 郭迅华. 2021. 《大数据—小数据》问题：以小见大的洞察，管理世界, 37(02): 203-213+14. 
Chen G, Zhang J, Wang C, 等. 2021. The"big data-small data"problem: Insights for the big through the small，Jourmal of management world, 37(02): 203-213+14. (in Chinese)

[5]	贾建民, 耿维, 徐戈, 郝辽钢, 贾轼. 2020. 大数据行为研究趋势:一个《时空关》的视角，管理世界, 36(02): 106-116+221. 
Jia J, Geng W, Xu G, 等. 2020. Big data behavioral research trends: A time-space-connection perspective，Journal of management world, 36(02): 106-116+221. (in Chinese)

[6]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用，营销科学学报, 2(03): 18-40. 
Liu Y, Wang X. 2022. The Impact of Brand-related User-Generated Content’s Functional Appeal on Consumers’Social Media Engagement: The Moderating Role，营销科学学报, 2(03): 18-40. (in Chinese)



```

**Comment by redleafnew** [comment]
```
[6]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用，营销科学学报, 2(03): 18-40. 
Liu Y, Wang X. 2022. The Impact of Brand-related User-Generated Content’s Functional Appeal on Consumers’Social Media Engagement: The Moderating Role，营销科学学报, 2(03): 18-40. (in Chinese)
```
这个条目一直无法调用 `original-container-title: Journal of Marketing Science`

**Comment by redleafnew** [comment]
> ```
> [6]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用，营销科学学报, 2(03): 18-40. 
> Liu Y, Wang X. 2022. The Impact of Brand-related User-Generated Content’s Functional Appeal on Consumers’Social Media Engagement: The Moderating Role，营销科学学报, 2(03): 18-40. (in Chinese)
> ```
> 
> ！！这个条目一直无法调用 `original-container-title: Journal of Marketing Science`

这个解决了。是翻译的题目中有回车。

**Comment by redleafnew** [comment]
@chujiuzz 文末的参考文献列表是按什么进行排序的。

**Comment by chujiuzz** [comment]
首字母排序，但是中文在前，英文在后，且前面加序号

**Comment by redleafnew** [comment]
1. 正文中引用显示`（陈国青等，2021）`这个括号是中文括号还是英文的？

**Comment by chujiuzz** [comment]
没有规定，但是看起来像是中文的

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/198878545-b0178119-afec-4d47-bdf6-47cb443d5ef6.png)
@chujiuzz 麻烦你在测试文件夹中，点击一下creator或作者，按作者一下序，感觉我的不大对头，怎么Zotero中也是中文作者升序，英文就降序；中文降序英文就升序，正好相反。

**Comment by chujiuzz** [comment]
已排序

**Comment by chujiuzz** [comment]
![111](https://user-images.githubusercontent.com/105706562/198879081-52266cfb-4da7-4a7e-a717-8e51630221dc.png)

**Comment by redleafnew** [comment]
你将Zotero界面语言切换到英文再试一下。

**Comment by chujiuzz** [comment]
![222](https://user-images.githubusercontent.com/105706562/198879874-fca8a8b8-4f23-4e70-a0f8-02a54d4afff4.png)
yingwensh英文是这样 感觉需要用中文版

**Comment by zepinglee** [comment]
> @zepinglee 有办法吗？ 用这种方式显示翻译的条目有这些问题，
> 
> 1. 正文中引用显示`（陈国青等，2021）`是对的，但参考文献列表中对应的中文显示全部作者，但翻译的英文要三个作者后显示`et al`，本身这个条目中中文的，应该显示`等`

`<et-al term="...">` 可以选择显示的 term。

> 2. 文末参考文献列表排序一起不对，
>    用的排序代码：
> 
> ```
>     <sort>
>       <key variable="language" sort="ascending"/>
>       <key macro="author-intext" sort="descending"/>
>       <key macro="issue-date-year" sort="ascending"/>
>     </sort>
> ```
> 英文是降序，中文是升序，原因未知。
> 
> ```
> （杨国荣，2018）
> （陈国青等，2021）
> （贾建民等，2020）
> （刘雨华和王霞，2022）
> （Axon and Jortner，1996）
> 
> [1]	Bixon, M, J Jortner. 1996. The Dynamics of Predissociating High Rydberg States of NO, The Journal of Chemical Physics, 105: pp.1363-1382.
> [2]	Alford, W. 1995. To Steal a Book Is an Elegant Offense: Intellectual Property Law in Chinese Civilization. Stanford University Press.
> [3]	杨国荣. 2018. 信任及其伦理意义，中国社会科学, (3): 45-51. 
> 杨国荣. 2018. 信任及其伦理意义，中国社会科学, (3): 45-51. (in Chinese)
> 
> [4]	陈国青, 张瑾, 王聪, 卫强, 郭迅华. 2021. 《大数据—小数据》问题：以小见大的洞察，管理世界, 37(02): 203-213+14. 
> Chen G, Zhang J, Wang C, 等. 2021. The"big data-small data"problem: Insights for the big through the small，Jourmal of management world, 37(02): 203-213+14. (in Chinese)
> 
> [5]	贾建民, 耿维, 徐戈, 郝辽钢, 贾轼. 2020. 大数据行为研究趋势:一个《时空关》的视角，管理世界, 36(02): 106-116+221. 
> Jia J, Geng W, Xu G, 等. 2020. Big data behavioral research trends: A time-space-connection perspective，Journal of management world, 36(02): 106-116+221. (in Chinese)
> 
> [6]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用，营销科学学报, 2(03): 18-40. 
> Liu Y, Wang X. 2022. The Impact of Brand-related User-Generated Content’s Functional Appeal on Consumers’Social Media Engagement: The Moderating Role，营销科学学报, 2(03): 18-40. (in Chinese)
> ```
> 
> > 已排序
> 
> 不是，你点一下截图一下。我看看和我的是不是一样。

`<key macro="author-intext" sort="descending"/>` 导致的降序。需要改成默认的 `ascending`。

**Comment by zepinglee** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/198878545-b0178119-afec-4d47-bdf6-47cb443d5ef6.png) @chujiuzz 麻烦你在测试文件夹中，点击一下creator或作者，按作者一下序，感觉我的不大对头，怎么Zotero中也是中文作者升序，英文就降序；中文降序英文就升序，正好相反。

英文界面的汉字是按照 Unicode 码排序的，不是拼音顺序。中文界面的汉字才会按照拼音排序。

**Comment by redleafnew** [comment]
> > ![image](https://user-images.githubusercontent.com/22135631/198878545-b0178119-afec-4d47-bdf6-47cb443d5ef6.png) @chujiuzz 麻烦你在测试文件夹中，点击一下creator或作者，按作者一下序，感觉我的不大对头，怎么Zotero中也是中文作者升序，英文就降序；中文降序英文就升序，正好相反。
> 
> 英文界面的汉字是按照 Unicode 码排序的，不是拼音顺序。中文界面的汉字才会按照拼音排序。

如果要实现参考文献列表中文按拼音，英文按字母升序，只能设置 `default-locale-sort="zh-CN"`了

**Comment by redleafnew** [comment]
> `<et-al term="...">` 可以选择显示的 term。

这个好使。
又学习了一招。感谢。

**Comment by redleafnew** [comment]
当前显示效果：

> （刘雨华 等，2022）
> （陈国青 等，2021）
> （贾建民 等，2020）
> （Alford，1995）
> （杨国荣，2018）
> （Bixon and Jortner，1996）
> [1]	陈国青, 张瑾, 王聪, 卫强, 郭迅华. 2021. “大数据—小数据”问题：以小见大的洞察，管理世界, 37(02): 203-213+14. 
> Chen G, Zhang J, Wang C, et al. 2021. The"big data-small data"problem: insights for the big through the small，Jourmal of management world, 37(02): 203-213+14. (in Chinese)
> 
> [2]	贾建民, 耿维, 徐戈, 郝辽钢, 贾轼. 2020. 大数据行为研究趋势:一个“时空关”的视角，管理世界, 36(02): 106-116+221. 
> Jia J, Geng W, Xu G, et al. 2020. Big data behavioral research trends: a time-space-connection perspective，Journal of management world, 36(02): 106-116+221. (in Chinese)
> 
> [3]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用，营销科学学报, 2(03): 18-40. 
> Liu Y, Wang X. 2022. The impact of brand-related user-generated content’s functional appeal on consumers’ social media engagement: the moderating role of the physical attractiveness of the profile picture，Journal of marketing science, 2(03): 18-40. (in Chinese)
> 
> [4]	杨国荣. 2018. 信任及其伦理意义，中国社会科学, 3: 45-51. 
> 杨国荣. 2018. 信任及其伦理意义，中国社会科学, 3: 45-51. (in Chinese)
> 
> [5]	Alford, W. 1995. To steal a book is an elegant offense: intellectual property law in chinese civilization. Stanford University Press.
> [6]	Bixon, M, J Jortner. 1996. The dynamics of predissociating high rydberg states of no, The Journal of chemical Physics, 105: 1363-1382.


存在问题：
1. 中文翻译后面会有空行。
2. 由于`title`使用了`sentence`字母大小写，因此冒号后面的字母，及一些专用的大写名词，如`USA`，`UN`等，会转为小写。如果这样不可接受，可将`title`自行改为合适大小写，`csl`直接调用，不更改大小写。
3. 现在仅测试了期刊，如果需要测试其它文献类型，请上传到群组，并且不要合并作者，并按现存条目的格式，在Extra提供翻译的作者、题目、期刊名称、出版社等。https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/87#issuecomment-1295797063

**Comment by redleafnew** [comment]
> > ![image](https://user-images.githubusercontent.com/22135631/198878545-b0178119-afec-4d47-bdf6-47cb443d5ef6.png) @chujiuzz 麻烦你在测试文件夹中，点击一下creator或作者，按作者一下序，感觉我的不大对头，怎么Zotero中也是中文作者升序，英文就降序；中文降序英文就升序，正好相反。
> 
> 英文界面的汉字是按照 Unicode 码排序的，不是拼音顺序。中文界面的汉字才会按照拼音排序。

@zepinglee 汉字Unicode 码和拼音正好是相反的吗？

**Comment by zepinglee** [comment]
> > > ![image](https://user-images.githubusercontent.com/22135631/198878545-b0178119-afec-4d47-bdf6-47cb443d5ef6.png) @chujiuzz 麻烦你在测试文件夹中，点击一下creator或作者，按作者一下序，感觉我的不大对头，怎么Zotero中也是中文作者升序，英文就降序；中文降序英文就升序，正好相反。
> > 
> > 
> > 英文界面的汉字是按照 Unicode 码排序的，不是拼音顺序。中文界面的汉字才会按照拼音排序。
> 
> @zepinglee 汉字Unicode 码和拼音正好是相反的吗？

不是。CJK 文字有好几个分区，其中最主要的是“中日韩统一表意文字”（CJK Unified Ideographs，U+4E00～U+9FFF），这一块是按照康熙字典排序的（忘记是笔划还是偏旁部首）。

陈（U+9648）、贾（U+8D3E）、刘（U+5218）这三个字恰好在 Unicode 中是倒序。

**Comment by redleafnew** [comment]
多谢。太巧了。
我试了其他几个测试集，有的就和拼音没有关系了。

**Comment by redleafnew** [comment]
@chujiuzz 已经上传到仓库212了。[212journal-of-marketing-science.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/9577c0350eda8995c80866cf986e79b7dcaacab6/212journal-of-marketing-science.csl)

**Comment by chujiuzz** [comment]
<img width="462" alt="333" src="https://user-images.githubusercontent.com/105706562/198884129-e0422274-0008-4753-9593-96a87482247d.png">

更新后有以下问题：
1.中文期刊后存在空行，且自动使用两端对齐，需要手动调整
2、中文期刊的英文翻译是需要我手动添加翻译到短标题还是其他？
3、姓氏的英文没有全部大写（中英文期刊都是）

**Comment by redleafnew** [comment]
> <img alt="333" width="462" src="https://user-images.githubusercontent.com/105706562/198884129-e0422274-0008-4753-9593-96a87482247d.png">
> 
> 更新后有以下问题： 1.中文期刊后存在空行，且自动使用两端对齐，需要手动调整 2、中文期刊的英文翻译是需要我手动添加翻译到短标题还是其他？ 3、姓氏的英文没有全部大写（中英文期刊都是）

1. 在Word设置，应该与csl无关。
2. 参考现在群组中设置的方法：相关信息放入到Extra中。
3. 正文中的作者是否也需要全部写？

**Comment by chujiuzz** [comment]
对于英文文献的著录，论文正文中引用文献时作者要用姓的全拼（首字母大写）；
同样，文末参考文献列表中作者的姓用大写全拼(新规），名字只保留缩写字母且用大写，姓前名后，姓、名间仅空一个字符，没有其他的标点符号

也就是说 上方的“刘雨华”翻译应该是“LIU Y H”，王霞就是“WANG X”

**Comment by redleafnew** [comment]
英文的正文中给个例子。

**Comment by chujiuzz** [comment]
![444](https://user-images.githubusercontent.com/105706562/198885265-8180f5bc-6e34-4bbd-872e-5406006a5934.png)

**Comment by redleafnew** [comment]
作者已经大写，请更新。

**Comment by chujiuzz** [comment]
已更新，辛苦了，谢谢！

**Comment by chujiuzz** [comment]
打扰了，在引用时发现了如下问题：
1、没有代表文献类型的标志，比如 [J] 这种
2、中文文献有三个作者的名字和等之间有空格

这是我的文档中出现的问题：
![222](https://user-images.githubusercontent.com/105706562/199257855-6241775a-9181-4b1e-ab30-ef2540e4df69.png)
![444](https://user-images.githubusercontent.com/105706562/199257879-624f8f4c-a97b-413b-9208-80c2e0d5ef2d.png)

这是期刊中的格式
![111](https://user-images.githubusercontent.com/105706562/199258027-7c5d15a1-68b9-43b8-b32e-eeae1b5b9c96.png)
![333](https://user-images.githubusercontent.com/105706562/199258049-775ac3ba-9903-4b0e-853b-bded2f96b92e.png)

**Comment by redleafnew** [comment]
如果是网络的是否需要加OL

**Comment by redleafnew** [comment]
```
（刘雨华等，2022）
[1]	刘雨华, 王霞. 2022. 用户生成品牌内容的功能性诉求对社交媒体参与度的影响——头像外表吸引力的调节作用[J/OL]，营销科学学报, 2(03): 18-40. 
LIU Y, WANG X. 2022. The impact of brand-related user-generated content’s functional appeal on consumers’ social media engagement: the moderating role of the physical attractiveness of the profile picture[J/OL]，Journal of marketing science, 2(03): 18-40. (in Chinese)

```

**Comment by chujiuzz** [comment]
不用 ，期刊只需要有[ J]即可，但是报告麻烦加上OL，如图
![555](https://user-images.githubusercontent.com/105706562/199375919-b7508f04-90f4-41d8-85c0-10e24e31b693.png)

**Comment by redleafnew** [comment]
报告没有条目测试，请提供。

**Comment by chujiuzz** [comment]
已提供报告

**Comment by redleafnew** [comment]
这两个时间是什么？填写到条目中？报告时间？访问日间？

**Comment by chujiuzz** [comment]
我猜测的一个是报告时间，一个是引用时间

**Comment by redleafnew** [comment]
@chujiuzz 请在条目上补充。

**Comment by redleafnew** [comment]
@zepinglee 
csl中choose, if是可以嵌套的吧。
   ```
 <choose>
            <if is-numeric="edition">
              <group>
                   <choose>
                         <if>
                               ....
                           </if>
                   </choose>
                </group>
            </if>
            <else>
                <text variable="edition"/>
            </else>
        </choose>
```

**Comment by zepinglee** [comment]
> @zepinglee csl中choose, if是可以嵌套的吧。
> 
> ```
> <choose>
>          <if is-numeric="edition">
>            <group>
>                 <choose>
>                       <if>
>                             ....
>                         </if>
>                 </choose>
>              </group>
>          </if>
>          <else>
>              <text variable="edition"/>
>          </else>
>      </choose>
> ```

对，可以嵌套。

**Comment by redleafnew** [comment]
<code>issue</code> 中的 `01`、`08`等，可以显示为`1`、`8`吗？适合`date`中的`numeric-leading-zeros`、`numeric`吗？
`<text variable="issue" form="short" prefix="(" suffix=")"/>` 设置无效。
@zepinglee

**Comment by zepinglee** [comment]
> `issue` 中的 `01`、`08`等，可以显示为`1`、`8`吗？适合`date`中的`numeric-leading-zeros`、`numeric`吗？ `<text variable="issue" form="short" prefix="(" suffix=")"/>` 设置无效。 @zepinglee

这个在 CSL 中实现不了，只能修改原字段信息。

早期知网没处理期号中的 0，导致会录入 `01` 这样的信息。现在已经修改过来了。

**Comment by redleafnew** [comment]
> 不用 ，期刊只需要有[ J]即可，但是报告麻烦加上OL，如图 ![555](https://user-images.githubusercontent.com/105706562/199375919-b7508f04-90f4-41d8-85c0-10e24e31b693.png)

这个报告作者英文翻译不是全部大写啊，

**Comment by chujiuzz** [comment]
这是之前的文献，今年9月新规要求全部大写，新规定下的文章还没发出来

**Comment by redleafnew** [comment]
> > `issue` 中的 `01`、`08`等，可以显示为`1`、`8`吗？适合`date`中的`numeric-leading-zeros`、`numeric`吗？ `<text variable="issue" form="short" prefix="(" suffix=")"/>` 设置无效。 @zepinglee
> 
> 这个在 CSL 中实现不了，只能修改原字段信息。
> 
> 早期知网没处理期号中的 0，导致会录入 `01` 这样的信息。现在已经修改过来了。
写个了删除代码：
https://github.com/redleafnew/zotero-javascripts/blob/b809a14af1d34316404a591c0402dc6099e165c6/24remove-starting-zotero-in-issue.js

**Comment by redleafnew** [comment]
> 这是之前的文献，今年9月新规要求全部大写，新规定下的文章还没发出来

已更新，添加了两个日期。

**Comment by zepinglee** [comment]
> 不用 ，期刊只需要有[ J]即可，但是报告麻烦加上OL，如图 ![555](https://user-images.githubusercontent.com/105706562/199375919-b7508f04-90f4-41d8-85c0-10e24e31b693.png)

这是期刊官网提供的样式吗？

按照国标，这个“/OL”是在有 URL 或者 DOI 时才写的。这里没有 URL，“/OL”以及引用日期就显得有些矛盾。

**Comment by chujiuzz** [comment]
是的，这是已经刊出的文献后面的引用

**Comment by zepinglee** [comment]
> 是的，这是已经刊出的文献后面的引用

我感觉这里作者和编辑处理不过严谨，没必要按照这个格式。

**Comment by chujiuzz** [comment]
发现了一个问题，作者名字有三个字的时候大写显示不完全 LIU Y H 只有 LIU Y 了
![111](https://user-images.githubusercontent.com/105706562/199483567-1f7a249f-8c69-4822-9f3a-9c67cea9b366.png)

**Comment by zepinglee** [comment]
> 发现了一个问题，作者名字有三个字的时候大写显示不完全 LIU Y H 只有 LIU Y 了 ![111](https://user-images.githubusercontent.com/105706562/199483567-1f7a249f-8c69-4822-9f3a-9c67cea9b366.png)

这个问题 CSL 没法处理，只能将英文的名分开：Liu || Yu Hua

**Comment by redleafnew** [comment]
@zepinglee @northword @l0o0
我想写一个判断条目为中文或英文的代码，用哪个字段比较合适呢？
初步想法期刊用期刊名称，其它用题目。如果这两个字段是中文，就把语言字段设置为zh-CN，否则设置为en-US，当然其它语言也会有但不多。

**Comment by zepinglee** [comment]
> @zepinglee @northword @l0o0 我想写一个判断条目为中文或英文的代码，用哪个字段比较合适呢？ 初步想法期刊用期刊名称，其它用题目。如果这两个字段是中文，就把语言字段设置为zh-CN，否则设置为en-US，当然其它语言也会有但不多。

建议都用标题吧。印象中又的期刊既有中文文章又有英文文章。

参考 <https://github.com/l0o0/jasminum/pull/105>。

**Comment by redleafnew** [comment]
> > @zepinglee @northword @l0o0 我想写一个判断条目为中文或英文的代码，用哪个字段比较合适呢？ 初步想法期刊用期刊名称，其它用题目。如果这两个字段是中文，就把语言字段设置为zh-CN，否则设置为en-US，当然其它语言也会有但不多。
> 
> 建议都用标题吧。印象中又的期刊既有中文文章又有英文文章。
> 
> 参考 [l0o0/jasminum#105](https://github.com/l0o0/jasminum/pull/105)。

既然茉莉花有这个功能了，那我就不搞了。

**Comment by zepinglee** [comment]
简单粗暴版： `item.title.match([/\u4e00-\u9fa5]/) ? 'zh-CN' : 'en-US'`。对于绝大部分人够用了。

**Comment by redleafnew** [comment]
> 简单粗暴版： `item.title.match([/\u4e00-\u9fa5]/) ? 'zh-CN' : 'en-US'`。对于绝大部分人够用了。

是的，少数也有中文期刊发表英文文章的。所以才想用期刊名判断。

**Comment by redleafnew** [comment]
> > 有的期刊既有中文文章又有英文文章
> 
> 印象中这种期刊一般都是分中文版和英文版，期刊名也是分别是中文和英文？ 用标题的话，如果用正则表达式去判断字符集，如果标题里含有拉丁字符或者其他语言的字符（例如 α 之类的），这样会不会干扰判断呢？（我不大了解这个）
> 
> > 如果这两个字段是中文，就把语言字段设置为zh-CN，否则设置为en-US，当然其它语言也会有但不多。
> 
> 其他语言有没有可能通过第三方库或 API 来支持？例如：https://denghao.me/index.php/archives/language-detection.html 不过这样就只能集成到插件里了，不能写成单独的 js 片段粘贴运行。

是想集成到插件，现在茉莉花已经有这个功能了。

**Comment by redleafnew** [comment]
> 'zh-CN' : 'en-US'
放入
https://github.com/redleafnew/delitemwithatt/releases/tag/0.0.19
中，右键一级菜单。

**Comment by redleafnew** [comment]
如无进一步反馈，本issue将关闭。

**Comment by YUKITOfoxx** [comment]
大佬您好，我运用了您之前开发的管理世界的格式，然后出现了一个小问题，就是我的参考文献英文出现了两个a-z的序列，请问怎么解决呀？问题如下：
<img width="407" alt="截屏2022-11-07 23 39 21" src="https://user-images.githubusercontent.com/115545817/200351482-e04ebe55-f3fa-4954-9cfc-3bbf9c4c4ab3.png">

**Comment by zepinglee** [comment]
> 大佬您好，我运用了您之前开发的管理世界的格式，然后出现了一个小问题，就是我的参考文献英文出现了两个a-z的序列，请问怎么解决呀？问题如下：
> 
> <img alt="截屏2022-11-07 23 39 21" width="407" src="https://user-images.githubusercontent.com/115545817/200351482-e04ebe55-f3fa-4954-9cfc-3bbf9c4c4ab3.png">

新开 issue 讨论，将这几篇文献导出为 CSL 格式贴在 issue 中。

**Comment by YUKITOfoxx** [comment]
您好，徐宇佳已经收到啦，我将尽快给您答复。
