### ISSUE TITLE
pandoc导出md为docx，为什么用选择支持双语的csl就会参考文献就会重复出现条目呀

### ISSUE THREAD

**Issue by Achuan-2** [redleafnew/Chinese-STD-GB-T-7714-related-csl#88]
![Snipaste_2022-10-30_11-22-42](https://user-images.githubusercontent.com/60436214/198861089-1d208e4e-dc80-4205-949f-370f2014d1a5.png)
同时想问问能不能直接通过添加bib字段，来让csl识别语言

**Comment by zepinglee** [comment]
同 <https://github.com/jgm/citeproc/issues/120#issuecomment-1290038742>，pandoc 的 citeproc 不支持 多语言的 layout。

**Comment by Achuan-2** [comment]
感谢感谢，我现在的做法是
* 把csl里的layout进行注释

  ```xml
  <bibliography entry-spacing="0" et-al-min="4" et-al-use-first="3" second-field-align="flush">
    <!-- 取消这部分注释可以使用 CSL-M 的功能支持双语 -->
    <!-- <layout suffix="." locale="en">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout"/>
    </layout> -->
    <layout suffix=".">
      <text variable="citation-number" prefix="[" suffix="]"/>
      <text macro="entry-layout"/>
    </layout>
  </bibliography>
  ```
* 把zh-CN替换为en-US

这样就可以支持GB7714引用英文文献啦，虽然不支持中文文献的导入，但是没关系，天坑专业一般也不会去引用中文文献……
![image](https://user-images.githubusercontent.com/60436214/198862349-6bea11f5-69bd-4e30-baa9-203c93750706.png)
