### ISSUE TITLE
请问013样式如何修改使文末的[1]缩进？

### ISSUE THREAD

**Issue by tigerwang1998** [redleafnew/Chinese-STD-GB-T-7714-related-csl#89]
**描述错误**

CSL 样式：[013gb-t-7714-2015-numeric-aulower-bilan-ce.csl]

中英对照的csl默认没有缩进，请问如何修改可以使其产生缩进？

**Comment by redleafnew** [comment]
截图说明一下？

**Comment by tigerwang1998** [comment]
您好，邮件已收到。
 久等不回或急事请电话联系。

**Comment by tigerwang1998** [comment]
比如用通用格式就是悬挂缩进，但是如果想增加英文对照翻译（比如013样式），就没有出现悬挂缩进。自己手动设置悬挂缩进总是对不齐，中文缩进对齐了英文就对不齐。
![1](https://user-images.githubusercontent.com/50581765/198955480-e970ed16-774f-4300-8685-704a9b5fdaeb.jpg)
![2](https://user-images.githubusercontent.com/50581765/198955492-9cb2a811-915d-4ca1-bf76-26a1db7a3cf6.jpg)
![3](https://user-images.githubusercontent.com/50581765/198955498-1deae95d-82aa-4802-84a6-0923c0dcce42.jpg)

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by tigerwang1998** [comment]
网页版拖动不过去咋整，从my library拖动到群组的时候鼠标指针变成了不可拖放的状态（一个圈圈+反斜杠的图案）

**Comment by redleafnew** [comment]
Zotero ID是什么，需要调整为Admin权限才可以添加条目。

**Comment by tigerwang1998** [comment]
> 

bjfuwangxin

**Comment by redleafnew** [comment]
已经给予权限。

**Comment by tigerwang1998** [comment]
已上传2英文1中文，共3篇测试文献至“测试”文件夹

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/198965427-a331b04a-9a73-46d1-8d42-c52d8cd8d54f.png)
可以设置悬挂

**Comment by tigerwang1998** [comment]
但是显然每个段落中，第一行与其余行没有对齐。比如第一篇引用中，首行的K和次行的N不在同一条垂直线上。

**Comment by redleafnew** [comment]
已更新csl，再试试

**Comment by tigerwang1998** [comment]
请问更新的csl是需要我重新在github上下载，然后再重新导入到zotero吗？还是我只需要刷新一下zotero即可？

**Comment by redleafnew** [comment]
重新下载，再安装。

**Comment by tigerwang1998** [comment]
经过测试，更新后的csl013，可以在应用该格式后，全选参考文献部分并设置悬挂缩进2字符。非常感谢您的更新！向您致敬！
