### ISSUE TITLE
能否加入华中农业大学的参考文献的首字母排序代码，谢谢

### ISSUE THREAD

**Issue by ljm1218** [redleafnew/Chinese-STD-GB-T-7714-related-csl#90]
**样式信息**

- 期刊/学校：

- 英文名称：

- 期刊/学校官网链接：

- ISSN 号：

- 参考文献格式要求的链接：

**测试条目**

将期刊/学校官网的示例文献全部录入 Zotero 群组“[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development)”，用于测试、比对 CSL 样式的输出结果。

Zotero ID:

**其他样式信息**

**Comment by redleafnew** [comment]
现在有华中农大的csl，请详细指出问题，并提供测试条目。
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
如无进一步反馈，本issue将关闭。

**Comment by redleafnew** [comment]
c2513de8a5883e5e82530d6047c9c94851262da7
