### ISSUE TITLE
国标的脚注能不能支持每页重新编号

### ISSUE THREAD

**Issue by AchanRao** [redleafnew/Chinese-STD-GB-T-7714-related-csl#92]
国标numeric样式

按照语言显示“等”或“et al.”；
姓名取消全大写。
每页重新编号，且重复文献显示第一次出现的页码

**Comment by redleafnew** [comment]
用得哪个csl？
 数字格式的不会出现脚注的。
第三条举个例子。

**Comment by redleafnew** [comment]
如无进一步反馈，本issue即将关闭。
