### ISSUE TITLE
两位老师好，在添加引用格式的时候报错了，然后尝试加入styles文件夹中，还是不行，请问该怎么解决呢？

### ISSUE THREAD

**Issue by YUKITOfoxx** [redleafnew/Chinese-STD-GB-T-7714-related-csl#93]
**描述错误**

CSL 样式：
202journal-of-management-world.csl

清晰简洁地描述错误是什么，预期的结果是什么。

**屏幕截图**

<img width="472" alt="截屏2022-11-15 21 55 13" src="https://user-images.githubusercontent.com/115545817/201937391-6516db2c-562a-45c0-88aa-bcc73dd10546.png">
<img width="446" alt="截屏2022-11-15 21 55 47" src="https://user-images.githubusercontent.com/115545817/201937406-dcf2cc2e-798c-45a1-a2aa-54f687bbacf1.png">

**Comment by zepinglee** [comment]
正常应该是这样的警告：
<img width="693" alt="Screen Shot 2022-11-15 at 22 06 10" src="https://user-images.githubusercontent.com/12290822/201939548-0c62fb4d-0727-4c0e-82db-620167623b5c.png">

你是怎么下载的？

**Comment by YUKITOfoxx** [comment]
直接下载您这的整个安装包，然后选了202

**Comment by YUKITOfoxx** [comment]
刚刚试了一下别的格式，是可以的导入的，只有管理世界不行😭，会是因为之前导入过一个管理世界格式吗？删掉原来的格式并且重启zotero和word，并把之前的文章格式修改掉，还是不能添加进去...

**Comment by zepinglee** [comment]
原来是这里的 merge conflict 没有解决。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/760779a43d15e8fc936f198ad51f8e4912f618f8/202journal-of-management-world.csl#L340-L343

@redleafnew 有时合并时会有冲突，这种需要手动解决再 `git commit`。

**Comment by redleafnew** [comment]
> 原来是这里的 merge conflict 没有解决。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/760779a43d15e8fc936f198ad51f8e4912f618f8/202journal-of-management-world.csl#L340-L343
> 
> @redleafnew 有时合并时会有冲突，这种需要手动解决再 `git commit`。

好的，没有注意到这个冲突。

**Comment by zepinglee** [comment]
如果使用命令行的话，合并冲突一般会提示。参考 <https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%88%86%E6%94%AF%E7%9A%84%E6%96%B0%E5%BB%BA%E4%B8%8E%E5%90%88%E5%B9%B6#_basic_merge_conflicts>。

```
$ git merge 44a2c46
Auto-merging 202journal-of-management-world.csl
CONFLICT (content): Merge conflict in 202journal-of-management-world.csl
Automatic merge failed; fix conflicts and then commit the result.
$ git st
On branch tmp
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	copied:     .github/ISSUE_TEMPLATE/feature_request.md -> .gitee/ISSUE_TEMPLATE.zh-CN.md
	modified:   .github/ISSUE_TEMPLATE/bug_report.md
	modified:   .github/ISSUE_TEMPLATE/feature_request.md
	modified:   107chinese-journal-of-cardiology.csl
	modified:   110food-science.csl
	modified:   111acta-agriculurae-boreali-sinica.csl
	modified:   207chinas-industrial-economics.csl
	modified:   212journal-of-marketing-science.csl
	modified:   213scientia-agricultura-sinica.csl
	new file:   214studies-of-marxism.csl
	modified:   301manual-of-legal-citation-multi-lingual.csl
	modified:   306manual-of-legal-citation-multi-lingual-no-ibid.csl
	modified:   404jnu-thesis.csl
	modified:   415zju-thesis.csl
	modified:   422caas-thesis.csl
	modified:   README.md

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   202journal-of-management-world.csl
```

**Comment by YUKITOfoxx** [comment]
两位老师好，打扰了，关于管理世界的格式我又发现以下几点问题：

以下两条截图来自管理世界投稿格式 http://www.mwm.net.cn/Web/Format
1、
<img width="547" alt="截屏2022-11-17 12 09 10" src="https://user-images.githubusercontent.com/115545817/202353314-8a419eea-57f1-45b7-a1e2-427157034e5b.png">
<img width="690" alt="截屏2022-11-17 12 09 28" src="https://user-images.githubusercontent.com/115545817/202353590-986abf42-373a-4897-9e1c-6cf5666e57fd.png">
目前csl中 两个英文作者中间是”&“，而参考文献中的两个作者是”，“

2、
<img width="703" alt="截屏2022-11-17 12 09 33" src="https://user-images.githubusercontent.com/115545817/202353680-070fe1a5-1094-479f-bb38-6cd622b6f36f.png">
目前csl中 参考文献期刊编号号缺少”vol“

3、本条截图来自我的参考文献
<img width="644" alt="截屏2022-11-17 12 14 51" src="https://user-images.githubusercontent.com/115545817/202353772-1f22e828-0a63-487f-8042-21ec478c327e.png">
目前csl中 未出版仅仅在线发表的文献号会被识别为页码

**Comment by zepinglee** [comment]
@YUKITOfoxx 在新 issue #95 中讨论吧。
