### ISSUE TITLE
申请增加哈尔滨理工大学的学位论文样式

### ISSUE THREAD

**Issue by ambition-xx** [redleafnew/Chinese-STD-GB-T-7714-related-csl#94]
**样式信息**

- 期刊/学校：哈尔滨理工大学

- 英文名称：

- 相关领域：

- 期刊/学校官网链接：http://www.hrbust.edu.cn/
- 【金山文档】 附件1：哈尔滨理工大学研究生学位论文撰写范例（2021版）
https://kdocs.cn/l/capyy3CK23er

- ISSN 号：

- 参考文献格式要求的链接：http://graduate.hrbust.edu.cn/info/1245/5420.htm

**测试条目**

加入 Zotero 群组[Chinese CSL development](https://www.zotero.org/groups/4677213/chinese_csl_development，提供Zotero ID，赋予编辑权限后，将**期刊/学校官网的示例文献**条目录入 Zotero 并拖动到群组中，方便测试。

Zotero ID：ambition.xx

**其他样式信息**

**Comment by redleafnew** [comment]
已赋予管理权限，
1. 请将撰写范例16-18页中的条目每种文献类型选择一个录入到群组，或导出json文件（所有条目导出为一个，不要每个条目一个json文件）。
2. 看看与仓库中现在哪个csl最类似，在上面基础上修改更方便、快捷。

**Comment by ambition-xx** [comment]
1. 已经录进去了，但是有几个日文、俄文的参考文献找不到，还有几个英语期刊知网上没有，也没导进去。
2. 和这个最相似”[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)“
> 书目的样式(悬挂缩进)是在word中设置，而不是在样式表中设置，对吗？

**Comment by redleafnew** [comment]
> 1. 已经录进去了，但是有几个日文、俄文的参考文献找不到，还有几个英语期刊知网上没有，也没导进去。
> 2. 和这个最相似”[002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/002gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl)“
> 
> > 书目的样式(悬挂缩进)是在word中设置，而不是在样式表中设置，对吗？

有常用文献类型即可，
它与002这个csl主要区别是什么，麻烦详细列出。

缩进需要在Word中操作。

**Comment by ambition-xx** [comment]
国标7714-2015是这样：
[1]姜锡洲. 一种温热外敷药的制备方法[P]. 上海市：CN1019452B,1992-12-16.
学校要求是这样：
[17]	姜锡洲. 一种温热外敷药制备方案: 中国, 88105607.3[P]. 1989-07-26 [2017-04-02].
专利文献：序号└┘专利申请者或所有者. 专利题名: 专利国别, 专利号[P]. 公告日期或公开日期[引用日期].
（└┘表示一个空格）

国标7714-2015是这样：
[1]何正嘉. 机械故障诊断理论及应用[M]. 高等教育出版社, 2010.
学校要求是这样：
[9]	何正嘉, 陈进, 王太勇, 等. 机械故障诊断理论及应用[M]. 北京: 高等教育出版社, 2010: 1-3, 31-41.
中文专著（书）：序号└┘作者. 书名[M]. 出版地: 出版商, 出版年: 引用部分起止页码.
注：作者多于三位加“, 等”。对不同页码的内容进行引用时，起止页码可分开连续给出，中间用“,”隔开。


由于我对002样式中不太熟，所以我也不太清楚学校的要求中和002样式有什么不同，上面的两条是我识别出的和国标不太一样的地方。其他的有待继续识别。

**Comment by redleafnew** [comment]
> [17] 姜锡洲. 一种温热外敷药制备方案: 中国, 88105607.3[P]. 1989-07-26 [2017-04-02].

这个专利你的测试条目中没有

**Comment by redleafnew** [comment]
> [1]何正嘉. 机械故障诊断理论及应用[M]. 高等教育出版社, 2010.

这个条目的作者只有一个，要显示页码，可以在Extra中输入： Pages: 1-3, 31-41

**Comment by redleafnew** [comment]
https://www.jianguoyun.com/p/DdVlOKIQtOD-BRjWyuYEIAA 
可以试一下效果。

**Comment by ambition-xx** [comment]
> 一种温热外敷药制备方案

已加入

**Comment by redleafnew** [comment]
专利中需要输入Place，访问时间，否则最终不显示。

**Comment by redleafnew** [comment]
条目的语言需要设置，中文设置为zh-CN，英文en-US，否则无法正确显示“等”和“et al”

**Comment by ambition-xx** [comment]
![image](https://user-images.githubusercontent.com/37329475/228765441-a57f6d70-b710-4e96-b9dd-8ea870fa7a5a.png)
实词首字母大写可以帮忙设置一下吗，条目我已经录入了。
