### ISSUE TITLE
请求在word中用zotero插入文献时，后面的references能够按照时间排序

### ISSUE THREAD

**Issue by realxieyingjun** [redleafnew/Chinese-STD-GB-T-7714-related-csl#96]
请求在word中用zotero插入参考文献时，后面的references能够按照时间新旧排序，谢谢

**Comment by redleafnew** [comment]
现在用得哪个csl？
提供几个条目的过来。

把几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
请进一步提供相关信息，否则本issue将关闭。
