### ISSUE TITLE
关于212营销科学学报格式的错误

### ISSUE THREAD

**Issue by chujiuzz** [redleafnew/Chinese-STD-GB-T-7714-related-csl#98]
**描述错误**

CSL 样式：212journal-of-marketing-science.csl

清晰简洁地描述错误是什么，预期的结果是什么。
1、期刊要求中作者的姓用大写全拼，名字只保留缩写字母且用大写，姓前名后，姓、名间仅空一个字符，没有其他的标点符号，但是我的格式是**只有第一作者是姓前名后**，其他作者均为**姓后名前**，且姓和名之间**有标点符号**。
2、中文文献英文翻译后加“In Chinese”，但我的in是小写
**屏幕截图**
![111](https://user-images.githubusercontent.com/105706562/204125082-d1e10fe4-7c86-4325-bcc0-3c05a81651c9.png)
![222](https://user-images.githubusercontent.com/105706562/204125107-28ab885c-cd61-4d94-99f8-7a84aab491b0.png)

如果必要，请添加屏幕截图以帮助解释。

**条目信息**

```json
英文：
[
	{
		"id": "ringlerLookDonTouch2019",
		"type": "article-journal",
		"archive_location": "10 citation(s)",
		"container-title": "Journal of Retailing",
		"DOI": "10.1016/j.jretai.2019.10.007",
		"ISSN": "00224359",
		"issue": "4",
		"journalAbbreviation": "Journal of Retailing",
		"language": "en",
		"page": "186-203",
		"source": "DOI.org (Crossref)",
		"title": "Look but Don’t Touch! The Impact of Active Interpersonal Haptic Blocking on Compensatory Touch and Purchase Behavior",
		"URL": "https://linkinghub.elsevier.com/retrieve/pii/S0022435919300661",
		"volume": "95",
		"author": [
			{
				"family": "Ringler",
				"given": "Christine"
			},
			{
				"family": "Sirianni",
				"given": "Nancy J."
			},
			{
				"family": "Gustafsson",
				"given": "Anders"
			},
			{
				"family": "Peck",
				"given": "Joann"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					11,
					27
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2019",
					12
				]
			]
		}
	}
]

中文：
[
	{
		"id": "liuXuanZeDuoDuoYiShanXuanZeJiDaXiaoDuiXiaoFeiZheDuoYangHuaXunQiuDeYingXiang2015",
		"type": "article-journal",
		"abstract": "一系列实验发现消费者多样化寻求行为随选择集增大而呈现倒U型变化,这是由于过大选择集情况下消费者倾向于采取启发式信息处理策略导致多样化寻求行为降低。同时,个体的认知需求水平调节选择集大小与多样化寻求行为间的倒U型关系。此外,通过操纵个体认知困难,理论机制进一步得到验证:在认知困难条件下,消费者也会因采用启发式信息处理策略而导致多样化寻求行为显著降低。",
		"container-title": "心理学报",
		"ISSN": "0439-755X",
		"issue": "01",
		"language": "zh-CN",
		"note": "original-author: Liu || Lei\noriginal-author: Zheng || Yu Huang\noriginal-author: Chen || Rui\noriginal-title: Better with More Choices?Impact of Choice Set Size on Variety Seeking\noriginal-container-title: Acta psychologica sinica",
		"page": "66-78",
		"source": "CNKI",
		"title": "选择多多益善?——选择集大小对消费者多样化寻求的影响",
		"title-short": "选择多多益善?",
		"URL": "https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2015&filename=XLXB201501007&uniplatform=NZKPT&v=D-Iiiu_ODZwp_jadCHGhnLt5QDWXzap_p2EiI81FnW5xNPH8pjThHcdZ6bR5wQJW",
		"volume": "47",
		"author": [
			{
				"family": "刘",
				"given": "蕾"
			},
			{
				"family": "郑",
				"given": "毓煌"
			},
			{
				"family": "陈",
				"given": "瑞"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					11,
					27
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2015"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by redleafnew** [comment]
已修改 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/db17828346005f6e3455f7adec7a63b8876e4e54

**Comment by chujiuzz** [comment]
你好刚刚试了一下，英文的姓名还是存在问题，只有第一作者是姓前名后，其他作者均为姓后名前，且姓和名之间有标点符号。这个有办法解决吗？

**Comment by redleafnew** [comment]
[1]	RINGLER, C, SIRIANNI, N J, GUSTAFSSON, A, PECK, J. 2019. Look but don’t touch! the impact of active interpersonal haptic blocking on compensatory touch and purchase behavior[J], Journal of retailing, 95(4): 186-203.

这样？

**Comment by chujiuzz** [comment]
RINGLER C, SIRIANNI N J, GUSTAFSSON A，PECK J

**Comment by redleafnew** [comment]
[1]	刘蕾, 郑毓煌, 陈瑞. 2015. 选择多多益善?——选择集大小对消费者多样化寻求的影响[J]，心理学报, 47(01): 66-78. 
LIU L, ZHENG Y H, CHEN R. 2015. Better with more choices?impact of choice set size on variety seeking[J]，Acta psychologica sinica, 47(01): 66-78. (In Chinese)

[2]	RINGLER C, SIRIANNI N J, GUSTAFSSON A, PECK J. 2019. Look but don’t touch! the impact of active interpersonal haptic blocking on compensatory touch and purchase behavior[J], Journal of retailing, 95(4): 186-203.

**Comment by redleafnew** [comment]
176bc144428bdcbd5a15f69234cd8f9cd6c2623d

**Comment by chujiuzz** [comment]
问题已解决，感谢！
