### ISSUE TITLE
有关011gb-t-7714-2015的问题，非常感谢您！

### ISSUE THREAD

**Issue by neuronsandsynapses** [redleafnew/Chinese-STD-GB-T-7714-related-csl#99]
您好，我现在正在使用的是011gb-t-7714-2015-author-date-bilingual-no-uppercase-no-url-doi-full-width-parentheses，我选这个主要是因为它的括号是全角中文的。
现有三处拜托您帮忙，如果能实现，不胜感激！！期待回复~~

1. 文内目前的效果→期待的效果：（王琴 等, 2021）→（王琴、何赳立，2021）
（前提是文章有两位作者：王琴、何赳立）（希望设置两个作者用顿号隔开，三个及以上采用“等”）
（英文文献的文内引用也是两个作者就用“等”了，可以设置成作者A & 作者B，年份吗）如（Mansfield & Gu, 2017）

2. 文后目前的效果→期待的效果：王琴, 何赳立, 2021. 基础教育教师发展内涵探究[J]. 华南教育信息化研究经验交流会2021论文汇编（五）: 102-107. →→ →→→王琴, 何赳立. 基础教育教师发展内涵探究[J]. 华南教育信息化研究经验交流会2021论文汇编（五）, 2021: 102–107.                                 （主要是年份的位置需要变一下）

3. 三个及以上作者时，“等”前面不要空格。现有格式是（陆财团 等, 2022），希望变成（陆财团等, 2022）

**Comment by redleafnew** [comment]
把这几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。
或
加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

**Comment by redleafnew** [comment]
这是哪个学校或期刊的要求？

**Comment by neuronsandsynapses** [comment]
> 



> 这是哪个学校或期刊的要求？

您好 我刚刚特意去找了一下 《国际经贸探索》采取的是我想要的格式~

**Comment by neuronsandsynapses** [comment]
> 把这几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。 或 加入Zotero群组，提供Zotero ID，赋予权限后，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4677213/gbt_7714_csl_development

您好 我已经成功进入你给的群组了 但我不知道接下来要怎么做 能说得详细一点吗？ 谢谢~

**Comment by redleafnew** [comment]
提供你的Zotero ID，我来设置一下编辑权限。

**Comment by redleafnew** [comment]
> > 
> 
> > 这是哪个学校或期刊的要求？
> 
> 您好 我刚刚特意去找了一下 《国际经贸探索》采取的是我想要的格式~

提供一下该期刊的信息，如期刊网址，参考文献要求网址等。

**Comment by neuronsandsynapses** [comment]
> 提供你的Zotero ID，我来设置一下编辑权限。

请问就在这里把ID回复给你吗  还是在别的地方

**Comment by neuronsandsynapses** [comment]
> > > 
> > 
> > 
> > > 这是哪个学校或期刊的要求？
> > 
> > 
> > 您好 我刚刚特意去找了一下 《国际经贸探索》采取的是我想要的格式~
> 
> 提供一下该期刊的信息，如期刊网址，参考文献要求网址等。

期刊网址：https://navi.cnki.net/knavi/journals/GJTS/detail?uniplatform=NZKPT

**Comment by redleafnew** [comment]
> > 提供你的Zotero ID，我来设置一下编辑权限。
> 
> 请问就在这里把ID回复给你吗 还是在别的地方

可以，ID不用保密的。

**Comment by redleafnew** [comment]
> > > > 
> > > 
> > > 
> > > > 这是哪个学校或期刊的要求？
> > > 
> > > 
> > > 您好 我刚刚特意去找了一下 《国际经贸探索》采取的是我想要的格式~
> > 
> > 
> > 提供一下该期刊的信息，如期刊网址，参考文献要求网址等。
> 
> 期刊网址：https://navi.cnki.net/knavi/journals/GJTS/detail?uniplatform=NZKPT

这个期刊没有主页，也就是投稿的地址，包括参考文献要求的网址？

**Comment by neuronsandsynapses** [comment]
> > > 提供你的Zotero ID，我来设置一下编辑权限。
> > 
> > 
> > 请问就在这里把ID回复给你吗 还是在别的地方
> 
> 可以，ID不用保密的。

2103800168  如果你能进入我的文献库的话  文章在【BOOK】→【中文格式】

**Comment by neuronsandsynapses** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > 这是哪个学校或期刊的要求？
> > > > 
> > > > 
> > > > 您好 我刚刚特意去找了一下 《国际经贸探索》采取的是我想要的格式~
> > > 
> > > 
> > > 提供一下该期刊的信息，如期刊网址，参考文献要求网址等。
> > 
> > 
> > 期刊网址：https://navi.cnki.net/knavi/journals/GJTS/detail?uniplatform=NZKPT
> 
> 这个期刊没有主页，也就是投稿的地址，包括参考文献要求的网址？

https://gjts.cbpt.cnki.net/WKG/WebPublication/index.aspx?mid=gjts#  这个网址拉到最下面有一个【下载中心】，里面有个文内引用格式下载，是个word文档

**Comment by redleafnew** [comment]
> > > > 提供你的Zotero ID，我来设置一下编辑权限。
> > > 
> > > 
> > > 请问就在这里把ID回复给你吗 还是在别的地方
> > 
> > 
> > 可以，ID不用保密的。
> 
> 2103800168 如果你能进入我的文献库的话 文章在【BOOK】→【中文格式】

https://www.zotero.org/groups/4677213/gbt_7714_csl_development 这个群组中没有你这说的这个ID。

**Comment by neuronsandsynapses** [comment]
> > > > > 提供你的Zotero ID，我来设置一下编辑权限。
> > > > 
> > > > 
> > > > 请问就在这里把ID回复给你吗 还是在别的地方
> > > 
> > > 
> > > 可以，ID不用保密的。
> > 
> > 
> > 2103800168 如果你能进入我的文献库的话 文章在【BOOK】→【中文格式】
> 
> https://www.zotero.org/groups/4677213/gbt_7714_csl_development 这个群组中没有你这说的这个ID。

不好意思  请问我要怎样获得我的ID啊

**Comment by redleafnew** [comment]
Zotero中同步用的账号，加入到群组。
或是把测试用的参考文献导出为json格式，贴到这里也可以，

**Comment by neuronsandsynapses** [comment]
> Zotero中同步用的账号，加入到群组。 或是把测试用的参考文献导出为json格式，贴到这里也可以，

**Comment by neuronsandsynapses** [comment]
> Zotero中同步用的账号，加入到群组。 或是把测试用的参考文献导出为json格式，贴到这里也可以，

我已经加入群组了 但不知道怎么操作  那试试第二种方法吧 
[Exported Items.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10098501/Exported.Items.zip)

**Comment by redleafnew** [comment]
只导出一篇文献？
把这些也导出来吧：
（Mansfield & Gu, 2017）

王琴, 何赳立. 基础教育教师发展内涵探究[J]. 华南教育信息化研究经验交流会2021论文汇编（五）, 2021: 102–107. （主要是年份的位置需要变一下）

（陆财团 等, 2022），希望变成（陆财团等, 2022）

**Comment by redleafnew** [comment]
最好也贴出来打赢显示的效果。

**Comment by redleafnew** [comment]
> > Zotero中同步用的账号，加入到群组。 或是把测试用的参考文献导出为json格式，贴到这里也可以，
> 
> 我已经加入群组了 但不知道怎么操作 那试试第二种方法吧 [Exported Items.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10098501/Exported.Items.zip)

你的Zotero ID在群组中搜不到，2103800168

**Comment by neuronsandsynapses** [comment]
> 只导出一篇文献？ 把这些也导出来吧： （Mansfield & Gu, 2017）
> 
> 王琴, 何赳立. 基础教育教师发展内涵探究[J]. 华南教育信息化研究经验交流会2021论文汇编（五）, 2021: 102–107. （主要是年份的位置需要变一下）
> 
> （陆财团 等, 2022），希望变成（陆财团等, 2022）

稍等一下 我整理一下  谢谢你

**Comment by neuronsandsynapses** [comment]
> 只导出一篇文献？ 把这些也导出来吧： （Mansfield & Gu, 2017）
> 
> 王琴, 何赳立. 基础教育教师发展内涵探究[J]. 华南教育信息化研究经验交流会2021论文汇编（五）, 2021: 102–107. （主要是年份的位置需要变一下）
> 
> （陆财团 等, 2022），希望变成（陆财团等, 2022）

实在是不好意思 让您久等了  这是我第一次引用中文文献 动作很慢 
以下是更多的文章  请查收
[Exported Items (2).zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10098649/Exported.Items.2.zip)

**Comment by neuronsandsynapses** [comment]
> > > Zotero中同步用的账号，加入到群组。 或是把测试用的参考文献导出为json格式，贴到这里也可以，
> > 
> > 
> > 我已经加入群组了 但不知道怎么操作 那试试第二种方法吧 [Exported Items.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/10098501/Exported.Items.zip)
> 
> 你的Zotero ID在群组中搜不到，2103800168

至于我的ID  我再百度一下 到哪里去找 谢谢

**Comment by redleafnew** [comment]
> 二、姓名在括号内的情况
1.中文姓名：
（1）1人：（张三，2020）
（2）2人：（张三、李四，2020）
（3）3人及以上：（张三 等，2020）

下载的Word上，3个及以上是等前是带空格的。

**Comment by redleafnew** [comment]
> 2.英文姓名：
（1）1人：（A，2020）
（2）2人：（A & B，2020）（姓名与&之间要空一格）
（3）3人及以上：(A et al.，2020）

英文的参考文献也给一下吧，1人的，2人的，3人的。

**Comment by redleafnew** [comment]
> 
> （Jiang, 2017; Wang et al., 2020; Bowker & Zhuang, 2017; 金朝辉, 2022; 高磊、鲍晓华, 2022; 李宏、乔越, 2022; 林创伟 等, 2022）
> 
> 高磊, 鲍晓华, 2022. 技术性贸易壁垒对本国出口的影响：理论与实证[J]. 国际经贸探索, 38(11): 20-34.
> 金朝辉, 2022. 人民币汇率、融资约束对出口贸易的影响研究[J]. 国际经贸探索, 38(11): 35-50.
> 李宏, 乔越, 2022. 企业嵌入全球价值链的创新路径选择：“渐进式”抑或“突破式”创新[J]. 国际经贸探索, 38(11): 66-81.
> 林创伟, 白洁, 何传添, 2022. 高标准国际经贸规则解读、形成的挑战与中国应对——基于美式、欧式、亚太模板的比较分析[J]. 国际经贸探索, 38(11): 95-112.
> Bowker, B, Zhuang, H, 2017. Freezing-thawing and sub-sampling influence the marination performance of chicken breast meat1 1The use of trade, firm, or corporation names in this publication is for the information and convenience of the reader. Such use does not constitute an official endorsement or approval by the United States Department of Agriculture or the Agricultural Research Service of any product or service to the exclusion of others that may be suitable.[J]. Poultry Science, 96(9): 3482-3488.
> Jiang, J, 2017. Dietary linseed oil supplemented with organic selenium improved the fatty acid nutritional profile, muscular selenium deposition, water retention, and tenderness of fresh pork[J]. Meat Science, 131: 99-106.
> Wang, H, Qin, X, Li, X, et al., 2020. Effect of chilling methods on the surface color and water retention of yellow-feathered chickens[J]. Poultry Science, 99(4): 2246-2255.

根据我手上的文献生成的效果。

**Comment by neuronsandsynapses** [comment]
> 

这样就可以了 请问我要怎么弄才能达到这个效果呢 十分感谢

**Comment by neuronsandsynapses** [comment]
> > （Jiang, 2017; Wang et al., 2020; Bowker & Zhuang, 2017; 金朝辉, 2022; 高磊、鲍晓华, 2022; 李宏、乔越, 2022; 林创伟 等, 2022）
> > 高磊, 鲍晓华, 2022. 技术性贸易壁垒对本国出口的影响：理论与实证[J]. 国际经贸探索, 38(11): 20-34.
> > 金朝辉, 2022. 人民币汇率、融资约束对出口贸易的影响研究[J]. 国际经贸探索, 38(11): 35-50.
> > 李宏, 乔越, 2022. 企业嵌入全球价值链的创新路径选择：“渐进式”抑或“突破式”创新[J]. 国际经贸探索, 38(11): 66-81.
> > 林创伟, 白洁, 何传添, 2022. 高标准国际经贸规则解读、形成的挑战与中国应对——基于美式、欧式、亚太模板的比较分析[J]. 国际经贸探索, 38(11): 95-112.
> > Bowker, B, Zhuang, H, 2017. Freezing-thawing and sub-sampling influence the marination performance of chicken breast meat1 1The use of trade, firm, or corporation names in this publication is for the information and convenience of the reader. Such use does not constitute an official endorsement or approval by the United States Department of Agriculture or the Agricultural Research Service of any product or service to the exclusion of others that may be suitable.[J]. Poultry Science, 96(9): 3482-3488.
> > Jiang, J, 2017. Dietary linseed oil supplemented with organic selenium improved the fatty acid nutritional profile, muscular selenium deposition, water retention, and tenderness of fresh pork[J]. Meat Science, 131: 99-106.
> > Wang, H, Qin, X, Li, X, et al., 2020. Effect of chilling methods on the surface color and water retention of yellow-feathered chickens[J]. Poultry Science, 99(4): 2246-2255.
> 
> 根据我手上的文献生成的效果。

这样就可以了 请问我要怎么弄才能达到这个效果呢 十分感谢

**Comment by redleafnew** [comment]
c6b082a8ecc39ba6408bfa8f2a27be64ecb4767e

**Comment by neuronsandsynapses** [comment]
> [c6b082a](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/c6b082a8ecc39ba6408bfa8f2a27be64ecb4767e)

刚刚试用了一下 简直完美 太感谢您了 感恩的心ღ( ´･ᴗ･` )

**Comment by neuronsandsynapses** [comment]
不好意思，我发现文内引用的逗号是英文状态下的，如（张慧迪、张力跃, 2020）

请问能换成中文的全角逗号吗？如（张慧迪、张力跃， 2020）

我看了下期刊的要求也是后者

谢谢！

**Comment by redleafnew** [comment]
fbf4182a6d06dfb88940434adfbc4c7be48cc11d

**Comment by neuronsandsynapses** [comment]
> [fbf4182](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/fbf4182a6d06dfb88940434adfbc4c7be48cc11d)

收到！ 感谢！祝您生活愉快~
